package ais.action.master.jurnal;
import java.util.*;import java.util.regex.*;import org.hibernate.*;import org.json.*;
import ais.database.hibernate.HibernateUtil;import ais.database.model.Tbmuser;import ais.database.model.jurnal.TemplateEmailJurnal;
/** Template resolver with variable allowlist; delivery remains through existing MailSender/Notifikasi. */
public final class JurnalEmailService{
 private static final Pattern VARIABLE=Pattern.compile("\\{\\{([A-Za-z][A-Za-z0-9_]*)\\}\\}");private final JurnalAuthorizationService auth=new JurnalAuthorizationService();
 public static final class Rendered{public String subject,body,templateKey,locale;public int version;}
 public TemplateEmailJurnal save(Long journalId,String tenant,String key,String locale,String subject,String body,Set<String> variables,Tbmuser actor){auth.requireCrud(actor,"emailNotifikasi","update");if(!JurnalEmailTemplateCatalog.contains(key))throw new IllegalArgumentException("Key template tidak dikenal.");validateVariables(subject,body,variables);Session s=HibernateUtil.currentSession();Transaction tx=s.getTransaction();boolean own=!tx.isActive();try{if(own)tx.begin();Number n=(Number)s.createQuery("select max(versionNumber) from TemplateEmailJurnal where jurnalPenelitianId=:j and templateKey=:k and locale=:l").setLong("j",journalId).setString("k",key).setString("l",locale).uniqueResult();TemplateEmailJurnal t=new TemplateEmailJurnal();t.setTenantKey(tenant);t.setJurnalPenelitianId(journalId);t.setTemplateKey(key);t.setLocale(locale);t.setSubjectTemplate(subject);t.setBodyTemplate(body);JSONObject policy=new JSONObject();JSONArray a=new JSONArray();for(String v:variables)a.put(v);policy.put("schemaVersion",1);policy.put("allowed",a);t.setVariablePolicyJson(policy.toString());t.setVersionNumber(n==null?1:n.intValue()+1);t.setCreatedBy(actor.getUserId());t.setCreatedAt(new Date());t.setUpdatedAt(new Date());t.setAktif(Boolean.TRUE);s.save(t);if(own)tx.commit();return t;}catch(RuntimeException e){if(own&&tx.isActive())tx.rollback();throw e;}catch(Exception e){if(own&&tx.isActive())tx.rollback();throw new IllegalArgumentException("Template email tidak valid.",e);}}
 public Rendered render(Long journalId,String key,String locale,Map<String,String> values){Session s=HibernateUtil.currentSession();Query q=s.createQuery("from TemplateEmailJurnal where jurnalPenelitianId=:j and templateKey=:k and locale=:l and aktif=true order by versionNumber desc");q.setLong("j",journalId);q.setString("k",key);q.setString("l",locale);q.setMaxResults(1);TemplateEmailJurnal t=(TemplateEmailJurnal)q.uniqueResult();if(t==null)throw new IllegalArgumentException("Template email belum dikonfigurasi.");try{JSONObject p=new JSONObject(t.getVariablePolicyJson());Set<String> allowed=new HashSet<String>();JSONArray a=p.getJSONArray("allowed");for(int i=0;i<a.length();i++)allowed.add(a.getString(i));for(String supplied:values.keySet())if(!allowed.contains(supplied))throw new IllegalArgumentException("Variabel email tidak diizinkan: "+supplied);Rendered r=new Rendered();r.templateKey=key;r.locale=locale;r.version=t.getVersionNumber();r.subject=replace(t.getSubjectTemplate(),values,allowed);r.body=replace(t.getBodyTemplate(),values,allowed);return r;}catch(RuntimeException e){throw e;}catch(Exception e){throw new IllegalArgumentException("Kontrak template email rusak.",e);}}
 private static String replace(String text,Map<String,String> values,Set<String> allowed){Matcher m=VARIABLE.matcher(text==null?"":text);StringBuffer b=new StringBuffer();while(m.find()){String k=m.group(1);if(!allowed.contains(k)||!values.containsKey(k))throw new IllegalArgumentException("Variabel email belum tersedia: "+k);m.appendReplacement(b,Matcher.quoteReplacement(values.get(k)==null?"":values.get(k)));}m.appendTail(b);return b.toString();}
 private static void validateVariables(String s,String b,Set<String> allowed){if(s==null||b==null||s.length()>1000||b.length()>262144)throw new IllegalArgumentException("Ukuran template tidak valid.");Matcher m=VARIABLE.matcher(s+"\n"+b);while(m.find())if(allowed==null||!allowed.contains(m.group(1)))throw new IllegalArgumentException("Variabel tidak diizinkan: "+m.group(1));}
}
