package ais.action.master.jurnal;

import java.text.SimpleDateFormat;
import java.net.URI;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Locale;
import java.util.Set;
import java.util.TimeZone;
import org.json.JSONArray;
import org.json.JSONObject;

/** Clean-room native behavior for public metadata/export/recommendation plugins. */
public final class JurnalPluginParityService {
    private final JurnalPublicService published=new JurnalPublicService();
    public String exportArticle(Long id,String format){return exportArticle(id,format,System.getenv("AIS_JURNAL_PUBLIC_BASE_URL"));}
    public String exportArticle(Long id,String format,String publicBaseUrl){JurnalPublicService.ArticleCard a=published.article(id);if(a==null)return null;String f=clean(format).toLowerCase(Locale.ENGLISH);
        if("native".equals(f))return nativeXml(a);if("doaj".equals(f))return doaj(a,absoluteBase(publicBaseUrl));if("pubmed".equals(f))return pubmed(a);if("jats".equals(f))return jats(a);if("crossref".equals(f))return crossref(a,absoluteBase(publicBaseUrl));if("datacite".equals(f))return datacite(a);throw new IllegalArgumentException("Format ekspor jurnal tidak didukung.");}
    public JSONObject integrityFacts(Long id){JurnalPublicService.ArticleCard a=published.article(id);if(a==null)return null;try{return new JSONObject().put("schemaVersion",1).put("articleId",a.id).put("published",true).put("publishedAt",iso(a.publishedAt)).put("doi",clean(a.doi)).put("metadataComplete",clean(a.title).length()>0&&clean(a.authors).length()>0&&clean(a.abstractText).length()>0).put("withdrawn",false);}catch(Exception e){throw new IllegalStateException(e);}}
    public JSONArray recommendations(Long id,String mode,int limit){JurnalPublicService.ArticleCard source=published.article(id);if(source==null)return null;int n=Math.max(1,Math.min(20,limit));List<JurnalPublicService.ArticleCard> pool=published.latest(200);List<Scored> scored=new ArrayList<Scored>();Set<String> sourceTokens=tokens(source.title+" "+source.abstractText);for(JurnalPublicService.ArticleCard a:pool){if(a.id.equals(id))continue;double score;
            if("author".equalsIgnoreCase(mode))score=authorOverlap(source.authors,a.authors);else if("similarity".equalsIgnoreCase(mode))score=jaccard(sourceTokens,tokens(a.title+" "+a.abstractText));else throw new IllegalArgumentException("Mode rekomendasi tidak dikenal.");if(score>0)scored.add(new Scored(a,score));}
        java.util.Collections.sort(scored,new java.util.Comparator<Scored>(){public int compare(Scored x,Scored y){int c=Double.compare(y.score,x.score);return c!=0?c:y.article.id.compareTo(x.article.id);}});try{JSONArray out=new JSONArray();for(int i=0;i<Math.min(n,scored.size());i++){Scored x=scored.get(i);out.put(new JSONObject().put("id",x.article.id).put("title",clean(x.article.title)).put("score",Math.round(x.score*10000D)/10000D));}return out;}catch(Exception e){throw new IllegalStateException(e);}}
    private static String nativeXml(JurnalPublicService.ArticleCard a){return xmlDecl()+"<ais-journal-article schemaVersion=\"1\"><id>"+a.id+"</id><title>"+xml(a.title)+"</title><authors>"+xml(a.authors)+"</authors><abstract>"+xml(a.abstractText)+"</abstract><language>"+xml(a.language)+"</language><doi>"+xml(a.doi)+"</doi><publishedAt>"+iso(a.publishedAt)+"</publishedAt></ais-journal-article>";}
    private static String doaj(JurnalPublicService.ArticleCard a,String base){String language=iso639(a.language);StringBuilder authors=new StringBuilder();List<String>names=new ArrayList<String>(a.authorNames);if(names.isEmpty()&&clean(a.authors).length()>0)names.addAll(Arrays.asList(clean(a.authors).split("\\s*;\\s*")));for(String name:names)if(clean(name).length()>0)authors.append("<author><name>").append(xml(name)).append("</name></author>");return xmlDecl()+"<records><record><language>"+language+"</language><publisher>"+xml(a.publisher)+"</publisher><journalTitle>"+xml(a.journalTitle)+"</journalTitle>"+(clean(a.issn).length()==0?"":"<issn>"+xml(a.issn)+"</issn>")+"<publicationDate>"+day(a.publishedAt)+"</publicationDate><doi>"+xml(a.doi)+"</doi><publisherRecordId>ais-"+a.id+"</publisherRecordId><documentType>article</documentType><title language=\""+language+"\">"+xml(a.title)+"</title>"+(authors.length()==0?"":"<authors>"+authors+"</authors>")+"<abstract language=\""+language+"\">"+xml(a.abstractText)+"</abstract><fullTextUrl format=\"html\">"+xml(base+"/jurnal/article/"+a.id)+"</fullTextUrl></record></records>";}
    private static String pubmed(JurnalPublicService.ArticleCard a){if(!clean(a.issn).matches("[0-9]{4}-[0-9]{3}[0-9X]"))throw new IllegalArgumentException("ISSN wajib untuk ekspor PubMed.");String year=a.publishedAt==null?"":new SimpleDateFormat("yyyy").format(a.publishedAt);return xmlDecl()+"<!DOCTYPE ArticleSet PUBLIC \"-//NLM//DTD PubMed 3.0//EN\" \"https://dtd.nlm.nih.gov/ncbi/pubmed/in/PubMed.dtd\"><ArticleSet><Article><Journal><PublisherName>"+xml(a.publisher)+"</PublisherName><JournalTitle>"+xml(a.journalTitle)+"</JournalTitle><Issn>"+xml(a.issn)+"</Issn><PubDate PubStatus=\"epublish\"><Year>"+xml(year)+"</Year></PubDate></Journal><ArticleTitle>"+xml(a.title)+"</ArticleTitle>"+pubmedAuthors(a)+"<ArticleIdList><ArticleId IdType=\"doi\">"+xml(a.doi)+"</ArticleId></ArticleIdList><Abstract><AbstractText Label=\"Abstract\">"+xml(a.abstractText)+"</AbstractText></Abstract></Article></ArticleSet>";}
    private static String jats(JurnalPublicService.ArticleCard a){return xmlDecl()+"<article xmlns:xlink=\"http://www.w3.org/1999/xlink\" article-type=\"research-article\"><front><article-meta><article-id pub-id-type=\"doi\">"+xml(a.doi)+"</article-id><title-group><article-title>"+xml(a.title)+"</article-title></title-group><contrib-group><contrib contrib-type=\"author\"><string-name>"+xml(a.authors)+"</string-name></contrib></contrib-group><pub-date><string-date>"+day(a.publishedAt)+"</string-date></pub-date><abstract><p>"+xml(a.abstractText)+"</p></abstract></article-meta></front><body><p>Full text tersedia melalui galley publikasi.</p></body></article>";}
    private static String crossref(JurnalPublicService.ArticleCard a,String base){String year=a.publishedAt==null?"":new SimpleDateFormat("yyyy").format(a.publishedAt);return xmlDecl()+"<doi_batch xmlns=\"http://www.crossref.org/schema/5.3.1\" version=\"5.3.1\"><head><doi_batch_id>ais-"+a.id+"</doi_batch_id><timestamp>"+(a.publishedAt==null?0:a.publishedAt.getTime())+"</timestamp><depositor><depositor_name>eCampus AIS</depositor_name><email_address>noreply@localhost</email_address></depositor><registrant>eCampus AIS</registrant></head><body><journal><journal_metadata><full_title>eCampus AIS Journal</full_title></journal_metadata><journal_article publication_type=\"full_text\"><titles><title>"+xml(a.title)+"</title></titles>"+crossrefContributors(a)+"<publication_date media_type=\"online\"><year>"+xml(year)+"</year></publication_date><doi_data><doi>"+xml(a.doi)+"</doi><resource>"+xml(base+"/jurnal/article/"+a.id)+"</resource></doi_data></journal_article></journal></body></doi_batch>";}
    private static String datacite(JurnalPublicService.ArticleCard a){String year=a.publishedAt==null?"":new SimpleDateFormat("yyyy").format(a.publishedAt);return xmlDecl()+"<resource xmlns=\"http://datacite.org/schema/kernel-4\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"><identifier identifierType=\"DOI\">"+xml(a.doi)+"</identifier><creators><creator><creatorName>"+xml(a.authors)+"</creatorName></creator></creators><titles><title>"+xml(a.title)+"</title></titles><publisher>eCampus AIS</publisher><publicationYear>"+xml(year)+"</publicationYear><resourceType resourceTypeGeneral=\"Text\">JournalArticle</resourceType><descriptions><description descriptionType=\"Abstract\">"+xml(a.abstractText)+"</description></descriptions></resource>";}
    private static double authorOverlap(String a,String b){Set<String>x=tokens(clean(a).replace(';',' '));Set<String>y=tokens(clean(b).replace(';',' '));return jaccard(x,y);}
    private static double jaccard(Set<String>a,Set<String>b){if(a.isEmpty()||b.isEmpty())return 0D;Set<String>i=new HashSet<String>(a);i.retainAll(b);Set<String>u=new HashSet<String>(a);u.addAll(b);return ((double)i.size())/u.size();}
    private static Set<String> tokens(String value){Set<String>out=new HashSet<String>();for(String x:clean(value).toLowerCase(Locale.ENGLISH).split("[^\\p{L}\\p{N}]+"))if(x.length()>2&&!STOP.contains(x))out.add(x);return out;}
    private static final Set<String> STOP=new HashSet<String>(Arrays.asList("dan","yang","the","and","untuk","dengan","dari","this","that","pada"));
    /**
     * Tipe implementasi bersarang {@link Scored} milik {@link JurnalPluginParityService}. Kelas ini memberi nama
     * pada state atau perilaku lokal agar tanggung jawabnya tidak tersebar sebagai blok anonim.
     *
     * <p><b>Scope:</b> tipe bersifat {@code static}; instance tidak menangkap object {@link
     * JurnalPluginParityService}. Dependensi yang diperlukan harus diberikan secara eksplisit agar aman digunakan
     * dan diuji.</p> Tipe ini merupakan detail implementasi privat; pemanggil luar harus memakai API kelas induk.
     * <p>Kontrak yang tampak dari deklarasi ini meliputi state utama: {@code JurnalPublicService.ArticleCard
     * article}, {@code double score}. Aturan bisnis bersama tetap berada pada kelas induk atau service yang
     * dipanggilnya.</p>
     *
     * @see JurnalPluginParityService
     */
    private static final class Scored{final JurnalPublicService.ArticleCard article;final double score;Scored(JurnalPublicService.ArticleCard a,double s){article=a;score=s;}}
    private static String xmlDecl(){return"<?xml version=\"1.0\" encoding=\"UTF-8\"?>";}private static String xml(String v){return clean(v).replace("&","&amp;").replace("<","&lt;").replace(">","&gt;").replace("\"","&quot;").replace("'","&apos;");}
    private static String lang(String v){String x=clean(v);return x.matches("[A-Za-z]{2,3}(?:[-_][A-Za-z]{2})?")?x:"id";}private static String clean(String v){return v==null?"":v.trim();}
    private static String iso639(String value){String x=clean(value).toLowerCase(Locale.ENGLISH).split("[-_]",2)[0];if("id".equals(x)||"ind".equals(x))return"ind";if("en".equals(x)||"eng".equals(x))return"eng";if("de".equals(x)||"deu".equals(x)||"ger".equals(x))return"ger";if("fr".equals(x)||"fra".equals(x)||"fre".equals(x))return"fre";if(x.matches("[a-z]{3}"))return x;throw new IllegalArgumentException("Bahasa ISO 639-2/B wajib untuk ekspor DOAJ.");}
    private static String absoluteBase(String value){try{String v=clean(value);if(v.length()==0||v.length()>1024)throw new Exception();URI u=new URI(v);String scheme=u.getScheme();if(scheme==null||u.getHost()==null||u.getUserInfo()!=null||u.getQuery()!=null||u.getFragment()!=null||(!"http".equalsIgnoreCase(scheme)&&!"https".equalsIgnoreCase(scheme)))throw new Exception();while(v.endsWith("/"))v=v.substring(0,v.length()-1);return v;}catch(Exception e){throw new IllegalArgumentException("AIS_JURNAL_PUBLIC_BASE_URL absolut http/https wajib untuk ekspor Crossref.");}}
    private static String crossrefContributors(JurnalPublicService.ArticleCard a){List<String> names=new ArrayList<String>(a.authorNames);if(names.isEmpty()&&clean(a.authors).length()>0)names.addAll(Arrays.asList(clean(a.authors).split("\\s*;\\s*")));StringBuilder out=new StringBuilder();int sequence=0;for(String raw:names){String name=clean(raw).replaceAll("\\s+"," ");if(name.length()==0)continue;int cut=name.lastIndexOf(' ');String given=cut>0?name.substring(0,cut):"",surname=cut>0?name.substring(cut+1):name;if(given.length()>60||surname.length()>60||!surname.matches("[^\\d\\?]*[^\\?\\s]+[^\\d]*"))throw new IllegalArgumentException("Nama kontributor tidak memenuhi kontrak Crossref.");if(sequence==0)out.append("<contributors>");out.append("<person_name contributor_role=\"author\" sequence=\"").append(sequence++==0?"first":"additional").append("\">");if(given.length()>0)out.append("<given_name>").append(xml(given)).append("</given_name>");out.append("<surname>").append(xml(surname)).append("</surname></person_name>");}if(sequence>0)out.append("</contributors>");return out.toString();}
    private static String pubmedAuthors(JurnalPublicService.ArticleCard a){List<String> names=new ArrayList<String>(a.authorNames);if(names.isEmpty()&&clean(a.authors).length()>0)names.addAll(Arrays.asList(clean(a.authors).split("\\s*;\\s*")));StringBuilder out=new StringBuilder();for(String raw:names){String name=clean(raw).replaceAll("\\s+"," ");if(name.length()==0)continue;int cut=name.lastIndexOf(' ');String given=cut>0?name.substring(0,cut):"",last=cut>0?name.substring(cut+1):name;if(out.length()==0)out.append("<AuthorList>");out.append("<Author>");if(given.length()>0)out.append("<FirstName>").append(xml(given)).append("</FirstName>");else out.append("<FirstName EmptyYN=\"Y\"></FirstName>");out.append("<LastName>").append(xml(last)).append("</LastName></Author>");}if(out.length()>0)out.append("</AuthorList>");return out.toString();}
    private static String iso(Date d){if(d==null)return"";SimpleDateFormat f=new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss'Z'");f.setTimeZone(TimeZone.getTimeZone("UTC"));return f.format(d);}private static String day(Date d){if(d==null)return"";SimpleDateFormat f=new SimpleDateFormat("yyyy-MM-dd");f.setTimeZone(TimeZone.getTimeZone("UTC"));return f.format(d);}
}
