package ais.action.master.jurnal;
import java.util.*;import org.json.*;
/** Typed/versioned bounded validators for journal profiles stored on RepoCollection. */
public final class JurnalProfileValidator{
 private static final int MAX_DEPTH=10,MAX_FORMS=50,MAX_ELEMENTS=100,MAX_POLICIES=100;
 private JurnalProfileValidator(){}
 public static String metadata(String raw){JSONObject r=root(raw,262144,"metadata");bounded(r,0);JSONArray locales=r.optJSONArray("locales");if(locales!=null){if(locales.length()>30)bad("Terlalu banyak locale.");for(int i=0;i<locales.length();i++)if(!locales.optString(i).matches("[a-z]{2}(?:_[A-Z]{2})?"))bad("Locale tidak valid.");}return r.toString();}
 public static String workflow(String raw,String previous){JSONObject r=root(raw,1048576,"workflow");bounded(r,0);JSONArray forms=r.optJSONArray("reviewForms");if(forms==null)bad("reviewForms wajib berupa array.");if(forms.length()>MAX_FORMS)bad("Terlalu banyak form review.");Set<String> ids=new HashSet<String>();for(int i=0;i<forms.length();i++){JSONObject f=object(forms,i,"Form review tidak valid.");String key=key(f,"formKey");int version=f.optInt("version",0);if(version<1)bad("Versi form review tidak valid.");String identity=key+":"+version;if(!ids.add(identity))bad("Versi form review duplikat.");String status=f.optString("status","DRAFT");if(!status.matches("DRAFT|PUBLISHED|RETIRED"))bad("Status form review tidak valid.");JSONArray elements=f.optJSONArray("elements");if(elements==null)elements=new JSONArray();if(elements.length()>MAX_ELEMENTS)bad("Terlalu banyak elemen form review.");Set<String> elementKeys=new HashSet<String>();for(int j=0;j<elements.length();j++){JSONObject e=object(elements,j,"Elemen review tidak valid.");if(!elementKeys.add(key(e,"elementKey")))bad("Key elemen review duplikat.");String type=e.optString("type");if(!type.matches("TEXT|TEXTAREA|CHECKBOX|RADIO|SELECT|SCALE"))bad("Tipe elemen review tidak valid.");JSONArray options=e.optJSONArray("options");if(options!=null&&options.length()>100)bad("Opsi elemen terlalu banyak.");}}
  if(previous!=null&&previous.trim().length()>0){JSONObject old=root(previous,1048576,"workflow lama");Map<String,String> immutable=published(old.optJSONArray("reviewForms"));Map<String,String> next=published(forms);for(Map.Entry<String,String>x:immutable.entrySet())if(!x.getValue().equals(next.get(x.getKey())))bad("Form review published bersifat immutable: "+x.getKey());}return r.toString();}
 public static String access(String raw){JSONObject r=root(raw,262144,"access");bounded(r,0);JSONArray policies=r.optJSONArray("policies");if(policies==null||policies.length()==0)bad("Minimal satu access policy diperlukan.");if(policies.length()>MAX_POLICIES)bad("Terlalu banyak access policy.");Set<String> keys=new HashSet<String>();for(int i=0;i<policies.length();i++){JSONObject p=object(policies,i,"Access policy tidak valid.");if(!keys.add(key(p,"policyKey")))bad("Policy key duplikat.");String format=p.optString("format");if(!format.matches("OPEN|EMBARGO|SUBSCRIPTION|INSTITUTION"))bad("Format access policy tidak valid.");if(p.optDouble("price",0)<0)bad("Harga policy tidak valid.");}return r.toString();}
 private static Map<String,String> published(JSONArray a){Map<String,String>m=new HashMap<String,String>();if(a==null)return m;for(int i=0;i<a.length();i++){JSONObject f=object(a,i,"Form review tidak valid.");if("PUBLISHED".equals(f.optString("status")))m.put(key(f,"formKey")+":"+f.optInt("version",0),canonical(f));}return m;}
 private static String canonical(JSONObject o){try{return new JSONObject(o.toString()).toString();}catch(Exception e){throw new IllegalArgumentException(e);}}
 private static JSONObject root(String raw,int max,String name){if(raw==null||raw.length()>max)bad("Ukuran profil "+name+" tidak valid.");try{JSONObject r=new JSONObject(raw);if(r.optInt("schemaVersion",0)!=1)bad("Profil "+name+" harus memakai schemaVersion 1.");return r;}catch(RuntimeException e){throw e;}catch(Exception e){throw new IllegalArgumentException("Profil "+name+" bukan JSON object valid.",e);}}
 private static JSONObject object(JSONArray a,int i,String message){try{return a.getJSONObject(i);}catch(Exception e){throw new IllegalArgumentException(message,e);}}
 private static String key(JSONObject o,String field){String v=o.optString(field).trim();if(!v.matches("[A-Za-z][A-Za-z0-9_.-]{0,119}"))bad(field+" tidak valid.");return v;}
 private static void bounded(Object v,int depth){if(depth>MAX_DEPTH)bad("Kedalaman JSON melewati batas.");if(v instanceof JSONObject){JSONObject o=(JSONObject)v;if(o.length()>500)bad("Object JSON terlalu besar.");Iterator<?>i=o.keys();while(i.hasNext()){String k=String.valueOf(i.next());try{bounded(o.get(k),depth+1);}catch(JSONException e){throw new IllegalArgumentException(e);}}}else if(v instanceof JSONArray){JSONArray a=(JSONArray)v;if(a.length()>1000)bad("Array JSON terlalu besar.");for(int i=0;i<a.length();i++)try{bounded(a.get(i),depth+1);}catch(JSONException e){throw new IllegalArgumentException(e);}}else if(v instanceof String&&((String)v).length()>262144)bad("Nilai JSON terlalu panjang.");}
 private static void bad(String m){throw new IllegalArgumentException(m);}
}
