package ais.action.master.jurnal;

import java.util.Date;
import org.hibernate.*;
import org.json.JSONObject;
import ais.database.hibernate.HibernateUtil;
import ais.database.model.Tbmuser;
import ais.database.model.penelitiandanpengabdian.JurnalPenelitian;
import ais.database.model.repository.RepoCollection;

/** Journal master tetap JurnalPenelitian, dengan RepoCollection JOURNAL sebagai kernel konten. */
public final class JurnalAdministrationService {
    private final JurnalAuthorizationService auth=new JurnalAuthorizationService();
    public JurnalPenelitian create(String tenant,String title,String slug,String locale,Tbmuser actor){auth.requireCrud(actor,"masterJurnal","create");auth.requireAdministrator(actor);required(title,"Nama jurnal wajib diisi.");required(slug,"Slug wajib diisi.");String key=slug(slug);Session s=HibernateUtil.currentSession();Transaction tx=s.getTransaction();boolean own=!tx.isActive();try{if(own)tx.begin();Number exists=(Number)s.createQuery("select count(*) from RepoCollection where lower(kode)=:k and aktif=true").setString("k",key).uniqueResult();if(exists.longValue()>0)throw new IllegalArgumentException("Slug jurnal sudah dipakai.");RepoCollection c=new RepoCollection();c.setTenantKey(clean(tenant).length()==0?"default":clean(tenant));c.setKode(key);c.setNama(clean(title));c.setTipe("JOURNAL");c.setSourceSystem("AIS");c.setMetadataProfileJson(defaultMetadata());c.setWorkflowProfileJson(defaultWorkflow());c.setAccessPolicyJson(defaultAccess());c.setDepositEnabled(Boolean.TRUE);c.setAktif(Boolean.TRUE);c.setOlehId(actor.getUserId());s.save(c);s.flush();JurnalPenelitian j=new JurnalPenelitian();j.setJudul(clean(title));j.setPath(key);j.setRepoCollectionId(c.getId());j.setTenantKey(c.getTenantKey());j.setDefaultLocale(blank(locale)?"id_ID":clean(locale));j.setAktif(Boolean.TRUE);j.setOlehId(actor.getUserId());s.save(j);if(own)tx.commit();return j;}catch(RuntimeException e){if(own&&tx.isActive())tx.rollback();throw e;}}
    public RepoCollection updateProfiles(Long collectionId,String metadata,String workflow,String access,Tbmuser actor){auth.requireCrud(actor,"masterJurnal","update");Session s=HibernateUtil.currentSession();Transaction tx=s.getTransaction();boolean own=!tx.isActive();try{if(own)tx.begin();RepoCollection c=(RepoCollection)s.get(RepoCollection.class,collectionId);if(c==null||!"JOURNAL".equalsIgnoreCase(c.getTipe()))throw new IllegalArgumentException("Jurnal tidak ditemukan.");JurnalPenelitian j=(JurnalPenelitian)s.createQuery("from JurnalPenelitian where repoCollectionId=:c and aktif=true").setLong("c",collectionId).setMaxResults(1).uniqueResult();if(j==null)throw new IllegalArgumentException("Jurnal tidak ditemukan.");auth.requireJournalScope(s,actor,j.getId(),null,null,false,"MANAGEMENT");String canonicalMetadata=JurnalProfileValidator.metadata(metadata),canonicalWorkflow=JurnalProfileValidator.workflow(workflow,c.getWorkflowProfileJson()),canonicalAccess=JurnalProfileValidator.access(access);c.setMetadataProfileJson(canonicalMetadata);c.setWorkflowProfileJson(canonicalWorkflow);c.setAccessPolicyJson(canonicalAccess);c.setOlehId(actor.getUserId());s.update(c);if(own)tx.commit();return c;}catch(RuntimeException e){if(own&&tx.isActive())tx.rollback();throw e;}}
    private static String defaultMetadata(){return "{\"schemaVersion\":1,\"locales\":[\"id_ID\",\"en_US\"],\"fields\":[]}";}private static String defaultWorkflow(){return "{\"schemaVersion\":1,\"reviewForms\":[],\"settings\":{}}";}private static String defaultAccess(){return "{\"schemaVersion\":1,\"policies\":[{\"policyKey\":\"open\",\"active\":true,\"format\":\"OPEN\"}]}";}
    private static String slug(String v){String s=clean(v).toLowerCase().replaceAll("[^a-z0-9]+","-").replaceAll("^-|-$","");if(s.length()<2||s.length()>120)throw new IllegalArgumentException("Slug jurnal tidak valid.");return s;}private static boolean blank(String v){return clean(v).length()==0;}private static void required(String v,String m){if(blank(v))throw new IllegalArgumentException(m);}private static String clean(String v){return v==null?"":v.trim();}
}
