package ais.action.master.jurnal;

import java.security.MessageDigest;
import java.security.SecureRandom;
import java.util.Date;
import org.hibernate.*;
import ais.database.hibernate.HibernateUtil;
import ais.database.model.Tbmuser;
import ais.database.model.jurnal.PenugasanTahapJurnal;
import ais.database.model.jurnal.UndanganPeranJurnal;

/** One-time invitation; hanya hash token yang disimpan. */
public final class JurnalInvitationService {
    private final JurnalAuthorizationService auth=new JurnalAuthorizationService();private final SecureRandom random=new SecureRandom();
    public static final class Issued{public Long id;public String token;public Date expiresAt;}
    public Issued issue(Long journalId,String tenant,String email,String roleKey,String scopeType,String scopeKey,long ttlMillis,Tbmuser actor){auth.requireCrud(actor,"penggunaPeran","create");required(email,"Email wajib diisi.");required(roleKey,"Peran wajib diisi.");if(ttlMillis<60000||ttlMillis>2592000000L)throw new IllegalArgumentException("Masa berlaku undangan tidak valid.");byte[] bytes=new byte[32];random.nextBytes(bytes);String token=hex(bytes),hash=sha256(token);Date expiry=new Date(System.currentTimeMillis()+ttlMillis);Session s=HibernateUtil.currentSession();Transaction tx=s.getTransaction();boolean own=!tx.isActive();try{if(own)tx.begin();UndanganPeranJurnal i=new UndanganPeranJurnal();i.setTenantKey(clean(tenant));i.setJurnalPenelitianId(journalId);i.setEmail(clean(email).toLowerCase());i.setRoleKey(clean(roleKey));i.setScopeType(clean(scopeType));i.setScopeKey(clean(scopeKey));i.setTokenHash(hash);i.setStatus("PENDING");i.setExpiresAt(expiry);i.setCreatedBy(actor.getUserId());i.setCreatedAt(new Date());i.setUpdatedAt(new Date());i.setAktif(Boolean.TRUE);s.save(i);if(own)tx.commit();Issued out=new Issued();out.id=i.getId();out.token=token;out.expiresAt=expiry;return out;}catch(RuntimeException e){if(own&&tx.isActive())tx.rollback();throw e;}}
    public PenugasanTahapJurnal accept(String token,Tbmuser actor){if(actor==null)throw new SecurityException("Login diperlukan.");required(token,"Token wajib diisi.");Session s=HibernateUtil.currentSession();Transaction tx=s.getTransaction();boolean own=!tx.isActive();try{if(own)tx.begin();Query q=s.createQuery("from UndanganPeranJurnal where tokenHash=:h and status='PENDING' and aktif=true");q.setString("h",sha256(token));q.setMaxResults(1);UndanganPeranJurnal i=(UndanganPeranJurnal)q.uniqueResult();if(i==null||i.getExpiresAt().before(new Date()))throw new SecurityException("Undangan tidak valid atau kedaluwarsa.");i.setStatus("ACCEPTED");i.setAcceptedAt(new Date());i.setInvitedUserId(actor.getUserId());s.update(i);PenugasanTahapJurnal a=new PenugasanTahapJurnal();a.setTenantKey(i.getTenantKey());a.setJurnalPenelitianId(i.getJurnalPenelitianId());a.setUserId(actor.getUserId());a.setRoleKey(i.getRoleKey());a.setStageKey(i.getScopeType());a.setSectionKey(i.getScopeKey());a.setStatus("ACTIVE");a.setStartsAt(new Date());a.setCreatedBy(actor.getUserId());a.setCreatedAt(new Date());a.setUpdatedAt(new Date());a.setAktif(Boolean.TRUE);s.save(a);if(own)tx.commit();return a;}catch(RuntimeException e){if(own&&tx.isActive())tx.rollback();throw e;}}
    public void revoke(Long id,Tbmuser actor){auth.requireCrud(actor,"penggunaPeran","delete");Session s=HibernateUtil.currentSession();Transaction tx=s.getTransaction();boolean own=!tx.isActive();try{if(own)tx.begin();UndanganPeranJurnal i=(UndanganPeranJurnal)s.get(UndanganPeranJurnal.class,id);if(i==null)throw new IllegalArgumentException("Undangan tidak ditemukan.");if("ACCEPTED".equals(i.getStatus()))throw new IllegalStateException("Undangan sudah diterima.");i.setStatus("REVOKED");i.setRevokedAt(new Date());s.update(i);if(own)tx.commit();}catch(RuntimeException e){if(own&&tx.isActive())tx.rollback();throw e;}}
    private static String sha256(String v){try{return hex(MessageDigest.getInstance("SHA-256").digest(v.getBytes("UTF-8")));}catch(Exception e){throw new IllegalStateException(e);}}private static String hex(byte[]b){StringBuilder s=new StringBuilder();for(byte x:b)s.append(String.format("%02x",x&255));return s.toString();}private static void required(String v,String m){if(clean(v).length()==0)throw new IllegalArgumentException(m);}private static String clean(String v){return v==null?"":v.trim();}
}
