package ais.action.master.jurnal;

import java.math.BigInteger;
import java.net.InetAddress;
import java.util.*;
import org.hibernate.*;
import org.json.*;
import ais.database.hibernate.HibernateUtil;
import ais.database.model.Tbmuser;
import ais.database.model.jurnal.LanggananJurnal;
import ais.database.model.jurnal.RentangIpLanggananJurnal;
import ais.database.model.repository.RepoCollection;
import ais.database.model.repository.RepoItem;

/** Evaluator open/embargo/subscription/institution-IP dengan policy snapshot immutable. */
public final class JurnalAccessService {
    private final JurnalAuthorizationService auth=new JurnalAuthorizationService();
    public static final class Decision{public final boolean allowed;public final String reason;Decision(boolean a,String r){allowed=a;reason=r;}}

    public LanggananJurnal activate(Long journalId,Long collectionId,String policyKey,String userId,String institutionType,
            Long institutionId,Date starts,Date ends,Long paymentId,String tenant,Tbmuser actor){auth.requireWorkflow(actor,"manageSubscription");if(starts==null||ends==null||!ends.after(starts))throw new IllegalArgumentException("Periode langganan tidak valid.");Session s=HibernateUtil.currentSession();Transaction tx=s.getTransaction();boolean own=!tx.isActive();try{if(own)tx.begin();RepoCollection c=(RepoCollection)s.get(RepoCollection.class,collectionId);if(c==null||!"JOURNAL".equalsIgnoreCase(c.getTipe()))throw new IllegalArgumentException("Jurnal tidak ditemukan.");JSONObject policy=findPolicy(c.getAccessPolicyJson(),policyKey);LanggananJurnal l=new LanggananJurnal();l.setTenantKey(clean(tenant));l.setJurnalPenelitianId(journalId);l.setCollectionId(collectionId);l.setPolicyKey(policyKey);l.setPolicySnapshotJson(policy.toString());l.setUserId(cleanNull(userId));l.setInstitutionType(cleanNull(institutionType));l.setInstitutionId(institutionId);l.setStartsAt(starts);l.setEndsAt(ends);l.setPaymentId(paymentId);l.setStatus(paymentRequired(policy)&&paymentId==null?"PENDING_PAYMENT":"ACTIVE");l.setCreatedBy(actor.getUserId());l.setCreatedAt(new Date());l.setUpdatedAt(new Date());l.setAktif(Boolean.TRUE);s.save(l);if(own)tx.commit();return l;}catch(RuntimeException e){if(own&&tx.isActive())tx.rollback();throw e;}catch(Exception e){if(own&&tx.isActive())tx.rollback();throw new IllegalArgumentException("Policy langganan tidak valid.",e);}}
    public Decision evaluate(RepoItem item,String userId,Long institutionId,String remoteIp,Date now){if(item==null)return new Decision(false,"ITEM_NOT_FOUND");Date at=now==null?new Date():now;if("OPEN_ACCESS".equals(item.getAccessPolicy())&&(item.getEmbargoUntil()==null||!item.getEmbargoUntil().after(at)))return new Decision(true,"OPEN");Session s=HibernateUtil.currentSession();Query q=s.createQuery("from LanggananJurnal where collectionId=:c and status='ACTIVE' and aktif=true and startsAt<=:at and endsAt>:at and ((userId is not null and userId=:u) or (institutionId is not null and institutionId=:i))");q.setLong("c",item.getCollectionId());q.setTimestamp("at",at);q.setString("u",clean(userId));q.setLong("i",institutionId==null?-1L:institutionId.longValue());q.setMaxResults(1);LanggananJurnal l=(LanggananJurnal)q.uniqueResult();if(l!=null)return new Decision(true,l.getUserId()!=null?"USER_SUBSCRIPTION":"INSTITUTION_SUBSCRIPTION");if(!blank(remoteIp)){Query ipq=s.createQuery("select r from RentangIpLanggananJurnal r,LanggananJurnal l where r.langgananId=l.id and l.collectionId=:c and l.status='ACTIVE' and l.aktif=true and r.aktif=true and l.startsAt<=:at and l.endsAt>:at");ipq.setLong("c",item.getCollectionId());ipq.setTimestamp("at",at);@SuppressWarnings("unchecked")List<RentangIpLanggananJurnal> ranges=ipq.list();for(RentangIpLanggananJurnal r:ranges)if(inRange(remoteIp,r.getStartAddress(),r.getEndAddress(),r.getAddressFamily()))return new Decision(true,"INSTITUTION_IP");}return new Decision(false,item.getEmbargoUntil()!=null&&item.getEmbargoUntil().after(at)?"EMBARGO":"SUBSCRIPTION_REQUIRED");}
    public RentangIpLanggananJurnal addRange(Long subscriptionId,String start,String end,String label,Tbmuser actor){auth.requireWorkflow(actor,"manageSubscription");try{InetAddress a=InetAddress.getByName(clean(start)),b=InetAddress.getByName(clean(end));if(a.getAddress().length!=b.getAddress().length||unsigned(a).compareTo(unsigned(b))>0)throw new IllegalArgumentException("Rentang IP tidak valid.");Session s=HibernateUtil.currentSession();LanggananJurnal l=(LanggananJurnal)s.get(LanggananJurnal.class,subscriptionId);if(l==null)throw new IllegalArgumentException("Langganan tidak ditemukan.");RentangIpLanggananJurnal r=new RentangIpLanggananJurnal();r.setTenantKey(l.getTenantKey());r.setJurnalPenelitianId(l.getJurnalPenelitianId());r.setLanggananId(subscriptionId);r.setAddressFamily(a.getAddress().length==4?4:6);r.setStartAddress(a.getHostAddress());r.setEndAddress(b.getHostAddress());r.setLabel(clean(label));r.setCreatedBy(actor.getUserId());r.setCreatedAt(new Date());r.setUpdatedAt(new Date());r.setAktif(Boolean.TRUE);Transaction tx=s.getTransaction();boolean own=!tx.isActive();if(own)tx.begin();s.save(r);if(own)tx.commit();return r;}catch(RuntimeException e){throw e;}catch(Exception e){throw new IllegalArgumentException("Rentang IP tidak valid.",e);}}
    private static JSONObject findPolicy(String raw,String key)throws Exception{JSONObject root=new JSONObject(raw);if(root.optInt("schemaVersion",0)!=1)throw new Exception();JSONArray policies=root.getJSONArray("policies");for(int i=0;i<policies.length();i++){JSONObject p=policies.getJSONObject(i);if(key.equals(p.optString("policyKey"))&&p.optBoolean("active",false))return new JSONObject(p.toString());}throw new IllegalArgumentException("Policy langganan tidak ditemukan.");}
    private static boolean paymentRequired(JSONObject p){return p.optDouble("price",0)>0;}private static boolean inRange(String ip,String start,String end,Integer family){try{InetAddress a=InetAddress.getByName(ip);if((a.getAddress().length==4?4:6)!=(family==null?0:family.intValue()))return false;BigInteger v=unsigned(a);return v.compareTo(unsigned(InetAddress.getByName(start)))>=0&&v.compareTo(unsigned(InetAddress.getByName(end)))<=0;}catch(Exception e){return false;}}private static BigInteger unsigned(InetAddress a){return new BigInteger(1,a.getAddress());}private static boolean blank(String v){return clean(v).length()==0;}private static String cleanNull(String v){return blank(v)?null:clean(v);}private static String clean(String v){return v==null?"":v.trim();}
}
