package ais.action.master.jurnal;

import java.util.*;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.Transaction;
import ais.database.hibernate.HibernateUtil;
import ais.database.model.Tbmuser;
import ais.database.model.penelitiandanpengabdian.*;
import ais.database.model.repository.*;

/** Issue/TOC/publication lifecycle with idempotent legacy compatibility projections. */
public final class JurnalPublicationService {
    private final JurnalAuthorizationService auth=new JurnalAuthorizationService();

    public RepoItem createIssue(Long collectionId,String title,Integer volume,String number,Integer year,
            Date scheduledAt,Tbmuser actor){auth.requireCrud(actor,"edisiDaftarIsi","create");required(title,"Judul edisi wajib diisi.");Session s=HibernateUtil.currentSession();Transaction tx=s.getTransaction();boolean own=!tx.isActive();try{if(own)tx.begin();RepoCollection c=journal(s,collectionId);auth.requireCollectionScope(s,actor,collectionId,"PUBLICATION");RepoItem issue=new RepoItem();issue.setCollectionId(collectionId);issue.setTenantKey(c.getTenantKey());issue.setDocumentType("JOURNAL_ISSUE");issue.setWorkflowStatus(scheduledAt==null?"DRAFT":"SCHEDULED");issue.setSyncStatus(issue.getWorkflowStatus());issue.setTitle(clean(title));issue.setLanguage("id");issue.setOwnerId(actor.getUserId());issue.setVersionNumber(1L);issue.setViewCount(0L);issue.setDownloadCount(0L);issue.setAktif(Boolean.TRUE);issue.setOlehId(actor.getUserId());s.save(issue);s.flush();metadata(s,issue.getId(),"issue.volume",String.valueOf(volume==null?0:volume),actor);metadata(s,issue.getId(),"issue.number",clean(number),actor);metadata(s,issue.getId(),"issue.year",String.valueOf(year==null?year(new Date()):year),actor);if(scheduledAt!=null)metadata(s,issue.getId(),"issue.scheduledAt",String.valueOf(scheduledAt.getTime()),actor);if(own)tx.commit();return issue;}catch(RuntimeException e){if(own&&tx.isActive())tx.rollback();throw e;}}

    public RepoItemRelation placeArticle(Long issueId,Long articleId,int sortOrder,Tbmuser actor){auth.requireCrud(actor,"edisiDaftarIsi","update");if(sortOrder<0)throw new IllegalArgumentException("Urutan TOC tidak valid.");Session s=HibernateUtil.currentSession();Transaction tx=s.getTransaction();boolean own=!tx.isActive();try{if(own)tx.begin();RepoItem issue=item(s,issueId,"JOURNAL_ISSUE"),article=item(s,articleId,"JOURNAL_SUBMISSION");auth.requireItemScope(s,actor,issue,false,"PUBLICATION");if(!issue.getCollectionId().equals(article.getCollectionId()))throw new SecurityException("Artikel dan edisi berbeda jurnal.");Query q=s.createQuery("from RepoItemRelation where itemId=:i and relatedItemId=:a and relationType='ISSUE_CONTAINS' and aktif=true");q.setLong("i",issueId);q.setLong("a",articleId);q.setMaxResults(1);RepoItemRelation r=(RepoItemRelation)q.uniqueResult();if(r==null){r=new RepoItemRelation();r.setItemId(issueId);r.setRelatedItemId(articleId);r.setRelationType("ISSUE_CONTAINS");r.setActorId(actor.getUserId());r.setCreatedAt(new Date());r.setAktif(Boolean.TRUE);r.setSortOrder(Integer.valueOf(sortOrder));s.save(r);}else{r.setSortOrder(Integer.valueOf(sortOrder));s.update(r);}if(own)tx.commit();return r;}catch(RuntimeException e){if(own&&tx.isActive())tx.rollback();throw e;}}

    public RepoItem publishIssue(Long issueId,Date publishAt,Tbmuser actor){auth.requireWorkflow(actor,"publish");Session s=HibernateUtil.currentSession();Transaction tx=s.getTransaction();boolean own=!tx.isActive();try{if(own)tx.begin();RepoItem issue=item(s,issueId,"JOURNAL_ISSUE");auth.requireItemScope(s,actor,issue,false,"PUBLICATION");Date at=publishAt==null?new Date():publishAt;@SuppressWarnings("unchecked")List<RepoItem> articles=s.createQuery("select a from RepoItem a,RepoItemRelation r where r.itemId=:i and r.relatedItemId=a.id and r.relationType='ISSUE_CONTAINS' and r.aktif=true and a.aktif=true order by r.sortOrder,a.id").setLong("i",issueId).list();if(articles.isEmpty())throw new IllegalStateException("Edisi belum mempunyai artikel.");for(RepoItem a:articles){String st=a.getWorkflowStatus();if(!("PUBLICATION_READY".equals(st)||"SCHEDULED".equals(st)||"PUBLISHED".equals(st)))throw new IllegalStateException("Artikel "+a.getId()+" belum siap publikasi.");if(!"PUBLISHED".equals(st)){a.setWorkflowStatus("PUBLISHED");a.setSyncStatus("PUBLISHED");a.setPublishedAt(at);a.setIssuedAt(at);a.setIsWithdrawn(Boolean.FALSE);if(blank(a.getSlug()))a.setSlug(slug(a.getTitle(),a.getId()));if(blank(a.getOaiIdentifier()))a.setOaiIdentifier("oai:ais:jurnal:"+a.getId());a.setOlehId(actor.getUserId());s.update(a);}project(s,a,actor);}issue.setWorkflowStatus("PUBLISHED");issue.setSyncStatus("PUBLISHED");issue.setPublishedAt(at);issue.setIssuedAt(at);issue.setIsWithdrawn(Boolean.FALSE);if(blank(issue.getSlug()))issue.setSlug(slug(issue.getTitle(),issue.getId()));if(blank(issue.getOaiIdentifier()))issue.setOaiIdentifier("oai:ais:jurnal:issue:"+issue.getId());issue.setOlehId(actor.getUserId());s.update(issue);if(own)tx.commit();return issue;}catch(RuntimeException e){if(own&&tx.isActive())tx.rollback();throw e;}}

    /** Projection may be called repeatedly; repo_item_id is the stable idempotency key. */
    public Artikel projectPublishedArticle(Long itemId,Tbmuser actor){auth.requireCrud(actor,"publikasi","update");Session s=HibernateUtil.currentSession();Transaction tx=s.getTransaction();boolean own=!tx.isActive();try{if(own)tx.begin();RepoItem item=item(s,itemId,"JOURNAL_SUBMISSION");auth.requireItemScope(s,actor,item,false,"PUBLICATION");Artikel a=project(s,item,actor);if(own)tx.commit();return a;}catch(RuntimeException e){if(own&&tx.isActive())tx.rollback();throw e;}}

    private Artikel project(Session s,RepoItem item,Tbmuser actor){if(!"PUBLISHED".equals(item.getWorkflowStatus())||Boolean.TRUE.equals(item.getIsWithdrawn()))throw new IllegalStateException("Hanya artikel terbit aktif yang dapat diproyeksikan.");Query q=s.createQuery("from Artikel where repoItemId=:id");q.setLong("id",item.getId());q.setMaxResults(1);Artikel a=(Artikel)q.uniqueResult();if(a==null){a=new Artikel();a.setRepoItemId(item.getId());a.setArticleId(item.getId()<=Integer.MAX_VALUE?Integer.valueOf(item.getId().intValue()):Integer.valueOf(-item.getId().intValue()));}
        Query jq=s.createQuery("from JurnalPenelitian where repoCollectionId=:c and aktif=true");jq.setLong("c",item.getCollectionId());jq.setMaxResults(1);JurnalPenelitian journal=(JurnalPenelitian)jq.uniqueResult();if(journal==null)throw new IllegalStateException("Master jurnal tidak ditemukan.");Date published=item.getPublishedAt()==null?new Date():item.getPublishedAt();Calendar academic=Calendar.getInstance();academic.setTime(published);int academicStart=academic.get(Calendar.MONTH)>5?academic.get(Calendar.YEAR):academic.get(Calendar.YEAR)-1;a.setJurnalPenelitian(journal);a.setJudul(item.getTitle());a.setAbstrak(item.getAbstractText());a.setKeyword(item.getSubjects());a.setBahasa(item.getLanguage());a.setTanggalPublikasi(published);a.setTahun(Integer.valueOf(year(published)));a.setSemester(academic.get(Calendar.MONTH)>5?"Ganjil":"Genap");a.setTahunAkademik(academicStart+"/"+(academicStart+1));a.setCopyrightHolder(blank(journal.getJudul())?"Jurnal Ilmiah eCampus":journal.getJudul());a.setSponsor(blank(journal.getJudul())?"Jurnal Ilmiah eCampus":journal.getJudul());a.setLicenseURL(item.getLicenseUri());a.setPathUrl("/jurnal/article/"+item.getSlug());a.setPath(item.getSlug());a.setStatus(Artikel.DISETUJUI);a.setAktif(Boolean.TRUE);a.setOlehId(actor.getUserId());if(a.getId()==null)s.save(a);else s.update(a);s.flush();projectFiles(s,item,a,actor);projectContributors(s,item,a,actor);return a;
    }
    private void projectFiles(Session s,RepoItem item,Artikel a,Tbmuser actor){@SuppressWarnings("unchecked")List<RepoBitstream> files=s.createQuery("from RepoBitstream where itemId=:i and aktif=true and storageState='LINKED' and journalStage in ('PRODUCTION','PROOF','PUBLICATION')").setLong("i",item.getId()).list();for(RepoBitstream b:files){Query q=s.createQuery("from FileArtikel where repoBitstreamId=:id");q.setLong("id",b.getId());q.setMaxResults(1);FileArtikel f=(FileArtikel)q.uniqueResult();if(f==null){f=new FileArtikel();f.setRepoBitstreamId(b.getId());f.setArtikel(a);}f.setNama(b.getNamaFile());f.setMimeType(b.getMimeType());f.setPath("lampiranlain:"+b.getContentRef());f.setKeterangan(b.getDescription());f.setUploadDate(new Date());f.setOlehId(actor.getUserId());if(f.getId()==null)s.save(f);else s.update(f);}}
    private void projectContributors(Session s,RepoItem item,Artikel a,Tbmuser actor){@SuppressWarnings("unchecked")List<RepoItemContributor> contributors=s.createQuery("from RepoItemContributor where itemId=:i and aktif=true order by sequenceNumber,id").setLong("i",item.getId()).list();for(RepoItemContributor c:contributors){Query q=s.createQuery("from AnggotaArtikel where repoContributorId=:id");q.setLong("id",c.getId());q.setMaxResults(1);AnggotaArtikel x=(AnggotaArtikel)q.uniqueResult();if(x==null){x=new AnggotaArtikel();x.setRepoContributorId(c.getId());x.setArtikel(a);}x.setKeterangan(c.getDisplayName()+" | "+c.getContributorRole()+(Boolean.TRUE.equals(c.getCorresponding())?" | corresponding":""));x.setOlehId(actor.getUserId());if(x.getId()==null)s.save(x);else s.update(x);}}
    private static void metadata(Session s,Long item,String field,String value,Tbmuser actor){RepoItemMetadata m=new RepoItemMetadata();m.setItemId(item);m.setMetadataField(field);m.setMetadataValue(value);m.setLanguage("*");m.setPlace(0);m.setAktif(Boolean.TRUE);m.setOlehId(actor.getUserId());s.save(m);}
    private static RepoCollection journal(Session s,Long id){RepoCollection c=(RepoCollection)s.get(RepoCollection.class,id);if(c==null||!Boolean.TRUE.equals(c.getAktif())||!"JOURNAL".equals(c.getTipe()))throw new IllegalArgumentException("Jurnal tidak ditemukan.");return c;}
    private static RepoItem item(Session s,Long id,String type){RepoItem i=(RepoItem)s.get(RepoItem.class,id);if(i==null||!Boolean.TRUE.equals(i.getAktif())||!type.equals(i.getDocumentType()))throw new IllegalArgumentException("Item jurnal tidak ditemukan.");journal(s,i.getCollectionId());return i;}
    private static int year(Date d){Calendar c=Calendar.getInstance();c.setTime(d==null?new Date():d);return c.get(Calendar.YEAR);}private static String slug(String t,Long id){String s=clean(t).toLowerCase(Locale.ENGLISH).replaceAll("[^a-z0-9]+","-").replaceAll("^-|-$","");return(s.length()>100?s.substring(0,100):s)+"-"+id;}private static void required(String v,String m){if(blank(v))throw new IllegalArgumentException(m);}private static boolean blank(String v){return clean(v).length()==0;}private static String clean(String v){return v==null?"":v.trim();}
}
