<%-- @generated by generate_new_jsp_scaffold.py
Source: src/ais/action/report/format1/akademik/LaporanRekapAngketPerMahasiswaWindow.java
Generated: 2026-08-06T18:20:20Z
Safe service-adapter scaffold. Implement data access in a Java service layer, not directly in this JSP.
--%>
<%@ page language="java" contentType="application/json; charset=UTF-8" pageEncoding="UTF-8" %>
<%
request.setAttribute("nuiServiceModule", "root/report");
request.setAttribute("nuiServicePage", "format1/akademik/laporan_rekap_angket_per_mahasiswa");
request.setAttribute("nuiServiceTitle", "Laporan Rekap Angket Per Mahasiswa");
request.setAttribute("nuiServiceType", "report");
request.setAttribute("nuiServiceSourceClass", "LaporanRekapAngketPerMahasiswaWindow");
request.setAttribute("nuiServiceSourcePackage", "ais.action.report.format1.akademik");
request.setAttribute("nuiServiceSourcePath", "src/ais/action/report/format1/akademik/LaporanRekapAngketPerMahasiswaWindow.java");
request.setAttribute("nuiServiceMethods", new String[]{"onEvent", "generateParameters", "onLaporanAngketDosenPerDosen"});
request.setAttribute("nuiServiceLegacyRefs", new String[]{});
request.setAttribute("nuiServiceEntities", new String[]{});
%>
<jsp:include page="/WEB-INF/new/_shared/services/dispatcher.jsp" />
