<%-- @generated by generate_new_jsp_scaffold.py
Source: src/ais/action/report/format1/akademik/LaporanDaftarHadirDosen.java
Generated: 2026-08-06T18:20:20Z
Safe service-adapter scaffold. Implement data access in a Java service layer, not directly in this JSP.
--%>
<%@ page language="java" contentType="application/json; charset=UTF-8" pageEncoding="UTF-8" %>
<%
request.setAttribute("nuiServiceModule", "root/report");
request.setAttribute("nuiServicePage", "format1/akademik/laporan_daftar_hadir_dosen");
request.setAttribute("nuiServiceTitle", "Laporan Daftar Hadir Dosen");
request.setAttribute("nuiServiceType", "report");
request.setAttribute("nuiServiceSourceClass", "LaporanDaftarHadirDosen");
request.setAttribute("nuiServiceSourcePackage", "ais.action.report.format1.akademik");
request.setAttribute("nuiServiceSourcePath", "src/ais/action/report/format1/akademik/LaporanDaftarHadirDosen.java");
request.setAttribute("nuiServiceMethods", new String[]{"onEvent", "generateParameters", "onDaftarHadirDosenSemua"});
request.setAttribute("nuiServiceEntities", new String[]{"Staff", "Perkuliahan", "Dosen", "PenugasanDosenMengajar"});
%>
<jsp:include page="/WEB-INF/new/_shared/services/dispatcher.jsp" />
