<%-- @generated by generate_new_jsp_scaffold.py
Source: src/ais/action/report/format1/akademik/LaporanRekapJumlahMahasiswaAngkatan.java
Generated: 2026-08-06T18:20:20Z
Safe service-adapter scaffold. Implement data access in a Java service layer, not directly in this JSP.
--%>
<%@ page language="java" contentType="application/json; charset=UTF-8" pageEncoding="UTF-8" %>
<%
request.setAttribute("nuiServiceModule", "root/report");
request.setAttribute("nuiServicePage", "format1/akademik/laporan_rekap_jumlah_mahasiswa_angkatan");
request.setAttribute("nuiServiceTitle", "Laporan Rekap Jumlah Mahasiswa Angkatan");
request.setAttribute("nuiServiceType", "report");
request.setAttribute("nuiServiceSourceClass", "LaporanRekapJumlahMahasiswaAngkatan");
request.setAttribute("nuiServiceSourcePackage", "ais.action.report.format1.akademik");
request.setAttribute("nuiServiceSourcePath", "src/ais/action/report/format1/akademik/LaporanRekapJumlahMahasiswaAngkatan.java");
request.setAttribute("nuiServiceMethods", new String[]{"onEvent", "generateParameters", "onCetak", "run"});
request.setAttribute("nuiServiceLegacyRefs", new String[]{});
request.setAttribute("nuiServiceEntities", new String[]{"StatusAwalMahasiswa", "Mahasiswa"});
%>
<jsp:include page="/WEB-INF/new/_shared/services/dispatcher.jsp" />
