<%-- @generated by generate_new_jsp_scaffold.py
Source: src/ais/action/master/obe/CapaianLulusanVsCapaianPembelajaranLulusanAction.java
Generated: 2026-08-06T18:20:20Z
Safe service-adapter scaffold. Implement data access in a Java service layer, not directly in this JSP.
--%>
<%@ page language="java" contentType="application/json; charset=UTF-8" pageEncoding="UTF-8" %>
<%
request.setAttribute("nuiServiceModule", "obe");
request.setAttribute("nuiServicePage", "capaian_lulusan_vs_capaian_pembelajaran_lulusan");
request.setAttribute("nuiServiceTitle", "Capaian Lulusan Vs Capaian Pembelajaran Lulusan");
request.setAttribute("nuiServiceType", "academic");
request.setAttribute("nuiServiceSourceClass", "CapaianLulusanVsCapaianPembelajaranLulusanAction");
request.setAttribute("nuiServiceSourcePackage", "ais.action.master.obe");
request.setAttribute("nuiServiceSourcePath", "src/ais/action/master/obe/CapaianLulusanVsCapaianPembelajaranLulusanAction.java");
request.setAttribute("nuiServiceMethods", new String[]{"onEvent", "onKHS"});
request.setAttribute("nuiServiceLegacyRefs", new String[]{});
request.setAttribute("nuiServiceEntities", new String[]{"CapaianPembelajaranLulusan", "CapaianLulusan"});
%>
<jsp:include page="/WEB-INF/new/_shared/services/dispatcher.jsp" />
