<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ page import="java.text.DecimalFormat" %><%@ page import="java.util.List" %>
<%@ page import="ais.common.newui.menu.NewUiHybridMenuNode" %><%@ page import="ais.common.newui.menu.NewUiModuleDashboardService.Dashboard" %><%@ page import="ais.common.newui.menu.NewUiModuleDashboardService.Definition" %><%@ page import="ais.common.newui.menu.NewUiModuleDashboardService.Metric" %><%@ page import="ais.common.newui.menu.NewUiModuleFunctionService.Function" %><%@ page import="ais.common.newui.menu.NewUiModuleShortcut" %>
<%@ page import="ais.common.Common" %><%@ page import="ais.database.model.Tbmuser" %><%@ page import="ais.common.newui.menu.NewUiActionDashboardMetricService" %>
<%!
private String mfH(Object value){if(value==null)return "";return String.valueOf(value).replace("&","&amp;").replace("<","&lt;").replace(">","&gt;").replace("\"","&quot;").replace("'","&#39;");}
%>
<%
Dashboard mfDashboard=(Dashboard)request.getAttribute("nuiActiveModuleDashboard");Definition mfDefinition=mfDashboard.getDefinition();List<Metric> mfMetrics=mfDashboard.getMetrics();Function mfFunction=(Function)request.getAttribute("nuiActiveModuleFunction");NewUiModuleShortcut mfShortcut=(NewUiModuleShortcut)request.getAttribute("nuiActiveModuleShortcut");List<NewUiHybridMenuNode> mfMenus=(List<NewUiHybridMenuNode>)request.getAttribute("nuiActiveModuleMenus");String mfNew=request.getContextPath()+"/new";String mfHome=mfNew+"?frame=1&amp;dashboard="+java.net.URLEncoder.encode(mfDefinition.getKey(),"UTF-8");DecimalFormat mfNumber=new DecimalFormat("#,##0");NewUiHybridMenuNode mfTarget=mfFunction.getTarget();boolean mfHasTarget=mfFunction.isOperationalRouteAvailable();boolean mfBranch=mfHasTarget&&mfTarget.isBranch();String mfParam=mfBranch?"groupMenuId":"menuId";String mfTargetShell=mfHasTarget?mfNew+"?"+mfParam+"="+mfTarget.getMenuId():mfNew+"?dashboard="+java.net.URLEncoder.encode(mfDefinition.getKey(),"UTF-8");String mfTargetFrame=mfHasTarget?mfNew+"?frame=1&amp;"+mfParam+"="+mfTarget.getMenuId():mfHome;
Tbmuser mfUser=null;try{mfUser=Common.getCurrentUser(request);}catch(Exception ignored){}List<NewUiActionDashboardMetricService.Metric> mfActionMetrics=NewUiActionDashboardMetricService.load(mfFunction.getSourceClass(),mfUser);
%>
<section class="nui-page nui-module-dashboard" data-module-dashboard="<%=mfH(mfDefinition.getKey())%>"><header class="nui-module-dashboard-hero"><div><div class="nui-breadcrumb"><a href="<%=mfHome%>"><%=mfH(mfShortcut.getLabel())%></a> / <%=mfH(mfFunction.getLabel())%></div><p class="nui-dashboard-eyebrow"><i class="fa-solid fa-code-branch"></i> FUNGSI NATIVE</p><h1><%=mfH(mfFunction.getLabel())%></h1><p><%=mfH(mfFunction.getDescription())%></p></div><div class="nui-dashboard-head-actions"><a class="nui-btn nui-btn-hero" href="<%=mfHome%>"><i class="fa-solid fa-arrow-left"></i> Kembali</a><%if(mfHasTarget){%><a class="nui-btn nui-btn-hero" target="nuiMainFrame" data-shell-url="<%=mfH(mfTargetShell)%>" href="<%=mfTargetFrame%>"><i class="fa-solid fa-arrow-up-right-from-square"></i> Buka Operasional</a><%}%></div></header>
<div class="nui-dashboard-filterbar"><label><i class="fa-solid fa-shield-halved"></i> Hanya data dan menu yang lolos role aktif</label><span class="nui-chip">Sumber: <%=mfH(mfFunction.getSourceClass())%></span></div>
<div class="nui-grid nui-grid-4 nui-dashboard-kpis"><%for(int mfI=0;mfI<mfMetrics.size();mfI++){Metric metric=mfMetrics.get(mfI);%><article class="nui-card nui-card-pad" data-dashboard-metric data-label="<%=mfH(metric.getLabel())%>" data-value="<%=metric.isAvailable()?metric.getValue():""%>"><div class="nui-stat"><div class="nui-stat-icon"><i class="<%=mfI==0?"fa-solid fa-database":mfI==1?"fa-solid fa-chart-column":mfI==2?"fa-solid fa-list-check":"fa-solid fa-circle-exclamation"%>"></i></div><div><div><%=mfH(metric.getLabel())%></div><div class="nui-stat-value"><%=metric.isAvailable()?mfNumber.format(metric.getValue()):"Tidak tersedia"%></div><div class="nui-stat-meta">Sumber entity existing</div><%if(metric.isStatusAvailable()){%><div class="nui-stat-meta"><span class="nui-status ok"><%=mfNumber.format(metric.getActiveValue())%> aktif</span> <span class="nui-status"><%=mfNumber.format(metric.getInactiveValue())%> nonaktif</span></div><%}%></div></div></article><%}%></div>
<section class="nui-dashboard-menu-catalog"><div class="nui-card-title">Data Action Existing <small><%=mfActionMetrics.size()%> entity terdeteksi langsung dari <%=mfH(mfFunction.getSourceClass())%></small></div><div class="nui-dashboard-feature-grid"><%if(mfActionMetrics.isEmpty()){%><div class="nui-card nui-card-pad"><strong>Tidak ada entity Hibernate langsung</strong><p class="nui-page-desc">Fungsi ini memakai helper, integrasi, atau menu operasional tanpa query entity langsung.</p></div><%}for(int mfA=0;mfA<mfActionMetrics.size();mfA++){NewUiActionDashboardMetricService.Metric actionMetric=mfActionMetrics.get(mfA);%><article class="nui-dashboard-feature"><span><i class="fa-solid fa-table-list"></i></span><div><strong><%=mfH(actionMetric.getLabel())%></strong><small><%=mfH(actionMetric.getEntityClass())%></small><em><%=actionMetric.isAvailable()?mfNumber.format(actionMetric.getValue())+" data sesuai scope":"Tidak tersedia"%></em></div></article><%}%></div></section>
<div class="nui-grid nui-grid-2 nui-dashboard-content-grid"><article class="nui-card nui-card-pad"><div class="nui-card-title">Kontrak Fungsi <small>Source of truth existing</small></div><div class="nui-detail-row"><span>Modul</span><strong><%=mfH(mfShortcut.getLabel())%></strong></div><div class="nui-detail-row"><span>Fungsi</span><strong><%=mfH(mfFunction.getLabel())%></strong></div><div class="nui-detail-row"><span>Kelas sumber</span><strong><%=mfH(mfFunction.getSourceClass())%></strong></div><div class="nui-detail-row"><span>Route operasional</span><strong><%=mfHasTarget?"Authorized New UI":"Ringkasan dashboard-only"%></strong></div></article><article class="nui-card nui-card-pad"><div class="nui-card-title">Akses Operasional <small>Tanpa ZUL</small></div><%if(mfHasTarget){%><p><%=mfH(mfTarget.getFullPath())%></p><a class="nui-btn nui-btn-primary" target="nuiMainFrame" data-shell-url="<%=mfH(mfTargetShell)%>" href="<%=mfTargetFrame%>">Buka <%=mfH(mfTarget.getLabel())%></a><%}else{%><div class="nui-empty"><div class="nui-empty-icon"><i class="fa-solid fa-chart-simple"></i></div><p>Fungsi ini merupakan ringkasan dashboard existing. Tidak ada menu operasional terpisah yang lolos RBAC untuk role aktif.</p></div><%}%></article></div>
<section class="nui-dashboard-menu-catalog"><div class="nui-card-title">Menu Terkait yang Dapat Diakses <small><%=mfMenus==null?0:mfMenus.size()%> menu dalam modul</small></div><div class="nui-page-catalog nui-dashboard-menu-grid"><%if(mfMenus!=null)for(int mfM=0;mfM<mfMenus.size();mfM++){NewUiHybridMenuNode node=mfMenus.get(mfM);boolean branch=node.isBranch();String param=branch?"groupMenuId":"menuId";String shell=mfNew+"?"+param+"="+node.getMenuId();String frame=mfNew+"?frame=1&amp;"+param+"="+node.getMenuId();%><a class="nui-page-link nui-leaf-card" target="nuiMainFrame" data-shell-url="<%=mfH(shell)%>" href="<%=frame%>"><span class="nui-leaf-icon"><i class="<%=branch?"fa-solid fa-folder-tree":"fa-solid fa-file-lines"%>"></i></span><span><strong><%=mfH(node.getLabel())%></strong><small><%=mfH(node.getParentPath())%></small></span><span class="nui-status <%=branch?"info":"ok"%>"><%=branch?"Subkelompok":"Buka"%></span></a><%}%></div></section></section>
