<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ page import="java.text.DecimalFormat" %><%@ page import="java.text.SimpleDateFormat" %><%@ page import="java.util.Date" %><%@ page import="java.util.List" %>
<%@ page import="ais.common.newui.menu.NewUiModuleDashboardService.Dashboard" %><%@ page import="ais.common.newui.menu.NewUiModuleDashboardService.Definition" %><%@ page import="ais.common.newui.menu.NewUiModuleDashboardService.Metric" %>
<%@ page import="ais.common.newui.menu.NewUiModuleShortcut" %><%@ page import="ais.common.newui.menu.NewUiHybridMenuNode" %>
<%!
private String mdH(Object value){if(value==null)return "";return String.valueOf(value).replace("&","&amp;").replace("<","&lt;").replace(">","&gt;").replace("\"","&quot;").replace("'","&#39;");}
%>
<%
Dashboard mdDashboard=(Dashboard)request.getAttribute("nuiActiveModuleDashboard");
NewUiModuleShortcut mdShortcut=(NewUiModuleShortcut)request.getAttribute("nuiActiveModuleShortcut");
Definition mdDefinition=mdDashboard.getDefinition();List<Metric> mdMetrics=mdDashboard.getMetrics();
NewUiHybridMenuNode mdTarget=mdShortcut.getTarget();boolean mdBranch=mdTarget!=null&&mdTarget.isBranch();
String mdTargetParam=mdBranch?"groupMenuId":"menuId";String mdNew=request.getContextPath()+"/new";
String mdTargetShell=mdTarget==null?mdNew:mdNew+"?"+mdTargetParam+"="+mdTarget.getMenuId();
String mdTargetFrame=mdTarget==null?mdNew+"?frame=1":mdNew+"?frame=1&amp;"+mdTargetParam+"="+mdTarget.getMenuId();
DecimalFormat mdNumber=new DecimalFormat("#,##0");SimpleDateFormat mdTime=new SimpleDateFormat("dd-MM-yyyy HH:mm:ss");
List<NewUiHybridMenuNode> mdMenus=(List<NewUiHybridMenuNode>)request.getAttribute("nuiActiveModuleMenus");if(mdMenus==null)mdMenus=new java.util.ArrayList<NewUiHybridMenuNode>();
%>
<section class="nui-page nui-module-dashboard" data-module-dashboard="<%=mdH(mdDefinition.getKey())%>">
  <header class="nui-module-dashboard-hero">
    <div><div class="nui-breadcrumb"><a href="<%=mdNew%>?frame=1">Beranda</a> / Aplikasi &amp; Modul / <%=mdH(mdShortcut.getLabel())%></div><p class="nui-dashboard-eyebrow"><i class="<%=mdH(mdShortcut.getIcon())%>"></i> DASHBOARD MODUL</p><h1><%=mdH(mdDefinition.getTitle())%></h1><p><%=mdH(mdDefinition.getDescription())%></p></div>
    <div class="nui-dashboard-head-actions"><button type="button" class="nui-btn nui-btn-hero" data-dashboard-refresh><i class="fa-solid fa-arrows-rotate"></i> Muat Ulang</button><button type="button" class="nui-btn nui-btn-hero" data-dashboard-export data-dashboard-title="<%=mdH(mdDefinition.getTitle())%>"><i class="fa-solid fa-file-csv"></i> Ekspor Ringkasan</button><a class="nui-btn nui-btn-hero" target="nuiMainFrame" data-shell-url="<%=mdH(mdTargetShell)%>" href="<%=mdTargetFrame%>"><i class="fa-solid fa-table-cells-large"></i> Buka Modul</a></div>
  </header>
  <div class="nui-dashboard-filterbar"><label><i class="fa-regular fa-calendar"></i> Data aktual dari database existing</label><span class="nui-chip">Diperbarui <%=mdH(mdTime.format(new Date(mdDashboard.getGeneratedAt())))%></span><a href="<%=mdNew%>?frame=1"><i class="fa-solid fa-arrow-left"></i> Kembali ke semua modul</a></div>
  <div class="nui-grid nui-grid-4 nui-dashboard-kpis">
  <%for(int mdI=0;mdI<mdMetrics.size();mdI++){Metric mdMetric=mdMetrics.get(mdI);%>
    <article class="nui-card nui-card-pad" data-dashboard-metric data-label="<%=mdH(mdMetric.getLabel())%>" data-value="<%=mdMetric.isAvailable()?mdMetric.getValue():""%>"><div class="nui-stat"><div class="nui-stat-icon"><i class="<%=mdI==0?"fa-solid fa-database":mdI==1?"fa-solid fa-chart-column":mdI==2?"fa-solid fa-list-check":"fa-solid fa-circle-exclamation"%>"></i></div><div><div><%=mdH(mdMetric.getLabel())%></div><div class="nui-stat-value"><%=mdMetric.isAvailable()?mdNumber.format(mdMetric.getValue()):"Tidak tersedia"%></div><div class="nui-stat-meta"><%=mdMetric.isAvailable()?"Data entity existing":"Entity tidak tersedia pada instalasi ini"%></div></div></div></article>
  <%}%>
  </div>
  <div class="nui-grid nui-grid-2 nui-dashboard-content-grid">
    <article class="nui-card nui-card-pad"><div class="nui-card-title">Cakupan Dashboard <small>Sesuai handler existing</small></div><div class="nui-dashboard-feature-grid"><%String[] mdFeatures=mdDefinition.getFeatures();for(int mdF=0;mdF<mdFeatures.length;mdF++){boolean mdTimeline="elearning".equals(mdDefinition.getKey())&&mdF==0;String mdFeatureShell=mdTimeline?mdNew+"?dashboard=elearning&dashboardView=linimasa":mdTargetShell;String mdFeatureFrame=mdTimeline?mdNew+"?frame=1&amp;dashboard=elearning&amp;dashboardView=linimasa":mdTargetFrame;%><a target="nuiMainFrame" data-shell-url="<%=mdH(mdFeatureShell)%>" href="<%=mdFeatureFrame%>" class="nui-dashboard-feature"><span><i class="<%=mdF==0?"fa-solid fa-gauge-high":mdF==1?"fa-solid fa-chart-line":mdF==2?"fa-solid fa-clock-rotate-left":"fa-solid fa-triangle-exclamation"%>"></i></span><div><strong><%=mdH(mdFeatures[mdF])%></strong><small><%=mdTimeline?"Buka Linimasa New UI":"Buka data dan tindakan terkait"%></small></div><i class="fa-solid fa-chevron-right"></i></a><%}%></div></article>
    <article class="nui-card nui-card-pad"><div class="nui-card-title">Status Integrasi <small>Native New UI</small></div><div class="nui-dashboard-health"><div class="nui-dashboard-health-ring"><strong>100%</strong><span>Native</span></div><div><div class="nui-detail-row"><span>Sumber logika</span><strong><%=mdH(mdDefinition.getSourceClass())%></strong></div><div class="nui-detail-row"><span>Sumber data</span><strong>Hibernate entity existing</strong></div><div class="nui-detail-row"><span>Hak akses</span><strong>Role + Menu + READ</strong></div><div class="nui-detail-row"><span>Tampilan ZK/ZUL</span><strong>Tidak digunakan</strong></div></div></div></article>
  </div>
  <section class="nui-dashboard-menu-catalog"><div class="nui-card-title">Daftar Menu <small><%=mdMenus.size()%> child dan sub-child sesuai role aktif</small></div><div class="nui-card nui-catalog-toolbar"><input id="nuiLeafSearch" class="nui-input" type="search" aria-controls="nuiLeafCatalog" placeholder="Cari menu dalam <%=mdH(mdShortcut.getLabel())%>..." autocomplete="off"><select id="nuiLeafSort" class="nui-select" aria-label="Urutan menu"><option value="order">Urutan Menu</option><option value="az">Nama A-Z</option></select></div>
  <%if(mdMenus.isEmpty()){%><div class="nui-card nui-empty"><div class="nui-empty-icon"><i class="fa-solid fa-folder-open"></i></div>Tidak ada child atau sub-child yang dapat diakses oleh role aktif.</div><%}else{%><div id="nuiLeafCatalog" class="nui-page-catalog nui-dashboard-menu-grid"><%for(int mdM=0;mdM<mdMenus.size();mdM++){NewUiHybridMenuNode mdMenu=mdMenus.get(mdM);boolean mdMenuBranch=mdMenu.isBranch();String mdMenuParam=mdMenuBranch?"groupMenuId":"menuId";String mdMenuShell=mdNew+"?"+mdMenuParam+"="+mdMenu.getMenuId();String mdMenuFrame=mdNew+"?frame=1&amp;"+mdMenuParam+"="+mdMenu.getMenuId();%><a class="nui-page-link nui-leaf-card<%=mdMenuBranch?" nui-menu-branch-card":""%>" data-search="<%=mdH(mdMenu.getSearchText())%>" data-label="<%=mdH(mdMenu.getLabel())%>" data-order="<%=mdM%>" data-path="<%=mdH(mdMenu.getFullPath())%>" target="nuiMainFrame" data-shell-url="<%=mdH(mdMenuShell)%>" href="<%=mdMenuFrame%>"><span class="nui-leaf-icon"><i class="<%=mdH(mdMenu.getIcon()==null||mdMenu.getIcon().trim().length()==0?(mdMenuBranch?"fa-solid fa-folder-tree":"fa-solid fa-file-lines"):mdMenu.getIcon())%>"></i></span><span><strong><%=mdH(mdMenu.getLabel())%></strong><small><%=mdH(mdMenu.getParentPath())%></small></span><span class="nui-status <%=mdMenuBranch?"info":"ok"%>"><%=mdMenuBranch?"Subkelompok":"Buka"%></span></a><%}%></div><div id="nuiLeafNoResult" class="nui-card nui-empty nui-leaf-no-result" hidden>Tidak ada menu yang cocok dengan pencarian.</div><%}%></section>
</section>
