<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ page import="java.security.SecureRandom" %><%@ page import="ais.common.newui.menu.NewUiModuleFunctionService.Function" %>
<%!
private String psH(Object value){if(value==null)return "";return String.valueOf(value).replace("&","&amp;").replace("<","&lt;").replace(">","&gt;").replace("\"","&quot;").replace("'","&#39;");}
private String psToken(){SecureRandom r=new SecureRandom();byte[] b=new byte[24];r.nextBytes(b);StringBuilder s=new StringBuilder();for(int i=0;i<b.length;i++)s.append(Integer.toHexString((b[i]&255)|256).substring(1));return s.toString();}
%>
<%
Function psFunction=(Function)request.getAttribute("nuiActiveModuleFunction");String psCsrf=(String)session.getAttribute("newUiCsrfToken");if(psCsrf==null){psCsrf=psToken();session.setAttribute("newUiCsrfToken",psCsrf);}String psEndpoint=request.getContextPath()+"/new?service=1&module=_shared&page=dashboard_function&dashboard=koperasi&dashboardView=shu";
%>
<section class="nui-page" id="nuiShuPage" data-endpoint="<%=psH(psEndpoint)%>" data-csrf="<%=psH(psCsrf)%>">
  <header class="nui-module-dashboard-hero"><div><div class="nui-breadcrumb">Koperasi / Pembagian SHU</div><p class="nui-dashboard-eyebrow"><i class="fa-solid fa-scale-balanced"></i> WORKFLOW NATIVE</p><h1><%=psH(psFunction.getLabel())%></h1><p>Logika hitung dan penyimpanan mengikuti <code>PembagianShuAction</code>, dengan transaksi, scope koperasi aktif, RBAC, dan CSRF.</p></div><a class="nui-btn nui-btn-hero" href="<%=request.getContextPath()%>/new?frame=1&amp;dashboard=koperasi"><i class="fa-solid fa-arrow-left"></i> Kembali</a></header>
  <article class="nui-card nui-card-pad"><form id="nuiShuForm"><div class="nui-form-grid"><div class="nui-field"><label>Tahun buku</label><input class="nui-input" type="number" name="year" min="1900" max="2200" required></div><div class="nui-field"><label>Total SHU hasil RAT</label><input class="nui-input" type="number" name="totalShu" min="0.01" step="0.01" required></div><div class="nui-field"><label>Cadangan (%)</label><input class="nui-input" type="number" name="cadangan" value="25" min="0" max="100" step="0.01"></div><div class="nui-field"><label>Jasa modal (%)</label><input class="nui-input" type="number" name="jasaModal" value="25" min="0" max="100" step="0.01"></div><div class="nui-field"><label>Jasa usaha (%)</label><input class="nui-input" type="number" name="jasaUsaha" value="30" min="0" max="100" step="0.01"></div><div class="nui-field"><label>Pendidikan (%)</label><input class="nui-input" type="number" name="pendidikan" value="10" min="0" max="100" step="0.01"></div><div class="nui-field"><label>Pengurus (%)</label><input class="nui-input" type="number" name="pengurus" value="5" min="0" max="100" step="0.01"></div><div class="nui-field"><label>Sosial (%)</label><input class="nui-input" type="number" name="sosial" value="5" min="0" max="100" step="0.01"></div><div class="nui-field"><label>Lain-lain (%)</label><input class="nui-input" type="number" name="lain" value="0" min="0" max="100" step="0.01"></div></div><div style="display:flex;gap:8px;justify-content:flex-end;margin-top:16px"><button class="nui-btn" type="button" id="nuiShuRefresh"><i class="fa-solid fa-rotate"></i> Segarkan</button><button class="nui-btn nui-btn-primary" type="submit"><i class="fa-solid fa-calculator"></i> Hitung &amp; Bagikan</button></div></form></article>
  <div class="nui-grid nui-grid-4 nui-dashboard-kpis" style="margin-top:14px"><article class="nui-card nui-card-pad"><small>Total SHU</small><strong class="nui-stat-value" id="nuiShuTotal">--</strong></article><article class="nui-card nui-card-pad"><small>Jasa Modal</small><strong class="nui-stat-value" id="nuiShuCapital">--</strong></article><article class="nui-card nui-card-pad"><small>Jasa Usaha</small><strong class="nui-stat-value" id="nuiShuBusiness">--</strong></article><article class="nui-card nui-card-pad"><small>Diterima Anggota</small><strong class="nui-stat-value" id="nuiShuDistributed">--</strong></article></div>
  <article class="nui-card" style="margin-top:14px"><div class="nui-toolbar"><input id="nuiShuSearch" class="nui-input" type="search" placeholder="Cari anggota..."><span id="nuiShuCount" class="nui-chip">0 anggota</span></div><div class="nui-table-wrap"><table class="nui-table"><thead><tr><th>Anggota</th><th>Total Simpanan</th><th>Partisipasi</th><th>Jasa Modal</th><th>Jasa Usaha</th><th>Total SHU</th><th>Dibayar</th></tr></thead><tbody id="nuiShuRows"><tr><td colspan="7">Memuat data...</td></tr></tbody></table></div></article>
</section>
<script>(function(){var root=document.getElementById('nuiShuPage'),form=document.getElementById('nuiShuForm'),rows=[],endpoint=root.dataset.endpoint,money=new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0});form.year.value=new Date().getFullYear();function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}function paint(data){var h=data.head||{};if(h.totalShu!=null){Object.keys(h).forEach(function(k){var e=form.elements[k];if(e)e.value=h[k]})}rows=data.rows||[];document.getElementById('nuiShuTotal').textContent=money.format(h.totalShu||0);document.getElementById('nuiShuCapital').textContent=money.format((h.totalShu||0)*(h.jasaModal||0)/100);document.getElementById('nuiShuBusiness').textContent=money.format((h.totalShu||0)*(h.jasaUsaha||0)/100);document.getElementById('nuiShuDistributed').textContent=money.format(data.distributed||0);filter()}function filter(){var q=document.getElementById('nuiShuSearch').value.toLowerCase(),view=rows.filter(function(r){return r.member.toLowerCase().indexOf(q)>=0}),html=view.map(function(r){return'<tr><td>'+esc(r.member)+'</td><td>'+money.format(r.savings)+'</td><td>'+money.format(r.participation)+'</td><td>'+money.format(r.capital)+'</td><td>'+money.format(r.business)+'</td><td><strong>'+money.format(r.total)+'</strong></td><td>'+(r.paid?'Sudah':'Belum')+'</td></tr>'}).join('');document.getElementById('nuiShuRows').innerHTML=html||'<tr><td colspan="7">Belum ada rincian SHU.</td></tr>';document.getElementById('nuiShuCount').textContent=view.length+' anggota'}async function load(){var r=await fetch(endpoint+'&action=list&year='+encodeURIComponent(form.year.value),{credentials:'same-origin'}),j=await r.json();if(!r.ok)throw new Error(j.message||'Gagal memuat SHU');paint(j)}form.addEventListener('submit',async function(e){e.preventDefault();try{var body=new URLSearchParams(new FormData(form)),r=await fetch(endpoint+'&action=calculate',{method:'POST',credentials:'same-origin',headers:{'X-CSRF-Token':root.dataset.csrf,'Content-Type':'application/x-www-form-urlencoded'},body:body}),j=await r.json();if(!r.ok)throw new Error(j.message||'Gagal menghitung SHU');paint(j);alert('Pembagian SHU berhasil dihitung dan disimpan.')}catch(x){alert(x.message)}});document.getElementById('nuiShuRefresh').onclick=function(){load().catch(function(x){alert(x.message)})};document.getElementById('nuiShuSearch').oninput=filter;form.year.onchange=function(){load().catch(function(x){alert(x.message)})};load().catch(function(x){document.getElementById('nuiShuRows').innerHTML='<tr><td colspan="7">'+esc(x.message)+'</td></tr>'})})();</script>
