<%-- @generated by generate_new_jsp_scaffold.py
Source: src/ais/action/master/rab/util/WorkspaceTreeModel.java
Generated: 2026-08-06T18:20:20Z
Safe service-adapter scaffold. Implement data access in a Java service layer, not directly in this JSP.
--%>
<%@ page language="java" contentType="application/json; charset=UTF-8" pageEncoding="UTF-8" %>
<%
request.setAttribute("nuiServiceModule", "rab");
request.setAttribute("nuiServicePage", "util/workspace_tree_model");
request.setAttribute("nuiServiceTitle", "Workspace Tree Model");
request.setAttribute("nuiServiceType", "finance");
request.setAttribute("nuiServiceSourceClass", "WorkspaceTreeModel");
request.setAttribute("nuiServiceSourcePackage", "ais.action.master.rab.util");
request.setAttribute("nuiServiceSourcePath", "src/ais/action/master/rab/util/WorkspaceTreeModel.java");
request.setAttribute("nuiServiceMethods", new String[]{"copy", "copyChild", "ubahRealisasiParents", "getChildCountById", "getRealisasiProses", "ubahHargaTotalParentss", "ubahHargaTotalParents", "ubahMulaiParents", "ubahSelesaiParents", "ubahKomplitParents", "ubahDurasiParents", "ubahPegawaisParents", "main", "checkForParent", "getCheckForLeafNulll", "getChildren", "getSatuChildren", "getChildrenIds", "sudahDigunakanTransaksi", "getChild", "getChildCount", "deleteChilds", "deleteChildsWithNativeSession", "getHargaTotal", "getHargaTotals", "getMaksimalSelesai", "getMinimalMulai", "getDurasi", "getPagawais", "getRealisasiSemuaTotal", "getRealisasiTotal", "generateChilds", "generateChildsByIds", "getHargaTotalRealisasiTiapBulan", "getHargaTotalPerencanaanTiapBulan", "getHargaTotalRealisasiTriWulan", "getHargaTotalPerencanaanTriWulan", "getRealisasi", "getJumlahJurnal", "isLeaf", "getParentCount", "getParentSet", "getParentSetName", "getChildDeepSet", "getIndexOfChild", "getTahunWorkspace", "checkBentrok", "getPersenKomplit", "getJenisWorkspace", "getSatuanKerjas", "getSatuanKerjaTreeModel"});
request.setAttribute("nuiServiceEntities", new String[]{"Workspace", "GrupTransaksi", "WorkspacePunyaPegawai", "Transaksi", "PenggunaanAnggaran"});
%>
<jsp:include page="/WEB-INF/new/_shared/services/dispatcher.jsp" />
