<%-- @generated by generate_new_jsp_scaffold.py
Source: src/ais/action/master/helper/penilaian/DownloadNilaiMahasiswaFormatEpsbed.java
Generated: 2026-08-06T18:20:20Z
Safe service-adapter scaffold. Implement data access in a Java service layer, not directly in this JSP.
--%>
<%@ page language="java" contentType="application/json; charset=UTF-8" pageEncoding="UTF-8" %>
<%
request.setAttribute("nuiServiceModule", "helper");
request.setAttribute("nuiServicePage", "penilaian/download_nilai_mahasiswa_format_epsbed");
request.setAttribute("nuiServiceTitle", "Download Nilai Mahasiswa Format EPSBED");
request.setAttribute("nuiServiceType", "integration");
request.setAttribute("nuiServiceSourceClass", "DownloadNilaiMahasiswaFormatEpsbed");
request.setAttribute("nuiServiceSourcePackage", "ais.action.master.helper.penilaian");
request.setAttribute("nuiServiceSourcePath", "src/ais/action/master/helper/penilaian/DownloadNilaiMahasiswaFormatEpsbed.java");
request.setAttribute("nuiServiceMethods", new String[]{"onEvent", "run"});
request.setAttribute("nuiServiceEntities", new String[]{"Detailperkuliahan"});
%>
<jsp:include page="/WEB-INF/new/_shared/services/dispatcher.jsp" />
