<%-- @generated by generate_new_jsp_scaffold.py
Source: src/ais/action/master/kursus/helper/KursusUtil.java
Generated: 2026-08-06T18:20:20Z
Safe service-adapter scaffold. Implement data access in a Java service layer, not directly in this JSP.
--%>
<%@ page language="java" contentType="application/json; charset=UTF-8" pageEncoding="UTF-8" %>
<%
request.setAttribute("nuiServiceModule", "kursus");
request.setAttribute("nuiServicePage", "helper/kursus_util");
request.setAttribute("nuiServiceTitle", "Kursus Util");
request.setAttribute("nuiServiceType", "academic");
request.setAttribute("nuiServiceSourceClass", "KursusUtil");
request.setAttribute("nuiServiceSourcePackage", "ais.action.master.kursus.helper");
request.setAttribute("nuiServiceSourcePath", "src/ais/action/master/kursus/helper/KursusUtil.java");
request.setAttribute("nuiServiceMethods", new String[]{"reloadFormula", "onEvent", "reloadDetail", "reloadDataFormula"});
request.setAttribute("nuiServiceEntities", new String[]{"TipePeserta", "JenisIdentitasPeserta", "JenisPeserta", "KomponenDataProdukKursus", "KomponenProdukKursus"});
%>
<jsp:include page="/WEB-INF/new/_shared/services/dispatcher.jsp" />
