<%-- @generated by generate_new_jsp_scaffold.py
Source: src/ais/action/master/sapto/util/SaptoGridConfig.java
Generated: 2026-08-06T18:20:20Z
Safe service-adapter scaffold. Implement data access in a Java service layer, not directly in this JSP.
--%>
<%@ page language="java" contentType="application/json; charset=UTF-8" pageEncoding="UTF-8" %>
<%
request.setAttribute("nuiServiceModule", "sapto");
request.setAttribute("nuiServicePage", "util/sapto_grid_config");
request.setAttribute("nuiServiceTitle", "SAPTO Grid Config");
request.setAttribute("nuiServiceType", "integration");
request.setAttribute("nuiServiceSourceClass", "SaptoGridConfig");
request.setAttribute("nuiServiceSourcePackage", "ais.action.master.sapto.util");
request.setAttribute("nuiServiceSourcePath", "src/ais/action/master/sapto/util/SaptoGridConfig.java");
request.setAttribute("nuiServiceMethods", new String[]{"getConfig"});
request.setAttribute("nuiServiceLegacyRefs", new String[]{});
request.setAttribute("nuiServiceEntities", new String[]{});
%>
<jsp:include page="/WEB-INF/new/_shared/services/dispatcher.jsp" />
