package ais.database.model.employ;

// Generated Apr 16, 2010 2:27:16 PM by Hibernate Tools 3.2.4.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;




import org.hibernate.envers.Audited;

import ais.database.model.GeneralValueObject;



/**
 * Bank generated by hbm2java
 *
 * <p>Entity master data kepegawaian (tabel {@code employ.jabatan_fungsional_tambahan}) yang
 * mendaftarkan komponen "jabatan fungsional tambahan" — sebuah kelompok tunjangan tambahan yang
 * TERPISAH dari {@link JabatanFungsional} biasa, masing-masing membawa SATU nilai tunjangan tetap
 * lewat {@link #getTunjanganFungsionalTambahan()}. Javadoc lama "Bank generated by hbm2java" adalah
 * sisa salin-tempel generator hbm2java dari kelas lain (kelas ini tidak berhubungan dengan entity
 * Bank) — dibiarkan apa adanya sesuai aturan "jangan mengurangi javadoc lama", diperkaya dengan
 * javadoc ini.</p>
 *
 * <h2>TIDAK terhubung ke mesin formula gaji</h2>
 * <p>Berbeda dari {@link JabatanStruktural} dan {@link JabatanFungsional} — yang keduanya
 * dikonfirmasi dipanggil langsung oleh {@code ItemGajiPegawaiTreeModel} lewat method statis
 * {@code ambilTunjangans(...)} untuk me-resolve token formula {@code TUNJ_SRTK_*}/{@code
 * TUNJ_FUNG_*} — kelas ini TIDAK memiliki method {@code ambilTunjangan}/{@code ambilTunjangans}
 * sama sekali, dan penelusuran seluruh kode sumber ({@code ais.action.master.payroll.*}) tidak
 * menemukan satu pun referensi ke {@code JabatanFungsionalTambahan} di luar layar CRUD-nya sendiri
 * ({@code ais.action.master.employ.JabatanFungsionalTambahanAction}) dan DAO-nya
 * ({@code ais.database.dao.employ.JabatanFungsionalTambahanDaoImpl}). Dengan kata lain, field
 * {@link #getTunjanganFungsionalTambahan()} yang diisi lewat layar CRUD saat ini TIDAK pernah
 * dibaca/dijumlahkan oleh mesin formula gaji {@code payroll} — berbeda dari saudara-saudaranya di
 * paket {@code employ} yang nilainya benar-benar menjadi bagian perhitungan gaji pegawai. Field
 * ini kemungkinan berupa data referensi yang disiapkan untuk kebutuhan mendatang atau dikonsumsi
 * lewat jalur laporan/tampilan lain di luar formula {@code exp4j}; VERIFIKASI ulang bila hendak
 * mengandalkan entity ini sebagai bagian perhitungan gaji aktif.</p>
 *
 * <p>Perhatikan pula bahwa struktur nilai tunjangan di sini jauh lebih sederhana daripada
 * {@link JabatanStruktural}/{@link JabatanFungsional}: tidak ada riwayat JSON multi-tanggal/
 * multi-sub-kode, hanya SATU kolom {@link Double} tunggal tanpa riwayat efektif — perubahan nilai
 * tunjangan tambahan langsung menimpa nilai lama tanpa jejak kapan nilai sebelumnya berlaku.</p>
 *
 * <p>Layar CRUD-nya adalah {@code JabatanFungsionalTambahanAction}. Entity ini tidak membawa
 * filter tenant/satuan-kerja eksplisit di levelnya sendiri.</p>
 */
@Entity
@org.hibernate.annotations.Entity(
    dynamicInsert = true,
    dynamicUpdate = true
)
@Audited
@Table(schema = "employ", name = "jabatan_fungsional_tambahan")



public class JabatanFungsionalTambahan extends GeneralValueObject {

	/**
	 * Versi serialisasi entity ini untuk kompatibilitas Java serialization. Object entity AIS
	 * diserialkan ke cache MapDB dan session ZK, sehingga nilai ini jangan diubah tanpa alasan
	 * kuat — mengubahnya membuat data ter-cache lama tidak terbaca lagi
	 * ({@code InvalidClassException}) setelah deploy.
	 */
	private static final long serialVersionUID = 2463821577548439808L;
	/** Primary key entity. Lihat {@link #getId()}. */
	private Long id;
	/**
	 * Nama pengguna terakhir yang mengubah entity ini. Field ini meng-hide field privat bernama
	 * sama di {@link GeneralValueObject}: karena kelas induk tersebut bukan
	 * {@code @Entity}/{@code @MappedSuperclass}, field yang dideklarasikannya tidak otomatis
	 * dipetakan Hibernate — setiap entity turunan wajib mendeklarasikan ulang field beserta
	 * getter/setter-nya sendiri agar benar-benar tersimpan sebagai kolom. Pola ini berulang di
	 * hampir seluruh entity AIS (kebutuhan teknis, bukan bug). Diisi otomatis lewat
	 * {@link #onUpdate()} setiap kali entity di-{@code UPDATE}.
	 */
	private String oleh;
	/**
	 * Id pengguna terakhir yang mengubah entity ini. Sama seperti {@link #oleh}, field ini
	 * meng-hide field privat bernama sama di {@link GeneralValueObject} demi pemetaan Hibernate.
	 * Diisi otomatis lewat {@link #onUpdate()}.
	 */
	private String olehId;

	/**
	 * Mengembalikan id pengguna yang terakhir mengubah entity ini.
	 *
	 * @return id pengguna pengubah terakhir, atau {@code null} bila belum pernah terisi
	 */
	public String getOlehId() {
		return olehId;
	}

	/**
	 * Menyetel id pengguna pengubah terakhir, dengan validasi non-trivial: nilai {@code null} atau
	 * string kosong/hanya-spasi diabaikan diam-diam. Konsekuensinya nilai lama tidak pernah bisa
	 * dihapus lewat setter ini — perilaku ini disengaja (mengikuti kontrak
	 * {@link GeneralValueObject#setOlehId(String)}) agar jejak audit yang sudah terisi tidak
	 * terhapus oleh jalur simpan yang kebetulan tidak membawa informasi pengguna.
	 *
	 * @param olehId id pengguna pengubah; diabaikan bila {@code null}/kosong
	 */
	public void setOlehId(String olehId) {
		if (olehId == null || olehId.trim().isEmpty()) {
			return;
		}
		this.olehId = olehId;
	}

	/**
	 * Menyetel nama pengguna pengubah terakhir, dengan validasi non-trivial yang sama seperti
	 * {@link #setOlehId(String)}: nilai {@code null}/kosong diabaikan diam-diam sehingga jejak
	 * audit yang sudah terisi tidak bisa terhapus tanpa sengaja.
	 *
	 * @param oleh nama pengguna pengubah; diabaikan bila {@code null}/kosong
	 */
	public void setOleh(String oleh) {
		if (oleh == null || oleh.trim().isEmpty()) {
			return;
		}
		this.oleh = oleh;
	}

	/**
	 * Mengembalikan nama pengguna yang terakhir mengubah entity ini.
	 *
	 * @return nama pengguna pengubah terakhir, atau {@code null} bila belum pernah terisi
	 */
	public String getOleh() {
		return oleh;
	}

	/**
	 * Hook siklus-hidup JPA {@code @PreUpdate}: dipanggil otomatis oleh provider persistence tepat
	 * sebelum statement {@code UPDATE} dikirim ke database setiap kali entity ini diubah dan
	 * disimpan lewat session Hibernate yang aktif. Satu-satunya isi method ini adalah delegasi ke
	 * {@code ais.database.hibernate.AuditTimestampInterceptor.ubah(this)}, pola audit-timestamp
	 * standar yang diulang di hampir seluruh entity AIS. Efeknya: {@link #setTanggal_dirubah}
	 * diisi waktu server saat ini, dan {@link #setOleh}/{@link #setOlehId} diisi identitas
	 * pengguna yang sedang login — karena kedua setter itu mengabaikan nilai {@code null}/kosong,
	 * hook ini tidak pernah bisa menghapus jejak audit yang sudah ada.
	 */
	@javax.persistence.PreUpdate
	protected void onUpdate() {
		ais.database.hibernate.AuditTimestampInterceptor.ubah(this);
	}

	/**
	 * Stempel waktu perubahan terakhir. Diinisialisasi ke waktu pembuatan object memakai
	 * {@code WaktuUtil.getDate()} (jam server aplikasi, bukan jam database), sehingga entity baru
	 * yang belum pernah disimpan tetap punya nilai walau jalur simpan lupa mengisinya secara
	 * eksplisit. Field ini juga meng-hide field bernama sama di {@link GeneralValueObject}.
	 */
	private Date tanggal_dirubah = ais.ui.util.WaktuUtil.getDate();

	/**
	 * Menyetel stempel waktu perubahan terakhir. Tanpa validasi; nilai {@code null} diterima apa
	 * adanya.
	 *
	 * @param tanggal_dirubah waktu perubahan terakhir
	 */
	public void setTanggal_dirubah(Date tanggal_dirubah) {
		this.tanggal_dirubah = tanggal_dirubah;
	}

	/**
	 * Mengembalikan stempel waktu perubahan terakhir, dipetakan sebagai kolom {@code TIMESTAMP}
	 * ({@code @Temporal(TemporalType.TIMESTAMP)}) sehingga bagian jam ikut tersimpan.
	 *
	 * @return waktu perubahan terakhir; tidak pernah {@code null} kecuali sengaja disetel demikian
	 *         lewat {@link #setTanggal_dirubah(Date)}
	 */
	@Temporal(TemporalType.TIMESTAMP)
	public Date getTanggal_dirubah() {
		return tanggal_dirubah;
	}

	/**
	 * Representasi teks singkat entity ini untuk keperluan debug/log/tampilan combobox: nama
	 * jabatan fungsional tambahan apa adanya (tanpa trim, berbeda dari {@link #getNama()}).
	 *
	 * @return nama jabatan fungsional tambahan, bisa {@code null} bila belum pernah diisi
	 */
	public String toString() {
		return nama;
	}

	/** Nama komponen jabatan fungsional tambahan; lihat {@link #getNama()} untuk perilaku trim saat dibaca. */
	private String nama;
	/** Keterangan bebas komponen ini; lihat {@link #getKeterangan()}. */
	private String keterangan;
	/**
	 * Nilai tunjangan tetap komponen ini, TANPA riwayat efektif bertanggal (berbeda dari
	 * {@link JabatanStruktural#getTunjangans()}/{@link JabatanFungsional#getTunjangans()} yang
	 * berupa JSON array riwayat). Lihat dokumentasi kelas soal field ini yang TIDAK terhubung ke
	 * mesin formula gaji {@code payroll}.
	 */
	private Double tunjanganFungsionalTambahan;

	/**
	 * Constructor default tanpa argumen, dibutuhkan Hibernate untuk membuat instance saat hidrasi
	 * entity dari hasil query.
	 */
	public JabatanFungsionalTambahan() {
	}

	/**
	 * Mengembalikan primary key entity, kolom identity ({@code insertable = false}, digenerasi
	 * database) dari tabel {@code employ.jabatan_fungsional_tambahan}.
	 *
	 * @return primary key, atau {@code null} bila entity belum pernah disimpan
	 */
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", insertable = false, unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	/**
	 * Menyetel primary key entity. Tanpa validasi; normalnya tidak perlu dipanggil manual karena
	 * kolomnya {@code insertable = false}, kecuali saat membuat object "penunjuk" (hanya berisi id)
	 * untuk keperluan kriteria/relasi.
	 *
	 * @param id nilai primary key baru
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * Mengembalikan nama komponen jabatan fungsional tambahan, sudah di-trim.
	 *
	 * @return nama yang sudah di-trim, atau {@code null} bila kolom {@code null}
	 */
	@Column(name = "nama", nullable = false, length = 255)
	public String getNama() {
		return this.nama == null ? null : this.nama.trim();
	}

	/**
	 * Menyetel nama komponen jabatan fungsional tambahan. Tanpa validasi/trim di sisi setter; kolom
	 * dipetakan {@code nullable = false} sehingga validasi wajib-isi ditegakkan di layar CRUD.
	 *
	 * @param nama nama komponen baru
	 */
	public void setNama(String nama) {
		this.nama = nama;
	}

	/**
	 * Mengembalikan keterangan bebas komponen ini, apa adanya tanpa trim.
	 *
	 * @return keterangan, boleh {@code null}
	 */
	@Column(name = "keterangan", nullable = true)
	public String getKeterangan() {
		return this.keterangan;
	}

	/**
	 * Menyetel keterangan bebas komponen ini.
	 *
	 * @param keterangan keterangan baru; boleh {@code null}
	 */
	public void setKeterangan(String keterangan) {
		this.keterangan = keterangan;
	}

	/**
	 * Mengembalikan nilai tunjangan tetap komponen ini apa adanya, tanpa default (bisa
	 * {@code null} bila belum pernah diisi). Lihat dokumentasi kelas: nilai ini TIDAK dikonsumsi
	 * mesin formula gaji {@code payroll} saat ini — hanya tersimpan dan ditampilkan lewat layar
	 * CRUD {@code JabatanFungsionalTambahanAction}.
	 *
	 * @return nilai tunjangan tetap, atau {@code null} bila belum diisi
	 */
	@Column(name="tunjangan_fungsional_tambahan")
	public Double getTunjanganFungsionalTambahan() {
		return tunjanganFungsionalTambahan;
	}

	/**
	 * Menyetel nilai tunjangan tetap komponen ini. Tanpa validasi (mis. tidak menolak nilai
	 * negatif).
	 *
	 * @param tunjanganFungsionalTambahan nilai tunjangan tetap baru; boleh {@code null}
	 */
	public void setTunjanganFungsionalTambahan(
			Double tunjanganFungsionalTambahan) {
		this.tunjanganFungsionalTambahan = tunjanganFungsionalTambahan;
	}



}
