package ais.database.model.employ;

// Generated Apr 16, 2010 2:27:16 PM by Hibernate Tools 3.2.4.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Calendar;
import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.envers.Audited;

import ais.common.Common;
import ais.database.model.GeneralValueObject;
import ais.database.model.Pegawai;



/**
 * Entity JPA/Hibernate yang memetakan tabel {@code employ.riwayat_organisasi_sekolah_pegawai},
 * mencatat satu baris riwayat keanggotaan/aktivitas organisasi kesiswaan (sekolah, di bawah
 * jenjang kampus) milik seorang {@link Pegawai} — nama organisasi, kedudukan/jabatan, periode,
 * dan rentang tahun keikutsertaan.
 *
 * <p>Anggota klaster "riwayat pegawai" di paket {@code ais.database.model.employ}; lihat
 * javadoc {@link RiwayatKerjaPegawai} untuk penjelasan lengkap pola arsitektur bersama (field
 * audit shadow {@code oleh}/{@code olehId}, timestamp otomatis {@code tanggal_dirubah} lewat
 * {@link #onUpdate()}, fallback {@code pegawai} ke pengguna saat ini, flag {@code status}
 * dengan null-guard, dan {@code serialVersionUID} yang dibagi identik lintas kelas).
 *
 * <p><b>Struktur field kelas ini nyaris identik dengan {@link RiwayatOrganisasiKampusPegawai}
 * dan {@link RiwayatOrganisasiLainPegawai}</b> (sama-sama punya {@code nama}, {@code kedudukan},
 * {@code tahunMulai}, {@code tahunSelesai}, {@code alamat}, {@code pimpinan}, {@code status},
 * {@code periode}) — namun {@link #getPegawai()} di kelas ini MENGIKUTI pola klaster standar
 * (memanggil {@code check(pegawai)} lalu fallback ke
 * {@link Common#getCurrentUser()}{@code .getPegawai()}, fetch {@code LAZY} polos), BERBEDA dari
 * {@link RiwayatOrganisasiKampusPegawai#getPegawai()} yang tidak memiliki keduanya (lihat
 * peringatan lengkap di javadoc kelas tersebut). Ini contoh nyata pentingnya memverifikasi
 * kode aktual per-kelas: dua kelas dengan nama sangat mirip (Kampus vs Sekolah) dan field yang
 * identik ternyata berbeda perilaku pada method paling penting dalam entity ini.
 *
 * <p><b>Catatan format berkas:</b> deklarasi field {@code oleh}/{@code olehId} beserta getter
 * dan setter-nya pada sumber asli kelas ini digabung menjadi satu baris tunggal yang sangat
 * padat, sama seperti pada {@link RiwayatPelatihanPegawai} dan
 * {@link RiwayatOrganisasiKampusPegawai}. Format ditata ulang di sini menjadi satu deklarasi
 * per baris semata-mata agar setiap elemen dapat diberi Javadoc sendiri — TIDAK ada perubahan
 * semantik.
 *
 * <p>Cakupan penggunaan nyata: dirujuk aktif oleh
 * {@code ais.action.master.employ.RiwayatOrganisasiSekolahPegawaiAction} dan
 * {@code ais.action.master.employ.helper.RiwayatOrganisasiSekolahPegawaiHelper} — bukan entity
 * yatim.
 *
 * Bank generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Entity(
    dynamicInsert = true,
    dynamicUpdate = true
)
@Audited
@Table(schema = "employ", name = "riwayat_organisasi_sekolah_pegawai")



public class RiwayatOrganisasiSekolahPegawai extends GeneralValueObject {

	/**
	 * Versi serialisasi tetap, identik dengan seluruh anggota klaster riwayat pegawai lainnya.
	 * Lihat catatan di javadoc {@link RiwayatKerjaPegawai} mengenai asal-usulnya.
	 */
	private static final long serialVersionUID = 2463821577548439808L;
	/** Primary key baris riwayat organisasi sekolah, dibangkitkan otomatis oleh database (IDENTITY). Lihat {@link #getId()}. */
	private Long id;
	/** Nama pengguna yang terakhir mengubah baris ini — field audit shadow, lihat {@link #getOleh()}. */
	private String oleh;
	/** Id pengguna yang terakhir mengubah baris ini — field audit shadow, lihat {@link #getOlehId()}. */
	private String olehId;

	/**
	 * Mengembalikan id pengguna yang tercatat terakhir kali mengubah baris riwayat organisasi
	 * sekolah ini. Field audit shadow murni tekstual, tidak divalidasi terhadap tabel pengguna —
	 * lihat penjelasan lengkap pola ini di {@link RiwayatKerjaPegawai#getOlehId()}.
	 *
	 * @return id pengguna terakhir yang mengubah, atau {@code null} bila belum pernah diisi.
	 */
	public String getOlehId() {return olehId;}

	/**
	 * Mengisi id pengguna pengubah terakhir. Seperti anggota klaster lain, setter ini
	 * mengabaikan diam-diam nilai {@code null} atau string kosong/whitespace-only — tidak bisa
	 * dipakai untuk mengosongkan kembali nilai yang sudah tersimpan. Lihat
	 * {@link RiwayatKerjaPegawai#setOlehId(String)} untuk penjelasan lengkap.
	 *
	 * @param olehId id pengguna pengubah; nilai null/kosong diabaikan tanpa efek.
	 */
	public void setOlehId(String olehId) {if (olehId == null || olehId.trim().isEmpty()) {return;}this.olehId = olehId;}

	/**
	 * Mengisi nama pengguna pengubah terakhir; berlaku aturan pengabaian null/kosong yang sama
	 * dengan {@link #setOlehId(String)}.
	 *
	 * @param oleh nama pengguna pengubah; nilai null/kosong diabaikan tanpa efek.
	 */
	public void setOleh(String oleh) {if (oleh == null || oleh.trim().isEmpty()) {return;}
		this.oleh = oleh;
	}

	/**
	 * Mengembalikan nama pengguna yang tercatat terakhir kali mengubah baris riwayat organisasi
	 * sekolah ini.
	 *
	 * @return nama pengguna terakhir yang mengubah, atau {@code null} bila belum pernah diisi.
	 */
	public String getOleh() {
		return oleh;
	}

	/**
	 * Hook siklus hidup JPA {@code @PreUpdate}, dipanggil otomatis oleh Hibernate sebelum
	 * statement UPDATE dieksekusi, mendelegasikan pencatatan stempel waktu ke
	 * {@code AuditTimestampInterceptor.ubah(this)}. Lihat javadoc
	 * {@link RiwayatKerjaPegawai#onUpdate()} untuk penjelasan lengkap mengenai dua jalur
	 * penulisan {@link #tanggal_dirubah} dan implikasinya.
	 */
	@javax.persistence.PreUpdate protected void onUpdate() { ais.database.hibernate.AuditTimestampInterceptor.ubah(this);}     private Date tanggal_dirubah = ais.ui.util.WaktuUtil.getDate();

	/**
	 * Mengatur stempel waktu perubahan terakhir secara manual, memotong jalur otomatis.
	 *
	 * @param tanggal_dirubah stempel waktu perubahan baru.
	 */
	public void setTanggal_dirubah(Date tanggal_dirubah) {
		this.tanggal_dirubah = tanggal_dirubah;
	}

	/**
	 * Mengembalikan stempel waktu perubahan terakhir baris riwayat organisasi sekolah ini.
	 *
	 * @return tanggal-waktu perubahan terakhir (tipe {@code TIMESTAMP} di database).
	 */
	@Temporal(TemporalType.TIMESTAMP)
	public Date getTanggal_dirubah() {
		return tanggal_dirubah;
	}

	/**
	 * Representasi string default entity ini, mengembalikan field {@link #keterangan} apa
	 * adanya. Dapat mengembalikan {@code null} bila {@link #keterangan} belum diisi — lihat
	 * peringatan lengkap di {@link RiwayatKerjaPegawai#toString()}.
	 *
	 * @return isi field {@link #keterangan}, dapat berupa {@code null}.
	 */
	public String toString() {
		return keterangan;
	}

	/** Catatan/keterangan bebas mengenai baris riwayat organisasi sekolah ini; lihat {@link #getKeterangan()}. */
	private String keterangan;

	/** Pegawai pemilik baris riwayat organisasi sekolah ini; lihat {@link #getPegawai()}. */
	private Pegawai pegawai;

	/** Nama organisasi sekolah pada riwayat ini; lihat {@link #getNama()}. */
	private String nama;
	/** Kedudukan/jabatan pegawai di organisasi tersebut; lihat {@link #getKedudukan()}. */
	private String kedudukan;
	/** Tahun mulai keanggotaan di organisasi tersebut, default tahun berjalan; lihat {@link #getTahunMulai()}. */
	private Integer tahunMulai = ais.ui.util.WaktuUtil.getCalendar().get(Calendar.YEAR);
	/** Tahun selesai keanggotaan di organisasi tersebut, default tahun berjalan; lihat {@link #getTahunSelesai()}. */
	private Integer tahunSelesai = ais.ui.util.WaktuUtil.getCalendar().get(Calendar.YEAR);
	/** Alamat organisasi sekolah tersebut; lihat {@link #getAlamat()}. */
	private String alamat;
	/** Nama pimpinan organisasi sekolah tersebut; lihat {@link #getPimpinan()}. */
	private String pimpinan;
	/** Flag status baris riwayat organisasi sekolah ini; default {@code false}, lihat {@link #getStatus()}. */
	private Boolean status = false;
	/** Periode kepengurusan/keanggotaan pada organisasi tersebut; lihat {@link #getPeriode()}. */
	private String periode;

	/**
	 * Mengembalikan {@link Pegawai} pemilik baris riwayat organisasi sekolah ini, dengan
	 * resolusi proxy lewat {@code check()} lalu fallback ke
	 * {@link Common#getCurrentUser()}{@code .getPegawai()} bila hasilnya masih {@code null},
	 * dibungkus try/catch yang menelan seluruh exception ke {@code ErrorAuditUtil.record(...)}.
	 * Pola sama persis dengan {@link RiwayatKerjaPegawai#getPegawai()} — lihat javadoc method
	 * tersebut untuk penjelasan lengkap. BERBEDA dari
	 * {@link RiwayatOrganisasiKampusPegawai#getPegawai()} meski struktur field kedua kelas
	 * nyaris identik — lihat peringatan di javadoc kelas tersebut.
	 *
	 * <p>Relasi {@code @ManyToOne} dengan {@code cascade = {PERSIST, MERGE}},
	 * {@code fetch = FetchType.LAZY}, kolom join {@code pegawai} {@code nullable = false}.
	 *
	 * @return pegawai pemilik riwayat organisasi sekolah ini, atau {@code null} bila resolusi
	 *         dan fallback keduanya gagal.
	 */
	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY)
	@JoinColumn(name = "pegawai", nullable = false)
	public Pegawai getPegawai() {
		pegawai = check(pegawai);

		try {
			if (pegawai == null) {
				pegawai = Common.getCurrentUser().getPegawai();
			}
		} catch (Exception e) { ais.common.ErrorAuditUtil.record(e, "auto-audit(empty-catch) src/ais/database/model/employ/RiwayatOrganisasiSekolahPegawai.java:97");

		}

		return pegawai;
	}

	/**
	 * Mengisi field {@link Pegawai} pemilik baris riwayat organisasi sekolah ini secara
	 * langsung, tanpa validasi.
	 *
	 * @param pegawai pegawai pemilik baris riwayat organisasi sekolah ini.
	 */
	public void setPegawai(Pegawai pegawai) {
		this.pegawai = pegawai;
	}

	/**
	 * Mengembalikan alamat organisasi sekolah pada riwayat ini, dipetakan ke kolom
	 * {@code alamat_}, {@code nullable = false} di level skema.
	 *
	 * @return alamat organisasi sekolah.
	 */
	@Column(name = "alamat_", nullable = false)
	public String getAlamat() {
		return alamat;
	}

	/**
	 * Mengisi alamat organisasi sekolah pada riwayat ini.
	 *
	 * @param alamat alamat organisasi baru.
	 */
	public void setAlamat(String alamat) {
		this.alamat = alamat;
	}

	/**
	 * Constructor default tanpa argumen, dibutuhkan oleh spesifikasi JPA/Hibernate untuk
	 * instansiasi reflektif entity ini.
	 */
	public RiwayatOrganisasiSekolahPegawai() {
	}

	/**
	 * Mengembalikan primary key baris riwayat organisasi sekolah ini, dibangkitkan otomatis
	 * oleh database lewat strategi {@link javax.persistence.GenerationType#IDENTITY}.
	 *
	 * @return id baris, atau {@code null} untuk entity yang belum pernah disimpan.
	 */
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", insertable = false, unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	/**
	 * Mengisi id baris riwayat organisasi sekolah secara manual. Kolom {@code id} dipetakan
	 * {@code insertable = false} sehingga pengisian di sini tidak terbawa ke statement INSERT.
	 *
	 * @param id id baris yang ingin diset.
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * Mengembalikan catatan/keterangan bebas mengenai baris riwayat organisasi sekolah ini.
	 *
	 * @return isi keterangan, dapat berupa {@code null}.
	 */
	@Column(name = "keterangan", nullable = true)
	public String getKeterangan() {
		return this.keterangan;
	}

	/**
	 * Mengisi catatan/keterangan bebas mengenai baris riwayat organisasi sekolah ini.
	 *
	 * @param keterangan teks keterangan baru, boleh {@code null}.
	 */
	public void setKeterangan(String keterangan) {
		this.keterangan = keterangan;
	}

	/**
	 * Mengembalikan nama organisasi sekolah pada riwayat ini.
	 *
	 * @return nama organisasi sekolah.
	 */
	public String getNama() {
		return nama;
	}

	/**
	 * Mengisi nama organisasi sekolah pada riwayat ini.
	 *
	 * @param nama nama organisasi baru.
	 */
	public void setNama(String nama) {
		this.nama = nama;
	}

	/**
	 * Mengembalikan kedudukan/jabatan pegawai di organisasi sekolah pada riwayat ini.
	 *
	 * @return kedudukan/jabatan di organisasi tersebut.
	 */
	public String getKedudukan() {
		return kedudukan;
	}

	/**
	 * Mengisi kedudukan/jabatan pegawai di organisasi sekolah pada riwayat ini.
	 *
	 * @param kedudukan kedudukan/jabatan baru.
	 */
	public void setKedudukan(String kedudukan) {
		this.kedudukan = kedudukan;
	}

	/**
	 * Mengembalikan tahun mulai keanggotaan di organisasi sekolah pada riwayat ini,
	 * diinisialisasi eager ke tahun kalender berjalan saat objek dikonstruksi.
	 *
	 * @return tahun mulai keanggotaan.
	 */
	public Integer getTahunMulai() {
		return tahunMulai;
	}

	/**
	 * Mengisi tahun mulai keanggotaan di organisasi sekolah pada riwayat ini.
	 *
	 * @param tahunMulai tahun mulai baru.
	 */
	public void setTahunMulai(Integer tahunMulai) {
		this.tahunMulai = tahunMulai;
	}

	/**
	 * Mengembalikan tahun selesai keanggotaan di organisasi sekolah pada riwayat ini,
	 * diinisialisasi eager ke tahun kalender berjalan saat objek dikonstruksi.
	 *
	 * @return tahun selesai keanggotaan.
	 */
	public Integer getTahunSelesai() {
		return tahunSelesai;
	}

	/**
	 * Mengisi tahun selesai keanggotaan di organisasi sekolah pada riwayat ini.
	 *
	 * @param tahunSelesai tahun selesai baru.
	 */
	public void setTahunSelesai(Integer tahunSelesai) {
		this.tahunSelesai = tahunSelesai;
	}

	/**
	 * Mengembalikan nama pimpinan organisasi sekolah pada riwayat ini.
	 *
	 * @return nama pimpinan organisasi tersebut.
	 */
	public String getPimpinan() {
		return pimpinan;
	}

	/**
	 * Mengisi nama pimpinan organisasi sekolah pada riwayat ini.
	 *
	 * @param pimpinan nama pimpinan baru.
	 */
	public void setPimpinan(String pimpinan) {
		this.pimpinan = pimpinan;
	}

	/**
	 * Mengembalikan flag status baris riwayat organisasi sekolah ini, dengan null-guard yang
	 * menuliskan ulang field ke {@code false} bila bernilai {@code null} sebelum
	 * mengembalikannya — pola yang sama persis dengan {@link RiwayatKerjaPegawai#getStatus()}.
	 * Default {@code false} di sini SAMA dengan mayoritas anggota klaster, BERBEDA dengan
	 * {@link RiwayatKartuIdentitasPegawai#getStatus()} yang men-default {@code true}.
	 *
	 * @return status baris riwayat organisasi sekolah ini, tidak pernah {@code null}.
	 */
	public Boolean getStatus() {
		if (status == null) {
			status = false;
		}
		return status;
	}

	/**
	 * Mengisi flag status baris riwayat organisasi sekolah ini secara langsung, tanpa
	 * null-guard.
	 *
	 * @param status status baru.
	 */
	public void setStatus(Boolean status) {
		this.status = status;
	}

	/**
	 * Mengembalikan periode kepengurusan/keanggotaan pada organisasi sekolah tersebut (mis. teks
	 * bebas seperti "2018/2019"). Field ini TIDAK ada pada {@link RiwayatKerjaPegawai}, tetapi
	 * ADA pada seluruh sub-klaster riwayat organisasi ({@link RiwayatOrganisasiKampusPegawai},
	 * {@link RiwayatOrganisasiLainPegawai}).
	 *
	 * @return periode kepengurusan/keanggotaan.
	 */
	public String getPeriode() {
		return periode;
	}

	/**
	 * Mengisi periode kepengurusan/keanggotaan pada organisasi sekolah tersebut.
	 *
	 * @param periode periode baru.
	 */
	public void setPeriode(String periode) {
		this.periode = periode;
	}

}
