<%-- @generated by generate_new_jsp_scaffold.py
Source: src/ais/action/master/bkd/KinerjaAction.java
Generated: 2026-08-06T18:20:20Z
Safe service-adapter scaffold. Implement data access in a Java service layer, not directly in this JSP.
--%>
<%@ page language="java" contentType="application/json; charset=UTF-8" pageEncoding="UTF-8" %>
<%
request.setAttribute("nuiServiceModule", "bkd");
request.setAttribute("nuiServicePage", "kinerja");
request.setAttribute("nuiServiceTitle", "Kinerja");
request.setAttribute("nuiServiceType", "academic");
request.setAttribute("nuiServiceSourceClass", "KinerjaAction");
request.setAttribute("nuiServiceSourcePackage", "ais.action.master.bkd");
request.setAttribute("nuiServiceSourcePath", "src/ais/action/master/bkd/KinerjaAction.java");
request.setAttribute("nuiServiceMethods", new String[]{"onBidangPenunjang", "onBidangPendidikan", "onBidangPenelitian", "onBidangPengabdian", "tampilRingkasan", "onEvent", "doAfterCompose"});
request.setAttribute("nuiServiceEntities", new String[]{"Tbmuser", "AsesorPegawai", "Pegawai", "KewajibanBebanDosen", "Dosen"});
%>
<jsp:include page="/WEB-INF/new/_shared/services/dispatcher.jsp" />
