<%-- @generated by generate_new_jsp_scaffold.py
Source: src/ais/action/master/koperasi/KonfigurasiPoinKegiatanAction.java
Generated: 2026-08-06T18:20:20Z
Safe service-adapter scaffold. Implement data access in a Java service layer, not directly in this JSP.
--%>
<%@ page language="java" contentType="application/json; charset=UTF-8" pageEncoding="UTF-8" %>
<%
request.setAttribute("nuiServiceModule", "koperasi");
request.setAttribute("nuiServicePage", "konfigurasi_poin_kegiatan");
request.setAttribute("nuiServiceTitle", "Konfigurasi Poin Kegiatan");
request.setAttribute("nuiServiceType", "inventory");
request.setAttribute("nuiServiceSourceClass", "KonfigurasiPoinKegiatanAction");
request.setAttribute("nuiServiceSourcePackage", "ais.action.master.koperasi");
request.setAttribute("nuiServiceSourcePath", "src/ais/action/master/koperasi/KonfigurasiPoinKegiatanAction.java");
request.setAttribute("nuiServiceMethods", new String[]{"doBeforeCompose", "doAfterCompose", "render", "onEvent"});
request.setAttribute("nuiServiceEntities", new String[]{"JenisFormulirKegiatan", "FormulirKegiatan", "KonfigurasiPoinKegiatan"});
%>
<jsp:include page="/WEB-INF/new/_shared/services/dispatcher.jsp" />
