<%-- @generated by generate_new_jsp_scaffold.py
Source: src/ais/action/master/penelitiandanpengabdian/TingkatArtikelAction.java
Generated: 2026-08-06T18:20:20Z
This JSP contains presentation metadata only. Keep business logic in Java services.
--%>
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%
request.setAttribute("nuiModule", "penelitiandanpengabdian");
request.setAttribute("nuiModuleLabel", "Penelitian & Pengabdian");
request.setAttribute("nuiPage", "tingkat_artikel");
request.setAttribute("nuiPageTitle", "Tingkat Artikel");
request.setAttribute("nuiPageType", "list");
request.setAttribute("nuiPageDescription", "Pendataan untuk Penelitian & Pengabdian. Daftar data, pencarian, filter, detail, impor, dan ekspor.");
request.setAttribute("nuiSourceClass", "TingkatArtikelAction");
request.setAttribute("nuiSourcePackage", "ais.action.master.penelitiandanpengabdian");
request.setAttribute("nuiSourcePath", "src/ais/action/master/penelitiandanpengabdian/TingkatArtikelAction.java");
request.setAttribute("nuiSourceKind", "class");
request.setAttribute("nuiSourceExtends", "GenericAutowireComposer");
request.setAttribute("nuiSourceImplements", "DataCriteria");
request.setAttribute("nuiSourceMethods", new String[]{"doBeforeCompose", "doAfterCompose", "onEvent", "run", "render", "onAdd", "onSave", "initCriteria", "onSearchDefault", "checkNama"});
request.setAttribute("nuiEntityCandidates", new String[]{"TingkatArtikel"});
%>
<jsp:include page="/WEB-INF/new/_shared/ui/page.jsp" />
