<%-- @generated by generate_new_jsp_scaffold.py
Source: src/ais/action/master/helper/AbsensiHelper.java
Generated: 2026-08-06T18:20:20Z
This JSP contains presentation metadata only. Keep business logic in Java services.
--%>
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%
request.setAttribute("nuiModule", "helper");
request.setAttribute("nuiModuleLabel", "Helper & Komponen Pendukung");
request.setAttribute("nuiPage", "absensi_helper");
request.setAttribute("nuiPageTitle", "Absensi Helper");
request.setAttribute("nuiPageType", "academic");
request.setAttribute("nuiPageDescription", "Akademik untuk Helper & Komponen Pendukung. Data akademik, jadwal, capaian, dan status proses pendidikan.");
request.setAttribute("nuiSourceClass", "AbsensiHelper");
request.setAttribute("nuiSourcePackage", "ais.action.master.helper");
request.setAttribute("nuiSourcePath", "src/ais/action/master/helper/AbsensiHelper.java");
request.setAttribute("nuiSourceKind", "class");
request.setAttribute("nuiSourceExtends", "");
request.setAttribute("nuiSourceImplements", "");
request.setAttribute("nuiSourceMethods", new String[]{"createTombolAbsen", "onEvent", "populateMahasiswaDariPertemuan", "mainInit", "run", "sesuaikan", "render", "createStatusKehadiran", "boleh", "bolehKonfirmasi", "bolehKonfirmasiRps", "bolehOlehAkademik", "createStatusKehadiranData", "createStatusKehadiranKonfirmasi", "createStatusSesuaiDenganRpsKonfirmasi", "createStatusSesuaiOlehAkademik"});
request.setAttribute("nuiLegacyRefs", new String[]{"/read_qr_code_kartu.jsp?q=", "/read_rfid_kartu.jsp?q="});
request.setAttribute("nuiEntityCandidates", new String[]{"Statusabsensi", "ProdukPeserta", "PesertaKursus", "HasilUjianMahasiswa", "BiodataCalonMahasiswa", "RuangPaketPMB", "Detailperkuliahan", "FormulirKegiatanPeserta", "Mahasiswa", "PendaftaranWisuda", "MahasiswaDapatKelompokKkn", "MahasiswaDapatKelompokPkl", "StatusPertemuan", "Lokasi", "Dosen", "DetailKelasPertemuan", "Pegawai", "Pertemuan", "KelasPertemuan", "PengajuanIzinTidakMasukPerkuliahan"});
%>
<jsp:include page="/WEB-INF/new/_shared/ui/page.jsp" />
