<%-- @generated by generate_new_jsp_scaffold.py
Source: src/ais/action/master/helper/AmbilDataItemBiayaBanbox.java
Generated: 2026-08-06T18:20:20Z
This JSP contains presentation metadata only. Keep business logic in Java services.
--%>
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%
request.setAttribute("nuiModule", "helper");
request.setAttribute("nuiModuleLabel", "Helper & Komponen Pendukung");
request.setAttribute("nuiPage", "ambil_data_item_biaya_banbox");
request.setAttribute("nuiPageTitle", "Ambil Data Item Biaya Banbox");
request.setAttribute("nuiPageType", "finance");
request.setAttribute("nuiPageDescription", "Keuangan untuk Helper & Komponen Pendukung. Transaksi, status, rekonsiliasi, detail, dan audit keuangan.");
request.setAttribute("nuiSourceClass", "AmbilDataItemBiayaBanbox");
request.setAttribute("nuiSourcePackage", "ais.action.master.helper");
request.setAttribute("nuiSourcePath", "src/ais/action/master/helper/AmbilDataItemBiayaBanbox.java");
request.setAttribute("nuiSourceKind", "class");
request.setAttribute("nuiSourceExtends", "Bandbox");
request.setAttribute("nuiSourceImplements", "GetEventListener");
request.setAttribute("nuiSourceMethods", new String[]{"onEvent", "render", "display", "onSearchDefault", "setEventListener", "getEventListener"});
request.setAttribute("nuiEntityCandidates", new String[]{"ItemBiaya"});
%>
<jsp:include page="/WEB-INF/new/_shared/ui/page.jsp" />
