<%-- @generated by generate_new_jsp_scaffold.py
Source: src/ais/action/master/helper/AmbilDataMahasiswaKknHelper.java
Generated: 2026-08-06T18:20:20Z
This JSP contains presentation metadata only. Keep business logic in Java services.
--%>
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%
request.setAttribute("nuiModule", "helper");
request.setAttribute("nuiModuleLabel", "Helper & Komponen Pendukung");
request.setAttribute("nuiPage", "ambil_data_mahasiswa_kkn_helper");
request.setAttribute("nuiPageTitle", "Ambil Data Mahasiswa KKN Helper");
request.setAttribute("nuiPageType", "academic");
request.setAttribute("nuiPageDescription", "Akademik untuk Helper & Komponen Pendukung. Data akademik, jadwal, capaian, dan status proses pendidikan.");
request.setAttribute("nuiSourceClass", "AmbilDataMahasiswaKknHelper");
request.setAttribute("nuiSourcePackage", "ais.action.master.helper");
request.setAttribute("nuiSourcePath", "src/ais/action/master/helper/AmbilDataMahasiswaKknHelper.java");
request.setAttribute("nuiSourceKind", "class");
request.setAttribute("nuiSourceExtends", "");
request.setAttribute("nuiSourceImplements", "");
request.setAttribute("nuiSourceMethods", new String[]{"render", "save", "display", "onEvent", "onSearchDefault"});
request.setAttribute("nuiLegacyRefs", new String[]{});
request.setAttribute("nuiEntityCandidates", new String[]{"MahasiswaDapatKkn", "Mahasiswa"});
%>
<jsp:include page="/WEB-INF/new/_shared/ui/page.jsp" />
