<%-- @generated by generate_new_jsp_scaffold.py
Source: src/ais/action/master/helper/MainHelper.java
Generated: 2026-08-06T18:20:20Z
This JSP contains presentation metadata only. Keep business logic in Java services.
--%>
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%
request.setAttribute("nuiModule", "helper");
request.setAttribute("nuiModuleLabel", "Helper & Komponen Pendukung");
request.setAttribute("nuiPage", "main_helper");
request.setAttribute("nuiPageTitle", "Main Helper");
request.setAttribute("nuiPageType", "list");
request.setAttribute("nuiPageDescription", "Pendataan untuk Helper & Komponen Pendukung. Daftar data, pencarian, filter, detail, impor, dan ekspor.");
request.setAttribute("nuiSourceClass", "MainHelper");
request.setAttribute("nuiSourcePackage", "ais.action.master.helper");
request.setAttribute("nuiSourcePath", "src/ais/action/master/helper/MainHelper.java");
request.setAttribute("nuiSourceKind", "class");
request.setAttribute("nuiSourceExtends", "");
request.setAttribute("nuiSourceImplements", "");
request.setAttribute("nuiSourceMethods", new String[]{"initMain", "onEvent", "onBantuan", "onKatalogBantuan", "onKeluar", "hasChild", "parents", "onDapatkanKode", "onUbahBiodata", "onSearchDefault"});
request.setAttribute("nuiEntityCandidates", new String[]{});
%>
<jsp:include page="/WEB-INF/new/_shared/ui/page.jsp" />
