<%-- @generated by generate_new_jsp_scaffold.py
Source: src/ais/action/master/helper/ManajemenPenjadwalanMahasiswaComposer.java
Generated: 2026-08-06T18:20:20Z
This JSP contains presentation metadata only. Keep business logic in Java services.
--%>
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%
request.setAttribute("nuiModule", "helper");
request.setAttribute("nuiModuleLabel", "Helper & Komponen Pendukung");
request.setAttribute("nuiPage", "manajemen_penjadwalan_mahasiswa");
request.setAttribute("nuiPageTitle", "Manajemen Penjadwalan Mahasiswa");
request.setAttribute("nuiPageType", "academic");
request.setAttribute("nuiPageDescription", "Akademik untuk Helper & Komponen Pendukung. Data akademik, jadwal, capaian, dan status proses pendidikan.");
request.setAttribute("nuiSourceClass", "ManajemenPenjadwalanMahasiswaComposer");
request.setAttribute("nuiSourcePackage", "ais.action.master.helper");
request.setAttribute("nuiSourcePath", "src/ais/action/master/helper/ManajemenPenjadwalanMahasiswaComposer.java");
request.setAttribute("nuiSourceKind", "class");
request.setAttribute("nuiSourceExtends", "GenericForwardComposer");
request.setAttribute("nuiSourceImplements", "OnSearchDefaultListener");
request.setAttribute("nuiSourceMethods", new String[]{"onSearchDefault", "onRefresh", "doBeforeCompose", "doAfterCompose", "onEvent", "onMoveDate", "onToday", "onSwitchTimeZone", "onUpdateFirstDayOfWeek", "onUpdateView", "initDataMahasiswa", "loadData", "initCriteria", "loadDataMahasiswa", "render"});
request.setAttribute("nuiEntityCandidates", new String[]{"Perkuliahan", "Jurusan", "Fakultas", "Kelas", "Detailperkuliahan", "PenjadwalanMahasiswa"});
%>
<jsp:include page="/WEB-INF/new/_shared/ui/page.jsp" />
