<%-- @generated by generate_new_jsp_scaffold.py
Source: src/ais/action/master/helper/OrganisasiDosenPunyaDosenHelper.java
Generated: 2026-08-06T18:20:20Z
This JSP contains presentation metadata only. Keep business logic in Java services.
--%>
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%
request.setAttribute("nuiModule", "helper");
request.setAttribute("nuiModuleLabel", "Helper & Komponen Pendukung");
request.setAttribute("nuiPage", "organisasi_dosen_punya_dosen_helper");
request.setAttribute("nuiPageTitle", "Organisasi Dosen Punya Dosen Helper");
request.setAttribute("nuiPageType", "academic");
request.setAttribute("nuiPageDescription", "Akademik untuk Helper & Komponen Pendukung. Data akademik, jadwal, capaian, dan status proses pendidikan.");
request.setAttribute("nuiSourceClass", "OrganisasiDosenPunyaDosenHelper");
request.setAttribute("nuiSourcePackage", "ais.action.master.helper");
request.setAttribute("nuiSourcePath", "src/ais/action/master/helper/OrganisasiDosenPunyaDosenHelper.java");
request.setAttribute("nuiSourceKind", "class");
request.setAttribute("nuiSourceExtends", "");
request.setAttribute("nuiSourceImplements", "DataLoader, DataCriteria, DataSearchDefault");
request.setAttribute("nuiSourceMethods", new String[]{"onEvent", "render", "initCriteria", "loadData", "display", "process", "onSearchDefault"});
request.setAttribute("nuiLegacyRefs", new String[]{});
request.setAttribute("nuiEntityCandidates", new String[]{"OrganisasiDosenPunyaDosen", "JabatanOrganisasiDosen", "Jurusan"});
%>
<jsp:include page="/WEB-INF/new/_shared/ui/page.jsp" />
