<%-- @generated by generate_new_jsp_scaffold.py
Source: src/ais/action/master/helper/ParameterTambahanPengaduanListener.java
Generated: 2026-08-06T18:20:20Z
This JSP contains presentation metadata only. Keep business logic in Java services.
--%>
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%
request.setAttribute("nuiModule", "helper");
request.setAttribute("nuiModuleLabel", "Helper & Komponen Pendukung");
request.setAttribute("nuiPage", "parameter_tambahan_pengaduan_listener");
request.setAttribute("nuiPageTitle", "Parameter Tambahan Pengaduan Listener");
request.setAttribute("nuiPageType", "settings");
request.setAttribute("nuiPageDescription", "Pengaturan untuk Helper & Komponen Pendukung. Konfigurasi terstruktur, validasi, versi, dan riwayat perubahan.");
request.setAttribute("nuiSourceClass", "ParameterTambahanPengaduanListener");
request.setAttribute("nuiSourcePackage", "ais.action.master.helper");
request.setAttribute("nuiSourcePath", "src/ais/action/master/helper/ParameterTambahanPengaduanListener.java");
request.setAttribute("nuiSourceKind", "class");
request.setAttribute("nuiSourceExtends", "");
request.setAttribute("nuiSourceImplements", "EventListener");
request.setAttribute("nuiSourceMethods", new String[]{"validate", "onSave", "onEvent"});
request.setAttribute("nuiLegacyRefs", new String[]{});
request.setAttribute("nuiEntityCandidates", new String[]{"ParameterTambahanPengaduan", "ParameterTambahan"});
%>
<jsp:include page="/WEB-INF/new/_shared/ui/page.jsp" />
