<%-- @generated by generate_new_jsp_scaffold.py
Source: src/ais/action/master/ux/UxPertemuanAction.java
Generated: 2026-08-06T18:20:20Z
Safe service-adapter scaffold. Implement data access in a Java service layer, not directly in this JSP.
--%>
<%@ page language="java" contentType="application/json; charset=UTF-8" pageEncoding="UTF-8" %>
<%
request.setAttribute("nuiServiceModule", "ux");
request.setAttribute("nuiServicePage", "ux_pertemuan");
request.setAttribute("nuiServiceTitle", "Ux Pertemuan");
request.setAttribute("nuiServiceType", "list");
request.setAttribute("nuiServiceSourceClass", "UxPertemuanAction");
request.setAttribute("nuiServiceSourcePackage", "ais.action.master.ux");
request.setAttribute("nuiServiceSourcePath", "src/ais/action/master/ux/UxPertemuanAction.java");
request.setAttribute("nuiServiceMethods", new String[]{"doAfterCompose", "loadData"});
request.setAttribute("nuiServiceEntities", new String[]{"Pertemuan"});
%>
<jsp:include page="/WEB-INF/new/_shared/services/dispatcher.jsp" />
