<%-- @generated by generate_new_jsp_scaffold.py
Source: src/ais/action/report/format1/surat/LaporanSuratPerLoker.java
Generated: 2026-08-06T18:20:20Z
Safe service-adapter scaffold. Implement data access in a Java service layer, not directly in this JSP.
--%>
<%@ page language="java" contentType="application/json; charset=UTF-8" pageEncoding="UTF-8" %>
<%
request.setAttribute("nuiServiceModule", "root/report");
request.setAttribute("nuiServicePage", "format1/surat/laporan_surat_per_loker");
request.setAttribute("nuiServiceTitle", "Laporan Surat Per Loker");
request.setAttribute("nuiServiceType", "report");
request.setAttribute("nuiServiceSourceClass", "LaporanSuratPerLoker");
request.setAttribute("nuiServiceSourcePackage", "ais.action.report.format1.surat");
request.setAttribute("nuiServiceSourcePath", "src/ais/action/report/format1/surat/LaporanSuratPerLoker.java");
request.setAttribute("nuiServiceMethods", new String[]{"onEvent", "generateParameters", "onReport"});
request.setAttribute("nuiServiceEntities", new String[]{"LokerSurat"});
%>
<jsp:include page="/WEB-INF/new/_shared/services/dispatcher.jsp" />
