<%-- @generated by generate_new_jsp_scaffold.py
Source: src/ais/action/report/helper/statistik/LaporanProporsiJumlahmahasiswapendaftar.java
Generated: 2026-08-06T18:20:20Z
Safe service-adapter scaffold. Implement data access in a Java service layer, not directly in this JSP.
--%>
<%@ page language="java" contentType="application/json; charset=UTF-8" pageEncoding="UTF-8" %>
<%
request.setAttribute("nuiServiceModule", "root/report");
request.setAttribute("nuiServicePage", "helper/statistik/laporan_proporsi_jumlahmahasiswapendaftar");
request.setAttribute("nuiServiceTitle", "Laporan Proporsi Jumlahmahasiswapendaftar");
request.setAttribute("nuiServiceType", "dashboard");
request.setAttribute("nuiServiceSourceClass", "LaporanProporsiJumlahmahasiswapendaftar");
request.setAttribute("nuiServiceSourcePackage", "ais.action.report.helper.statistik");
request.setAttribute("nuiServiceSourcePath", "src/ais/action/report/helper/statistik/LaporanProporsiJumlahmahasiswapendaftar.java");
request.setAttribute("nuiServiceMethods", new String[]{"onEvent"});
request.setAttribute("nuiServiceLegacyRefs", new String[]{});
request.setAttribute("nuiServiceEntities", new String[]{"Fakultas", "JenisSeleksi", "Jurusan", "BiodataCalonMahasiswa"});
%>
<jsp:include page="/WEB-INF/new/_shared/services/dispatcher.jsp" />
