<%@page import="ais.common.Common"%><%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%><%
String rnd=Common.getGeneratedBarCode(7); String root=Common.ROOT;
%><link rel="stylesheet" href="<%=root%>/assets/library-modern/library.css?v=20260821d"><script src="<%=root%>/assets/library-modern/library.js?v=20260821d"></script>
<section class="library-modern library-page" id="libraryDashboard<%=rnd%>"><div class="library-container">
  <header class="library-page-head"><div><div class="library-eyebrow"><%=Common.getBahasaConfig("Pusat tindakan")%></div><h1><%=Common.getBahasaConfig("Dashboard Perpustakaan")%></h1><p class="library-muted"><%=Common.getBahasaConfig("Ringkasan koleksi, layanan, dan pekerjaan prioritas sesuai hak akses Anda.")%></p></div><button class="library-button" id="refresh<%=rnd%>" type="button"><%=Common.getBahasaConfig("Muat ulang")%></button></header>
  <div class="library-kpis">
    <article class="library-card library-kpi"><small><%=Common.getBahasaConfig("Judul publik")%></small><strong id="titles<%=rnd%>">—</strong><span class="library-muted"><%=Common.getBahasaConfig("rekaman bibliografi")%></span></article>
    <article class="library-card library-kpi"><small><%=Common.getBahasaConfig("Eksemplar")%></small><strong id="copies<%=rnd%>">—</strong><span class="library-muted"><%=Common.getBahasaConfig("barcode tercatat")%></span></article>
    <article class="library-card library-kpi"><small><%=Common.getBahasaConfig("Peminjaman")%></small><strong id="loans<%=rnd%>">—</strong><span class="library-muted"><%=Common.getBahasaConfig("transaksi disetujui")%></span></article>
    <article class="library-card library-kpi"><small><%=Common.getBahasaConfig("Kunjungan")%></small><strong id="visits<%=rnd%>">—</strong><span class="library-muted"><%=Common.getBahasaConfig("sesuai scope akun")%></span></article>
  </div>
  <div class="library-dashboard-grid">
    <article class="library-card library-card-pad"><div class="library-eyebrow"><%=Common.getBahasaConfig("7 hari terakhir")%></div><h2 class="library-section-title"><%=Common.getBahasaConfig("Tren kunjungan")%></h2><div class="library-bars" id="trend<%=rnd%>" aria-label="<%=Common.getBahasaConfig("Grafik kunjungan tujuh hari")%>"></div></article>
    <aside class="library-card library-card-pad"><div class="library-eyebrow"><%=Common.getBahasaConfig("Tindakan")%></div><h2 class="library-section-title"><%=Common.getBahasaConfig("Perlu perhatian")%></h2><div class="library-action-list" id="actions<%=rnd%>"></div></aside>
  </div>
  <article class="library-card library-card-pad" style="margin-top:16px"><div class="library-eyebrow"><%=Common.getBahasaConfig("Koleksi")%></div><h2 class="library-section-title"><%=Common.getBahasaConfig("Subjek teratas")%></h2><div class="library-action-list" id="subjects<%=rnd%>"></div></article>
  <div class="library-dashboard-grid" style="margin-top:16px">
    <article class="library-card library-card-pad"><div class="library-eyebrow"><%=Common.getBahasaConfig("Discovery analytics")%></div><h2 class="library-section-title"><%=Common.getBahasaConfig("Pencarian teratas")%></h2><div class="library-action-list" id="queries<%=rnd%>"></div></article>
    <article class="library-card library-card-pad"><div class="library-eyebrow"><%=Common.getBahasaConfig("Discovery analytics")%></div><h2 class="library-section-title"><%=Common.getBahasaConfig("Koleksi paling banyak dilihat")%></h2><div class="library-action-list" id="popularTitles<%=rnd%>"></div></article>
  </div>
</div></section>
<script>(function(){'use strict';var s='<%=rnd%>',root='<%=root%>',api=root+'/pustaka?hanya_tampil_jsp=true&p=pustaka&s=_workspace_api';function e(id){return document.getElementById(id+s);}function n(v){return Number(v||0).toLocaleString('id-ID');}function load(){LibraryModern.fetchJson(api,{action:'dashboard'}).then(function(d){var c=d.counts||{};['titles','copies','loans','visits'].forEach(function(k){e(k).textContent=n(c[k]);});var trend=d.visitTrend||[],max=1;trend.forEach(function(x){max=Math.max(max,Number(x.count||0));});e('trend').innerHTML=trend.length?trend.map(function(x){var h=Math.max(4,Math.round(Number(x.count||0)*180/max));return '<div class="library-bar"><b>'+n(x.count)+'</b><span style="height:'+h+'px"></span><small>'+LibraryModern.escapeHtml(x.date)+'</small></div>';}).join(''):'<div class="library-state"><span class="library-muted"><%=Common.getBahasaConfigJS("Belum ada kunjungan pada periode ini.")%></span></div>';e('actions').innerHTML='<div class="library-action-item"><span><%=Common.getBahasaConfigJS("Terlambat")%></span><strong>'+n(c.overdue)+'</strong></div><div class="library-action-item"><span><%=Common.getBahasaConfigJS("Reservasi aktif")%></span><strong>'+n(c.holds)+'</strong></div><div class="library-action-item"><span><%=Common.getBahasaConfigJS("Pengembalian")%></span><strong>'+n(c.returns)+'</strong></div>';e('subjects').innerHTML=(d.topSubjects||[]).map(function(x){return '<div class="library-action-item"><a href="'+root+'/pustaka?subject='+encodeURIComponent(x.name)+'">'+LibraryModern.escapeHtml(x.name)+'</a><strong>'+n(x.count)+'</strong></div>';}).join('');e('queries').innerHTML=(d.popularQueries||[]).map(function(x){return '<div class="library-action-item"><a href="'+root+'/pustaka?query='+encodeURIComponent(x.name)+'">'+LibraryModern.escapeHtml(x.name)+'</a><strong>'+n(x.count)+'</strong></div>';}).join('')||'<div class="library-state">Belum ada data pencarian.</div>';e('popularTitles').innerHTML=(d.popularTitles||[]).map(function(x){return '<div class="library-action-item"><a href="'+root+'/pustaka?id='+encodeURIComponent(x.id)+'">'+LibraryModern.escapeHtml(x.name)+'</a><strong>'+n(x.count)+'</strong></div>';}).join('')||'<div class="library-state">Belum ada statistik tampilan.</div>';}).catch(function(){e('trend').innerHTML='<div class="library-state"><strong><%=Common.getBahasaConfigJS("Dashboard belum dapat dimuat")%></strong></div>';});}e('refresh').addEventListener('click',load);load();}());</script>
