<%@page import="ais.common.Common"%><%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%><%String root=Common.ROOT;String rnd=Common.getGeneratedBarCode(7);%>
<link rel="stylesheet" href="<%=root%>/assets/library-modern/library.css?v=20260825a"><script src="<%=root%>/assets/library-modern/library.js?v=20260825a"></script>
<section class="library-modern library-page"><div class="library-container">
 <header class="library-page-head"><div><div class="library-eyebrow">Interoperabilitas</div><h1>Integrasi Perpustakaan</h1><p class="library-muted">Adapter dinonaktifkan secara default. Endpoint dan kredensial dibaca dari konfigurasi server, tidak pernah dari browser.</p></div><a class="library-button" href="<%=root%>/pustaka?hanya_tampil_jsp=true&p=pustaka&s=_oai&verb=Identify" target="_blank" rel="noopener">OAI-PMH Identify</a></header>
 <div class="library-grid library-grid-3" id="integrationCards<%=rnd%>" aria-live="polite"></div>
 <article class="library-card library-card-pad"><h2>RFID / self-check</h2><p class="library-muted">Checkout dan check-in dikirim sebagai perintah typed ke bridge RFID yang dikonfigurasi di server.</p><div class="library-toolbar"><select class="library-select" id="selfOperation<%=rnd%>"><option value="checkout">Peminjaman mandiri</option><option value="checkin">Pengembalian mandiri</option></select><input class="library-input" id="selfMember<%=rnd%>" maxlength="100" placeholder="Kode anggota"><input class="library-input" id="selfBarcode<%=rnd%>" maxlength="100" placeholder="Barcode / tag RFID"><button class="library-button library-button-primary" id="selfExecute<%=rnd%>" type="button">Proses self-check</button></div><div class="library-state" id="selfResult<%=rnd%>" aria-live="polite">Menunggu transaksi.</div></article>
 <article class="library-card library-card-pad"><h2>Uji koneksi berwenang</h2><div class="library-toolbar"><div class="library-toolbar-field"><label for="adapter<%=rnd%>">Adapter</label><select class="library-select" id="adapter<%=rnd%>"><option value="sru">SRU / Z39.50 bridge</option><option value="ncip">NCIP</option><option value="sip2">SIP2</option><option value="rfid">RFID bridge</option><option value="sushi">COUNTER/SUSHI</option></select></div></div><label for="payload<%=rnd%>">Query / payload</label><textarea class="library-input" id="payload<%=rnd%>" rows="8" maxlength="65536" placeholder="Masukkan CQL, XML, pesan SIP2, JSON, atau path laporan sesuai adapter."></textarea><div class="library-actions"><button class="library-button library-button-primary" id="execute<%=rnd%>" type="button">Kirim</button></div><pre class="library-state" id="integrationResult<%=rnd%>" tabindex="0">Belum ada permintaan.</pre></article>
</div></section>
<script>(function(){'use strict';var s='<%=rnd%>',root='<%=root%>',api=root+'/pustaka?hanya_tampil_jsp=true&p=pustaka&s=_integrations_api',csrf='';function e(id){return document.getElementById(id+s);}function load(){LibraryModern.fetchJson(api,{action:'status'}).then(function(d){csrf=d.csrf||'';e('integrationCards').innerHTML=(d.data||[]).map(function(x){return '<article class="library-card library-card-pad"><h2>'+LibraryModern.escapeHtml(x.id.toUpperCase())+'</h2><span class="library-status">'+(x.enabled?'Aktif':'Belum dikonfigurasi')+'</span><p class="library-muted">'+LibraryModern.escapeHtml(x.description)+'</p></article>';}).join('');}).catch(function(err){e('integrationCards').innerHTML='<div class="library-state">'+LibraryModern.escapeHtml(err.message)+'</div>';});}e('selfOperation').addEventListener('change',function(){e('selfMember').disabled=this.value==='checkin';});e('selfExecute').addEventListener('click',function(){var b=this;b.disabled=true;e('selfResult').textContent='Memproses transaksi RFID...';LibraryModern.postJson(api,{action:'self_check',operation:e('selfOperation').value,memberCode:e('selfMember').value,barcode:e('selfBarcode').value,nui_csrf:csrf}).then(function(d){e('selfResult').textContent=d.message||d.response;e('selfBarcode').value='';e('selfBarcode').focus();}).catch(function(err){e('selfResult').textContent=err.message;}).then(function(){b.disabled=false;});});e('execute').addEventListener('click',function(){var b=this;b.disabled=true;e('integrationResult').textContent='Menghubungi adapter...';LibraryModern.postJson(api,{action:'execute',adapter:e('adapter').value,payload:e('payload').value,nui_csrf:csrf}).then(function(d){e('integrationResult').textContent=d.response||JSON.stringify(d,null,2);}).catch(function(err){e('integrationResult').textContent=err.message;}).then(function(){b.disabled=false;});});load();}());</script>
