<%-- @generated by generate_new_jsp_scaffold.py
Source: src/ais/action/master/sekolah/CalonSiswaAction.java
Generated: 2026-08-06T18:20:20Z
Safe service-adapter scaffold. Implement data access in a Java service layer, not directly in this JSP.
--%>
<%@ page language="java" contentType="application/json; charset=UTF-8" pageEncoding="UTF-8" %>
<%
request.setAttribute("nuiServiceModule", "sekolah");
request.setAttribute("nuiServicePage", "calon_siswa");
request.setAttribute("nuiServiceTitle", "Calon Siswa");
request.setAttribute("nuiServiceType", "academic");
request.setAttribute("nuiServiceSourceClass", "CalonSiswaAction");
request.setAttribute("nuiServiceSourcePackage", "ais.action.master.sekolah");
request.setAttribute("nuiServiceSourcePath", "src/ais/action/master/sekolah/CalonSiswaAction.java");
request.setAttribute("nuiServiceMethods", new String[]{"doBeforeCompose", "doAfterCompose", "onEvent", "run", "onDownloadLampiran", "onDownloadNilaiRaport", "render", "initCriteria", "initBg", "onDownloadFotoMassal", "onUploadFotoMassal", "onAdd", "onAddExternal", "init", "initKelasLes", "reloadDataFormula", "reloadFormula", "onSave", "onSearchDefault", "onCetakKartu", "checkInfoDariMana", "infoDariMana", "infoPindahan", "onDasborStatistik", "onDasborStatus", "onDasborSekolah", "onDasborRegistrasi", "onDasborHarian", "onDasborRekapMultiTahun"});
request.setAttribute("nuiServiceLegacyRefs", new String[]{"/WEB-INF/z/x/y/pages/master/sekolah/dasbor_keuangan_siswa.zul"});
request.setAttribute("nuiServiceEntities", new String[]{"GelombangPendaftaranPsb", "StatusAwalSiswa", "CalonSiswa", "FotoCalonSiswa", "CalonSiswaPunyaVerifikasiBerkas", "GelombangPendaftaranPsbPunyaMatapelajaran", "MatapelajaranSekolah", "CalonSiswaPunyaVerifikasiMatapelajaran", "LampiranLain", "PembayaranSiswaDetail", "DefaultNisGenerator", "RuangPSB", "RuangGelombangPendaftaranPsbPSB", "KelasSiswaPSB", "KelasLesSiswa", "KelasLesSiswaPunyaSiswa", "Agama", "JadwalPertemuanPSB", "JenisTinggalMahasiswa", "AlatTransportasiMahasiswa", "Pendidikan", "Pekerjaan", "PenghasilanOrangTuaSiswa", "PaketPsbPunyaGelombangPendaftaranPsb", "PaketPsb", "Siswa", "JadwalUjianPSB", "PertemuanPunyaUjian"});
%>
<jsp:include page="/WEB-INF/new/_shared/services/dispatcher.jsp" />
