<%-- @generated by generate_new_jsp_scaffold.py
Source: src/ais/action/master/sekolah/PrestasiSiswaAction.java
Generated: 2026-08-06T18:20:20Z
Safe service-adapter scaffold. Implement data access in a Java service layer, not directly in this JSP.
--%>
<%@ page language="java" contentType="application/json; charset=UTF-8" pageEncoding="UTF-8" %>
<%
request.setAttribute("nuiServiceModule", "sekolah");
request.setAttribute("nuiServicePage", "prestasi_siswa");
request.setAttribute("nuiServiceTitle", "Prestasi Siswa");
request.setAttribute("nuiServiceType", "academic");
request.setAttribute("nuiServiceSourceClass", "PrestasiSiswaAction");
request.setAttribute("nuiServiceSourcePackage", "ais.action.master.sekolah");
request.setAttribute("nuiServiceSourcePath", "src/ais/action/master/sekolah/PrestasiSiswaAction.java");
request.setAttribute("nuiServiceMethods", new String[]{"onDasbor", "onKategoriPrestasiSiswa", "onCabangPrestasiSiswa", "onRekapCabang", "onRekapKategori", "doBeforeCompose", "doAfterCompose", "onEvent", "render", "onAdd", "onSave", "initCriteria", "onSearchDefault"});
request.setAttribute("nuiServiceEntities", new String[]{"KategoriPrestasiSiswa", "CabangPrestasiSiswa", "Siswa", "PrestasiSiswa", "Sekolah", "LampiranLain"});
%>
<jsp:include page="/WEB-INF/new/_shared/services/dispatcher.jsp" />
