<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ page import="java.text.DecimalFormat" %><%@ page import="java.text.SimpleDateFormat" %><%@ page import="java.util.List" %>
<%@ page import="ais.common.newui.NewUiCsrfUtil" %><%@ page import="ais.common.newui.NewUiPermission" %><%@ page import="ais.common.newui.NewUiRouteGuard" %>
<%@ page import="ais.common.newui.menu.NewUiDepositoAroService" %><%@ page import="ais.common.newui.menu.NewUiDepositoAroService.Dashboard" %><%@ page import="ais.common.newui.menu.NewUiDepositoAroService.Row" %>
<%!
private String daH(Object value){if(value==null)return "";return String.valueOf(value).replace("&","&amp;").replace("<","&lt;").replace(">","&gt;").replace("\"","&quot;").replace("'","&#39;");}
private String daJs(Object value){return daH(value).replace("\\","\\\\").replace("'","\\'").replace("\r","").replace("\n","\\n");}
%>
<%
NewUiPermission daPermission=NewUiRouteGuard.permissionFor(request,"koperasi","deposito_aro_koperasi");if(!daPermission.isCanRead()){response.setStatus(403);%><jsp:include page="/WEB-INF/new/_shared/ui/403.jsp"/><%return;}
Dashboard da=null;Exception daError=null;try{da=NewUiDepositoAroService.load();}catch(Exception error){daError=error;try{ais.common.ErrorAuditUtil.record(error,"New UI deposito ARO koperasi");}catch(Exception ignored){}}
Long daMenuId=(Long)request.getAttribute("nui_current_menu_id");String daEndpoint=request.getContextPath()+"/new?service=1&module=koperasi&page=deposito_aro_koperasi&menuId="+(daMenuId==null?"":daMenuId);String daCsrf=NewUiCsrfUtil.getToken(session);DecimalFormat daMoney=new DecimalFormat("#,##0.00");SimpleDateFormat daDate=new SimpleDateFormat("dd-MM-yyyy");
%>
<section class="nui-page" id="nui-deposito-aro"><header class="nui-page-head"><div><div class="nui-breadcrumb">Beranda / Koperasi / ARO Deposito</div><h1 class="nui-page-title">ARO Deposito Koperasi</h1><p class="nui-page-desc">Pemantauan jatuh tempo, perpanjangan otomatis, dan proses ARO manual mengikuti <code>DepositoAroKoperasiAction</code>.</p></div><div class="nui-head-actions"><button class="nui-btn" type="button" onclick="location.reload()"><i class="fa-solid fa-rotate"></i> Segarkan</button><%if(daPermission.isCanUpdate()){%><button class="nui-btn nui-btn-primary" type="button" id="nui-process-aro"><i class="fa-solid fa-gears"></i> Proses ARO Sekarang</button><%}%></div></header>
<%if(daError!=null||da==null){%><article class="nui-card nui-card-pad"><span class="nui-status warn">DATA_ERROR</span><h2>Data ARO belum dapat dimuat</h2><p><%=daH(daError==null?"Service tidak mengembalikan data.":daError.getMessage())%></p></article><%}else{%>
<div class="nui-grid nui-grid-2"><article class="nui-card nui-card-pad"><div class="nui-stat"><div class="nui-stat-icon"><i class="fa-solid fa-rotate"></i></div><div><div>Deposito ARO Aktif</div><div class="nui-stat-value"><%=da.automaticCount%></div><div class="nui-stat-meta">Rp <%=daMoney.format(da.automaticValue)%></div></div></div></article><article class="nui-card nui-card-pad"><div class="nui-stat"><div class="nui-stat-icon"><i class="fa-solid fa-hourglass-end"></i></div><div><div>Menunggu Pencairan</div><div class="nui-stat-value"><%=da.dueCount%></div><div class="nui-stat-meta">Rp <%=daMoney.format(da.dueValue)%></div></div></div></article></div><div style="height:14px"></div>
<article class="nui-card"><div class="nui-toolbar"><input class="nui-input" id="nui-aro-search" placeholder="Cari anggota, produk, status..."><span class="nui-chip"><%=da.getRows().size()%> deposito</span></div><div class="nui-table-wrap"><table class="nui-table"><thead><tr><th>Anggota</th><th>Produk</th><th style="text-align:right">Nominal</th><th>Jatuh Tempo</th><th>Perpanjangan</th><th>ARO</th><th>Status</th></tr></thead><tbody id="nui-aro-rows"><%List<Row> rows=da.getRows();if(rows.isEmpty()){%><tr><td colspan="7"><div class="nui-empty"><i class="fa-solid fa-vault"></i><p>Belum ada deposito rollover aktif.</p></div></td></tr><%}for(int i=0;i<rows.size();i++){Row row=rows.get(i);%><tr data-search="<%=daH((row.member+" "+row.product+" "+row.statusLabel).toLowerCase())%>"><td><strong><%=daH(row.member)%></strong></td><td><%=daH(row.product)%></td><td style="text-align:right">Rp <%=daMoney.format(row.nominal)%></td><td><%=row.dueDate==null?"-":daDate.format(row.dueDate)%></td><td><%=row.extensionCount%>x</td><td><%if(daPermission.isCanUpdate()){%><button type="button" class="nui-btn nui-aro-toggle" data-id="<%=row.id%>" data-enabled="<%=!row.automatic%>"><i class="fa-solid <%=row.automatic?"fa-toggle-on":"fa-toggle-off"%>"></i> <%=row.automatic?"Aktif":"Nonaktif"%></button><%}else{%><span class="nui-status <%=row.automatic?"ok":""%>"><%=row.automatic?"Aktif":"Nonaktif"%></span><%}%></td><td><span class="nui-status <%=row.statusLabel.indexOf("Jatuh")>=0?"warn":"ok"%>"><%=daH(row.statusLabel)%></span></td></tr><%}%></tbody></table></div></article><%}%>
<div id="nui-aro-message" class="nui-toast" hidden></div></section>
<script>(function(){var root=document.getElementById('nui-deposito-aro');if(!root)return;var endpoint='<%=daJs(daEndpoint)%>',csrf='<%=daJs(daCsrf)%>',message=document.getElementById('nui-aro-message');function notify(text,bad){message.textContent=text;message.hidden=false;message.className='nui-toast '+(bad?'error':'success');setTimeout(function(){message.hidden=true;},5000);}function post(params){params.nui_csrf=csrf;return fetch(endpoint+'&action=update',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded;charset=UTF-8','X-NUI-CSRF':csrf},body:new URLSearchParams(params).toString(),credentials:'same-origin'}).then(function(r){return r.json().then(function(j){if(!r.ok||!j.ok)throw new Error(j.message||'Operasi gagal.');return j;});});}root.addEventListener('click',function(event){var button=event.target.closest('.nui-aro-toggle');if(!button)return;button.disabled=true;post({operation:'toggle',id:button.getAttribute('data-id'),enabled:button.getAttribute('data-enabled')}).then(function(j){notify(j.message||'Status ARO diperbarui.');location.reload();}).catch(function(e){button.disabled=false;notify(e.message,true);});});var process=document.getElementById('nui-process-aro');if(process)process.addEventListener('click',function(){if(!confirm('Jalankan proses ARO sekarang?'))return;process.disabled=true;post({operation:'process'}).then(function(j){notify(j.message||'Proses ARO selesai.');location.reload();}).catch(function(e){process.disabled=false;notify(e.message,true);});});var search=document.getElementById('nui-aro-search');if(search)search.addEventListener('input',function(){var q=this.value.toLowerCase(),rows=document.querySelectorAll('#nui-aro-rows tr[data-search]');for(var i=0;i<rows.length;i++)rows[i].hidden=rows[i].getAttribute('data-search').indexOf(q)<0;});})();</script>
