<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ page import="java.text.DecimalFormat" %>
<%@ page import="ais.common.newui.NewUiPermission" %>
<%@ page import="ais.common.newui.NewUiRouteGuard" %>
<%@ page import="ais.common.newui.menu.NewUiKoperasiFinancialService" %>
<%@ page import="ais.common.newui.menu.NewUiKoperasiFinancialService.Summary" %>
<%!
private String lkH(Object value){if(value==null)return "";return String.valueOf(value).replace("&","&amp;").replace("<","&lt;").replace(">","&gt;").replace("\"","&quot;").replace("'","&#39;");}
private String lkMoney(DecimalFormat format,double value){return "Rp "+format.format(value);}
%>
<%
NewUiPermission lkPermission=NewUiRouteGuard.permissionFor(request,"koperasi","laporan_keuangan_koperasi");
if(!lkPermission.isCanRead()){response.setStatus(403);%><jsp:include page="/WEB-INF/new/_shared/ui/403.jsp"/><%return;}
Summary lk=null;Exception lkError=null;try{lk=NewUiKoperasiFinancialService.load();}catch(Exception error){lkError=error;try{ais.common.ErrorAuditUtil.record(error,"New UI laporan keuangan koperasi");}catch(Exception ignored){}}
DecimalFormat lkNumber=new DecimalFormat("#,##0.00");Long lkMenuId=(Long)request.getAttribute("nui_current_menu_id");String lkBase=request.getContextPath()+"/new?frame=1"+(lkMenuId==null?"":"&amp;menuId="+lkMenuId);String lkExport=request.getContextPath()+"/new?service=1&amp;module=koperasi&amp;page=laporan_keuangan_koperasi&amp;action=export"+(lkMenuId==null?"":"&amp;menuId="+lkMenuId);
%>
<section class="nui-page">
  <header class="nui-page-head"><div><div class="nui-breadcrumb">Beranda / Koperasi / Laporan Keuangan</div><h1 class="nui-page-title">Laporan Keuangan Koperasi</h1><p class="nui-page-desc">Neraca, hasil usaha, arus kas, PPAP, dan CALK memakai rumus serta sumber transaksi yang sama dengan <code>LaporanKeuanganKoperasiAction</code>.</p></div><div class="nui-head-actions"><a class="nui-btn" href="<%=lkBase%>"><i class="fa-solid fa-rotate"></i> Segarkan</a><%if(lkPermission.isCanRead()){%><a class="nui-btn nui-btn-primary" href="<%=lkExport%>"><i class="fa-solid fa-file-excel"></i> Unduh Excel</a><%}%></div></header>
  <%if(lkError!=null||lk==null){%><article class="nui-card nui-card-pad"><div class="nui-status warn">DATA_ERROR</div><h2>Data laporan belum dapat dimuat</h2><p><%=lkH(lkError==null?"Service tidak mengembalikan data.":lkError.getMessage())%></p></article><%}else{%>
  <div class="nui-grid nui-grid-4 nui-dashboard-kpis">
    <article class="nui-card nui-card-pad"><div class="nui-stat"><div class="nui-stat-icon"><i class="fa-solid fa-building-columns"></i></div><div><div>Total Aset</div><div class="nui-stat-value"><%=lkMoney(lkNumber,lk.totalAset)%></div><div class="nui-stat-meta">Kas + piutang berjalan</div></div></div></article>
    <article class="nui-card nui-card-pad"><div class="nui-stat"><div class="nui-stat-icon"><i class="fa-solid fa-hand-holding-dollar"></i></div><div><div>Piutang Pinjaman</div><div class="nui-stat-value"><%=lkMoney(lkNumber,lk.outstandingPokok)%></div><div class="nui-stat-meta">Pokok yang belum dibayar</div></div></div></article>
    <article class="nui-card nui-card-pad"><div class="nui-stat"><div class="nui-stat-icon"><i class="fa-solid fa-vault"></i></div><div><div>Modal Sendiri</div><div class="nui-stat-value"><%=lkMoney(lkNumber,lk.modalSendiri)%></div><div class="nui-stat-meta">Pokok + wajib + penyertaan</div></div></div></article>
    <article class="nui-card nui-card-pad"><div class="nui-stat"><div class="nui-stat-icon"><i class="fa-solid fa-shield-halved"></i></div><div><div>Cadangan PPAP</div><div class="nui-stat-value"><%=lkMoney(lkNumber,lk.totalPpap)%></div><div class="nui-stat-meta">Menurut kolektibilitas</div></div></div></article>
  </div>
  <div style="height:14px"></div>
  <div class="nui-grid nui-grid-2 nui-dashboard-content-grid">
    <article class="nui-card"><div class="nui-card-title nui-card-pad">Neraca Ringkas <small>Posisi saat ini</small></div><div class="nui-table-wrap"><table class="nui-table"><thead><tr><th>Pos</th><th style="text-align:right">Nilai</th></tr></thead><tbody><tr><td>Kas dan Setara Kas</td><td style="text-align:right"><%=lkMoney(lkNumber,lk.kas)%></td></tr><tr><td>Piutang Pinjaman</td><td style="text-align:right"><%=lkMoney(lkNumber,lk.outstandingPokok)%></td></tr><tr><td><strong>Total Aset</strong></td><td style="text-align:right"><strong><%=lkMoney(lkNumber,lk.totalAset)%></strong></td></tr><tr><td>Simpanan Sukarela (Kewajiban)</td><td style="text-align:right"><%=lkMoney(lkNumber,lk.simpananSukarela)%></td></tr><tr><td>Modal Sendiri</td><td style="text-align:right"><%=lkMoney(lkNumber,lk.modalSendiri)%></td></tr></tbody></table></div></article>
    <article class="nui-card"><div class="nui-card-title nui-card-pad">Arus Kas & Hasil Usaha <small>Aktivitas simpan pinjam</small></div><div class="nui-table-wrap"><table class="nui-table"><thead><tr><th>Uraian</th><th style="text-align:right">Nilai</th></tr></thead><tbody><tr><td>Total Kas Masuk</td><td style="text-align:right"><%=lkMoney(lkNumber,lk.kasMasuk)%></td></tr><tr><td>Penyaluran Pinjaman</td><td style="text-align:right"><%=lkMoney(lkNumber,lk.kasKeluar)%></td></tr><tr><td><strong>Arus Kas Bersih</strong></td><td style="text-align:right"><strong><%=lkMoney(lkNumber,lk.arusKasBersih)%></strong></td></tr><tr><td>Pendapatan Jasa Pinjaman</td><td style="text-align:right"><%=lkMoney(lkNumber,lk.jasaDiterima)%></td></tr><tr><td>Angsuran Pokok Diterima</td><td style="text-align:right"><%=lkMoney(lkNumber,lk.angsuranPokokDiterima)%></td></tr></tbody></table></div></article>
  </div>
  <div style="height:14px"></div>
  <div class="nui-grid nui-grid-2 nui-dashboard-content-grid">
    <article class="nui-card"><div class="nui-card-title nui-card-pad">PPAP <small>Penyisihan Penghapusan Aktiva Produktif</small></div><div class="nui-table-wrap"><table class="nui-table"><thead><tr><th>Kolektibilitas</th><th>Bobot</th><th style="text-align:right">Outstanding</th><th style="text-align:right">Cadangan</th></tr></thead><tbody><tr><td>Lancar</td><td>0,5%</td><td style="text-align:right"><%=lkMoney(lkNumber,lk.outLancar)%></td><td style="text-align:right"><%=lkMoney(lkNumber,lk.outLancar*.005D)%></td></tr><tr><td>Kurang Lancar</td><td>10%</td><td style="text-align:right"><%=lkMoney(lkNumber,lk.outKurang)%></td><td style="text-align:right"><%=lkMoney(lkNumber,lk.outKurang*.10D)%></td></tr><tr><td>Ragu-ragu</td><td>50%</td><td style="text-align:right"><%=lkMoney(lkNumber,lk.outRagu)%></td><td style="text-align:right"><%=lkMoney(lkNumber,lk.outRagu*.50D)%></td></tr><tr><td>Macet</td><td>100%</td><td style="text-align:right"><%=lkMoney(lkNumber,lk.outMacet)%></td><td style="text-align:right"><%=lkMoney(lkNumber,lk.outMacet)%></td></tr></tbody></table></div></article>
    <article class="nui-card nui-card-pad"><div class="nui-card-title">Catatan atas Laporan Keuangan (CALK)</div><p><strong>Dasar penyusunan.</strong> Posisi ringkas diturunkan dari transaksi simpan pinjam. Pendapatan jasa diakui saat diterima; simpanan pokok dan wajib menjadi modal sendiri, sedangkan simpanan sukarela menjadi kewajiban anggota.</p><div class="nui-detail-row"><span>Simpanan Pokok</span><strong><%=lkMoney(lkNumber,lk.simpananPokok)%></strong></div><div class="nui-detail-row"><span>Simpanan Wajib</span><strong><%=lkMoney(lkNumber,lk.simpananWajib)%></strong></div><div class="nui-detail-row"><span>Modal Penyertaan Aktif</span><strong><%=lkMoney(lkNumber,lk.modalPenyertaan)%></strong></div><div class="nui-detail-row"><span>Piutang Berjalan</span><strong><%=lkMoney(lkNumber,lk.outstandingPokok)%></strong></div></article>
  </div>
  <%}%>
</section>
