<%-- @generated by generate_new_jsp_scaffold.py
Source: src/ais/action/master/akunting/JenisLaporanAction.java
Generated: 2026-08-06T18:20:20Z
This JSP contains presentation metadata only. Keep business logic in Java services.
--%>
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%
request.setAttribute("nuiModule", "akunting");
request.setAttribute("nuiModuleLabel", "Akuntansi");
request.setAttribute("nuiPage", "jenis_laporan");
request.setAttribute("nuiPageTitle", "Jenis Laporan");
request.setAttribute("nuiPageType", "report");
request.setAttribute("nuiPageDescription", "Laporan untuk Akuntansi. Filter, pratinjau, ekspor, dan histori pembuatan laporan.");
request.setAttribute("nuiSourceClass", "JenisLaporanAction");
request.setAttribute("nuiSourcePackage", "ais.action.master.akunting");
request.setAttribute("nuiSourcePath", "src/ais/action/master/akunting/JenisLaporanAction.java");
request.setAttribute("nuiSourceKind", "class");
request.setAttribute("nuiSourceExtends", "GenericAutowireComposer");
request.setAttribute("nuiSourceImplements", "");
request.setAttribute("nuiSourceMethods", new String[]{"doBeforeCompose", "doAfterCompose", "render", "onEvent", "onAdd", "onSave", "onSearchDefault", "checkNamaJenisLaporan"});
request.setAttribute("nuiLegacyRefs", new String[]{});
request.setAttribute("nuiEntityCandidates", new String[]{"JenisLaporan"});
%>
<jsp:include page="/WEB-INF/new/_shared/ui/page.jsp" />
