<%-- @generated by generate_new_jsp_scaffold.py
Source: src/ais/action/master/sekolah/CalonSiswaAction.java
Generated: 2026-08-06T18:20:20Z
This JSP contains presentation metadata only. Keep business logic in Java services.
--%>
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%
request.setAttribute("nuiModule", "sekolah");
request.setAttribute("nuiModuleLabel", "eSchool");
request.setAttribute("nuiPage", "calon_siswa");
request.setAttribute("nuiPageTitle", "Calon Siswa");
request.setAttribute("nuiPageType", "academic");
request.setAttribute("nuiPageDescription", "Akademik untuk eSchool. Data akademik, jadwal, capaian, dan status proses pendidikan.");
request.setAttribute("nuiSourceClass", "CalonSiswaAction");
request.setAttribute("nuiSourcePackage", "ais.action.master.sekolah");
request.setAttribute("nuiSourcePath", "src/ais/action/master/sekolah/CalonSiswaAction.java");
request.setAttribute("nuiSourceKind", "class");
request.setAttribute("nuiSourceExtends", "GenericAutowireComposer");
request.setAttribute("nuiSourceImplements", "DataCriteria, DataSearchDefault, DataInitDefault");
request.setAttribute("nuiSourceMethods", new String[]{"doBeforeCompose", "doAfterCompose", "onEvent", "run", "onDownloadLampiran", "onDownloadNilaiRaport", "render", "initCriteria", "initBg", "onDownloadFotoMassal", "onUploadFotoMassal", "onAdd", "onAddExternal", "init", "initKelasLes", "reloadDataFormula", "reloadFormula", "onSave", "onSearchDefault", "onCetakKartu", "checkInfoDariMana", "infoDariMana", "infoPindahan", "onDasborStatistik", "onDasborStatus", "onDasborSekolah", "onDasborRegistrasi", "onDasborHarian", "onDasborRekapMultiTahun"});
request.setAttribute("nuiLegacyRefs", new String[]{"/WEB-INF/z/x/y/pages/master/sekolah/dasbor_keuangan_siswa.zul"});
request.setAttribute("nuiEntityCandidates", new String[]{"GelombangPendaftaranPsb", "StatusAwalSiswa", "CalonSiswa", "FotoCalonSiswa", "CalonSiswaPunyaVerifikasiBerkas", "GelombangPendaftaranPsbPunyaMatapelajaran", "MatapelajaranSekolah", "CalonSiswaPunyaVerifikasiMatapelajaran", "LampiranLain", "PembayaranSiswaDetail", "DefaultNisGenerator", "RuangPSB", "RuangGelombangPendaftaranPsbPSB", "KelasSiswaPSB", "KelasLesSiswa", "KelasLesSiswaPunyaSiswa", "Agama", "JadwalPertemuanPSB", "JenisTinggalMahasiswa", "AlatTransportasiMahasiswa"});
%>
<jsp:include page="/WEB-INF/new/_shared/ui/page.jsp" />
