<%-- @generated by generate_new_jsp_scaffold.py
Source: src/ais/action/master/sekolah/PendidikanOrangTuaSiswaAction.java
Generated: 2026-08-06T18:20:20Z
This JSP contains presentation metadata only. Keep business logic in Java services.
--%>
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%
request.setAttribute("nuiModule", "sekolah");
request.setAttribute("nuiModuleLabel", "eSchool");
request.setAttribute("nuiPage", "pendidikan_orang_tua_siswa");
request.setAttribute("nuiPageTitle", "Pendidikan Orang Tua Siswa");
request.setAttribute("nuiPageType", "academic");
request.setAttribute("nuiPageDescription", "Akademik untuk eSchool. Data akademik, jadwal, capaian, dan status proses pendidikan.");
request.setAttribute("nuiSourceClass", "PendidikanOrangTuaSiswaAction");
request.setAttribute("nuiSourcePackage", "ais.action.master.sekolah");
request.setAttribute("nuiSourcePath", "src/ais/action/master/sekolah/PendidikanOrangTuaSiswaAction.java");
request.setAttribute("nuiSourceKind", "class");
request.setAttribute("nuiSourceExtends", "GenericAutowireComposer");
request.setAttribute("nuiSourceImplements", "DataCriteria, DataSearchDefault, DataInitDefault");
request.setAttribute("nuiSourceMethods", new String[]{"doBeforeCompose", "doAfterCompose", "onEvent", "render", "onAdd", "init", "onSave", "initCriteria", "onSearchDefault", "checkNamaPendidikanOrangTuaSiswa"});
request.setAttribute("nuiEntityCandidates", new String[]{"PendidikanOrangTuaSiswa"});
%>
<jsp:include page="/WEB-INF/new/_shared/ui/page.jsp" />
