<%-- @generated by generate_new_jsp_scaffold.py
Source: src/ais/action/master/sekolah/PklSiswaAction.java
Generated: 2026-08-06T18:20:20Z
This JSP contains presentation metadata only. Keep business logic in Java services.
--%>
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%
request.setAttribute("nuiModule", "sekolah");
request.setAttribute("nuiModuleLabel", "eSchool");
request.setAttribute("nuiPage", "pkl_siswa");
request.setAttribute("nuiPageTitle", "PKL Siswa");
request.setAttribute("nuiPageType", "academic");
request.setAttribute("nuiPageDescription", "Akademik untuk eSchool. Data akademik, jadwal, capaian, dan status proses pendidikan.");
request.setAttribute("nuiSourceClass", "PklSiswaAction");
request.setAttribute("nuiSourcePackage", "ais.action.master.sekolah");
request.setAttribute("nuiSourcePath", "src/ais/action/master/sekolah/PklSiswaAction.java");
request.setAttribute("nuiSourceKind", "class");
request.setAttribute("nuiSourceExtends", "GenericAutowireComposer");
request.setAttribute("nuiSourceImplements", "");
request.setAttribute("nuiSourceMethods", new String[]{"doAfterCompose", "initCriteria", "onSearchDefault", "loadData", "render", "onEvent", "onAdd"});
request.setAttribute("nuiLegacyRefs", new String[]{});
request.setAttribute("nuiEntityCandidates", new String[]{"Sekolah", "KelompokPkl", "SiswaDapatKelompokPkl"});
%>
<jsp:include page="/WEB-INF/new/_shared/ui/page.jsp" />
