<%-- @generated by generate_new_jsp_scaffold.py
Source: src/ais/action/master/finpay/FinpayBackandProsess.java
Generated: 2026-08-06T18:20:20Z
This JSP contains presentation metadata only. Keep business logic in Java services.
--%>
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%
request.setAttribute("nuiModule", "finpay");
request.setAttribute("nuiModuleLabel", "Integrasi Finpay");
request.setAttribute("nuiPage", "finpay_backand_prosess");
request.setAttribute("nuiPageTitle", "Finpay Backand Prosess");
request.setAttribute("nuiPageType", "finance");
request.setAttribute("nuiPageDescription", "Keuangan untuk Integrasi Finpay. Transaksi, status, rekonsiliasi, detail, dan audit keuangan.");
request.setAttribute("nuiSourceClass", "FinpayBackandProsess");
request.setAttribute("nuiSourcePackage", "ais.action.master.finpay");
request.setAttribute("nuiSourcePath", "src/ais/action/master/finpay/FinpayBackandProsess.java");
request.setAttribute("nuiSourceKind", "class");
request.setAttribute("nuiSourceExtends", "TimerTask");
request.setAttribute("nuiSourceImplements", "");
request.setAttribute("nuiSourceMethods", new String[]{"check", "run"});
request.setAttribute("nuiEntityCandidates", new String[]{"FinpayResponse", "FinpayRequest"});
%>
<jsp:include page="/WEB-INF/new/_shared/ui/page.jsp" />
