<%-- @generated by generate_new_jsp_scaffold.py
Source: src/ais/action/master/bkd/AsesorNilaiAction.java
Generated: 2026-08-06T18:20:20Z
This JSP contains presentation metadata only. Keep business logic in Java services.
--%>
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%
request.setAttribute("nuiModule", "bkd");
request.setAttribute("nuiModuleLabel", "Beban Kinerja Dosen");
request.setAttribute("nuiPage", "asesor_nilai");
request.setAttribute("nuiPageTitle", "Asesor Nilai");
request.setAttribute("nuiPageType", "academic");
request.setAttribute("nuiPageDescription", "Akademik untuk Beban Kinerja Dosen. Data akademik, jadwal, capaian, dan status proses pendidikan.");
request.setAttribute("nuiSourceClass", "AsesorNilaiAction");
request.setAttribute("nuiSourcePackage", "ais.action.master.bkd");
request.setAttribute("nuiSourcePath", "src/ais/action/master/bkd/AsesorNilaiAction.java");
request.setAttribute("nuiSourceKind", "class");
request.setAttribute("nuiSourceExtends", "GenericAutowireComposer");
request.setAttribute("nuiSourceImplements", "");
request.setAttribute("nuiSourceMethods", new String[]{"doBeforeCompose", "doAfterCompose", "onEvent", "render", "onAdd", "onSave", "initCriteria", "onSearchDefault", "checkNamaAsesorNilai"});
request.setAttribute("nuiLegacyRefs", new String[]{});
request.setAttribute("nuiEntityCandidates", new String[]{"AsesorNilai"});
%>
<jsp:include page="/WEB-INF/new/_shared/ui/page.jsp" />
