package ais.action.master.sosial.helper;

import java.math.BigDecimal; import java.util.Date; import org.hibernate.Session; import org.hibernate.Transaction; import org.hibernate.criterion.Restrictions;
import ais.database.hibernate.HibernateUtil; import ais.database.model.sosial.*;

public final class SocialDonationService {
 public TransaksiDonasi create(SocialRequestContext context,Long fundTypeId,Long programExtensionId,Long calculationId,BigDecimal requestedAmount,BigDecimal contribution,boolean anonymous,String donorName,String donorContact,String prayer,boolean publicPrayer,String idempotencyKey){
  if(!context.isAuthenticated())throw new SecurityException("Login AIS diperlukan untuk membuat transaksi sosial.");
  if(idempotencyKey==null||!idempotencyKey.matches("[A-Za-z0-9._:-]{8,120}"))throw new IllegalArgumentException("Idempotency key tidak valid.");
  Session s=null;Transaction tx=null;try{s=HibernateUtil.openSession();tx=s.beginTransaction();new SocialComplianceService().requireCollectionReady(s,context);
   TransaksiDonasi existing=(TransaksiDonasi)s.createCriteria(TransaksiDonasi.class).add(Restrictions.eq("tenantKey",context.getTenantKey())).add(Restrictions.eq("idempotencyKey",idempotencyKey)).setMaxResults(1).uniqueResult();if(existing!=null){requireIdempotentMatch(s,context,existing,fundTypeId,programExtensionId,calculationId,requestedAmount,contribution,anonymous);tx.commit();return existing;}
   JenisDanaSosial fund=(JenisDanaSosial)s.get(JenisDanaSosial.class,fundTypeId);if(fund==null||!context.getTenantKey().equals(fund.getTenantKey())||!fund.getPublicActive())throw new IllegalArgumentException("Jenis dana tidak tersedia.");
   SocialProgramExtension program=null;if(programExtensionId!=null){program=(SocialProgramExtension)s.get(SocialProgramExtension.class,programExtensionId);if(program==null||!context.getTenantKey().equals(program.getTenantKey())||!"PUBLISHED".equals(program.getPublicStatus()))throw new IllegalArgumentException("Program tidak tersedia.");if(!fund.getId().equals(program.getFundType().getId()))throw new IllegalArgumentException("Jenis dana program tidak cocok.");}
   PerhitunganZakat calculation=null;BigDecimal amount=requestedAmount;if(calculationId!=null){calculation=(PerhitunganZakat)s.get(PerhitunganZakat.class,calculationId);if(calculation==null||!context.getTenantKey().equals(calculation.getTenantKey())||calculation.getConverted())throw new IllegalArgumentException("Hasil kalkulasi tidak valid.");amount=calculation.getAmount();}
   validateAmount(amount,program);if(contribution==null)contribution=BigDecimal.ZERO;if(contribution.signum()<0||contribution.scale()>2||contribution.compareTo(new BigDecimal("1000000000000"))>0)throw new IllegalArgumentException("Kontribusi operasional tidak valid.");contribution=contribution.setScale(2);
   SocialDonorIdentity identity=context.isAuthenticated()?new SocialIdentityService().resolveOrCreate(s,context):null;if(identity==null&&(donorName==null||donorName.trim().isEmpty()))throw new IllegalArgumentException("Nama donatur wajib diisi.");
   SosialChannel channel=new SocialSmartlinkCredentialService().requireChannel(context,fund);TransaksiDonasi d=new TransaksiDonasi();d.setTenantKey(context.getTenantKey());d.setTransactionNumber(SocialSecurity.reference("SOC"));d.setSosialChannel(channel);d.setDonorIdentity(identity);d.setDonorNameSnapshot(identity==null?clean(donorName,255):identity.getDisplayName());d.setDonorContactSnapshot(identity==null?clean(donorContact,320):clean(identity.getEmail(),320));d.setAnonymous(Boolean.valueOf(anonymous));d.setPublicName(anonymous?"Hamba Allah":clean(d.getDonorNameSnapshot(),255));d.setFundType(fund);d.setCalculation(calculation);d.setGrossDonationAmount(amount.setScale(2));d.setPlatformContribution(contribution);d.setGatewayFee(BigDecimal.ZERO.setScale(2));d.setTotalPayable(SocialFinancialInvariantService.totalCharged(amount,contribution,BigDecimal.ZERO));d.setCurrency("IDR");d.setStatus("DRAFT");d.setSourceChannel("WEB");d.setIdempotencyKey(idempotencyKey);d.setRequestId(context.getRequestId());d.setPrayer(clean(prayer,1000));d.setPublicPrayer(Boolean.valueOf(publicPrayer));d.setReceiptStatus("NOT_AVAILABLE");d.setAccountingStatus("NOT_POSTED");d.setCreatedBy(context.getActorId());s.save(d);
   AlokasiDonasi allocation=new AlokasiDonasi();allocation.setTenantKey(context.getTenantKey());allocation.setTransaction(d);allocation.setProgram(program==null?null:program.getProgram());allocation.setFundType(fund);allocation.setAmount(amount);allocation.setRestriction(Boolean.TRUE.equals(fund.getRestricted())?"RESTRICTED":"UNRESTRICTED");allocation.setStatus("PLANNED");allocation.setCreatedBy(context.getActorId());s.save(allocation);
   if(calculation!=null){calculation.setConverted(Boolean.TRUE);calculation.setUpdatedBy(context.getActorId());}
   if(prayer!=null&&!prayer.trim().isEmpty()){SocialPrayerMessage msg=new SocialPrayerMessage();msg.setTenantKey(context.getTenantKey());msg.setTransaction(d);msg.setMessage(clean(prayer,1000));msg.setDisplayName(d.getPublicName());msg.setAnonymous(Boolean.valueOf(anonymous));msg.setModerationStatus("PENDING");msg.setStatus("PENDING");msg.setCreatedBy(context.getActorId());s.save(msg);}
   tx.commit();return d;
  }catch(RuntimeException e){if(tx!=null)try{tx.rollback();}catch(Exception ignored){}throw e;}finally{close(s);}
 }
 private void validateAmount(BigDecimal a,SocialProgramExtension p){if(a==null||a.signum()<=0||a.scale()>2)throw new IllegalArgumentException("Nominal donasi tidak valid.");if(a.compareTo(new BigDecimal("1000000000000"))>0)throw new IllegalArgumentException("Nominal melampaui batas transaksi.");if(p!=null&&p.getMinimumDonation()!=null&&a.compareTo(p.getMinimumDonation())<0)throw new IllegalArgumentException("Nominal di bawah minimum program.");}
 private void requireIdempotentMatch(Session s,SocialRequestContext c,TransaksiDonasi d,Long fundId,Long programExtensionId,Long calculationId,BigDecimal amount,BigDecimal contribution,boolean anonymous){if(d.getDonorIdentity()==null||d.getDonorIdentity().getTbmuser()==null||c.getUser()==null||!c.getUser().getUserId().equals(d.getDonorIdentity().getTbmuser().getUserId()))throw new SecurityException("Idempotency key sudah digunakan pengguna lain.");if(d.getFundType()==null||!d.getFundType().getId().equals(fundId))throw conflict();Long oldCalculation=d.getCalculation()==null?null:d.getCalculation().getId();if(!same(oldCalculation,calculationId))throw conflict();BigDecimal expectedContribution=contribution==null?BigDecimal.ZERO:contribution;if(!sameMoney(d.getPlatformContribution(),expectedContribution)||d.getAnonymous().booleanValue()!=anonymous)throw conflict();if(calculationId==null&&!sameMoney(d.getGrossDonationAmount(),amount))throw conflict();AlokasiDonasi allocation=(AlokasiDonasi)s.createCriteria(AlokasiDonasi.class).add(Restrictions.eq("transaction",d)).setMaxResults(1).uniqueResult();if(programExtensionId==null){if(allocation!=null&&allocation.getProgram()!=null)throw conflict();}else{SocialProgramExtension p=(SocialProgramExtension)s.get(SocialProgramExtension.class,programExtensionId);if(p==null||!c.getTenantKey().equals(p.getTenantKey())||allocation==null||allocation.getProgram()==null||!allocation.getProgram().getId().equals(p.getProgram().getId()))throw conflict();}}
 private IllegalStateException conflict(){return new IllegalStateException("Idempotency key digunakan dengan payload berbeda.");} private boolean same(Object a,Object b){return a==null?b==null:a.equals(b);} private boolean sameMoney(BigDecimal a,BigDecimal b){return a!=null&&b!=null&&a.compareTo(b)==0;}
 private String clean(String v,int max){if(v==null)return null;v=v.replaceAll("[\\p{Cntrl}&&[^\\r\\n\\t]]","").trim();return v.length()>max?v.substring(0,max):v;}
 private void close(Session s){if(s!=null)try{s.close();}catch(Exception ignored){}}
}
