package ais.action.master.sosial.helper;

import java.math.BigDecimal;
import java.util.List;
import org.hibernate.LockMode;
import org.hibernate.Session;
import org.hibernate.Transaction;
import org.hibernate.criterion.Order;
import org.hibernate.criterion.Restrictions;
import ais.database.hibernate.HibernateUtil;
import ais.database.model.sosial.AlokasiDonasi;
import ais.database.model.sosial.SocialCorrectionEvent;
import ais.database.model.sosial.TransaksiDonasi;

/** Maker-checker boundary for refund/reversal records; gateway execution remains external. */
public final class SocialCorrectionService {
    public SocialCorrectionEvent request(SocialRequestContext c,String transactionNumber,String type,BigDecimal amount,String reason,String idempotencyKey){
        new SocialPrivilegeGuard().require(c,SocialPrivilegeGuard.FINANCE);type=normalize(type);if(!("REFUND".equals(type)||"REVERSAL".equals(type)))throw new IllegalArgumentException("Tipe koreksi harus REFUND atau REVERSAL.");if(amount==null||amount.signum()<=0||amount.scale()>2)throw new IllegalArgumentException("Nominal koreksi tidak valid.");if(transactionNumber==null||transactionNumber.trim().isEmpty())throw new IllegalArgumentException("Nomor transaksi wajib diisi.");if(reason==null||reason.trim().length()<10)throw new IllegalArgumentException("Alasan koreksi minimal 10 karakter.");if(idempotencyKey==null||!idempotencyKey.matches("[A-Za-z0-9._:-]{8,120}"))throw new IllegalArgumentException("Idempotency key koreksi tidak valid.");amount=amount.setScale(2);transactionNumber=transactionNumber.trim();reason=reason.trim();
        Session s=null;Transaction tx=null;try{s=HibernateUtil.openSession();tx=s.beginTransaction();SocialCorrectionEvent old=(SocialCorrectionEvent)s.createCriteria(SocialCorrectionEvent.class).add(Restrictions.eq("tenantKey",c.getTenantKey())).add(Restrictions.eq("requestId",idempotencyKey)).setMaxResults(1).uniqueResult();if(old!=null){if(!"TRANSACTION".equals(old.getTargetType())||!same(old.getTargetReference(),transactionNumber)||!same(old.getCorrectionType(),type)||!sameMoney(old.getAmount(),amount)||!same(old.getReason(),reason)||!same(old.getCreatedBy(),c.getActorId()))throw new IllegalStateException("Idempotency key koreksi digunakan dengan payload berbeda.");tx.commit();return old;}TransaksiDonasi d=(TransaksiDonasi)s.createCriteria(TransaksiDonasi.class).add(Restrictions.eq("tenantKey",c.getTenantKey())).add(Restrictions.eq("transactionNumber",transactionNumber)).setMaxResults(1).uniqueResult();if(d==null||d.getPaidAt()==null)throw new IllegalArgumentException("Transaksi paid tidak ditemukan.");BigDecimal posted=(BigDecimal)s.createQuery("select sum(e.amount) from SocialCorrectionEvent e where e.tenantKey=:tenant and e.targetType='TRANSACTION' and e.targetReference=:ref and e.status='POSTED' and e.correctionType in ('REFUND','REVERSAL')").setString("tenant",c.getTenantKey()).setString("ref",transactionNumber).uniqueResult();if(posted==null)posted=BigDecimal.ZERO;if(posted.add(amount).compareTo(d.getGrossDonationAmount())>0)throw new IllegalStateException("Total refund/reversal melebihi dana transaksi.");SocialCorrectionEvent e=new SocialCorrectionEvent();e.setTenantKey(c.getTenantKey());e.setTargetType("TRANSACTION");e.setTargetReference(transactionNumber);e.setCorrectionType(type);e.setAmount(amount);e.setReason(reason);e.setPriorState(d.getStatus());e.setApprovalStatus("REQUESTED");e.setStatus("REQUESTED");e.setActor(c.getActorId());e.setRequestId(idempotencyKey);e.setCreatedBy(c.getActorId());s.save(e);tx.commit();return e;}catch(RuntimeException e){if(tx!=null)try{tx.rollback();}catch(Exception ignored){}throw e;}finally{close(s);}
    }
    public SocialCorrectionEvent approveAndPost(SocialRequestContext c,Long eventId){new SocialPrivilegeGuard().require(c,SocialPrivilegeGuard.APPROVE);Session s=null;Transaction tx=null;try{s=HibernateUtil.openSession();tx=s.beginTransaction();SocialCorrectionEvent e=(SocialCorrectionEvent)s.get(SocialCorrectionEvent.class,eventId);if(e==null||!c.getTenantKey().equals(e.getTenantKey()))throw new IllegalArgumentException("Koreksi tidak ditemukan.");s.lock(e,LockMode.UPGRADE);if("POSTED".equals(e.getStatus())){tx.commit();return e;}if(!"REQUESTED".equals(e.getStatus()))throw new IllegalStateException("Koreksi tidak berstatus REQUESTED.");if(c.getActorId().equals(e.getCreatedBy()))throw new SecurityException("Pembuat koreksi tidak boleh menyetujui koreksinya sendiri.");TransaksiDonasi d=(TransaksiDonasi)s.createCriteria(TransaksiDonasi.class).add(Restrictions.eq("tenantKey",c.getTenantKey())).add(Restrictions.eq("transactionNumber",e.getTargetReference())).setMaxResults(1).uniqueResult();if(d==null)throw new IllegalStateException("Transaksi koreksi tidak ditemukan.");s.lock(d,LockMode.UPGRADE);BigDecimal posted=(BigDecimal)s.createQuery("select sum(x.amount) from SocialCorrectionEvent x where x.tenantKey=:tenant and x.targetType='TRANSACTION' and x.targetReference=:ref and x.status='POSTED' and x.correctionType in ('REFUND','REVERSAL')").setString("tenant",c.getTenantKey()).setString("ref",e.getTargetReference()).uniqueResult();if(posted==null)posted=BigDecimal.ZERO;if(posted.add(e.getAmount()).compareTo(d.getGrossDonationAmount())>0)throw new IllegalStateException("Approval membuat total refund/reversal melebihi dana transaksi.");reduceUnspentAllocations(s,c,d,e.getAmount());e.setApprovalStatus("APPROVED");e.setStatus("POSTED");e.setResultingState("FINANCIAL_RETURN_POSTED");e.setUpdatedBy(c.getActorId());tx.commit();return e;}catch(RuntimeException e){if(tx!=null)try{tx.rollback();}catch(Exception ignored){}throw e;}finally{close(s);}}
    @SuppressWarnings("unchecked")
    private void reduceUnspentAllocations(Session s,SocialRequestContext c,TransaksiDonasi transaction,BigDecimal correctionAmount){
        List<AlokasiDonasi> allocations=s.createCriteria(AlokasiDonasi.class).add(Restrictions.eq("transaction",transaction)).add(Restrictions.eq("tenantKey",c.getTenantKey())).add(Restrictions.eq("status","POSTED")).addOrder(Order.asc("id")).list();
        BigDecimal available=BigDecimal.ZERO;
        for(AlokasiDonasi allocation:allocations){s.lock(allocation,LockMode.UPGRADE);available=available.add(unspentAmount(s,allocation));}
        if(available.compareTo(correctionAmount)<0)throw new IllegalStateException("Refund/reversal tidak dapat diposting karena dana sudah disalurkan atau saldo alokasi tidak cukup.");
        BigDecimal remaining=correctionAmount;
        for(AlokasiDonasi allocation:allocations){
            if(remaining.signum()==0)break;
            BigDecimal reducible=unspentAmount(s,allocation);if(reducible.signum()==0)continue;
            BigDecimal reduction=reducible.min(remaining);BigDecimal newAmount=allocation.getAmount().subtract(reduction).setScale(2,BigDecimal.ROUND_HALF_UP);
            allocation.setAmount(newAmount);if(newAmount.signum()==0)allocation.setStatus("REVERSED");allocation.setUpdatedBy(c.getActorId());remaining=remaining.subtract(reduction);
        }
    }
    private BigDecimal unspentAmount(Session s,AlokasiDonasi allocation){BigDecimal distributed=(BigDecimal)s.createQuery("select sum(x.amount) from DetailPenyaluranDonasi x where x.sourceAllocation=:allocation and x.status='POSTED'").setEntity("allocation",allocation).uniqueResult();if(distributed==null)distributed=BigDecimal.ZERO;BigDecimal result=allocation.getAmount().subtract(distributed);if(result.signum()<0)throw new IllegalStateException("Alokasi memiliki penyaluran melebihi nominalnya.");return result;}
    private boolean same(String a,String b){return a==null?b==null:a.equals(b);} private boolean sameMoney(BigDecimal a,BigDecimal b){return a!=null&&b!=null&&a.compareTo(b)==0;} private String normalize(String v){return v==null?"":v.trim().toUpperCase();} private void close(Session s){if(s!=null)try{s.close();}catch(Exception ignored){}}
}
