package ais.action.master.sosial.helper;

import java.math.BigDecimal;
import org.hibernate.LockMode;
import org.hibernate.Session;
import org.hibernate.Transaction;
import org.hibernate.criterion.Restrictions;
import ais.database.hibernate.HibernateUtil;
import ais.database.model.sosial.SocialCorrectionEvent;
import ais.database.model.sosial.TransaksiDonasi;

/** Maker-checker boundary for refund/reversal records; gateway execution remains external. */
public final class SocialCorrectionService {
    public SocialCorrectionEvent request(SocialRequestContext c,String transactionNumber,String type,BigDecimal amount,String reason,String idempotencyKey){
        new SocialPrivilegeGuard().require(c,SocialPrivilegeGuard.FINANCE);type=normalize(type);if(!("REFUND".equals(type)||"REVERSAL".equals(type)))throw new IllegalArgumentException("Tipe koreksi harus REFUND atau REVERSAL.");if(amount==null||amount.signum()<=0)throw new IllegalArgumentException("Nominal koreksi tidak valid.");if(reason==null||reason.trim().length()<10)throw new IllegalArgumentException("Alasan koreksi minimal 10 karakter.");if(idempotencyKey==null||!idempotencyKey.matches("[A-Za-z0-9._:-]{8,120}"))throw new IllegalArgumentException("Idempotency key koreksi tidak valid.");
        Session s=null;Transaction tx=null;try{s=HibernateUtil.openSession();tx=s.beginTransaction();SocialCorrectionEvent old=(SocialCorrectionEvent)s.createCriteria(SocialCorrectionEvent.class).add(Restrictions.eq("tenantKey",c.getTenantKey())).add(Restrictions.eq("requestId",idempotencyKey)).setMaxResults(1).uniqueResult();if(old!=null){tx.commit();return old;}TransaksiDonasi d=(TransaksiDonasi)s.createCriteria(TransaksiDonasi.class).add(Restrictions.eq("tenantKey",c.getTenantKey())).add(Restrictions.eq("transactionNumber",transactionNumber)).setMaxResults(1).uniqueResult();if(d==null||d.getPaidAt()==null)throw new IllegalArgumentException("Transaksi paid tidak ditemukan.");BigDecimal posted=(BigDecimal)s.createQuery("select sum(e.amount) from SocialCorrectionEvent e where e.tenantKey=:tenant and e.targetType='TRANSACTION' and e.targetReference=:ref and e.status='POSTED' and e.correctionType in ('REFUND','REVERSAL')").setString("tenant",c.getTenantKey()).setString("ref",transactionNumber).uniqueResult();if(posted==null)posted=BigDecimal.ZERO;if(posted.add(amount).compareTo(d.getGrossDonationAmount())>0)throw new IllegalStateException("Total refund/reversal melebihi dana transaksi.");SocialCorrectionEvent e=new SocialCorrectionEvent();e.setTenantKey(c.getTenantKey());e.setTargetType("TRANSACTION");e.setTargetReference(transactionNumber);e.setCorrectionType(type);e.setAmount(amount.setScale(2,BigDecimal.ROUND_HALF_UP));e.setReason(reason.trim());e.setPriorState(d.getStatus());e.setApprovalStatus("REQUESTED");e.setStatus("REQUESTED");e.setActor(c.getActorId());e.setRequestId(idempotencyKey);e.setCreatedBy(c.getActorId());s.save(e);tx.commit();return e;}catch(RuntimeException e){if(tx!=null)try{tx.rollback();}catch(Exception ignored){}throw e;}finally{close(s);}
    }
    public SocialCorrectionEvent approveAndPost(SocialRequestContext c,Long eventId){new SocialPrivilegeGuard().require(c,SocialPrivilegeGuard.APPROVE);Session s=null;Transaction tx=null;try{s=HibernateUtil.openSession();tx=s.beginTransaction();SocialCorrectionEvent e=(SocialCorrectionEvent)s.get(SocialCorrectionEvent.class,eventId);if(e==null||!c.getTenantKey().equals(e.getTenantKey()))throw new IllegalArgumentException("Koreksi tidak ditemukan.");s.lock(e,LockMode.UPGRADE);if("POSTED".equals(e.getStatus())){tx.commit();return e;}if(!"REQUESTED".equals(e.getStatus()))throw new IllegalStateException("Koreksi tidak berstatus REQUESTED.");if(c.getActorId().equals(e.getCreatedBy()))throw new SecurityException("Pembuat koreksi tidak boleh menyetujui koreksinya sendiri.");TransaksiDonasi d=(TransaksiDonasi)s.createCriteria(TransaksiDonasi.class).add(Restrictions.eq("tenantKey",c.getTenantKey())).add(Restrictions.eq("transactionNumber",e.getTargetReference())).setMaxResults(1).uniqueResult();if(d==null)throw new IllegalStateException("Transaksi koreksi tidak ditemukan.");s.lock(d,LockMode.UPGRADE);BigDecimal posted=(BigDecimal)s.createQuery("select sum(x.amount) from SocialCorrectionEvent x where x.tenantKey=:tenant and x.targetType='TRANSACTION' and x.targetReference=:ref and x.status='POSTED' and x.correctionType in ('REFUND','REVERSAL')").setString("tenant",c.getTenantKey()).setString("ref",e.getTargetReference()).uniqueResult();if(posted==null)posted=BigDecimal.ZERO;if(posted.add(e.getAmount()).compareTo(d.getGrossDonationAmount())>0)throw new IllegalStateException("Approval membuat total refund/reversal melebihi dana transaksi.");e.setApprovalStatus("APPROVED");e.setStatus("POSTED");e.setResultingState("FINANCIAL_RETURN_POSTED");e.setUpdatedBy(c.getActorId());tx.commit();return e;}catch(RuntimeException e){if(tx!=null)try{tx.rollback();}catch(Exception ignored){}throw e;}finally{close(s);}}
    private String normalize(String v){return v==null?"":v.trim().toUpperCase();} private void close(Session s){if(s!=null)try{s.close();}catch(Exception ignored){}}
}
