package ais.action.master.sosial.helper;

import java.math.BigDecimal; import java.util.Calendar; import java.util.Date; import org.hibernate.LockMode; import org.hibernate.Session; import org.hibernate.Transaction; import org.hibernate.criterion.Restrictions; import org.json.JSONObject;
import ais.action.master.helper.PembayaranGatewayKatalog; import ais.common.Common; import ais.database.hibernate.HibernateUtil; import ais.database.model.sosial.*;

public final class SocialPaymentService {
 public PembayaranDonasi initiate(SocialRequestContext context,String transactionNumber,String gatewayId){
  if(!"smartlink".equals(gatewayId))throw new IllegalArgumentException("Gateway sosial tidak didukung.");if(!PembayaranGatewayKatalog.aktif(PembayaranGatewayKatalog.cari(gatewayId)))throw new IllegalStateException("Smartlink tidak aktif pada katalog gateway.");
  Session s=null;Transaction tx=null;PembayaranDonasi payment;SocialSmartlinkCredentialService.Credential credential;String name,email,phone,description;try{s=HibernateUtil.openSession();tx=s.beginTransaction();new SocialComplianceService().requireCollectionReady(s,context);if(!SocialFeatureFlags.enabled(s,context,SocialFeatureFlags.SMARTLINK))throw new IllegalStateException("Smartlink Sosial belum diaktifkan.");
   TransaksiDonasi donation=(TransaksiDonasi)s.createCriteria(TransaksiDonasi.class).add(Restrictions.eq("tenantKey",context.getTenantKey())).add(Restrictions.eq("transactionNumber",transactionNumber)).setMaxResults(1).uniqueResult();if(donation==null)throw new IllegalArgumentException("Transaksi tidak ditemukan.");s.lock(donation,LockMode.UPGRADE);guardOwner(context,donation);if(!("DRAFT".equals(donation.getStatus())||"PENDING_PAYMENT".equals(donation.getStatus())))throw new IllegalStateException("Status transaksi tidak dapat dibayar.");
   PembayaranDonasi active=(PembayaranDonasi)s.createCriteria(PembayaranDonasi.class).add(Restrictions.eq("transaction",donation)).add(Restrictions.in("paymentStatus",new String[]{"CREATED","PENDING","VA_ISSUED"})).setMaxResults(1).uniqueResult();if(active!=null){tx.commit();return active;}
   SocialSmartlinkCredentialService credentialService=new SocialSmartlinkCredentialService();SosialChannel channel=donation.getSosialChannel();if(channel==null){channel=credentialService.requireChannel(context,donation.getFundType());donation.setSosialChannel(channel);}credential=credentialService.load(channel);BigDecimal fee=credential.getFee();BigDecimal total=SocialFinancialInvariantService.totalCharged(donation.getGrossDonationAmount(),donation.getPlatformContribution(),fee);donation.setGatewayFee(fee);donation.setTotalPayable(total);SocialStateMachine.requireDonation(donation.getStatus(),"PENDING_PAYMENT");donation.setStatus("PENDING_PAYMENT");
   Calendar c=Calendar.getInstance();c.add(Calendar.DAY_OF_MONTH,1);payment=new PembayaranDonasi();payment.setTenantKey(context.getTenantKey());payment.setTransaction(donation);payment.setSosialChannel(channel);payment.setGatewayId(gatewayId);payment.setGatewayOrderId(SocialSecurity.reference("SOCSL"));payment.setRequestAmount(donation.getGrossDonationAmount());payment.setFee(fee);payment.setTotal(total);payment.setCurrency("IDR");payment.setPaymentStatus("CREATED");payment.setIssuedAt(new Date());payment.setExpiryAt(c.getTime());payment.setReconciliationStatus("PENDING");payment.setRequestId(context.getRequestId());payment.setCreatedBy(context.getActorId());s.save(payment);name=donation.getDonorNameSnapshot();email=donation.getDonorContactSnapshot();phone=donation.getDonorIdentity()==null?null:donation.getDonorIdentity().getPhone();description="ZIS/Donasi "+donation.getTransactionNumber();tx.commit();
  }catch(RuntimeException e){if(tx!=null)try{tx.rollback();}catch(Exception ignored){}throw e;}finally{close(s);}
  try{JSONObject response=new SocialSmartlinkAdapter().createOrder(credential,payment.getGatewayOrderId(),payment.getTotal(),description,name,email,phone,payment.getExpiryAt());JSONObject data=response.getJSONObject("data");return updateGatewayResult(payment.getId(),"VA_ISSUED",data.optString("payment_url",null),data.optString("reference",null),null);}
  catch(Exception e){PembayaranDonasi current=updateGatewayResult(payment.getId(),"FAILED",null,null,e.getMessage());if("PAID".equals(current.getPaymentStatus()))return current;throw e instanceof RuntimeException?(RuntimeException)e:new IllegalStateException(e);}
 }
 private PembayaranDonasi updateGatewayResult(Long id,String status,String url,String ref,String failure){Session s=null;Transaction tx=null;try{s=HibernateUtil.openSession();tx=s.beginTransaction();PembayaranDonasi p=(PembayaranDonasi)s.get(PembayaranDonasi.class,id);if(p==null)throw new IllegalStateException("Payment attempt hilang setelah create order.");s.lock(p,LockMode.UPGRADE);if("PAID".equals(p.getPaymentStatus())){tx.commit();return p;}SocialStateMachine.requirePayment(p.getPaymentStatus(),status);p.setPaymentStatus(status);p.setPaymentUrl(url);p.setGatewayReference(ref);p.setFailureReason(failure);tx.commit();return p;}catch(RuntimeException e){if(tx!=null)try{tx.rollback();}catch(Exception ignored){}throw e;}finally{close(s);}}
 private void guardOwner(SocialRequestContext c,TransaksiDonasi d){if(d.getDonorIdentity()!=null){if(!c.isAuthenticated()||d.getDonorIdentity().getTbmuser()==null||!c.getUser().getUserId().equals(d.getDonorIdentity().getTbmuser().getUserId()))throw new SecurityException("Transaksi bukan milik pengguna.");}}
 private void close(Session s){if(s!=null)try{s.close();}catch(Exception ignored){}}
}
