package ais.action.master.sosial.helper;

import java.math.BigDecimal; import java.util.List;
import org.hibernate.Session; import org.hibernate.Transaction; import org.hibernate.criterion.Order; import org.hibernate.criterion.Restrictions;
import ais.database.hibernate.HibernateUtil; import ais.database.model.akunting.Akun; import ais.database.model.sekolah.Sekolah; import ais.database.model.sekolah.Yayasan; import ais.database.model.sosial.SosialChannel;

/** Restricted write boundary for the SosialChannel master; blank secrets preserve existing values. */
public final class SosialChannelAdminService {
 @SuppressWarnings("unchecked") public List<SosialChannel> list(SocialRequestContext context){new SocialPrivilegeGuard().require(context,SocialPrivilegeGuard.ADMIN);Session s=null;try{s=HibernateUtil.openSession();return s.createCriteria(SosialChannel.class).add(Restrictions.eq("tenantKey",context.getTenantKey())).addOrder(Order.asc("nama")).list();}finally{close(s);}}
 public SosialChannel save(SocialRequestContext context,Long id,String code,String name,String description,Long accountId,Long foundationId,Long schoolId,boolean active,boolean smartlinkEnabled,String mode,String url,String username,String passwordPlain,String channels,BigDecimal fee,String callbackSecretPlain,String allowedIps){new SocialPrivilegeGuard().require(context,SocialPrivilegeGuard.ADMIN);validate(code,name,accountId,smartlinkEnabled,url,username,passwordPlain,callbackSecretPlain,id);Session s=null;Transaction tx=null;try{s=HibernateUtil.openSession();tx=s.beginTransaction();SosialChannel channel=id==null?new SosialChannel():(SosialChannel)s.get(SosialChannel.class,id);if(channel==null||id!=null&&!context.getTenantKey().equals(channel.getTenantKey()))throw new SecurityException("SosialChannel tidak ditemukan.");Akun account=(Akun)s.get(Akun.class,accountId);if(account==null)throw new IllegalArgumentException("Akun Kas/Bank tidak ditemukan.");channel.setTenantKey(context.getTenantKey());channel.setKode(code);channel.setNama(name);channel.setKeterangan(description);channel.setProvider("SMARTLINK");channel.setOperationMode("PRODUCTION".equalsIgnoreCase(mode)?"PRODUCTION":"SANDBOX");channel.setAktif(Boolean.valueOf(active));channel.setSmartlinkEnabled(Boolean.valueOf(smartlinkEnabled));channel.setSmartlinkUrl(url);channel.setSmartlinkUsername(username);channel.setSmartlinkChannels(channels);channel.setSmartlinkFee(fee==null?BigDecimal.ZERO:fee.setScale(2,BigDecimal.ROUND_HALF_UP));channel.setSmartlinkCallbackAllowedIps(allowedIps);channel.setAkun(account);channel.setYayasan(foundationId==null?null:(Yayasan)s.get(Yayasan.class,foundationId));channel.setSekolah(schoolId==null?null:(Sekolah)s.get(Sekolah.class,schoolId));SocialSmartlinkCredentialService secrets=new SocialSmartlinkCredentialService();if(notBlank(passwordPlain))channel.setSmartlinkPasswordCiphertext(secrets.encryptSecret(passwordPlain));if(notBlank(callbackSecretPlain))channel.setSmartlinkCallbackSecretCiphertext(secrets.encryptSecret(callbackSecretPlain));channel.setStatus(active?"ACTIVE":"INACTIVE");if(id==null){channel.setCreatedBy(context.getActorId());s.save(channel);}else channel.setUpdatedBy(context.getActorId());tx.commit();return channel;}catch(RuntimeException e){if(tx!=null)try{tx.rollback();}catch(Exception ignored){}throw e;}finally{close(s);}}
 private void validate(String code,String name,Long accountId,boolean enabled,String url,String username,String password,String secret,Long id){if(code==null||!code.matches("[A-Za-z0-9_-]{1,80}"))throw new IllegalArgumentException("Kode SosialChannel tidak valid.");if(!notBlank(name))throw new IllegalArgumentException("Nama SosialChannel wajib diisi.");if(accountId==null)throw new IllegalArgumentException("Akun Kas/Bank wajib diisi.");if(enabled&&(empty(url)||empty(username)))throw new IllegalArgumentException("URL dan username Smartlink wajib diisi.");if(id==null&&enabled&&(empty(password)||empty(secret)))throw new IllegalArgumentException("Password dan callback secret wajib untuk channel baru.");if(notBlank(secret)&&secret.length()<16)throw new IllegalArgumentException("Callback secret minimal 16 karakter.");}
 private boolean notBlank(String v){return !empty(v);} private boolean empty(String v){return v==null||v.trim().isEmpty();} private void close(Session s){if(s!=null)try{s.close();}catch(Exception ignored){}}
}
