<section class="repo-wrap repo-page-head repo-help-head">
  <div class="repo-breadcrumb"><a href="<%=root%>/repository">Beranda</a> / Bantuan</div>
  <p class="repo-eyebrow">Manual layanan Repository</p>
  <h1>Pusat bantuan Repository</h1>
  <p>Panduan lengkap untuk menemukan, membaca, mengunduh, mengajukan, memperbaiki, dan menjaga karya ilmiah di Repository <%=rh(institution)%>.</p>
  <p class="repo-help-meta"><strong>Pemilik konten:</strong> Pengelola Repository · <strong>Terakhir ditinjau:</strong> 24 Agustus 2026 · <strong>Siklus tinjau:</strong> minimal setiap 6 bulan atau setelah perubahan kebijakan.</p>
  <div class="repo-help-search"><label for="repo-help-search"><strong>Cari di dalam panduan</strong></label><div><input id="repo-help-search" type="search" placeholder="Contoh: unggah PDF, embargo, metadata" autocomplete="off" data-repo-help-search><button class="repo-btn" type="button" data-repo-help-clear hidden>Hapus</button></div><p class="repo-muted" role="status" aria-live="polite" data-repo-help-status>17 bab tersedia.</p></div>
  <div class="repo-paper-actions"><a class="repo-btn repo-btn-primary" href="#mulai">Mulai membaca</a><a class="repo-btn" href="<%=root%>/repository/ask#repository-faq">Cari 300 tanya jawab</a><a class="repo-btn" href="#troubleshooting">Atasi masalah</a></div>
</section>

<section class="repo-wrap repo-help-layout" id="mulai">
  <aside class="repo-card repo-help-toc" aria-label="Daftar isi pusat bantuan">
    <strong>Daftar isi</strong>
    <nav>
      <a href="#orientasi">1. Orientasi dan peran</a><a href="#pencarian">2. Pencarian publikasi</a><a href="#record">3. Membaca record</a><a href="#akses">4. Akses dan unduhan</a>
      <a href="#akun">5. Akun dan keamanan</a><a href="#persiapan">6. Persiapan deposit</a><a href="#upload">7. Sembilan tahap deposit</a><a href="#metadata">8. Standar metadata</a>
      <a href="#berkas">9. Berkas, lisensi, embargo</a><a href="#review">10. Review dan revisi</a><a href="#publikasi">11. Publikasi dan versi</a><a href="#sitasi">12. Sitasi dan identifier</a>
      <a href="#integrasi">13. Alert dan integrasi</a><a href="#privasi">14. Privasi dan aksesibilitas</a><a href="#troubleshooting">15. Pemecahan masalah</a><a href="#dukungan">16. Meminta bantuan</a><a href="#glosarium">17. Glosarium</a>
    </nav>
  </aside>

  <article class="repo-help-manual">
    <section class="repo-card repo-help-intro">
      <h2>Cara menggunakan manual ini</h2>
      <p>Manual ini disusun berdasarkan perjalanan pengguna, bukan berdasarkan nama menu teknis. Pengunjung umum dapat memulai dari pencarian, pembacaan record, akses naskah, dan sitasi. Mahasiswa, dosen, peneliti, atau pegawai yang akan menyerahkan karya dapat langsung menuju persiapan deposit, sembilan tahap pengajuan, metadata, dan berkas. Reviewer serta administrator dapat memakai bagian review, publikasi, versi, keamanan, dan penanganan masalah sebagai rujukan komunikasi dengan depositor. Setiap bab menerangkan tujuan, langkah, hasil yang diharapkan, tanda kegagalan, dan tindakan berikutnya.</p>
      <p>Istilah <em>record</em> berarti satu entri bibliografis yang mewakili sebuah karya. Record dapat mempunyai metadata saja atau disertai satu maupun beberapa berkas. Istilah <em>deposit</em> berarti proses menyerahkan karya ke Repository, bukan memindahkan hak cipta secara otomatis. Status akses pada metadata dan status akses pada berkas perlu dibedakan. Sebuah judul dapat ditemukan oleh publik sementara PDF-nya hanya tersedia setelah login, berada dalam embargo, atau dibatasi berdasarkan kebijakan.</p>
      <div class="repo-help-callout"><strong>Prinsip aman</strong><p>Simpan draf secara berkala, periksa record sebelum mengirim, jangan mengunggah data pribadi yang tidak diperlukan, jangan membuat deposit kedua untuk memperbaiki deposit pertama, dan jangan membagikan kata sandi. Bila ragu, catat URL atau nomor pengajuan lalu tanyakan kepada pengelola.</p></div>
    </section>

    <section class="repo-card repo-help-chapter" id="orientasi">
      <p class="repo-eyebrow">Bab 1</p><h2>Orientasi Repository dan pembagian peran</h2>
      <p>Repository adalah layanan institusi untuk mengumpulkan, menjelaskan, menemukan, mendiseminasikan, dan melestarikan keluaran akademik. Isinya dapat berupa skripsi, tesis, disertasi, artikel, prosiding, buku, bab buku, laporan penelitian, bahan ajar, dataset, perangkat lunak, serta materi pendukung. Repository bukan sekadar tempat menyimpan PDF. Nilai utamanya muncul ketika metadata konsisten, identifier stabil, hak akses jelas, berkas terjaga integritasnya, dan karya dapat ditemukan kembali melalui mesin pencari maupun protokol pertukaran metadata.</p>
      <p>Pengunjung umum menjelajahi metadata, membaca abstrak, memakai filter, menyalin sitasi, dan mengakses berkas sesuai izin. Pengguna terautentikasi memperoleh hak berdasarkan akun eCampus serta perannya. Depositor membuat dan memperbaiki pengajuan miliknya. Reviewer menilai kelengkapan, kesesuaian koleksi, mutu metadata, berkas, lisensi, dan akses. Administrator mengelola kebijakan, koleksi, authority penulis, integrasi, kualitas data, serta tindakan khusus seperti penarikan. Pembagian ini menjaga agar sebuah perubahan memiliki penanggung jawab dan jejak audit.</p>
      <p>Jangan menyimpulkan bahwa tombol yang terlihat merupakan bukti kewenangan akhir. Sistem selalu memeriksa hak pada sisi server. Depositor bertanggung jawab atas kebenaran materi dan izin distribusi; reviewer membantu memastikan standar; administrator menjaga layanan, tetapi tidak menggantikan tanggung jawab akademik penulis. Jika suatu langkah tidak tersedia, periksa apakah akun sudah login, koleksi menerima deposit, karya masih dapat diedit, dan peran pengguna sesuai.</p>
      <div class="repo-help-diagram" role="img" aria-label="Alur ekosistem Repository dari penulis ke depositor, reviewer, publikasi, pembaca, dan preservasi">
        <div class="repo-help-node"><b>Penulis</b><span>Menyiapkan karya dan izin</span></div><i>→</i><div class="repo-help-node"><b>Depositor</b><span>Mengisi metadata dan berkas</span></div><i>→</i><div class="repo-help-node"><b>Reviewer</b><span>Memeriksa dan memberi keputusan</span></div><i>→</i><div class="repo-help-node"><b>Record publik</b><span>Ditemukan dan disitasi</span></div><i>→</i><div class="repo-help-node"><b>Preservasi</b><span>Fixity, versi, provenance</span></div>
      </div>
      <h3>Hasil yang benar</h3><p>Sebuah karya yang dikelola dengan benar memiliki judul dan penulis akurat, abstrak serta kata kunci informatif, koleksi tepat, status akses eksplisit, berkas yang dapat dibuka, dan identifier yang dapat dirujuk. Riwayat pengajuan memperlihatkan kapan karya dibuat, diperiksa, dikembalikan, disetujui, atau ditarik. Record dapat tetap ada sebagai metadata atau tombstone walaupun berkas tidak tersedia, karena keberadaan jejak ilmiah perlu dipertahankan.</p>
    </section>

    <section class="repo-card repo-help-chapter" id="pencarian">
      <p class="repo-eyebrow">Bab 2</p><h2>Mencari dan menelusuri publikasi secara efektif</h2>
      <p>Mulailah dengan kebutuhan informasi yang jelas. Jika mengetahui judul, masukkan bagian judul yang paling khas, bukan seluruh kalimat beserta tanda baca. Jika mencari penulis, gunakan bentuk nama yang tampil pada publikasi dan coba variasi tanpa gelar. Untuk topik, pilih dua sampai empat istilah inti yang membedakan bidang, objek, lokasi, atau metode. Pencarian terlalu umum menghasilkan banyak record; pencarian terlalu panjang dapat kehilangan record karena perbedaan ejaan.</p>
      <p>Pilih bidang pencarian sesuai bukti yang dimiliki. Bidang judul cocok untuk nama karya, penulis untuk nama kontributor, abstrak untuk uraian penelitian, subjek untuk kata kunci, program studi untuk unit akademik, pembimbing untuk nama pembimbing, serta identifier untuk DOI, Handle, atau nomor lain. Pencarian semua bidang berguna pada tahap awal, tetapi hasilnya perlu dipersempit. Gunakan frasa tepat bila urutan kata harus sama, pilihan OR untuk sinonim, dan pengecualian NOT untuk istilah yang tidak diinginkan.</p>
      <p>Setelah hasil muncul, baca jumlah hasil dan chip filter aktif. Terapkan filter satu per satu: jenis dokumen, rentang tahun, koleksi, bahasa, kebijakan akses, atau ketersediaan naskah. Jangan mengaktifkan banyak filter sekaligus sebelum memahami dampaknya. Jika hasil menjadi nol, hapus filter paling spesifik terlebih dahulu. Urutan terbaru berguna untuk perkembangan mutakhir; urutan terlama untuk sejarah; judul A–Z untuk daftar tematik; penulis A–Z untuk pemeriksaan authority.</p>
      <div class="repo-help-diagram repo-help-diagram-stack" role="img" aria-label="Diagram penyempurnaan pencarian dari kebutuhan informasi sampai verifikasi record">
        <div class="repo-help-node"><b>1. Rumuskan kebutuhan</b><span>Topik, penulis, tahun, jenis</span></div><i>↓</i><div class="repo-help-node"><b>2. Pilih kata inti</b><span>Gunakan istilah khas dan sinonim</span></div><i>↓</i><div class="repo-help-node"><b>3. Pilih bidang</b><span>Judul, penulis, abstrak, identifier</span></div><i>↓</i><div class="repo-help-node"><b>4. Saring hasil</b><span>Koleksi, tahun, akses, bahasa</span></div><i>↓</i><div class="repo-help-node"><b>5. Verifikasi</b><span>Buka record dan baca metadata lengkap</span></div>
      </div>
      <h3>Contoh strategi</h3><p>Untuk mencari penelitian pendidikan karakter di sekolah dasar, mulai dengan “pendidikan karakter sekolah dasar”. Bila terlalu luas, tambah lokasi atau metode. Bila terlalu sempit, cari “pendidikan karakter” lalu pilih jenis tugas akhir dan tahun. Untuk karya tertentu, gunakan potongan judul dan nama belakang penulis. Untuk DOI, tempel nilai DOI tanpa awalan URL. Selalu buka record sebelum menyimpulkan relevansi karena cuplikan daftar hanya memperlihatkan sebagian abstrak.</p>
      <h3>Menyimpan dan mengulang pencarian</h3><p>Pengguna yang login dapat menyimpan pencarian atau mengaktifkan alert jika fitur tersedia. Beri nama yang menjelaskan topik dan filter, misalnya “literasi digital—artikel—2024 ke atas”. Sebelum mengaktifkan alert, pastikan hasil awal memang relevan. Pencarian tersimpan menyimpan parameter, bukan salinan record; hasil dapat berubah ketika metadata diperbarui atau publikasi baru masuk.</p>
    </section>

    <section class="repo-card repo-help-chapter" id="record">
      <p class="repo-eyebrow">Bab 3</p><h2>Membaca halaman detail record</h2>
      <p>Halaman detail menyatukan identitas karya, deskripsi bibliografis, akses berkas, statistik, versi, dan publikasi terkait. Judul harus dibaca bersama penulis, tahun, jenis dokumen, koleksi, program studi, serta abstrak. Badge akses menjelaskan kebijakan umum record atau berkas. Identifier memberi rujukan yang lebih stabil daripada menyalin alamat sementara dari hasil pencarian. Statistik dilihat dan unduhan menunjukkan aktivitas layanan, bukan otomatis mutu ilmiah.</p>
      <p>Periksa abstrak untuk tujuan, metode, objek, hasil, dan kesimpulan. Kata kunci membantu navigasi ke topik sejenis, tetapi dapat berasal dari pilihan penulis sehingga tidak selalu menggunakan istilah yang sama. Metadata tambahan mungkin menampilkan pembimbing, penguji, penerbit, bahasa, lisensi, tanggal, nomor halaman, dan relasi. Jika sebuah field kosong, jangan mengasumsikan informasi itu tidak ada dalam dokumen; metadata mungkin belum dilengkapi atau tidak berlaku untuk jenis tersebut.</p>
      <p>Panel berkas membedakan metadata dari objek digital. Nama berkas, format, ukuran, status akses, dan checksum dapat ditampilkan sesuai kewenangan. Pratinjau membuka berkas secara inline jika aman dan didukung, sedangkan unduh menyimpan salinan. Pada karya berembargo, metadata dapat terlihat sebelum berkas dibuka. Pada record terbatas, pengguna mungkin diminta login walaupun halaman detail dapat dibaca tanpa akun.</p>
      <h3>Daftar pemeriksaan sebelum memakai karya</h3>
      <ol><li>Pastikan judul, penulis, dan tahun sesuai kebutuhan.</li><li>Baca abstrak lengkap, bukan hanya cuplikan hasil.</li><li>Perhatikan jenis dokumen karena skripsi, artikel, dan dataset memiliki konteks berbeda.</li><li>Periksa apakah ada versi lebih baru atau keterangan bahwa karya digantikan.</li><li>Gunakan DOI atau Handle untuk sitasi bila tersedia.</li><li>Baca lisensi dan pembatasan sebelum menggunakan ulang gambar, tabel, instrumen, atau data.</li><li>Verifikasi informasi penting dengan membuka sumber utama sesuai hak akses.</li></ol>
      <p>Jika metadata tampak salah, catat URL, identifier, field yang bermasalah, nilai yang tampil, nilai yang seharusnya, dan sumber pembanding. Jangan membuat pengajuan baru hanya untuk mengoreksi record yang sudah terbit. Laporkan melalui pengelola agar koreksi mengikuti riwayat dan tidak menghasilkan duplikasi.</p>
    </section>

    <section class="repo-card repo-help-chapter" id="akses">
      <p class="repo-eyebrow">Bab 4</p><h2>Memahami akses dan mengunduh naskah</h2>
      <p>Akses ditentukan oleh kombinasi status record, kebijakan berkas, autentikasi, embargo, peran, dan lisensi. Open Access berarti berkas tertentu dapat dibuka sesuai kebijakan tanpa pembatasan akun. Akses terautentikasi mengharuskan login. Khusus institusi dapat memerlukan keanggotaan atau kondisi jaringan. Terbatas berarti hanya kelompok tertentu atau proses permintaan yang diperbolehkan. Metadata saja berarti tidak ada berkas publik, walaupun berkas preservasi mungkin tersimpan secara internal.</p>
      <p>Untuk mengunduh, buka halaman detail dan lihat panel naskah lengkap. Bila tombol tersedia, periksa nama serta ukuran berkas lalu pilih pratinjau atau unduh. Jika diminta login, masuk menggunakan akun sendiri dan kembali ke record. Bila tombol tidak muncul, baca badge akses dan tanggal embargo. Jangan mengubah URL, menebak alamat file, memakai akun orang lain, atau mencoba melewati pemeriksaan server. Pembatasan adalah bagian dari perlindungan hak dan privasi.</p>
      <div class="repo-help-decision" role="img" aria-label="Pohon keputusan akses berkas">
        <div class="repo-help-node repo-help-node-main"><b>Apakah berkas tercantum?</b></div>
        <div class="repo-help-branches"><div><b>Tidak</b><span>Metadata saja atau berkas belum dipublikasikan. Periksa keterangan dan hubungi pengelola bila perlu.</span></div><div><b>Ya</b><span>Periksa badge akses.</span></div></div>
        <div class="repo-help-branches"><div><b>Open Access</b><span>Pratinjau atau unduh sesuai lisensi.</span></div><div><b>Login/institusi</b><span>Masuk dengan akun yang berhak.</span></div><div><b>Embargo/terbatas</b><span>Tunggu tanggal akhir atau ikuti prosedur izin.</span></div></div>
      </div>
      <p>Unduhan yang berhasil tidak memberikan hak untuk menjual, menyebarkan ulang, menghapus atribusi, atau memakai materi di luar lisensi. Gunakan karya untuk tujuan yang sah, sitasi sumber, dan periksa izin pihak ketiga. Jika PDF gagal dibuka, pastikan unduhan selesai, ukuran tidak nol, dan perangkat memiliki pembaca PDF terbaru. Coba pratinjau sekali; bila tetap gagal, laporkan identifier serta nama berkas tanpa mengirim kata sandi.</p>
      <h3>Permintaan akses</h3><p>Jika penelitian membutuhkan materi terbatas, jelaskan identitas, afiliasi, tujuan, bagian yang diperlukan, durasi penggunaan, dan cara menjaga data. Pengelola mungkin perlu meminta persetujuan pemegang hak atau pemilik data. Tidak semua permintaan dapat dipenuhi. Metadata publik tetap dapat disitasi meskipun naskah tidak dapat dibagikan.</p>
    </section>

    <section class="repo-card repo-help-chapter" id="akun">
      <p class="repo-eyebrow">Bab 5</p><h2>Akun eCampus, sesi, peran, dan keamanan</h2>
      <p>Repository menggunakan identitas eCampus untuk mengenali pengguna. Masuk melalui halaman resmi, periksa nama institusi dan alamat situs, lalu gunakan akun pribadi. Jangan menyimpan kata sandi pada komputer umum. Setelah selesai mengelola deposit atau review, keluar dari akun dan tutup peramban. Sistem dapat mengakhiri sesi setelah tidak aktif untuk mengurangi risiko penyalahgunaan; simpan draf sebelum meninggalkan formulir.</p>
      <p>Hak menu mengikuti peran. Pengguna umum tidak perlu login untuk metadata publik. Depositor melihat Karya Saya dan, bila koleksi tersedia, dapat membuat deposit. Reviewer melihat antrean yang diizinkan, sedangkan administrator mempunyai fungsi tata kelola tambahan. Peran tidak diberikan hanya karena seseorang mengetahui URL. Jika menu tidak muncul, pastikan akun benar, status pengguna aktif, dan kewenangan sudah diberikan oleh unit yang berwenang.</p>
      <p>Jika lupa kata sandi atau akun terkunci, gunakan prosedur pemulihan eCampus. Pengelola Repository tidak semestinya meminta kata sandi, kode verifikasi, atau salinan penuh identitas melalui pesan biasa. Jika mencurigai akun disalahgunakan, ganti kata sandi melalui kanal resmi, keluar dari sesi lain bila tersedia, dan laporkan waktu serta aktivitas yang tidak dikenali. Jangan menunggu sampai deposit atau keputusan review berubah.</p>
      <h3>Masalah sesi</h3><p>Apabila setelah login halaman kembali ke beranda, muat ulang satu kali dan pastikan cookie sesi tidak diblokir. Hindari membuka banyak akun pada profil peramban yang sama. Untuk perangkat bersama, gunakan jendela privat hanya bila kebijakan institusi mengizinkan dan selalu tutup seluruh jendela setelah selesai. Pesan 403 biasanya berarti identitas dikenali tetapi tidak berhak; pesan login berulang dapat menunjukkan sesi kedaluwarsa. Catat waktu, URL, peramban, dan pesan yang tampil ketika meminta bantuan.</p>
      <div class="repo-help-callout repo-help-callout-warning"><strong>Jangan pernah dikirim</strong><p>Kata sandi, kode OTP, token sesi, salinan database, atau tangkapan layar yang memperlihatkan data pribadi lengkap. Tim bantuan cukup menerima nama pengguna, peran yang diharapkan, URL, waktu kejadian, dan pesan galat.</p></div>
    </section>

    <section class="repo-card repo-help-chapter" id="persiapan">
      <p class="repo-eyebrow">Bab 6</p><h2>Persiapan sebelum membuat deposit</h2>
      <p>Deposit yang baik dimulai sebelum formulir dibuka. Siapkan dokumen final yang telah disetujui sesuai prosedur akademik, halaman judul, abstrak Indonesia dan Inggris bila diwajibkan, kata kunci, daftar penulis, pembimbing, penguji, program studi, tahun, serta informasi penerbitan. Pastikan versi berkas yang akan dikirim sama dengan versi yang menjadi dasar kelulusan atau publikasi. Beri nama berkas secara jelas dan hindari “final-baru-revisi-terakhir” yang membingungkan.</p>
      <p>Periksa hak cipta dan materi pihak ketiga. Gambar, tabel, peta, instrumen, artikel terbit, atau data dari pihak lain mungkin mempunyai izin tersendiri. Tentukan apakah versi yang boleh disimpan adalah versi penerbit, manuskrip diterima, atau naskah penulis. Untuk data penelitian, lakukan anonimisasi dan pisahkan data yang tidak boleh dibuka. Repository bukan tempat mengunggah data sensitif hanya karena lampiran diperlukan dalam ujian.</p>
      <p>Periksa kualitas PDF: dapat dibuka, teks dapat dipilih bila memungkinkan, halaman berurutan, orientasi benar, tidak dilindungi kata sandi, dan tidak mengandung komentar atau perubahan terlacak yang tidak dimaksudkan. Terapkan watermark hanya sesuai ketentuan institusi. Kompres gambar secara wajar tanpa membuat tulisan tidak terbaca. Siapkan lampiran terpisah dengan nama dan deskripsi yang menjelaskan isinya.</p>
      <h3>Checklist kesiapan</h3>
      <ul class="repo-help-checklist"><li>Dokumen final telah disahkan.</li><li>Judul dan nama penulis sama pada dokumen serta formulir.</li><li>Abstrak dan kata kunci telah diperiksa.</li><li>Program studi, pembimbing, penguji, dan tahun tersedia.</li><li>PDF dapat dibuka dan tidak memakai kata sandi.</li><li>Data pribadi yang tidak perlu telah dihapus atau dianonimkan.</li><li>Izin materi pihak ketiga telah diperiksa.</li><li>Lisensi dan kebutuhan embargo telah didiskusikan.</li><li>Semua lampiran diberi nama jelas.</li><li>Koneksi stabil dan tersedia waktu untuk melakukan pratinjau.</li></ul>
      <p>Jangan membuat beberapa deposit untuk karya yang sama ketika belum yakin. Buat satu draf, simpan, dan lanjutkan. Jika karya pernah terbit di Repository, cari berdasarkan judul, penulis, dan identifier terlebih dahulu. Duplikasi memecah statistik, profil penulis, sitasi, dan riwayat versi.</p>
    </section>

    <section class="repo-card repo-help-chapter" id="upload">
      <p class="repo-eyebrow">Bab 7</p><h2>Sembilan tahap mengunggah karya ilmiah</h2>
      <div class="repo-help-diagram repo-help-workflow" role="img" aria-label="Alur sembilan tahap deposit dari login sampai review">
        <div class="repo-help-node"><b>1. Masuk</b></div><i>→</i><div class="repo-help-node"><b>2. Jenis & koleksi</b></div><i>→</i><div class="repo-help-node"><b>3. Informasi utama</b></div><i>→</i><div class="repo-help-node"><b>4. Data akademik</b></div><i>→</i><div class="repo-help-node"><b>5. Berkas</b></div><i>→</i><div class="repo-help-node"><b>6. Akses</b></div><i>→</i><div class="repo-help-node"><b>7. Relasi</b></div><i>→</i><div class="repo-help-node"><b>8. Pratinjau</b></div><i>→</i><div class="repo-help-node"><b>9. Kirim</b></div>
      </div>
      <h3>1. Masuk dan buka Karya Saya</h3><p>Gunakan akun eCampus pribadi, buka workspace Repository, lalu pilih Karya Saya. Periksa apakah draf untuk karya tersebut sudah ada. Lanjutkan draf lama jika judul, penulis, dan dokumennya sama. Tombol deposit baru hanya digunakan untuk karya berbeda. Jika koleksi deposit tidak tersedia, jangan memilih koleksi sembarang; tanyakan kepada pengelola.</p>
      <h3>2. Pilih jenis dokumen dan koleksi</h3><p>Jenis dokumen menjelaskan bentuk akademik, misalnya skripsi, tesis, disertasi, artikel, laporan, buku, atau dataset. Koleksi menjelaskan wadah tata kelola dan unit pemilik. Pilihan yang salah memengaruhi field wajib, reviewer, kebijakan akses, serta statistik. Baca deskripsi koleksi dan pilih yang sesuai program atau kegiatan.</p>
      <h3>3. Lengkapi informasi utama</h3><p>Salin judul dari halaman judul final. Masukkan judul alternatif hanya jika benar-benar ada. Tulis abstrak lengkap tanpa format dekoratif, lalu tambahkan kata kunci satu per satu dengan istilah yang bermakna. Pilih bahasa utama dan tahun yang merepresentasikan penerbitan atau pengesahan sesuai kebijakan.</p>
      <h3>4. Lengkapi data akademik dan kontributor</h3><p>Masukkan nama penulis tanpa gelar kecuali pedoman menyatakan lain. Pertahankan urutan kontributor. Tambahkan pembimbing, penguji, afiliasi, program studi, fakultas, dan unit sebagaimana dokumen resmi. Jangan menggabungkan beberapa orang dalam satu field bila formulir menyediakan baris terpisah.</p>
      <h3>5. Unggah berkas</h3><p>Pilih PDF utama, tunggu progres selesai, dan pastikan status berhasil. Tambahkan lampiran dengan deskripsi. Sistem dapat memeriksa tipe, ukuran, checksum, virus, atau kebutuhan watermark. Kegagalan pemeriksaan harus diselesaikan sebelum melanjutkan; mengganti ekstensi tidak mengubah format berkas sebenarnya.</p>
      <h3>6. Tentukan akses, lisensi, dan embargo</h3><p>Pilih kebijakan berdasarkan hak yang benar, bukan berdasarkan keinginan memperoleh banyak unduhan. Jika ada embargo, masukkan tanggal berakhir dan alasan sesuai prosedur. Pilih lisensi hanya jika penulis atau pemegang hak berwenang memberikannya. Metadata umumnya tetap dapat ditemukan walaupun berkas ditunda.</p>
      <h3>7. Tambahkan relasi dan identifier</h3><p>Hubungkan versi, dataset, artikel terkait, proyek, atau identifier eksternal bila tersedia. Masukkan DOI atau Handle persis, tanpa membuat nilai baru. Relasi membantu pembaca memahami bahwa beberapa record merupakan bagian dari keluaran yang sama, bukan duplikasi.</p>
      <h3>8. Periksa pratinjau</h3><p>Baca pratinjau seperti pembaca publik. Periksa judul, nama, abstrak, kata kunci, tahun, koleksi, akses, dan setiap nama berkas. Buka PDF bila tersedia. Kembali ke tahap terkait untuk memperbaiki kesalahan; jangan mengandalkan reviewer untuk menemukan semua kesalahan depositor.</p>
      <h3>9. Kirim untuk review</h3><p>Tambahkan catatan singkat jika ada keadaan khusus, lalu kirim sekali. Setelah dikirim, status berubah dan sebagian field dapat terkunci. Pantau notifikasi serta riwayat. Jika reviewer meminta revisi, gunakan pengajuan yang sama. Jika tombol kirim tidak aktif, cari indikator tahap yang belum lengkap dan field wajib yang belum diisi.</p>
      <div class="repo-paper-actions"><%if(publicUser==null){%><a class="repo-btn repo-btn-primary" href="<%=root%>/login2">Login eCampus</a><%}else if(canDeposit){%><a class="repo-btn repo-btn-primary" href="<%=root%>/repository-workspace?view=deposit">Buka Karya Saya</a><%}%><a class="repo-btn" href="<%=root%>/repository/policies#submission">Kebijakan pengajuan</a></div>
    </section>

    <section class="repo-card repo-help-chapter" id="metadata">
      <p class="repo-eyebrow">Bab 8</p><h2>Standar pengisian metadata yang konsisten</h2>
      <p>Metadata menentukan apakah karya dapat ditemukan dan dipahami tanpa membuka berkas. Gunakan sumber utama: halaman judul, lembar pengesahan, informasi penerbit, dan identifier resmi. Jangan menyalin metadata dari situs lain tanpa pemeriksaan karena ejaan, tahun, atau urutan penulis dapat berbeda. Isilah setiap field dengan satu jenis informasi sesuai label; jangan memasukkan catatan pribadi ke judul atau abstrak.</p>
      <h3>Judul</h3><p>Pertahankan kata, urutan, dan bahasa dari dokumen final. Gunakan kapitalisasi wajar, bukan seluruh huruf besar kecuali singkatan. Jangan menambahkan tipe dokumen, nama file, atau status “revisi” ke judul. Judul terjemahan masuk ke field alternatif bila tersedia.</p>
      <h3>Nama dan authority penulis</h3><p>Tulis nama secara konsisten tanpa gelar. Pilih authority yang sudah ada jika benar-benar orang yang sama. ORCID harus diverifikasi dan tidak boleh dipinjam. Variasi nama dapat dicatat agar pencarian menyatukan karya, sedangkan afiliasi menjelaskan hubungan institusi pada saat karya dibuat.</p>
      <h3>Abstrak dan kata kunci</h3><p>Abstrak sebaiknya menjelaskan latar belakang, tujuan, metode, objek, hasil, dan kesimpulan secara ringkas. Jangan hanya menyalin pendahuluan atau daftar isi. Hindari informasi sensitif. Kata kunci menggunakan istilah khusus yang mewakili topik, metode, populasi, atau lokasi; jangan mengulang semua kata dalam judul dan jangan memakai kalimat panjang.</p>
      <h3>Tanggal, tahun, dan bahasa</h3><p>Gunakan tanggal sesuai arti field: tanggal terbit, pengesahan, submit, atau tersedia. Tahun tidak selalu sama dengan waktu record dimasukkan. Pilih bahasa isi utama, bukan bahasa judul terjemahan. Untuk karya multibahasa, ikuti ketentuan koleksi.</p>
      <h3>Identifier dan relasi</h3><p>DOI, Handle, ISBN, ISSN, nomor laporan, dan identifier lokal memiliki fungsi berbeda. Salin persis dan hindari spasi tambahan. Jangan mengganti identifier record lama. Gunakan relasi untuk menghubungkan artikel dengan dataset, versi awal dengan versi baru, atau bagian dengan keseluruhan.</p>
      <table class="repo-help-table"><thead><tr><th>Field</th><th>Sumber yang dianjurkan</th><th>Kesalahan umum</th></tr></thead><tbody><tr><td>Judul</td><td>Halaman judul final</td><td>Huruf besar semua, tambahan status, salah versi</td></tr><tr><td>Penulis</td><td>Halaman judul/publikasi</td><td>Gelar masuk nama, urutan berubah, dua orang satu field</td></tr><tr><td>Abstrak</td><td>Abstrak final</td><td>Terpotong, format rusak, data sensitif</td></tr><tr><td>Kata kunci</td><td>Kata kunci penulis/istilah bidang</td><td>Terlalu umum, berupa kalimat, duplikat</td></tr><tr><td>Tahun</td><td>Pengesahan atau penerbitan</td><td>Memakai tahun unggah tanpa alasan</td></tr><tr><td>Identifier</td><td>Layanan penerbit resmi</td><td>Membuat DOI sendiri atau menyalin URL salah</td></tr></tbody></table>
      <p>Sebelum mengirim, bandingkan pratinjau dengan dokumen. Kesalahan metadata dapat menyebar ke sitasi, profil penulis, mesin pencari, OAI-PMH, dan layanan eksternal. Koreksi setelah publikasi mungkin memerlukan waktu sinkronisasi, sehingga ketelitian pada awal proses lebih efisien.</p>
    </section>

    <section class="repo-card repo-help-chapter" id="berkas">
      <p class="repo-eyebrow">Bab 9</p><h2>Berkas, checksum, watermark, lisensi, dan embargo</h2>
      <p>Berkas utama harus mewakili karya final. Format PDF dianjurkan untuk dokumen karena mempertahankan tata letak, tetapi file tetap harus dapat dibaca, dicari, dan diakses. Dataset, audio, video, gambar, atau kode dapat memakai format lain sesuai profil koleksi. Nama file sebaiknya singkat, deskriptif, tanpa karakter kontrol, dan membedakan naskah utama dari lampiran.</p>
      <p>Checksum adalah sidik digital yang membantu mendeteksi perubahan bit. Nilai checksum yang berubah tidak selalu berarti pelanggaran, karena penggantian berkas yang sah juga menghasilkan nilai baru; yang penting perubahan mengikuti proses dan riwayat. Pemeriksaan fixity membandingkan checksum tersimpan dengan checksum terkini. Pengguna tidak perlu menghitung manual kecuali diminta, tetapi harus melaporkan jika berkas tampak rusak atau tidak lengkap.</p>
      <p>Watermark memberi penanda asal atau ketentuan penggunaan, bukan pengganti hak cipta. Jangan menambahkan watermark yang menutupi teks, gambar, tanda tangan, atau informasi penting. Gunakan versi dan posisi sesuai kebijakan. PDF yang dilindungi kata sandi menghambat pemeriksaan, preservasi, dan aksesibilitas sehingga biasanya perlu dibuka perlindungannya sebelum deposit.</p>
      <p>Lisensi menjelaskan izin penggunaan. Open Access tidak selalu berarti bebas untuk semua tujuan. Pembaca harus mengikuti atribusi, pembatasan perubahan, penggunaan nonkomersial, atau ketentuan lain yang tercantum. Depositor hanya boleh memilih lisensi bila mempunyai kewenangan. Untuk artikel terbit, periksa perjanjian penerbit mengenai versi yang dapat disimpan dan masa embargo.</p>
      <p>Embargo menunda pembukaan berkas sampai tanggal tertentu, sedangkan metadata dapat tetap publik. Pilih tanggal berdasarkan surat, kontrak, kebijakan, atau persetujuan yang dapat dibuktikan. Jangan menggunakan embargo untuk menyembunyikan kesalahan metadata. Ketika embargo berakhir, sistem dapat membuka akses menurut kebijakan; depositor tetap perlu memastikan bahwa tanggal dan status awal benar.</p>
      <h3>Pemisahan berkas</h3><p>Jika lampiran memiliki tingkat akses berbeda, unggah sebagai berkas terpisah dan beri deskripsi. Misalnya naskah utama dapat dibuka, sedangkan data mentah terbatas karena privasi. Jangan menyatukan data pribadi dengan PDF publik. Untuk dataset, sertakan README, definisi variabel, metode, format, versi perangkat lunak, lisensi, dan kontak yang sesuai.</p>
    </section>

    <section class="repo-card repo-help-chapter" id="review">
      <p class="repo-eyebrow">Bab 10</p><h2>Review, revisi, keputusan, dan komunikasi</h2>
      <p>Review Repository memeriksa kesiapan record untuk dikelola dan dipublikasikan. Pemeriksaan dapat meliputi kesesuaian koleksi, kelengkapan field, konsistensi dengan dokumen, kejelasan abstrak, authority penulis, duplikasi, kualitas berkas, keamanan, watermark, lisensi, embargo, serta hak akses. Review Repository bukan pengganti penilaian akademik, ujian, penyuntingan jurnal, atau pemeriksaan plagiarisme kecuali kebijakan menyatakan demikian.</p>
      <div class="repo-help-diagram" role="img" aria-label="Siklus review deposit">
        <div class="repo-help-node"><b>Draf</b><span>Depositor melengkapi</span></div><i>→</i><div class="repo-help-node"><b>Dikirim</b><span>Masuk antrean</span></div><i>→</i><div class="repo-help-node"><b>Diperiksa</b><span>Metadata, berkas, hak</span></div><i>→</i><div class="repo-help-node"><b>Keputusan</b><span>Revisi, tolak, atau setujui</span></div>
      </div>
      <p>Status menunggu berarti pengajuan berada dalam antrean. Status diperiksa berarti reviewer sedang bekerja atau telah membuka pengajuan. Permintaan revisi mengembalikan karya kepada depositor dengan catatan. Penolakan digunakan bila karya tidak memenuhi ruang lingkup atau persyaratan yang tidak dapat diselesaikan melalui revisi biasa. Persetujuan berarti record lolos tahap review, tetapi tampil publik dapat menunggu transaksi, sinkronisasi indeks, atau aturan waktu.</p>
      <h3>Menanggapi revisi</h3><p>Baca semua catatan sebelum mengubah. Buat daftar: field atau berkas yang diminta, alasan, perubahan, dan bukti. Perbaiki pada pengajuan yang sama. Jangan menghapus catatan reviewer atau membuat deposit duplikat. Tulis balasan singkat seperti “Judul disamakan dengan halaman judul; PDF utama diganti versi pengesahan; embargo dipertahankan sampai tanggal yang tercantum pada surat.” Setelah pratinjau, kirim ulang sekali.</p>
      <p>Jika dua catatan tampak bertentangan, jangan memilih secara acak. Minta klarifikasi dengan menyebut nomor pengajuan dan kedua bagian catatan. Jika proses melebihi waktu layanan, tanyakan status secara sopan tanpa mengirim pengajuan berulang. Reviewer sebaiknya menulis catatan yang spesifik, dapat ditindaklanjuti, dan tidak memuat data sensitif.</p>
      <h3>Jejak audit</h3><p>Riwayat status membantu menjelaskan siapa melakukan tindakan, kapan, dan mengapa. Karena itu keputusan tidak boleh dipindahkan ke percakapan pribadi saja. Catatan penting perlu direkam melalui mekanisme resmi. Jejak audit melindungi depositor, reviewer, institusi, dan pembaca ketika terjadi koreksi atau sengketa.</p>
    </section>

    <section class="repo-card repo-help-chapter" id="publikasi">
      <p class="repo-eyebrow">Bab 11</p><h2>Sesudah publikasi: visibilitas, koreksi, versi, dan penarikan</h2>
      <p>Setelah disetujui, record memperoleh status publik sesuai kebijakan. Metadata dapat muncul pada beranda, koleksi, hasil pencarian, profil penulis, feed, sitemap, atau OAI-PMH. Tidak semua kanal diperbarui pada detik yang sama. Gunakan halaman detail sebagai rujukan utama dan tunggu proses indeks normal sebelum menyatakan record hilang. Jika record dapat dibuka melalui URL tetapi tidak muncul dalam pencarian, laporkan sebagai masalah indeks.</p>
      <p>Koreksi kecil seperti salah ketik dapat dilakukan administrator melalui proses tercatat. Perubahan penulis, judul substantif, berkas, lisensi, atau hasil ilmiah memerlukan pemeriksaan lebih ketat. Jangan menimpa karya terbit tanpa menjaga provenance. Versi baru digunakan ketika perubahan penting perlu dibedakan tetapi relasi dengan versi lama harus tetap jelas. Halaman detail dapat menunjukkan nomor versi dan karya yang menggantikan.</p>
      <p>Record duplikat harus ditangani dengan memilih record otoritatif, memeriksa identifier, penggunaan, sitasi, berkas, dan riwayat. Menghapus salah satu secara diam-diam dapat memutus tautan. Administrator dapat menggabungkan relasi, mengarahkan pembaca, atau mempertahankan tombstone sesuai kebijakan. Depositor cukup melaporkan kedua URL dan menjelaskan mana yang benar.</p>
      <p>Penarikan dilakukan untuk alasan seperti pelanggaran hak, data sensitif, masalah integritas, permintaan resmi, atau ketidaksesuaian berat. Penarikan bukan penghapusan tanpa jejak. Tombstone mempertahankan identifier minimum, status, dan kadang alasan yang layak dipublikasikan. Berkas tidak lagi tersedia sesuai keputusan. Permintaan penarikan harus menyertakan identitas pemohon, URL, alasan, bukti kewenangan, serta tingkat urgensi.</p>
      <h3>Pemeriksaan pascapublikasi</h3><ol><li>Buka record dari URL permanen.</li><li>Periksa judul, penulis, tahun, abstrak, koleksi, dan akses.</li><li>Uji berkas sesuai hak pengguna.</li><li>Periksa profil penulis dan relasi versi.</li><li>Salin sitasi dan pastikan field utamanya benar.</li><li>Simpan identifier untuk komunikasi berikutnya.</li></ol>
    </section>

    <section class="repo-card repo-help-chapter" id="sitasi">
      <p class="repo-eyebrow">Bab 12</p><h2>Sitasi, DOI, Handle, identifier OAI, dan ekspor</h2>
      <p>Sitasi mengakui sumber dan membantu pembaca menemukan karya. Gunakan informasi dari halaman detail, bukan hanya nama file. Elemen minimum biasanya penulis, tahun, judul, jenis atau sumber, institusi/penerbit, dan identifier. Gaya APA, MLA, Chicago, atau pedoman lokal dapat mengatur urutan serta tanda baca berbeda. Generator sitasi adalah bantuan; pengguna tetap harus memeriksa kapitalisasi, urutan penulis, tahun, dan kelengkapan.</p>
      <p>DOI adalah identifier yang dikelola melalui lembaga registrasi dan harus mengarah ke landing page yang memuat metadata serta akses. Handle juga menyediakan rujukan persisten. Identifier OAI digunakan untuk pertukaran metadata melalui OAI-PMH dan tidak selalu sama dengan URL publik. Identifier lokal mengenali record di dalam sistem. Jangan membuat DOI sendiri, mengganti identifier lama, atau menganggap semua string URL sebagai identifier permanen.</p>
      <p>Ekspor RIS, BibTeX, EndNote, atau CSL-JSON memindahkan metadata ke pengelola referensi. Setelah impor, buka satu record dan periksa mapping jenis dokumen, penulis, tahun, judul, serta URL. Jika metadata sumber salah, ekspor juga salah. Laporkan koreksi ke Repository dan perbaiki sementara di pustaka pribadi bila tenggat penulisan mendesak.</p>
      <h3>Contoh proses sitasi yang aman</h3><ol><li>Buka halaman detail versi yang benar.</li><li>Catat penulis, tahun, judul, dan tipe.</li><li>Pilih DOI; jika tidak ada, gunakan Handle atau URL permanen yang disediakan.</li><li>Ekspor format yang didukung pengelola referensi.</li><li>Bandingkan hasil impor dengan halaman detail.</li><li>Sesuaikan gaya menurut pedoman tujuan.</li><li>Saat mengutip isi, periksa nomor halaman pada naskah asli.</li></ol>
      <p>Jika identifier tidak dapat dibuka, coba salin nilainya tanpa tanda baca akhir. Periksa apakah DOI sudah didaftarkan atau record baru diterbitkan. Jangan mengganti DOI pada daftar pustaka dengan alamat file langsung. Laporkan nilai identifier, URL record, waktu, dan hasil resolusi kepada pengelola.</p>
    </section>

    <section class="repo-card repo-help-chapter" id="integrasi">
      <p class="repo-eyebrow">Bab 13</p><h2>Bookmark, alert, RSS, Atom, OAI-PMH, dan integrasi</h2>
      <p>Bookmark membantu pengguna login menyimpan record untuk dibaca lagi. Bookmark tidak mengubah akses, tidak mengunduh berkas, dan bukan daftar sitasi otomatis. Pencarian tersimpan mempertahankan parameter pencarian. Alert menggunakan parameter tersebut untuk memberi tahu perubahan atau publikasi baru sesuai konfigurasi. Beri nama yang jelas, periksa filter, dan hapus alert yang tidak lagi relevan agar notifikasi tetap berguna.</p>
      <p>RSS dan Atom menyediakan daftar publikasi terbaru untuk pembaca feed. Feed penulis dapat mengikuti karya yang dikaitkan dengan authority penulis. Karena feed berfokus pada pembaruan, gunakan halaman detail untuk metadata lengkap. Jika feed kosong, periksa alamat, format, dan apakah ada record publik dalam cakupan.</p>
      <p>OAI-PMH ditujukan untuk pemanen metadata oleh perpustakaan, agregator, atau sistem penemuan. Verb seperti Identify, ListSets, ListIdentifiers, ListRecords, dan GetRecord memiliki argumen tertentu. Resumption token digunakan untuk halaman lanjutan dan tidak boleh diubah. OAI-PMH bukan API untuk mengunduh massal naskah lengkap. Integrasi harus mengikuti kebijakan, kapasitas layanan, tenant, serta lisensi metadata.</p>
      <p>Sebelum meminta integrasi, jelaskan tujuan, pemilik sistem, field yang dibutuhkan, format, volume, frekuensi, autentikasi, masa retensi, dan kontak teknis. Hindari scraping antarmuka manusia bila endpoint resmi tersedia. Integrator harus mempertahankan identifier, menangani record yang diperbarui atau ditarik, membatasi retry, dan mencatat provenance. Pengelola dapat menetapkan rate limit atau jadwal agar layanan publik tetap stabil.</p>
      <div class="repo-help-callout"><strong>Pilih kanal yang tepat</strong><p>Gunakan bookmark untuk daftar pribadi, pencarian tersimpan untuk mengulang filter, alert untuk pemberitahuan, RSS/Atom untuk pembaruan ringan, OAI-PMH untuk metadata terstruktur, dan ekspor RIS/BibTeX untuk referensi individual.</p></div>
    </section>

    <section class="repo-card repo-help-chapter" id="privasi">
      <p class="repo-eyebrow">Bab 14</p><h2>Privasi, keamanan informasi, dan aksesibilitas</h2>
      <p>Repository mempublikasikan karya, tetapi tidak berarti semua data di dalamnya layak dibuka. Depositor harus menghapus atau menyamarkan nomor identitas, alamat pribadi, tanda tangan yang tidak diperlukan, data kesehatan, kredensial, data responden, serta informasi lain yang dapat merugikan subjek. Persetujuan penelitian dan izin distribusi perlu diperiksa sebelum unggah. Jika data sensitif terlanjur terbit, jangan menyebarkan tautannya; segera laporkan dengan prioritas tinggi.</p>
      <p>Data akun, komentar review, dan catatan internal tidak menjadi metadata publik. Aktivitas penting dapat dicatat untuk keamanan, audit, dan statistik sesuai kebijakan. Pengguna tidak boleh mencoba melihat data milik orang lain, membagikan tautan internal, atau menguji kelemahan tanpa izin. Laporan keamanan harus menjelaskan dampak dan langkah reproduksi minimal tanpa mengeksploitasi lebih lanjut.</p>
      <p>Antarmuka dirancang untuk papan ketik, fokus terlihat, label, heading, dan tampilan responsif. Gunakan Tab untuk berpindah, Enter atau Space untuk mengaktifkan kontrol, dan heading untuk menavigasi dengan pembaca layar. Perbesar halaman melalui fungsi zoom peramban. Jika dialog, filter, atau menu tidak dapat dicapai, catat elemen dan urutan langkah.</p>
      <p>Aksesibilitas dokumen merupakan tanggung jawab bersama. PDF sebaiknya mempunyai teks yang dapat dipilih, tag, bahasa, urutan baca, heading, tabel yang benar, dan teks alternatif untuk gambar bermakna. Dokumen hasil pindai memerlukan OCR, tetapi hasil OCR harus diperiksa. Audio memerlukan transkrip; video memerlukan takarir; grafik perlu uraian. Jangan mengandalkan warna saja untuk menyampaikan status.</p>
      <h3>Melaporkan hambatan aksesibilitas</h3><p>Sertakan URL, judul halaman atau dokumen, perangkat, peramban, teknologi bantu, langkah, hasil yang diharapkan, dan hambatan yang terjadi. Jangan hanya menulis “tidak bisa diakses”. Pengelola dapat menawarkan format alternatif sambil memperbaiki sumber, tetapi isi akademik serta hak akses tetap harus dijaga.</p>
    </section>

    <section class="repo-card repo-help-chapter" id="troubleshooting">
      <p class="repo-eyebrow">Bab 15</p><h2>Pemecahan masalah secara sistematis</h2>
      <p>Jangan langsung mengulang tindakan berkali-kali. Pertama, tentukan ruang masalah: satu record atau semua record; satu akun atau semua pengguna; satu perangkat atau beberapa perangkat; satu jaringan atau jaringan lain; metadata atau berkas; tampilan atau operasi simpan. Pembatasan ruang ini mengubah laporan umum menjadi bukti yang dapat ditindaklanjuti.</p>
      <div class="repo-help-diagram repo-help-diagram-stack" role="img" aria-label="Tangga pemecahan masalah Repository">
        <div class="repo-help-node"><b>1. Amankan pekerjaan</b><span>Simpan draf dan salin teks penting</span></div><i>↓</i><div class="repo-help-node"><b>2. Baca pesan</b><span>Catat kode, waktu, dan URL</span></div><i>↓</i><div class="repo-help-node"><b>3. Coba satu kali</b><span>Muat ulang atau login kembali bila aman</span></div><i>↓</i><div class="repo-help-node"><b>4. Bandingkan</b><span>Peramban, perangkat, record, atau jaringan lain</span></div><i>↓</i><div class="repo-help-node"><b>5. Eskalasi</b><span>Kirim bukti tanpa data sensitif</span></div>
      </div>
      <h3>Halaman kosong atau sangat lambat</h3><p>Tunggu proses awal, lalu muat ulang satu kali. Periksa apakah halaman lain dapat dibuka. Matikan ekstensi yang mengubah halaman hanya untuk pengujian yang aman, atau gunakan profil peramban bersih. Catat waktu agar log server dapat dicocokkan. Jangan terus menekan tombol kirim ketika indikator masih berjalan.</p>
      <h3>Pesan 403, 404, atau 500</h3><p>403 berarti akses ditolak: periksa login dan peran. 404 berarti route, record, atau berkas tidak ditemukan: periksa URL dan apakah record ditarik. 500 berarti server gagal memproses permintaan: simpan bukti dan coba lagi setelah jeda sesuai arahan pengelola. Kode tidak selalu menunjukkan sebab akhir, tetapi sangat membantu diagnosis.</p>
      <h3>Formulir gagal disimpan</h3><p>Cari field wajib, format tanggal, panjang teks, karakter tidak lazim, atau sesi kedaluwarsa. Salin teks panjang ke tempat aman sebelum memuat ulang. Jika satu field memicu kegagalan, catat label dan contoh nilai yang tidak sensitif. Jangan membuat deposit baru sebelum memastikan draf lama tidak tersimpan.</p>
      <h3>Unggahan gagal</h3><p>Periksa format nyata, ukuran, nama file, proteksi kata sandi, koneksi, dan hasil pemindaian keamanan. Coba berkas yang sama sekali lagi setelah sesi stabil, bukan berulang tanpa batas. Bila berkas besar, ikuti kanal khusus yang diberikan institusi. Jangan mengompres hingga isi rusak atau mengganti ekstensi untuk melewati validasi.</p>
      <h3>Record tidak ditemukan</h3><p>Cari potongan judul, variasi nama, koleksi, dan identifier. Hapus filter. Jika URL langsung bekerja tetapi pencarian tidak, laporkan indeks. Jika record baru, berikan waktu sinkronisasi. Jika terbit dua kali, kirim kedua URL; jangan mengunduh lalu mengunggah ulang.</p>
      <table class="repo-help-table"><thead><tr><th>Gejala</th><th>Periksa dahulu</th><th>Bukti untuk bantuan</th></tr></thead><tbody><tr><td>Login berulang</td><td>Sesi, cookie, akun</td><td>Waktu, URL, peramban</td></tr><tr><td>Simpan gagal</td><td>Field wajib, sesi, panjang nilai</td><td>Tahap, label field, pesan</td></tr><tr><td>Unggah berhenti</td><td>Ukuran, format, koneksi</td><td>Nama, tipe, ukuran, persentase</td></tr><tr><td>Unduh ditolak</td><td>Badge akses, login, embargo</td><td>Identifier, akun/peran tanpa sandi</td></tr><tr><td>Metadata salah</td><td>Sumber resmi dan versi</td><td>URL, field, nilai benar, bukti</td></tr></tbody></table>
    </section>

    <section class="repo-card repo-help-chapter" id="dukungan">
      <p class="repo-eyebrow">Bab 16</p><h2>Meminta bantuan dan membuat laporan yang dapat ditindaklanjuti</h2>
      <p>Laporan yang baik menjawab siapa mengalami masalah, apa yang dilakukan, di halaman mana, kapan, hasil apa yang diharapkan, hasil apa yang terjadi, dan apakah dapat diulang. Gunakan judul singkat, misalnya “Upload PDF berhenti pada 80% di tahap berkas” atau “Record disetujui tidak muncul dalam pencarian”. Hindari judul “error” tanpa konteks.</p>
      <p>Sertakan URL lengkap, identifier, nomor pengajuan bila ada, waktu dengan zona, peran pengguna, peramban, perangkat, langkah bernomor, pesan galat persis, serta tangkapan layar yang sudah menyamarkan data pribadi. Untuk metadata, sebut field, nilai tampil, nilai yang benar, dan sumber resmi. Untuk akses, sebut badge dan apakah sudah login. Untuk berkas, sebut nama, format, ukuran, tetapi jangan mengirim dokumen sensitif lewat kanal yang tidak disetujui.</p>
      <h3>Tingkat urgensi</h3><p>Darurat mencakup kebocoran data, akses tanpa izin, malware, atau publikasi materi yang membahayakan; hentikan penyebaran dan laporkan segera. Tinggi mencakup kegagalan layanan luas atau tenggat resmi yang terancam. Normal mencakup satu pengajuan, koreksi metadata, atau pertanyaan prosedur. Permintaan pengembangan dapat dicatat terpisah agar tidak bercampur dengan insiden.</p>
      <h3>Setelah melapor</h3><p>Simpan nomor tiket atau salinan komunikasi. Jangan membuka banyak laporan untuk masalah sama; tambahkan bukti pada laporan awal. Jawab permintaan klarifikasi dengan data yang diminta. Setelah solusi diberikan, uji langkah yang relevan dan konfirmasikan hasil. Solusi sementara perlu dibedakan dari perbaikan permanen.</p>
      <div class="repo-help-callout"><strong>Template laporan</strong><p><b>Judul:</b> [fitur] gejala singkat. <b>URL/identifier:</b> …. <b>Waktu:</b> …. <b>Akun/peran:</b> tanpa kata sandi. <b>Langkah:</b> 1…, 2…, 3…. <b>Diharapkan:</b> …. <b>Terjadi:</b> …. <b>Pesan:</b> …. <b>Lampiran:</b> tangkapan layar yang sudah disamarkan.</p></div>
      <h3>Kontak pengelola Repository</h3><dl class="repo-contact-list"><%if(institutionEmail.length()>0){%><dt>Email</dt><dd><a href="mailto:<%=rh(institutionEmail)%>"><%=rh(institutionEmail)%></a></dd><%}if(institutionPhone.length()>0){%><dt>Telepon</dt><dd><%=rh(institutionPhone)%></dd><%}if(institutionAddress.length()>0){%><dt>Alamat</dt><dd><%=rh(institutionAddress)%></dd><%}%></dl>
      <div class="repo-paper-actions"><a class="repo-btn repo-btn-primary" href="<%=root%>/repository/ask#repository-faq">Cari tanya jawab</a><a class="repo-btn" href="<%=root%>/repository/policies">Baca kebijakan</a></div>
    </section>

    <section class="repo-card repo-help-chapter" id="glosarium">
      <p class="repo-eyebrow">Bab 17</p><h2>Glosarium istilah Repository</h2>
      <dl class="repo-help-glossary">
        <dt>Abstrak</dt><dd>Ringkasan terstruktur mengenai latar belakang, tujuan, metode, hasil, dan kesimpulan karya.</dd><dt>Afiliasi</dt><dd>Institusi atau unit tempat penulis terhubung ketika karya dibuat atau diterbitkan.</dd>
        <dt>Alert</dt><dd>Pemberitahuan berdasarkan pencarian tersimpan atau perubahan tertentu.</dd><dt>Authority penulis</dt><dd>Identitas terkelola yang menyatukan variasi nama seorang penulis dan membedakannya dari orang lain.</dd>
        <dt>Bitstream</dt><dd>Satu objek berkas digital yang terhubung dengan record, misalnya PDF utama atau lampiran.</dd><dt>Checksum</dt><dd>Nilai sidik digital untuk memeriksa apakah bit berkas berubah.</dd>
        <dt>Deposit</dt><dd>Proses menyerahkan metadata dan berkas ke Repository untuk diperiksa dan dikelola.</dd><dt>Depositor</dt><dd>Pengguna berwenang yang membuat, melengkapi, dan menanggapi revisi pengajuan.</dd>
        <dt>DOI</dt><dd>Digital Object Identifier yang dikelola melalui layanan registrasi untuk rujukan persisten.</dd><dt>Embargo</dt><dd>Penundaan akses berkas sampai tanggal atau kondisi yang ditentukan.</dd>
        <dt>Fixity</dt><dd>Proses memeriksa integritas berkas dengan membandingkan checksum.</dd><dt>Handle</dt><dd>Identifier persisten yang mengarahkan pengguna ke landing page sebuah objek.</dd>
        <dt>Identifier OAI</dt><dd>Identifier record pada protokol OAI-PMH untuk pertukaran metadata.</dd><dt>Koleksi</dt><dd>Wadah tata kelola yang mengelompokkan record berdasarkan unit, program, atau profil konten.</dd>
        <dt>Lisensi</dt><dd>Pernyataan izin dan batas penggunaan karya atau data.</dd><dt>Metadata</dt><dd>Data terstruktur yang menjelaskan judul, penulis, abstrak, subjek, tanggal, akses, dan hubungan karya.</dd>
        <dt>OAI-PMH</dt><dd>Protokol pemanenan metadata yang memungkinkan agregator mengambil record terstruktur.</dd><dt>Open Access</dt><dd>Akses terbuka terhadap objek tertentu dengan tetap mengikuti hak cipta dan lisensi.</dd>
        <dt>ORCID</dt><dd>Identifier peneliti global yang membantu membedakan identitas penulis.</dd><dt>Preservasi</dt><dd>Upaya menjaga integritas, keterbacaan, provenance, dan keberlanjutan objek digital.</dd>
        <dt>Provenance</dt><dd>Riwayat asal, kepemilikan, dan perubahan suatu record atau berkas.</dd><dt>Record</dt><dd>Satu entri Repository yang terdiri atas metadata, kebijakan, relasi, dan mungkin berkas.</dd>
        <dt>Reviewer</dt><dd>Pengguna yang memeriksa pengajuan dan memberi keputusan sesuai kewenangan koleksi.</dd><dt>ROR</dt><dd>Research Organization Registry identifier untuk membedakan institusi secara global.</dd>
        <dt>Takedown</dt><dd>Proses membatasi atau menarik materi setelah laporan dan pemeriksaan.</dd><dt>Tombstone</dt><dd>Metadata minimum yang dipertahankan ketika record ditarik agar identifier dan jejak ilmiah tidak hilang.</dd>
        <dt>Versi</dt><dd>Keadaan karya yang berbeda dan tetap dihubungkan agar pembaca mengetahui urutan serta penggantinya.</dd><dt>Watermark</dt><dd>Penanda visual atau digital pada dokumen yang menunjukkan asal atau ketentuan penggunaan.</dd>
      </dl>
      <p>Jika istilah yang dicari belum tercantum, gunakan katalog 300 tanya jawab atau hubungi pengelola dengan menyebut halaman tempat istilah tersebut muncul. Makna operasional selalu mengikuti kebijakan institusi dan konteks field, sehingga glosarium ini menjadi panduan penggunaan, bukan pengganti dokumen kebijakan resmi.</p>
      <p class="repo-help-back"><a class="repo-btn" href="#mulai">Kembali ke awal ↑</a></p>
    </section>
    <section class="repo-card repo-help-feedback" id="help-feedback">
      <p class="repo-eyebrow">Perbaikan berkelanjutan</p><h2>Apakah panduan ini membantu?</h2>
      <%if("thanks".equals(request.getParameter("feedback"))){%><div class="repo-alert repo-alert-success" role="status">Terima kasih. Masukan Anda telah dicatat untuk tinjauan konten berikutnya.</div><%}%>
      <p>Penilaian digunakan untuk menemukan bab yang perlu diperjelas. Jangan menulis kata sandi, OTP, NIM lengkap, atau data pribadi pada komentar.</p>
      <form method="post" action="<%=root%>/repository" class="repo-help-feedback-form">
        <input type="hidden" name="action" value="helpFeedback"><input type="hidden" name="csrf" value="<%=rh((String)request.getAttribute("repoCsrf"))%>"><input type="hidden" name="contentKey" value="repository-help-v2" data-repo-help-content>
        <fieldset><legend>Penilaian</legend><label><input type="radio" name="helpful" value="yes" required> Ya, membantu</label><label><input type="radio" name="helpful" value="no" required> Belum membantu</label></fieldset>
        <label>Komentar opsional <textarea name="comment" rows="3" maxlength="1000" placeholder="Sebut bab atau langkah yang perlu diperjelas; jangan sertakan data sensitif."></textarea></label>
        <button class="repo-btn repo-btn-primary" type="submit">Kirim penilaian</button>
      </form>
    </section>
  </article>
</section>
