<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ page import="java.text.SimpleDateFormat" %>
<%@ page import="java.util.*" %>
<%@ page import="ais.database.model.repository.*" %>
<%@ page import="ais.action.master.repository.RepositoryPublicService.CollectionView" %>
<%@ page import="ais.action.master.repository.RepositoryWorkflowService.DuplicateCandidate" %>
<%@ page import="ais.action.master.repository.RepositoryPublicService.MetadataSuggestion" %>
<%@ page import="ais.action.master.repository.RepositoryAdminService.Health" %>
<%@ page import="ais.action.master.repository.RepositoryAdminService.ImportResult" %>
<%@ page import="ais.action.master.repository.RepositoryAdminService.FixityResult" %>
<%!
private String wh(String value) { if (value == null) return ""; return value.replace("&","&amp;").replace("<","&lt;").replace(">","&gt;").replace("\"","&quot;").replace("'","&#39;"); }
private String wf(Date value) { return value == null ? "" : new SimpleDateFormat("yyyy-MM-dd").format(value); }
private String ws(Date value) { return value == null ? "-" : new SimpleDateFormat("dd MMM yyyy HH:mm").format(value); }
private String authorsForEdit(String value) { return value == null ? "" : value.replace("; ","\n").replace(";","\n"); }
private boolean editable(RepoItem item) { return item == null || "DRAFT".equals(item.getWorkflowStatus()) || "REVISION_REQUIRED".equals(item.getWorkflowStatus()); }
%>
<%
String root=request.getContextPath(); String csrf=(String)request.getAttribute("repoCsrf");
String view=(String)request.getAttribute("repoWorkspaceView"); if(view==null)view="deposit";
boolean admin=Boolean.TRUE.equals(request.getAttribute("repoIsAdmin")); RepoItem item=(RepoItem)request.getAttribute("repoWorkspaceItem");
List<CollectionView> collections=(List<CollectionView>)request.getAttribute("repoCollections"); if(collections==null)collections=Collections.emptyList();
List<RepoItem> deposits=(List<RepoItem>)request.getAttribute("repoMyDeposits"); if(deposits==null)deposits=Collections.emptyList();
List<RepoItem> queue=(List<RepoItem>)request.getAttribute("repoReviewQueue"); if(queue==null)queue=Collections.emptyList();
List<RepoBitstream> bitstreams=(List<RepoBitstream>)request.getAttribute("repoWorkspaceFiles"); if(bitstreams==null)bitstreams=Collections.emptyList();
List<RepoWorkflowEvent> history=(List<RepoWorkflowEvent>)request.getAttribute("repoWorkspaceHistory"); if(history==null)history=Collections.emptyList();
List<DuplicateCandidate> duplicates=(List<DuplicateCandidate>)request.getAttribute("repoDuplicates"); if(duplicates==null)duplicates=Collections.emptyList();
List<RepoNotification> notifications=(List<RepoNotification>)request.getAttribute("repoNotifications"); if(notifications==null)notifications=Collections.emptyList();
String orcids=(String)request.getAttribute("repoAuthorOrcids"); if(orcids==null)orcids="";
String affiliations=(String)request.getAttribute("repoAuthorAffiliations");if(affiliations==null)affiliations="";String authorRors=(String)request.getAttribute("repoAuthorRors");if(authorRors==null)authorRors="";
String advisors=(String)request.getAttribute("repoAdvisors");if(advisors==null)advisors="";String examiners=(String)request.getAttribute("repoExaminers");if(examiners==null)examiners="";
String programStudy=(String)request.getAttribute("repoProgramStudy");if(programStudy==null)programStudy="";String faculty=(String)request.getAttribute("repoFaculty");if(faculty==null)faculty="";
String funding=(String)request.getAttribute("repoFunding");if(funding==null)funding="";String rightsStatement=(String)request.getAttribute("repoRightsStatement");if(rightsStatement==null)rightsStatement="";String depositorNote=(String)request.getAttribute("repoDepositorNote");if(depositorNote==null)depositorNote="";
String bibliography=(String)request.getAttribute("repoBibliography");if(bibliography==null)bibliography="";
Object flash=request.getAttribute("repoFlash"), flashError=request.getAttribute("repoFlashError"); boolean canEdit=editable(item);
MetadataSuggestion aiSuggestion=(MetadataSuggestion)request.getAttribute("repoAiSuggestion");
List<RepoCollection> adminCollections=(List<RepoCollection>)request.getAttribute("repoAdminCollections"); if(adminCollections==null)adminCollections=Collections.emptyList();
List<RepoAuthorAuthority> authorities=(List<RepoAuthorAuthority>)request.getAttribute("repoAuthorities");if(authorities==null)authorities=Collections.emptyList();
RepoCollection adminCollection=(RepoCollection)request.getAttribute("repoAdminCollection"); Health health=(Health)request.getAttribute("repoAdminHealth");
ImportResult importResult=(ImportResult)request.getAttribute("repoImportResult"); FixityResult fixityResult=(FixityResult)request.getAttribute("repoFixityResult");
boolean dataCiteConfigured=Boolean.TRUE.equals(request.getAttribute("repoDataCiteConfigured")),coarConfigured=Boolean.TRUE.equals(request.getAttribute("repoCoarConfigured")),orcidConfigured=Boolean.TRUE.equals(request.getAttribute("repoOrcidConfigured")),rorConfigured=Boolean.TRUE.equals(request.getAttribute("repoRorConfigured")),aiConfigured=Boolean.TRUE.equals(request.getAttribute("repoAiConfigured"));
Map<String,String> deploymentChecks=(Map<String,String>)request.getAttribute("repoDeploymentChecks");if(deploymentChecks==null)deploymentChecks=Collections.emptyMap();
%>
<!doctype html><html lang="id"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Workspace Repository AIS</title><jsp:include page="/WEB-INF/baru/modul/repository/_repository_theme.jsp" /></head>
<body class="repo-modern repo-workspace-body">
<a class="repo-skip" href="#workspace-main">Lewati ke konten</a>
<header class="repo-topbar"><div class="repo-wrap repo-nav"><a class="repo-brand" href="<%=root%>/repository"><span class="repo-brand-mark">R</span><span><strong>Repository AIS</strong><small>Workspace internal</small></span></a><nav class="repo-links" aria-label="Workspace"><a href="<%=root%>/repository">Portal publik</a><a href="<%=root%>/repository-workspace?view=deposit" <%="deposit".equals(view)?"aria-current='page'":""%>>Deposit saya</a><%if(admin){%><a href="<%=root%>/repository-workspace?view=review" <%="review".equals(view)?"aria-current='page'":""%>>Review</a><a href="<%=root%>/repository-workspace?view=admin" <%="admin".equals(view)?"aria-current='page'":""%>>Admin</a><%}%></nav></div></header>
<main id="workspace-main" class="repo-wrap repo-workspace">
<%if(!notifications.isEmpty()){%><details class="repo-card repo-notifications"><summary>Notifikasi repository (<%=notifications.size()%>)</summary><div><%for(RepoNotification n:notifications){%><article class="<%=n.getReadAt()==null?"is-unread":""%>"><span><strong><%=wh(n.getType())%></strong> · <%=wh(n.getMessage())%></span><small><%=ws(n.getCreatedAt())%></small><%if(n.getReadAt()==null){%><form method="post" action="<%=root%>/repository-workspace"><input type="hidden" name="csrf" value="<%=wh(csrf)%>"><input type="hidden" name="action" value="readNotification"><input type="hidden" name="notificationId" value="<%=n.getId()%>"><button class="repo-btn" type="submit">Tandai dibaca</button></form><%}%></article><%}%></div></details><%}%>
<%if(flash!=null){%><div class="repo-alert repo-alert-success" role="status"><%=wh(String.valueOf(flash))%></div><%}%>
<%if(flashError!=null){%><div class="repo-alert repo-alert-error" role="alert"><%=wh(String.valueOf(flashError))%></div><%}%>

<%if("deposit".equals(view)){%>
<div class="repo-workspace-grid">
  <aside class="repo-card repo-workspace-side"><div class="repo-section-head"><div><h2>Deposit saya</h2><p><%=deposits.size()%> record</p></div><a class="repo-btn repo-btn-primary" href="<%=root%>/repository-workspace?view=deposit">Baru</a></div>
    <div class="repo-deposit-list"><%for(RepoItem d:deposits){%><a href="<%=root%>/repository-workspace?view=deposit&id=<%=d.getId()%>" <%=(item!=null&&d.getId().equals(item.getId()))?"aria-current='page'":""%>><strong><%=wh(d.getTitle().length()==0?"Draft tanpa judul":d.getTitle())%></strong><small><%=wh(d.getWorkflowStatus())%> · v<%=d.getLockVersion()%></small></a><%}%><%if(deposits.isEmpty()){%><p class="repo-muted">Belum ada deposit.</p><%}%></div>
  </aside>
  <section class="repo-workspace-main">
    <div class="repo-card repo-card-pad"><div class="repo-section-head"><div><p class="repo-eyebrow">Deposit wizard</p><h1><%=item==null?"Buat deposit baru":wh(item.getTitle().length()==0?"Lengkapi draft":item.getTitle())%></h1></div><%if(item!=null){%><span class="repo-chip"><%=wh(item.getWorkflowStatus())%></span><%}%></div>
      <ol class="repo-stepper repo-stepper-nine" aria-label="Tahapan deposit"><li class="active">1 Jenis karya</li><li>2 Informasi utama</li><li>3 Penulis</li><li>4 Akademik</li><li>5 Subjek</li><li>6 File</li><li>7 Lisensi</li><li>8 Preview</li><li>9 Kirim</li></ol>
      <form method="post" action="<%=root%>/repository-workspace" class="repo-workspace-form" <%=item!=null&&canEdit?"data-repo-autosave":""%>>
        <input type="hidden" name="csrf" value="<%=wh(csrf)%>"><input type="hidden" name="action" value="<%=item==null?"create":"save"%>"><%if(item!=null){%><input type="hidden" name="id" value="<%=item.getId()%>"><input type="hidden" name="version" value="<%=item.getLockVersion()%>"><%}%>
        <fieldset <%=canEdit?"":"disabled"%>><legend>1–2. Jenis karya dan informasi utama</legend><div class="repo-form-grid">
          <label>Koleksi <span aria-hidden="true">*</span><select name="collectionId" required><option value="">Pilih koleksi</option><%for(CollectionView c:collections){%><option value="<%=c.id%>" <%=(item!=null&&c.id.equals(item.getCollectionId()))?"selected":""%>><%=wh(c.nama)%></option><%}%></select></label>
<label>Jenis dokumen <select name="documentType"><%String[] types={"Skripsi","Tesis","Disertasi","Thesis","Dissertation","Article","Book","Book Chapter","Karya Dosen","Research Report","Proceedings","Dataset","Teaching Material","Other"};for(String t:types){%><option <%=(item!=null&&t.equals(item.getDocumentType()))?"selected":""%>><%=t%></option><%}%></select></label>
          <label class="repo-field-full">Judul <span aria-hidden="true">*</span><input name="title" maxlength="4000" required value="<%=item==null?"":wh(item.getTitle())%>"></label>
          <label class="repo-field-full">Abstrak <textarea name="abstractText" rows="7" maxlength="40000"><%=item==null?"":wh(item.getAbstractText())%></textarea></label>
          <label class="repo-field-full">Subjek/kata kunci <textarea name="subjects" rows="3" placeholder="Pisahkan dengan titik koma"><%=item==null?"":wh(item.getSubjects())%></textarea></label>
          <label>Penerbit <input name="publisher" maxlength="255" value="<%=item==null?"":wh(item.getPublisher())%>"></label><label>Bahasa <select name="language"><option value="id" <%=(item==null||"id".equals(item.getLanguage()))?"selected":""%>>Indonesia</option><option value="en" <%=(item!=null&&"en".equals(item.getLanguage()))?"selected":""%>>English</option></select></label>
          <label>DOI <input name="doi" maxlength="255" placeholder="10.xxxx/xxxxx" value="<%=item==null?"":wh(item.getDoi())%>"></label>
        </div></fieldset>
        <fieldset <%=canEdit?"":"disabled"%>><legend>3. Penulis dan kontributor</legend><div class="repo-form-grid"><label>Nama penulis—satu per baris <textarea name="authors" rows="5" required><%=item==null?"":wh(authorsForEdit(item.getAuthors()))%></textarea></label><label>ORCID sesuai urutan penulis—boleh kosong <textarea name="authorOrcids" rows="5" placeholder="0000-0002-1825-0097"><%=wh(orcids)%></textarea></label><label>Afiliasi sesuai urutan penulis<textarea name="authorAffiliations" rows="5"><%=wh(affiliations)%></textarea></label><label>ROR ID afiliasi sesuai urutan<textarea name="authorRors" rows="5" placeholder="https://ror.org/..."><%=wh(authorRors)%></textarea></label></div></fieldset>
        <fieldset <%=canEdit?"":"disabled"%>><legend>4. Informasi akademik</legend><div class="repo-form-grid"><label>Program studi<input name="programStudy" maxlength="255" value="<%=wh(programStudy)%>"></label><label>Fakultas/unit<input name="faculty" maxlength="255" value="<%=wh(faculty)%>"></label><label>Pembimbing—satu per baris<textarea name="advisors" rows="4"><%=wh(advisors)%></textarea></label><label>Penguji—satu per baris<textarea name="examiners" rows="4"><%=wh(examiners)%></textarea></label></div></fieldset>
<fieldset <%=canEdit?"":"disabled"%>><legend>5. Subjek, daftar pustaka, pendanaan, dan catatan</legend><div class="repo-form-grid"><label>Pendanaan/hibah<input name="funding" maxlength="1000" value="<%=wh(funding)%>"></label><label class="repo-field-full">Daftar pustaka <textarea name="bibliography" rows="7" maxlength="40000" placeholder="Cantumkan referensi sesuai naskah final"><%=wh(bibliography)%></textarea><small class="repo-help">Wajib untuk skripsi, tesis, dan disertasi.</small></label><label class="repo-field-full">Pernyataan hak/distribusi<textarea name="rightsStatement" rows="3"><%=wh(rightsStatement)%></textarea></label><label class="repo-field-full">Catatan untuk reviewer<textarea name="depositorNote" rows="3"><%=wh(depositorNote)%></textarea></label></div></fieldset>
        <fieldset <%=canEdit?"":"disabled"%>><legend>Akses, lisensi, dan embargo</legend><div class="repo-form-grid"><label>Kebijakan akses <select name="accessPolicy"><%String[] accesses={"METADATA_ONLY","OPEN_ACCESS","EMBARGOED","INSTITUTION_ONLY","AUTHENTICATED","RESTRICTED"};for(String a:accesses){%><option <%=(item!=null&&a.equals(item.getAccessPolicy()))?"selected":""%>><%=a%></option><%}%></select></label><label>Lisensi <select name="licenseUri"><option value="">Belum dipilih</option><%String[][] licenses={{"https://creativecommons.org/licenses/by/4.0/","CC BY 4.0"},{"https://creativecommons.org/licenses/by-sa/4.0/","CC BY-SA 4.0"},{"https://creativecommons.org/licenses/by-nc/4.0/","CC BY-NC 4.0"},{"https://creativecommons.org/licenses/by-nc-nd/4.0/","CC BY-NC-ND 4.0"}};for(String[] l:licenses){%><option value="<%=l[0]%>" <%=(item!=null&&l[0].equals(item.getLicenseUri()))?"selected":""%>><%=l[1]%></option><%}%></select></label><label>Akhir embargo <input type="date" name="embargoUntil" value="<%=item==null?"":wf(item.getEmbargoUntil())%>"></label></div></fieldset>
        <%if(canEdit){%><div class="repo-form-actions"><button class="repo-btn repo-btn-primary" type="submit"><%=item==null?"Buat draft":"Simpan perubahan"%></button><span class="repo-autosave-status" aria-live="polite"></span></div><%}%>
      </form>
    </div>
    <%if(item!=null){%>
    <%if(!duplicates.isEmpty()){%><div class="repo-alert repo-alert-warning"><strong>Kemungkinan duplikat:</strong><%for(DuplicateCandidate d:duplicates){%> <a href="<%=root%>/repository/item/<%=d.id%>"><%=wh(d.title)%></a><%}%></div><%}%>
    <div class="repo-card repo-card-pad repo-ai-assistant"><div class="repo-section-head"><div><p class="repo-eyebrow">Metadata assistant</p><h2>Saran yang ditinjau manusia</h2></div><%if(canEdit){%><form method="post" action="<%=root%>/repository-workspace"><input type="hidden" name="csrf" value="<%=wh(csrf)%>"><input type="hidden" name="id" value="<%=item.getId()%>"><button class="repo-btn" name="action" value="aiSuggest">Buat saran draft</button></form><%}%></div><%if(aiSuggestion!=null){%><p><strong>Bahasa:</strong> <%=wh(aiSuggestion.language)%> · <strong>Jenis:</strong> <%=wh(aiSuggestion.documentType)%></p><div class="repo-chips"><%for(String keyword:aiSuggestion.keywords){%><span class="repo-chip"><%=wh(keyword)%></span><%}%></div><p class="repo-muted">Saran ini belum disimpan. Salin hanya setelah diperiksa.</p><%}%></div>
<div class="repo-card repo-card-pad"><h2>Berkas</h2><%if(canEdit){%><form method="post" enctype="multipart/form-data" action="<%=root%>/repository-workspace" class="repo-upload-form"><input type="hidden" name="csrf" value="<%=wh(csrf)%>"><input type="hidden" name="id" value="<%=item.getId()%>"><label>Pilih berkas <input type="file" name="file" required></label><label>Deskripsi <input name="description" maxlength="500"></label><label>Akses berkas <select name="fileAccess"><option>OPEN_ACCESS</option><option>RESTRICTED</option></select></label><label class="repo-check"><input type="checkbox" name="primary" value="true"> Berkas utama</label><label class="repo-check repo-watermark-check"><input type="checkbox" name="watermarkConfirmed" value="true"> PDF final sudah diberi watermark institusi</label><button class="repo-btn repo-btn-primary" type="submit">Unggah</button></form><p class="repo-help">Maksimal 100 MB. Konfirmasi watermark wajib untuk PDF. Signature, MIME, checksum SHA-256, dan status pemindaian dicatat.</p><%}%>
      <div class="repo-file-list"><%for(RepoBitstream b:bitstreams){%><article><div><strong><%=wh(b.getNamaFile())%></strong><small><%=wh(b.getMimeType())%> · SHA-256 <%=wh(b.getChecksum())%> · scan <%=wh(b.getVirusScanStatus())%> · versi <%=b.getFileVersion()%></small></div><%if(canEdit){%><form method="post" action="<%=root%>/repository-workspace"><input type="hidden" name="csrf" value="<%=wh(csrf)%>"><input type="hidden" name="action" value="removeFile"><input type="hidden" name="id" value="<%=item.getId()%>"><input type="hidden" name="fileId" value="<%=b.getId()%>"><button class="repo-btn repo-btn-danger" type="submit">Hapus</button></form><%}%></article><%}%><%if(bitstreams.isEmpty()){%><p class="repo-muted">Belum ada berkas.</p><%}%></div>
    </div>
    <div class="repo-card repo-card-pad"><h2>Validasi dan pengiriman</h2><p>Pastikan metadata, lisensi, akses, dan berkas utama telah benar.</p><%if("DRAFT".equals(item.getWorkflowStatus())||"REVISION_REQUIRED".equals(item.getWorkflowStatus())){%><form method="post" action="<%=root%>/repository-workspace"><input type="hidden" name="csrf" value="<%=wh(csrf)%>"><input type="hidden" name="action" value="<%="REVISION_REQUIRED".equals(item.getWorkflowStatus())?"resubmit":"submit"%>"><input type="hidden" name="id" value="<%=item.getId()%>"><input type="hidden" name="version" value="<%=item.getLockVersion()%>"><label>Catatan untuk reviewer <textarea name="comment" rows="3"></textarea></label><button class="repo-btn repo-btn-primary" type="submit">Kirim untuk review</button></form><%}else{%><p class="repo-alert repo-alert-success">Item berada pada status <strong><%=wh(item.getWorkflowStatus())%></strong>.</p><%}%></div>
    <div class="repo-card repo-card-pad"><h2>Riwayat</h2><ol class="repo-timeline"><%for(RepoWorkflowEvent e:history){%><li><strong><%=wh(e.getAction())%></strong><span><%=wh(e.getFromStatus())%> → <%=wh(e.getToStatus())%></span><small><%=wh(e.getActorName())%> · <%=ws(e.getCreatedAt())%></small><%if(e.getCommentText()!=null&&!e.getCommentText().trim().isEmpty()){%><p><%=wh(e.getCommentText())%></p><%}%></li><%}%></ol></div>
    <%}%>
  </section>
</div>
<%}else if("review".equals(view)){%>
<section class="repo-card repo-card-pad"><div class="repo-section-head"><div><p class="repo-eyebrow">Review queue</p><h1>Antrian penelaahan</h1></div><span class="repo-chip"><%=queue.size()%> item</span></div><div class="repo-admin-table"><table><thead><tr><th>Item</th><th>Status</th><th>Pemilik</th><th>Reviewer</th><th>Aksi</th></tr></thead><tbody><%for(RepoItem q:queue){%><tr><td><strong><%=wh(q.getTitle())%></strong><small><%=wh(q.getDocumentType())%></small></td><td><%=wh(q.getWorkflowStatus())%></td><td><%=wh(q.getOwnerId())%></td><td><%=wh(q.getAssignedReviewerId())%></td><td><a class="repo-btn" href="<%=root%>/repository-workspace?view=review&id=<%=q.getId()%>">Review</a></td></tr><%}%></tbody></table></div></section>
<%if(item!=null){%><section class="repo-card repo-card-pad repo-review-panel"><h2><%=wh(item.getTitle())%></h2><p><%=wh(item.getAuthors())%></p><p><%=wh(item.getAbstractText())%></p><div class="repo-chips"><span class="repo-chip"><%=wh(item.getWorkflowStatus())%></span><span class="repo-chip"><%=wh(item.getAccessPolicy())%></span></div><form method="post" action="<%=root%>/repository-workspace" class="repo-review-actions"><input type="hidden" name="csrf" value="<%=wh(csrf)%>"><input type="hidden" name="id" value="<%=item.getId()%>"><input type="hidden" name="version" value="<%=item.getLockVersion()%>"><label>Catatan keputusan <textarea name="comment" rows="4"></textarea></label><div><%if("SUBMITTED".equals(item.getWorkflowStatus())){%><button name="action" value="claim" class="repo-btn repo-btn-primary">Claim</button><%}%><%if("IN_REVIEW".equals(item.getWorkflowStatus())){%><button name="action" value="return" class="repo-btn">Kembalikan</button><button name="action" value="reject" class="repo-btn repo-btn-danger">Tolak</button><button name="action" value="approve" class="repo-btn repo-btn-primary">Setujui</button><%}%><%if("APPROVED".equals(item.getWorkflowStatus())){%><button name="action" value="publish" class="repo-btn repo-btn-primary">Publikasikan</button><%}%><%if("PUBLISHED".equals(item.getWorkflowStatus())){%><button name="action" value="withdraw" class="repo-btn repo-btn-danger">Tarik</button><%}%><%if("WITHDRAWN".equals(item.getWorkflowStatus())){%><button name="action" value="restore" class="repo-btn repo-btn-primary">Pulihkan</button><%}%><button name="action" value="comment" class="repo-btn">Tambah komentar</button></div></form><h3>Riwayat audit</h3><ol class="repo-timeline"><%for(RepoWorkflowEvent e:history){%><li><strong><%=wh(e.getAction())%></strong><span><%=wh(e.getFromStatus())%> → <%=wh(e.getToStatus())%></span><small><%=wh(e.getActorName())%> · <%=ws(e.getCreatedAt())%></small><p><%=wh(e.getCommentText())%></p></li><%}%></ol></section><%}%>
<%if(item!=null){%><section class="repo-card repo-card-pad repo-integration-actions"><p class="repo-eyebrow">Publikasi dan interoperabilitas</p><h2>DOI, karya unggulan, dan COAR Notify</h2><div class="repo-paper-actions"><form method="post" action="<%=root%>/repository-workspace"><input type="hidden" name="csrf" value="<%=wh(csrf)%>"><input type="hidden" name="id" value="<%=item.getId()%>"><button class="repo-btn" name="action" value="toggleFeatured"><%=Boolean.TRUE.equals(item.getFeatured())?"Hapus dari unggulan":"Jadikan karya unggulan"%></button></form><form method="post" action="<%=root%>/repository-workspace"><input type="hidden" name="csrf" value="<%=wh(csrf)%>"><input type="hidden" name="id" value="<%=item.getId()%>"><button class="repo-btn repo-btn-primary" name="action" value="datacite" <%=dataCiteConfigured?"":"disabled"%>>Mint/update DOI DataCite</button></form><form method="post" action="<%=root%>/repository-workspace"><input type="hidden" name="csrf" value="<%=wh(csrf)%>"><input type="hidden" name="id" value="<%=item.getId()%>"><label>Target layanan eksternal<input name="targetUrl" type="url" placeholder="https://..."></label><button class="repo-btn" name="action" value="coarNotify" <%=coarConfigured?"":"disabled"%>>Kirim COAR Notify</button></form></div><p class="repo-muted">Operasi eksternal selalu dicatat pada audit integrasi. Tombstone dan DOI yang sudah terdaftar tidak dihapus.</p></section><%}%>
<%}else{%>
<section class="repo-card repo-card-pad"><div class="repo-section-head"><div><p class="repo-eyebrow">Administrasi</p><h1>Kesehatan Repository</h1></div><a class="repo-btn" href="<%=root%>/repository-workspace?view=admin&action=exportXlsx">Ekspor XLSX</a></div>
<%if(health!=null){%><div class="repo-admin-cards"><article><h2>Item publik</h2><b><%=health.publicItems%></b><p><%=health.items%> total item</p></article><article><h2>Antrian review</h2><b><%=queue.size()%></b><p>Status workflow aktif</p></article><article><h2>OAI-PMH</h2><b><%=health.missingOai+health.duplicateOai%></b><p>Missing/duplikat identifier · <a href="<%=root%>/oai?verb=Identify">Identify</a></p></article><article><h2>Berkas</h2><b><%=health.bitstreams%></b><p><%=health.pendingScan%> scan tertunda · <%=health.infected%> terinfeksi</p></article></div>
<div class="repo-integration-status" aria-label="Status integrasi"><span class="repo-chip <%=dataCiteConfigured?"repo-chip-open":"repo-chip-warning"%>">DataCite <%=dataCiteConfigured?"siap":"belum dikonfigurasi"%></span><span class="repo-chip <%=orcidConfigured?"repo-chip-open":"repo-chip-warning"%>">ORCID <%=orcidConfigured?"siap":"belum dikonfigurasi"%></span><span class="repo-chip <%=rorConfigured?"repo-chip-open":"repo-chip-warning"%>">ROR <%=rorConfigured?"siap":"belum dikonfigurasi"%></span><span class="repo-chip <%=coarConfigured?"repo-chip-open":"repo-chip-warning"%>">COAR Notify <%=coarConfigured?"siap":"belum dikonfigurasi"%></span><span class="repo-chip <%=aiConfigured?"repo-chip-open":"repo-chip-warning"%>">AI <%=aiConfigured?"siap":"fallback lokal"%></span></div>
<div class="repo-health-grid"><div><h3>Workflow</h3><ul class="repo-stat-list"><%for(Map.Entry<String,Long> e:health.workflow.entrySet()){%><li><span><%=wh(e.getKey())%></span><b><%=e.getValue()%></b></li><%}%></ul></div><div><h3>Integritas &amp; integrasi</h3><ul class="repo-stat-list"><li><span>Checksum kosong</span><b><%=health.missingChecksum%></b></li><li><span>Sync gagal</span><b><%=health.failedSync%></b></li><li><span>Turnitin terkirim</span><b><%=health.turnitinSubmitted%></b></li><li><span>OAI publik</span><b><%=health.publicItems%></b></li></ul><%if(health.failedSync>0){%><form method="post" action="<%=root%>/repository-workspace"><input type="hidden" name="csrf" value="<%=wh(csrf)%>"><button class="repo-btn" name="action" value="retrySync">Antrekan ulang sync gagal</button></form><%}%></div></div>
<div class="repo-health-grid"><section><h3>Kualitas metadata</h3><ul class="repo-stat-list"><%for(Map.Entry<String,Integer> metric:health.qualityPercent.entrySet()){%><li><span><%=wh(metric.getKey())%><small><%=health.qualityMissing.get(metric.getKey())%> perlu diperbaiki</small></span><b><%=metric.getValue()%>%</b></li><%}%></ul><div class="repo-bulk-actions"><form method="post" action="<%=root%>/repository-workspace"><input type="hidden" name="csrf" value="<%=wh(csrf)%>"><input type="hidden" name="action" value="bulkRepairMetadata"><select name="field"><option value="language">Isi bahasa kosong → id</option><option value="documentType">Isi jenis kosong → Other</option><option value="accessPolicy">Isi akses kosong → Metadata saja</option></select><button class="repo-btn" type="submit">Perbaiki massal</button></form></div></section><section><h3>Penggunaan terverifikasi</h3><ul class="repo-stat-list"><li><span>Human view</span><b><%=health.humanViews%></b></li><li><span>Unique view</span><b><%=health.uniqueViews%></b></li><li><span>Bot/crawler</span><b><%=health.botViews%></b></li><li><span>Human download</span><b><%=health.humanDownloads%></b></li><li><span>Unique download</span><b><%=health.uniqueDownloads%></b></li></ul></section></div>
<div class="repo-health-grid"><section><h3>Negara pengakses</h3><ul class="repo-stat-list"><%for(Map.Entry<String,Long> e:health.countries.entrySet()){%><li><span><%=wh(e.getKey())%></span><b><%=e.getValue()%></b></li><%}if(health.countries.isEmpty()){%><li><span>Belum ada data negara</span><b>—</b></li><%}%></ul></section><section><h3>Referrer</h3><ul class="repo-stat-list"><%for(Map.Entry<String,Long> e:health.referrers.entrySet()){%><li><span><%=wh(e.getKey())%></span><b><%=e.getValue()%></b></li><%}if(health.referrers.isEmpty()){%><li><span>Belum ada data referrer</span><b>—</b></li><%}%></ul></section></div>
<section class="repo-usage-trend" aria-labelledby="repo-usage-trend-title"><h3 id="repo-usage-trend-title">Tren penggunaan manusia 30 hari</h3><div class="repo-trend-bars"><%long trendMax=1L;for(Long n:health.dailyTrend.values())if(n!=null&&n.longValue()>trendMax)trendMax=n.longValue();for(Map.Entry<String,Long> e:health.dailyTrend.entrySet()){long count=e.getValue()==null?0L:e.getValue().longValue();int height=(int)Math.max(4L,Math.round((count*100.0d)/trendMax));%><span class="repo-trend-bar" title="<%=wh(e.getKey())%>: <%=count%> aktivitas"><i style="height:<%=height%>%"></i><small><%=wh(e.getKey().substring(Math.max(0,e.getKey().length()-5)))%></small><b><%=count%></b></span><%}if(health.dailyTrend.isEmpty()){%><p class="repo-muted">Belum ada aktivitas manusia dalam 30 hari terakhir.</p><%}%></div></section><%}%></section>

<div class="repo-admin-layout"><section class="repo-card repo-card-pad"><div class="repo-section-head"><div><p class="repo-eyebrow">Typed profiles</p><h2>Profil koleksi</h2></div><a class="repo-btn" href="<%=root%>/repository-workspace?view=admin">Koleksi baru</a></div>
<div class="repo-collection-admin-list"><%for(RepoCollection c:adminCollections){%><a href="<%=root%>/repository-workspace?view=admin&collectionId=<%=c.getId()%>"><strong><%=wh(c.getNama())%></strong><small><%=Boolean.TRUE.equals(c.getDepositEnabled())?"Deposit aktif":"Deposit nonaktif"%></small></a><%}%></div>
<form method="post" action="<%=root%>/repository-workspace" class="repo-workspace-form"><input type="hidden" name="csrf" value="<%=wh(csrf)%>"><input type="hidden" name="action" value="saveCollectionProfile"><%if(adminCollection!=null){%><input type="hidden" name="collectionProfileId" value="<%=adminCollection.getId()%>"><%}%>
<div class="repo-form-grid"><label>Kode <input name="kode" maxlength="50" value="<%=adminCollection==null?"":wh(adminCollection.getKode())%>"></label><label>Nama <span aria-hidden="true">*</span><input name="nama" required maxlength="255" value="<%=adminCollection==null?"":wh(adminCollection.getNama())%>"></label><label>Induk <select name="parentId"><option value="">Tanpa induk</option><%for(RepoCollection c:adminCollections){if(adminCollection!=null&&c.getId().equals(adminCollection.getId()))continue;%><option value="<%=c.getId()%>" <%=(adminCollection!=null&&c.getId().equals(adminCollection.getParentId()))?"selected":""%>><%=wh(c.getNama())%></option><%}%></select></label><label>Lisensi default <input name="defaultLicenseUri" maxlength="500" value="<%=adminCollection==null?"":wh(adminCollection.getDefaultLicenseUri())%>"></label><label class="repo-field-full">Deskripsi <textarea name="description" rows="3"><%=adminCollection==null?"":wh(adminCollection.getDeskripsi())%></textarea></label><label class="repo-check repo-field-full"><input type="checkbox" name="depositEnabled" value="true" <%=(adminCollection==null||Boolean.TRUE.equals(adminCollection.getDepositEnabled()))?"checked":""%>> Deposit diizinkan</label>
<label class="repo-field-full">Profil metadata (JSON)<textarea class="repo-code-input" name="metadataProfileJson" rows="7" required><%=adminCollection==null?"{}":wh(adminCollection.getMetadataProfileJson())%></textarea></label><label class="repo-field-full">Profil workflow (JSON)<textarea class="repo-code-input" name="workflowProfileJson" rows="6" required><%=adminCollection==null?"{}":wh(adminCollection.getWorkflowProfileJson())%></textarea></label><label class="repo-field-full">Kebijakan akses (JSON)<textarea class="repo-code-input" name="accessPolicyJson" rows="6" required><%=adminCollection==null?"{}":wh(adminCollection.getAccessPolicyJson())%></textarea></label></div><button class="repo-btn repo-btn-primary" type="submit">Simpan profil typed</button></form></section>

<aside><section class="repo-card repo-card-pad"><p class="repo-eyebrow">Preservasi</p><h2>Fixity SHA-256</h2><p>Membaca ulang berkas aktif dan membandingkannya dengan checksum tersimpan.</p><form method="post" action="<%=root%>/repository-workspace"><input type="hidden" name="csrf" value="<%=wh(csrf)%>"><button class="repo-btn repo-btn-primary" name="action" value="verifyFixity">Jalankan pemeriksaan</button></form><%if(fixityResult!=null){%><div class="repo-alert <%=fixityResult.mismatch+fixityResult.missing==0?"repo-alert-success":"repo-alert-error"%>"><%=fixityResult.ok%>/<%=fixityResult.checked%> cocok; <%=fixityResult.missing%> hilang; <%=fixityResult.mismatch%> berbeda.<%for(String err:fixityResult.errors){%><br><%=wh(err)%><%}%></div><%}%></section>
<section class="repo-card repo-card-pad"><p class="repo-eyebrow">Bulk import</p><h2>Dry-run XLSX</h2><p>Validasi saja, tanpa menulis data. Header: title, authors, collection_id, document_type, access_policy.</p><form method="post" enctype="multipart/form-data" action="<%=root%>/repository-workspace"><input type="hidden" name="csrf" value="<%=wh(csrf)%>"><input type="hidden" name="action" value="importDryRun"><input type="file" name="file" accept=".xlsx" required><button class="repo-btn repo-btn-primary" type="submit">Validasi dry-run</button></form><%if(importResult!=null){%><div class="repo-alert <%=importResult.isValid()?"repo-alert-success":"repo-alert-warning"%>"><%=importResult.validRows%>/<%=importResult.rows%> baris valid.<%for(String err:importResult.errors){%><br><%=wh(err)%><%}%></div><%}%></section></aside></div>
<section class="repo-card repo-card-pad"><p class="repo-eyebrow">Deployment readiness</p><h2>Pemeriksaan konfigurasi</h2><ul class="repo-stat-list"><%for(Map.Entry<String,String> check:deploymentChecks.entrySet()){%><li><span><%=wh(check.getKey())%></span><b><%=wh(check.getValue())%></b></li><%}%></ul><p class="repo-muted">Status ini memeriksa kesiapan konfigurasi tanpa mengirim data atau memanggil layanan eksternal.</p></section>
<section class="repo-card repo-card-pad"><p class="repo-eyebrow">Authority control</p><h2>Penulis, ORCID, dan ROR</h2><div class="repo-admin-table"><table><thead><tr><th>Nama baku</th><th>ORCID</th><th>Afiliasi/ROR</th><th>Status</th><th>Aksi</th></tr></thead><tbody><%for(RepoAuthorAuthority authority:authorities){%><tr><td><strong><%=wh(authority.getCanonicalName())%></strong><small><%=wh(authority.getNameVariants().replace("\n"," · "))%></small></td><td><%=wh(authority.getOrcid())%><%if(orcidConfigured&&!Boolean.TRUE.equals(authority.getVerified())){%><small><a href="<%=root%>/repository-workspace?action=orcidStart&amp;authorityId=<%=authority.getId()%>">Autentikasi ORCID</a></small><%}%></td><td><%=wh(authority.getAffiliation())%><small><%=wh(authority.getRorId())%></small></td><td><%=Boolean.TRUE.equals(authority.getVerified())?"Terverifikasi":"Belum diverifikasi"%></td><td><form method="post" action="<%=root%>/repository-workspace"><input type="hidden" name="csrf" value="<%=wh(csrf)%>"><input type="hidden" name="action" value="rorMatch"><input type="hidden" name="authorityId" value="<%=authority.getId()%>"><input name="query" required value="<%=wh(authority.getAffiliation())%>" placeholder="Nama institusi"><button class="repo-btn" <%=rorConfigured?"":"disabled"%>>Cocokkan ROR</button></form></td></tr><%}if(authorities.isEmpty()){%><tr><td colspan="5">Belum ada authority penulis. Authority dibuat ketika metadata penulis disinkronkan.</td></tr><%}%></tbody></table></div><h3>Gabungkan variasi nama</h3><form method="post" action="<%=root%>/repository-workspace" class="repo-form-grid"><input type="hidden" name="csrf" value="<%=wh(csrf)%>"><input type="hidden" name="action" value="mergeAuthorities"><label>Authority sumber<select name="sourceAuthorityId" required><option value="">Pilih</option><%for(RepoAuthorAuthority a:authorities){%><option value="<%=a.getId()%>"><%=wh(a.getCanonicalName())%></option><%}%></select></label><label>Authority tujuan<select name="targetAuthorityId" required><option value="">Pilih nama baku</option><%for(RepoAuthorAuthority a:authorities){%><option value="<%=a.getId()%>"><%=wh(a.getCanonicalName())%></option><%}%></select></label><button class="repo-btn repo-btn-primary repo-field-full" type="submit" <%=authorities.size()<2?"disabled":""%>>Gabungkan dengan jejak audit</button></form></section>
<%}%>
</main><script src="<%=root%>/js/repository-modern.js"></script></body></html>
