<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ page import="java.text.SimpleDateFormat" %>
<%@ page import="java.util.*" %>
<%@ page import="ais.database.model.repository.*" %>
<%@ page import="ais.action.master.repository.RepositoryPublicService.CollectionView" %>
<%@ page import="ais.action.master.repository.RepositoryWorkflowService.DuplicateCandidate" %>
<%!
private String wh(String value) { if (value == null) return ""; return value.replace("&","&amp;").replace("<","&lt;").replace(">","&gt;").replace("\"","&quot;").replace("'","&#39;"); }
private String wf(Date value) { return value == null ? "" : new SimpleDateFormat("yyyy-MM-dd").format(value); }
private String ws(Date value) { return value == null ? "-" : new SimpleDateFormat("dd MMM yyyy HH:mm").format(value); }
private String authorsForEdit(String value) { return value == null ? "" : value.replace("; ","\n").replace(";","\n"); }
private boolean editable(RepoItem item) { return item == null || "DRAFT".equals(item.getWorkflowStatus()) || "REVISION_REQUIRED".equals(item.getWorkflowStatus()); }
%>
<%
String root=request.getContextPath(); String csrf=(String)request.getAttribute("repoCsrf");
String view=(String)request.getAttribute("repoWorkspaceView"); if(view==null)view="deposit";
boolean admin=Boolean.TRUE.equals(request.getAttribute("repoIsAdmin")); RepoItem item=(RepoItem)request.getAttribute("repoWorkspaceItem");
List<CollectionView> collections=(List<CollectionView>)request.getAttribute("repoCollections"); if(collections==null)collections=Collections.emptyList();
List<RepoItem> deposits=(List<RepoItem>)request.getAttribute("repoMyDeposits"); if(deposits==null)deposits=Collections.emptyList();
List<RepoItem> queue=(List<RepoItem>)request.getAttribute("repoReviewQueue"); if(queue==null)queue=Collections.emptyList();
List<RepoBitstream> bitstreams=(List<RepoBitstream>)request.getAttribute("repoWorkspaceFiles"); if(bitstreams==null)bitstreams=Collections.emptyList();
List<RepoWorkflowEvent> history=(List<RepoWorkflowEvent>)request.getAttribute("repoWorkspaceHistory"); if(history==null)history=Collections.emptyList();
List<DuplicateCandidate> duplicates=(List<DuplicateCandidate>)request.getAttribute("repoDuplicates"); if(duplicates==null)duplicates=Collections.emptyList();
String orcids=(String)request.getAttribute("repoAuthorOrcids"); if(orcids==null)orcids="";
Object flash=request.getAttribute("repoFlash"), flashError=request.getAttribute("repoFlashError"); boolean canEdit=editable(item);
%>
<!doctype html><html lang="id"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Workspace Repository AIS</title><link rel="stylesheet" href="<%=root%>/css/repository-modern.css"></head>
<body class="repo-modern repo-workspace-body">
<a class="repo-skip" href="#workspace-main">Lewati ke konten</a>
<header class="repo-topbar"><div class="repo-wrap repo-nav"><a class="repo-brand" href="<%=root%>/repository"><span class="repo-brand-mark">R</span><span><strong>Repository AIS</strong><small>Workspace internal</small></span></a><nav class="repo-links" aria-label="Workspace"><a href="<%=root%>/repository">Portal publik</a><a href="<%=root%>/repository-workspace?view=deposit" <%="deposit".equals(view)?"aria-current='page'":""%>>Deposit saya</a><%if(admin){%><a href="<%=root%>/repository-workspace?view=review" <%="review".equals(view)?"aria-current='page'":""%>>Review</a><a href="<%=root%>/repository-workspace?view=admin" <%="admin".equals(view)?"aria-current='page'":""%>>Admin</a><%}%></nav></div></header>
<main id="workspace-main" class="repo-wrap repo-workspace">
<%if(flash!=null){%><div class="repo-alert repo-alert-success" role="status"><%=wh(String.valueOf(flash))%></div><%}%>
<%if(flashError!=null){%><div class="repo-alert repo-alert-error" role="alert"><%=wh(String.valueOf(flashError))%></div><%}%>

<%if("deposit".equals(view)){%>
<div class="repo-workspace-grid">
  <aside class="repo-card repo-workspace-side"><div class="repo-section-head"><div><h2>Deposit saya</h2><p><%=deposits.size()%> record</p></div><a class="repo-btn repo-btn-primary" href="<%=root%>/repository-workspace?view=deposit">Baru</a></div>
    <div class="repo-deposit-list"><%for(RepoItem d:deposits){%><a href="<%=root%>/repository-workspace?view=deposit&id=<%=d.getId()%>" <%=(item!=null&&d.getId().equals(item.getId()))?"aria-current='page'":""%>><strong><%=wh(d.getTitle().length()==0?"Draft tanpa judul":d.getTitle())%></strong><small><%=wh(d.getWorkflowStatus())%> · v<%=d.getLockVersion()%></small></a><%}%><%if(deposits.isEmpty()){%><p class="repo-muted">Belum ada deposit.</p><%}%></div>
  </aside>
  <section class="repo-workspace-main">
    <div class="repo-card repo-card-pad"><div class="repo-section-head"><div><p class="repo-eyebrow">Deposit wizard</p><h1><%=item==null?"Buat deposit baru":wh(item.getTitle().length()==0?"Lengkapi draft":item.getTitle())%></h1></div><%if(item!=null){%><span class="repo-chip"><%=wh(item.getWorkflowStatus())%></span><%}%></div>
      <ol class="repo-stepper" aria-label="Tahapan deposit"><li class="active">1 Metadata</li><li>2 Kontributor</li><li>3 Akses</li><li>4 Berkas</li><li>5 Kirim</li></ol>
      <form method="post" action="<%=root%>/repository-workspace" class="repo-workspace-form" <%=item!=null&&canEdit?"data-repo-autosave":""%>>
        <input type="hidden" name="csrf" value="<%=wh(csrf)%>"><input type="hidden" name="action" value="<%=item==null?"create":"save"%>"><%if(item!=null){%><input type="hidden" name="id" value="<%=item.getId()%>"><input type="hidden" name="version" value="<%=item.getLockVersion()%>"><%}%>
        <fieldset <%=canEdit?"":"disabled"%>><legend>Metadata utama</legend><div class="repo-form-grid">
          <label>Koleksi <span aria-hidden="true">*</span><select name="collectionId" required><option value="">Pilih koleksi</option><%for(CollectionView c:collections){%><option value="<%=c.id%>" <%=(item!=null&&c.id.equals(item.getCollectionId()))?"selected":""%>><%=wh(c.nama)%></option><%}%></select></label>
          <label>Jenis dokumen <select name="documentType"><%String[] types={"Thesis","Article","Book","Book Chapter","Research Report","Dataset","Teaching Material","Other"};for(String t:types){%><option <%=(item!=null&&t.equals(item.getDocumentType()))?"selected":""%>><%=t%></option><%}%></select></label>
          <label class="repo-field-full">Judul <span aria-hidden="true">*</span><input name="title" maxlength="4000" required value="<%=item==null?"":wh(item.getTitle())%>"></label>
          <label class="repo-field-full">Abstrak <textarea name="abstractText" rows="7" maxlength="40000"><%=item==null?"":wh(item.getAbstractText())%></textarea></label>
          <label class="repo-field-full">Subjek/kata kunci <textarea name="subjects" rows="3" placeholder="Pisahkan dengan titik koma"><%=item==null?"":wh(item.getSubjects())%></textarea></label>
          <label>Penerbit <input name="publisher" maxlength="255" value="<%=item==null?"":wh(item.getPublisher())%>"></label><label>Bahasa <select name="language"><option value="id" <%=(item==null||"id".equals(item.getLanguage()))?"selected":""%>>Indonesia</option><option value="en" <%=(item!=null&&"en".equals(item.getLanguage()))?"selected":""%>>English</option></select></label>
          <label>DOI <input name="doi" maxlength="255" placeholder="10.xxxx/xxxxx" value="<%=item==null?"":wh(item.getDoi())%>"></label>
        </div></fieldset>
        <fieldset <%=canEdit?"":"disabled"%>><legend>Kontributor</legend><div class="repo-form-grid"><label>Nama penulis—satu per baris <textarea name="authors" rows="5" required><%=item==null?"":wh(authorsForEdit(item.getAuthors()))%></textarea></label><label>ORCID sesuai urutan penulis—boleh kosong <textarea name="authorOrcids" rows="5" placeholder="0000-0002-1825-0097"><%=wh(orcids)%></textarea></label></div></fieldset>
        <fieldset <%=canEdit?"":"disabled"%>><legend>Akses, lisensi, dan embargo</legend><div class="repo-form-grid"><label>Kebijakan akses <select name="accessPolicy"><%String[] accesses={"METADATA_ONLY","OPEN_ACCESS","EMBARGOED","INSTITUTION_ONLY","AUTHENTICATED","RESTRICTED"};for(String a:accesses){%><option <%=(item!=null&&a.equals(item.getAccessPolicy()))?"selected":""%>><%=a%></option><%}%></select></label><label>Lisensi <select name="licenseUri"><option value="">Belum dipilih</option><%String[][] licenses={{"https://creativecommons.org/licenses/by/4.0/","CC BY 4.0"},{"https://creativecommons.org/licenses/by-sa/4.0/","CC BY-SA 4.0"},{"https://creativecommons.org/licenses/by-nc/4.0/","CC BY-NC 4.0"},{"https://creativecommons.org/licenses/by-nc-nd/4.0/","CC BY-NC-ND 4.0"}};for(String[] l:licenses){%><option value="<%=l[0]%>" <%=(item!=null&&l[0].equals(item.getLicenseUri()))?"selected":""%>><%=l[1]%></option><%}%></select></label><label>Akhir embargo <input type="date" name="embargoUntil" value="<%=item==null?"":wf(item.getEmbargoUntil())%>"></label></div></fieldset>
        <%if(canEdit){%><div class="repo-form-actions"><button class="repo-btn repo-btn-primary" type="submit"><%=item==null?"Buat draft":"Simpan perubahan"%></button><span class="repo-autosave-status" aria-live="polite"></span></div><%}%>
      </form>
    </div>
    <%if(item!=null){%>
    <%if(!duplicates.isEmpty()){%><div class="repo-alert repo-alert-warning"><strong>Kemungkinan duplikat:</strong><%for(DuplicateCandidate d:duplicates){%> <a href="<%=root%>/repository?view=item&id=<%=d.id%>"><%=wh(d.title)%></a><%}%></div><%}%>
    <div class="repo-card repo-card-pad"><h2>Berkas</h2><%if(canEdit){%><form method="post" enctype="multipart/form-data" action="<%=root%>/repository-workspace" class="repo-upload-form"><input type="hidden" name="csrf" value="<%=wh(csrf)%>"><input type="hidden" name="id" value="<%=item.getId()%>"><label>Pilih berkas <input type="file" name="file" required></label><label>Deskripsi <input name="description" maxlength="500"></label><label>Akses berkas <select name="fileAccess"><option>OPEN_ACCESS</option><option>RESTRICTED</option></select></label><label class="repo-check"><input type="checkbox" name="primary" value="true"> Berkas utama</label><button class="repo-btn repo-btn-primary" type="submit">Unggah</button></form><p class="repo-help">Maksimal 100 MB. Signature, MIME, checksum SHA-256, dan status pemindaian dicatat.</p><%}%>
      <div class="repo-file-list"><%for(RepoBitstream b:bitstreams){%><article><div><strong><%=wh(b.getNamaFile())%></strong><small><%=wh(b.getMimeType())%> · SHA-256 <%=wh(b.getChecksum())%> · scan <%=wh(b.getVirusScanStatus())%> · versi <%=b.getFileVersion()%></small></div><%if(canEdit){%><form method="post" action="<%=root%>/repository-workspace"><input type="hidden" name="csrf" value="<%=wh(csrf)%>"><input type="hidden" name="action" value="removeFile"><input type="hidden" name="id" value="<%=item.getId()%>"><input type="hidden" name="fileId" value="<%=b.getId()%>"><button class="repo-btn repo-btn-danger" type="submit">Hapus</button></form><%}%></article><%}%><%if(bitstreams.isEmpty()){%><p class="repo-muted">Belum ada berkas.</p><%}%></div>
    </div>
    <div class="repo-card repo-card-pad"><h2>Validasi dan pengiriman</h2><p>Pastikan metadata, lisensi, akses, dan berkas utama telah benar.</p><%if("DRAFT".equals(item.getWorkflowStatus())||"REVISION_REQUIRED".equals(item.getWorkflowStatus())){%><form method="post" action="<%=root%>/repository-workspace"><input type="hidden" name="csrf" value="<%=wh(csrf)%>"><input type="hidden" name="action" value="<%="REVISION_REQUIRED".equals(item.getWorkflowStatus())?"resubmit":"submit"%>"><input type="hidden" name="id" value="<%=item.getId()%>"><input type="hidden" name="version" value="<%=item.getLockVersion()%>"><label>Catatan untuk reviewer <textarea name="comment" rows="3"></textarea></label><button class="repo-btn repo-btn-primary" type="submit">Kirim untuk review</button></form><%}else{%><p class="repo-alert repo-alert-success">Item berada pada status <strong><%=wh(item.getWorkflowStatus())%></strong>.</p><%}%></div>
    <div class="repo-card repo-card-pad"><h2>Riwayat</h2><ol class="repo-timeline"><%for(RepoWorkflowEvent e:history){%><li><strong><%=wh(e.getAction())%></strong><span><%=wh(e.getFromStatus())%> → <%=wh(e.getToStatus())%></span><small><%=wh(e.getActorName())%> · <%=ws(e.getCreatedAt())%></small><%if(e.getCommentText()!=null&&!e.getCommentText().trim().isEmpty()){%><p><%=wh(e.getCommentText())%></p><%}%></li><%}%></ol></div>
    <%}%>
  </section>
</div>
<%}else if("review".equals(view)){%>
<section class="repo-card repo-card-pad"><div class="repo-section-head"><div><p class="repo-eyebrow">Review queue</p><h1>Antrian penelaahan</h1></div><span class="repo-chip"><%=queue.size()%> item</span></div><div class="repo-admin-table"><table><thead><tr><th>Item</th><th>Status</th><th>Pemilik</th><th>Reviewer</th><th>Aksi</th></tr></thead><tbody><%for(RepoItem q:queue){%><tr><td><strong><%=wh(q.getTitle())%></strong><small><%=wh(q.getDocumentType())%></small></td><td><%=wh(q.getWorkflowStatus())%></td><td><%=wh(q.getOwnerId())%></td><td><%=wh(q.getAssignedReviewerId())%></td><td><a class="repo-btn" href="<%=root%>/repository-workspace?view=review&id=<%=q.getId()%>">Review</a></td></tr><%}%></tbody></table></div></section>
<%if(item!=null){%><section class="repo-card repo-card-pad repo-review-panel"><h2><%=wh(item.getTitle())%></h2><p><%=wh(item.getAuthors())%></p><p><%=wh(item.getAbstractText())%></p><div class="repo-chips"><span class="repo-chip"><%=wh(item.getWorkflowStatus())%></span><span class="repo-chip"><%=wh(item.getAccessPolicy())%></span></div><form method="post" action="<%=root%>/repository-workspace" class="repo-review-actions"><input type="hidden" name="csrf" value="<%=wh(csrf)%>"><input type="hidden" name="id" value="<%=item.getId()%>"><input type="hidden" name="version" value="<%=item.getLockVersion()%>"><label>Catatan keputusan <textarea name="comment" rows="4"></textarea></label><div><%if("SUBMITTED".equals(item.getWorkflowStatus())){%><button name="action" value="claim" class="repo-btn repo-btn-primary">Claim</button><%}%><%if("IN_REVIEW".equals(item.getWorkflowStatus())){%><button name="action" value="return" class="repo-btn">Kembalikan</button><button name="action" value="reject" class="repo-btn repo-btn-danger">Tolak</button><button name="action" value="approve" class="repo-btn repo-btn-primary">Setujui</button><%}%><%if("APPROVED".equals(item.getWorkflowStatus())){%><button name="action" value="publish" class="repo-btn repo-btn-primary">Publikasikan</button><%}%><%if("PUBLISHED".equals(item.getWorkflowStatus())){%><button name="action" value="withdraw" class="repo-btn repo-btn-danger">Tarik</button><%}%><%if("WITHDRAWN".equals(item.getWorkflowStatus())){%><button name="action" value="restore" class="repo-btn repo-btn-primary">Pulihkan</button><%}%><button name="action" value="comment" class="repo-btn">Tambah komentar</button></div></form><h3>Riwayat audit</h3><ol class="repo-timeline"><%for(RepoWorkflowEvent e:history){%><li><strong><%=wh(e.getAction())%></strong><span><%=wh(e.getFromStatus())%> → <%=wh(e.getToStatus())%></span><small><%=wh(e.getActorName())%> · <%=ws(e.getCreatedAt())%></small><p><%=wh(e.getCommentText())%></p></li><%}%></ol></section><%}%>
<%}else{%>
<section class="repo-card repo-card-pad"><p class="repo-eyebrow">Administrasi</p><h1>Konfigurasi Repository</h1><p>Profil koleksi, metadata, workflow, akses, integrasi, preservasi, dan kesehatan OAI dikelola pada panel ini.</p><div class="repo-admin-cards"><article><h2>Koleksi</h2><b><%=collections.size()%></b><p>Hierarchy dan kebijakan deposit.</p></article><article><h2>Antrian review</h2><b><%=queue.size()%></b><p>Submit sampai publish.</p></article><article><h2>OAI-PMH</h2><b>6 verb</b><p><a href="<%=root%>/oai?verb=Identify">Buka Identify</a></p></article><article><h2>Preservasi</h2><b><%=bitstreams.size()%></b><p>Checksum dan malware scan.</p></article></div><p class="repo-alert repo-alert-warning">Editor profil admin typed sedang tersedia melalui model koleksi; konfigurasi rinci ditambahkan pada tahap admin berikutnya.</p></section>
<%}%>
</main><script src="<%=root%>/js/repository-modern.js"></script></body></html>
