package ais.common.newui.finance;
import java.util.ArrayList;import java.util.List;import org.hibernate.Criteria;import org.hibernate.Session;import org.hibernate.Transaction;import org.hibernate.Hibernate;import org.hibernate.criterion.MatchMode;import org.hibernate.criterion.Order;import org.hibernate.criterion.Projections;import org.hibernate.criterion.Restrictions;import ais.database.hibernate.HibernateUtil;import ais.database.model.DetailKegiatan;import ais.database.model.Fakultas;import ais.database.model.Jenjang;import ais.database.model.Jurusan;import ais.database.model.Kegiatan;import ais.database.model.Konsentrasi;import ais.database.model.Mahasiswa;import ais.database.model.Perkuliahan;import ais.database.model.StatusAwalMahasiswa;import ais.database.model.StatusMahasiswa;import ais.database.model.Tbmuser;import ais.database.model.TunggakanMahasiswa;import ais.database.model.TunggakanMahasiswaDetail;
/** Daftar, rincian biaya/terbayar, status lunas, rekap, dan hapus dari TunggakanMahasiswaAction. */
@SuppressWarnings({"rawtypes","unchecked"})public final class NewUiStudentArrearsService{
 public Snapshot load(Filter f){Session s=HibernateUtil.openSession();try{Snapshot o=new Snapshot();Number n=(Number)criteria(s,f,false).setProjection(Projections.rowCount()).uniqueResult();o.total=n==null?0:n.intValue();for(Object v:criteria(s,f,true).setFirstResult(Math.max(0,f.page)*f.size).setMaxResults(f.size).list())o.rows.add(row((TunggakanMahasiswa)v));Object[]sum=(Object[])criteria(s,f,false).setProjection(Projections.projectionList().add(Projections.sum("jumlahTunggakan")).add(Projections.count("id"))).uniqueResult();o.debt=sum==null||sum[0]==null?0:((Number)sum[0]).doubleValue();o.records=sum==null||sum[1]==null?0:((Number)sum[1]).intValue();return o;}finally{s.close();}}
 public Details details(Long id){Session s=HibernateUtil.openSession();try{TunggakanMahasiswa x=require(s,id);Details o=new Details();for(Object v:s.createCriteria(TunggakanMahasiswaDetail.class).add(Restrictions.eq("tunggakanMahasiswa",x)).addOrder(Order.asc("nama")).list()){TunggakanMahasiswaDetail d=(TunggakanMahasiswaDetail)v;o.charges.add(new Detail(d.getItemBiaya()==null?d.getNama():d.getItemBiaya().getNama(),number(d.getNilaiBiaya())));}if(x.getKegiatan()!=null)for(Object v:s.createCriteria(DetailKegiatan.class).add(Restrictions.eq("kegiatan",x.getKegiatan())).list()){DetailKegiatan d=(DetailKegiatan)v;o.payments.add(new Detail(d.getDetailBiaya()==null||d.getDetailBiaya().getItemBiaya()==null?"Pembayaran":d.getDetailBiaya().getItemBiaya().getNama(),number(d.getBiaya())));}return o;}finally{s.close();}}
 public Options options(){Session s=HibernateUtil.openSession();try{Options o=new Options();for(Object v:s.createCriteria(StatusMahasiswa.class).addOrder(Order.asc("nama")).list()){StatusMahasiswa x=(StatusMahasiswa)v;o.statuses.add(new Option(x.getId(),x.getNama(),null));}for(Object v:s.createCriteria(StatusAwalMahasiswa.class).addOrder(Order.asc("nama")).list()){StatusAwalMahasiswa x=(StatusAwalMahasiswa)v;o.initialStatuses.add(new Option(x.getId(),x.getNama(),null));}for(Object v:s.createCriteria(Fakultas.class).addOrder(Order.asc("nama")).list()){Fakultas x=(Fakultas)v;o.faculties.add(new Option(x.getId(),x.getNama(),null));}for(Object v:s.createCriteria(Jurusan.class).addOrder(Order.asc("nama")).list()){Jurusan x=(Jurusan)v;o.studyPrograms.add(new Option(x.getId(),x.getNama(),x.getFakultas()==null?null:x.getFakultas().getId()));}for(Object v:s.createCriteria(Konsentrasi.class).addOrder(Order.asc("nama")).list()){Konsentrasi x=(Konsentrasi)v;o.concentrations.add(new Option(x.getId(),x.getNama(),null));}for(Object v:s.createCriteria(Jenjang.class).addOrder(Order.asc("nama")).list()){Jenjang x=(Jenjang)v;o.levels.add(new Option(x.getId(),x.getNama(),null));}return o;}finally{s.close();}}
 public void settle(Long id,boolean value,Tbmuser user){Session s=HibernateUtil.openSession();Transaction tx=null;try{tx=s.beginTransaction();TunggakanMahasiswa x=require(s,id);if(x.getKegiatan()==null)throw new IllegalArgumentException("Tunggakan belum mempunyai transaksi pembayaran.");x.setDianggapLunas(Boolean.valueOf(value));stamp(x,user);s.update(x);s.flush();tx.commit();}catch(RuntimeException e){rollback(tx);throw e;}finally{s.close();}}
 public void delete(Long id){Session s=HibernateUtil.openSession();Transaction tx=null;try{tx=s.beginTransaction();TunggakanMahasiswa x=require(s,id);s.delete(x);s.flush();tx.commit();}catch(RuntimeException e){rollback(tx);throw e;}finally{s.close();}}
 private Criteria criteria(Session s,Filter f,boolean order){Criteria c=s.createCriteria(TunggakanMahasiswa.class,"a").add(Restrictions.ge("jumlahTunggakan",Double.valueOf(1)));if(f.studentStatusId!=null)c.add(Restrictions.sqlRestriction("mahasiswa in (select mahasiswa from history_status_mahasiswa where status_mahasiswa=? and tahunakademik=? and ganjil_genap=?)",new Object[]{f.studentStatusId,f.statusAcademicYear,f.statusSemesterOdd?Perkuliahan.GANJIL:Perkuliahan.GENAP},new org.hibernate.type.Type[]{Hibernate.LONG,Hibernate.STRING,Hibernate.STRING}));c.createAlias("mahasiswa","m").createAlias("m.jurusan","j",Criteria.LEFT_JOIN).createAlias("j.fakultas","fac",Criteria.LEFT_JOIN);if(clean(f.query)!=null)c.add(Restrictions.or(Restrictions.ilike("m.nim",clean(f.query),MatchMode.ANYWHERE),Restrictions.ilike("m.nama",clean(f.query),MatchMode.ANYWHERE)));if(f.year!=null)c.add(Restrictions.eq("m.tahunangkatan",f.year));if(clean(f.academicYear)!=null)c.add(Restrictions.eq("tahunAkademik",clean(f.academicYear)));if(f.semester!=null)c.add(Restrictions.eq("semester",f.semester));if(clean(f.program)!=null)c.add(Restrictions.eq("m.program",clean(f.program)));if(clean(f.citizenship)!=null)c.add(Restrictions.eq("m.warganegara",clean(f.citizenship)));if(f.facultyId!=null)c.add(Restrictions.eq("fac.id",f.facultyId));if(f.studyProgramId!=null)c.add(Restrictions.eq("j.id",f.studyProgramId));if(f.initialStatusId!=null)c.add(Restrictions.eq("m.statusAwalMahasiswa.id",f.initialStatusId));if(f.concentrationId!=null)c.add(Restrictions.eq("m.konsentrasi.id",f.concentrationId));if(f.levelId!=null)c.add(Restrictions.eq("j.jenjang.id",f.levelId));if(f.advisorId!=null)c.add(Restrictions.eq("m.dosen",f.advisorId));if(f.advisorMissing)c.add(Restrictions.isNull("m.dosen"));if(f.unpaidOnly)c.add(Restrictions.isNull("kegiatan"));if(f.settledOnly)c.add(Restrictions.eq("dianggapLunas",true));if(order)c.addOrder(Order.asc("m.nim")).addOrder(Order.desc("tahunAkademik")).addOrder(Order.desc("semester"));return c;}
 private Row row(TunggakanMahasiswa x){Row r=new Row();r.id=x.getId();r.academicYear=x.getTahunAkademik();r.semester=x.getSemester();r.debt=number(x.getJumlahTunggakan());r.settled=Boolean.TRUE.equals(x.getDianggapLunas());r.note=x.getKeterangan();Mahasiswa m=x.getMahasiswa();if(m!=null){r.studentId=m.getId();r.nim=m.getNim();r.name=m.getNama();r.cohort=m.getTahunangkatan();r.citizenship=m.getWarganegara();r.startSemester=m.getSemesterMulai();r.program=m.getProgram();if(m.getJurusan()!=null){r.studyProgram=m.getJurusan().getNama();if(m.getJurusan().getFakultas()!=null)r.faculty=m.getJurusan().getFakultas().getNama();}}Kegiatan k=x.getKegiatan();r.hasPayment=k!=null;if(k!=null){r.paid=number(k.getAmount());r.remaining=number(k.getAmountTerhutang());r.paidPercent=number(k.getPersentaseLunas());}else r.remaining=r.debt;return r;}
 private static TunggakanMahasiswa require(Session s,Long id){TunggakanMahasiswa x=id==null?null:(TunggakanMahasiswa)s.get(TunggakanMahasiswa.class,id);if(x==null)throw new IllegalArgumentException("Tunggakan mahasiswa tidak ditemukan.");return x;}private static void stamp(TunggakanMahasiswa x,Tbmuser u){if(u!=null){x.setOleh(u.getUserNama());x.setOlehId(u.getUserId());}}private static double number(Number n){return n==null?0:n.doubleValue();}private static String clean(String v){return v==null||v.trim().length()==0?null:v.trim();}private static void rollback(Transaction t){if(t!=null)try{t.rollback();}catch(Exception ignored){}}
 public static final class Filter{public String query,academicYear,program,citizenship,statusAcademicYear;public Integer year,semester;public Long facultyId,studyProgramId,studentStatusId,initialStatusId,concentrationId,levelId,advisorId;public boolean statusSemesterOdd,advisorMissing,unpaidOnly,settledOnly;public int page,size=20;}
 public static final class Snapshot{public int total,records;public double debt;public final List<Row>rows=new ArrayList<Row>();}
 public static final class Row{public Long id,studentId;public Integer semester,cohort;public String academicYear,nim,name,citizenship,startSemester,faculty,studyProgram,status,program,note;public double debt,remaining,paid,paidPercent;public boolean settled,hasPayment;}
 public static final class Details{public final List<Detail>charges=new ArrayList<Detail>(),payments=new ArrayList<Detail>();}
 public static final class Detail{public final String name;public final double amount;Detail(String n,double a){name=n;amount=a;}}
 public static final class Options{public final List<Option>statuses=new ArrayList<Option>(),initialStatuses=new ArrayList<Option>(),faculties=new ArrayList<Option>(),studyPrograms=new ArrayList<Option>(),concentrations=new ArrayList<Option>(),levels=new ArrayList<Option>();}
 public static final class Option{public final Long id,parentId;public final String label;Option(Long i,String l,Long p){id=i;label=l;parentId=p;}}
}

