(function(){
'use strict';
var app=document.getElementById('siApp'); if(!app)return;
var apiUrl=app.getAttribute('data-api');
var groups={master:'Master Data',stock:'Persediaan & Harga',ap:'Pembelian & Hutang',ar:'Penjualan & Piutang',trip:'Distribusi Nota Sales',finance:'Kas & Laporan'};
var screens=[
['01','Data Supplier','master','master_supplier','si_supplier_list','Identitas supplier, termin, rekening bank dan saldo hutang.'],
['02','Membuka Daftar Supplier','master','master_supplier','si_supplier_list','Cari, urutkan dan pilih supplier tanpa mengubah transaksi.'],
['03','Menutup Daftar Supplier','master','master_supplier','si_supplier_list','Detail supplier tetap aktif ketika panel daftar ditutup.'],
['04','Data Customer','master','master_customer','si_customer_list','Identitas customer, limit kredit, sales pemilik dan saldo piutang.'],
['05','Membuka Daftar Customer','master','master_customer','si_customer_list','Daftar customer dengan pencarian dan pengurutan.'],
['06','Menutup Daftar Customer','master','master_customer','si_customer_list','Menutup daftar tanpa mengubah record customer aktif.'],
['07','Data Sales / Penjual Keliling','master','master_sales','si_sales_list','Master sales, area, target, akun perkiraan dan beban penagihan.'],
['08','Data Stok Barang','stock','persediaan','si_inventory_balance','Saldo awal, masuk, keluar, stok akhir dan nilai persediaan.'],
['09','Laporan Opname','stock','persediaan','si_inventory_balance','Rekonsiliasi stok buku dan hasil hitung fisik.'],
['10','Mencetak Laporan Opname','stock','laporan_inventory_sales','si_inventory_balance','Pratinjau laporan opname siap cetak.','print'],
['11','Harga Beli dan Harga Jual','stock','harga','si_price_analysis','Analisis biaya, harga jual, margin dan kondisi stok.'],
['12','Cetak Harga Beli / Jual','stock','harga','si_price_analysis','Pilih parameter dan cetak analisis harga.','print'],
['13','Mencetak Harga Jual','stock','harga','si_customer_price_list','Daftar harga jual aktif per customer.','print'],
['14','Ekspor Harga / Stok Excel','stock','laporan_inventory_sales','si_price_analysis','Ekspor data aktif dengan filter yang sama.','export'],
['15','Mencetak Daftar Stok','stock','laporan_inventory_sales','si_inventory_balance','Laporan saldo dan nilai stok per gudang.','print'],
['16','Hasil Cetak Stok','stock','laporan_inventory_sales','si_inventory_balance','Pratinjau hasil cetak persediaan.','print'],
['17','Menu Master Harga','stock','harga','si_price_analysis','Pusat harga beli supplier dan harga jual customer.'],
['18','Master Harga Beli per Supplier','stock','harga','si_supplier_price_list','Harga beli efektif menurut supplier dan produk.'],
['19','Master Harga Jual per Customer','stock','harga','si_customer_price_list','Harga jual efektif menurut customer dan produk.'],
['20','Pembelian Barang dari Supplier','ap','pembelian_sales','si_purchase_report','Daftar pembelian supplier dan termin pembayaran.'],
['21','Tombol Hutang pada Pembelian','ap','hutang','si_payable_list','Deep-link hutang yang terbentuk dari faktur pembelian.'],
['22','Data Hutang Supplier','ap','hutang','si_payable_list','Outstanding faktur supplier dari subledger AP.'],
['23','Hutang Termasuk yang Lunas','ap','hutang','si_payable_list','Tampilkan atau sembunyikan faktur yang telah lunas.'],
['24','Pembayaran Hutang','ap','hutang','si_payable_list','Alokasi pembayaran faktur, tunai, transfer atau BG.'],
['25','Melihat Pembayaran Hutang','ap','hutang','si_payable_payment_history','Riwayat pembayaran append-only dan status dokumen.'],
['26','Mencetak Pembayaran Hutang','ap','laporan_inventory_sales','si_payable_payment_history','Voucher pembayaran hutang dan jejak cetak.','print'],
['27','Analisis Hutang','ap','hutang','si_payable_aging','Aging hutang per supplier dan bucket jatuh tempo.'],
['28','Mencetak Faktur Pembelian','ap','laporan_inventory_sales','si_purchase_report','Pratinjau faktur pembelian barang.','print'],
['29','Laporan Pembelian per Periode','ap','laporan_inventory_sales','si_purchase_report','Rekap pembelian supplier menurut periode.','print'],
['30','Menu Penjualan','ar','penjualan_sales','si_sales_order_list','Sales order lapangan dan status pemenuhan.'],
['31','Membuka Piutang dari Penjualan','ar','piutang','si_receivable_list','Piutang yang berasal dari faktur penjualan.'],
['32','Data Piutang Customer','ar','piutang','si_receivable_list','Outstanding faktur customer dari subledger AR.'],
['33','Piutang Termasuk yang Lunas','ar','piutang','si_receivable_list','Tampilkan atau sembunyikan piutang lunas.'],
['34','Pembayaran Piutang','ar','piutang','si_receivable_list','Penerimaan dan alokasi pembayaran customer.'],
['35','Melihat Pembayaran Piutang','ar','piutang','si_collection_history','Riwayat penerimaan piutang append-only.'],
['36','Mencetak Pembayaran Piutang','ar','laporan_inventory_sales','si_collection_history','Kwitansi penerimaan dan jejak cetak.','print'],
['37','Analisis Piutang per Customer','ar','piutang','si_receivable_aging_customer','Aging dan risiko piutang menurut customer.'],
['38','Analisis Piutang per Sales','ar','piutang','si_receivable_aging_sales','Aging dan beban tagih menurut sales.'],
['39','Sales Membawa Nota','trip','surat_perintah_sales','si_spj_list','Surat perintah jalan, barang dan custody nota.'],
['40','Nota Sales','trip','nota_sales','si_trip_list','Sesi nota, tagihan, biaya, setoran dan rekonsiliasi.'],
['41','Laporan Piutang','ar','laporan_inventory_sales','si_receivable_report','Rekap piutang berdasarkan periode dan status.'],
['42','Mencetak Laporan Piutang','ar','laporan_inventory_sales','si_receivable_report','Pratinjau laporan piutang siap cetak.','print'],
['43','Kas dan Jurnal','finance','kas_jurnal','si_cash_journal_list','Kas, bank, debit/kredit dan status posting jurnal.'],
['44','Membuat Perkiraan Baru','finance','kas_jurnal','si_coa_list','Chart of accounts untuk posting Inventory & Sales.'],
['45','Menu Laba / Rugi','finance','laba_rugi','si_profit_loss_params','Parameter periode dan cakupan laporan laba rugi.'],
['46','Mencetak Laba Rugi Kotor','finance','laba_rugi','si_gross_profit_report','Laba kotor penjualan berdasarkan kelompok barang.','print'],
['47','Laporan Laba / Rugi','finance','laba_rugi','si_profit_loss_report','Pendapatan, HPP, biaya dan laba bersih.'],
['48','Mencetak Laporan Laba / Rugi','finance','laporan_inventory_sales','si_profit_loss_print','Pratinjau laporan laba rugi final.','print']
];
var formConfig={
'01':{save:'si_supplier_create',id:'id',fields:[['kode','Kode Supplier','text',true],['nama','Nama Supplier','text',true],['wilayah','Wilayah'],['termin_hari','Termin (hari)','number'],['alamat','Alamat','textarea'],['telp','Telepon'],['no_rekening','No. Rekening'],['atas_nama','Atas Nama'],['bank','Bank'],['alamat_bank','Alamat Bank','textarea']]},
'04':{save:'si_customer_create',id:'anggota_id',fields:[['kode','Kode Customer','text',true],['nama','Nama Customer','text',true],['wilayah','Wilayah'],['termin_hari','Termin (hari)','number'],['alamat','Alamat','textarea'],['telp','Telepon'],['hp','Ponsel'],['limit_kredit','Limit Kredit','number'],['diskon_default_persen','Diskon Default (%)','number']]},
'07':{save:'si_sales_create',id:'id',fields:[['kode','Kode Sales','text',true],['nama','Nama Sales','text',true],['nomor_perkiraan','No. Perkiraan'],['area','Wilayah / Area'],['telepon','Ponsel'],['target_bulanan','Target Bulanan','number'],['limit_penagihan','Limit Penagihan','number'],['toko_id','ID Toko','number',true],['tbmuser_id','Akun Login']]},
'44':{save:'si_coa_save',id:'akun_id',fields:[['kode','Kode Perkiraan','text',true],['nama','Nama Perkiraan','text',true],['keterangan','Keterangan','textarea'],['debet_credit','Saldo Normal','select',true,['1','-1']],['parent_id','ID Perkiraan Induk','number']]}
};
formConfig['18']={save:'si_supplier_price_save',fields:[['supplier_id','ID Supplier','number',true],['produk_id','ID Produk','number',true],['harga','Harga Beli','number',true],['tanggal_efektif','Tanggal Efektif','date',true],['keterangan','Keterangan','textarea']]};
formConfig['19']={save:'si_customer_price_save',fields:[['anggota_id','ID Customer (kosong = umum)','number'],['produk_id','ID Produk','number',true],['harga','Harga Jual','number',true],['tanggal_efektif','Tanggal Efektif','date',true],['keterangan','Keterangan','textarea']]};
formConfig['20']={save:'kulakan_faktur_simpan',fields:[['toko_id','ID Toko (Admin)','number'],['supplier_id','ID Supplier','number'],['nomor_faktur','Nomor Faktur Supplier','text',true],['tanggal_faktur','Tanggal Faktur','date',true],['jenis_pembayaran','Pembayaran','select',true,['CASH','DP','CREDIT']],['termin_hari','Termin (hari)','number'],['dibayar_awal','Dibayar Awal / DP','number'],['total_faktur_manual','Total Faktur Setelah Diskon','number'],['keterangan','Keterangan','textarea'],['items','Item Pembelian (JSON)','json',true,null,'Contoh: [{"produk_id":10,"qty":5,"harga_beli_satuan":25000,"diskon_1_persen":10,"diskon_2_persen":2,"nomor_batch":"B2408","tanggal_expired":"2028-08-31"}]']]};
formConfig['24']={save:'si_payable_payment_create',fields:[['supplier_id','ID Supplier','number',true],['nominal','Total Pembayaran','number',true],['metode','Metode','select',true,['TUNAI','TRANSFER','GIRO']],['no_bg','No. BG'],['nama_bank','Nama Bank'],['tanggal_bg','Tanggal BG','date'],['keterangan','Keterangan','textarea'],['kode_unik','Kode Unik','auto'],['alokasi','Alokasi Faktur (JSON)','json',true,null,'Contoh: [{"faktur_id":12,"nominal":150000}]']]};
formConfig['30']={save:'si_sales_order_create',fields:[['customer_id','ID Customer','number',true],['sales_id','ID Sales','number'],['toko_id','ID Toko (Admin)','number'],['keterangan','Keterangan','textarea'],['kode_unik','Kode Unik','auto'],['items','Item Order (JSON)','json',true,null,'Contoh: [{"produk_id":10,"jumlah":2,"harga":25000}]']]};
formConfig['34']={save:'si_collection_create',fields:[['customer_id','ID Customer','number',true],['sales_id','ID Sales','number'],['nominal','Total Penerimaan','number',true],['metode','Metode','select',true,['TUNAI','TRANSFER','GIRO']],['no_bg','No. BG'],['nama_bank','Nama Bank'],['tanggal_bg','Tanggal BG','date'],['keterangan','Keterangan','textarea'],['kode_unik','Kode Unik','auto'],['alokasi','Alokasi Piutang (JSON)','json',true,null,'Contoh: [{"piutang_id":12,"nominal":150000}]']]};
formConfig['39']={save:'si_spj_create',fields:[['sales_id','ID Sales','number'],['toko_id','ID Toko (Admin)','number'],['tanggal_berangkat_rencana','Tanggal Berangkat','date',true],['rute','Rute'],['kendaraan','Kendaraan'],['uang_muka_operasional','Uang Muka','number'],['catatan','Catatan','textarea'],['kode_unik','Kode Unik','auto'],['barang','Barang Dibawa (JSON)','json',true,null,'Contoh: [{"produk_id":10,"qty_rencana":5}]']]};
var columns={master:[['kode','Kode'],['nama','Nama'],['wilayah','Wilayah'],['terminHari','Termin'],['telp','Telepon'],['aktif','Status']],stock:[['kode','Kode'],['nama','Barang'],['satuan','Sat'],['hargaBeli','Harga Beli'],['awal','Awal'],['masuk','Masuk'],['keluar','Keluar'],['akhir','Akhir'],['nilai','Nilai']],ap:[['nomorFaktur','No. Faktur'],['supplierNama','Supplier'],['tanggal','Tanggal'],['jatuhTempo','Jatuh Tempo'],['total','Total'],['dibayar','Dibayar'],['outstanding','Sisa'],['statusDok','Status']],ar:[['nomorFaktur','No. Faktur'],['customerNama','Customer'],['salesNama','Sales'],['tanggal','Tanggal'],['jatuhTempo','Jatuh Tempo'],['total','Total'],['outstanding','Sisa'],['status','Status']],trip:[['nomor','Nomor'],['salesNama','Sales'],['tanggal','Tanggal'],['status','Status'],['totalNota','Nota'],['totalBarang','Barang'],['totalSetoran','Setoran']],finance:[['tanggal','Tanggal'],['nomor','Nomor'],['kodeAkun','Akun'],['namaAkun','Nama Akun'],['keterangan','Keterangan'],['debit','Debit'],['kredit','Kredit'],['status','Status']]};
var state={screen:screens[0],page:1,rows:[],raw:null,selected:null};
var activeSpec=null;
var field=function(n,l,t,r,o,h){return[n,l,t||'text',!!r,o||null,h||'']};
var workflows={
master:[
 {label:'Ubah record',desc:'Buka data terpilih dalam form edit.',local:'edit'},
 {label:'Nonaktifkan / Aktifkan',desc:'Tidak menghapus histori; alasan audit wajib.',action:'deactivate',danger:true,fields:[field('aktif','Status Baru','select',true,['false','true']),field('alasan','Alasan','textarea',true)]}
],stock:[{label:'Kartu stok',desc:'Lihat seluruh mutasi produk terpilih.',action:'si_inventory_ledger',detail:true,fields:[field('produk_id','ID Produk','number',true)]}],
ap:[
 {label:'Atur termin faktur',desc:'Tunai, DP, atau kredit dan jatuh tempo.',action:'si_purchase_terms_save',fields:[field('faktur_id','ID Faktur','number',true),field('jenis_pembayaran','Jenis','select',true,['CASH','DP','CREDIT']),field('termin_hari','Termin Hari','number'),field('dibayar_awal','Dibayar Awal','number'),field('keterangan','Keterangan','textarea')]},
 {label:'Bayar hutang',desc:'Alokasi pembayaran idempoten ke faktur.',local:'create24'},
 {label:'Lihat voucher',desc:'Ambil data voucher pembayaran.',action:'si_payable_payment_receipt',detail:true,fields:[field('id','ID Pembayaran','number',true)]},
 {label:'Reversal pembayaran',desc:'Dokumen posted dibalik, tidak dihapus.',action:'si_payable_payment_reverse',danger:true,fields:[field('pembayaran_id','ID Pembayaran','number',true),field('alasan','Alasan Reversal','textarea',true)]},
 {label:'BG Cair / Tolak',desc:'TOLAK menerbitkan reversal otomatis.',action:'si_payable_bg_status',fields:[field('id','ID Pembayaran','number',true),field('status_bg','Status BG','select',true,['CAIR','TOLAK']),field('alasan','Alasan','textarea')]}
],
ar:[
 {label:'Terima piutang',desc:'Alokasi penerimaan idempoten ke faktur.',local:'create34'},
 {label:'Lihat kwitansi',desc:'Ambil data kwitansi penerimaan.',action:'si_collection_receipt',detail:true,fields:[field('penerimaan_id','ID Penerimaan','number',true)]},
 {label:'Reversal penerimaan',desc:'Dokumen posted dibalik, saldo dipulihkan.',action:'si_collection_reverse',danger:true,fields:[field('penerimaan_id','ID Penerimaan','number',true),field('alasan','Alasan Reversal','textarea',true)]},
 {label:'BG Cair / Tolak',desc:'TOLAK menerbitkan reversal otomatis.',action:'si_collection_bg_status',fields:[field('id','ID Penerimaan','number',true),field('status_bg','Status BG','select',true,['CAIR','TOLAK']),field('alasan','Alasan','textarea')]},
 {label:'Ubah status Sales Order',desc:'DRAFT → PESAN → SIAP_KIRIM → TERKIRIM atau BATAL.',action:'si_sales_order_status',fields:[field('order_id','ID Sales Order','number',true),field('status','Status','select',true,['PESAN','SIAP_KIRIM','TERKIRIM','BATAL']),field('alasan','Alasan','textarea')]},
 {label:'Terbitkan faktur',desc:'Membuat faktur piutang secara idempoten.',action:'si_sales_order_invoice',fields:[field('order_id','ID Sales Order','number',true),field('termin_hari','Termin Hari','number')]}
],
trip:[
 {label:'Ubah status SPJ',desc:'Ajukan, setujui, atau batalkan SPJ.',action:'si_spj_status',fields:[field('spj_id','ID SPJ','number',true),field('status','Status','select',true,['SUBMITTED','APPROVED','CANCELLED']),field('alasan','Alasan','textarea')]},
 {label:'Atur nota SPJ',desc:'Tetapkan daftar piutang yang dibawa.',action:'si_spj_nota_assign',fields:[field('spj_id','ID SPJ','number',true),field('piutang_doc_ids','ID Piutang (JSON)','json',true,null,'Contoh: [12,13,14]')]},
 {label:'Mulai perjalanan',desc:'Membuat sesi Nota Sales dari SPJ approved.',action:'si_trip_start',fields:[field('spj_id','ID SPJ','number',true)]},
 {label:'Hasil kunjungan nota',desc:'Catat hasil tagihan sesuai status nota server.',action:'si_trip_nota_result',fields:[field('nota_id','ID Nota Sesi','number',true),field('status','Status','select',true,['UNPAID','PROMISE','PARTIAL','PAID','RETURNED','DISPUTED','LOST']),field('hasil_kunjungan','Hasil Kunjungan','textarea'),field('janji_bayar','Tanggal Janji Bayar','date'),field('alasan_gagal','Alasan Gagal','textarea')]},
 {label:'Update barang sesi',desc:'Rekonsiliasi terjual, kembali, rusak, hilang.',action:'si_trip_barang_update',fields:[field('rows','Baris Barang (JSON)','json',true,null,'[{"barang_id":1,"qty_terjual":2,"qty_kembali":3,"qty_rusak":0,"qty_hilang":0,"alasan_selisih":""}]')]},
 {label:'Penjualan tunai',desc:'Tambahkan penerimaan kas sesi.',action:'si_trip_cash_sale',fields:[field('session_id','ID Sesi','number',true),field('nominal','Nominal','number',true),field('referensi','Referensi'),field('keterangan','Keterangan','textarea')]},
 {label:'Setoran ke pemilik',desc:'Catat kas yang disetorkan.',action:'si_trip_deposit',fields:[field('session_id','ID Sesi','number',true),field('nominal','Nominal','number',true),field('referensi','Referensi'),field('keterangan','Keterangan','textarea')]},
 {label:'Daftar kategori biaya',desc:'Lihat kategori biaya aktif sebelum mencatat biaya.',action:'si_expense_category_list',detail:true,fields:[]},
 {label:'Kelola kategori biaya',desc:'Tambah atau aktif/nonaktifkan kategori (Pemilik/Admin).',action:'si_expense_category_save',fields:[field('kode','Kode Kategori','text',true),field('nama','Nama Kategori','text',true),field('aktif','Aktif','select',true,['true','false'])]},
 {label:'Catat biaya',desc:'Biaya sales append-only.',action:'si_expense_create',fields:[field('session_id','ID Sesi','number',true),field('kategori_id','ID Kategori','number',true),field('nilai','Nilai','number',true),field('uraian','Uraian','textarea'),field('penerima','Penerima'),field('metode','Metode','select',true,['TUNAI','TRANSFER']),field('nomor_bukti','Nomor Bukti'),field('kode_unik','Kode Unik','auto')]},
 {label:'Reversal biaya',desc:'Hanya non-sales; sesi CLOSED ditolak server.',action:'si_expense_reverse',danger:true,fields:[field('biaya_id','ID Biaya','number',true),field('alasan','Alasan Reversal','textarea',true)]},
 {label:'Catat pembelian sesi',desc:'Hubungkan pembelian supplier ke sesi.',action:'si_trip_purchase_link',fields:[field('session_id','ID Sesi','number',true),field('faktur_id','ID Faktur (opsional)','number'),field('supplier_id','ID Supplier','number'),field('total','Total Pembelian','number',true),field('dibayar','Dibayar','number'),field('tujuan_stok','Tujuan Stok','select',true,['MOBIL_SALES','GUDANG']),field('keterangan','Keterangan','textarea'),field('kode_unik','Kode Unik','auto')]},
 {label:'Sales kembali',desc:'Ubah sesi menjadi RETURNED.',action:'si_trip_return',fields:[field('session_id','ID Sesi','number',true)]},
 {label:'Rekonsiliasi sesi',desc:'Validasi barang, nota, dan kas.',action:'si_trip_reconcile',fields:[field('session_id','ID Sesi','number',true)]},
 {label:'Tutup sesi',desc:'Approval Pemilik/Admin dan kas fisik.',action:'si_trip_close',fields:[field('session_id','ID Sesi','number',true),field('kas_fisik_aktual','Kas Fisik Aktual','number',true),field('catatan','Catatan Penutupan','textarea')]}
],
finance:[{label:'Tambah / ubah perkiraan',desc:'Kelola chart of accounts.',local:'create44'},{label:'Riwayat audit',desc:'Lihat jejak perubahan transaksi.',action:'si_audit_history',detail:true,fields:[field('entity_type','Jenis Entitas'),field('entity_id','ID Entitas','number')]},{label:'Riwayat cetak',desc:'Daftar append-only khusus Pemilik/Admin.',local:'printHistory'}]
};
var $=function(id){return document.getElementById(id)};
function money(v){var n=Number(v);return isFinite(n)?new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(n):String(v==null?'':v)}
function isMoneyKey(k){return /(harga|nilai|total|saldo|nominal|outstanding|debit|kredit|limit|target|dibayar|hpp|laba|rugi)/i.test(k)&&!/(nota|barang|jumlah|qty)/i.test(k)}
function getValue(row,key){if(row[key]!==undefined)return row[key];var camel=key.replace(/_([a-z])/g,function(_,c){return c.toUpperCase()});if(row[camel]!==undefined)return row[camel];var lower=key.toLowerCase();for(var k in row)if(k.toLowerCase()===lower)return row[k];return ''}
function labelKey(k){return k.replace(/([A-Z])/g,' $1').replace(/_/g,' ').replace(/^./,function(c){return c.toUpperCase()})}
function detectRows(json){if(Array.isArray(json.data))return json.data;if(json.data&&typeof json.data==='object')return [json.data];var preferred=['items','rows','list','laporan','jurnal','aging','detail'];for(var i=0;i<preferred.length;i++)if(Array.isArray(json[preferred[i]]))return json[preferred[i]];for(var k in json)if(Array.isArray(json[k]))return json[k];return []}
async function call(action,payload){var body=Object.assign({action:action},payload||{});var res=await fetch(apiUrl,{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json','X-Requested-With':'XMLHttpRequest'},body:JSON.stringify(body)});var json;try{json=await res.json()}catch(e){throw new Error('Balasan server tidak valid (HTTP '+res.status+').')}if(!res.ok||json.status!=='success')throw new Error(json.message||'Permintaan tidak dapat diproses.');return json}
function renderNav(){var nav=$('siNavigation');nav.innerHTML='';Object.keys(groups).forEach(function(g){var wrap=document.createElement('section');wrap.className='si-nav-group';var h=document.createElement('button');h.textContent=groups[g];wrap.appendChild(h);screens.filter(function(s){return s[2]===g}).forEach(function(s){var a=document.createElement('a');a.href='#screen='+s[0];a.className='si-nav-item'+(state.screen[0]===s[0]?' active':'');a.setAttribute('data-screen',s[0]);a.innerHTML='<b>'+s[0]+'</b><span>'+s[1]+'</span>';wrap.appendChild(a)});nav.appendChild(wrap)})}
function filteredScreens(q){q=(q||'').toLowerCase();document.querySelectorAll('.si-nav-item').forEach(function(a){a.style.display=!q||a.textContent.toLowerCase().indexOf(q)>=0?'flex':'none'})}
function screenFromHash(){var m=location.hash.match(/screen=(\d{1,2})/);var no=m?('0'+m[1]).slice(-2):(app.getAttribute('data-initial')||'01');return screens.filter(function(s){return s[0]===no})[0]||screens[0]}
function dateDefaults(){var now=new Date(),from=new Date(now.getFullYear(),now.getMonth(),1);$('siDateFrom').value=from.toISOString().slice(0,10);$('siDateTo').value=now.toISOString().slice(0,10)}
function setScreen(s){state.screen=s;state.page=1;state.selected=null;$('siNumber').textContent='LAYAR '+s[0]+' / 48';$('siTitle').textContent=s[1];$('siBreadcrumb').textContent=s[1];$('siDescription').textContent=s[5];$('siCreate').disabled=!formConfig[s[0]];$('siCreate').innerHTML='<i class="fas fa-plus"></i> '+(s[0]==='20'?'Pembelian Baru':s[0]==='30'?'Order Baru':'Tambah');$('siCreate').title=formConfig[s[0]]?'Tambah data baru':'Layar ini menggunakan alur transaksi/approval khusus';$('siPrint').style.display=s[6]==='print'?'inline-block':'none';$('siExport').style.display=s[6]==='export'?'inline-block':'none';renderNav();load()}
function payload(){var f=$('siFilter').value,dari=$('siDateFrom').value,sampai=$('siDateTo').value;return {keyword:$('siKeyword').value.trim(),aktif:(f==='aktif'||f==='nonaktif')?f:undefined,status:(f==='open'||f==='lunas')?f:undefined,termasuk_lunas:(state.screen[0]==='23'||state.screen[0]==='33'||f==='lunas'),tanggal_awal:dari,tanggal_akhir:sampai,dari:dari,sampai:sampai,page:state.page,page_size:50}}
async function load(){var s=state.screen;$('siLoading').hidden=false;$('siEmpty').hidden=true;$('siNotice').hidden=true;$('siRows').innerHTML='';try{var json=await call(s[4],payload());state.raw=json;state.rows=detectRows(json);renderTable();$('siStatus').textContent='Tersambung';$('siTotal').textContent=String(json.total!==undefined?json.total:state.rows.length);$('siCount').textContent=(json.total!==undefined?json.total:state.rows.length)+' data';$('siPage').textContent=state.page;var totalNominal=0;state.rows.forEach(function(r){for(var k in r)if(isMoneyKey(k)&&/^(total|nilai|outstanding|saldo|nominal|debit)$/i.test(k))totalNominal+=Number(r[k])||0});$('siNominal').textContent=money(totalNominal);if(!state.rows.length)$('siEmpty').hidden=false}catch(e){state.rows=[];renderTable();$('siStatus').textContent='Perlu perhatian';$('siNotice').textContent=e.message;$('siNotice').hidden=false;$('siEmpty').hidden=false}finally{$('siLoading').hidden=true}}
function activeColumns(){var base=columns[state.screen[2]]||[];if(!state.rows.length)return base;var keys=Object.keys(state.rows[0]).filter(function(k){return typeof state.rows[0][k]!=='object'});var chosen=base.filter(function(c){return getValue(state.rows[0],c[0])!==''});if(chosen.length<3)chosen=keys.slice(0,9).map(function(k){return [k,labelKey(k)]});return chosen}
function renderTable(){var cols=activeColumns(),head=$('siHead'),body=$('siRows');head.innerHTML='';body.innerHTML='';var tr=document.createElement('tr');cols.forEach(function(c){var th=document.createElement('th');th.textContent=c[1];tr.appendChild(th)});head.appendChild(tr);state.rows.forEach(function(row,idx){var r=document.createElement('tr');r.tabIndex=0;r.addEventListener('click',function(){document.querySelectorAll('.si-table tbody tr').forEach(function(x){x.classList.remove('selected')});r.classList.add('selected');state.selected=row});r.addEventListener('dblclick',showDetail);cols.forEach(function(c){var td=document.createElement('td'),v=getValue(row,c[0]);if(typeof v==='boolean'){var b=document.createElement('span');b.className='si-badge'+(v?'':' off');b.textContent=v?'Aktif':'Nonaktif';td.appendChild(b)}else td.textContent=isMoneyKey(c[0])&&v!==''?money(v):(v==null?'':String(v));td.title=td.textContent;r.appendChild(td)});body.appendChild(r)})}
function toast(msg,error){var t=$('siToast');t.textContent=msg;t.className='si-toast'+(error?' error':'');t.hidden=false;setTimeout(function(){t.hidden=true},4200)}
function makeField(f,row){var wrap=document.createElement('div');wrap.className='si-field'+((f[2]==='textarea'||f[2]==='json')?' si-field-wide':'');var label=document.createElement('label');label.textContent=f[1]+(f[3]?' *':'');var input;if(f[2]==='select'){input=document.createElement('select');(f[4]||[]).forEach(function(v){var o=document.createElement('option');o.value=v;o.textContent=v;input.appendChild(o)})}else input=document.createElement((f[2]==='textarea'||f[2]==='json')?'textarea':'input');input.name=f[0];input.dataset.type=f[2]||'text';if(['number','date'].indexOf(f[2])>=0)input.type=f[2];if(f[3])input.required=true;var camel=f[0].replace(/_([a-z])/g,function(_,c){return c.toUpperCase()});var val=row?(row[f[0]]!==undefined?row[f[0]]:row[camel]):'';if(f[2]==='auto'&&!val)val='JSP-'+Date.now()+'-'+Math.floor(Math.random()*10000);if((f[2]==='json')&&val&&typeof val!=='string')val=JSON.stringify(val,null,2);input.value=val==null?'':val;wrap.appendChild(label);wrap.appendChild(input);if(f[5]){var help=document.createElement('div');help.className='si-field-help';help.textContent=f[5];wrap.appendChild(help)}return wrap}
function openForm(row){activeSpec=null;var cfg=formConfig[state.screen[0]];if(!cfg)return;row=row||null;$('siModalTitle').textContent=(row?'Ubah ':'Tambah ')+state.screen[1];var fields=$('siFormFields');fields.className='si-form-grid';fields.innerHTML='';cfg.fields.forEach(function(f){fields.appendChild(makeField(f,row))});$('siForm').dataset.edit=row?'1':'0';$('siForm').dataset.row=JSON.stringify(row||{});$('siForm').querySelector('footer').style.display='flex';$('siModal').hidden=false}
function closeForm(){$('siModal').hidden=true;activeSpec=null}
function rowValue(name){var r=state.selected||{};var camel=name.replace(/_([a-z])/g,function(_,c){return c.toUpperCase()});var map={produk_id:['produkId','id'],faktur_id:['fakturId','id'],pembayaran_id:['id'],penerimaan_id:['id'],order_id:['orderId','id'],spj_id:['spjId','id'],session_id:['sessionId','id'],nota_id:['notaId','id'],biaya_id:['biayaId','id'],supplier_id:['supplierId','id'],customer_id:['customerId','anggotaId','id'],akun_id:['akunId','id']};if(r[name]!==undefined)return r[name];if(r[camel]!==undefined)return r[camel];var a=map[name]||[];for(var i=0;i<a.length;i++)if(r[a[i]]!==undefined)return r[a[i]];return ''}
function openOperation(spec){activeSpec=spec;$('siModalTitle').textContent=spec.label;var box=$('siFormFields');box.className='si-form-grid';box.innerHTML='';(spec.fields||[]).forEach(function(f){var seed={};seed[f[0]]=rowValue(f[0]);box.appendChild(makeField(f,seed))});$('siForm').dataset.edit='0';$('siForm').dataset.row='{}';$('siForm').querySelector('footer').style.display='flex';$('siModal').hidden=false}
function actionsForScreen(){var list=(workflows[state.screen[2]]||[]).slice();if(state.screen[0]==='40')list=workflows.trip.slice(3);if(state.screen[0]==='39')list=workflows.trip.slice(0,3);if(state.screen[0]!=='30')list=list.filter(function(x){return x.action!=='si_sales_order_status'&&x.action!=='si_sales_order_invoice'});if(state.screen[0]!=='25'&&state.screen[0]!=='26')list=list.filter(function(x){return x.action!=='si_payable_payment_receipt'&&x.action!=='si_payable_payment_reverse'&&x.action!=='si_payable_bg_status'});if(state.screen[0]!=='35'&&state.screen[0]!=='36')list=list.filter(function(x){return x.action!=='si_collection_receipt'&&x.action!=='si_collection_reverse'&&x.action!=='si_collection_bg_status'});return list}
function openWorkflow(){var list=actionsForScreen();activeSpec=null;$('siModalTitle').textContent='Aksi · '+state.screen[1];var box=$('siFormFields');box.className='si-action-grid';box.innerHTML='';if(!list.length)box.innerHTML='<div class="si-notice">Tidak ada aksi mutasi pada layar baca-saja ini.</div>';list.forEach(function(spec){var b=document.createElement('button');b.type='button';b.className='si-action-card'+(spec.danger?' si-danger':'');b.innerHTML='<strong>'+spec.label+'</strong><small>'+spec.desc+'</small>';b.onclick=function(){if(spec.local==='edit')return editSelected();if(spec.local==='create24'){closeForm();return openFormFor('24')}if(spec.local==='create34'){closeForm();return openFormFor('34')}if(spec.local==='create44'){closeForm();return openFormFor('44')}if(spec.local==='printHistory')return showPrintHistory();openOperation(spec)};box.appendChild(b)});$('siForm').querySelector('footer').style.display='none';$('siModal').hidden=false}
function openFormFor(no){var cfg=formConfig[no],screen=screens.filter(function(s){return s[0]===no})[0];if(!cfg)return;openOperation({label:'Tambah '+screen[1],action:cfg.save,fields:cfg.fields,create:true})}
function detailEndpoint(){var n=state.screen[0];if(['01','02','03'].indexOf(n)>=0)return['si_supplier_detail',{id:rowValue('id')}];if(['04','05','06'].indexOf(n)>=0)return['si_customer_detail',{anggota_id:rowValue('customer_id')}];if(n==='07')return['si_sales_detail',{id:rowValue('id')}];if(n==='30')return['si_sales_order_detail',{order_id:rowValue('order_id')}];if(n==='39')return['si_spj_detail',{spj_id:rowValue('spj_id')}];if(n==='40')return['si_trip_detail',{session_id:rowValue('session_id')}];return null}
function renderObject(obj,title){activeSpec=null;$('siModalTitle').textContent=title||'Detail';var box=$('siFormFields');box.className='si-detail-grid';box.innerHTML='';for(var k in obj){var v=obj[k],d=document.createElement('div');if(v&&typeof v==='object')d.className='si-field-wide';d.innerHTML='<span>'+labelKey(k)+'</span><strong></strong>';d.querySelector('strong').textContent=v&&typeof v==='object'?JSON.stringify(v,null,2):String(v==null?'—':v);box.appendChild(d)}$('siForm').querySelector('footer').style.display='none';$('siModal').hidden=false}
async function showDetail(){if(!state.selected)return toast('Pilih satu baris terlebih dahulu.',true);var ep=detailEndpoint();if(!ep)return renderObject(state.selected,'Detail · '+state.screen[1]);try{var j=await call(ep[0],ep[1]);renderObject(j.data||j,'Detail · '+state.screen[1])}catch(e){toast(e.message,true)}}
async function editSelected(){if(!state.selected)return toast('Pilih satu baris terlebih dahulu.',true);var n=state.screen[0],target=['01','02','03'].indexOf(n)>=0?'01':['04','05','06'].indexOf(n)>=0?'04':n,cfg=formConfig[target];if(!cfg)return toast('Layar ini tidak memiliki form edit.',true);var ep=detailEndpoint();try{var row=state.selected;if(ep){var j=await call(ep[0],ep[1]);row=j.data||row}activeSpec={label:'Ubah '+state.screen[1],action:cfg.save.replace('_create','_update'),fields:cfg.fields,edit:true,id:cfg.id,row:row};$('siModalTitle').textContent=activeSpec.label;var box=$('siFormFields');box.className='si-form-grid';box.innerHTML='';cfg.fields.forEach(function(f){box.appendChild(makeField(f,row))});$('siForm').dataset.edit='1';$('siForm').dataset.row=JSON.stringify(row);$('siForm').querySelector('footer').style.display='flex';$('siModal').hidden=false}catch(e){toast(e.message,true)}}
async function showPrintHistory(){try{var j=await call('si_print_log_list',{});renderObject({riwayat:j.rows||j.data||[]},'Riwayat Cetak · Pemilik/Admin')}catch(e){toast(e.message,true)}}
async function submitForm(e){e.preventDefault();var cfg=activeSpec||formConfig[state.screen[0]],fd=new FormData(e.target),data={},invalid='';fd.forEach(function(v,k){var el=e.target.elements[k],type=el&&el.dataset?el.dataset.type:'';if(v==='')return;try{if(type==='json')data[k]=JSON.parse(v);else if(type==='number')data[k]=Number(v);else if(type==='select'&&(v==='true'||v==='false'))data[k]=v==='true';else data[k]=v}catch(ex){invalid='JSON pada '+k+' tidak valid.'}});if(invalid)return toast(invalid,true);if(activeSpec){var spec=activeSpec,action=spec.action;if(spec.edit&&spec.id){var old=spec.row||{},id=old[spec.id]!==undefined?old[spec.id]:(spec.id==='anggota_id'?old.anggotaId:old.id);data[spec.id]=id}if(action==='deactivate'){var n=state.screen[0],supplier=['01','02','03'].indexOf(n)>=0,customer=['04','05','06'].indexOf(n)>=0;action=supplier?'si_supplier_deactivate':customer?'si_customer_deactivate':'si_sales_deactivate';if(supplier||n==='07')data.id=rowValue('id');else data.anggota_id=rowValue('customer_id')}try{var result=await call(action,data);if(spec.detail)return renderObject(result.data||result.rows||result,spec.label);closeForm();toast(spec.create||spec.edit?'Data berhasil disimpan.':'Aksi berhasil diproses.');load()}catch(err){toast(err.message,true)}return}var old2=JSON.parse(e.target.dataset.row||'{}'),editing=e.target.dataset.edit==='1';if(editing&&cfg.id){var id2=old2[cfg.id]!==undefined?old2[cfg.id]:(cfg.id==='anggota_id'?old2.anggotaId:old2.id);data[cfg.id]=id2}var action2=cfg.save;if(editing)action2=action2.replace('_create','_update');try{await call(action2,data);closeForm();toast('Data berhasil disimpan.');load()}catch(err2){toast(err2.message,true)}}
function csv(){if(!state.rows.length)return toast('Tidak ada data untuk diekspor.',true);var keys=Object.keys(state.rows[0]).filter(function(k){return typeof state.rows[0][k]!=='object'}),lines=[keys.join(',')];state.rows.forEach(function(r){lines.push(keys.map(function(k){return '"'+String(r[k]==null?'':r[k]).replace(/"/g,'""')+'"'}).join(','))});var blob=new Blob(['\ufeff'+lines.join('\r\n')],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='inventory-layar-'+state.screen[0]+'-'+new Date().toISOString().slice(0,10)+'.csv';a.click();setTimeout(function(){URL.revokeObjectURL(a.href)},1000)}
function printView(){window.print();call('si_print_log_create',{jenis_dokumen:'LAYAR_'+state.screen[0],referensi:state.screen[1],parameter:JSON.stringify(Object.assign(payload(),{jumlah_baris:state.rows.length})),perangkat:'JSP Inventory'}).catch(function(){})}
window.addEventListener('hashchange',function(){setScreen(screenFromHash())});window.addEventListener('online',function(){$('siOnline').classList.remove('offline');$('siOnline').innerHTML='<i class="fas fa-circle"></i> Online'});window.addEventListener('offline',function(){$('siOnline').classList.add('offline');$('siOnline').innerHTML='<i class="fas fa-circle"></i> Offline'});
$('siMenuSearch').addEventListener('input',function(){filteredScreens(this.value)});$('siKeyword').addEventListener('keydown',function(e){if(e.key==='Enter'){state.page=1;load()}});$('siFilter').addEventListener('change',load);$('siRefresh').addEventListener('click',load);$('siCreate').addEventListener('click',function(){openForm(null)});$('siDetail').addEventListener('click',showDetail);$('siWorkflow').addEventListener('click',openWorkflow);$('siPrintHistory').addEventListener('click',showPrintHistory);$('siExport').addEventListener('click',csv);$('siPrint').addEventListener('click',printView);$('siPrev').addEventListener('click',function(){if(state.page>1){state.page--;load()}});$('siNext').addEventListener('click',function(){if(state.rows.length){state.page++;load()}});$('siModalClose').addEventListener('click',closeForm);$('siCancel').addEventListener('click',closeForm);$('siModal').addEventListener('click',function(e){if(e.target===this)closeForm()});$('siForm').addEventListener('submit',submitForm);$('siOpenNav').addEventListener('click',function(){$('siSidebar').classList.add('open')});$('siCloseNav').addEventListener('click',function(){$('siSidebar').classList.remove('open')});$('siNavigation').addEventListener('click',function(){$('siSidebar').classList.remove('open')});
dateDefaults();setScreen(screenFromHash());
})();
