(function(){
'use strict';
var app=document.getElementById('siApp'); if(!app)return;
var apiUrl=app.getAttribute('data-api');
var groups={master:'Master Data',stock:'Persediaan & Harga',ap:'Pembelian & Hutang',ar:'Penjualan & Piutang',trip:'Distribusi Nota Sales',finance:'Kas & Laporan'};
var screens=[
['01','Data Supplier','master','master_supplier','si_supplier_list','Identitas supplier, termin, rekening bank dan saldo hutang.'],
['02','Membuka Daftar Supplier','master','master_supplier','si_supplier_list','Cari, urutkan dan pilih supplier tanpa mengubah transaksi.'],
['03','Menutup Daftar Supplier','master','master_supplier','si_supplier_list','Detail supplier tetap aktif ketika panel daftar ditutup.'],
['04','Data Customer','master','master_customer','si_customer_list','Identitas customer, limit kredit, sales pemilik dan saldo piutang.'],
['05','Membuka Daftar Customer','master','master_customer','si_customer_list','Daftar customer dengan pencarian dan pengurutan.'],
['06','Menutup Daftar Customer','master','master_customer','si_customer_list','Menutup daftar tanpa mengubah record customer aktif.'],
['07','Data Sales / Penjual Keliling','master','master_sales','si_sales_list','Master sales, area, target, akun perkiraan dan beban penagihan.'],
['08','Data Stok Barang','stock','persediaan','si_inventory_balance','Saldo awal, masuk, keluar, stok akhir dan nilai persediaan.'],
['09','Laporan Opname','stock','persediaan','si_inventory_balance','Rekonsiliasi stok buku dan hasil hitung fisik.'],
['10','Mencetak Laporan Opname','stock','laporan_inventory_sales','si_inventory_balance','Pratinjau laporan opname siap cetak.','print'],
['11','Harga Beli dan Harga Jual','stock','harga','si_price_analysis','Analisis biaya, harga jual, margin dan kondisi stok.'],
['12','Cetak Harga Beli / Jual','stock','harga','si_price_analysis','Pilih parameter dan cetak analisis harga.','print'],
['13','Mencetak Harga Jual','stock','harga','si_customer_price_list','Daftar harga jual aktif per customer.','print'],
['14','Ekspor Harga / Stok Excel','stock','laporan_inventory_sales','si_price_analysis','Ekspor data aktif dengan filter yang sama.','export'],
['15','Mencetak Daftar Stok','stock','laporan_inventory_sales','si_inventory_balance','Laporan saldo dan nilai stok per gudang.','print'],
['16','Hasil Cetak Stok','stock','laporan_inventory_sales','si_inventory_balance','Pratinjau hasil cetak persediaan.','print'],
['17','Menu Master Harga','stock','harga','si_price_analysis','Pusat harga beli supplier dan harga jual customer.'],
['18','Master Harga Beli per Supplier','stock','harga','si_supplier_price_list','Harga beli efektif menurut supplier dan produk.'],
['19','Master Harga Jual per Customer','stock','harga','si_customer_price_list','Harga jual efektif menurut customer dan produk.'],
['20','Pembelian Barang dari Supplier','ap','pembelian_sales','si_purchase_report','Daftar pembelian supplier dan termin pembayaran.'],
['21','Tombol Hutang pada Pembelian','ap','hutang','si_payable_list','Deep-link hutang yang terbentuk dari faktur pembelian.'],
['22','Data Hutang Supplier','ap','hutang','si_payable_list','Outstanding faktur supplier dari subledger AP.'],
['23','Hutang Termasuk yang Lunas','ap','hutang','si_payable_list','Tampilkan atau sembunyikan faktur yang telah lunas.'],
['24','Pembayaran Hutang','ap','hutang','si_payable_list','Alokasi pembayaran faktur, tunai, transfer atau BG.'],
['25','Melihat Pembayaran Hutang','ap','hutang','si_payable_payment_history','Riwayat pembayaran append-only dan status dokumen.'],
['26','Mencetak Pembayaran Hutang','ap','laporan_inventory_sales','si_payable_payment_history','Voucher pembayaran hutang dan jejak cetak.','print'],
['27','Analisis Hutang','ap','hutang','si_payable_aging','Aging hutang per supplier dan bucket jatuh tempo.'],
['28','Mencetak Faktur Pembelian','ap','laporan_inventory_sales','si_purchase_report','Pratinjau faktur pembelian barang.','print'],
['29','Laporan Pembelian per Periode','ap','laporan_inventory_sales','si_purchase_report','Rekap pembelian supplier menurut periode.','print'],
['30','Menu Penjualan','ar','penjualan_sales','si_sales_order_list','Sales order lapangan dan status pemenuhan.'],
['31','Membuka Piutang dari Penjualan','ar','piutang','si_receivable_list','Piutang yang berasal dari faktur penjualan.'],
['32','Data Piutang Customer','ar','piutang','si_receivable_list','Outstanding faktur customer dari subledger AR.'],
['33','Piutang Termasuk yang Lunas','ar','piutang','si_receivable_list','Tampilkan atau sembunyikan piutang lunas.'],
['34','Pembayaran Piutang','ar','piutang','si_receivable_list','Penerimaan dan alokasi pembayaran customer.'],
['35','Melihat Pembayaran Piutang','ar','piutang','si_collection_history','Riwayat penerimaan piutang append-only.'],
['36','Mencetak Pembayaran Piutang','ar','laporan_inventory_sales','si_collection_history','Kwitansi penerimaan dan jejak cetak.','print'],
['37','Analisis Piutang per Customer','ar','piutang','si_receivable_aging_customer','Aging dan risiko piutang menurut customer.'],
['38','Analisis Piutang per Sales','ar','piutang','si_receivable_aging_sales','Aging dan beban tagih menurut sales.'],
['39','Sales Membawa Nota','trip','surat_perintah_sales','si_spj_list','Surat perintah jalan, barang dan custody nota.'],
['40','Nota Sales','trip','nota_sales','si_trip_list','Sesi nota, tagihan, biaya, setoran dan rekonsiliasi.'],
['41','Laporan Piutang','ar','laporan_inventory_sales','si_receivable_report','Rekap piutang berdasarkan periode dan status.'],
['42','Mencetak Laporan Piutang','ar','laporan_inventory_sales','si_receivable_report','Pratinjau laporan piutang siap cetak.','print'],
['43','Kas dan Jurnal','finance','kas_jurnal','si_cash_journal_list','Kas, bank, debit/kredit dan status posting jurnal.'],
['44','Membuat Perkiraan Baru','finance','kas_jurnal','si_coa_list','Chart of accounts untuk posting Inventory & Sales.'],
['45','Menu Laba / Rugi','finance','laba_rugi','si_profit_loss_params','Parameter periode dan cakupan laporan laba rugi.'],
['46','Mencetak Laba Rugi Kotor','finance','laba_rugi','si_gross_profit_report','Laba kotor penjualan berdasarkan kelompok barang.','print'],
['47','Laporan Laba / Rugi','finance','laba_rugi','si_profit_loss_report','Pendapatan, HPP, biaya dan laba bersih.'],
['48','Mencetak Laporan Laba / Rugi','finance','laporan_inventory_sales','si_profit_loss_print','Pratinjau laporan laba rugi final.','print']
];
var formConfig={
'01':{save:'si_supplier_create',id:'id',fields:[['kode','Kode Supplier','text',true],['nama','Nama Supplier','text',true],['wilayah','Wilayah'],['termin_hari','Termin (hari)','number'],['alamat','Alamat','textarea'],['telp','Telepon'],['no_rekening','No. Rekening'],['atas_nama','Atas Nama'],['bank','Bank'],['alamat_bank','Alamat Bank','textarea']]},
'04':{save:'si_customer_create',id:'anggota_id',fields:[['kode','Kode Customer','text',true],['nama','Nama Customer','text',true],['wilayah','Wilayah'],['termin_hari','Termin (hari)','number'],['alamat','Alamat','textarea'],['telp','Telepon'],['hp','Ponsel'],['limit_kredit','Limit Kredit','number'],['diskon_default_persen','Diskon Default (%)','number']]},
'07':{save:'si_sales_create',id:'id',fields:[['kode','Kode Sales','text',true],['nama','Nama Sales','text',true],['nomor_perkiraan','No. Perkiraan'],['area','Wilayah / Area'],['telepon','Ponsel'],['target_bulanan','Target Bulanan','number'],['limit_penagihan','Limit Penagihan','number'],['toko_id','ID Toko','number',true],['tbmuser_id','Akun Login']]},
'44':{save:'si_coa_save',id:'id',fields:[['kode','Kode Perkiraan','text',true],['nama','Nama Perkiraan','text',true],['tipe','Tipe Akun'],['induk_id','ID Induk','number'],['saldo_normal','Saldo Normal']]}
};
var columns={master:[['kode','Kode'],['nama','Nama'],['wilayah','Wilayah'],['terminHari','Termin'],['telp','Telepon'],['aktif','Status']],stock:[['kode','Kode'],['nama','Barang'],['satuan','Sat'],['hargaBeli','Harga Beli'],['awal','Awal'],['masuk','Masuk'],['keluar','Keluar'],['akhir','Akhir'],['nilai','Nilai']],ap:[['nomorFaktur','No. Faktur'],['supplierNama','Supplier'],['tanggal','Tanggal'],['jatuhTempo','Jatuh Tempo'],['total','Total'],['dibayar','Dibayar'],['outstanding','Sisa'],['statusDok','Status']],ar:[['nomorFaktur','No. Faktur'],['customerNama','Customer'],['salesNama','Sales'],['tanggal','Tanggal'],['jatuhTempo','Jatuh Tempo'],['total','Total'],['outstanding','Sisa'],['status','Status']],trip:[['nomor','Nomor'],['salesNama','Sales'],['tanggal','Tanggal'],['status','Status'],['totalNota','Nota'],['totalBarang','Barang'],['totalSetoran','Setoran']],finance:[['tanggal','Tanggal'],['nomor','Nomor'],['kodeAkun','Akun'],['namaAkun','Nama Akun'],['keterangan','Keterangan'],['debit','Debit'],['kredit','Kredit'],['status','Status']]};
var state={screen:screens[0],page:1,rows:[],raw:null,selected:null};
var $=function(id){return document.getElementById(id)};
function money(v){var n=Number(v);return isFinite(n)?new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(n):String(v==null?'':v)}
function isMoneyKey(k){return /(harga|nilai|total|saldo|nominal|outstanding|debit|kredit|limit|target|dibayar|hpp|laba|rugi)/i.test(k)}
function getValue(row,key){if(row[key]!==undefined)return row[key];var camel=key.replace(/_([a-z])/g,function(_,c){return c.toUpperCase()});if(row[camel]!==undefined)return row[camel];var lower=key.toLowerCase();for(var k in row)if(k.toLowerCase()===lower)return row[k];return ''}
function labelKey(k){return k.replace(/([A-Z])/g,' $1').replace(/_/g,' ').replace(/^./,function(c){return c.toUpperCase()})}
function detectRows(json){if(Array.isArray(json.data))return json.data;if(json.data&&typeof json.data==='object')return [json.data];var preferred=['items','rows','list','laporan','jurnal','aging','detail'];for(var i=0;i<preferred.length;i++)if(Array.isArray(json[preferred[i]]))return json[preferred[i]];for(var k in json)if(Array.isArray(json[k]))return json[k];return []}
async function call(action,payload){var body=Object.assign({action:action},payload||{});var res=await fetch(apiUrl,{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json','X-Requested-With':'XMLHttpRequest'},body:JSON.stringify(body)});var json;try{json=await res.json()}catch(e){throw new Error('Balasan server tidak valid (HTTP '+res.status+').')}if(!res.ok||json.status!=='success')throw new Error(json.message||'Permintaan tidak dapat diproses.');return json}
function renderNav(){var nav=$('siNavigation');nav.innerHTML='';Object.keys(groups).forEach(function(g){var wrap=document.createElement('section');wrap.className='si-nav-group';var h=document.createElement('button');h.textContent=groups[g];wrap.appendChild(h);screens.filter(function(s){return s[2]===g}).forEach(function(s){var a=document.createElement('a');a.href='#screen='+s[0];a.className='si-nav-item'+(state.screen[0]===s[0]?' active':'');a.setAttribute('data-screen',s[0]);a.innerHTML='<b>'+s[0]+'</b><span>'+s[1]+'</span>';wrap.appendChild(a)});nav.appendChild(wrap)})}
function filteredScreens(q){q=(q||'').toLowerCase();document.querySelectorAll('.si-nav-item').forEach(function(a){a.style.display=!q||a.textContent.toLowerCase().indexOf(q)>=0?'flex':'none'})}
function screenFromHash(){var m=location.hash.match(/screen=(\d{1,2})/);var no=m?('0'+m[1]).slice(-2):(app.getAttribute('data-initial')||'01');return screens.filter(function(s){return s[0]===no})[0]||screens[0]}
function dateDefaults(){var now=new Date(),from=new Date(now.getFullYear(),now.getMonth(),1);$('siDateFrom').value=from.toISOString().slice(0,10);$('siDateTo').value=now.toISOString().slice(0,10)}
function setScreen(s){state.screen=s;state.page=1;state.selected=null;$('siNumber').textContent='LAYAR '+s[0]+' / 48';$('siTitle').textContent=s[1];$('siBreadcrumb').textContent=s[1];$('siDescription').textContent=s[5];$('siCreate').disabled=!formConfig[s[0]];$('siCreate').title=formConfig[s[0]]?'Tambah data baru':'Layar ini menggunakan alur transaksi/approval khusus';$('siPrint').style.display=s[6]==='print'?'inline-block':'none';$('siExport').style.display=s[6]==='export'?'inline-block':'none';renderNav();load()}
function payload(){var f=$('siFilter').value;return {keyword:$('siKeyword').value.trim(),aktif:(f==='aktif'||f==='nonaktif')?f:undefined,status:(f==='open'||f==='lunas')?f:undefined,termasuk_lunas:(state.screen[0]==='23'||state.screen[0]==='33'||f==='lunas'),tanggal_awal:$('siDateFrom').value,tanggal_akhir:$('siDateTo').value,page:state.page,page_size:50}}
async function load(){var s=state.screen;$('siLoading').hidden=false;$('siEmpty').hidden=true;$('siNotice').hidden=true;$('siRows').innerHTML='';try{var json=await call(s[4],payload());state.raw=json;state.rows=detectRows(json);renderTable();$('siStatus').textContent='Tersambung';$('siTotal').textContent=String(json.total!==undefined?json.total:state.rows.length);$('siCount').textContent=(json.total!==undefined?json.total:state.rows.length)+' data';$('siPage').textContent=state.page;var totalNominal=0;state.rows.forEach(function(r){for(var k in r)if(isMoneyKey(k)&&/^(total|nilai|outstanding|saldo|nominal|debit)$/i.test(k))totalNominal+=Number(r[k])||0});$('siNominal').textContent=money(totalNominal);if(!state.rows.length)$('siEmpty').hidden=false}catch(e){state.rows=[];renderTable();$('siStatus').textContent='Perlu perhatian';$('siNotice').textContent=e.message;$('siNotice').hidden=false;$('siEmpty').hidden=false}finally{$('siLoading').hidden=true}}
function activeColumns(){var base=columns[state.screen[2]]||[];if(!state.rows.length)return base;var keys=Object.keys(state.rows[0]).filter(function(k){return typeof state.rows[0][k]!=='object'});var chosen=base.filter(function(c){return getValue(state.rows[0],c[0])!==''});if(chosen.length<3)chosen=keys.slice(0,9).map(function(k){return [k,labelKey(k)]});return chosen}
function renderTable(){var cols=activeColumns(),head=$('siHead'),body=$('siRows');head.innerHTML='';body.innerHTML='';var tr=document.createElement('tr');cols.forEach(function(c){var th=document.createElement('th');th.textContent=c[1];tr.appendChild(th)});head.appendChild(tr);state.rows.forEach(function(row,idx){var r=document.createElement('tr');r.tabIndex=0;r.addEventListener('click',function(){document.querySelectorAll('.si-table tbody tr').forEach(function(x){x.classList.remove('selected')});r.classList.add('selected');state.selected=row});r.addEventListener('dblclick',function(){if(formConfig[state.screen[0]])openForm(row)});cols.forEach(function(c){var td=document.createElement('td'),v=getValue(row,c[0]);if(typeof v==='boolean'){var b=document.createElement('span');b.className='si-badge'+(v?'':' off');b.textContent=v?'Aktif':'Nonaktif';td.appendChild(b)}else td.textContent=isMoneyKey(c[0])&&v!==''?money(v):(v==null?'':String(v));td.title=td.textContent;r.appendChild(td)});body.appendChild(r)})}
function toast(msg,error){var t=$('siToast');t.textContent=msg;t.className='si-toast'+(error?' error':'');t.hidden=false;setTimeout(function(){t.hidden=true},4200)}
function openForm(row){var cfg=formConfig[state.screen[0]];if(!cfg)return;row=row||null;$('siModalTitle').textContent=(row?'Ubah ':'Tambah ')+state.screen[1];var fields=$('siFormFields');fields.innerHTML='';cfg.fields.forEach(function(f){var wrap=document.createElement('div');wrap.className='si-field';var label=document.createElement('label');label.textContent=f[1]+(f[3]?' *':'');var input=document.createElement(f[2]==='textarea'?'textarea':'input');input.name=f[0];if(f[2]&&f[2]!=='textarea'&&f[2]!=='text')input.type=f[2];if(f[3])input.required=true;if(row){var camel=f[0].replace(/_([a-z])/g,function(_,c){return c.toUpperCase()});input.value=row[f[0]]!==undefined?row[f[0]]:(row[camel]!==undefined?row[camel]:'')}wrap.appendChild(label);wrap.appendChild(input);fields.appendChild(wrap)});$('siForm').dataset.edit=row?'1':'0';$('siForm').dataset.row=JSON.stringify(row||{});$('siModal').hidden=false}
function closeForm(){$('siModal').hidden=true}
async function submitForm(e){e.preventDefault();var cfg=formConfig[state.screen[0]],fd=new FormData(e.target),data={};fd.forEach(function(v,k){data[k]=v});var old=JSON.parse(e.target.dataset.row||'{}'),editing=e.target.dataset.edit==='1';if(editing){var id=old[cfg.id]!==undefined?old[cfg.id]:(cfg.id==='anggota_id'?old.anggotaId:old.id);data[cfg.id]=id}var action=cfg.save;if(editing)action=action.replace('_create','_update');try{await call(action,data);closeForm();toast('Data berhasil disimpan.');load()}catch(err){toast(err.message,true)}}
function csv(){if(!state.rows.length)return toast('Tidak ada data untuk diekspor.',true);var keys=Object.keys(state.rows[0]).filter(function(k){return typeof state.rows[0][k]!=='object'}),lines=[keys.join(',')];state.rows.forEach(function(r){lines.push(keys.map(function(k){return '"'+String(r[k]==null?'':r[k]).replace(/"/g,'""')+'"'}).join(','))});var blob=new Blob(['\ufeff'+lines.join('\r\n')],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='inventory-layar-'+state.screen[0]+'-'+new Date().toISOString().slice(0,10)+'.csv';a.click();setTimeout(function(){URL.revokeObjectURL(a.href)},1000)}
function printView(){window.print();call('si_print_log_create',{jenis_dokumen:'LAYAR_'+state.screen[0],referensi:state.screen[1],parameter:JSON.stringify(Object.assign(payload(),{jumlah_baris:state.rows.length})),perangkat:'JSP Inventory'}).catch(function(){})}
window.addEventListener('hashchange',function(){setScreen(screenFromHash())});window.addEventListener('online',function(){$('siOnline').classList.remove('offline');$('siOnline').innerHTML='<i class="fas fa-circle"></i> Online'});window.addEventListener('offline',function(){$('siOnline').classList.add('offline');$('siOnline').innerHTML='<i class="fas fa-circle"></i> Offline'});
$('siMenuSearch').addEventListener('input',function(){filteredScreens(this.value)});$('siKeyword').addEventListener('keydown',function(e){if(e.key==='Enter'){state.page=1;load()}});$('siFilter').addEventListener('change',load);$('siRefresh').addEventListener('click',load);$('siCreate').addEventListener('click',function(){openForm(null)});$('siExport').addEventListener('click',csv);$('siPrint').addEventListener('click',printView);$('siPrev').addEventListener('click',function(){if(state.page>1){state.page--;load()}});$('siNext').addEventListener('click',function(){if(state.rows.length){state.page++;load()}});$('siModalClose').addEventListener('click',closeForm);$('siCancel').addEventListener('click',closeForm);$('siModal').addEventListener('click',function(e){if(e.target===this)closeForm()});$('siForm').addEventListener('submit',submitForm);$('siOpenNav').addEventListener('click',function(){$('siSidebar').classList.add('open')});$('siCloseNav').addEventListener('click',function(){$('siSidebar').classList.remove('open')});$('siNavigation').addEventListener('click',function(){$('siSidebar').classList.remove('open')});
dateDefaults();setScreen(screenFromHash());
})();
