<%-- @generated by generate_new_jsp_scaffold.py
Source: src/ais/action/master/sekolah/helper/AmbilDataCalonSiswaForPengaturanBiayaHelper.java
Generated: 2026-08-06T18:20:20Z
This JSP contains presentation metadata only. Keep business logic in Java services.
--%>
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%
request.setAttribute("nuiModule", "sekolah");
request.setAttribute("nuiModuleLabel", "eSchool");
request.setAttribute("nuiPage", "helper/ambil_data_calon_siswa_for_pengaturan_biaya_helper");
request.setAttribute("nuiPageTitle", "Ambil Data Calon Siswa For Pengaturan Biaya Helper");
request.setAttribute("nuiPageType", "finance");
request.setAttribute("nuiPageDescription", "Keuangan untuk eSchool. Transaksi, status, rekonsiliasi, detail, dan audit keuangan.");
request.setAttribute("nuiSourceClass", "AmbilDataCalonSiswaForPengaturanBiayaHelper");
request.setAttribute("nuiSourcePackage", "ais.action.master.sekolah.helper");
request.setAttribute("nuiSourcePath", "src/ais/action/master/sekolah/helper/AmbilDataCalonSiswaForPengaturanBiayaHelper.java");
request.setAttribute("nuiSourceKind", "class");
request.setAttribute("nuiSourceExtends", "");
request.setAttribute("nuiSourceImplements", "");
request.setAttribute("nuiSourceMethods", new String[]{"onEvent", "render", "save", "display", "initCriteria", "onSearchDefault"});
request.setAttribute("nuiEntityCandidates", new String[]{"Yayasan", "Sekolah", "PengaturanBiayaPunyaSiswa", "CalonSiswa"});
%>
<jsp:include page="/WEB-INF/new/_shared/ui/page.jsp" />
