<%-- @generated by generate_new_jsp_scaffold.py
Source: src/ais/action/master/sekolah/helper/DetailAbsenGuruPiketHelper.java
Generated: 2026-08-06T18:20:20Z
This JSP contains presentation metadata only. Keep business logic in Java services.
--%>
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%
request.setAttribute("nuiModule", "sekolah");
request.setAttribute("nuiModuleLabel", "eSchool");
request.setAttribute("nuiPage", "helper/detail_absen_guru_piket_helper");
request.setAttribute("nuiPageTitle", "Detail Absen Guru Piket Helper");
request.setAttribute("nuiPageType", "academic");
request.setAttribute("nuiPageDescription", "Akademik untuk eSchool. Data akademik, jadwal, capaian, dan status proses pendidikan.");
request.setAttribute("nuiSourceClass", "DetailAbsenGuruPiketHelper");
request.setAttribute("nuiSourcePackage", "ais.action.master.sekolah.helper");
request.setAttribute("nuiSourcePath", "src/ais/action/master/sekolah/helper/DetailAbsenGuruPiketHelper.java");
request.setAttribute("nuiSourceKind", "class");
request.setAttribute("nuiSourceExtends", "");
request.setAttribute("nuiSourceImplements", "DataLoader, DataCriteria");
request.setAttribute("nuiSourceMethods", new String[]{"onEvent", "render", "initCriteria", "loadData", "displayDetailPA"});
request.setAttribute("nuiEntityCandidates", new String[]{"Guru", "Statusabsensi"});
%>
<jsp:include page="/WEB-INF/new/_shared/ui/page.jsp" />
