<%-- @generated by generate_new_jsp_scaffold.py
Source: src/ais/action/master/sekolah/helper/RevisiPembayaranSiswaDetailHelper.java
Generated: 2026-08-06T19:13:10Z
This JSP contains presentation metadata only. Keep business logic in Java services.
--%>
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%
request.setAttribute("nuiModule", "sekolah");
request.setAttribute("nuiModuleLabel", "eSchool");
request.setAttribute("nuiPage", "helper/revisi_pembayaran_siswa_detail_helper");
request.setAttribute("nuiPageTitle", "Revisi Pembayaran Siswa Detail Helper");
request.setAttribute("nuiPageType", "finance");
request.setAttribute("nuiPageDescription", "Keuangan untuk eSchool. Transaksi, status, rekonsiliasi, detail, dan audit keuangan.");
request.setAttribute("nuiSourceClass", "RevisiPembayaranSiswaDetailHelper");
request.setAttribute("nuiSourcePackage", "ais.action.master.sekolah.helper");
request.setAttribute("nuiSourcePath", "src/ais/action/master/sekolah/helper/RevisiPembayaranSiswaDetailHelper.java");
request.setAttribute("nuiSourceKind", "class");
request.setAttribute("nuiSourceExtends", "GenericRevisiHelper<PembayaranSiswaDetail>");
request.setAttribute("nuiSourceImplements", "");
request.setAttribute("nuiSourceMethods", new String[]{"apply", "bukaTabSeluruhData"});
request.setAttribute("nuiLegacyRefs", new String[]{});
request.setAttribute("nuiEntityCandidates", new String[]{"PembayaranSiswa", "PembayaranSiswaDetail"});
%>
<jsp:include page="/WEB-INF/new/_shared/ui/page.jsp" />
