-- DESTRUCTIVE rollback for migrasi_repository_modern_v2.sql.
-- Back up public.repo_workflow_event/repo_item_relation/repo_usage_event first.
BEGIN;
DROP TABLE IF EXISTS public.repo_notification;
DROP TABLE IF EXISTS public.repo_usage_event;
DROP TABLE IF EXISTS public.repo_item_relation;
DROP TABLE IF EXISTS public.repo_workflow_event;
ALTER TABLE public.repo_collection DROP COLUMN IF EXISTS deposit_enabled;
ALTER TABLE public.repo_collection DROP COLUMN IF EXISTS default_license_uri;
ALTER TABLE public.repo_collection DROP COLUMN IF EXISTS access_policy_json;
ALTER TABLE public.repo_collection DROP COLUMN IF EXISTS workflow_profile_json;
ALTER TABLE public.repo_collection DROP COLUMN IF EXISTS metadata_profile_json;
ALTER TABLE public.repo_bitstream DROP COLUMN IF EXISTS file_version;
ALTER TABLE public.repo_bitstream DROP COLUMN IF EXISTS signature_valid;
ALTER TABLE public.repo_bitstream DROP COLUMN IF EXISTS virus_scanned_at;
ALTER TABLE public.repo_bitstream DROP COLUMN IF EXISTS virus_scan_status;
ALTER TABLE public.repo_item DROP COLUMN IF EXISTS download_count;
ALTER TABLE public.repo_item DROP COLUMN IF EXISTS extracted_text;
ALTER TABLE public.repo_item DROP COLUMN IF EXISTS view_count;
ALTER TABLE public.repo_item DROP COLUMN IF EXISTS previous_version_id;
ALTER TABLE public.repo_item DROP COLUMN IF EXISTS version_number;
ALTER TABLE public.repo_item DROP COLUMN IF EXISTS slug;
ALTER TABLE public.repo_item DROP COLUMN IF EXISTS doi;
ALTER TABLE public.repo_item DROP COLUMN IF EXISTS withdrawal_reason;
ALTER TABLE public.repo_item DROP COLUMN IF EXISTS withdrawn_at;
ALTER TABLE public.repo_item DROP COLUMN IF EXISTS published_at;
ALTER TABLE public.repo_item DROP COLUMN IF EXISTS embargo_until;
ALTER TABLE public.repo_item DROP COLUMN IF EXISTS license_uri;
ALTER TABLE public.repo_item DROP COLUMN IF EXISTS assigned_reviewer_id;
ALTER TABLE public.repo_item DROP COLUMN IF EXISTS owner_id;
ALTER TABLE public.repo_item DROP COLUMN IF EXISTS workflow_status;
ALTER TABLE public.repo_item DROP COLUMN IF EXISTS lock_version;
ALTER TABLE new_audit.repo_collection__audit DROP COLUMN IF EXISTS deposit_enabled;
ALTER TABLE new_audit.repo_collection__audit DROP COLUMN IF EXISTS default_license_uri;
ALTER TABLE new_audit.repo_collection__audit DROP COLUMN IF EXISTS access_policy_json;
ALTER TABLE new_audit.repo_collection__audit DROP COLUMN IF EXISTS workflow_profile_json;
ALTER TABLE new_audit.repo_collection__audit DROP COLUMN IF EXISTS metadata_profile_json;
ALTER TABLE new_audit.repo_bitstream__audit DROP COLUMN IF EXISTS file_version;
ALTER TABLE new_audit.repo_bitstream__audit DROP COLUMN IF EXISTS signature_valid;
ALTER TABLE new_audit.repo_bitstream__audit DROP COLUMN IF EXISTS virus_scanned_at;
ALTER TABLE new_audit.repo_bitstream__audit DROP COLUMN IF EXISTS virus_scan_status;
ALTER TABLE new_audit.repo_item__audit DROP COLUMN IF EXISTS download_count;
ALTER TABLE new_audit.repo_item__audit DROP COLUMN IF EXISTS extracted_text;
ALTER TABLE new_audit.repo_item__audit DROP COLUMN IF EXISTS view_count;
ALTER TABLE new_audit.repo_item__audit DROP COLUMN IF EXISTS previous_version_id;
ALTER TABLE new_audit.repo_item__audit DROP COLUMN IF EXISTS version_number;
ALTER TABLE new_audit.repo_item__audit DROP COLUMN IF EXISTS slug;
ALTER TABLE new_audit.repo_item__audit DROP COLUMN IF EXISTS doi;
ALTER TABLE new_audit.repo_item__audit DROP COLUMN IF EXISTS withdrawal_reason;
ALTER TABLE new_audit.repo_item__audit DROP COLUMN IF EXISTS withdrawn_at;
ALTER TABLE new_audit.repo_item__audit DROP COLUMN IF EXISTS published_at;
ALTER TABLE new_audit.repo_item__audit DROP COLUMN IF EXISTS embargo_until;
ALTER TABLE new_audit.repo_item__audit DROP COLUMN IF EXISTS license_uri;
ALTER TABLE new_audit.repo_item__audit DROP COLUMN IF EXISTS assigned_reviewer_id;
ALTER TABLE new_audit.repo_item__audit DROP COLUMN IF EXISTS owner_id;
ALTER TABLE new_audit.repo_item__audit DROP COLUMN IF EXISTS workflow_status;
ALTER TABLE new_audit.repo_item__audit DROP COLUMN IF EXISTS lock_version;
COMMIT;
