<%-- @generated by generate_new_jsp_scaffold.py
Source: src/ais/action/ws/PembayaranWithJenisBayarAction.java
Generated: 2026-08-06T18:20:20Z
Safe service-adapter scaffold. Implement data access in a Java service layer, not directly in this JSP.
--%>
<%@ page language="java" contentType="application/json; charset=UTF-8" pageEncoding="UTF-8" %>
<%
request.setAttribute("nuiServiceModule", "root/ws");
request.setAttribute("nuiServicePage", "pembayaran_with_jenis_bayar");
request.setAttribute("nuiServiceTitle", "Pembayaran With Jenis Bayar");
request.setAttribute("nuiServiceType", "finance");
request.setAttribute("nuiServiceSourceClass", "PembayaranWithJenisBayarAction");
request.setAttribute("nuiServiceSourcePackage", "ais.action.ws");
request.setAttribute("nuiServiceSourcePath", "src/ais/action/ws/PembayaranWithJenisBayarAction.java");
request.setAttribute("nuiServiceMethods", new String[]{"hello", "reversal", "inquery", "pay"});
request.setAttribute("nuiServiceEntities", new String[]{});
%>
<jsp:include page="/WEB-INF/new/_shared/services/dispatcher.jsp" />
