<%-- @generated by generate_new_jsp_scaffold.py
Source: src/ais/action/master/obe/PikobeChartHelper.java
Generated: 2026-08-06T18:20:20Z
This JSP contains presentation metadata only. Keep business logic in Java services.
--%>
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%
request.setAttribute("nuiModule", "obe");
request.setAttribute("nuiModuleLabel", "Kurikulum OBE");
request.setAttribute("nuiPage", "pikobe_chart_helper");
request.setAttribute("nuiPageTitle", "Pikobe Chart Helper");
request.setAttribute("nuiPageType", "academic");
request.setAttribute("nuiPageDescription", "Akademik untuk Kurikulum OBE. Data akademik, jadwal, capaian, dan status proses pendidikan.");
request.setAttribute("nuiSourceClass", "PikobeChartHelper");
request.setAttribute("nuiSourcePackage", "ais.action.master.obe");
request.setAttribute("nuiSourcePath", "src/ais/action/master/obe/PikobeChartHelper.java");
request.setAttribute("nuiSourceKind", "class");
request.setAttribute("nuiSourceExtends", "");
request.setAttribute("nuiSourceImplements", "");
request.setAttribute("nuiSourceMethods", new String[]{"radar", "donut", "bars", "trend"});
request.setAttribute("nuiLegacyRefs", new String[]{});
request.setAttribute("nuiEntityCandidates", new String[]{});
%>
<jsp:include page="/WEB-INF/new/_shared/ui/page.jsp" />
