<%-- @generated by generate_new_jsp_scaffold.py
Source: src/ais/action/master/helper/keuangan/DownloadCicilanMahasiswa.java
Generated: 2026-08-06T18:20:20Z
Safe service-adapter scaffold. Implement data access in a Java service layer, not directly in this JSP.
--%>
<%@ page language="java" contentType="application/json; charset=UTF-8" pageEncoding="UTF-8" %>
<%
request.setAttribute("nuiServiceModule", "helper");
request.setAttribute("nuiServicePage", "keuangan/download_cicilan_mahasiswa");
request.setAttribute("nuiServiceTitle", "Download Cicilan Mahasiswa");
request.setAttribute("nuiServiceType", "finance");
request.setAttribute("nuiServiceSourceClass", "DownloadCicilanMahasiswa");
request.setAttribute("nuiServiceSourcePackage", "ais.action.master.helper.keuangan");
request.setAttribute("nuiServiceSourcePath", "src/ais/action/master/helper/keuangan/DownloadCicilanMahasiswa.java");
request.setAttribute("nuiServiceMethods", new String[]{"onEvent", "run"});
request.setAttribute("nuiServiceEntities", new String[]{"CicilanPembayaran"});
%>
<jsp:include page="/WEB-INF/new/_shared/services/dispatcher.jsp" />
