<%-- @generated by generate_new_jsp_scaffold.py
Source: src/ais/action/master/sirs/util/CommonItem.java
Generated: 2026-08-06T18:20:20Z
Safe service-adapter scaffold. Implement data access in a Java service layer, not directly in this JSP.
--%>
<%@ page language="java" contentType="application/json; charset=UTF-8" pageEncoding="UTF-8" %>
<%
request.setAttribute("nuiServiceModule", "sirs");
request.setAttribute("nuiServicePage", "util/common_item");
request.setAttribute("nuiServiceTitle", "Common Item");
request.setAttribute("nuiServiceType", "inventory");
request.setAttribute("nuiServiceSourceClass", "CommonItem");
request.setAttribute("nuiServiceSourcePackage", "ais.action.master.sirs.util");
request.setAttribute("nuiServiceSourcePath", "src/ais/action/master/sirs/util/CommonItem.java");
request.setAttribute("nuiServiceMethods", new String[]{"onUploadBiaya", "run", "onEvent", "onDownloadBiaya", "saveDetail", "initHargaJual"});
request.setAttribute("nuiServiceLegacyRefs", new String[]{});
request.setAttribute("nuiServiceEntities", new String[]{"ItemMedis", "JenisItemMedis", "SatuanItem", "KelompokItem", "KelasItem", "GenerikItem", "TarifKhususPunyaItem", "KelasPerawatan", "JenisBiaya", "Biaya"});
%>
<jsp:include page="/WEB-INF/new/_shared/services/dispatcher.jsp" />
