package ais.database.model.payroll;

// Generated Apr 16, 2010 2:27:16 PM by Hibernate Tools 3.2.4.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.envers.Audited;

import ais.database.model.GeneralValueObject;
import ais.database.model.Pegawai;

/**
 * Bank generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Entity(
    dynamicInsert = true,
    dynamicUpdate = true
)
@Audited
@Table(schema = "payroll", name = "gaji_tabahan")
public class GajiTabahan extends GeneralValueObject {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2463821577548439808L;
	private Long id;
	private String oleh;
	private String olehId;

	public String getOlehId() {
		return olehId;
	}

	public void setOlehId(String olehId) {if (olehId == null || olehId.trim().isEmpty()) {return;}
		this.olehId = olehId;
	}

	public String toString() {
		return nama;
	}

	public void setOleh(String oleh) {if (oleh == null || oleh.trim().isEmpty()) {return;}
		this.oleh = oleh;
	}

	public String getOleh() {
		return oleh;
	}

	@javax.persistence.PreUpdate protected void onUpdate() { ais.database.hibernate.AuditTimestampInterceptor.ubah(this);}     private Date tanggal_dirubah = ais.ui.util.WaktuUtil.getDate();

	public void setTanggal_dirubah(Date tanggal_dirubah) {
		this.tanggal_dirubah = tanggal_dirubah;
	}

	@Temporal(TemporalType.TIMESTAMP)
	public Date getTanggal_dirubah() {
		return tanggal_dirubah;
	}

	private String kode;
	private String nama;
	private String keterangan;
	private Date mulai = ais.ui.util.WaktuUtil.getDate();
	private Date sampai;

	private Cabang cabang;
	private Departemen departemen;
	private LevelJabatan levelJabatan;
	private Pegawai pegawai;
	private AdjusVariablePenggajian adjusVariablePenggajian;

	public GajiTabahan() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", insertable = false, unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "kode", nullable = false, length = 255)
	public String getKode() {
		if (getAdjusVariablePenggajian() != null) {
			kode = adjusVariablePenggajian.getKode();
		}
		return this.kode;
	}

	public void setKode(String kode) {
		this.kode = kode;
	}

	@Column(name = "keterangan", nullable = true)
	public String getKeterangan() {
		if ((keterangan == null || keterangan.trim().isEmpty()) && getAdjusVariablePenggajian() != null) {
			keterangan = adjusVariablePenggajian.getKeterangan();
		}
		return this.keterangan;
	}

	public void setKeterangan(String keterangan) {
		this.keterangan = keterangan;
	}

	public void setNama(String nama) {
		this.nama = nama;
	}

	@Column(name = "nama", columnDefinition = "text", nullable = true)
	public String getNama() {
		if ((nama == null || nama.trim().isEmpty()) && getAdjusVariablePenggajian() != null) {
			nama = adjusVariablePenggajian.getNama();
		}
		return nama;
	}

	public Date getMulai() {
		if (getAdjusVariablePenggajian() != null) {
			mulai = adjusVariablePenggajian.getMulai();
		}
		return mulai;
	}

	public void setMulai(Date mulai) {
		this.mulai = mulai;
	}

	public Date getSampai() {
		if (getAdjusVariablePenggajian() != null) {
			sampai = adjusVariablePenggajian.getSampai();
		}
		return sampai;
	}

	public void setSampai(Date sampai) {
		this.sampai = sampai;
	}

	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY)
	@JoinColumn(name = "cabang", nullable = true)
	public Cabang getCabang() {
		cabang = check(cabang);
		return cabang;
	}

	public void setCabang(Cabang cabang) {
		this.cabang = cabang;
	}

	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY)
	@JoinColumn(name = "departemen", nullable = true)
	public Departemen getDepartemen() {
		departemen = check(departemen);
		return departemen;
	}

	public void setDepartemen(Departemen departemen) {
		this.departemen = departemen;
	}

	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY)
	@JoinColumn(name = "level_jabatan", nullable = true)
	public LevelJabatan getLevelJabatan() {
		levelJabatan = check(levelJabatan);
		return levelJabatan;
	}

	public void setLevelJabatan(LevelJabatan levelJabatan) {
		this.levelJabatan = levelJabatan;
	}

	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY)
	@JoinColumn(name = "pegawai", nullable = true)
	public Pegawai getPegawai() {
		pegawai = check(pegawai);
		return pegawai;
	}

	public void setPegawai(Pegawai pegawai) {
		this.pegawai = pegawai;
	}

	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY)
	@JoinColumn(name = "adjus_variable_penggajian", nullable = true)
	public AdjusVariablePenggajian getAdjusVariablePenggajian() {
		adjusVariablePenggajian = check(adjusVariablePenggajian);
		return adjusVariablePenggajian;
	}

	public void setAdjusVariablePenggajian(AdjusVariablePenggajian adjusVariablePenggajian) {
		this.adjusVariablePenggajian = adjusVariablePenggajian;
	}

}
