package ais.database.model.payroll;

// Generated Apr 16, 2010 2:27:16 PM by Hibernate Tools 3.2.4.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.Session;
import org.hibernate.criterion.Restrictions;
import org.hibernate.envers.Audited;

import ais.database.hibernate.HibernateUtil;
import ais.database.model.GeneralValueObject;

/**
 * Entitas "kelompok" (header) untuk parameter tambahan gaji pegawai pada modul payroll:
 * mengelompokkan sekumpulan {@link ParameterTambahanGajiPegawai} (dan lewat relasi itu,
 * {@link ParameterTambahan} master) di bawah satu judul yang ditampilkan sebagai baris
 * pemisah pada formulir isian dinamis pegawai/penggajian — lihat
 * {@code ais.action.master.payroll.helper.ParameterTambahanGajiPegawaiListener} yang merender
 * satu baris judul per kelompok aktif diikuti baris input per parameter dalam kelompok
 * tersebut.
 *
 * <p>Baris komentar {@code "Bank generated by hbm2java"} di atas adalah sisa salin-tempel dari
 * kelas lain saat pembuatan berkas ini lewat Hibernate Tools (kelas ini sama sekali tidak
 * berhubungan dengan {@code Bank}) — dibiarkan sebagai jejak sejarah pembuatan berkas, bukan
 * dihapus, sesuai kebijakan dokumentasi yang hanya memperkaya, tidak mengurangi.</p>
 *
 * <h3>Sepupu paralel di modul lain</h3>
 * <p>Kelas ini adalah <b>sepupu struktural</b> dari
 * {@code ais.database.model.payroll.KelompokParameterTambahanPengajuanTransaksiPegawai} (dipakai
 * pada alur pengajuan transaksi pegawai, bukan gaji pokok/penggajian rutin) — keduanya dibuat
 * dari cetakan (template) hbm2java yang sama sehingga bentuk field, getter/setter, dan pola
 * {@link #checkCreateDefault()}/{@link #compareTo(GeneralValueObject)} identik, namun beroperasi
 * atas tabel dan konteks bisnis yang berbeda sama sekali. <b>Catatan verifikasi keamanan:</b> pada
 * pasangan sepupu {@code PengajuanTransaksiPegawai}, listener-nya menuliskan atribut baris ZK
 * dengan kunci {@code "kelompokParameterTambahanPengajuanTransaksiPegawai"} sedangkan
 * {@code PengajuanTransaksiPegawai.populateParameterTambahan(List)} membacanya kembali dengan
 * kunci yang SALAH, {@code "kelompokParameterTambahanPengajuanPegawai"} (nama kelas/kunci milik
 * modul lain, {@code KelompokParameterTambahanPengajuanPegawai}) — akibatnya setiap simpan
 * formulir pengajuan transaksi pegawai diam-diam mengosongkan seluruh isian parameter tambahan.
 * Kelas GAJI PEGAWAI ini <b>telah diverifikasi TIDAK terkena pola bug yang sama</b>: kunci atribut
 * baris {@code "kelompokParameterTambahanGajiPegawai"} yang dituliskan oleh
 * {@code ParameterTambahanGajiPegawaiListener.onEvent(Event)} (baris pembangunan form) cocok
 * persis — baik string kunci maupun tipe cast {@link KelompokParameterTambahanGajiPegawai} —
 * dengan yang dibaca kembali di {@code ParameterTambahanGajiPegawaiListener.validate()} dan di
 * {@code ais.database.model.Pegawai#populateParameterTambahan(java.util.List)}. Tidak ada
 * kehilangan data pada jalur simpan kelompok parameter tambahan gaji pegawai.</p>
 *
 * <h3>Pola arsitektur yang perlu diperhatikan</h3>
 * <ul>
 * <li><b>Flag {@code aktif} satu-arah.</b> {@link #getAktif()} menormalkan {@code null} menjadi
 * {@code true} (kelompok baru dianggap aktif secara default) dan MENULIS balik ke field saat
 * dibaca — pola "getter destruktif" yang sama dipakai {@link #getDefaultData()} dan
 * {@link #getNomorUrut()}; lihat javadoc masing-masing untuk implikasinya terhadap
 * {@code dynamicUpdate}.</li>
 * <li><b>Field audit ringan (bayangan).</b> {@code oleh}/{@code olehId}/{@code tanggal_dirubah}
 * adalah jejak audit sederhana di luar Hibernate Envers penuh (kelas ini juga {@code @Audited}) —
 * ini KEHARUSAN TEKNIS arsitektur aplikasi (kompatibilitas dengan kode lama yang membaca kolom ini
 * langsung), bukan duplikasi yang perlu dibersihkan.</li>
 * <li><b>Satu baris default per seluruh instalasi.</b> {@link #checkCreateDefault()} menjamin
 * tepat satu baris dengan {@code defaultData = true} ada di tabel — TANPA filter unit
 * kerja/cabang/tenant apa pun; lihat javadoc method untuk detail dan implikasinya pada instalasi
 * multi-cabang.</li>
 * </ul>
 *
 * @see ParameterTambahanGajiPegawai
 * @see ais.database.model.ParameterTambahan
 * @see ais.database.model.Pegawai#populateParameterTambahan(java.util.List)
 */
@Entity
@org.hibernate.annotations.Entity(
    dynamicInsert = true,
    dynamicUpdate = true
)
@Audited
@Table(schema = "payroll", name = "kelompok_parameter_tambahan_gaji_pegawai")
public class KelompokParameterTambahanGajiPegawai extends GeneralValueObject {

	/**
	 * ID versi serialisasi Java untuk kompatibilitas antar build saat objek ini diserialisasi
	 * (mis. disimpan ke sesi HTTP ZK). Nilai tetap, tidak berubah kecuali struktur field yang
	 * memengaruhi serialisasi berubah signifikan.
	 */
	private static final long serialVersionUID = 2463821577548439808L;

	/** Primary key baris kelompok parameter tambahan gaji pegawai, digenerasi database (IDENTITY). */
	private Long id;

	/** Nama/username pengguna yang terakhir membuat/mengubah baris ini (jejak audit ringan, bebas-teks). */
	private String oleh;

	/** ID pengguna yang terakhir membuat/mengubah baris ini (jejak audit ringan, pasangan {@link #oleh}). */
	private String olehId;

	/**
	 * Mengambil ID pengguna yang terakhir membuat/mengubah baris ini.
	 *
	 * @return ID pengguna audit ringan; bisa {@code null} bila belum pernah diisi
	 */
	public String getOlehId() {
		return olehId;
	}

	/**
	 * Mengisi ID pengguna audit ringan. Nilai {@code null} atau string kosong/berisi-spasi-saja
	 * DIABAIKAN (method langsung {@code return} tanpa mengubah field) — sekali {@link #olehId}
	 * terisi, ia tidak bisa "dikosongkan lagi" lewat setter ini, hanya bisa ditimpa nilai lain
	 * yang tidak kosong.
	 *
	 * @param olehId ID pengguna; diabaikan bila {@code null}/kosong
	 */
	public void setOlehId(String olehId) {if (olehId == null || olehId.trim().isEmpty()) {return;}
		this.olehId = olehId;
	}

	/**
	 * Mengisi nama/username pengguna audit ringan. Sama seperti {@link #setOlehId(String)},
	 * nilai {@code null}/kosong/berisi-spasi-saja diabaikan sehingga {@link #oleh} tidak pernah
	 * ditimpa balik menjadi kosong lewat jalur ini.
	 *
	 * @param oleh nama/username pengguna; diabaikan bila {@code null}/kosong
	 */
	public void setOleh(String oleh) {if (oleh == null || oleh.trim().isEmpty()) {return;}
		this.oleh = oleh;
	}

	/**
	 * Mengambil nama/username pengguna yang terakhir membuat/mengubah baris ini.
	 *
	 * @return nama/username audit ringan; bisa {@code null} bila belum pernah diisi
	 */
	public String getOleh() {
		return oleh;
	}

	/**
	 * Callback siklus-hidup JPA yang dipicu Hibernate tepat sebelum {@code UPDATE} dijalankan
	 * terhadap baris ini. Mendelegasikan ke
	 * {@link ais.database.hibernate.AuditTimestampInterceptor#ubah(Object)} yang menuliskan
	 * {@link #tanggal_dirubah} (dan pada beberapa entitas lain, {@link #oleh}/{@link #olehId})
	 * berdasarkan konteks pengguna yang sedang login pada sesi saat ini. Field
	 * {@link #tanggal_dirubah} diinisialisasi eager ke waktu sekarang ({@code WaktuUtil.getDate()})
	 * pada saat objek dikonstruksi, sehingga baris yang baru dibuat pun sudah punya nilai awal
	 * sebelum {@code onUpdate} sempat dipanggil (yang hanya terpicu pada {@code UPDATE}, bukan
	 * {@code INSERT}).
	 */
	@javax.persistence.PreUpdate protected void onUpdate() { ais.database.hibernate.AuditTimestampInterceptor.ubah(this);}     private Date tanggal_dirubah = ais.ui.util.WaktuUtil.getDate();

	/**
	 * Mengisi paksa tanggal perubahan terakhir. Biasanya tidak dipanggil manual — nilainya normal
	 * ditulis otomatis oleh {@link #onUpdate()} lewat interceptor Hibernate.
	 *
	 * @param tanggal_dirubah tanggal/jam perubahan terakhir
	 */
	public void setTanggal_dirubah(Date tanggal_dirubah) {
		this.tanggal_dirubah = tanggal_dirubah;
	}

	/**
	 * Mengambil tanggal/jam perubahan terakhir baris ini, dipetakan sebagai kolom timestamp.
	 *
	 * @return tanggal/jam perubahan terakhir
	 */
	@Temporal(TemporalType.TIMESTAMP)
	public Date getTanggal_dirubah() {
		return tanggal_dirubah;
	}

	/**
	 * Representasi teks ringkas baris ini untuk keperluan log/debug: {@code "<id>-<nama>"}.
	 *
	 * @return string gabungan ID dan nama kelompok
	 */
	public String toString() {
		return id + "-" + nama;
	}

	/** Nama kelompok yang ditampilkan sebagai judul baris pemisah pada formulir dinamis. */
	private String nama;

	/** Keterangan/deskripsi bebas-teks untuk kelompok ini; boleh {@code null}. */
	private String keterangan;

	/**
	 * Penanda apakah baris ini adalah kelompok DEFAULT bawaan sistem (lihat
	 * {@link #checkCreateDefault()}) — hanya boleh ada satu baris {@code true} di seluruh tabel.
	 */
	private Boolean defaultData;

	/** Penanda apakah kelompok ini aktif dan boleh ditampilkan pada formulir. Default {@code true}. */
	private Boolean aktif;

	/** Urutan tampil kelompok relatif terhadap kelompok lain (dipakai {@link #compareTo}). Default {@code 1}. */
	private Integer nomorUrut;

	/**
	 * Menjamin tersedianya SATU baris kelompok "default" ({@code defaultData = true}) di tabel
	 * {@code payroll.kelompok_parameter_tambahan_gaji_pegawai}, membuatnya (dengan nama/keterangan
	 * {@code "Form Tambahan"}) bila belum ada, lalu mengembalikannya.
	 *
	 * <p><b>Cara kerja:</b> query native session dengan
	 * {@code Restrictions.eq("defaultData", true)} dibatasi satu hasil ({@code setMaxResults(1)}).
	 * Bila tidak ditemukan, method membuka transaksi baru secara manual
	 * ({@code session.getTransaction().begin()/commit()}) — di LUAR pengelolaan transaksi
	 * request/servlet normal — untuk menyimpan baris baru, lalu menutup sesi native lewat
	 * {@link HibernateUtil#closeSession()} sebelum mengembalikan hasil.</p>
	 *
	 * <p><b>Nama variabel lokal menyesatkan (peninggalan salin-tempel).</b> Variabel lokal di
	 * method ini bernama {@code kelompokParameterTambahanCatatanSiswa} — nama itu adalah sisa
	 * salin-tempel dari kelas sepupu {@code KelompokParameterTambahanCatatanSiswa} (modul sekolah)
	 * saat berkas ini pertama kali dibuat dari cetakan yang sama; TIDAK ada bug fungsional di
	 * sini karena tipe variabel tetap benar ({@link KelompokParameterTambahanGajiPegawai}) dan
	 * seluruh operasi query/simpan mengacu ke kelas yang benar — hanya penamaan yang menyesatkan
	 * bagi pembaca kode.</p>
	 *
	 * <p><b>Tanpa filter tenant/cabang.</b> Query TIDAK menyaring berdasarkan unit
	 * kerja/cabang/satuan kerja apa pun — pada instalasi dengan banyak cabang yang berbagi satu
	 * basis data, hanya ada SATU baris default untuk SEMUA cabang. Ini konsisten dengan
	 * {@link #checkCreateDefault()} pada kelas sepupu di modul lain (pola yang sama, bukan
	 * penyimpangan khusus kelas ini).</p>
	 *
	 * <p><b>Race condition potensial.</b> Dua thread/request yang memanggil method ini bersamaan
	 * saat baris default belum ada bisa sama-sama lolos pengecekan {@code uniqueResult() == null}
	 * sebelum salah satunya sempat commit, berpotensi membuat DUA baris {@code defaultData = true}
	 * (tidak ada constraint unique di level database yang mencegah ini). Dalam praktiknya risiko
	 * ini rendah karena method biasanya dipanggil sekali saat inisialisasi/seed data, bukan pada
	 * jalur transaksi bervolume tinggi.</p>
	 *
	 * @return baris kelompok default (baru dibuat atau yang sudah ada)
	 */
	public static KelompokParameterTambahanGajiPegawai checkCreateDefault() {
		Session session = HibernateUtil.currentNativeSession();
		KelompokParameterTambahanGajiPegawai kelompokParameterTambahanCatatanSiswa = (KelompokParameterTambahanGajiPegawai) session
				.createCriteria(KelompokParameterTambahanGajiPegawai.class).add(Restrictions.eq("defaultData", true))
				.setMaxResults(1).uniqueResult();
		if (kelompokParameterTambahanCatatanSiswa == null) {
			kelompokParameterTambahanCatatanSiswa = new KelompokParameterTambahanGajiPegawai();
			kelompokParameterTambahanCatatanSiswa.setDefaultData(true);
			kelompokParameterTambahanCatatanSiswa.setNama("Form Tambahan");
			kelompokParameterTambahanCatatanSiswa.setKeterangan("Form Tambahan");
			session.getTransaction().begin();
			session.save(kelompokParameterTambahanCatatanSiswa);
			session.getTransaction().commit();
		}

		HibernateUtil.closeSession();
		return kelompokParameterTambahanCatatanSiswa;
	}

	/** Konstruktor kosong yang diwajibkan JPA/Hibernate untuk instansiasi lewat refleksi. */
	public KelompokParameterTambahanGajiPegawai() {
	}

	/**
	 * Primary key baris ini, digenerasi otomatis oleh database (strategi {@code IDENTITY}).
	 *
	 * @return ID baris; {@code null} untuk instance yang belum disimpan
	 */
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", insertable = false, unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	/**
	 * Mengisi ID baris. Kolomnya {@code insertable = false} sehingga nilai ini praktis hanya
	 * relevan untuk baris yang sudah tersimpan (dibaca kembali dari database), bukan untuk
	 * ditentukan manual sebelum {@code INSERT}.
	 *
	 * @param id ID baris
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * Nama kelompok, ditampilkan sebagai judul baris pemisah pada formulir parameter tambahan
	 * dinamis. Nilai di-{@code trim()} setiap kali dibaca (field aslinya tidak diubah).
	 *
	 * @return nama kelompok yang sudah di-trim; {@code null} bila field belum diisi
	 */
	@Column(name = "nama", nullable = false, length = 255)
	public String getNama() {
		return this.nama == null ? null : this.nama.trim();
	}

	/**
	 * Mengisi nama kelompok. Wajib diisi (kolom {@code nullable = false}) sebelum baris berhasil
	 * disimpan; nilai TIDAK di-trim di sini (trimming hanya terjadi pada {@link #getNama()}).
	 *
	 * @param nama nama kelompok, maksimal 255 karakter
	 */
	public void setNama(String nama) {
		this.nama = nama;
	}

	/**
	 * Keterangan/deskripsi bebas-teks untuk kelompok ini.
	 *
	 * @return keterangan kelompok; boleh {@code null}
	 */
	@Column(name = "keterangan", nullable = true)
	public String getKeterangan() {
		return this.keterangan;
	}

	/**
	 * Mengisi keterangan/deskripsi kelompok.
	 *
	 * @param keterangan teks keterangan; boleh {@code null}
	 */
	public void setKeterangan(String keterangan) {
		this.keterangan = keterangan;
	}

	/**
	 * Penanda apakah baris ini adalah kelompok default bawaan sistem (lihat
	 * {@link #checkCreateDefault()}). <b>Getter destruktif:</b> {@code null} dinormalkan menjadi
	 * {@code false} dan DITULIS BALIK ke field {@link #defaultData} pada saat dibaca — bukan
	 * murni method baca. Karena entitas ini memakai {@code dynamicUpdate = true}, efek samping ini
	 * bisa memengaruhi kolom mana yang ikut serta pada {@code UPDATE} berikutnya jika getter
	 * sempat dipanggil di antara load dan flush pada sesi Hibernate yang sama.
	 *
	 * @return {@code true} bila kelompok default; {@code false} (termasuk hasil normalisasi
	 *         {@code null}) bila bukan
	 */
	public Boolean getDefaultData() {
		if (defaultData == null) {
			defaultData = false;
		}
		return defaultData;
	}

	/**
	 * Mengisi penanda kelompok default. Pemanggil bertanggung jawab menjaga invarian "hanya satu
	 * baris {@code true} di seluruh tabel" — tidak ada validasi otomatis di level entitas ini;
	 * lihat {@link #checkCreateDefault()} untuk satu-satunya jalur yang menjamin invarian tersebut
	 * secara terkontrol.
	 *
	 * @param defaultData {@code true} untuk menjadikan baris ini kelompok default
	 */
	public void setDefaultData(Boolean defaultData) {
		this.defaultData = defaultData;
	}

	/**
	 * Penanda apakah kelompok ini aktif dan boleh ditampilkan pada formulir parameter tambahan.
	 * <b>Getter destruktif:</b> {@code null} dinormalkan menjadi {@code true} (kelompok baru
	 * default-nya AKTIF) dan ditulis balik ke field {@link #aktif} — lihat catatan
	 * {@code dynamicUpdate} pada {@link #getDefaultData()} yang berlaku sama di sini. Nonaktifkan
	 * kelompok lewat {@link #setAktif(Boolean)} untuk menyembunyikannya dari formulir tanpa
	 * menghapus baris (dan riwayat parameter di bawahnya) dari database.
	 *
	 * @return {@code true} bila kelompok aktif; default {@code true} bila belum pernah diisi
	 */
	public Boolean getAktif() {
		if (aktif == null) {
			aktif = true;
		}
		return aktif;
	}

	/**
	 * Mengisi penanda aktif/nonaktif kelompok.
	 *
	 * @param aktif {@code true} untuk mengaktifkan, {@code false} untuk menyembunyikan dari formulir
	 */
	public void setAktif(Boolean aktif) {
		this.aktif = aktif;
	}

	/**
	 * Urutan tampil kelompok ini relatif terhadap kelompok lain pada formulir, dipakai oleh
	 * {@link #compareTo(GeneralValueObject)} untuk pengurutan. <b>Getter destruktif:</b>
	 * {@code null} dinormalkan menjadi {@code 1} dan ditulis balik ke field {@link #nomorUrut} —
	 * pola sama seperti {@link #getDefaultData()}/{@link #getAktif()}. Kondisi
	 * {@code return nomorUrut == null ? 1 : nomorUrut} di baris terakhir method secara logis tidak
	 * pernah bernilai {@code null} lagi pada titik itu (sudah dinormalkan di baris sebelumnya) —
	 * sisa kode defensif yang tidak berbahaya, hanya redundan.
	 *
	 * @return nomor urut tampil; default {@code 1} bila belum pernah diisi
	 */
	public Integer getNomorUrut() {
		if (nomorUrut == null) {
			nomorUrut = 1;
		}
		return nomorUrut == null ? 1 : nomorUrut;
	}

	/**
	 * Mengisi nomor urut tampil kelompok.
	 *
	 * @param nomorUrut nomor urut; angka lebih kecil tampil lebih dulu lewat {@link #compareTo}
	 */
	public void setNomorUrut(Integer nomorUrut) {
		this.nomorUrut = nomorUrut;
	}

	/**
	 * Membandingkan urutan tampil dua kelompok berdasarkan {@link #getNomorUrut()}, dipakai saat
	 * daftar kelompok diurutkan (mis. {@code Collections.sort}) sebelum dirender pada formulir.
	 *
	 * <p><b>Risiko {@code ClassCastException}.</b> Argumen di-cast paksa ke
	 * {@link KelompokParameterTambahanGajiPegawai} tanpa pengecekan {@code instanceof} — memanggil
	 * method ini dengan instance {@link GeneralValueObject} dari subclass lain akan melempar
	 * exception saat runtime, bukan dicegah lebih awal.</p>
	 *
	 * @param arg0 objek pembanding, harus berupa {@link KelompokParameterTambahanGajiPegawai}
	 * @return negatif/nol/positif sesuai kontrak {@link Comparable}, berdasarkan selisih nomor urut
	 * @throws ClassCastException bila {@code arg0} bukan {@link KelompokParameterTambahanGajiPegawai}
	 */
	@Override
	public int compareTo(GeneralValueObject arg0) {
		return getNomorUrut().compareTo(((KelompokParameterTambahanGajiPegawai) arg0).getNomorUrut());
	}

}
