<%-- @generated by generate_new_jsp_scaffold.py
Source: src/ais/action/master/payroll/TransaksiPegawaiAction.java
Generated: 2026-08-06T18:20:20Z
Safe service-adapter scaffold. Implement data access in a Java service layer, not directly in this JSP.
--%>
<%@ page language="java" contentType="application/json; charset=UTF-8" pageEncoding="UTF-8" %>
<%
request.setAttribute("nuiServiceModule", "payroll");
request.setAttribute("nuiServicePage", "transaksi_pegawai");
request.setAttribute("nuiServiceTitle", "Transaksi Pegawai");
request.setAttribute("nuiServiceType", "finance");
request.setAttribute("nuiServiceSourceClass", "TransaksiPegawaiAction");
request.setAttribute("nuiServiceSourcePackage", "ais.action.master.payroll");
request.setAttribute("nuiServiceSourcePath", "src/ais/action/master/payroll/TransaksiPegawaiAction.java");
request.setAttribute("nuiServiceMethods", new String[]{"doAfterCompose", "onEvent", "render", "onAdd", "init", "onSave", "onSearchDefault", "initCriteria"});
request.setAttribute("nuiServiceLegacyRefs", new String[]{});
request.setAttribute("nuiServiceEntities", new String[]{"JenisTransaksiPegawai", "TransaksiPegawai"});
%>
<jsp:include page="/WEB-INF/new/_shared/services/dispatcher.jsp" />
