<%-- @generated by generate_new_jsp_scaffold.py
Source: src/ais/action/master/sekolah/psb/form/PPDB_Simple3.java
Generated: 2026-08-06T18:20:20Z
This JSP contains presentation metadata only. Keep business logic in Java services.
--%>
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%
request.setAttribute("nuiModule", "sekolah");
request.setAttribute("nuiModuleLabel", "eSchool");
request.setAttribute("nuiPage", "psb/form/ppdb_simple3");
request.setAttribute("nuiPageTitle", "Simple 3");
request.setAttribute("nuiPageType", "form");
request.setAttribute("nuiPageDescription", "Formulir untuk eSchool. Pendataan bertahap dengan validasi, status kelengkapan, dan audit.");
request.setAttribute("nuiSourceClass", "PPDB_Simple3");
request.setAttribute("nuiSourcePackage", "ais.action.master.sekolah.psb.form");
request.setAttribute("nuiSourcePath", "src/ais/action/master/sekolah/psb/form/PPDB_Simple3.java");
request.setAttribute("nuiSourceKind", "class");
request.setAttribute("nuiSourceExtends", "PPDB");
request.setAttribute("nuiSourceImplements", "");
request.setAttribute("nuiSourceMethods", new String[]{"onEvent", "init", "onSave"});
request.setAttribute("nuiEntityCandidates", new String[]{"PaketPsbPunyaGelombangPendaftaranPsb", "PaketPsb", "CalonSiswa", "DefaultNisGenerator", "Siswa"});
%>
<jsp:include page="/WEB-INF/new/_shared/ui/page.jsp" />
