package ais.action.master.jurnal.importer;

import java.security.MessageDigest;import java.sql.*;import java.util.*;

/** External-source inspection only. Never uses OjsHibernateUtil and never mutates the source. */
public final class OjsImportPreflightService{
 public static final class Config{public String jdbcUrl,user,password,schema;public int loginTimeoutSeconds=15,queryTimeoutSeconds=30;}
 public static final class Result{public String dialect,version,schemaSignature;public int expectedTables,foundTables,foundFields;public final List<String> missing=new ArrayList<String>();public final Map<String,Integer> fieldsByTable=new LinkedHashMap<String,Integer>();}
 public Result inspect(Config cfg)throws Exception{validate(cfg);DriverManager.setLoginTimeout(Math.max(1,Math.min(60,cfg.loginTimeoutSeconds)));Properties p=new Properties();p.setProperty("user",cfg.user);p.setProperty("password",cfg.password);Connection c=null;try{c=DriverManager.getConnection(cfg.jdbcUrl,p);c.setReadOnly(true);c.setAutoCommit(false);Result r=new Result();r.expectedTables=OjsSourceCatalog.TABLES.size();r.dialect=dialect(cfg.jdbcUrl);DatabaseMetaData m=c.getMetaData();Map<String,String> physical=new HashMap<String,String>();ResultSet tables=m.getTables(c.getCatalog(),blank(cfg.schema)?null:cfg.schema,"%",new String[]{"TABLE"});try{while(tables.next()){String n=tables.getString("TABLE_NAME");if(n!=null)physical.put(n.toLowerCase(),n);}}finally{tables.close();}inventory(c,cfg,m,physical,OjsSourceCatalog.TABLES,r);r.version=readVersion(c,cfg,r);if("LEGACY".equals(r.version)){r.expectedTables=OjsLegacySourceCatalog.TABLES.size();r.missing.clear();r.fieldsByTable.clear();r.foundTables=0;r.foundFields=0;inventory(c,cfg,m,physical,OjsLegacySourceCatalog.TABLES,r);}r.schemaSignature=signature(r);c.rollback();return r;}finally{if(c!=null)try{c.rollback();}catch(Exception ignored){}if(c!=null)try{c.close();}catch(Exception ignored){}}}
 private static void inventory(Connection c,Config cfg,DatabaseMetaData m,Map<String,String>physical,List<String>expectedTables,Result r)throws Exception{for(String expected:expectedTables){String actual=physical.get(expected);if(actual==null){r.missing.add(expected);continue;}int count=0;ResultSet cols=m.getColumns(c.getCatalog(),blank(cfg.schema)?null:cfg.schema,actual,"%");try{while(cols.next())count++;}finally{cols.close();}r.fieldsByTable.put(expected,Integer.valueOf(count));r.foundTables++;r.foundFields+=count;}}
 private String readVersion(Connection c,Config cfg,Result r){if(!r.fieldsByTable.containsKey("versions"))return r.foundTables<100?"LEGACY":"UNKNOWN";String prefix=blank(cfg.schema)?"":quote(cfg.schema)+".";String sql="select major,minor,revision,build from "+prefix+quote("versions")+" order by date_installed desc";Statement st=null;ResultSet rs=null;try{st=c.createStatement();st.setQueryTimeout(Math.max(1,Math.min(300,cfg.queryTimeoutSeconds)));st.setMaxRows(1);rs=st.executeQuery(sql);if(rs.next())return rs.getInt(1)+"."+rs.getInt(2)+"."+rs.getInt(3)+"-"+rs.getInt(4);}catch(Exception ignored){}finally{try{if(rs!=null)rs.close();}catch(Exception ignored){}try{if(st!=null)st.close();}catch(Exception ignored){}}return "UNKNOWN";}
 private static String signature(Result r)throws Exception{StringBuilder b=new StringBuilder();for(Map.Entry<String,Integer>e:r.fieldsByTable.entrySet())b.append(e.getKey()).append(':').append(e.getValue()).append(';');MessageDigest d=MessageDigest.getInstance("SHA-256");byte[] h=d.digest(b.toString().getBytes("UTF-8"));StringBuilder o=new StringBuilder();for(byte x:h)o.append(String.format("%02x",x&255));return o.toString();}
 private static void validate(Config c){if(c==null||blank(c.jdbcUrl)||blank(c.user)||c.password==null)throw new IllegalArgumentException("Konfigurasi sumber OJS belum lengkap.");String u=c.jdbcUrl.toLowerCase();if(!(u.startsWith("jdbc:postgresql:")||u.startsWith("jdbc:mysql:")||u.startsWith("jdbc:mariadb:")))throw new IllegalArgumentException("Driver sumber OJS tidak diizinkan.");if(c.jdbcUrl.indexOf('\n')>=0||c.jdbcUrl.indexOf('\r')>=0)throw new IllegalArgumentException("JDBC URL tidak valid.");}
 private static String dialect(String u){String x=u.toLowerCase();return x.startsWith("jdbc:postgresql:")?"POSTGRESQL":x.startsWith("jdbc:mariadb:")?"MARIADB":"MYSQL";}private static String quote(String v){return '"'+v.replace("\"","\"\"")+'"';}private static boolean blank(String v){return v==null||v.trim().length()==0;}
}
