<%-- @generated by generate_new_jsp_scaffold.py
Source: src/ais/action/master/jatelindo/JatelindoRequestAction.java
Generated: 2026-08-06T18:20:20Z
This JSP contains presentation metadata only. Keep business logic in Java services.
--%>
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%
request.setAttribute("nuiModule", "jatelindo");
request.setAttribute("nuiModuleLabel", "Integrasi Jatelindo");
request.setAttribute("nuiPage", "jatelindo_request");
request.setAttribute("nuiPageTitle", "Jatelindo Request");
request.setAttribute("nuiPageType", "finance");
request.setAttribute("nuiPageDescription", "Keuangan untuk Integrasi Jatelindo. Transaksi, status, rekonsiliasi, detail, dan audit keuangan.");
request.setAttribute("nuiSourceClass", "JatelindoRequestAction");
request.setAttribute("nuiSourcePackage", "ais.action.master.jatelindo");
request.setAttribute("nuiSourcePath", "src/ais/action/master/jatelindo/JatelindoRequestAction.java");
request.setAttribute("nuiSourceKind", "class");
request.setAttribute("nuiSourceExtends", "GenericAutowireComposer");
request.setAttribute("nuiSourceImplements", "DataCriteria");
request.setAttribute("nuiSourceMethods", new String[]{"doBeforeCompose", "doAfterCompose", "onEvent", "render", "initCriteria", "onSearchDefault"});
request.setAttribute("nuiLegacyRefs", new String[]{});
request.setAttribute("nuiEntityCandidates", new String[]{"CicilanPembayaran", "JatelindoRequestDetail", "JatelindoRequest"});
%>
<jsp:include page="/WEB-INF/new/_shared/ui/page.jsp" />
