package ais.database.model.asset;

// Generated Apr 16, 2010 2:27:16 PM by Hibernate Tools 3.2.4.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.Session;
import org.hibernate.criterion.Order;
import org.hibernate.envers.Audited;

import ais.database.hibernate.HibernateUtil;
import ais.database.model.GeneralValueObject;
import ais.database.model.akunting.Akun;
import ais.database.model.rab.SatuanKerja;

/**
 * Bank generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Entity(
    dynamicInsert = true,
    dynamicUpdate = true
)
@Audited
@Table(schema = "asset", name = "jenis_penerimaan_barang")
public class JenisPenerimaanBarang extends GeneralValueObject {

	/** 
	 * 
	 */
	private static final long serialVersionUID = 2463821577548439808L;
	private Long id;
	private String oleh;
	private String olehId;

	public String getOlehId() {
		return olehId;
	}

	public void setOlehId(String olehId) {if (olehId == null || olehId.trim().isEmpty()) {return;}
		this.olehId = olehId;
	}

	public void setOleh(String oleh) {if (oleh == null || oleh.trim().isEmpty()) {return;}
		this.oleh = oleh;
	}

	public String getOleh() {
		return oleh;
	}

	@javax.persistence.PreUpdate protected void onUpdate() { ais.database.hibernate.AuditTimestampInterceptor.ubah(this);}     private Date tanggal_dirubah = ais.ui.util.WaktuUtil.getDate();

	public void setTanggal_dirubah(Date tanggal_dirubah) {
		this.tanggal_dirubah = tanggal_dirubah;
	}

	@Temporal(TemporalType.TIMESTAMP)
	public Date getTanggal_dirubah() {
		return tanggal_dirubah;
	}

	public String toString() {
		return id + "-" + nama;
	}

	public static JenisPenerimaanBarang DEFAULT_PENERIMAAN_BARANG_JASA = null;

	public static void reloadDefault() {
		Session session = HibernateUtil.currentNativeSession();
		DEFAULT_PENERIMAAN_BARANG_JASA = (JenisPenerimaanBarang) session.createCriteria(JenisPenerimaanBarang.class)
				.setMaxResults(1).addOrder(Order.asc("id")).uniqueResult();
		if (DEFAULT_PENERIMAAN_BARANG_JASA == null) {
			DEFAULT_PENERIMAAN_BARANG_JASA = new JenisPenerimaanBarang();
			DEFAULT_PENERIMAAN_BARANG_JASA.setKode("001");
			DEFAULT_PENERIMAAN_BARANG_JASA.setAktif(true);
			DEFAULT_PENERIMAAN_BARANG_JASA.setNama("Penerimaan Barang/Jasa");
			DEFAULT_PENERIMAAN_BARANG_JASA.setKeterangan("Penerimaan Barang/Jasa");
			session.getTransaction().begin();
			session.save(DEFAULT_PENERIMAAN_BARANG_JASA);
			session.getTransaction().commit();
		}
		HibernateUtil.closeSession();
	}

	private String kode;
	private Akun akun;
	private Akun akunHutangPenyedia;
	private String nama;
	private String keterangan;
	private SatuanKerja satuanKerja;
	private Boolean aktif;

	public JenisPenerimaanBarang() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", insertable = false, unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getKode() {
		return kode == null ? "" : kode.trim();
	}

	public void setKode(String kode) {
		this.kode = kode;
	}

	@Column(name = "nama", nullable = false, length = 255)
	public String getNama() {
		return this.nama == null ? null : this.nama.trim();
	}

	public void setNama(String nama) {
		this.nama = nama;
	}

	@Column(name = "keterangan", nullable = true)
	public String getKeterangan() {
		return this.keterangan;
	}

	public void setKeterangan(String keterangan) {
		this.keterangan = keterangan;
	}

	public Boolean getAktif() {
		return aktif == null ? true : aktif;
	}

	public void setAktif(Boolean aktif) {
		this.aktif = aktif;
	}

	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY)
	@JoinColumn(name = "akun", nullable = true)
	public Akun getAkun() {
		akun = check(akun);
		return akun;
	}

	public void setAkun(Akun akun) {
		this.akun = akun;
	}

	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY)
	@JoinColumn(name = "satuan_kerja", nullable = true)
	public SatuanKerja getSatuanKerja() {
		satuanKerja = check(satuanKerja);
		return satuanKerja;
	}

	public void setSatuanKerja(SatuanKerja satuanKerja) {
		this.satuanKerja = satuanKerja;
	}

	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY)
	@JoinColumn(name = "akun_hutang_penyedia", nullable = true)
	public Akun getAkunHutangPenyedia() {
		akunHutangPenyedia = check(akunHutangPenyedia);
		return akunHutangPenyedia;
	}

	public void setAkunHutangPenyedia(Akun akunHutangPenyedia) {
		this.akunHutangPenyedia = akunHutangPenyedia;
	}

}
