package ais.database.model.asset;

// Generated Apr 16, 2010 2:27:16 PM by Hibernate Tools 3.2.4.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;
import org.hibernate.envers.Audited;

import ais.database.model.GeneralValueObject;
import ais.database.model.akunting.DaftarPengajuanTransfer;
import ais.database.model.akunting.PostingHistory;
import ais.ui.util.WaktuUtil;

/**
 * Baris rincian pembayaran DP -- satu baris mewakili satu {@link PemesananPengadaanMasterAsset}
 * yang dibayar DP-nya dalam satu dokumen {@link PembayaranDpMasterAsset}. Field {@link #dibayar}
 * menyimpan nilai yang dibayarkan pada baris ini, sedangkan {@link #totalTelahDibayar} menyimpan
 * akumulasi total yang sudah dibayarkan sampai dengan baris ini (dipakai untuk tampilan
 * progres pembayaran, bukan dihitung otomatis oleh entity).
 * <p>
 * Relasi ke {@link #pemesananPengadaanMasterAsset} adalah satu-satunya jalur (tidak langsung)
 * untuk menelusuri kembali ke {@link PerjanjianKerjasamaMasterAsset} yang menjadi payung
 * kontraknya. <b>Tidak ada validasi di lapisan model</b> yang menjumlahkan {@link #dibayar} lintas
 * baris/dokumen dan membandingkannya dengan nilai DP/kontrak yang disepakati -- perluasan
 * langsung dari temuan {@code task_578b720b}.
 *
 * Bank generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Entity(
    dynamicInsert = true,
    dynamicUpdate = true
)
@Audited
@Table(schema = "asset", name = "pembayaran_dp_master_asset_detail")
public class PembayaranDpMasterAssetDetail extends GeneralValueObject {

	/**
	 * Versi serialisasi tetap, diwariskan dari template hbm2java standar paket ini.
	 */
	private static final long serialVersionUID = 2463821577548439808L;
	/** Primary key (identity, auto-increment). */
	private Long id;
	/** Nama pengguna pembuat/pengubah terakhir, dicatat untuk jejak audit tampilan. */
	private String oleh;
	/** Id pengguna pembuat/pengubah terakhir, pasangan dari {@link #oleh}. */
	private String olehId;

	/**
	 * Mengambil id pengguna pembuat/pengubah terakhir.
	 *
	 * @return id pengguna, atau {@code null} bila belum pernah diset.
	 */
	public String getOlehId() {
		return olehId;
	}

	/**
	 * Menyetel id pengguna pembuat/pengubah terakhir. Nilai kosong/blank diabaikan.
	 *
	 * @param olehId id pengguna; nilai {@code null} atau string kosong/blank tidak berefek.
	 */
	public void setOlehId(String olehId) {if (olehId == null || olehId.trim().isEmpty()) {return;}
		this.olehId = olehId;
	}

	/**
	 * Representasi ringkas baris ini untuk log/debug: id, header pembayaran DP, pemesanan
	 * pengadaan, dan keterangan digabung dalam satu string.
	 *
	 * @return string ringkasan baris pembayaran DP ini.
	 */
	public String toString() {
		return id + "-" + pembayaranDpMasterAsset + " " + pemesananPengadaanMasterAsset + " " + getKeterangan();
	}

	/**
	 * Menyetel nama pengguna pembuat/pengubah terakhir. Nilai kosong/blank diabaikan.
	 *
	 * @param oleh nama pengguna; nilai {@code null} atau string kosong/blank tidak berefek.
	 */
	public void setOleh(String oleh) {if (oleh == null || oleh.trim().isEmpty()) {return;}
		this.oleh = oleh;
	}

	/**
	 * Mengambil nama pengguna pembuat/pengubah terakhir.
	 *
	 * @return nama pengguna, atau {@code null} bila belum pernah diset.
	 */
	public String getOleh() {
		return oleh;
	}

	/**
	 * Callback JPA {@code @PreUpdate}: dipanggil otomatis oleh provider sebelum baris di-UPDATE,
	 * mendelegasikan pencatatan waktu perubahan ke {@code AuditTimestampInterceptor.ubah(this)}.
	 */
	@javax.persistence.PreUpdate protected void onUpdate() { ais.database.hibernate.AuditTimestampInterceptor.ubah(this);}     private Date tanggal_dirubah = ais.ui.util.WaktuUtil.getDate();

	/**
	 * Menyetel cap waktu terakhir kali baris ini diubah.
	 *
	 * @param tanggal_dirubah waktu perubahan.
	 */
	public void setTanggal_dirubah(Date tanggal_dirubah) {
		this.tanggal_dirubah = tanggal_dirubah;
	}

	/**
	 * Mengambil cap waktu terakhir kali baris ini diubah.
	 *
	 * @return cap waktu perubahan terakhir.
	 */
	@Temporal(TemporalType.TIMESTAMP)
	public Date getTanggal_dirubah() {
		return tanggal_dirubah;
	}

	/** Header dokumen pembayaran DP yang memiliki baris ini. */
	private PembayaranDpMasterAsset pembayaranDpMasterAsset;
	/** Pemesanan pengadaan yang dibayar DP-nya pada baris ini. */
	private PemesananPengadaanMasterAsset pemesananPengadaanMasterAsset;
	/** Menandakan apakah baris ini dipilih untuk dibayarkan; menentukan apakah {@link #dibayar} berlaku. */
	private Boolean pilih;
	/** Nilai yang dibayarkan pada baris ini; dipaksa {@code 0.0} bila {@link #pilih} bernilai {@code false}. */
	private Double dibayar;
	/** Akumulasi total yang sudah dibayarkan s.d. baris ini (nilai tampilan, bukan hasil hitung otomatis). */
	private Double totalTelahDibayar;
	/** Keterangan bebas untuk baris ini. */
	private String keterangan;

	/** Riwayat posting akuntansi terkait baris pembayaran ini. */
	private PostingHistory postingHistory;
	/** Tanggal pembayaran dibayarkan; fallback ke tanggal pembuatan pemesanan pengadaan atau waktu saat ini. */
	private Date tanggalDibayar;
	/** Pengajuan transfer dana yang merealisasikan pembayaran baris ini. */
	private DaftarPengajuanTransfer daftarPengajuanTransfer;
	/** Tanggal transaksi aktual, diselaraskan dari status realisasi transfer/transitori bila tersedia. */
	private Date tanggalTransaksi;

	/**
	 * Konstruktor default (dipakai Hibernate/JPA saat rehydrasi entity dari database).
	 */
	public PembayaranDpMasterAssetDetail() {
	}

	/**
	 * Mengambil primary key baris ini.
	 *
	 * @return id (identity, auto-increment), atau {@code null} untuk instance yang belum dipersist.
	 */
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", insertable = false, unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	/**
	 * Menyetel primary key. Biasanya hanya dipakai internal oleh Hibernate.
	 *
	 * @param id primary key baris.
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * Mengambil keterangan bebas untuk baris ini, dinormalisasi ke string kosong (bukan
	 * {@code null}) bila belum diset.
	 *
	 * @return keterangan; tidak pernah {@code null}.
	 */
	@Column(name = "keterangan", nullable = true)
	public String getKeterangan() {
		return this.keterangan == null ? "" : keterangan;
	}

	/**
	 * Menyetel keterangan bebas untuk baris ini.
	 *
	 * @param keterangan teks keterangan.
	 */
	public void setKeterangan(String keterangan) {
		this.keterangan = keterangan;
	}

	/**
	 * Mengambil header dokumen pembayaran DP yang memiliki baris ini.
	 *
	 * @return header pembayaran DP, wajib ada ({@code nullable = false} pada kolom database).
	 */
	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE })
	@Fetch(FetchMode.SELECT)
	@JoinColumn(name = "pembayaran_dp_master_asset", nullable = false)
	public PembayaranDpMasterAsset getPembayaranDpMasterAsset() {
		return pembayaranDpMasterAsset;
	}

	/**
	 * Menyetel header dokumen pembayaran DP yang memiliki baris ini.
	 *
	 * @param pembayaranDpMasterAsset header pembayaran DP.
	 */
	public void setPembayaranDpMasterAsset(PembayaranDpMasterAsset pembayaranDpMasterAsset) {
		this.pembayaranDpMasterAsset = pembayaranDpMasterAsset;
	}

	/**
	 * Mengambil nilai yang dibayarkan pada baris ini, dibulatkan ke bilangan bulat terdekat.
	 * Getter destruktif: bila {@link #getPilih()} bernilai {@code false}, field {@link #dibayar}
	 * DIPAKSA menjadi {@code 0.0} pada saat getter dipanggil -- baris yang tidak dipilih dianggap
	 * tidak berkontribusi pada pembayaran meskipun nilai numeriknya sudah pernah diisi
	 * sebelumnya. Tidak ada validasi terhadap total nilai DP kontrak (lihat javadoc kelas).
	 *
	 * @return nilai dibayar (dibulatkan); {@code 0.0} bila tidak dipilih atau belum diset.
	 */
	public Double getDibayar() {

		if (!getPilih()) {
			dibayar = 0.0;
		}
		return (double) Math.round(dibayar == null ? 0.0 : dibayar);
	}

	/**
	 * Menyetel nilai yang dibayarkan pada baris ini. Nilai ini bisa ditimpa menjadi {@code 0.0}
	 * oleh {@link #getDibayar()} bila {@link #pilih} bernilai {@code false}.
	 *
	 * @param dibayar nilai yang dibayarkan.
	 */
	public void setDibayar(Double dibayar) {
		this.dibayar = dibayar;
	}

	/**
	 * Mengambil status pilih baris ini (apakah baris ini disertakan dalam pembayaran).
	 *
	 * @return {@code true} bila dipilih; {@code false} bila belum diset (default tidak dipilih).
	 */
	public Boolean getPilih() {
		return pilih == null ? false : pilih;
	}

	/**
	 * Menyetel status pilih baris ini.
	 *
	 * @param pilih status pilih.
	 */
	public void setPilih(Boolean pilih) {
		this.pilih = pilih;
	}

	/**
	 * Mengambil pemesanan pengadaan yang dibayar DP-nya pada baris ini. Relasi inilah satu-satunya
	 * jalur (tidak langsung) untuk menelusuri kembali ke {@link PerjanjianKerjasamaMasterAsset}.
	 *
	 * @return pemesanan pengadaan, atau {@code null} bila belum diset.
	 */
	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE })
	@Fetch(FetchMode.SELECT)
	@JoinColumn(name = "pemesanan_pengadaan_master_asset", nullable = true)
	public PemesananPengadaanMasterAsset getPemesananPengadaanMasterAsset() {
		return pemesananPengadaanMasterAsset;
	}

	/**
	 * Menyetel pemesanan pengadaan yang dibayar DP-nya pada baris ini.
	 *
	 * @param pemesananPengadaanMasterAsset pemesanan pengadaan.
	 */
	public void setPemesananPengadaanMasterAsset(PemesananPengadaanMasterAsset pemesananPengadaanMasterAsset) {
		this.pemesananPengadaanMasterAsset = pemesananPengadaanMasterAsset;
	}

	/**
	 * Mengambil akumulasi total yang sudah dibayarkan sampai dengan baris ini. Ini adalah field
	 * penyimpanan pasif (dipakai untuk tampilan progres pembayaran) -- BUKAN dihitung otomatis
	 * oleh entity berdasarkan riwayat pembayaran lain, sehingga nilainya sepenuhnya bergantung
	 * pada disiplin lapisan pemanggil (Action/Helper) untuk mengisinya secara benar.
	 *
	 * @return total telah dibayar; {@code 0.0} bila belum diset.
	 */
	public Double getTotalTelahDibayar() {
		return totalTelahDibayar == null ? 0.0 : totalTelahDibayar;
	}

	/**
	 * Menyetel akumulasi total yang sudah dibayarkan sampai dengan baris ini.
	 *
	 * @param totalTelahDibayar total telah dibayar.
	 */
	public void setTotalTelahDibayar(Double totalTelahDibayar) {
		this.totalTelahDibayar = totalTelahDibayar;
	}

	/**
	 * Mengambil riwayat posting akuntansi terkait baris pembayaran ini.
	 *
	 * @return riwayat posting, atau {@code null} bila belum diposting.
	 */
	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE })
	@Fetch(FetchMode.SELECT)
	@JoinColumn(name = "posting_history", nullable = true)
	public PostingHistory getPostingHistory() {
		return postingHistory;
	}

	/**
	 * Menyetel riwayat posting akuntansi terkait baris pembayaran ini.
	 *
	 * @param postingHistory riwayat posting.
	 */
	public void setPostingHistory(PostingHistory postingHistory) {
		this.postingHistory = postingHistory;
	}

	/**
	 * Mengambil tanggal pembayaran dibayarkan. Fallback ke tanggal pembuatan
	 * {@link #getPemesananPengadaanMasterAsset()} bila tersedia, atau ke waktu saat ini
	 * ({@link WaktuUtil#getDate()}) bila pemesanan pengadaan juga belum ada.
	 *
	 * @return tanggal pembayaran; tidak pernah {@code null}.
	 */
	@Temporal(TemporalType.TIMESTAMP)
	public Date getTanggalDibayar() {
		return tanggalDibayar == null
				? (getPemesananPengadaanMasterAsset() != null ? getPemesananPengadaanMasterAsset().getTanggalPembuatan()
						: WaktuUtil.getDate())
				: tanggalDibayar;
	}

	/**
	 * Menyetel tanggal pembayaran dibayarkan secara eksplisit.
	 *
	 * @param tanggalDibayar tanggal pembayaran.
	 */
	public void setTanggalDibayar(Date tanggalDibayar) {
		this.tanggalDibayar = tanggalDibayar;
	}

	/**
	 * Mengambil pengajuan transfer dana yang merealisasikan pembayaran baris ini.
	 *
	 * @return pengajuan transfer, atau {@code null} bila belum ada.
	 */
	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE })
	@Fetch(FetchMode.SELECT)
	@JoinColumn(name = "daftar_pengajuan_transfer", nullable = true)
	public DaftarPengajuanTransfer getDaftarPengajuanTransfer() {
		return daftarPengajuanTransfer;
	}

	/**
	 * Menyetel pengajuan transfer dana yang merealisasikan pembayaran baris ini.
	 *
	 * @param daftarPengajuanTransfer pengajuan transfer.
	 */
	public void setDaftarPengajuanTransfer(DaftarPengajuanTransfer daftarPengajuanTransfer) {
		this.daftarPengajuanTransfer = daftarPengajuanTransfer;
	}

	/**
	 * Mengambil tanggal transaksi aktual. Getter shadow yang mencoba menyelaraskan
	 * {@link #tanggalTransaksi} dari status realisasi {@link #daftarPengajuanTransfer}: bila
	 * transfer bertipe transitori dan sudah punya data proses transitori, dipakai tanggal
	 * pembuatan proses transitori tersebut; bila tidak transitori tapi sudah punya proses
	 * transfer, dipakai tanggal realisasi (atau tanggal pembuatan bila belum direalisasi);
	 * bila tidak ada transfer sama sekali, fallback ke {@link #getTanggalDibayar()}. Seluruh
	 * logika dibungkus {@code try/catch} untuk menahan {@code LazyInitializationException} pada
	 * proxy relasi lintas-Session (dicatat via {@code ErrorAuditUtil}, tidak dilempar ke
	 * pemanggil).
	 *
	 * @return tanggal transaksi aktual.
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "tanggal_transaksi")
	public Date getTanggalTransaksi() {
		try {
			// FIX LazyInitializationException: daftarPengajuanTransfer bisa berupa instance canonical/shared
			// (AuditTimestampInterceptor) yang proxy-nya terikat ke Session lain yang sudah closed
			// -> jangan biarkan getter ini crash, cukup lewati bagian ini (nilai fallback dipertahankan).
			if (getDaftarPengajuanTransfer() != null && daftarPengajuanTransfer.getTransitori()
					&& daftarPengajuanTransfer.getTransitoriData() != null
					&& daftarPengajuanTransfer.getTransitoriData().getProsesTransitori() != null) {
				tanggalTransaksi = daftarPengajuanTransfer.getTransitoriData().getProsesTransitori().getTanggalPembuatan();
			} else if (getDaftarPengajuanTransfer() != null && daftarPengajuanTransfer.getProsesTransfer() != null) {
				tanggalTransaksi = daftarPengajuanTransfer.getProsesTransfer().getTanggalRealisasikan() == null
						? daftarPengajuanTransfer.getProsesTransfer().getTanggalPembuatan()
						: daftarPengajuanTransfer.getProsesTransfer().getTanggalRealisasikan();
			} else {
				tanggalTransaksi = getTanggalDibayar();
			}
		} catch (Exception exLazy) { ais.common.ErrorAuditUtil.record(exLazy, "auto-audit(empty-catch) src/ais/database/model/asset/PembayaranDpMasterAssetDetail.java:getTanggalTransaksi-lazy");
		}
		return tanggalTransaksi;
	}

	/**
	 * Menyetel tanggal transaksi aktual secara langsung. Nilai ini bisa ditimpa kembali oleh
	 * {@link #getTanggalTransaksi()} berdasarkan status realisasi transfer.
	 *
	 * @param tanggalTransaksi tanggal transaksi.
	 */
	public void setTanggalTransaksi(Date tanggalTransaksi) {
		this.tanggalTransaksi = tanggalTransaksi;
	}
}
