package ais.database.model.asset;

// Generated Apr 16, 2010 2:27:16 PM by Hibernate Tools 3.2.4.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;
import org.hibernate.envers.Audited;

import ais.database.model.GeneralValueObject;
import ais.ui.util.WaktuUtil;

/**
 * Bank generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Entity(
    dynamicInsert = true,
    dynamicUpdate = true
)
@Audited
@Table(schema = "asset", name = "peminjaman_master_asset_detail")
public class PeminjamanMasterAssetDetail extends GeneralValueObject {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2463821577548439808L;
	private Long id;
	private String oleh;
	private String olehId;

	public String getOlehId() {
		return olehId;
	}

	public void setOlehId(String olehId) {if (olehId == null || olehId.trim().isEmpty()) {return;}
		this.olehId = olehId;
	}

	public String toString() {
		masterAsset = getMasterAsset();
		return id + "-" + masterAsset + "";
	}

	public void setOleh(String oleh) {if (oleh == null || oleh.trim().isEmpty()) {return;}
		this.oleh = oleh;
	}

	public String getOleh() {
		return oleh;
	}

	@javax.persistence.PreUpdate protected void onUpdate() { ais.database.hibernate.AuditTimestampInterceptor.ubah(this);}     private Date tanggal_dirubah = ais.ui.util.WaktuUtil.getDate();

	public void setTanggal_dirubah(Date tanggal_dirubah) {
		this.tanggal_dirubah = tanggal_dirubah;
	}

	@Temporal(TemporalType.TIMESTAMP)
	public Date getTanggal_dirubah() {
		return tanggal_dirubah;
	}

	private MasterAsset masterAsset;
	private AssetDetail assetDetail;
	private Double hargaBeli;
	private PeminjamanMasterAsset peminjamanMasterAsset;
	private Boolean dikembalikan;
	private Date waktuPengembalian;
	private String keterangan;

	public PeminjamanMasterAssetDetail() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", insertable = false, unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "keterangan", nullable = true)
	public String getKeterangan() {
		return this.keterangan;
	}

	public void setKeterangan(String keterangan) {
		this.keterangan = keterangan;
	}

	public void setMasterAsset(MasterAsset masterAsset) {
		this.masterAsset = masterAsset;
	}

	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY)
	@JoinColumn(name = "master_asset", nullable = true)
	public MasterAsset getMasterAsset() {
		masterAsset = check(masterAsset);
		if (getAssetDetail() != null && getAssetDetail().getAsset() != null) {
			masterAsset = getAssetDetail().getAsset().getMasterAsset();
		}
		return masterAsset;
	}

	public void setPeminjamanMasterAsset(PeminjamanMasterAsset peminjamanMasterAsset) {
		this.peminjamanMasterAsset = peminjamanMasterAsset;
	}

	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE })
	@Fetch(FetchMode.SELECT)
	@JoinColumn(name = "peminjaman_master_asset", nullable = true)
	public PeminjamanMasterAsset getPeminjamanMasterAsset() {
		return peminjamanMasterAsset;
	}

	public Double getHargaBeli() {
		return hargaBeli == null ? 0.0 : hargaBeli;
	}

	public void setHargaBeli(Double hargaBeli) {
		this.hargaBeli = hargaBeli;
	}

	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE })
	@Fetch(FetchMode.SELECT)
	@JoinColumn(name = "asset_detail", nullable = true)
	public AssetDetail getAssetDetail() {
		return assetDetail;
	}

	public void setAssetDetail(AssetDetail assetDetail) {
		this.assetDetail = assetDetail;
	}

	public Boolean getDikembalikan() {
		return dikembalikan == null ? false : dikembalikan;
	}

	public void setDikembalikan(Boolean dikembalikan) {
		this.dikembalikan = dikembalikan;
	}

	@Temporal(TemporalType.TIMESTAMP)
	public Date getWaktuPengembalian() {
		if (getDikembalikan() && waktuPengembalian == null) {
			waktuPengembalian = WaktuUtil.getDate();
		}
		return waktuPengembalian;
	}

	public void setWaktuPengembalian(Date waktuPengembalian) {
		this.waktuPengembalian = waktuPengembalian;
	}

}
