package ais.action.master.generic.v2.adapter;
import java.util.*;import org.hibernate.*;import org.hibernate.criterion.*;import org.json.JSONObject;
import ais.action.master.bni.BniBackandProsess;import ais.action.master.generic.v2.*;import ais.action.servlet.Bniresponse;import ais.common.Common;import ais.database.hibernate.HibernateUtil;import ais.database.model.*;import ais.database.model.bni.*;import ais.database.model.sekolah.Siswa;
/** Parity BniRequestAction: report/detail, inquiry tunggal, check-all, dan hapus transaksi gagal oleh admin. */
@SuppressWarnings({"rawtypes","unchecked"})public class BniRequestGenericCrudAdapter extends AbstractPaymentRequestReadOnlyAdapter<BniRequest>{
 protected Mahasiswa owner(BniRequest x){return x==null?null:x.getMahasiswa();}protected Siswa schoolOwner(BniRequest x){return x==null?null:x.getSiswa();}protected Class requestType(){return BniRequest.class;}protected Class detailType(){return BniRequestDetail.class;}protected String detailRequestProperty(){return "bniRequest";}
 public List getActions(GenericCrudDefinition d,GenericCrudRequestContext c){List r=super.getActions(d,c);r.add(action("check_payment","Cek Pembayaran","SINGLE",GenericCrudOperation.UPDATE,c!=null&&c.isCanUpdate(),"tampilkan_check_ulang_pembayaran_via_bni"));r.add(action("check_all","Check Ulang Semua","NONE",GenericCrudOperation.UPDATE,c!=null&&c.isCanUpdate(),"aktifkan_tombol_check_ulang_bni"));r.add(action("delete_failed","Hapus Transaksi Gagal","SINGLE",GenericCrudOperation.DELETE,c!=null&&c.isCanDelete()&&admin(),null));return r;}private Map action(String k,String l,String m,String privilege,boolean enabled,String cfg){Map a=new LinkedHashMap();a.put("actionKey",k);a.put("label",l);a.put("requiredPrivilege",privilege);a.put("selectionMode",m);a.put("enabled",Boolean.valueOf(enabled));if(cfg!=null)a.put("configurationKey",cfg);a.put("confirmation",l+" BNI?");return a;}
 public GenericCrudResult execute(String k,List ids,Map p,GenericCrudRequestContext c)throws Exception{if(!"check_payment".equals(k)&&!"check_all".equals(k)&&!"delete_failed".equals(k))return super.execute(k,ids,p,c);if("delete_failed".equals(k))return delete(ids,c);if(c==null||!c.isCanUpdate())throw new GenericCrudException(403,"UPDATE_REQUIRED","Hak UPDATE diperlukan untuk mengecek pembayaran.");if("check_all".equals(k))return all(c);Long id=id(ids);Session s=HibernateUtil.currentNativeSession();JSONObject o=null;try{BniRequest x=(BniRequest)s.get(BniRequest.class,id);if(x==null)throw new GenericCrudException(404,"ROW_NOT_FOUND","Request BNI tidak ditemukan.");new GenericCrudScopeGuard().validateObject(x,c);o=one(s,x);}catch(Exception e){rollback(s);throw e;}finally{HibernateUtil.closeSessionQuietly(s);}Map data=new LinkedHashMap();data.put("id",id);data.put("gatewayResponse",o==null?null:o.toString());return GenericCrudResult.ok("Cek pembayaran BNI selesai.",data);}
 private GenericCrudResult delete(List ids,GenericCrudRequestContext c)throws Exception{if(c==null||!c.isCanDelete()||!admin())throw new GenericCrudException(403,"DELETE_REQUIRED","Hanya admin dengan hak DELETE dapat menghapus transaksi gagal.");Long id=id(ids);Session s=HibernateUtil.currentNativeSession();try{BniRequest x=(BniRequest)s.get(BniRequest.class,id);if(x==null)throw new GenericCrudException(404,"ROW_NOT_FOUND","Request BNI tidak ditemukan.");new GenericCrudScopeGuard().validateObject(x,c);if("Payment Sukses".equalsIgnoreCase(x.getStatus()))throw new GenericCrudException(409,"SUCCESS_PAYMENT_PROTECTED","Transaksi sukses tidak boleh dihapus.");begin(s);s.delete(x);s.getTransaction().commit();}catch(Exception e){rollback(s);throw e;}finally{HibernateUtil.closeSessionQuietly(s);}return GenericCrudResult.ok("Transaksi BNI gagal telah dihapus.",id);}
 private GenericCrudResult all(GenericCrudRequestContext c)throws Exception{if(!Common.bolehKonfigurasi("aktifkan_tombol_check_ulang_bni"))throw new GenericCrudException(403,"FEATURE_DISABLED","Fitur Check Ulang Semua BNI tidak aktif.");Session s=HibernateUtil.currentNativeSession();int ok=0,fail=0;try{Criteria q=s.createCriteria(BniRequest.class).addOrder(Order.desc("id"));applyReadScope(q,c);List rows=q.setMaxResults(1000).list();for(int i=0;i<rows.size();i++)try{one(s,(BniRequest)rows.get(i));ok++;}catch(Exception e){rollback(s);fail++;}}finally{HibernateUtil.closeSessionQuietly(s);}Map d=new LinkedHashMap();d.put("success",Integer.valueOf(ok));d.put("failed",Integer.valueOf(fail));return GenericCrudResult.ok("Check ulang BNI selesai: "+ok+" berhasil, "+fail+" gagal.",d);}
 private JSONObject one(Session s,BniRequest x)throws Exception{s.refresh(x);if(x.getKegiatanTemporarys().isEmpty()&&x.getSiswa()==null&&x.getCalonSiswa()==null){Kegiatan k=Bniresponse.createKegiatan(x,s);List rows=s.createCriteria(CicilanPembayaran.class).add(Restrictions.isNotNull("itemBiaya")).add(Restrictions.eq("kegiatan",k)).addOrder(Order.asc("tanggal")).addOrder(Order.asc("ke")).list();for(int i=0;i<rows.size();i++)detail(s,x,(CicilanPembayaran)rows.get(i));}x.setHapusCicilanSebelumnya(Boolean.TRUE);x.setCheckUlang(Boolean.TRUE);return BniBackandProsess.check(url(x),x,s,true);}
 private String url(BniRequest x){String ip=Common.getKonfigurasi("bni_ip_client","").getNilai();if(ip!=null&&!ip.trim().isEmpty())return ip+"/BniForwarder";if(!Common.bolehKonfigurasi("tambahkan_merchan_id_di_bni"))return Common.getKonfigurasi("bni_inquiry_gateway_url","https://billing-bpi.maja.id/bni/inquiry/").getNilai();if(x.getSiswa()!=null&&x.getSiswa().getSekolah()!=null&&x.getSiswa().getSekolah().getBniGatewayUrl()!=null&&!x.getSiswa().getSekolah().getBniGatewayUrl().isEmpty())return x.getSiswa().getSekolah().getBniGatewayUrl();return Common.getKonfigurasi("bni_gateway_url","https://apibeta.bni-ecollection.com/").getNilai();}
 private void detail(Session s,BniRequest x,CicilanPembayaran c){Number n=(Number)s.createCriteria(BniRequestDetail.class).add(Restrictions.eq("bniRequest",x)).add(Restrictions.eq("pengaturanPembayaranBulanan",c.getPengaturanPembayaranBulanan())).setProjection(Projections.rowCount()).uniqueResult();if(n!=null&&n.longValue()>0)return;BniRequestDetail d=new BniRequestDetail();d.setBniRequest(x);d.setPengaturanPembayaranBulanan(c.getPengaturanPembayaranBulanan());d.setItemBiaya(c.getItemBiaya());d.setDetailBiaya(c.getDetailBiaya());d.setIdCicilan(c.getId());d.setKeterangan(c.getKeterangan());d.setNilai(c.getNilai());d.setTanggal(c.getTanggal());d.setKe(Integer.valueOf(0));d.setDenda(c.getDenda());d.setNilaiAsli(c.getNilaiAsli());begin(s);Common.refreshSaveOrUpdate(s,d);s.getTransaction().commit();}private boolean admin(){try{return Common.getApakahAdmin();}catch(Throwable e){return false;}}private Long id(List x)throws GenericCrudException{try{return Long.valueOf(String.valueOf(x.get(0)));}catch(Exception e){throw new GenericCrudException(400,"ROW_ID_INVALID","ID BNI tidak valid.");}}private void begin(Session s){if(!s.getTransaction().isActive())s.getTransaction().begin();}private void rollback(Session s){try{if(s.getTransaction().isActive())s.getTransaction().rollback();}catch(Exception e){}}
}
