package ais.action.master.generic.v2.adapter;

import java.util.LinkedHashMap;import java.util.List;import java.util.Map;
import org.hibernate.Session;import org.hibernate.criterion.Order;import org.hibernate.criterion.Projections;import org.hibernate.criterion.Restrictions;
import org.json.JSONObject;
import ais.action.master.bri.BriBackandProsess;import ais.action.master.generic.v2.*;import ais.action.servlet.Briresponse;import ais.common.Common;
import ais.database.hibernate.HibernateUtil;import ais.database.model.*;import ais.database.model.bri.*;import ais.database.model.sekolah.Siswa;
/** Parity BriRequestAction untuk laporan/rincian dan cek status BRIVA. */
@SuppressWarnings({"rawtypes","unchecked"}) public class BriRequestGenericCrudAdapter extends AbstractPaymentRequestReadOnlyAdapter<BriRequest>{
 protected Mahasiswa owner(BriRequest x){return x==null?null:x.getMahasiswa();} protected Siswa schoolOwner(BriRequest x){return x==null?null:x.getSiswa();}
 protected Class requestType(){return BriRequest.class;} protected Class detailType(){return BriRequestDetail.class;} protected String detailRequestProperty(){return "briRequest";}
 public List getActions(GenericCrudDefinition d,GenericCrudRequestContext c){List r=super.getActions(d,c);Map a=new LinkedHashMap();a.put("actionKey","check_payment");a.put("label","Cek Pembayaran");a.put("requiredPrivilege",GenericCrudOperation.UPDATE);a.put("selectionMode","SINGLE");a.put("enabled",Boolean.valueOf(c!=null&&c.isCanUpdate()));a.put("confirmation","Cek ulang status pembayaran BRIVA?");r.add(a);return r;}
 public GenericCrudResult execute(String k,List ids,Map p,GenericCrudRequestContext c)throws Exception{if(!"check_payment".equals(k))return super.execute(k,ids,p,c);if(c==null||!c.isCanUpdate())throw new GenericCrudException(403,"UPDATE_REQUIRED","Hak UPDATE diperlukan untuk mengecek pembayaran.");Long id;try{id=Long.valueOf(String.valueOf(ids.get(0)));}catch(Exception e){throw new GenericCrudException(400,"ROW_ID_INVALID","ID BRI tidak valid.");}Session s=HibernateUtil.currentNativeSession();JSONObject response=null;try{BriRequest x=(BriRequest)s.get(BriRequest.class,id);if(x==null)throw new GenericCrudException(404,"ROW_NOT_FOUND","Request BRI tidak ditemukan.");new GenericCrudScopeGuard().validateObject(x,c);s.refresh(x);if(x.getKegiatanTemporarys().isEmpty()&&x.getSiswa()==null&&x.getCalonSiswa()==null){Kegiatan kegiatan=Briresponse.createKegiatan(x,s);List cicilan=s.createCriteria(CicilanPembayaran.class).add(Restrictions.isNotNull("itemBiaya")).add(Restrictions.eq("kegiatan",kegiatan)).addOrder(Order.asc("tanggal")).addOrder(Order.asc("ke")).list();for(int i=0;i<cicilan.size();i++)detail(s,x,(CicilanPembayaran)cicilan.get(i));s.refresh(x);}x.setHapusCicilanSebelumnya(Boolean.TRUE);x.setCheckUlang(Boolean.TRUE);begin(s);Common.refreshUpdate(s,x);s.getTransaction().commit();response=BriBackandProsess.checkSatu(x,s);}catch(Exception e){try{if(s.getTransaction().isActive())s.getTransaction().rollback();}catch(Exception z){}throw e;}finally{HibernateUtil.closeSessionQuietly(s);}Map data=new LinkedHashMap();data.put("id",id);data.put("gatewayResponse",response==null?null:response.toString());return GenericCrudResult.ok("Cek pembayaran BRI selesai.",data);}
 private void detail(Session s,BriRequest x,CicilanPembayaran c){Number n=(Number)s.createCriteria(BriRequestDetail.class).add(Restrictions.eq("briRequest",x)).add(Restrictions.eq("pengaturanPembayaranBulanan",c.getPengaturanPembayaranBulanan())).setProjection(Projections.rowCount()).uniqueResult();if(n!=null&&n.longValue()>0)return;BriRequestDetail d=new BriRequestDetail();d.setBriRequest(x);d.setPengaturanPembayaranBulanan(c.getPengaturanPembayaranBulanan());d.setItemBiaya(c.getItemBiaya());d.setDetailBiaya(c.getDetailBiaya());d.setIdCicilan(c.getId());d.setKeterangan(c.getKeterangan());d.setNilai(c.getNilai());d.setTanggal(c.getTanggal());d.setKe(Integer.valueOf(0));d.setDenda(c.getDenda());d.setNilaiAsli(c.getNilaiAsli());begin(s);Common.refreshSaveOrUpdate(s,d);s.getTransaction().commit();}
 private void begin(Session s){if(!s.getTransaction().isActive())s.getTransaction().begin();}
}
