package ais.action.master.generic.v2.adapter;
import java.util.*;import org.hibernate.*;import org.hibernate.criterion.*;import org.json.JSONObject;
import ais.action.master.bsi.BsiBackandProsess;import ais.action.master.generic.v2.*;import ais.action.servlet.Bsiresponse;import ais.common.Common;import ais.database.hibernate.HibernateUtil;import ais.database.model.*;import ais.database.model.bsi.*;import ais.database.model.sekolah.Siswa;
/** Parity BsiRequestAction termasuk inquiry tunggal dan check-all terkonfigurasi. */
@SuppressWarnings({"rawtypes","unchecked"})public class BsiRequestGenericCrudAdapter extends AbstractPaymentRequestReadOnlyAdapter<BsiRequest>{
 protected Mahasiswa owner(BsiRequest x){return x==null?null:x.getMahasiswa();}protected Siswa schoolOwner(BsiRequest x){return x==null?null:x.getSiswa();}protected Class requestType(){return BsiRequest.class;}protected Class detailType(){return BsiRequestDetail.class;}protected String detailRequestProperty(){return "bsiRequest";}
 public List getActions(GenericCrudDefinition d,GenericCrudRequestContext c){List r=super.getActions(d,c);r.add(action("check_payment","Cek Pembayaran","SINGLE",c,"tampilkan_check_ulang_pembayaran_via_bsi"));r.add(action("check_all","Check Ulang Semua","NONE",c,"aktifkan_tombol_check_ulang_bsi"));return r;}private Map action(String k,String l,String m,GenericCrudRequestContext c,String cfg){Map a=new LinkedHashMap();a.put("actionKey",k);a.put("label",l);a.put("requiredPrivilege",GenericCrudOperation.UPDATE);a.put("selectionMode",m);a.put("enabled",Boolean.valueOf(c!=null&&c.isCanUpdate()));a.put("configurationKey",cfg);a.put("confirmation",l+" BSI?");return a;}
 public GenericCrudResult execute(String k,List ids,Map p,GenericCrudRequestContext c)throws Exception{if(!"check_payment".equals(k)&&!"check_all".equals(k))return super.execute(k,ids,p,c);if(c==null||!c.isCanUpdate())throw new GenericCrudException(403,"UPDATE_REQUIRED","Hak UPDATE diperlukan untuk mengecek pembayaran.");if("check_all".equals(k))return all(c);Long id;try{id=Long.valueOf(String.valueOf(ids.get(0)));}catch(Exception e){throw new GenericCrudException(400,"ROW_ID_INVALID","ID BSI tidak valid.");}Session s=HibernateUtil.currentNativeSession();JSONObject o=null;try{BsiRequest x=(BsiRequest)s.get(BsiRequest.class,id);if(x==null)throw new GenericCrudException(404,"ROW_NOT_FOUND","Request BSI tidak ditemukan.");new GenericCrudScopeGuard().validateObject(x,c);o=one(s,x);}catch(Exception e){rollback(s);throw e;}finally{HibernateUtil.closeSessionQuietly(s);}Map data=new LinkedHashMap();data.put("id",id);data.put("gatewayResponse",o==null?null:o.toString());return GenericCrudResult.ok("Cek pembayaran BSI selesai.",data);}
 private GenericCrudResult all(GenericCrudRequestContext c)throws Exception{if(!Common.bolehKonfigurasi("aktifkan_tombol_check_ulang_bsi"))throw new GenericCrudException(403,"FEATURE_DISABLED","Fitur Check Ulang Semua BSI tidak aktif.");Session s=HibernateUtil.currentNativeSession();int ok=0,fail=0;try{Criteria q=s.createCriteria(BsiRequest.class).addOrder(Order.desc("id"));applyReadScope(q,c);List rows=q.setMaxResults(1000).list();for(int i=0;i<rows.size();i++)try{one(s,(BsiRequest)rows.get(i));ok++;}catch(Exception e){rollback(s);fail++;}}finally{HibernateUtil.closeSessionQuietly(s);}Map d=new LinkedHashMap();d.put("success",Integer.valueOf(ok));d.put("failed",Integer.valueOf(fail));return GenericCrudResult.ok("Check ulang BSI selesai: "+ok+" berhasil, "+fail+" gagal.",d);}
 private JSONObject one(Session s,BsiRequest x)throws Exception{s.refresh(x);if(x.getKegiatanTemporarys().isEmpty()&&x.getSiswa()==null&&x.getCalonSiswa()==null){Kegiatan k=Bsiresponse.createKegiatan(x,s);List rows=s.createCriteria(CicilanPembayaran.class).add(Restrictions.isNotNull("itemBiaya")).add(Restrictions.eq("kegiatan",k)).addOrder(Order.asc("tanggal")).addOrder(Order.asc("ke")).list();for(int i=0;i<rows.size();i++)detail(s,x,(CicilanPembayaran)rows.get(i));s.refresh(x);}x.setHapusCicilanSebelumnya(Boolean.TRUE);x.setCheckUlang(Boolean.TRUE);begin(s);Common.refreshUpdate(s,x);s.getTransaction().commit();return BsiBackandProsess.check(url(x),x,s);}
 private String url(BsiRequest x){String ip=Common.getKonfigurasi("bsi_ip_client","").getNilai();if(ip!=null&&!ip.trim().isEmpty())return ip+"/BsiForwarder";if(!Common.bolehKonfigurasi("tambahkan_merchan_id_di_bsi"))return Common.getKonfigurasi("bsi_inquiry_gateway_url","https://billing-bpi.maja.id/bsi/inquiry/").getNilai();if(x.getSiswa()!=null&&x.getSiswa().getSekolah()!=null&&x.getSiswa().getSekolah().getBsiGatewayUrl()!=null&&!x.getSiswa().getSekolah().getBsiGatewayUrl().isEmpty())return x.getSiswa().getSekolah().getBsiGatewayUrl();return Common.getKonfigurasi("bsi_gateway_url","https://apibeta.bsi-ecollection.com/").getNilai();}
 private void detail(Session s,BsiRequest x,CicilanPembayaran c){Number n=(Number)s.createCriteria(BsiRequestDetail.class).add(Restrictions.eq("bsiRequest",x)).add(Restrictions.eq("pengaturanPembayaranBulanan",c.getPengaturanPembayaranBulanan())).setProjection(Projections.rowCount()).uniqueResult();if(n!=null&&n.longValue()>0)return;BsiRequestDetail d=new BsiRequestDetail();d.setBsiRequest(x);d.setPengaturanPembayaranBulanan(c.getPengaturanPembayaranBulanan());d.setItemBiaya(c.getItemBiaya());d.setDetailBiaya(c.getDetailBiaya());d.setIdCicilan(c.getId());d.setKeterangan(c.getKeterangan());d.setNilai(c.getNilai());d.setTanggal(c.getTanggal());d.setKe(Integer.valueOf(0));d.setDenda(c.getDenda());d.setNilaiAsli(c.getNilaiAsli());begin(s);Common.refreshSaveOrUpdate(s,d);s.getTransaction().commit();}private void begin(Session s){if(!s.getTransaction().isActive())s.getTransaction().begin();}private void rollback(Session s){try{if(s.getTransaction().isActive())s.getTransaction().rollback();}catch(Exception e){}}
}
