<%-- @generated by generate_new_jsp_scaffold.py
Source: src/ais/action/master/asset/SatuanMasterAssetAction.java
Generated: 2026-08-06T18:20:20Z
This JSP contains presentation metadata only. Keep business logic in Java services.
--%>
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%
request.setAttribute("nuiModule", "asset");
request.setAttribute("nuiModuleLabel", "Aset & Pengadaan");
request.setAttribute("nuiPage", "satuan_master_asset");
request.setAttribute("nuiPageTitle", "Satuan Master Asset");
request.setAttribute("nuiPageType", "inventory");
request.setAttribute("nuiPageDescription", "Operasional untuk Aset & Pengadaan. Stok/aset, pergerakan, status, dan tindakan operasional.");
request.setAttribute("nuiSourceClass", "SatuanMasterAssetAction");
request.setAttribute("nuiSourcePackage", "ais.action.master.asset");
request.setAttribute("nuiSourcePath", "src/ais/action/master/asset/SatuanMasterAssetAction.java");
request.setAttribute("nuiSourceKind", "class");
request.setAttribute("nuiSourceExtends", "GenericAutowireComposer");
request.setAttribute("nuiSourceImplements", "");
request.setAttribute("nuiSourceMethods", new String[]{"doBeforeCompose", "doAfterCompose", "onEvent", "render", "onAdd", "onSave", "initCriteria", "onSearchDefault", "checkNamaSatuanMasterAsset"});
request.setAttribute("nuiLegacyRefs", new String[]{});
request.setAttribute("nuiEntityCandidates", new String[]{"SatuanMasterAsset"});
%>
<jsp:include page="/WEB-INF/new/_shared/ui/page.jsp" />
