<%-- @generated by generate_new_jsp_scaffold.py
Source: src/ais/action/master/sirs/jadwal_dokter/CalendarJadwalDokterComposer.java
Generated: 2026-08-06T18:20:20Z
This JSP contains presentation metadata only. Keep business logic in Java services.
--%>
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%
request.setAttribute("nuiModule", "sirs");
request.setAttribute("nuiModuleLabel", "SIRS / Klinik / Rumah Sakit");
request.setAttribute("nuiPage", "jadwal_dokter/calendar_jadwal_dokter");
request.setAttribute("nuiPageTitle", "Calendar Jadwal Dokter");
request.setAttribute("nuiPageType", "inventory");
request.setAttribute("nuiPageDescription", "Operasional untuk SIRS / Klinik / Rumah Sakit. Stok/aset, pergerakan, status, dan tindakan operasional.");
request.setAttribute("nuiSourceClass", "CalendarJadwalDokterComposer");
request.setAttribute("nuiSourcePackage", "ais.action.master.sirs.jadwal_dokter");
request.setAttribute("nuiSourcePath", "src/ais/action/master/sirs/jadwal_dokter/CalendarJadwalDokterComposer.java");
request.setAttribute("nuiSourceKind", "class");
request.setAttribute("nuiSourceExtends", "GenericForwardComposer");
request.setAttribute("nuiSourceImplements", "");
request.setAttribute("nuiSourceMethods", new String[]{"onBack", "onNext", "onEvent", "onRefresh", "doAfterCompose", "onMoveDate", "onToday", "onSwitchTimeZone", "onUpdateFirstDayOfWeek", "onUpdateView", "onSave", "onSearchDefault"});
request.setAttribute("nuiEntityCandidates", new String[]{"Shift", "Poly", "JadwalDokter"});
%>
<jsp:include page="/WEB-INF/new/_shared/ui/page.jsp" />
