<%-- @generated by generate_new_jsp_scaffold.py
Source: src/ais/action/master/helper/util/SmartlinkChannelWindow.java
Generated: 2026-08-06T18:20:20Z
Safe service-adapter scaffold. Implement data access in a Java service layer, not directly in this JSP.
--%>
<%@ page language="java" contentType="application/json; charset=UTF-8" pageEncoding="UTF-8" %>
<%
request.setAttribute("nuiServiceModule", "helper");
request.setAttribute("nuiServicePage", "util/smartlink_channel");
request.setAttribute("nuiServiceTitle", "Smartlink Channel");
request.setAttribute("nuiServiceType", "list");
request.setAttribute("nuiServiceSourceClass", "SmartlinkChannelWindow");
request.setAttribute("nuiServiceSourcePackage", "ais.action.master.helper.util");
request.setAttribute("nuiServiceSourcePath", "src/ais/action/master/helper/util/SmartlinkChannelWindow.java");
request.setAttribute("nuiServiceMethods", new String[]{"doBeforeCompose", "doAfterCompose", "parseEntriKanal", "isiRadioKanal", "init", "onEvent"});
request.setAttribute("nuiServiceEntities", new String[]{"Siswa", "CalonSiswa", "Tagihan", "BankHost", "AkunPembayaranSiswa"});
%>
<jsp:include page="/WEB-INF/new/_shared/services/dispatcher.jsp" />
