<%-- @generated by generate_new_jsp_scaffold.py
Source: src/ais/action/master/bkd/helper/BkdKknHelper.java
Generated: 2026-08-06T18:20:20Z
Safe service-adapter scaffold. Implement data access in a Java service layer, not directly in this JSP.
--%>
<%@ page language="java" contentType="application/json; charset=UTF-8" pageEncoding="UTF-8" %>
<%
request.setAttribute("nuiServiceModule", "bkd");
request.setAttribute("nuiServicePage", "helper/bkd_kkn_helper");
request.setAttribute("nuiServiceTitle", "BKD KKN Helper");
request.setAttribute("nuiServiceType", "academic");
request.setAttribute("nuiServiceSourceClass", "BkdKknHelper");
request.setAttribute("nuiServiceSourcePackage", "ais.action.master.bkd.helper");
request.setAttribute("nuiServiceSourcePath", "src/ais/action/master/bkd/helper/BkdKknHelper.java");
request.setAttribute("nuiServiceMethods", new String[]{"populate"});
request.setAttribute("nuiServiceEntities", new String[]{"Jenjang", "MahasiswaDapatKelompokKkn", "AsesorPegawai", "AsesemenPenilaian"});
%>
<jsp:include page="/WEB-INF/new/_shared/services/dispatcher.jsp" />
