<%-- @generated by generate_new_jsp_scaffold.py
Source: src/ais/action/master/bkd/helper/StatusKewajibanBebanDosenDetailAction.java
Generated: 2026-08-06T18:20:20Z
Safe service-adapter scaffold. Implement data access in a Java service layer, not directly in this JSP.
--%>
<%@ page language="java" contentType="application/json; charset=UTF-8" pageEncoding="UTF-8" %>
<%
request.setAttribute("nuiServiceModule", "bkd");
request.setAttribute("nuiServicePage", "helper/status_kewajiban_beban_dosen_detail");
request.setAttribute("nuiServiceTitle", "Status Kewajiban Beban Dosen Detail");
request.setAttribute("nuiServiceType", "academic");
request.setAttribute("nuiServiceSourceClass", "StatusKewajibanBebanDosenDetailAction");
request.setAttribute("nuiServiceSourcePackage", "ais.action.master.bkd.helper");
request.setAttribute("nuiServiceSourcePath", "src/ais/action/master/bkd/helper/StatusKewajibanBebanDosenDetailAction.java");
request.setAttribute("nuiServiceMethods", new String[]{"onEvent", "render", "initCriteria", "loadData", "display"});
request.setAttribute("nuiServiceEntities", new String[]{"Dosen"});
%>
<jsp:include page="/WEB-INF/new/_shared/services/dispatcher.jsp" />
