<%-- @generated by generate_new_jsp_scaffold.py
Source: src/ais/action/master/sapto/JenisDanaPenerimaanSaptoAction.java
Generated: 2026-08-06T18:20:20Z
Safe service-adapter scaffold. Implement data access in a Java service layer, not directly in this JSP.
--%>
<%@ page language="java" contentType="application/json; charset=UTF-8" pageEncoding="UTF-8" %>
<%
request.setAttribute("nuiServiceModule", "sapto");
request.setAttribute("nuiServicePage", "jenis_dana_penerimaan_sapto");
request.setAttribute("nuiServiceTitle", "Jenis Dana Penerimaan SAPTO");
request.setAttribute("nuiServiceType", "integration");
request.setAttribute("nuiServiceSourceClass", "JenisDanaPenerimaanSaptoAction");
request.setAttribute("nuiServiceSourcePackage", "ais.action.master.sapto");
request.setAttribute("nuiServiceSourcePath", "src/ais/action/master/sapto/JenisDanaPenerimaanSaptoAction.java");
request.setAttribute("nuiServiceMethods", new String[]{"doBeforeCompose", "doAfterCompose", "onEvent", "render", "onAdd", "init", "onSave", "initCriteria", "onSearchDefault", "checkNamaJenisDanaPenerimaanSapto"});
request.setAttribute("nuiServiceEntities", new String[]{"JenisDanaPenerimaanSapto"});
%>
<jsp:include page="/WEB-INF/new/_shared/services/dispatcher.jsp" />
