<%-- @generated by generate_new_jsp_scaffold.py
Source: src/ais/action/master/AkreditasiAction.java
Generated: 2026-08-06T18:20:20Z
This JSP contains presentation metadata only. Keep business logic in Java services.
--%>
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%
request.setAttribute("nuiModule", "root");
request.setAttribute("nuiModuleLabel", "Modul Inti");
request.setAttribute("nuiPage", "akreditasi");
request.setAttribute("nuiPageTitle", "Akreditasi");
request.setAttribute("nuiPageType", "finance");
request.setAttribute("nuiPageDescription", "Keuangan untuk Modul Inti. Transaksi, status, rekonsiliasi, detail, dan audit keuangan.");
request.setAttribute("nuiSourceClass", "AkreditasiAction");
request.setAttribute("nuiSourcePackage", "ais.action.master");
request.setAttribute("nuiSourcePath", "src/ais/action/master/AkreditasiAction.java");
request.setAttribute("nuiSourceKind", "class");
request.setAttribute("nuiSourceExtends", "GenericAutowireComposer");
request.setAttribute("nuiSourceImplements", "DataCriteria, DataSearchDefault, DataInitDefault");
request.setAttribute("nuiSourceMethods", new String[]{"doBeforeCompose", "doAfterCompose", "onEvent", "render", "getDspace", "getDspaceDokumenAkreditasi", "onAdd", "init", "onSave", "initCriteria", "onSearchDefault"});
request.setAttribute("nuiLegacyRefs", new String[]{});
request.setAttribute("nuiEntityCandidates", new String[]{"Dosen", "Akreditasi", "DokumenAkreditasi", "Jurusan"});
%>
<jsp:include page="/WEB-INF/new/_shared/ui/page.jsp" />
