<%-- @generated by generate_new_jsp_scaffold.py
Source: src/ais/action/master/BaypassPembayaranMahasiswaAction.java
Generated: 2026-08-06T18:20:20Z
This JSP contains presentation metadata only. Keep business logic in Java services.
--%>
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%
request.setAttribute("nuiModule", "root");
request.setAttribute("nuiModuleLabel", "Modul Inti");
request.setAttribute("nuiPage", "baypass_pembayaran_mahasiswa");
request.setAttribute("nuiPageTitle", "Baypass Pembayaran Mahasiswa");
request.setAttribute("nuiPageType", "finance");
request.setAttribute("nuiPageDescription", "Keuangan untuk Modul Inti. Transaksi, status, rekonsiliasi, detail, dan audit keuangan.");
request.setAttribute("nuiSourceClass", "BaypassPembayaranMahasiswaAction");
request.setAttribute("nuiSourcePackage", "ais.action.master");
request.setAttribute("nuiSourcePath", "src/ais/action/master/BaypassPembayaranMahasiswaAction.java");
request.setAttribute("nuiSourceKind", "class");
request.setAttribute("nuiSourceExtends", "GenericAutowireComposer");
request.setAttribute("nuiSourceImplements", "DataLoader, DataCriteria, DataSearchDefault");
request.setAttribute("nuiSourceMethods", new String[]{"doBeforeCompose", "doAfterCompose", "onEvent", "run", "render", "initCriteria", "onSearchDefault", "onAdd", "onSave", "loadData"});
request.setAttribute("nuiEntityCandidates", new String[]{"StatusMahasiswa", "StatusAwalMahasiswa", "Konsentrasi", "Fakultas", "Jurusan", "Jenjang", "BaypassPembayaranMahasiswa", "JenisKegiatan"});
%>
<jsp:include page="/WEB-INF/new/_shared/ui/page.jsp" />
