<%-- @generated by generate_new_jsp_scaffold.py
Source: src/ais/action/master/KelompokParameterTambahanPengajuanPegawaiAction.java
Generated: 2026-08-06T18:20:20Z
This JSP contains presentation metadata only. Keep business logic in Java services.
--%>
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%
request.setAttribute("nuiModule", "root");
request.setAttribute("nuiModuleLabel", "Modul Inti");
request.setAttribute("nuiPage", "kelompok_parameter_tambahan_pengajuan_pegawai");
request.setAttribute("nuiPageTitle", "Kelompok Parameter Tambahan Pengajuan Pegawai");
request.setAttribute("nuiPageType", "workflow");
request.setAttribute("nuiPageDescription", "Workflow untuk Modul Inti. Antrian kerja, persetujuan, timeline, SLA, dan tindak lanjut.");
request.setAttribute("nuiSourceClass", "KelompokParameterTambahanPengajuanPegawaiAction");
request.setAttribute("nuiSourcePackage", "ais.action.master");
request.setAttribute("nuiSourcePath", "src/ais/action/master/KelompokParameterTambahanPengajuanPegawaiAction.java");
request.setAttribute("nuiSourceKind", "class");
request.setAttribute("nuiSourceExtends", "GenericAutowireComposer");
request.setAttribute("nuiSourceImplements", "");
request.setAttribute("nuiSourceMethods", new String[]{"doBeforeCompose", "doAfterCompose", "onEvent", "render", "onAdd", "onSave", "initCriteria", "onSearchDefault", "checkNamaKelompokParameterTambahanPengajuanPegawai"});
request.setAttribute("nuiLegacyRefs", new String[]{});
request.setAttribute("nuiEntityCandidates", new String[]{"KelompokParameterTambahanPengajuanPegawai"});
%>
<jsp:include page="/WEB-INF/new/_shared/ui/page.jsp" />
