<%-- @generated by generate_new_jsp_scaffold.py
Source: src/ais/action/master/KelompokParameterTambahanCatatanMahasiswaAction.java
Generated: 2026-08-06T18:20:20Z
This JSP contains presentation metadata only. Keep business logic in Java services.
--%>
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%
request.setAttribute("nuiModule", "root");
request.setAttribute("nuiModuleLabel", "Modul Inti");
request.setAttribute("nuiPage", "kelompok_parameter_tambahan_catatan_mahasiswa");
request.setAttribute("nuiPageTitle", "Kelompok Parameter Tambahan Catatan Mahasiswa");
request.setAttribute("nuiPageType", "settings");
request.setAttribute("nuiPageDescription", "Pengaturan untuk Modul Inti. Konfigurasi terstruktur, validasi, versi, dan riwayat perubahan.");
request.setAttribute("nuiSourceClass", "KelompokParameterTambahanCatatanMahasiswaAction");
request.setAttribute("nuiSourcePackage", "ais.action.master");
request.setAttribute("nuiSourcePath", "src/ais/action/master/KelompokParameterTambahanCatatanMahasiswaAction.java");
request.setAttribute("nuiSourceKind", "class");
request.setAttribute("nuiSourceExtends", "GenericAutowireComposer");
request.setAttribute("nuiSourceImplements", "");
request.setAttribute("nuiSourceMethods", new String[]{"doBeforeCompose", "doAfterCompose", "onEvent", "render", "onAdd", "onSave", "initCriteria", "onSearchDefault", "checkNamaKelompokParameterTambahanCatatanMahasiswa"});
request.setAttribute("nuiEntityCandidates", new String[]{"KelompokParameterTambahanCatatanMahasiswa"});
%>
<jsp:include page="/WEB-INF/new/_shared/ui/page.jsp" />
