<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<% String op=String.valueOf(request.getAttribute("nui_native_subroute")); String endpoint=String.valueOf(request.getAttribute("nuiServiceEndpointOverride")); boolean upload=op.startsWith("upload_")||"import_data".equals(op); boolean photos="upload_photo_massal".equals(op); boolean dbf="import_data".equals(op); boolean sync="sync_status".equals(op); boolean execute="feeder".equals(op)||"ojs".equals(op); int now=java.util.Calendar.getInstance().get(java.util.Calendar.YEAR); %>
<section class="nui-page" data-operation-endpoint="<%=endpoint%>" aria-labelledby="mahOperationTitle">
  <div class="nui-breadcrumb"><a href="<%=request.getContextPath()%>/new">Beranda</a> / Mahasiswa / Operasi Lanjutan</div>
  <div class="nui-page-head"><div><h1 id="mahOperationTitle">Memuat operasi...</h1><p class="nui-page-desc">Alur native dengan aturan bisnis yang sama seperti MahasiswaAction existing.</p></div><a class="nui-btn" href="javascript:history.back()"><i class="fa-solid fa-arrow-left"></i> Kembali</a></div>
  <article class="nui-card nui-card-pad">
    <% if(sync){ %>
    <form id="mahSyncForm"><div class="row g-3"><div class="col-md-6"><label class="form-label">Tahun Akademik</label><input class="form-control" name="tahunAkademik" placeholder="2026/2027" required></div><div class="col-md-6"><label class="form-label">Semester</label><select class="form-select" name="semester"><option value="GANJIL">GANJIL</option><option value="GENAP">GENAP</option><option value="SP">SP</option><option value="">Semua</option></select></div><div class="col-md-6"><label class="form-label">Angkatan Mulai</label><input class="form-control" type="number" name="mulai" value="<%=now-4%>" required></div><div class="col-md-6"><label class="form-label">Angkatan Sampai</label><input class="form-control" type="number" name="sampai" value="<%=now%>" required></div></div><div class="row g-2 mt-2"><label class="col-md-6"><input type="checkbox" name="statusMahasiswa" checked> Status Mahasiswa</label><label class="col-md-6"><input type="checkbox" name="statusKrs"> KRS/KHS Mahasiswa</label><label class="col-md-6"><input type="checkbox" name="perkuliahan"> Perkuliahan Mahasiswa</label><label class="col-md-6"><input type="checkbox" name="pembayaran"> Pembayaran Mahasiswa</label><label class="col-md-6"><input type="checkbox" name="nonAktifkan"> Nonaktifkan/aktifkan berdasarkan KRS</label><label class="col-md-6"><input type="checkbox" name="reloadTemporary"> Reload data temporary</label></div><button class="nui-btn nui-btn-primary mt-3" type="submit"><i class="fa-solid fa-rotate"></i> Proses Sinkronisasi</button></form>
    <% }else if(upload){ %>
    <form id="mahOperationForm"><label class="nui-field"><span><%=photos?"Foto bernama NIM atau ZIP":(dbf?"Berkas EPSBED MSMHS.DBF":"Berkas Excel (.xlsx)")%></span><input id="mahOperationFile" class="nui-input" type="file" name="file" accept="<%=photos?"image/*,.zip,application/zip":(dbf?".dbf,application/octet-stream":".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")%>" <%=photos?"multiple":""%> required></label><div style="height:12px"></div><button class="nui-btn nui-btn-primary" type="submit"><i class="fa-solid fa-cloud-arrow-up"></i> Proses dan Unduh Laporan</button></form>
    <% }else if(execute){ %>
    <div class="nui-alert warning"><strong>Konfirmasi diperlukan.</strong> Proses ini menghubungi sistem eksternal dan memproses seluruh mahasiswa dalam scope PT aktif.</div><button id="mahOperationExecute" class="nui-btn nui-btn-primary" type="button"><i class="fa-solid fa-paper-plane"></i> Konfirmasi dan Jalankan</button>
    <% }else{ %>
    <p>Data yang boleh diakses akan diekspor sesuai scope perguruan tinggi aktif.</p><button id="mahOperationDownload" class="nui-btn nui-btn-primary" type="button"><i class="fa-solid fa-file-excel"></i> Unduh Excel</button>
    <% } %>
    <div id="mahOperationStatus" class="nui-alert" style="display:none;margin-top:14px" role="status"></div>
  </article>
</section>
<script>
(function(){var root=document.querySelector('[data-operation-endpoint]'),endpoint=root.getAttribute('data-operation-endpoint'),status=document.getElementById('mahOperationStatus'),csrf='';
function show(message,error){status.style.display='block';status.className='nui-alert '+(error?'danger':'info');status.textContent=message;}
function filename(response,fallback){var h=response.headers.get('Content-Disposition')||'',m=/filename\*?=(?:UTF-8''|\")?([^\";]+)/i.exec(h);return m?decodeURIComponent(m[1]):fallback;}
function save(response,fallback){return response.blob().then(function(blob){var a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=filename(response,fallback);document.body.appendChild(a);a.click();setTimeout(function(){URL.revokeObjectURL(a.href);a.remove();},1000);});}
fetch(endpoint+'&action=operation_meta',{credentials:'same-origin'}).then(function(r){return r.json();}).then(function(j){if(!j.ok)throw new Error(j.message||'Metadata gagal dimuat');csrf=j.data.csrf||'';document.getElementById('mahOperationTitle').textContent=j.data.title;}).catch(function(e){show(e.message,true);});
var download=document.getElementById('mahOperationDownload');if(download)download.addEventListener('click',function(){download.disabled=true;show('Menyiapkan berkas...',false);fetch(endpoint+'&action=operation_download',{credentials:'same-origin'}).then(function(r){if(!r.ok)return r.json().then(function(j){throw new Error(j.message||'Unduh gagal');});return save(r,'mahasiswa.xlsx');}).then(function(){show('Berkas berhasil dibuat.',false);}).catch(function(e){show(e.message,true);}).then(function(){download.disabled=false;});});
var form=document.getElementById('mahOperationForm');if(form)form.addEventListener('submit',function(e){e.preventDefault();var files=document.getElementById('mahOperationFile').files;if(!files.length){show('Pilih berkas.',true);return;}var data=new FormData();for(var i=0;i<files.length;i++)data.append('file',files[i]);var button=form.querySelector('button');button.disabled=true;show('Memproses setiap berkas/baris...',false);fetch(endpoint+'&action=operation_upload',{method:'POST',credentials:'same-origin',headers:{'X-NUI-CSRF':csrf},body:data}).then(function(r){if(!r.ok)return r.json().then(function(j){throw new Error(j.message||'Upload gagal');});return save(r,'laporan_upload.txt');}).then(function(){show('Proses selesai. Laporan rinci telah diunduh.',false);}).catch(function(err){show(err.message,true);}).then(function(){button.disabled=false;});});
var syncForm=document.getElementById('mahSyncForm');if(syncForm)syncForm.addEventListener('submit',function(e){e.preventDefault();var data=new URLSearchParams(new FormData(syncForm)),button=syncForm.querySelector('button');button.disabled=true;show('Sinkronisasi berjalan. Jangan tutup halaman...',false);fetch(endpoint+'&action=operation_execute',{method:'POST',credentials:'same-origin',headers:{'X-NUI-CSRF':csrf,'Content-Type':'application/x-www-form-urlencoded;charset=UTF-8'},body:data.toString()}).then(function(r){if(!r.ok)return r.json().then(function(j){throw new Error(j.message||'Sinkronisasi gagal');});return save(r,'laporan_sinkronisasi_status.txt');}).then(function(){show('Sinkronisasi selesai dan laporan telah diunduh.',false);}).catch(function(err){show(err.message,true);}).then(function(){button.disabled=false;});});
var executeButton=document.getElementById('mahOperationExecute');if(executeButton)executeButton.addEventListener('click',function(){if(!window.confirm('Yakin menjalankan proses ini untuk seluruh mahasiswa yang dapat diakses?'))return;executeButton.disabled=true;show('Proses berjalan. Jangan tutup halaman...',false);fetch(endpoint+'&action=operation_execute',{method:'POST',credentials:'same-origin',headers:{'X-NUI-CSRF':csrf,'Content-Type':'application/x-www-form-urlencoded;charset=UTF-8'},body:''}).then(function(r){if(!r.ok)return r.json().then(function(j){throw new Error(j.message||'Proses gagal');});return save(r,'laporan_operasi_mahasiswa.txt');}).then(function(){show('Proses selesai dan laporan telah diunduh.',false);}).catch(function(err){show(err.message,true);}).then(function(){executeButton.disabled=false;});});
})();
</script>
