<%-- @generated by generate_new_jsp_scaffold.py
Source: src/ais/action/master/OnlineUsersAction.java
Generated: 2026-08-06T18:20:20Z
This JSP contains presentation metadata only. Keep business logic in Java services.
--%>
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%
request.setAttribute("nuiModule", "root");
request.setAttribute("nuiModuleLabel", "Modul Inti");
request.setAttribute("nuiPage", "online_users");
request.setAttribute("nuiPageTitle", "Online Users");
request.setAttribute("nuiPageType", "list");
request.setAttribute("nuiPageDescription", "Pendataan untuk Modul Inti. Daftar data, pencarian, filter, detail, impor, dan ekspor.");
request.setAttribute("nuiSourceClass", "OnlineUsersAction");
request.setAttribute("nuiSourcePackage", "ais.action.master");
request.setAttribute("nuiSourcePath", "src/ais/action/master/OnlineUsersAction.java");
request.setAttribute("nuiSourceKind", "class");
request.setAttribute("nuiSourceExtends", "GenericAutowireComposer");
request.setAttribute("nuiSourceImplements", "");
request.setAttribute("nuiSourceMethods", new String[]{"doBeforeCompose", "doAfterCompose", "onEvent", "render", "onSearchDefault"});
request.setAttribute("nuiLegacyRefs", new String[]{});
request.setAttribute("nuiEntityCandidates", new String[]{"OnlineUsers"});
%>
<jsp:include page="/WEB-INF/new/_shared/ui/page.jsp" />
