<%-- @generated by generate_new_jsp_scaffold.py
Source: src/ais/action/master/PengecekanPendaftaranWisudaPerpustakaanFakultasAction.java
Generated: 2026-08-06T18:20:20Z
This JSP contains presentation metadata only. Keep business logic in Java services.
--%>
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%
request.setAttribute("nuiModule", "root");
request.setAttribute("nuiModuleLabel", "Modul Inti");
request.setAttribute("nuiPage", "pengecekan_pendaftaran_wisuda_perpustakaan_fakultas");
request.setAttribute("nuiPageTitle", "Pengecekan Pendaftaran Wisuda Perpustakaan Fakultas");
request.setAttribute("nuiPageType", "form");
request.setAttribute("nuiPageDescription", "Formulir untuk Modul Inti. Pendataan bertahap dengan validasi, status kelengkapan, dan audit.");
request.setAttribute("nuiSourceClass", "PengecekanPendaftaranWisudaPerpustakaanFakultasAction");
request.setAttribute("nuiSourcePackage", "ais.action.master");
request.setAttribute("nuiSourcePath", "src/ais/action/master/PengecekanPendaftaranWisudaPerpustakaanFakultasAction.java");
request.setAttribute("nuiSourceKind", "class");
request.setAttribute("nuiSourceExtends", "GenericAutowireComposer");
request.setAttribute("nuiSourceImplements", "");
request.setAttribute("nuiSourceMethods", new String[]{"doBeforeCompose", "doAfterCompose", "onPilihMahasiswa", "onSetuju", "onEvent", "onTolak"});
request.setAttribute("nuiEntityCandidates", new String[]{"PendaftaranWisuda"});
%>
<jsp:include page="/WEB-INF/new/_shared/ui/page.jsp" />
