<%-- @generated by generate_new_jsp_scaffold.py
Source: src/ais/action/master/PenilaianRemedialAction.java
Generated: 2026-08-06T18:20:20Z
This JSP contains presentation metadata only. Keep business logic in Java services.
--%>
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%
request.setAttribute("nuiModule", "root");
request.setAttribute("nuiModuleLabel", "Modul Inti");
request.setAttribute("nuiPage", "penilaian_remedial");
request.setAttribute("nuiPageTitle", "Penilaian Remedial");
request.setAttribute("nuiPageType", "academic");
request.setAttribute("nuiPageDescription", "Akademik untuk Modul Inti. Data akademik, jadwal, capaian, dan status proses pendidikan.");
request.setAttribute("nuiSourceClass", "PenilaianRemedialAction");
request.setAttribute("nuiSourcePackage", "ais.action.master");
request.setAttribute("nuiSourcePath", "src/ais/action/master/PenilaianRemedialAction.java");
request.setAttribute("nuiSourceKind", "class");
request.setAttribute("nuiSourceExtends", "PenilaianAction");
request.setAttribute("nuiSourceImplements", "");
request.setAttribute("nuiSourceMethods", new String[]{});
request.setAttribute("nuiEntityCandidates", new String[]{});
%>
<jsp:include page="/WEB-INF/new/_shared/ui/page.jsp" />
