<%-- @generated by generate_new_jsp_scaffold.py
Source: src/ais/action/master/akunting/PostingKasKecilAction.java
Generated: 2026-08-06T18:20:20Z
Safe service-adapter scaffold. Implement data access in a Java service layer, not directly in this JSP.
--%>
<%@ page language="java" contentType="application/json; charset=UTF-8" pageEncoding="UTF-8" %>
<%
request.setAttribute("nuiServiceModule", "akunting");
request.setAttribute("nuiServicePage", "posting_kas_kecil");
request.setAttribute("nuiServiceTitle", "Posting Kas Kecil");
request.setAttribute("nuiServiceType", "finance");
request.setAttribute("nuiServiceSourceClass", "PostingKasKecilAction");
request.setAttribute("nuiServiceSourcePackage", "ais.action.master.akunting");
request.setAttribute("nuiServiceSourcePath", "src/ais/action/master/akunting/PostingKasKecilAction.java");
request.setAttribute("nuiServiceMethods", new String[]{"doBeforeCompose", "doAfterCompose", "onEvent", "onBatalkanPostingSemua", "onPostingSemua", "run", "batalkanPostingSemua", "postingSemua", "render", "initCriteria", "onSearchDefault"});
request.setAttribute("nuiServiceEntities", new String[]{"Akun", "KasKecil", "GrupTransaksi"});
%>
<jsp:include page="/WEB-INF/new/_shared/services/dispatcher.jsp" />
