<%-- @generated by generate_new_jsp_scaffold.py
Source: src/ais/action/report/format1/keuangan/LaporanRekapitulasiTunggakanMahasiswaDetail.java
Generated: 2026-08-06T18:20:20Z
Safe service-adapter scaffold. Implement data access in a Java service layer, not directly in this JSP.
--%>
<%@ page language="java" contentType="application/json; charset=UTF-8" pageEncoding="UTF-8" %>
<%
request.setAttribute("nuiServiceModule", "root/report");
request.setAttribute("nuiServicePage", "format1/keuangan/laporan_rekapitulasi_tunggakan_mahasiswa_detail");
request.setAttribute("nuiServiceTitle", "Laporan Rekapitulasi Tunggakan Mahasiswa Detail");
request.setAttribute("nuiServiceType", "report");
request.setAttribute("nuiServiceSourceClass", "LaporanRekapitulasiTunggakanMahasiswaDetail");
request.setAttribute("nuiServiceSourcePackage", "ais.action.report.format1.keuangan");
request.setAttribute("nuiServiceSourcePath", "src/ais/action/report/format1/keuangan/LaporanRekapitulasiTunggakanMahasiswaDetail.java");
request.setAttribute("nuiServiceMethods", new String[]{"onEvent", "generateParameters", "onRekap"});
request.setAttribute("nuiServiceEntities", new String[]{});
%>
<jsp:include page="/WEB-INF/new/_shared/services/dispatcher.jsp" />
