package ais.action.master.generic.v2.test;
import java.util.ArrayList;import java.util.Date;
import ais.common.newui.akunting.NewUiJournalService;
import ais.common.newui.akunting.NewUiJournalService.Draft;
import ais.common.newui.akunting.NewUiJournalService.Filter;
import ais.common.newui.akunting.NewUiJournalService.LineDraft;
import ais.common.newui.akunting.NewUiJournalService.Options;
import ais.common.newui.akunting.NewUiJournalService.Snapshot;
public final class JournalDatabaseSelfTest{private JournalDatabaseSelfTest(){}public static void main(String[]a){NewUiJournalService s=new NewUiJournalService();Filter f=new Filter();f.page=0;f.size=10;Snapshot before=s.load(f);check(before.total>=0&&before.rows.size()<=10,"paging");Options o=s.options();check(o.accounts.size()>0,"account options");Filter all=new Filter();all.allJournals=true;all.page=0;all.size=10;s.load(all);Filter account=new Filter();account.accountIds=new ArrayList<Long>();account.accountIds.add(o.accounts.get(0).id);account.page=0;account.size=10;s.load(account);Filter dashboard=new Filter();dashboard.sourceEntity="cicilanPembayaran";dashboard.ref="dimuka";dashboard.postedActive=Boolean.FALSE;dashboard.page=0;dashboard.size=10;s.load(dashboard);Filter closing=new Filter();closing.closingBefore=new Date();closing.page=0;closing.size=10;s.load(closing);if(o.types.size()>0){Draft d=new Draft();d.code="CODEX-ROLLBACK-INVALID";d.date=new Date();d.typeId=o.types.get(0).id;LineDraft x=new LineDraft();x.accountId=o.accounts.get(0).id;x.description="debet test";x.debit=100;x.credit=0;d.lines.add(x);LineDraft y=new LineDraft();y.accountId=o.accounts.get(0).id;y.description="kredit invalid";y.debit=0;y.credit=90;d.lines.add(y);boolean rejected=false;try{s.save(d,null);}catch(IllegalArgumentException e){rejected=e.getMessage()!=null&&e.getMessage().toLowerCase().indexOf("balance")>=0;}check(rejected,"unbalanced journal rejected");Snapshot after=s.load(f);check(before.total==after.total,"invalid transaction must not persist");}System.out.println("JournalDatabaseSelfTest OK total="+before.total+" accounts="+o.accounts.size()+" types="+o.types.size());System.exit(0);}private static void check(boolean v,String m){if(!v)throw new IllegalStateException(m);}}
