<%-- @generated by generate_new_jsp_scaffold.py
Source: src/ais/action/master/epsbed/KapasitasProdiHelper.java
Generated: 2026-08-06T18:20:20Z
This JSP contains presentation metadata only. Keep business logic in Java services.
--%>
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%
request.setAttribute("nuiModule", "epsbed");
request.setAttribute("nuiModuleLabel", "EPSBED");
request.setAttribute("nuiPage", "kapasitas_prodi_helper");
request.setAttribute("nuiPageTitle", "Kapasitas Prodi Helper");
request.setAttribute("nuiPageType", "integration");
request.setAttribute("nuiPageDescription", "Integrasi untuk EPSBED. Status koneksi, sinkronisasi, log, retry, dan pemetaan data.");
request.setAttribute("nuiSourceClass", "KapasitasProdiHelper");
request.setAttribute("nuiSourcePackage", "ais.action.master.epsbed");
request.setAttribute("nuiSourcePath", "src/ais/action/master/epsbed/KapasitasProdiHelper.java");
request.setAttribute("nuiSourceKind", "class");
request.setAttribute("nuiSourceExtends", "");
request.setAttribute("nuiSourceImplements", "");
request.setAttribute("nuiSourceMethods", new String[]{"render", "onEvent", "display", "onSearchDefault", "init", "save"});
request.setAttribute("nuiEntityCandidates", new String[]{"KapasitasMahasiswaBaru"});
%>
<jsp:include page="/WEB-INF/new/_shared/ui/page.jsp" />
