<%-- @generated by generate_new_jsp_scaffold.py
Source: src/ais/action/master/epsbed/UpdateDataKapasitasProdi.java
Generated: 2026-08-06T18:20:20Z
This JSP contains presentation metadata only. Keep business logic in Java services.
--%>
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%
request.setAttribute("nuiModule", "epsbed");
request.setAttribute("nuiModuleLabel", "EPSBED");
request.setAttribute("nuiPage", "update_data_kapasitas_prodi");
request.setAttribute("nuiPageTitle", "Update Data Kapasitas Prodi");
request.setAttribute("nuiPageType", "integration");
request.setAttribute("nuiPageDescription", "Integrasi untuk EPSBED. Status koneksi, sinkronisasi, log, retry, dan pemetaan data.");
request.setAttribute("nuiSourceClass", "UpdateDataKapasitasProdi");
request.setAttribute("nuiSourcePackage", "ais.action.master.epsbed");
request.setAttribute("nuiSourcePath", "src/ais/action/master/epsbed/UpdateDataKapasitasProdi.java");
request.setAttribute("nuiSourceKind", "class");
request.setAttribute("nuiSourceExtends", "GenericAutowireComposer");
request.setAttribute("nuiSourceImplements", "");
request.setAttribute("nuiSourceMethods", new String[]{"doBeforeCompose", "onEvent", "run", "doProcess"});
request.setAttribute("nuiEntityCandidates", new String[]{"Fakultas", "Jurusan", "KapasitasMahasiswaBaru"});
%>
<jsp:include page="/WEB-INF/new/_shared/ui/page.jsp" />
