<%-- @generated by generate_new_jsp_scaffold.py
Source: src/ais/action/master/pmb/BiodataCalonMahasiswaAction.java
Generated: 2026-08-06T18:20:20Z
Safe service-adapter scaffold. Implement data access in a Java service layer, not directly in this JSP.
--%>
<%@ page language="java" contentType="application/json; charset=UTF-8" pageEncoding="UTF-8" %>
<%
request.setAttribute("nuiServiceModule", "root/pmb");
request.setAttribute("nuiServicePage", "biodata_calon_mahasiswa");
request.setAttribute("nuiServiceTitle", "Biodata Calon Mahasiswa");
request.setAttribute("nuiServiceType", "form");
request.setAttribute("nuiServiceSourceClass", "BiodataCalonMahasiswaAction");
request.setAttribute("nuiServiceSourcePackage", "ais.action.master.pmb");
request.setAttribute("nuiServiceSourcePath", "src/ais/action/master/pmb/BiodataCalonMahasiswaAction.java");
request.setAttribute("nuiServiceMethods", new String[]{"infoMahasiswaBaru", "initBg", "loadBiodataCalonMahasiswa", "onEvent", "init", "onSave", "lengkap", "onCetakKartu", "getEventListener", "setEventListener", "run"});
request.setAttribute("nuiServiceEntities", new String[]{"PaketPunyaGelombangPendaftaran", "BiodataCalonMahasiswa", "GelombangPendaftaran", "AfiliasiCalonMahasiswa", "JenisKartuIdentitasMahasiswaBaru", "Agama", "Negara", "JenisSekolahMahasiswaBaru", "JurusanSekolahMahasiswaBaru", "Paket", "PilihanPaketPerJurusanMhsBaru", "PendidikanOrangTua", "PekerjaanOrangTua", "PendapatanOrangTua", "Konsentrasi", "PaketPunyaProgram", "Program", "PaketJurusanPmb", "FotoBiodataCalonMahasiswa"});
%>
<jsp:include page="/WEB-INF/new/_shared/services/dispatcher.jsp" />
