<%-- @generated by generate_new_jsp_scaffold.py
Source: src/ais/action/master/pmb/PaketAction.java
Generated: 2026-08-06T18:20:20Z
Safe service-adapter scaffold. Implement data access in a Java service layer, not directly in this JSP.
--%>
<%@ page language="java" contentType="application/json; charset=UTF-8" pageEncoding="UTF-8" %>
<%
request.setAttribute("nuiServiceModule", "root/pmb");
request.setAttribute("nuiServicePage", "paket");
request.setAttribute("nuiServiceTitle", "Paket");
request.setAttribute("nuiServiceType", "academic");
request.setAttribute("nuiServiceSourceClass", "PaketAction");
request.setAttribute("nuiServiceSourcePackage", "ais.action.master.pmb");
request.setAttribute("nuiServiceSourcePath", "src/ais/action/master/pmb/PaketAction.java");
request.setAttribute("nuiServiceMethods", new String[]{"onPendidikanOrtu", "onTampilkanParameter", "onMatapelajaranSekolah", "onParameterVerifikasi", "onKartuIdentitas", "onJenisSekolah", "onJurusanSekolah", "onNamaSekolah", "onPekerjaanOrtu", "onPendapatanOrtu", "doBeforeCompose", "doAfterCompose", "render", "onEvent", "onAdd", "onSave", "onSearchDefault", "checkNamaPaket"});
request.setAttribute("nuiServiceLegacyRefs", new String[]{"/pages/master/pendidikan_orangtua.zul", "/pages/master/parameter_tambahan_paket.zul", "/pages/master/matapelajaran_sekolah.zul", "/pages/master/parameter_verifikasi_calon_mahasiswa.zul", "/pages/master/jenis_kartu_identitas.zul", "/pages/master/jenis_sekolah.zul", "/pages/master/jurusan_sekolah.zul", "/pages/master/nama_sekolah_asal.zul", "/pages/master/pekerjaan_orangtua.zul", "/pages/master/pendapatan_orangtua.zul", "/pages/master/paket_registrasi_mahasiswa.zul?paket=", "/pages/master/paket_punya_program.zul?paket=", "/pages/master/parameter_tambahan_paket.zul?paket=", "/pages/master/paket_punya_gelombang_pendaftaran.zul?paket=", "/pages/master/persyaratan_pilihan_paket.zul?paket=", "/pages/master/paket_punya_matapelajaran.zul?paket=", "/pages/master/paket_punya_parameter_verifikasi_calon_mahasiswa.zul?paket="});
request.setAttribute("nuiServiceEntities", new String[]{"Paket"});
%>
<jsp:include page="/WEB-INF/new/_shared/services/dispatcher.jsp" />
