<%-- @generated by generate_new_jsp_scaffold.py
Source: src/ais/action/master/pmb/TampilanPaymentGateway.java
Generated: 2026-08-06T18:20:20Z
Safe service-adapter scaffold. Implement data access in a Java service layer, not directly in this JSP.
--%>
<%@ page language="java" contentType="application/json; charset=UTF-8" pageEncoding="UTF-8" %>
<%
request.setAttribute("nuiServiceModule", "root/pmb");
request.setAttribute("nuiServicePage", "tampilan_payment_gateway");
request.setAttribute("nuiServiceTitle", "Tampilan Payment Gateway");
request.setAttribute("nuiServiceType", "academic");
request.setAttribute("nuiServiceSourceClass", "TampilanPaymentGateway");
request.setAttribute("nuiServiceSourcePackage", "ais.action.master.pmb");
request.setAttribute("nuiServiceSourcePath", "src/ais/action/master/pmb/TampilanPaymentGateway.java");
request.setAttribute("nuiServiceMethods", new String[]{"tampilPembayaranDaftarUlang", "adaPembayaranRegistrasi", "tampilPembayaranRegistrasi", "onEvent", "adaPaymentGatewayYangAktif"});
request.setAttribute("nuiServiceLegacyRefs", new String[]{"/common/daftarulang_mahasiswa_baru.zul?biodataCalonMahasiswa=", "/common/bankaltimtara/no_va.zul?pakaiva=", "/common/ntt/no_va.zul?va=", "/common/online/no_va.zul?va=", "/common/bri/no_va.zul?va=", "/common/bjb/no_va.zul?va=", "/common/btn/no_va.zul?va=", "/common/qris/no_va.zul?va="});
request.setAttribute("nuiServiceEntities", new String[]{});
%>
<jsp:include page="/WEB-INF/new/_shared/services/dispatcher.jsp" />
