package ais.database.model.sirs;

// Generated Apr 16, 2010 2:27:16 PM by Hibernate Tools 3.2.4.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;
import org.hibernate.envers.Audited;

import ais.database.model.GeneralValueObject;

/**
 * Bank generated by hbm2java
 *
 * <p>
 * <b>Satu lampiran pemakaian alat medis pada satu {@link DiagnosaPenyakit}</b> — satu dari tiga
 * jenis lampiran yang dapat dilekatkan ke sebuah diagnosa, bersama {@link ItemDiagnosaPenyakit}
 * (item obat/bahan habis pakai, ENTITY YATIM — lihat javadocnya) dan
 * {@link TindakanDiagnosaPenyakit} (tindakan medis). Ketiganya berbentuk identik: merujuk satu
 * katalog ({@link AlatMedis} untuk kelas ini), satu {@link DiagnosaPenyakit} pemilik, satu
 * {@link KelasPerawatan} penentu tarif, serta {@code jumlah} dan {@code biaya} pemakaian. Dipetakan
 * ke {@code sirs.alat_medis_diagnosa_penyakit} dengan tabel audit Envers berpasangan
 * {@code new_audit.alat_medis_diagnosa_penyakit__audit}.
 * </p>
 *
 * <h2>Peran di dalam AIS — AKTIF dikelola {@code AlatMedisHelper}</h2>
 * <p>
 * Berbeda dari {@link ItemDiagnosaPenyakit} yang yatim, baris kelas ini AKTIF dibuat/diperbarui
 * lewat {@code ais.action.master.sirs.detail.AlatMedisHelper} — helper UI ZK yang polanya identik
 * dengan {@code ais.action.master.sirs.detail.TindakanHelper} milik {@link TindakanDiagnosaPenyakit}:
 * menambah alat dari dialog pemilihan banyak ({@code AmbilDataAlatMedisBanyak}), MENOLAK
 * menambahkan alat yang belum memiliki {@code BiayaAlatMedisPerKelas} untuk kelas perawatan pasien
 * (menampilkan peringatan dan melewatinya alih-alih menyimpan biaya {@code null}/{@code 0}), serta
 * mengizinkan penyuntingan jumlah/tanggal/keterangan langsung dari grid pada layar diagnosa.
 * </p>
 *
 * <h2>Cakupan tenant</h2>
 * <p>
 * Kelas ini tidak membawa sumbu tenant/satuan-kerja langsung; cakupannya sepenuhnya mengikuti
 * {@link #getDiagnosaPenyakit()} — DATA MEDIS PASIEN karena merepresentasikan alat medis apa yang
 * dipakai untuk pasien tertentu pada diagnosa tertentu.
 * </p>
 *
 * <h2>Pola arsitektur khas AIS yang muncul di kelas ini</h2>
 * <ul>
 * <li><b>Field audit bayangan</b> ({@code oleh}, {@code olehId}, {@code tanggal_dirubah},
 * {@link #onUpdate()}) diduplikasi karena induk {@link GeneralValueObject} BUKAN {@code @Entity}.
 * KEHARUSAN TEKNIS, bukan salin-tempel ceroboh.</li>
 * <li><b>Dua gaya fetch berbeda pada relasi bertetangga</b>: {@link #getAlatMedis()} dan
 * {@link #getKelasPerawatan()} memakai {@code fetch = FetchType.LAZY} dengan resolusi cache
 * {@code check(...)}, sedangkan {@link #getDiagnosaPenyakit()} memakai EAGER +
 * {@code @Fetch(FetchMode.SELECT)} tanpa {@code check(...)} — pola dua-gaya-fetch yang berulang di
 * banyak entity {@code sirs} lain (bandingkan {@link ItemDiagnosaPenyakit},
 * {@link TindakanDiagnosaPenyakit}).</li>
 * <li><b>Satu tanggal pemakaian</b> ({@link #getTanggal()}), BERBEDA dari
 * {@link ItemDiagnosaPenyakit} yang membawa RENTANG tanggal ({@code mulai}/{@code sampai}) —
 * mencerminkan bahwa pemakaian alat medis dicatat sebagai peristiwa satu titik waktu, bukan
 * pemakaian berkelanjutan.</li>
 * </ul>
 *
 * @see ItemDiagnosaPenyakit lampiran item obat/bahan habis pakai (ENTITY YATIM, struktur sejenis)
 * @see TindakanDiagnosaPenyakit lampiran tindakan medis, struktur sejenis dan AKTIF dipakai
 * @see DiagnosaPenyakit induk diagnosa pasien pemilik lampiran ini
 * @see AlatMedis katalog alat medis yang dirujuk
 * @see ais.action.master.sirs.detail.AlatMedisHelper pengelola aktif satu-satunya kelas ini
 */
@Entity
@org.hibernate.annotations.Entity(
    dynamicInsert = true,
    dynamicUpdate = true
)
@Audited
@Table(schema = "sirs", name = "alat_medis_diagnosa_penyakit")
public class AlatMedisDiagnosaPenyakit extends GeneralValueObject {

	/**
	 * Nomor versi serialisasi Java. Nilainya identik dengan {@code serialVersionUID} pada banyak
	 * entity {@code sirs} lain karena semuanya lahir dari template hbm2java yang sama; kesamaan
	 * antar kelas berbeda tidak bermasalah karena {@code serialVersionUID} hanya dibandingkan antar
	 * versi dari kelas yang SAMA.
	 */
	private static final long serialVersionUID = 2463821577548439808L;
	/** Kunci primer numerik, {@code IDENTITY} (auto-increment basis data). Lihat {@link #getId()}. */
	private Long id;
	private String olehId;

	/**
	 * Mengembalikan identitas (username/ID) pengguna terakhir yang menyunting baris ini.
	 *
	 * @return identitas penyunting terakhir, atau {@code null} bila belum pernah diisi
	 */
	public String getOlehId() {
		return olehId;
	}

	/**
	 * Menetapkan identitas pengguna penyunting terakhir, dengan penjagaan anti-penghapusan:
	 * argumen {@code null} atau string kosong/berisi spasi saja diabaikan diam-diam sehingga nilai
	 * lama dipertahankan. Pola seragam di seluruh entity AIS agar jejak audit tidak hilang hanya
	 * karena sebuah proses batch atau importer menyerahkan objek tanpa konteks pengguna.
	 *
	 * @param olehId identitas penyunting; diabaikan bila {@code null} atau hanya berisi spasi
	 */
	public void setOlehId(String olehId) {if (olehId == null || olehId.trim().isEmpty()) {return;}
		this.olehId = olehId;
	}

	/**
	 * Nama tampil pengguna yang terakhir mengubah baris ini (field audit bayangan). Diisi oleh
	 * {@code AuditTimestampInterceptor} melalui {@link #setOleh(String)}.
	 */
	private String oleh;

	/**
	 * Mengembalikan label ringkas baris ini, yakni {@link #getKeterangan() keterangan} apa adanya.
	 *
	 * @return keterangan yang tersimpan, dapat {@code null} bila belum diisi
	 */
	public String toString() {
		return keterangan;
	}

	/**
	 * Menetapkan nama tampil pengguna penyunting terakhir, dengan penjagaan anti-penghapusan yang
	 * sama seperti {@link #setOlehId(String)}.
	 *
	 * @param oleh nama penyunting; diabaikan bila {@code null} atau hanya berisi spasi
	 */
	public void setOleh(String oleh) {if (oleh == null || oleh.trim().isEmpty()) {return;}
		this.oleh = oleh;
	}

	/**
	 * Mengembalikan nama tampil pengguna terakhir yang menyunting baris ini.
	 *
	 * @return nama penyunting terakhir, atau {@code null} bila belum pernah diisi
	 */
	public String getOleh() {
		return oleh;
	}

	/**
	 * Kait daur hidup JPA {@code @PreUpdate} yang mendelegasikan pengisian jejak audit ke
	 * {@code ais.database.hibernate.AuditTimestampInterceptor.ubah(this)} tepat sebelum Hibernate
	 * menerbitkan pernyataan {@code UPDATE}. Interceptor membaca konteks pengguna aktif dari sesi
	 * ZK/HTTP lalu mengisi {@link #setOleh(String)}, {@link #setOlehId(String)}, dan
	 * {@link #setTanggal_dirubah(Date)}. Mekanisme ini TERPISAH dari Hibernate Envers
	 * ({@link Audited}): Envers menulis salinan penuh setiap revisi ke
	 * {@code new_audit.alat_medis_diagnosa_penyakit__audit}, sedangkan trio {@code oleh}/
	 * {@code olehId}/{@code tanggal_dirubah} hanya menyimpan potret "siapa terakhir" pada baris
	 * hidup.
	 */
	@javax.persistence.PreUpdate protected void onUpdate() { ais.database.hibernate.AuditTimestampInterceptor.ubah(this);}     private Date tanggal_dirubah = new Date();

	/**
	 * Menetapkan cap waktu perubahan terakhir. Berbeda dari {@link #setOleh(String)}, setter ini
	 * TIDAK menjaga nilai kosong — {@code null} akan benar-benar tersimpan.
	 *
	 * @param tanggal_dirubah cap waktu perubahan terakhir
	 */
	public void setTanggal_dirubah(Date tanggal_dirubah) {
		this.tanggal_dirubah = tanggal_dirubah;
	}

	/**
	 * Mengembalikan cap waktu perubahan terakhir, dipetakan sebagai {@code TIMESTAMP}.
	 *
	 * @return cap waktu perubahan terakhir; tidak pernah {@code null} untuk objek yang baru
	 *         diinstansiasi lewat konstruktor kelas ini
	 */
	@Temporal(TemporalType.TIMESTAMP)
	public Date getTanggal_dirubah() {
		return tanggal_dirubah;
	}

	/** Keterangan bebas lampiran alat medis. Lihat {@link #getKeterangan()}. */
	private String keterangan;
	/** Katalog alat medis yang dipakai. Lihat {@link #getAlatMedis()}. */
	private AlatMedis alatMedis;
	/** Tanggal pemakaian alat (satu titik waktu). Lihat {@link #getTanggal()}. */
	private Date tanggal = new Date();
	/** Diagnosa pasien pemilik lampiran ini. Lihat {@link #getDiagnosaPenyakit()}. DATA MEDIS SENSITIF. */
	private DiagnosaPenyakit diagnosaPenyakit;

	/** Kelas perawatan penentu tarif alat ini. Lihat {@link #getKelasPerawatan()}. */
	private KelasPerawatan kelasPerawatan;
	/** Jumlah/kuantitas pemakaian. Lihat {@link #getJumlah()}. */
	private Double jumlah = 0.0;

	/** Biaya pemakaian alat ini. Lihat {@link #getBiaya()}. */
	private Double biaya = 0.0;

	/**
	 * Konstruktor tanpa argumen yang WAJIB ada agar Hibernate/JPA dapat meng-instansiasi entity
	 * lewat refleksi saat memuat baris dari basis data, dan agar {@code AlatMedisHelper} dapat
	 * membuat objek kosong untuk baris baru pada grid pemakaian alat.
	 */
	public AlatMedisDiagnosaPenyakit() {
	}

	/**
	 * Mengembalikan kunci primer lampiran alat medis.
	 *
	 * <p>
	 * Dipetakan {@code IDENTITY} (auto-increment basis data), sehingga nilainya baru terisi SETELAH
	 * baris tertulis. Nilai {@code null} adalah penanda baku bahwa objek belum tersimpan.
	 * </p>
	 *
	 * @return kunci primer, atau {@code null} bila entity belum pernah disimpan
	 */
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", insertable = false, unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	/**
	 * Menetapkan kunci primer. Umumnya hanya dipanggil Hibernate.
	 *
	 * @param id kunci primer
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * Mengembalikan keterangan bebas lampiran alat medis.
	 *
	 * @return keterangan, atau {@code null} bila tidak diisi
	 */
	@Column(name = "keterangan", nullable = true)
	public String getKeterangan() {
		return this.keterangan;
	}

	/**
	 * Menetapkan keterangan bebas lampiran alat medis.
	 *
	 * @param keterangan teks keterangan
	 */
	public void setKeterangan(String keterangan) {
		this.keterangan = keterangan;
	}

	/**
	 * Menetapkan katalog alat medis yang dipakai.
	 *
	 * @param alatMedis alat medis baru, boleh {@code null}
	 */
	public void setAlatMedis(AlatMedis alatMedis) {
		this.alatMedis = alatMedis;
	}

	/**
	 * Mengembalikan katalog alat medis yang dipakai pada diagnosa ini, melewati resolusi cache
	 * {@code check(...)} milik {@link GeneralValueObject}.
	 *
	 * @return alat medis yang dipakai, atau {@code null} bila tidak terpasang
	 */
	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY)
	@JoinColumn(name = "alat_medis", nullable = true)
	public AlatMedis getAlatMedis() {
		alatMedis = check(alatMedis);
		return alatMedis;
	}

	/**
	 * Menetapkan diagnosa pasien pemilik lampiran ini.
	 *
	 * @param diagnosaPenyakit diagnosa pemilik baru, boleh {@code null}
	 */
	public void setDiagnosaPenyakit(DiagnosaPenyakit diagnosaPenyakit) {
		this.diagnosaPenyakit = diagnosaPenyakit;
	}

	/**
	 * Mengembalikan diagnosa pasien pemilik lampiran alat medis ini — <b>DATA MEDIS PASIEN</b>
	 * (merepresentasikan alat medis apa yang dipakai untuk pasien tertentu).
	 *
	 * <p>
	 * Relasi ini {@code @ManyToOne} EAGER + {@code @Fetch(FetchMode.SELECT)} dan TIDAK memanggil
	 * {@code check(...)} — berbeda gaya dari {@link #getAlatMedis()}/{@link #getKelasPerawatan()}.
	 * </p>
	 *
	 * @return diagnosa pasien pemilik, atau {@code null} bila baris tidak terpasang
	 */
	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE })
	@Fetch(FetchMode.SELECT)
	@JoinColumn(name = "diagnosa_penyakit", nullable = true)
	public DiagnosaPenyakit getDiagnosaPenyakit() {
		return diagnosaPenyakit;
	}

	/**
	 * Mengembalikan kelas perawatan penentu tarif alat ini, melewati resolusi cache
	 * {@code check(...)} milik {@link GeneralValueObject}. {@code AlatMedisHelper} menolak
	 * menambahkan alat yang belum memiliki tarif ({@code BiayaAlatMedisPerKelas}) untuk kelas
	 * perawatan yang sama dengan yang dirujuk di sini.
	 *
	 * @return kelas perawatan, atau {@code null} bila tidak terpasang
	 */
	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY)
	@JoinColumn(name = "kelas_perawatan", nullable = true)
	public KelasPerawatan getKelasPerawatan() {
		kelasPerawatan = check(kelasPerawatan);
		return kelasPerawatan;
	}

	/**
	 * Menetapkan kelas perawatan penentu tarif alat ini.
	 *
	 * @param kelasPerawatan kelas perawatan baru, boleh {@code null}
	 */
	public void setKelasPerawatan(KelasPerawatan kelasPerawatan) {
		this.kelasPerawatan = kelasPerawatan;
	}

	/**
	 * Mengembalikan biaya pemakaian alat ini, dengan nilai baku {@code 0.0} bila belum diisi.
	 * Nilainya diambil otomatis dari {@code BiayaAlatMedisPerKelas} sesuai kelas perawatan pasien
	 * saat ditambahkan lewat {@code AlatMedisHelper}.
	 *
	 * @return biaya pemakaian; tidak pernah {@code null} untuk objek baru
	 */
	public Double getBiaya() {
		return biaya;
	}

	/**
	 * Menetapkan biaya pemakaian alat ini.
	 *
	 * @param biaya biaya baru
	 */
	public void setBiaya(Double biaya) {
		this.biaya = biaya;
	}

	/**
	 * Menetapkan jumlah/kuantitas pemakaian alat ini.
	 *
	 * @param jumlah jumlah baru
	 */
	public void setJumlah(Double jumlah) {
		this.jumlah = jumlah;
	}

	/**
	 * Mengembalikan jumlah/kuantitas pemakaian alat ini, dengan nilai baku {@code 0.0} bila belum
	 * diisi.
	 *
	 * @return jumlah pemakaian; tidak pernah {@code null} untuk objek baru
	 */
	public Double getJumlah() {
		return jumlah;
	}

	/**
	 * Menetapkan tanggal pemakaian alat ini.
	 *
	 * @param tanggal tanggal pemakaian baru
	 */
	public void setTanggal(Date tanggal) {
		this.tanggal = tanggal;
	}

	/**
	 * Mengembalikan tanggal pemakaian alat ini, dipetakan sebagai {@code TIMESTAMP} dengan nilai
	 * baku waktu instansiasi objek. Berbeda dari {@link ItemDiagnosaPenyakit} yang membawa RENTANG
	 * tanggal pemakaian ({@code mulai}/{@code sampai}), kelas ini hanya membawa satu titik waktu.
	 *
	 * @return tanggal pemakaian; tidak pernah {@code null} untuk objek baru
	 */
	@Temporal(TemporalType.TIMESTAMP)
	public Date getTanggal() {
		return tanggal;
	}
}
