package ais.database.model.sirs;

// Generated Apr 16, 2010 2:27:16 PM by Hibernate Tools 3.2.4.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;
import org.hibernate.envers.Audited;

import ais.database.model.GeneralValueObject;
import ais.database.model.asset.Lokasi;

/**
 * Bank generated by hbm2java
 *
 * <p>Buku besar mutasi JASA pada modul SIRS — tabel {@code sirs.detail_transaksi_layanan}. Satu baris
 * mencatat satu layanan yang diberikan kepada pasien: sebuah {@link Tindakan}, pemakaian sebuah
 * {@link AlatMedis}, sebuah {@link KunjunganDokter}, atau pencetakan {@link CetakKartuPasien}. Sebab
 * layanan itu tercatat dinyatakan oleh salah satu FK sumber, sama seperti pada kembarannya.</p>
 *
 * <h2>Hubungan dengan DetailTransaksiPasien dan TransaksiMedis</h2>
 * <p>Kelas ini adalah <b>pasangan kembar</b> {@link DetailTransaksiPasien}: keduanya merupakan buku besar
 * yang diturunkan dari rantai penagihan yang SAMA, dibedakan menurut sifat yang dicatat —
 * {@link DetailTransaksiPasien} untuk BARANG (obat, alat habis pakai, sekaligus seluruh mutasi gudang
 * non-tagihan), kelas ini untuk JASA. Keduanya menyimpan FK {@link #getTransaksiDetail()} ke
 * {@link TransaksiMedisDetail} dan sama-sama menyalin harga dari baris nota itu. Jadi
 * {@link TransaksiMedis} dan pasangan {@code DetailTransaksi*} <b>bukan dua rantai penagihan yang
 * berdiri sendiri</b>, melainkan satu rantai dengan percabangan buku besar.</p>
 * <p>Keduanya nyaris identik struktur maupun perilakunya. Perbedaan yang nyata dan perlu diketahui:</p>
 * <ul>
 *   <li>Kelas ini tidak memiliki FK sumber untuk mutasi gudang (penerimaan, transfer, koreksi, produksi,
 *       saldo awal, retur, pemakaian) maupun untuk racikan — jasa tidak berstok.</li>
 *   <li>Kelas ini tidak memiliki {@code amountTambahan} dan tidak memiliki kaitan ke diagnosa penyakit;
 *       field {@code tindakanDiagnosaPenyakit} ada di berkas ini namun <b>dikomentari</b>, sehingga
 *       kaitan rencana perawatan untuk jasa hanya tersedia lewat {@link TransaksiMedisDetail}.</li>
 *   <li>Field {@code hasilPenghitunganTotal} di sini tidak diberi nilai awal, sedangkan pada
 *       {@link DetailTransaksiPasien} diberi {@code 0.0}. Perbedaan itu tidak berdampak karena getternya
 *       selalu menghitung ulang, tetapi objek baru yang belum pernah dibaca akan memuat {@code null} di
 *       sini dan {@code 0.0} di sana.</li>
 * </ul>
 *
 * <h2>Peringatan integritas</h2>
 * <p>Seluruh peringatan pada {@link DetailTransaksiPasien} berlaku sama di sini: harga disalin ulang dari
 * baris nota pada setiap pembacaan sehingga baris yang sudah diposting masih dapat berubah nilainya;
 * {@link #getDiskon()} dan {@link #getPajak()} menghapus nilai rupiah yang diisi manual;
 * {@link #setQty(Double)} dan {@link #setAmount(Double)} memaksa nilai mutlak sehingga arah mutasi tidak
 * dapat dinyatakan lewat tanda; dan {@link #setLunas(Boolean)} adalah penanda dua arah tanpa penjaga yang
 * ditulis {@code true} oleh alur pembayaran tanpa membandingkan nilai bayar dengan nilai tagih.</p>
 *
 * @see DetailTransaksiPasien
 * @see TransaksiMedisDetail
 * @see Pembayaran
 * @see GeneralValueObject
 */
@Entity
@org.hibernate.annotations.Entity(
    dynamicInsert = true,
    dynamicUpdate = true
)
@Audited
@Table(schema = "sirs", name = "detail_transaksi_layanan")
public class DetailTransaksiLayanan extends GeneralValueObject {

	/**
	 * Penanda versi serialisasi, diwarisi dari templat generator yang sama dengan entity SIRS lain.
	 */
	private static final long serialVersionUID = 2463821577548439808L;

	/**
	 * Kunci utama (PK) baris, dihasilkan database lewat kolom identity {@code id}.
	 */
	private Long id;

	/**
	 * Field bayangan audit: id pengguna yang terakhir mengubah baris ini.
	 */
	private String olehId;

	/**
	 * Mengembalikan id pengguna yang terakhir mengubah baris ini.
	 *
	 * @return id pengguna pengubah terakhir, atau {@code null} bila belum pernah diisi.
	 */
	public String getOlehId() {
		return olehId;
	}

	/**
	 * Menetapkan id pengguna pengubah terakhir; nilai {@code null} atau kosong sengaja diabaikan.
	 *
	 * <p>Penjaga ini keharusan teknis, bukan cacat: binding form ZK kerap mengirim string kosong untuk
	 * kolom audit yang tidak ditampilkan, dan jejak pengubah pada baris tagihan jasa tidak boleh terhapus
	 * oleh penyimpanan biasa.</p>
	 *
	 * @param olehId id pengguna pengubah; nilai kosong diabaikan.
	 */
	public void setOlehId(String olehId) {if (olehId == null || olehId.trim().isEmpty()) {return;}
		this.olehId = olehId;
	}

	/**
	 * Field bayangan audit: nama pengguna yang terakhir mengubah baris ini.
	 */
	private String oleh;

	/**
	 * Mengembalikan representasi teks baris ini untuk komponen ZK, berupa isi {@link #getKeterangan()}.
	 *
	 * @return keterangan baris, mungkin {@code null}.
	 */
	public String toString() {
		return keterangan;
	}

	/**
	 * Menetapkan nama pengguna pengubah terakhir; nilai kosong diabaikan dengan alasan yang sama seperti
	 * {@link #setOlehId(String)}.
	 *
	 * @param oleh nama pengguna pengubah; nilai kosong diabaikan.
	 */
	public void setOleh(String oleh) {if (oleh == null || oleh.trim().isEmpty()) {return;}
		this.oleh = oleh;
	}

	/**
	 * Mengembalikan nama pengguna yang terakhir mengubah baris ini.
	 *
	 * @return nama pengguna pengubah terakhir, atau {@code null} bila belum pernah diisi.
	 */
	public String getOleh() {
		return oleh;
	}

	/**
	 * Kait JPA {@code @PreUpdate} yang memperbarui stempel waktu perubahan lewat
	 * {@code ais.database.hibernate.AuditTimestampInterceptor}. Tidak dipanggil langsung oleh kode
	 * aplikasi.
	 */
	@javax.persistence.PreUpdate protected void onUpdate() { ais.database.hibernate.AuditTimestampInterceptor.ubah(this);}     /**
	 * Field bayangan audit: stempel waktu perubahan terakhir, diinisialisasi ke waktu pembuatan objek.
	 */
	private Date tanggal_dirubah = new Date();

	/**
	 * Menetapkan stempel waktu perubahan terakhir. Umumnya diisi interceptor audit.
	 *
	 * @param tanggal_dirubah stempel waktu perubahan terakhir.
	 */
	public void setTanggal_dirubah(Date tanggal_dirubah) {
		this.tanggal_dirubah = tanggal_dirubah;
	}

	/**
	 * Mengembalikan stempel waktu perubahan terakhir baris ini.
	 *
	 * @return stempel waktu perubahan terakhir.
	 */
	@Temporal(TemporalType.TIMESTAMP)
	public Date getTanggal_dirubah() {
		return tanggal_dirubah;
	}

	/**
	 * Keterangan bebas atas baris; juga menjadi hasil {@link #toString()}.
	 */
	private String keterangan;

	/**
	 * Pasien penerima layanan.
	 */
	private Pasien pasien;

	/**
	 * Waktu layanan dicatat, diinisialisasi ke waktu pembuatan objek.
	 */
	private Date tanggal = new Date();

	/**
	 * Kuantitas layanan. Selalu tersimpan sebagai nilai mutlak karena {@link #setQty(Double)} memaksa
	 * {@code Math.abs}.
	 */
	private Double qty = 0.0;

	/**
	 * Kuantitas bonus (layanan gratis) yang menyertai baris. Tidak ikut dihitung dalam
	 * {@link #getHasilPenghitunganTotal()}.
	 */
	private Double qtyBonus = 0.0;

	/**
	 * Tindakan medis yang diberikan, bila baris ini merupakan tindakan.
	 */
	private Tindakan tindakan;

	/**
	 * Alat medis yang dipakai/disewa, bila baris ini merupakan pemakaian alat.
	 */
	private AlatMedis alatMedis;

	/**
	 * Lokasi (unit) tempat layanan diberikan.
	 */
	private Lokasi lokasi;

	/**
	 * Harga satuan layanan. Untuk baris yang bersumber dari nota, nilainya <b>disalin</b> dari
	 * {@link TransaksiMedisDetail#getAmount()} oleh {@link #getAmount()} pada setiap pembacaan.
	 */
	private Double amount = 0.0;

	/**
	 * Nilai rupiah diskon per satuan. <b>Bukan nilai mandiri</b> — selalu dihitung ulang dari
	 * {@code diskonPersen} oleh {@link #getDiskon()}.
	 */
	private Double diskon = 0.0;

	/**
	 * Nilai rupiah pajak per satuan. <b>Bukan nilai mandiri</b> — selalu dihitung ulang dari
	 * {@code pajakPersen} oleh {@link #getPajak()}.
	 */
	private Double pajak = 0.0;

	/**
	 * Persentase diskon terhadap harga satuan; inilah nilai yang benar-benar dipegang pengguna.
	 */
	private Double diskonPersen = 0.0;

	/**
	 * Persentase pajak terhadap harga satuan; inilah nilai yang benar-benar dipegang pengguna.
	 */
	private Double pajakPersen = 0.0;

	// Field reference
	// private TindakanDiagnosaPenyakit tindakanDiagnosaPenyakit;
	/**
	 * Kode transaksi yang menggolongkan layanan ini bagi laporan pendapatan jasa.
	 */
	private KodeTransaksiMedis kodeTransaksi;

	/**
	 * Kunjungan pasien yang menaungi layanan ini.
	 */
	private Pendaftaran pendaftaran;

	/**
	 * FK sumber: pencetakan kartu pasien yang ditagihkan.
	 */
	private CetakKartuPasien cetakKartuPasien;

	/**
	 * FK sumber: kunjungan dokter (visite) yang ditagihkan.
	 */
	private KunjunganDokter kunjunganDokter;

	/**
	 * FK sumber: baris nota yang menagihkan layanan ini. Inilah relasi yang membuat {@link #getAmount()}
	 * menyalin harga dari nota.
	 */
	private TransaksiMedisDetail transaksiDetail;

	/**
	 * Penanda baris sudah masuk jurnal akuntansi. Default {@code false}.
	 */
	private Boolean posting = false;

	/**
	 * Waktu baris masuk jurnal akuntansi.
	 */
	private Date tanggalPosting;

	/**
	 * Penanda baris sudah terbayar. Flag tersimpan biasa — tidak dihitung ulang. Default {@code false}.
	 */
	private Boolean lunas = false;

	/**
	 * Pembayaran yang melunasi baris ini.
	 */
	private Pembayaran pembayaran;

	/**
	 * Nilai total baris hasil hitung. Selalu ditimpa {@link #getHasilPenghitunganTotal()} saat dibaca.
	 * Berbeda dengan {@link DetailTransaksiPasien}, field ini tidak diberi nilai awal.
	 */
	private Double hasilPenghitunganTotal;

	/**
	 * FK sumber: layanan yang termasuk dalam paket perawatan pasien.
	 */
	private PaketPerawatanDetailPasien paketPerawatanDetailPasien;

	/**
	 * Konstruktor tanpa argumen yang dibutuhkan Hibernate/JPA untuk membuat instance saat memuat baris.
	 */
	public DetailTransaksiLayanan() {
	}

	/**
	 * Mengembalikan kunci utama baris.
	 *
	 * @return id baris, atau {@code null} bila entity belum tersimpan.
	 */
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", insertable = false, unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	/**
	 * Menetapkan kunci utama baris. Umumnya hanya dipanggil Hibernate.
	 *
	 * @param id kunci utama baris.
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * Mengembalikan keterangan bebas atas baris.
	 *
	 * @return keterangan baris, boleh {@code null}.
	 */
	@Column(name = "keterangan", nullable = true)
	public String getKeterangan() {
		return this.keterangan;
	}

	/**
	 * Menetapkan keterangan bebas atas baris.
	 *
	 * @param keterangan keterangan baris.
	 */
	public void setKeterangan(String keterangan) {
		this.keterangan = keterangan;
	}

	/**
	 * Mengembalikan waktu layanan dicatat.
	 *
	 * @return waktu pencatatan layanan, boleh {@code null} bila sengaja dikosongkan.
	 */
	@Temporal(TemporalType.TIMESTAMP)
	public Date getTanggal() {
		return tanggal;
	}

	/**
	 * Menetapkan waktu layanan dicatat.
	 *
	 * @param tanggal waktu pencatatan layanan.
	 */
	public void setTanggal(Date tanggal) {
		this.tanggal = tanggal;
	}

	/**
	 * Mengembalikan kuantitas layanan, dengan menormalkan {@code null} menjadi {@code 0.0}.
	 *
	 * <p>Normalisasi ini destruktif dan ikut tersimpan pada flush berikutnya. Kolom dipetakan
	 * {@code nullable = false}.</p>
	 * <p>Perhatikan bahwa untuk baris sewa {@link AlatMedis}, kuantitas TIDAK dihitung ulang dari rentang
	 * waktu di sini — perhitungan itu hanya ada pada {@link TransaksiMedisDetail#getQty()}. Buku besar ini
	 * memakai kuantitas yang tersimpan, sehingga bila baris nota menghitung ulang kuantitasnya (misalnya
	 * karena rentang pemakaian diperbaiki), buku besar ini <b>tidak</b> ikut menyesuaikan diri. Harga
	 * disalin ulang, kuantitas tidak — dua kolom pada satu baris yang bersumber dari nota yang sama
	 * karenanya dapat mengikuti dua keadaan yang berbeda.</p>
	 *
	 * @return kuantitas layanan; tidak pernah {@code null}.
	 */
	@Column(name = "qty", nullable = false)
	public Double getQty() {
		if (qty == null) {
			qty = 0.0;
		}
		return qty;
	}

	/**
	 * Menetapkan kuantitas layanan, dengan memaksa nilai mutlak dan memperlakukan {@code null} sebagai
	 * {@code 0.0}.
	 *
	 * <p>Sebagaimana {@link DetailTransaksiPasien#setQty(Double)}, pemaksaan ini berarti buku besar tidak
	 * dapat menyimpan kuantitas negatif, sehingga pembalikan layanan harus dinyatakan lewat mekanisme
	 * retur tersendiri, bukan lewat angka negatif.</p>
	 *
	 * @param qty kuantitas layanan; tanda minus dihapus.
	 */
	public void setQty(Double qty) {
		this.qty = Math.abs(qty == null ? 0.0 : qty);
	}

	/**
	 * Mengembalikan tindakan medis yang diberikan, setelah proxy lazy diselesaikan lewat
	 * {@link GeneralValueObject#check(Object)}.
	 *
	 * @return tindakan medis, atau {@code null} bila baris ini bukan tindakan.
	 */
	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY)
	@JoinColumn(name = "tindakan", nullable = true)
	public Tindakan getTindakan() {
		tindakan = check(tindakan);
		return tindakan;
	}

	/**
	 * Menetapkan tindakan medis yang diberikan.
	 *
	 * @param tindakan tindakan medis.
	 */
	public void setTindakan(Tindakan tindakan) {
		this.tindakan = tindakan;
	}

	/**
	 * Mengembalikan lokasi (unit) tempat layanan diberikan, setelah proxy lazy diselesaikan lewat
	 * {@link GeneralValueObject#check(Object)}.
	 *
	 * @return lokasi layanan, boleh {@code null}.
	 */
	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY)
	@JoinColumn(name = "lokasi", nullable = true)
	public Lokasi getLokasi() {
		lokasi = check(lokasi);
		return lokasi;
	}

	/**
	 * Menetapkan lokasi (unit) tempat layanan diberikan.
	 *
	 * <p>Setter polos tanpa penyaringan lingkup: tidak ada pemeriksaan bahwa lokasi yang dipilih termasuk
	 * lingkup pengguna atau unit yang sama dengan FK sumbernya, termasuk untuk baris yang sudah
	 * diposting.</p>
	 *
	 * @param lokasi lokasi layanan.
	 */
	public void setLokasi(Lokasi lokasi) {
		this.lokasi = lokasi;
	}

	/**
	 * Mengembalikan harga satuan layanan, dengan menyalin harga dari baris nota bila baris ini bersumber
	 * dari penagihan.
	 *
	 * <p><b>Getter destruktif.</b> Bila {@code transaksiDetail} terisi, field {@code amount}
	 * <i>ditimpa</i> dengan {@link TransaksiMedisDetail#getAmount()}; sesudah itu nilai {@code null} atau
	 * {@code NaN} dinormalkan menjadi {@code 0.0}. Karena getter dipetakan Hibernate, hasil salinan ikut
	 * tertulis ke kolom {@code amount} pada flush berikutnya.</p>
	 * <p>Konsekuensi yang perlu dipahami:</p>
	 * <ul>
	 *   <li><b>Harga buku besar bukan snapshot.</b> Buku besar jasa ini tidak mengawetkan tarif yang
	 *       berlaku saat layanan diberikan; ia mengikuti harga baris nota selamanya. Mengubah harga di
	 *       {@link TransaksiMedisDetail} — termasuk lewat harga manual
	 *       {@link TransaksiMedisDetail#getAmountCustom()} — otomatis mengubah nilai layanan yang sudah
	 *       tercatat, bahkan bila baris ini sudah ditandai {@link #getPosting()} dan sudah masuk jurnal
	 *       akuntansi. Tidak ada pembekuan nilai pada saat posting dan tidak ada pembandingan dengan angka
	 *       yang sudah dijurnal, sehingga selisih antara buku besar jasa dan jurnal akuntansi dapat muncul
	 *       tanpa jejak selain audit Envers.</li>
	 *   <li><b>Kuantitas tidak ikut disalin.</b> Hanya harga yang disegarkan dari nota. Untuk baris sewa
	 *       alat medis yang kuantitasnya dihitung ulang di {@link TransaksiMedisDetail#getQty()}, buku
	 *       besar ini akan memakai harga baru dengan kuantitas lama.</li>
	 *   <li><b>Penimpaan memakai field, bukan getter.</b> Syaratnya memeriksa variabel
	 *       {@code transaksiDetail} secara langsung. Relasi itu dipetakan eager dengan
	 *       {@code @Fetch(FetchMode.SELECT)}, tetapi pada entity detached yang relasinya belum termuat
	 *       penyalinan tidak terjadi dan nilai lama dipakai apa adanya — perbedaan perilaku yang
	 *       bergantung pada keadaan session, bukan pada data.</li>
	 *   <li><b>Penjaga {@code NaN} menyembunyikan gejala.</b> Nilai {@code NaN} diubah menjadi nol alih-alih
	 *       ditolak, sehingga tarif yang gagal dihitung diam-diam tercatat bernilai nol.</li>
	 *   <li><b>Baris non-nota memakai nilai mandiri.</b> Untuk baris yang bersumber dari
	 *       {@link #getKunjunganDokter()}, {@link #getCetakKartuPasien()}, atau paket perawatan, cabang
	 *       penyalinan dilewati dan nilai hasil {@link #setAmount(Double)} dipakai. Kolom yang sama
	 *       karenanya memiliki dua asal-usul berbeda tergantung jenis barisnya.</li>
	 * </ul>
	 *
	 * @return harga satuan layanan; tidak pernah {@code null} maupun {@code NaN}.
	 */
	public Double getAmount() {

		if (transaksiDetail != null) {
			amount = transaksiDetail.getAmount();
		}

		if (amount == null || Double.isNaN(amount)) {
			amount = 0.0;
		}
		return amount;
	}

	/**
	 * Menetapkan harga satuan layanan, dengan memaksa nilai mutlak dan memperlakukan {@code null} sebagai
	 * {@code 0.0}.
	 *
	 * <p>Pemaksaan nilai mutlak berarti tarif negatif tidak dapat dicatat; baris koreksi bernilai minus
	 * akan berbalik menjadi penambahan pendapatan. Untuk baris yang bersumber dari nota, nilai ini juga
	 * tidak bertahan karena {@link #getAmount()} menimpanya dari baris nota.</p>
	 *
	 * @param amount harga satuan layanan; tanda minus dihapus.
	 */
	public void setAmount(Double amount) {
		this.amount = Math.abs(amount == null ? 0.0 : amount);
	}

	/**
	 * Menetapkan kuantitas bonus, dengan memaksa nilai mutlak dan memperlakukan {@code null} sebagai
	 * {@code 0.0}.
	 *
	 * @param qtyBonus kuantitas bonus; tanda minus dihapus.
	 */
	public void setQtyBonus(Double qtyBonus) {
		this.qtyBonus = Math.abs(qtyBonus == null ? 0.0 : qtyBonus);
	}

	/**
	 * Mengembalikan kuantitas bonus (layanan gratis) yang menyertai baris.
	 *
	 * <p>Nilai ini tidak ikut dalam {@link #getHasilPenghitunganTotal()} — layanan bonus dicatat sebagai
	 * jumlah tetapi tidak menambah pendapatan. Laporan produktivitas layanan wajib menjumlahkan
	 * {@link #getQty()} DAN kolom ini, sementara laporan pendapatan hanya boleh memakai
	 * {@link #getQty()}. Berbeda dengan {@link #getQty()}, getter ini tidak menormalkan {@code null},
	 * sehingga baris lama dapat mengembalikan {@code null} walau kolom dipetakan
	 * {@code nullable = false}.</p>
	 *
	 * @return kuantitas bonus, dapat {@code null} pada baris lama.
	 */
	@Column(name = "qty_bonus", nullable = false)
	public Double getQtyBonus() {
		return qtyBonus;
	}

	/**
	 * Menetapkan penanda baris sudah masuk jurnal akuntansi.
	 *
	 * <p>Penanda dua arah tanpa penjaga: nilai {@code true} dapat dikembalikan menjadi {@code false} tanpa
	 * pemeriksaan, dan tidak ada keterkaitan otomatis dengan {@link #setTanggalPosting(Date)} sehingga
	 * keduanya dapat menjadi tidak sinkron.</p>
	 *
	 * @param posting penanda posting.
	 */
	public void setPosting(Boolean posting) {
		this.posting = posting;
	}

	/**
	 * Mengembalikan penanda baris sudah masuk jurnal akuntansi.
	 *
	 * @return {@code true} bila sudah diposting; dapat {@code null} pada baris lama.
	 */
	public Boolean getPosting() {
		return posting;
	}

	/**
	 * Menetapkan waktu baris masuk jurnal akuntansi.
	 *
	 * @param tanggalPosting waktu posting.
	 */
	public void setTanggalPosting(Date tanggalPosting) {
		this.tanggalPosting = tanggalPosting;
	}

	/**
	 * Mengembalikan waktu baris masuk jurnal akuntansi.
	 *
	 * @return waktu posting, atau {@code null} bila belum diposting.
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "tanggal_posting", nullable = true)
	public Date getTanggalPosting() {
		return tanggalPosting;
	}

	/**
	 * Menetapkan nilai rupiah diskon per satuan.
	 *
	 * <p>Nilai ini <b>tidak bertahan</b>: {@link #getDiskon()} menimpanya dengan hasil hitung dari
	 * persentase pada pembacaan berikutnya. Untuk memberi diskon, isilah
	 * {@link #setDiskonPersen(Double)}.</p>
	 *
	 * @param diskon nilai rupiah diskon per satuan.
	 */
	public void setDiskon(Double diskon) {
		this.diskon = diskon;
	}

	/**
	 * Mengembalikan nilai rupiah diskon per satuan, dihitung ulang dari persentase.
	 *
	 * <p><b>Getter destruktif.</b> Nilai {@code null} atau {@code NaN} dinormalkan menjadi {@code 0.0},
	 * lalu field {@code diskon} <i>ditimpa</i> dengan
	 * {@code getAmount() * (getDiskonPersen() / 100.0)}, dan hasilnya ikut tersimpan pada flush
	 * berikutnya.</p>
	 * <p>Konsekuensi yang perlu dipahami:</p>
	 * <ul>
	 *   <li><b>Diskon rupiah tidak dapat diberikan.</b> Syarat penimpaan
	 *       {@code getDiskonPersen() != null} selalu terpenuhi karena {@link #getDiskonPersen()}
	 *       menormalkan {@code null}/{@code NaN} menjadi {@code 0.0} dan tidak pernah mengembalikan
	 *       {@code null}. Diskon rupiah yang diisi manual berubah menjadi {@code 0.0} pada pembacaan
	 *       pertama, dan nol itu tersimpan permanen. Potongan bernilai tetap atas jasa — misalnya
	 *       keringanan biaya tindakan sebesar jumlah tertentu — tidak mungkin dinyatakan lewat entity
	 *       ini; satu-satunya jalan adalah mengubahnya menjadi persentase, yang berarti angkanya harus
	 *       dihitung ulang setiap kali tarif berubah.</li>
	 *   <li><b>Bergantung pada harga yang disalin.</b> Karena pengalinya {@link #getAmount()} — yang untuk
	 *       baris nota disalin dari {@link TransaksiMedisDetail} — mengubah tarif di baris nota otomatis
	 *       mengubah nilai rupiah diskon di sini, termasuk untuk baris yang sudah diposting.</li>
	 *   <li><b>Diskon bermakna per satuan.</b> Pengalinya harga satuan, bukan nilai baris. Laporan yang
	 *       menjumlahkan kolom {@code diskon} apa adanya akan meremehkan total diskon untuk baris
	 *       berkuantitas lebih dari satu.</li>
	 *   <li><b>Tidak ada pengecualian racikan.</b> Sama seperti {@link DetailTransaksiPasien#getDiskon()}
	 *       dan berbeda dari {@link TransaksiMedisDetail#getDiskon()}, blok ini selalu dijalankan.</li>
	 * </ul>
	 *
	 * @return nilai rupiah diskon per satuan; tidak pernah {@code null}.
	 */
	public Double getDiskon() {
		if (diskon == null || Double.isNaN(diskon)) {
			diskon = 0.0;
		}

		if (getDiskonPersen() != null && getAmount() != null) {
			diskon = getAmount() * (getDiskonPersen() / 100.0);
		}
		return diskon;
	}

	/**
	 * Menetapkan nilai rupiah pajak per satuan. Nilai ini tidak bertahan — isilah
	 * {@link #setPajakPersen(Double)} sebagai gantinya.
	 *
	 * @param pajak nilai rupiah pajak per satuan.
	 */
	public void setPajak(Double pajak) {
		this.pajak = pajak;
	}

	/**
	 * Mengembalikan nilai rupiah pajak per satuan, dihitung ulang dari persentase.
	 *
	 * <p>Getter destruktif dengan struktur dan seluruh konsekuensi yang sama persis seperti
	 * {@link #getDiskon()}: pajak rupiah yang diisi manual tidak bertahan, angka yang tersimpan bermakna
	 * per satuan, dan nilainya berubah mengikuti tarif yang disalin dari baris nota.</p>
	 *
	 * @return nilai rupiah pajak per satuan; tidak pernah {@code null}.
	 */
	public Double getPajak() {
		if (pajak == null || Double.isNaN(pajak)) {
			pajak = 0.0;
		}

		if (getPajakPersen() != null && getAmount() != null) {
			pajak = getAmount() * (getPajakPersen() / 100.0);
		}
		return pajak;
	}

	/**
	 * Menetapkan pasien penerima layanan.
	 *
	 * <p>Setter polos tanpa validasi. Tidak ada pemeriksaan silang terhadap pasien pada
	 * {@link #getPendaftaran()}, pada nota di balik {@link #getTransaksiDetail()}, maupun pada
	 * {@link #getPembayaran()}, sehingga pada tingkat model sebuah baris tagihan jasa dapat diarahkan ke
	 * pasien lain tanpa penolakan — termasuk baris yang sudah lunas dan sudah diposting. Perlu diingat
	 * bahwa baris ini juga memuat data kesehatan (tindakan apa yang diterima seseorang), sehingga
	 * pemindahan semacam itu bukan sekadar persoalan keuangan.</p>
	 *
	 * @param pasien pasien penerima layanan.
	 */
	public void setPasien(Pasien pasien) {
		this.pasien = pasien;
	}

	/**
	 * Mengembalikan pasien penerima layanan, setelah proxy lazy diselesaikan lewat
	 * {@link GeneralValueObject#check(Object)}.
	 *
	 * @return pasien penerima layanan, boleh {@code null}.
	 */
	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY)
	@JoinColumn(name = "pasien", nullable = true)
	public Pasien getPasien() {
		pasien = check(pasien);
		return pasien;
	}

	/**
	 * Menetapkan penanda baris sudah terbayar.
	 *
	 * <p><b>Penanda dua arah tanpa penjaga.</b> Tidak ada pemeriksaan terhadap nilai baris, terhadap
	 * keberadaan atau kecukupan {@link #getPembayaran()}, maupun terhadap status posting. Alur pembayaran
	 * {@code ais.action.master.sirs.PembayaranAction} (method {@code simpanDetailTransaksi}) memanggil
	 * setter ini dengan {@code true} untuk SETIAP baris layanan yang sedang diproses, tanpa lebih dahulu
	 * membandingkan total yang dibayar dengan total yang ditagihkan. Penjaga keseimbangan
	 * tagihan-pembayaran memang ada, tetapi letaknya di listener tombol simpan pada layar pembayaran —
	 * bukan di method penyimpanan dan bukan di entity ini. Setiap jalur penulisan baru yang tidak melewati
	 * tombol tersebut dapat menandai baris lunas tanpa uang yang masuk.</p>
	 * <p>Selain itu tidak ada pemeriksaan bahwa layanannya benar-benar sudah diberikan: tidak ada
	 * keterkaitan dengan status penyelesaian tindakan, dan {@link TransaksiMedis#getValidasi()} pun tidak
	 * dilihat. Sebuah layanan dapat berstatus lunas tanpa pernah dinyatakan selesai atau terverifikasi.</p>
	 *
	 * @param lunas penanda terbayar.
	 */
	public void setLunas(Boolean lunas) {
		this.lunas = lunas;
	}

	/**
	 * Mengembalikan penanda baris sudah terbayar.
	 *
	 * <p>Sebagaimana {@link DetailTransaksiPasien#getLunas()}, getter ini mengembalikan flag tersimpan apa
	 * adanya — berbeda dari {@link TransaksiMedis#getLunas()} dan {@link Pembayaran#getLunas()} yang
	 * menghitung ulang statusnya. Tiga tempat dalam satu rantai karenanya dapat memberi jawaban berbeda
	 * untuk tagihan yang sama.</p>
	 *
	 * @return {@code true} bila baris ditandai terbayar; dapat {@code null} pada baris lama.
	 */
	public Boolean getLunas() {
		return lunas;
	}

	/**
	 * Menetapkan pembayaran yang melunasi baris ini.
	 *
	 * <p>Setter polos: tidak ada pemeriksaan bahwa pembayaran tersebut milik pasien yang sama, bahwa
	 * nilainya mencukupi, atau bahwa baris belum terikat pembayaran lain.</p>
	 *
	 * @param pembayaran pembayaran pelunas.
	 */
	public void setPembayaran(Pembayaran pembayaran) {
		this.pembayaran = pembayaran;
	}

	/**
	 * Mengembalikan pembayaran yang melunasi baris ini.
	 *
	 * @return pembayaran pelunas, atau {@code null} bila baris belum dibayar.
	 */
	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE })
	@Fetch(FetchMode.SELECT)
	@JoinColumn(name = "pembayaran", nullable = true)
	public Pembayaran getPembayaran() {
		return pembayaran;
	}

	/**
	 * Menetapkan kunjungan pasien yang menaungi layanan ini.
	 *
	 * <p>Setter polos: tidak ada pemeriksaan bahwa kunjungan tersebut milik {@link #getPasien()} yang
	 * sama, sehingga dua kolom identitas yang seharusnya sejalan dapat menunjuk ke dua pasien
	 * berbeda.</p>
	 *
	 * @param pendaftaran kunjungan pasien.
	 */
	public void setPendaftaran(Pendaftaran pendaftaran) {
		this.pendaftaran = pendaftaran;
	}

	/**
	 * Mengembalikan kunjungan pasien yang menaungi layanan ini.
	 *
	 * @return kunjungan pasien, boleh {@code null}.
	 */
	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE })
	@Fetch(FetchMode.SELECT)
	@JoinColumn(name = "pendaftaran", nullable = true)
	public Pendaftaran getPendaftaran() {
		return pendaftaran;
	}

	/**
	 * Menetapkan FK sumber berupa pencetakan kartu pasien yang ditagihkan.
	 *
	 * @param cetakKartuPasien pencetakan kartu pasien.
	 */
	public void setCetakKartuPasien(CetakKartuPasien cetakKartuPasien) {
		this.cetakKartuPasien = cetakKartuPasien;
	}

	/**
	 * Mengembalikan FK sumber berupa pencetakan kartu pasien yang ditagihkan.
	 *
	 * @return pencetakan kartu pasien, atau {@code null} bila baris ini bukan cetak kartu.
	 */
	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE })
	@Fetch(FetchMode.SELECT)
	@JoinColumn(name = "cetak_kartu_pasien", nullable = true)
	public CetakKartuPasien getCetakKartuPasien() {
		return cetakKartuPasien;
	}

	/**
	 * Menetapkan FK sumber berupa kunjungan dokter (visite) yang ditagihkan.
	 *
	 * @param kunjunganDokter kunjungan dokter.
	 */
	public void setKunjunganDokter(KunjunganDokter kunjunganDokter) {
		this.kunjunganDokter = kunjunganDokter;
	}

	/**
	 * Mengembalikan FK sumber berupa kunjungan dokter (visite) yang ditagihkan.
	 *
	 * @return kunjungan dokter, atau {@code null} bila baris ini bukan visite.
	 */
	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE })
	@Fetch(FetchMode.SELECT)
	@JoinColumn(name = "kunjungan_dokter", nullable = true)
	public KunjunganDokter getKunjunganDokter() {
		return kunjunganDokter;
	}

	/**
	 * Mengembalikan FK sumber berupa baris nota yang menagihkan layanan ini.
	 *
	 * @return baris nota, atau {@code null} bila baris ini tidak lahir dari nota.
	 */
	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE })
	@Fetch(FetchMode.SELECT)
	@JoinColumn(name = "transaksi_detail", nullable = true)
	public TransaksiMedisDetail getTransaksiDetail() {
		return transaksiDetail;
	}

	/**
	 * Menetapkan FK sumber berupa baris nota yang menagihkan layanan ini.
	 *
	 * <p>Mengisi relasi ini <b>mengubah perilaku</b> {@link #getAmount()}: harga satuan berhenti menjadi
	 * data mandiri dan mulai disalin dari baris nota pada setiap pembacaan. Setter ini polos — tidak ada
	 * pemeriksaan bahwa baris nota tersebut milik pasien yang sama dengan {@link #getPasien()}.</p>
	 *
	 * @param transaksiDetail baris nota.
	 */
	public void setTransaksiDetail(TransaksiMedisDetail transaksiDetail) {
		this.transaksiDetail = transaksiDetail;
	}

	/**
	 * Mengembalikan kode transaksi yang menggolongkan layanan ini, setelah proxy lazy diselesaikan lewat
	 * {@link GeneralValueObject#check(Object)}.
	 *
	 * @return kode transaksi, boleh {@code null}.
	 */
	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY)
	@JoinColumn(name = "kode_transaksi", nullable = true)
	public KodeTransaksiMedis getKodeTransaksi() {
		kodeTransaksi = check(kodeTransaksi);
		return kodeTransaksi;
	}

	/**
	 * Menetapkan kode transaksi yang menggolongkan layanan ini.
	 *
	 * <p>Setter polos: tidak ada pemeriksaan bahwa kode yang dipilih sesuai dengan FK sumber yang terisi,
	 * sehingga laporan pendapatan yang mengelompokkan berdasarkan kode dapat menempatkan layanan pada
	 * golongan yang salah tanpa keberatan.</p>
	 *
	 * @param kodeTransaksi kode transaksi.
	 */
	public void setKodeTransaksi(KodeTransaksiMedis kodeTransaksi) {
		this.kodeTransaksi = kodeTransaksi;
	}

	/**
	 * Mengembalikan alat medis yang dipakai/disewa, setelah proxy lazy diselesaikan lewat
	 * {@link GeneralValueObject#check(Object)}.
	 *
	 * @return alat medis, atau {@code null} bila baris ini bukan pemakaian alat.
	 */
	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY)
	@JoinColumn(name = "alat_medis", nullable = true)
	public AlatMedis getAlatMedis() {
		alatMedis = check(alatMedis);
		return alatMedis;
	}

	/**
	 * Menetapkan alat medis yang dipakai/disewa.
	 *
	 * <p>Berbeda dengan {@link TransaksiMedisDetail#setAlatMedis(AlatMedis)}, mengisi relasi ini
	 * <b>tidak</b> mengaktifkan perhitungan ulang kuantitas dari rentang waktu — buku besar ini tidak
	 * menyimpan rentang pemakaian sama sekali.</p>
	 *
	 * @param alatMedis alat medis.
	 */
	public void setAlatMedis(AlatMedis alatMedis) {
		this.alatMedis = alatMedis;
	}

	/**
	 * Mengembalikan persentase diskon, dengan menormalkan {@code null} dan {@code NaN} menjadi
	 * {@code 0.0}.
	 *
	 * <p>Normalisasi ini destruktif dan menjadi sebab mengapa syarat penimpaan pada {@link #getDiskon()}
	 * selalu terpenuhi.</p>
	 *
	 * @return persentase diskon; tidak pernah {@code null}.
	 */
	public Double getDiskonPersen() {
		if (diskonPersen == null || Double.isNaN(diskonPersen)) {
			diskonPersen = 0.0;
		}
		return diskonPersen;
	}

	/**
	 * Menetapkan persentase diskon terhadap harga satuan. Tidak ada pembatasan rentang — nilai di atas
	 * 100 membuat total baris menjadi negatif tanpa penolakan.
	 *
	 * @param diskonPersen persentase diskon.
	 */
	public void setDiskonPersen(Double diskonPersen) {
		this.diskonPersen = diskonPersen;
	}

	/**
	 * Mengembalikan persentase pajak, dengan menormalkan {@code null} dan {@code NaN} menjadi
	 * {@code 0.0}.
	 *
	 * @return persentase pajak; tidak pernah {@code null}.
	 */
	public Double getPajakPersen() {
		if (pajakPersen == null || Double.isNaN(pajakPersen)) {
			pajakPersen = 0.0;
		}
		return pajakPersen;
	}

	/**
	 * Menetapkan persentase pajak terhadap harga satuan. Tidak ada pembatasan rentang.
	 *
	 * @param pajakPersen persentase pajak.
	 */
	public void setPajakPersen(Double pajakPersen) {
		this.pajakPersen = pajakPersen;
	}

	/**
	 * Mengembalikan nilai total baris, dihitung ulang sebagai {@code qty * ((amount - diskon) + pajak)}.
	 *
	 * <p><b>Getter destruktif dan getter terhitung.</b> Seluruh komponennya dibaca lewat getter, sehingga
	 * satu pemanggilan memicu penyalinan harga dari {@link TransaksiMedisDetail} serta penimpaan diskon
	 * dan pajak dari persentase sekaligus. Semua penimpaan itu ikut tersimpan pada flush berikutnya, jadi
	 * membaca nilai pendapatan jasa <i>bukan</i> operasi baca murni.</p>
	 * <p>Hal-hal yang perlu diperhatikan:</p>
	 * <ul>
	 *   <li><b>Baris yang sudah diposting tetap dapat berubah nilainya</b>, karena harga disalin ulang dari
	 *       baris nota setiap kali dibaca dan diskon serta pajak dihitung ulang dari harga itu. Tidak ada
	 *       pembekuan nilai pada saat posting.</li>
	 *   <li><b>Kuantitas bonus tidak dihitung</b> — layanan gratis menambah jumlah tetapi tidak menambah
	 *       pendapatan.</li>
	 *   <li><b>Tidak ada penjaga nilai negatif.</b> Meski {@link #setQty(Double)} dan
	 *       {@link #setAmount(Double)} memaksa nilai mutlak, persentase diskon di atas 100 tetap membuat
	 *       hasil method ini negatif tanpa penolakan.</li>
	 *   <li><b>Diskon dan pajak bersifat per satuan</b>, diterapkan pada harga satuan lebih dahulu sebelum
	 *       seluruhnya dikalikan kuantitas.</li>
	 * </ul>
	 *
	 * @return nilai total baris hasil hitung.
	 */
	public Double getHasilPenghitunganTotal() {
		Double jumlah = ((getAmount() - getDiskon()) + getPajak());
		hasilPenghitunganTotal = getQty() * jumlah;
		return hasilPenghitunganTotal;
	}

	/**
	 * Menetapkan nilai total baris. Nilai ini tidak bertahan — {@link #getHasilPenghitunganTotal()}
	 * menimpanya pada pembacaan berikutnya.
	 *
	 * @param hasilPenghitunganTotal nilai total baris.
	 */
	public void setHasilPenghitunganTotal(Double hasilPenghitunganTotal) {
		this.hasilPenghitunganTotal = hasilPenghitunganTotal;
	}

	/**
	 * Mengembalikan FK sumber berupa layanan yang termasuk dalam paket perawatan pasien.
	 *
	 * @return kaitan paket perawatan, atau {@code null}.
	 */
	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE })
	@Fetch(FetchMode.SELECT)
	@JoinColumn(name = "paket_perawatan_detail_pasien", nullable = true)
	public PaketPerawatanDetailPasien getPaketPerawatanDetailPasien() {
		return paketPerawatanDetailPasien;
	}

	/**
	 * Menetapkan FK sumber berupa layanan yang termasuk dalam paket perawatan pasien.
	 *
	 * @param paketPerawatanDetailPasien kaitan paket perawatan.
	 */
	public void setPaketPerawatanDetailPasien(PaketPerawatanDetailPasien paketPerawatanDetailPasien) {
		this.paketPerawatanDetailPasien = paketPerawatanDetailPasien;
	}
}
