package ais.database.model.sirs;

// Generated Dec 12, 2009 7:42:38 PM by Hibernate Tools 3.2.4.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.envers.Audited;

import ais.database.model.GeneralValueObject;
import ais.database.model.asset.Lokasi;

/**
 * JadwalDokter generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Entity(
    dynamicInsert = true,
    dynamicUpdate = true
)
@Audited
@Table(schema = "sirs", name = "jadwal_dokter")
public class JadwalDokter extends GeneralValueObject {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6970840500825359503L;

	private Long id;
	private String olehId;

	public String getOlehId() {
		return olehId;
	}

	public void setOlehId(String olehId) {if (olehId == null || olehId.trim().isEmpty()) {return;}
		this.olehId = olehId;
	}

	private String oleh;

	public void setOleh(String oleh) {if (oleh == null || oleh.trim().isEmpty()) {return;}
		this.oleh = oleh;
	}

	public String getOleh() {
		return oleh;
	}

	@javax.persistence.PreUpdate protected void onUpdate() { ais.database.hibernate.AuditTimestampInterceptor.ubah(this);}     private Date tanggal_dirubah = new Date();

	public void setTanggal_dirubah(Date tanggal_dirubah) {
		this.tanggal_dirubah = tanggal_dirubah;
	}

	@Temporal(TemporalType.TIMESTAMP)
	public Date getTanggal_dirubah() {
		return tanggal_dirubah;
	}

	public String toString() {
		getDokter();
		getPoly();
		getShift();
		return dokter + " - " + (poly == null ? "" : poly.toString()) + " - " + hari + " - " + shift;
	}

	private Shift shift;
	private Dokter dokter;
	private Lokasi lokasi;
	private Poly poly;

	private String hari = "Senin";
	private String warna = "#A32929,#D96666";

	private Date jadwalDokterDimulai = new Date();
	private Date jadwalDokterSampai;

	private String keterangan;
	private String deskripsi;

	public JadwalDokter() {

	}

	public JadwalDokter(Long id) {
		this.id = id;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", insertable = false, unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY)
	@JoinColumn(name = "shift", nullable = false)
	public Shift getShift() {
		shift = check(shift);
		return this.shift;
	}

	public void setShift(Shift shift) {
		this.shift = shift;
	}

	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY)
	@JoinColumn(name = "dokter", nullable = false)
	public Dokter getDokter() {
		dokter = check(dokter);
		return this.dokter;
	}

	public void setDokter(Dokter dokter) {
		this.dokter = dokter;
	}

	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY)
	@JoinColumn(name = "lokasi", nullable = false)
	public Lokasi getLokasi() {
		lokasi = check(lokasi);
		return this.lokasi;
	}

	public void setLokasi(Lokasi lokasi) {
		this.lokasi = lokasi;
	}

	public void setHari(String hari) {
		this.hari = hari;
	}

	@Column(name = "hari", length = 20)
	public String getHari() {
		return hari;
	}

	public void setWarna(String warna) {
		this.warna = warna;
	}

	@Column(name = "warna", nullable = true, length = 20)
	public String getWarna() {
		return warna;
	}

	@Temporal(TemporalType.DATE)
	public Date getJadwalDokterDimulai() {
		return jadwalDokterDimulai;
	}

	public void setJadwalDokterDimulai(Date jadwalDokterDimulai) {
		this.jadwalDokterDimulai = jadwalDokterDimulai;
	}

	@Temporal(TemporalType.DATE)
	public Date getJadwalDokterSampai() {
		return jadwalDokterSampai;
	}

	public void setJadwalDokterSampai(Date jadwalDokterSampai) {
		this.jadwalDokterSampai = jadwalDokterSampai;
	}

	public String getKeterangan() {
		return keterangan;
	}

	public void setKeterangan(String keterangan) {
		this.keterangan = keterangan;
	}

	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY)
	@JoinColumn(name = "poly")
	public Poly getPoly() {
		poly = check(poly);
		return poly;
	}

	public void setPoly(Poly poly) {
		this.poly = poly;
	}

	public String getDeskripsi() {
		deskripsi = toString();
		return deskripsi;
	}

	public void setDeskripsi(String deskripsi) {
		this.deskripsi = deskripsi;
	}

}
