package ais.database.model.sirs;

// Generated Apr 16, 2010 2:27:16 PM by Hibernate Tools 3.2.4.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.envers.Audited;

import ais.database.model.GeneralValueObject;

/**
 * Bank generated by hbm2java
 *
 * <p>
 * <b>Katalog butir pemeriksaan (parameter keluhan/riwayat kesehatan/pemeriksaan fisik) yang
 * ditawarkan kepada tenaga medis saat mencatat diagnosa pasien.</b> Satu baris mewakili satu butir
 * (mis. "Tekanan Darah", "Riwayat Alergi", "Batuk") yang disusun sebagai <b>pohon</b> lewat
 * {@link #getParent()} dan diberi label kedalaman lewat {@link #getDeep()}. Kelas ini dipetakan ke
 * {@code sirs.pemeriksaan} dengan tabel audit Envers berpasangan
 * {@code new_audit.pemeriksaan__audit}, dikelola lewat {@code ais.action.master.sirs.PemeriksaanAction}
 * dan {@code ais.action.master.sirs.PemeriksaanTreeAction}, serta dipilih dari layar diagnosa
 * lewat {@code ais.action.master.sirs.helper.AmbilDataPemeriksaanBanbox}.
 * </p>
 *
 * <h2>Peran di dalam AIS — katalog parameter, nilai aktualnya di {@link DiagnosaPenyakitPunyaPemeriksaan}</h2>
 * <p>
 * Kelas ini HANYA mendefinisikan parameter apa saja yang dapat diperiksa dan bagaimana bentuk
 * isiannya (lihat {@link #getNilaiYangMungkin()}, {@link #getHarusDiisi()},
 * {@link #getJumlahBaris()}) — bukan nilai aktual hasil pemeriksaan pasien tertentu. Nilai aktual
 * per pasien/diagnosa disimpan terpisah di {@link DiagnosaPenyakitPunyaPemeriksaan}, yang merujuk
 * balik ke satu baris kelas ini lewat {@code pemeriksaan}. Formulir dinamis yang ditampilkan pada
 * layar diagnosa ({@code ais.action.master.sirs.DiagnosaPenyakitAction}/
 * {@code DiagnosaPenyakitDetailAction}) dibangun oleh {@code ais.action.master.sirs.detail.PemeriksaanHelper}
 * berdasar tiga jenis butir yang diwakili konstanta {@link #JENIS_KELUHAN}, {@link #JENIS_RIWAYAT},
 * dan {@link #JENIS_PERIKSA}, masing-masing dimuat lewat instans {@code PemeriksaanHelper} terpisah
 * pada kedua layar tersebut.
 * </p>
 *
 * <h2>{@link #getNilaiYangMungkin()} — mini-DSL berbasis delimiter untuk jenis isian</h2>
 * <p>
 * {@code PemeriksaanHelper} mem-parsing string ini untuk menentukan JENIS widget yang dirender
 * per butir: bila mengandung {@code "|"} atau {@code ";"}, nilainya dipecah (
 * {@code String.split("\\|")}/{@code split(";")}) menjadi daftar pilihan yang dirender sebagai
 * checkbox/opsi jamak; bila kosong, butir dirender sebagai kombinasi kombo Ya/Tidak dan kolom teks
 * bebas ({@code keterangan}) yang jumlah barisnya diatur {@link #getJumlahBaris()}. Tidak ada
 * validasi format pada model ini — kebenaran sintaks delimiter sepenuhnya menjadi tanggung jawab
 * operator yang mengisi katalog lewat {@code PemeriksaanAction}/{@code PemeriksaanTreeAction}.
 * </p>
 *
 * <h2>{@link #getHarusDiisi()} — SATU DARI SEDIKIT flag "wajib" yang benar-benar DITEGAKKAN</h2>
 * <p>
 * Berbeda dari sejumlah flag "wajib"/"diperlukan" kosmetik yang sudah ditemukan pada entity lain
 * (mis. {@code rab.ChecklistLaporanDetail#getDiperlukan()}), flag ini benar-benar ditegakkan:
 * {@code PemeriksaanHelper.check()} menolak penyimpanan diagnosa dan memunculkan pesan peringatan
 * bila sebuah butir dengan {@code harusDiisi = true} dibiarkan kosong (kombo Ya/Tidak tidak
 * dipilih, kolom keterangan kosong, DAN tidak ada checkbox pilihan ganda yang tercentang) — lihat
 * {@code PemeriksaanHelper.check()} yang memfokuskan kolom bermasalah pada pelanggaran pertama.
 * </p>
 *
 * <h2>Getter yang mengubah keadaan diam-diam — {@link #getDeep()} dan {@link #getJenis()}</h2>
 * <p>
 * Kedua getter ini TIDAK sekadar mengembalikan nilai field, melainkan MENGHITUNG ULANG lalu
 * MENIMPA field {@code this} sebelum mengembalikannya:
 * </p>
 * <ul>
 * <li>{@link #getDeep()} mengabaikan nilai {@code deep} yang tersimpan dan menelusuri ulang rantai
 * {@link #getParent()} dari awal setiap kali dipanggil, menghitung jumlah leluhur, lalu menimpa
 * field {@code deep} dengan hasil hitungan sebelum mengembalikannya. Pola ini identik dengan efek
 * samping yang sudah dikonfirmasi pada {@code rab.ChecklistLaporanDetail#getDeep()}: bila dipanggil
 * di dalam sesi Hibernate yang sedang mengelola entity ini, penulisan field yang "sekadar dibaca"
 * ini dapat ikut ter-flush sebagai {@code UPDATE} oleh dirty-checking Hibernate pada baris yang
 * kolom {@code deep}-nya berbeda dari hasil hitungan terbaru.</li>
 * <li>{@link #getJenis()} menimpa field {@code jenis} dengan {@code parent.jenis} (akses field
 * mentah induk, BUKAN lewat {@code parent.getJenis()}) setiap kali dipanggil dan {@link #parent}
 * tidak {@code null}. Karena aksesnya hanya SATU tingkat (tidak rekursif ke leluhur yang lebih
 * tinggi), sebuah cucu yang induknya sendiri belum eksplisit mengisi {@code jenis} tidak otomatis
 * mewarisi jenis dari kakek — konsistensi jenis di seluruh cabang pohon bergantung pada disiplin
 * pengisian data di setiap tingkat, bukan dijamin model.</li>
 * </ul>
 *
 * <h2>Cakupan tenant</h2>
 * <p>
 * Kelas ini adalah katalog GLOBAL tanpa sumbu tenant/satuan-kerja — parameter pemeriksaan berlaku
 * untuk seluruh instalasi/poli yang memakai modul {@code sirs}. Data pasien yang sensitif (nilai
 * hasil pemeriksaan aktual) tersimpan di {@link DiagnosaPenyakitPunyaPemeriksaan} yang merujuk ke
 * sini, bukan pada kelas ini sendiri.
 * </p>
 *
 * <h2>Pola arsitektur khas AIS yang muncul di kelas ini</h2>
 * <ul>
 * <li><b>Field audit bayangan</b> ({@code oleh}, {@code olehId}, {@code tanggal_dirubah},
 * {@link #onUpdate()}) diduplikasi karena induk {@link GeneralValueObject} BUKAN {@code @Entity}.
 * KEHARUSAN TEKNIS, bukan salin-tempel ceroboh.</li>
 * <li><b>{@link #getJmlDipakai()}</b> mengikuti pola penghitung popularitas pilihan yang identik
 * dengan {@link Icd#getJmlDipakai()}: dinaikkan oleh {@code AmbilDataPemeriksaanBanbox} setiap kali
 * butir ini dipilih lewat dialog pencari, bukan penghitung referensi riil.</li>
 * <li><b>Relasi self-referencing tanpa penjaga siklus</b> pada {@link #getParent()}: tidak ada
 * validasi yang mencegah sebuah butir menjadi induk dirinya sendiri atau membentuk rantai
 * melingkar; {@link #getDeep()} yang rekursif akan berputar tanpa henti bila siklus semacam itu
 * terbentuk.</li>
 * </ul>
 *
 * @see DiagnosaPenyakitPunyaPemeriksaan pemegang nilai hasil pemeriksaan aktual per diagnosa pasien
 * @see ais.action.master.sirs.detail.PemeriksaanHelper penyusun formulir dinamis dan penegak {@link #getHarusDiisi()}
 * @see ais.action.master.sirs.PemeriksaanAction layar CRUD datar katalog butir pemeriksaan
 * @see ais.action.master.sirs.PemeriksaanTreeAction layar CRUD berbentuk pohon katalog butir pemeriksaan
 * @see ais.action.master.sirs.helper.AmbilDataPemeriksaanBanbox dialog pemilih yang menaikkan {@link #getJmlDipakai()}
 */
@Entity
@org.hibernate.annotations.Entity(
    dynamicInsert = true,
    dynamicUpdate = true
)
@Audited
@Table(schema = "sirs", name = "pemeriksaan")
public class Pemeriksaan extends GeneralValueObject {

	/** Konstanta jenis butir: keluhan pasien saat masuk. Lihat {@link #getJenis()}. */
	public static final String JENIS_KELUHAN = "Keluhan";
	/** Konstanta jenis butir: riwayat kesehatan pasien. Lihat {@link #getJenis()}. */
	public static final String JENIS_RIWAYAT = "Riwayat Kesehatan";
	/** Konstanta jenis butir: hasil pemeriksaan fisik/vital sign. Lihat {@link #getJenis()}. */
	public static final String JENIS_PERIKSA = "Pemeriksaan";

	/**
	 * Nomor versi serialisasi Java. Nilai {@code 2463822577548439808L} berbeda satu digit dari
	 * banyak entity {@code sirs} lain (yang umumnya {@code 2463821577548439808L}) — kemungkinan
	 * salah ketik saat template hbm2java disalin untuk kelas ini, namun tidak berdampak fungsional
	 * karena {@code serialVersionUID} hanya dibandingkan antar versi dari kelas yang SAMA.
	 */
	private static final long serialVersionUID = 2463822577548439808L;

	/** Kunci primer numerik, {@code IDENTITY} (auto-increment basis data). Lihat {@link #getId()}. */
	private Long id;
	private String olehId;

	/**
	 * Mengembalikan identitas (username/ID) pengguna terakhir yang menyunting baris ini.
	 *
	 * @return identitas penyunting terakhir, atau {@code null} bila belum pernah diisi
	 */
	public String getOlehId() {
		return olehId;
	}

	/**
	 * Menetapkan identitas pengguna penyunting terakhir, dengan penjagaan anti-penghapusan:
	 * argumen {@code null} atau string kosong/berisi spasi saja diabaikan diam-diam sehingga nilai
	 * lama dipertahankan. Pola seragam di seluruh entity AIS agar jejak audit tidak hilang hanya
	 * karena sebuah proses batch atau importer menyerahkan objek tanpa konteks pengguna.
	 *
	 * @param olehId identitas penyunting; diabaikan bila {@code null} atau hanya berisi spasi
	 */
	public void setOlehId(String olehId) {if (olehId == null || olehId.trim().isEmpty()) {return;}
		this.olehId = olehId;
	}

	/**
	 * Nama tampil pengguna yang terakhir mengubah baris ini (field audit bayangan). Diisi oleh
	 * {@code AuditTimestampInterceptor} melalui {@link #setOleh(String)}.
	 */
	private String oleh;

	/**
	 * Mengembalikan label ringkas butir pemeriksaan, yakni {@link #getNama() nama} apa adanya.
	 *
	 * @return nama butir pemeriksaan, dapat {@code null} bila belum diisi
	 */
	public String toString() {
		return nama;
	}

	/**
	 * Menetapkan nama tampil pengguna penyunting terakhir, dengan penjagaan anti-penghapusan yang
	 * sama seperti {@link #setOlehId(String)}.
	 *
	 * @param oleh nama penyunting; diabaikan bila {@code null} atau hanya berisi spasi
	 */
	public void setOleh(String oleh) {if (oleh == null || oleh.trim().isEmpty()) {return;}
		this.oleh = oleh;
	}

	/**
	 * Mengembalikan nama tampil pengguna terakhir yang menyunting baris ini.
	 *
	 * @return nama penyunting terakhir, atau {@code null} bila belum pernah diisi
	 */
	public String getOleh() {
		return oleh;
	}

	/**
	 * Kait daur hidup JPA {@code @PreUpdate} yang mendelegasikan pengisian jejak audit ke
	 * {@code ais.database.hibernate.AuditTimestampInterceptor.ubah(this)} tepat sebelum Hibernate
	 * menerbitkan pernyataan {@code UPDATE}. Interceptor membaca konteks pengguna aktif dari sesi
	 * ZK/HTTP lalu mengisi {@link #setOleh(String)}, {@link #setOlehId(String)}, dan
	 * {@link #setTanggal_dirubah(Date)}. Mekanisme ini TERPISAH dari Hibernate Envers
	 * ({@link Audited}): Envers menulis salinan penuh setiap revisi ke
	 * {@code new_audit.pemeriksaan__audit}, sedangkan trio {@code oleh}/{@code olehId}/
	 * {@code tanggal_dirubah} hanya menyimpan potret "siapa terakhir" pada baris hidup. Perhatikan
	 * bahwa kait ini juga akan terpicu bila efek samping {@link #getDeep()} (lihat javadoc kelas)
	 * membuat Hibernate menganggap baris ini kotor pada sesi yang sama.
	 */
	@javax.persistence.PreUpdate protected void onUpdate() { ais.database.hibernate.AuditTimestampInterceptor.ubah(this);}     private Date tanggal_dirubah = new Date();

	/**
	 * Menetapkan cap waktu perubahan terakhir. Berbeda dari {@link #setOleh(String)}, setter ini
	 * TIDAK menjaga nilai kosong — {@code null} akan benar-benar tersimpan.
	 *
	 * @param tanggal_dirubah cap waktu perubahan terakhir
	 */
	public void setTanggal_dirubah(Date tanggal_dirubah) {
		this.tanggal_dirubah = tanggal_dirubah;
	}

	/**
	 * Mengembalikan cap waktu perubahan terakhir, dipetakan sebagai {@code TIMESTAMP}.
	 *
	 * @return cap waktu perubahan terakhir; tidak pernah {@code null} untuk objek yang baru
	 *         diinstansiasi lewat konstruktor kelas ini
	 */
	@Temporal(TemporalType.TIMESTAMP)
	public Date getTanggal_dirubah() {
		return tanggal_dirubah;
	}

	/** Nama butir pemeriksaan, dipakai {@link #toString()}. Lihat {@link #getNama()}. */
	private String nama;
	/** Jenis butir: salah satu {@link #JENIS_KELUHAN}/{@link #JENIS_RIWAYAT}/{@link #JENIS_PERIKSA}. Lihat {@link #getJenis()}. */
	private String jenis;
	/** Butir induk pada hierarki pohon katalog ini, boleh {@code null} untuk simpul akar. Lihat {@link #getParent()}. */
	private Pemeriksaan parent;
	/** Penanda "butir ini wajib diisi", DITEGAKKAN oleh {@code PemeriksaanHelper.check()}. Lihat {@link #getHarusDiisi()}. */
	private Boolean harusDiisi;
	/** Penanda butir aktif/nonaktif pada katalog. Lihat {@link #getAktif()}. */
	private Boolean aktif;
	/** Keterangan bebas mengenai butir ini. Lihat {@link #getKeterangan()}. */
	private String keterangan;
	/** Mini-DSL berdelimiter {@code ;}/{@code |} penentu jenis widget isian. Lihat {@link #getNilaiYangMungkin()}. */
	private String nilaiYangMungkin;
	/** Nilai default yang dipratayang saat formulir dibuka. Lihat {@link #getNilaiDefault()}. */
	private String nilaiDefault;
	private String normal;
	private String satuan;
	/** Kedalaman pada pohon; SELALU dihitung ulang dan ditimpa saat {@link #getDeep()} dipanggil. */
	private Integer deep;
	/** Jumlah baris kolom teks bebas saat {@link #getNilaiYangMungkin()} kosong. Lihat {@link #getJumlahBaris()}. */
	private Integer jumlahBaris;
	/** Penghitung popularitas pilihan lewat dialog pencari, bukan penghitung referensi riil. Lihat {@link #getJmlDipakai()}. */
	private Long jmlDipakai = 0L;

	/**
	 * Konstruktor tanpa argumen yang WAJIB ada agar Hibernate/JPA dapat meng-instansiasi entity
	 * lewat refleksi saat memuat baris dari basis data, dan agar komponen ZK dapat membuat objek
	 * kosong untuk form tambah-baru.
	 */
	public Pemeriksaan() {
	}

	/**
	 * Konstruktor pintasan yang hanya mengisi kunci primer, dipakai untuk membuat objek penampung
	 * ringan saat hanya id butir yang diketahui (mis. sebagai kunci pencarian), tanpa memuat
	 * seluruh field lain dari basis data.
	 *
	 * @param id kunci primer butir pemeriksaan yang dirujuk
	 */
	public Pemeriksaan(Long id) {
		this.id = id;
	}

	/**
	 * Mengembalikan kunci primer butir pemeriksaan.
	 *
	 * <p>
	 * Dipetakan {@code IDENTITY} (auto-increment basis data), sehingga nilainya baru terisi SETELAH
	 * baris tertulis. Nilai {@code null} adalah penanda baku bahwa objek belum tersimpan.
	 * </p>
	 *
	 * @return kunci primer, atau {@code null} bila entity belum pernah disimpan
	 */
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", insertable = false, unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	/**
	 * Menetapkan kunci primer. Umumnya hanya dipanggil Hibernate.
	 *
	 * @param id kunci primer
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * Mengembalikan nama butir pemeriksaan.
	 *
	 * <p>
	 * Kolom dipetakan {@code nullable = false} sepanjang 255 karakter, namun penjagaan itu ada di
	 * lapisan basis data — method ini tetap dapat mengembalikan {@code null} untuk objek yang belum
	 * disimpan. Nilai ini pula yang dikembalikan {@link #toString()} untuk label yang tampil pada
	 * pohon katalog dan formulir dinamis diagnosa.
	 * </p>
	 *
	 * @return nama butir pemeriksaan, atau {@code null} bila belum diisi
	 */
	@Column(name = "nama", nullable = false, length = 255)
	public String getNama() {
		return this.nama;
	}

	/**
	 * Menetapkan nama butir pemeriksaan.
	 *
	 * @param nama nama butir
	 */
	public void setNama(String nama) {
		this.nama = nama;
	}

	/**
	 * Mengembalikan keterangan bebas butir pemeriksaan.
	 *
	 * @return keterangan, atau {@code null} bila tidak diisi
	 */
	@Column(name = "keterangan", nullable = true)
	public String getKeterangan() {
		return this.keterangan;
	}

	/**
	 * Menetapkan keterangan bebas butir pemeriksaan.
	 *
	 * @param keterangan teks keterangan
	 */
	public void setKeterangan(String keterangan) {
		this.keterangan = keterangan;
	}

	/**
	 * Mengembalikan status aktif/nonaktif butir pemeriksaan pada katalog, dengan nilai baku
	 * {@code true} bila belum pernah diisi (baris lama yang dibuat sebelum kolom ini ada, atau
	 * objek baru yang belum diset eksplisit, dianggap aktif secara default).
	 *
	 * @return {@code true} bila aktif, {@code false} bila dinonaktifkan; tidak pernah {@code null}
	 */
	public Boolean getAktif() {
		if (aktif == null) {
			aktif = true;
		}
		return aktif;
	}

	/**
	 * Menetapkan status aktif/nonaktif butir pemeriksaan.
	 *
	 * @param aktif status aktif baru
	 */
	public void setAktif(Boolean aktif) {
		this.aktif = aktif;
	}

	/**
	 * Mengembalikan mini-DSL berdelimiter yang menentukan jenis widget isian untuk butir ini pada
	 * formulir diagnosa, dengan nilai baku string kosong (bukan {@code null}) bila belum diisi.
	 *
	 * <p>
	 * {@code PemeriksaanHelper} memecah string ini dengan {@code ";"} atau {@code "|"} menjadi
	 * daftar pilihan yang dirender sebagai checkbox pilihan jamak; string kosong berarti butir
	 * dirender sebagai kombinasi kombo Ya/Tidak dan kolom teks bebas (lihat {@link #getJumlahBaris()}
	 * untuk jumlah barisnya). Tidak ada validasi format pada model ini — operator yang mengisi
	 * katalog bertanggung jawab menjaga konsistensi delimiter.
	 * </p>
	 *
	 * @return nilai mini-DSL pilihan, tidak pernah {@code null} (string kosong bila belum diisi)
	 */
	@Column(name = "nilai_yang_mungkin", nullable = true, length = 1000)
	public String getNilaiYangMungkin() {
		if (nilaiYangMungkin == null) {
			nilaiYangMungkin = "";
		}
		return nilaiYangMungkin;
	}

	/**
	 * Menetapkan mini-DSL berdelimiter penentu jenis widget isian. Lihat catatan format pada
	 * {@link #getNilaiYangMungkin()}.
	 *
	 * @param nilaiYangMungkin nilai mini-DSL pilihan baru
	 */
	public void setNilaiYangMungkin(String nilaiYangMungkin) {
		this.nilaiYangMungkin = nilaiYangMungkin;
	}

	/**
	 * Mengembalikan butir induk pada hierarki pohon katalog pemeriksaan ini.
	 *
	 * <p>
	 * Relasi ini melewati resolusi cache {@code check(...)} milik {@link GeneralValueObject} agar
	 * proxy/objek stale dari sesi lain diselaraskan sebelum dipakai. TIDAK ADA penjaga siklus:
	 * tidak ada validasi yang mencegah sebuah butir menjadi induk dirinya sendiri atau membentuk
	 * rantai melingkar; {@link #getDeep()} yang menelusuri rantai ini secara rekursif akan berputar
	 * tanpa henti bila siklus semacam itu terbentuk.
	 * </p>
	 *
	 * @return butir induk, atau {@code null} bila butir ini simpul akar
	 */
	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY)
	@JoinColumn(name = "parent", nullable = true)
	public Pemeriksaan getParent() {
		parent = check(parent);
		return parent;
	}

	/**
	 * Menetapkan butir induk pada hierarki pohon. Setter ini menyimpan argumen apa adanya; pemanggil
	 * bertanggung jawab mencegah siklus (lihat catatan pada {@link #getParent()}).
	 *
	 * @param parent butir induk, boleh {@code null} untuk menjadikan butir ini simpul akar
	 */
	public void setParent(Pemeriksaan parent) {
		this.parent = parent;
	}

	/**
	 * Mengembalikan kedalaman butir ini pada pohon katalog (0 untuk simpul akar, menaik satu untuk
	 * setiap tingkat anak).
	 *
	 * <p>
	 * <b>Getter ini MENGABAIKAN nilai {@code deep} tersimpan dan MENGHITUNG ULANG setiap kali
	 * dipanggil</b>, dengan menelusuri rantai {@link #getParent()} dari awal, lalu MENIMPA field
	 * {@code deep} dengan hasil hitungan sebelum mengembalikannya. Lihat catatan lengkap pada
	 * javadoc kelas mengenai kemiripan pola ini dengan
	 * {@code rab.ChecklistLaporanDetail#getDeep()}: bila dipanggil di dalam sesi Hibernate yang
	 * sedang mengelola entity ini, penulisan field yang tampak seperti "sekadar membaca" ini dapat
	 * ikut ter-flush sebagai {@code UPDATE} oleh dirty-checking Hibernate.
	 * </p>
	 *
	 * @return kedalaman pada pohon, dihitung ulang secara live pada setiap pemanggilan; tidak
	 *         pernah {@code null}
	 */
	public Integer getDeep() {
		deep = 0;
		Pemeriksaan temPemeriksaan = getParent();
		while (temPemeriksaan != null) {
			deep++;
			temPemeriksaan = temPemeriksaan.getParent();
		}
		return deep;
	}

	/**
	 * Menetapkan kedalaman butir pada pohon katalog. Perhatikan bahwa nilai yang diset di sini akan
	 * DITIMPA oleh pemanggilan {@link #getDeep()} berikutnya, sehingga setter ini pada praktiknya
	 * tidak memiliki efek baca yang bertahan.
	 *
	 * @param deep kedalaman pada pohon
	 */
	public void setDeep(Integer deep) {
		this.deep = deep;
	}

	/**
	 * Mengembalikan jumlah berapa kali butir ini DIPILIH lewat dialog pencari
	 * {@code AmbilDataPemeriksaanBanbox}.
	 *
	 * <p>
	 * Mengikuti pola yang identik dengan {@link Icd#getJmlDipakai()}: nilainya dinaikkan satu setiap
	 * kali pengguna memilih butir ini lewat dialog tersebut, BUKAN penghitung referensi riil
	 * berapa banyak baris {@link DiagnosaPenyakitPunyaPemeriksaan} yang benar-benar memakainya saat
	 * ini. Dipakai murni untuk mengurutkan/menonjolkan butir yang sering dipakai pada daftar
	 * pencarian.
	 * </p>
	 *
	 * @return jumlah pemilihan lewat dialog pencari; {@code 0} secara baku untuk objek baru
	 */
	public Long getJmlDipakai() {
		return jmlDipakai;
	}

	/**
	 * Menetapkan jumlah pemilihan lewat dialog pencari. Lihat catatan pada {@link #getJmlDipakai()}.
	 *
	 * @param jmlDipakai jumlah pemilihan baru
	 */
	public void setJmlDipakai(Long jmlDipakai) {
		this.jmlDipakai = jmlDipakai;
	}

	/**
	 * Mengembalikan rentang nilai normal/rujukan untuk butir pemeriksaan ini (mis. rentang tekanan
	 * darah normal), sebagai teks bebas tanpa format baku.
	 *
	 * @return teks rentang normal, atau {@code null} bila tidak diisi
	 */
	public String getNormal() {
		return normal;
	}

	/**
	 * Menetapkan rentang nilai normal/rujukan untuk butir pemeriksaan ini.
	 *
	 * @param normal teks rentang normal baru
	 */
	public void setNormal(String normal) {
		this.normal = normal;
	}

	/**
	 * Mengembalikan satuan ukur nilai butir pemeriksaan ini (mis. "mmHg", "°C"), sebagai teks bebas.
	 *
	 * @return satuan ukur, atau {@code null} bila tidak diisi
	 */
	public String getSatuan() {
		return satuan;
	}

	/**
	 * Menetapkan satuan ukur nilai butir pemeriksaan ini.
	 *
	 * @param satuan satuan ukur baru
	 */
	public void setSatuan(String satuan) {
		this.satuan = satuan;
	}

	/**
	 * Mengembalikan jenis butir ini: salah satu {@link #JENIS_KELUHAN}, {@link #JENIS_RIWAYAT},
	 * atau {@link #JENIS_PERIKSA}, dipakai {@code PemeriksaanHelper} untuk mengelompokkan butir ke
	 * salah satu dari tiga panel formulir diagnosa (Keluhan/Riwayat Kesehatan/Pemeriksaan).
	 *
	 * <p>
	 * <b>Getter ini MENIMPA field {@code jenis} dengan {@code parent.jenis}</b> (akses field mentah
	 * induk, BUKAN lewat {@code parent.getJenis()}) setiap kali dipanggil dan {@link #getParent()}
	 * tidak {@code null} — lihat catatan lengkap pada javadoc kelas. Karena hanya SATU tingkat
	 * (tidak rekursif ke leluhur lebih tinggi), butir cucu yang induk langsungnya belum eksplisit
	 * mengisi {@code jenis} tidak otomatis mewarisi jenis dari kakeknya.
	 * </p>
	 *
	 * @return jenis butir pemeriksaan; mengikuti nilai induk langsung bila induk ada, atau nilai
	 *         field ini sendiri bila butir ini simpul akar
	 */
	public String getJenis() {
		if (parent != null) {
			jenis = parent.jenis;
		}
		return jenis;
	}

	/**
	 * Menetapkan jenis butir ini. Perhatikan bahwa nilai ini akan DITIMPA oleh pemanggilan
	 * {@link #getJenis()} berikutnya bila {@link #getParent()} tidak {@code null} — lihat catatan
	 * pada {@link #getJenis()}.
	 *
	 * @param jenis jenis butir baru; sebaiknya salah satu {@link #JENIS_KELUHAN}/
	 *              {@link #JENIS_RIWAYAT}/{@link #JENIS_PERIKSA} walau tidak ditegakkan model
	 */
	public void setJenis(String jenis) {
		this.jenis = jenis;
	}

	/**
	 * Mengembalikan nilai default yang dipratayang saat formulir diagnosa dibuka untuk butir ini.
	 *
	 * @return nilai default, atau {@code null} bila tidak diisi
	 */
	public String getNilaiDefault() {
		return nilaiDefault;
	}

	/**
	 * Menetapkan nilai default butir pemeriksaan.
	 *
	 * @param nilaiDefault nilai default baru
	 */
	public void setNilaiDefault(String nilaiDefault) {
		this.nilaiDefault = nilaiDefault;
	}

	/**
	 * Mengembalikan penanda "butir ini wajib diisi", dengan nilai baku {@code false} bila belum
	 * pernah diisi.
	 *
	 * <p>
	 * <b>DITEGAKKAN, bukan kosmetik</b> — lihat catatan pada javadoc kelas.
	 * {@code PemeriksaanHelper.check()} menolak penyimpanan diagnosa dengan pesan peringatan bila
	 * butir dengan {@code harusDiisi = true} dibiarkan kosong (kombo Ya/Tidak tidak dipilih, kolom
	 * keterangan kosong, dan tidak ada checkbox pilihan ganda yang tercentang).
	 * </p>
	 *
	 * @return {@code true} bila wajib diisi, {@code false} bila opsional; tidak pernah {@code null}
	 */
	public Boolean getHarusDiisi() {
		if (harusDiisi == null) {
			harusDiisi = false;
		}
		return harusDiisi;
	}

	/**
	 * Menetapkan penanda "butir ini wajib diisi". Lihat catatan penegakan pada
	 * {@link #getHarusDiisi()}.
	 *
	 * @param harusDiisi status wajib-isi baru
	 */
	public void setHarusDiisi(Boolean harusDiisi) {
		this.harusDiisi = harusDiisi;
	}

	/**
	 * Mengembalikan jumlah baris kolom teks bebas yang dirender saat {@link #getNilaiYangMungkin()}
	 * kosong (butir direpresentasikan kombo Ya/Tidak plus kolom keterangan multi-baris), dengan
	 * nilai baku {@code 1} bila belum pernah diisi.
	 *
	 * @return jumlah baris kolom teks bebas; tidak pernah {@code null}
	 */
	public Integer getJumlahBaris() {
		if (jumlahBaris == null) {
			jumlahBaris = 1;
		}
		return jumlahBaris;
	}

	/**
	 * Menetapkan jumlah baris kolom teks bebas untuk butir ini.
	 *
	 * @param jumlahBaris jumlah baris baru
	 */
	public void setJumlahBaris(Integer jumlahBaris) {
		this.jumlahBaris = jumlahBaris;
	}

}
