<%-- @generated by generate_new_jsp_scaffold.py
Source: src/ais/action/report/format1/sirs/ranap/LaporanDataPasienRawatInap.java
Generated: 2026-08-06T18:20:20Z
Safe service-adapter scaffold. Implement data access in a Java service layer, not directly in this JSP.
--%>
<%@ page language="java" contentType="application/json; charset=UTF-8" pageEncoding="UTF-8" %>
<%
request.setAttribute("nuiServiceModule", "root/report");
request.setAttribute("nuiServicePage", "format1/sirs/ranap/laporan_data_pasien_rawat_inap");
request.setAttribute("nuiServiceTitle", "Laporan Data Pasien Rawat Inap");
request.setAttribute("nuiServiceType", "report");
request.setAttribute("nuiServiceSourceClass", "LaporanDataPasienRawatInap");
request.setAttribute("nuiServiceSourcePackage", "ais.action.report.format1.sirs.ranap");
request.setAttribute("nuiServiceSourcePath", "src/ais/action/report/format1/sirs/ranap/LaporanDataPasienRawatInap.java");
request.setAttribute("nuiServiceMethods", new String[]{"onEvent", "generateParameters", "onCetak"});
request.setAttribute("nuiServiceEntities", new String[]{});
%>
<jsp:include page="/WEB-INF/new/_shared/services/dispatcher.jsp" />
