package ais.database.model.bri;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Calendar;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;




import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;
import org.hibernate.envers.Audited;



import ais.common.Common;
import ais.database.model.BiodataCalonMahasiswa;
import ais.database.model.GeneralValueObject;
import ais.database.model.JadwalPembayaran;
import ais.database.model.JenisKegiatan;
import ais.database.model.KegiatanTemporary;
import ais.database.model.Mahasiswa;
import ais.database.model.sekolah.CalonSiswa;
import ais.database.model.sekolah.Siswa;

/**
 * Bank generated by hbm2java
 * <p>
 * Entitas <b>header transaksi</b> integrasi <i>host-to-host</i> (H2H) BRIVA
 * (BRI Virtual Account): satu baris tabel {@code public.bri_request} mewakili
 * SATU permintaan penerbitan BRIVA yang dikirim AIS ke gateway BRI, berikut
 * jawaban bank atas permintaan itu.
 *
 * <h3>Pola umum</h3>
 *
 * Kelas ini mengikuti pola empat kelas yang dipakai seluruh paket integrasi
 * bank AIS — header, rincian baris tagihan, komponen biaya, dan balasan bank.
 * <b>Penjelasan lengkap pola tersebut ada pada
 * {@link ais.database.model.bni.BniRequest}</b> dan tidak diulang di sini.
 * Untuk paket BRI keempat kelasnya adalah kelas ini,
 * {@link BriRequestDetail}, {@link BriRequestDetailBiaya}, dan
 * {@link BriResponse}.
 *
 * <h3>Perbedaan NYATA terhadap paket BNI (jangan disamakan)</h3>
 *
 * Meski polanya sama, isi dan perilaku paket ini BERBEDA. Perbedaan yang sudah
 * diverifikasi terhadap {@link ais.database.model.bni.BniRequest}:
 *
 * <ul>
 * <li><b>Bentuk Virtual Account.</b> BRI memakai skema BRIVA: nomor VA adalah
 * {@code custCode} yang berada di bawah {@code institutionCode}
 * (konfigurasi {@code bri_institution_code}) dan {@code brivaNo}
 * (konfigurasi {@code bri_briva_no}) milik institusi — bukan nomor berprefiks
 * seperti pada BNI.</li>
 *
 * <li><b>Autentikasi API.</b> BRI memakai OAuth2 <i>bearer token</i>:
 * {@code ais.common.BriCommon#requestToken()} menukar
 * {@code bri_merchant_id} (client id), {@code bri_password} (client secret),
 * dan {@code bri_auth_code} di {@code bri_gateway_url_token} menjadi
 * {@code access_token}, yang disimpan ke konfigurasi
 * {@code bri_auth_code_barier} dan dikirim bersama {@code bri_api_key} pada
 * setiap panggilan ke {@code bri_gateway_url}. Bandingkan dengan BNI yang
 * memakai enkripsi payload {@code BNIHash} tanpa token.</li>
 *
 * <li><b>Payload permintaan TIDAK ter-enkripsi.</b> Karena BRI mengandalkan
 * token pada <i>header</i>, badan permintaan yang tersimpan di
 * {@link #getRequest()} berupa JSON POLOS berisi {@code institutionCode},
 * {@code brivaNo}, {@code custCode}, nama pembayar, nominal, dan tanggal
 * kedaluwarsa. Ini berbeda dari BNI yang menyimpan blok {@code data}
 * ter-enkripsi. Lihat bagian catatan keamanan di bawah.</li>
 *
 * <li><b>Tidak ada jalur kursus.</b> Berbeda dari BNI, entitas ini tidak
 * memiliki FK {@code pesertaKursus}; pembayar hanya dapat berupa
 * {@link Mahasiswa}, {@link BiodataCalonMahasiswa}, {@link Siswa}, atau
 * {@link CalonSiswa}.</li>
 *
 * <li><b>Tidak ada kolom {@code cicilan}.</b> Entitas ini tidak menyimpan
 * rincian skema cicilan berbentuk teks seperti BNI.</li>
 *
 * <li><b>Kedaluwarsa jauh lebih pendek.</b> {@link #getBill_expired()}
 * memberi default <b>satu HARI</b>, sedangkan padanannya di BNI memberi
 * default satu BULAN. Nama propertinya pun berbeda ({@code bill_expired}
 * bergaya <i>snake case</i>, bukan {@code billExpired}).</li>
 *
 * <li><b>Semester tidak dipaksa nol.</b> {@link #getSemester()} mengembalikan
 * nilai apa adanya; tidak ada cabang yang memaksa {@code 0} untuk kegiatan
 * pendaftaran calon mahasiswa seperti pada BNI.</li>
 *
 * <li><b>Setter boolean bersifat dua arah.</b>
 * {@link #setHapusCicilanSebelumnya(Boolean)} dan
 * {@link #setCheckUlang(Boolean)} menerima nilai apa pun termasuk
 * {@code false} dan {@code null} — berbeda dari padanannya di BNI yang
 * mengabaikan {@code false} secara diam-diam.</li>
 *
 * <li><b>Normalisasi proxy tidak konsisten.</b> Hanya
 * {@link #getCalonSiswa()} yang melewatkan nilainya ke {@code check(...)};
 * {@link #getMahasiswa()}, {@link #getBiodataCalonMahasiswa()}, dan
 * {@link #getSiswa()} mengembalikan field apa adanya. Ketiga getter itu juga
 * memakai <i>fetch</i> bawaan (eager) dengan {@code FetchMode.SELECT}, bukan
 * {@code FetchType.LAZY} seperti di BNI.</li>
 * </ul>
 *
 * <h3>Alur hidup dan titik integrasi</h3>
 *
 * <ol>
 * <li>Tombol "BAYAR VIA BRI" muncul bila konfigurasi
 * {@code aktifkan_pembayaran_via_bri} aktif (untuk modul mahasiswa juga
 * {@code aktifkan_pembayaran_via_bri_pt_<idPerguruanTinggi>}); katalog gateway
 * ada di {@code ais.action.master.helper.PembayaranGatewayKatalog}.</li>
 *
 * <li>{@code ais.common.BriCommon} menyusun payload BRIVA, mengambil/memakai
 * ulang bearer token, mem-POST ke {@code bri_gateway_url}, lalu menyimpan
 * {@code custCode} sebagai {@link #getVa() va}, {@link #getTrxId() trxId},
 * {@link #getNama() nama}, dan {@link #getData() data} sekaligus — keempat
 * properti tersebut pada praktiknya berisi nilai yang SAMA.</li>
 *
 * <li><b>Tidak ada endpoint callback.</b> Kelas
 * {@code ais.action.servlet.Briresponse} memang merupakan turunan
 * {@code HttpServlet}, tetapi TIDAK terdaftar di {@code WEB-INF/web.xml}
 * (tidak ada {@code <servlet>} maupun {@code <servlet-mapping>}) dan tidak
 * memakai anotasi {@code @WebServlet}, sehingga {@code doGet}/{@code doPost}
 * -nya tidak dapat dijangkau lewat HTTP. Kelas itu efektif berfungsi sebagai
 * wadah metode statis ({@code prosesResponse}, {@code createKegiatan}) yang
 * dipanggil dari kode lain.</li>
 *
 * <li>Konsekuensinya, status pembayaran BRI HANYA diperbarui lewat
 * <i>polling</i>: {@code ais.action.master.bri.BriBackandProsess#checkSatu}
 * menanyakan status BRIVA ke bank lalu memanggil
 * {@code Briresponse#prosesResponse}. Rekonsiliasi manual tersedia lewat tab
 * BRI pada {@code ais.action.master.LogHostToHostAction} yang meng-include
 * {@code /pages/master/bri/bri_request.zul}
 * ({@code ais.action.master.bri.BriRequestAction}) dan lewat
 * {@code ais.action.master.psb.CariDataPembayaranAction}.</li>
 * </ol>
 *
 * <h3>Catatan keamanan</h3>
 *
 * <ul>
 * <li><b>Data finansial mentah tanpa masking.</b> Kolom {@code va},
 * {@code trx_id}, {@code bill_no}, {@code amount}, {@code merchant_id},
 * {@code request}, dan {@code response} menyimpan nilai apa adanya. Karena
 * payload BRI tidak ter-enkripsi, kolom {@code request} bertipe {@code text}
 * di sini memuat data transaksi yang LANGSUNG TERBACA — secara praktis lebih
 * terekspos daripada padanannya di BNI. Ini pola yang sama dengan temuan yang
 * sudah tercatat untuk Bank Mandiri dan OCBC NISP; BRI adalah bank tambahan
 * yang terkena pola tersebut.</li>
 *
 * <li><b>Efek {@code @Audited} (Hibernate Envers).</b> Setiap versi baris,
 * termasuk payload mentah, digandakan ke tabel revisi {@code bri_request_AUD};
 * menghapus baris {@code bri_request} tidak menghapus jejak di sana.</li>
 *
 * <li><b>Kredensial TIDAK disimpan di entitas ini.</b> Verifikasi terhadap
 * {@code ais.common.BriCommon}: {@code bri_password} (client secret),
 * {@code bri_api_key}, {@code bri_auth_code}, dan {@code access_token} hanya
 * hidup di tabel {@code Konfigurasi} dan pada <i>header</i> HTTP; tidak ada
 * yang ikut tersimpan ke kolom mana pun pada entitas ini. Yang tersimpan
 * hanyalah {@code merchant_id}/{@code institutionCode} yang merupakan
 * identitas institusi. Tidak ada kolom nomor kartu, PIN, maupun kunci tanda
 * tangan.</li>
 *
 * <li><b>Tidak ada kolom kepemilikan/tenant.</b> Sama seperti paket BNI,
 * entitas ini tidak memiliki FK ke {@code SatuanKerja}/{@code Sekolah}/
 * {@code PerguruanTinggi}; cakupan hanya tersirat lewat FK pembayar, dan
 * gerbang aksesnya adalah satu hak baca global pada
 * {@code LogHostToHostAction}.</li>
 * </ul>
 *
 * @see ais.database.model.bni.BniRequest
 * @see BriRequestDetail
 * @see BriRequestDetailBiaya
 * @see BriResponse
 * @see ais.common.BriCommon
 * @see ais.action.master.bri.BriBackandProsess
 * @see ais.action.master.bri.BriRequestAction
 */
@Entity
@org.hibernate.annotations.Entity(
    dynamicInsert = true,
    dynamicUpdate = true
)
@Audited
@Table(schema = "public", name = "bri_request")



public class BriRequest extends GeneralValueObject {
	/**
	 *
	 * Nomor versi serialisasi entitas; JANGAN diubah agar data lama tetap terbaca.
	 */
	private static final long serialVersionUID = 2463821327548439808L;
	/** Kunci utama (identity, dibangkitkan basis data). */
	private Long id;
	/** Nama pengguna terakhir yang mengubah baris ini (field audit bayangan). */
	private String oleh;
	/** Identitas (id) pengguna terakhir yang mengubah baris ini (field audit bayangan). */
	private String olehId;

	/**
	 * Mengembalikan identitas pengguna terakhir yang menyentuh baris ini.
	 *
	 * @return id pengguna audit, atau {@code null} bila belum pernah diisi.
	 */
	public String getOlehId() {
		return olehId;
	}

	/**
	 * Menetapkan identitas pengguna audit.
	 * <p>
	 * <b>Setter satu arah:</b> nilai {@code null} atau string kosong DIABAIKAN
	 * secara diam-diam.
	 *
	 * @param olehId id pengguna; diabaikan bila kosong.
	 */
	public void setOlehId(String olehId) {if (olehId == null || olehId.trim().isEmpty()) {return;}
		this.olehId = olehId;
	}

	/**
	 * Menetapkan nama pengguna audit.
	 * <p>
	 * <b>Setter satu arah:</b> nilai {@code null} atau string kosong DIABAIKAN
	 * secara diam-diam.
	 *
	 * @param oleh nama pengguna; diabaikan bila kosong.
	 */
	public void setOleh(String oleh) {if (oleh == null || oleh.trim().isEmpty()) {return;}
		this.oleh = oleh;
	}

	/**
	 * Mengembalikan nama pengguna terakhir yang menyentuh baris ini.
	 *
	 * @return nama pengguna audit, atau {@code null} bila belum pernah diisi.
	 */
	public String getOleh() {
		return oleh;
	}

	/**
	 * Kait daur hidup JPA yang dipanggil tepat sebelum {@code UPDATE};
	 * mendelegasikan pengisian jejak audit ke
	 * {@code ais.database.hibernate.AuditTimestampInterceptor#ubah(Object)}.
	 * Keharusan teknis mekanisme audit AIS, bukan logika bisnis.
	 */
	@javax.persistence.PreUpdate protected void onUpdate() { ais.database.hibernate.AuditTimestampInterceptor.ubah(this);}     /** Stempel waktu perubahan terakhir; diinisialisasi ke waktu server saat objek dibuat. */
	private Date tanggal_dirubah = ais.ui.util.WaktuUtil.getDate();

	/**
	 * Menetapkan stempel waktu perubahan terakhir.
	 *
	 * @param tanggal_dirubah waktu perubahan.
	 */
	public void setTanggal_dirubah(Date tanggal_dirubah) {
		this.tanggal_dirubah = tanggal_dirubah;
	}

	/**
	 * Mengembalikan stempel waktu perubahan terakhir apa adanya.
	 * <p>
	 * Berbeda dari {@code BniRequest#getTanggal_dirubah()}, getter ini TIDAK
	 * mengganti {@code null} dengan waktu server.
	 *
	 * @return stempel waktu perubahan, atau {@code null}.
	 */
	@Temporal(TemporalType.TIMESTAMP)
	public Date getTanggal_dirubah() {
		return tanggal_dirubah;
	}

	/**
	 * Representasi teks ringkas untuk kombo/daftar ZK dan berkas log.
	 *
	 * @return gabungan {@code id} dan {@code nama} ({@code custCode} BRIVA)
	 *         dipisah tanda hubung.
	 */
	public String toString() {
		return id + "-" + nama;
	}

	/** {@code custCode} BRIVA; dipetakan ke kolom {@code session_id} bertipe {@code text}. */
	private String nama;
	/** Flag "hapus cicilan sebelumnya"; di paket BRI dapat disetel dua arah. */
	private Boolean hapusCicilanSebelumnya;
	/** Penanda transaksi perlu diperiksa ulang; saat ini tidak dikonsumsi kode mana pun. */
	private Boolean checkUlang;
	/** Nomor transaksi BRI; diisi dengan {@code custCode} BRIVA. */
	private String trxId;
	/** Nomor BRIVA ({@code custCode}) yang diterbitkan untuk transaksi ini. */
	private String va;
	/** Nomor tagihan internal AIS. */
	private String billNo;
	/** Identitas merchant hasil salinan dari {@link BriResponse#getMerchant()}. */
	private String merchant;

	/** Payload permintaan mentah (JSON POLOS, tidak ter-enkripsi) yang di-POST ke BRI. */
	private String request;
	/** Kode institusi BRIVA, dari konfigurasi {@code bri_institution_code}. */
	private String merchant_id;
	/** {@code custCode} BRIVA hasil jawaban bank (duplikat pembantu dari {@link #va}). */
	private String data;

	/** Kode respons gateway BRI ({@code responseCode}) atas permintaan penerbitan BRIVA. */
	private String response_code;
	/** Keterangan respons gateway BRI ({@code responseDescription}). */
	private String response_desc;

	/** Pembayar berupa mahasiswa aktif; salah satu dari empat jalur pembayar. */
	private Mahasiswa mahasiswa;
	/** Pembayar berupa calon mahasiswa (PMB). */
	private BiodataCalonMahasiswa biodataCalonMahasiswa;
	/** Jenis kegiatan yang dibayar. */
	private JenisKegiatan jenisKegiatan;
	/** Jadwal pembayaran yang menaungi transaksi ini. */
	private JadwalPembayaran jadwalPembayaran;
	/** Semester yang dibayar; TIDAK dipaksa nol untuk kegiatan pendaftaran. */
	private Integer semester;
	/** Tahun akademik yang dibayar. */
	private String tahunAkademik;
	/** Keterangan bebas transaksi. */
	private String keterangan;
	/** Potongan/pengurangan nominal yang diterapkan sebelum tagihan dikirim. */
	private Double pengurangan;
	/** Nominal yang ditagihkan ke bank. */
	private Double amount;
	/** Nilai total biaya yang seharusnya dibayar menurut master biaya. */
	private Double nilaiBiayaHarusDiBayars;
	/** Balasan/notifikasi bank untuk transaksi ini. */
	private BriResponse briResponse;
	/** Status pembayaran versi AIS; default {@code "Belum diproses"}. */
	private String status;
	/** Kode status pembayaran versi bank. */
	private String kodeStatus;
	/** Payload jawaban mentah dari gateway BRI (kolom {@code text}). */
	private String response;
	/** Biaya administrasi bank; bila kosong diambil dari {@code bri_biaya_administrasi}. */
	private Double biayaAdministrasi;

	/** Keranjang kegiatan sementara yang dibayar sekaligus dalam satu BRIVA. */
	private Set<KegiatanTemporary> kegiatanTemporarys = new HashSet<KegiatanTemporary>();
	/** Biaya payment gateway; bila kosong diambil dari {@code bri_biaya_payment_gateway}. */
	private Double biayaPaymentGateway;
	/** Pembayar berupa siswa sekolah. */
	private Siswa siswa;
	/** Pembayar berupa calon siswa (PSB). */
	private CalonSiswa calonSiswa;
	/** Batas waktu tagihan BRIVA; default SATU HARI sejak dibaca pertama kali. */
	private Date bill_expired;

	/** Nominal deposit yang menyertai transaksi. */
	private Double deposit;

	/**
	 * Mengembalikan himpunan {@code KegiatanTemporary} (keranjang pembayaran)
	 * yang digabung ke dalam satu BRIVA.
	 * <p>
	 * Relasi {@code ManyToMany} lewat tabel penghubung
	 * {@code bri_request_has_kegiatan_temporary} — perhatikan namanya berbeda
	 * dari tabel penghubung paket bank lain.
	 *
	 * @return himpunan kegiatan sementara; tidak pernah {@code null}.
	 */
	@ManyToMany(targetEntity = KegiatanTemporary.class, cascade = { CascadeType.MERGE,
			CascadeType.PERSIST })
	@JoinTable(name = "bri_request_has_kegiatan_temporary", joinColumns = @JoinColumn(name = "bri_request"), inverseJoinColumns = @JoinColumn(name = "kegiatan_temporary"))
	public Set<KegiatanTemporary> getKegiatanTemporarys() {
		return kegiatanTemporarys;
	}

	/**
	 * Menetapkan keranjang kegiatan sementara yang dibayar dalam satu BRIVA.
	 *
	 * @param kegiatanTemporarys himpunan kegiatan sementara.
	 */
	public void setKegiatanTemporarys(Set<KegiatanTemporary> kegiatanTemporarys) {
		this.kegiatanTemporarys = kegiatanTemporarys;
	}

	/**
	 * Konstruktor tanpa argumen yang diwajibkan Hibernate/JPA.
	 * <p>
	 * Berbeda dari {@code BniRequest}, kelas ini TIDAK menyediakan konstruktor
	 * pintas berargumen.
	 */
	public BriRequest() {
	}

	/**
	 * Mengembalikan kunci utama baris ini.
	 *
	 * @return id baris, atau {@code null} bila belum di-persist.
	 */
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", insertable = false, unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	/**
	 * Menetapkan kunci utama baris ini.
	 *
	 * @param id kunci utama.
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * Mengembalikan {@code custCode} BRIVA yang tersimpan pada kolom
	 * {@code session_id}.
	 * <p>
	 * Meski nama properti Java-nya {@code nama} (konvensi
	 * {@link GeneralValueObject}), isinya bukan nama orang melainkan kode
	 * pelanggan BRIVA — pada praktiknya bernilai sama dengan
	 * {@link #getVa()}, {@link #getTrxId()}, dan {@link #getData()}. Nilai
	 * dipangkas spasi tepi sebelum dikembalikan.
	 *
	 * @return {@code custCode} yang sudah di-{@code trim}, atau {@code null}.
	 */
	@Column(name = "session_id", columnDefinition = "text")
	public String getNama() {
		return this.nama == null ? null : this.nama.trim();
	}

	/**
	 * Menetapkan {@code custCode} BRIVA.
	 *
	 * @param nama kode pelanggan BRIVA.
	 */
	public void setNama(String nama) {
		this.nama = nama;
	}

	/**
	 * Mengembalikan nomor transaksi BRI.
	 * <p>
	 * Diisi {@code ais.common.BriCommon} dengan {@code custCode} BRIVA, jadi
	 * bernilai sama dengan {@link #getVa()}. Getter mengembalikan string kosong
	 * (bukan {@code null}) bila belum terisi.
	 *
	 * @return nomor transaksi yang sudah di-{@code trim}, atau string kosong.
	 */
	public String getTrxId() {
		return trxId == null ? "" : trxId.trim();
	}

	/**
	 * Menetapkan nomor transaksi BRI.
	 *
	 * @param trxId nomor transaksi.
	 */
	public void setTrxId(String trxId) {
		this.trxId = trxId;
	}

	/**
	 * Mengembalikan mahasiswa pembayar transaksi ini.
	 * <p>
	 * <b>Bukan getter destruktif:</b> berbeda dari padanannya di paket BNI,
	 * nilai dikembalikan apa adanya tanpa dilewatkan {@code check(...)}, dan
	 * relasi memakai {@code FetchMode.SELECT} dengan <i>fetch</i> bawaan
	 * (eager) alih-alih {@code FetchType.LAZY}.
	 *
	 * @return mahasiswa pembayar, atau {@code null} bila pembayar bukan mahasiswa.
	 */
	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE })
	@Fetch(FetchMode.SELECT)
	@JoinColumn(name = "mahasiswa", nullable = true)
	public Mahasiswa getMahasiswa() {
		return mahasiswa;
	}

	/**
	 * Menetapkan mahasiswa pembayar transaksi ini.
	 *
	 * @param mahasiswa mahasiswa pembayar; boleh {@code null}.
	 */
	public void setMahasiswa(Mahasiswa mahasiswa) {
		this.mahasiswa = mahasiswa;
	}

	/**
	 * Mengembalikan calon mahasiswa (PMB) pembayar transaksi ini.
	 * <p>
	 * <b>Bukan getter destruktif</b>, sama seperti {@link #getMahasiswa()}.
	 *
	 * @return biodata calon mahasiswa, atau {@code null}.
	 */
	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE })
	@Fetch(FetchMode.SELECT)
	@JoinColumn(name = "biodata_calon_mahasiswa", nullable = true)
	public BiodataCalonMahasiswa getBiodataCalonMahasiswa() {
		return biodataCalonMahasiswa;
	}

	/**
	 * Menetapkan calon mahasiswa (PMB) pembayar transaksi ini.
	 *
	 * @param biodataCalonMahasiswa biodata calon mahasiswa; boleh {@code null}.
	 */
	public void setBiodataCalonMahasiswa(BiodataCalonMahasiswa biodataCalonMahasiswa) {
		this.biodataCalonMahasiswa = biodataCalonMahasiswa;
	}

	/**
	 * Mengembalikan siswa sekolah pembayar transaksi ini.
	 * <p>
	 * <b>Bukan getter destruktif</b>, sama seperti {@link #getMahasiswa()}.
	 *
	 * @return siswa pembayar, atau {@code null}.
	 */
	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE })
	@Fetch(FetchMode.SELECT)
	@JoinColumn(name = "siswa", nullable = true)
	public Siswa getSiswa() {
		return siswa;
	}

	/**
	 * Menetapkan siswa sekolah pembayar transaksi ini.
	 *
	 * @param siswa siswa pembayar; boleh {@code null}.
	 */
	public void setSiswa(Siswa siswa) {
		this.siswa = siswa;
	}

	/**
	 * Mengembalikan calon siswa (PSB) pembayar transaksi ini.
	 * <p>
	 * <b>Getter destruktif — SATU-SATUNYA di kelas ini:</b> nilai dilewatkan
	 * {@code check(...)} milik {@link GeneralValueObject} lalu ditulis balik ke
	 * field untuk menetralkan proxy Hibernate yang sesinya sudah tertutup.
	 * Ketidakseragaman terhadap tiga getter pembayar lainnya bersifat
	 * historis; jangan menyimpulkan perilaku yang sama untuk mereka.
	 *
	 * @return calon siswa pembayar, atau {@code null}.
	 */
	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY)
	@JoinColumn(name = "calon_siswa", nullable = true)
	public CalonSiswa getCalonSiswa() {
		calonSiswa = check(calonSiswa);
		return calonSiswa;
	}

	/**
	 * Menetapkan calon siswa (PSB) pembayar transaksi ini.
	 *
	 * @param calonSiswa calon siswa pembayar; boleh {@code null}.
	 */
	public void setCalonSiswa(CalonSiswa calonSiswa) {
		this.calonSiswa = calonSiswa;
	}

	/**
	 * Mengembalikan jenis kegiatan yang dibayar.
	 *
	 * @return jenis kegiatan, atau {@code null}.
	 */
	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE })
	@Fetch(FetchMode.SELECT)
	@JoinColumn(name = "jenis_kegiatan", nullable = true)
	public JenisKegiatan getJenisKegiatan() {
		return jenisKegiatan;
	}

	/**
	 * Menetapkan jenis kegiatan yang dibayar.
	 *
	 * @param jenisKegiatan jenis kegiatan; boleh {@code null}.
	 */
	public void setJenisKegiatan(JenisKegiatan jenisKegiatan) {
		this.jenisKegiatan = jenisKegiatan;
	}

	/**
	 * Mengembalikan jadwal pembayaran yang menaungi transaksi ini.
	 *
	 * @return jadwal pembayaran, atau {@code null}.
	 */
	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE })
	@Fetch(FetchMode.SELECT)
	@JoinColumn(name = "jadwal_pembayaran", nullable = true)
	public JadwalPembayaran getJadwalPembayaran() {
		return jadwalPembayaran;
	}

	/**
	 * Menetapkan jadwal pembayaran yang menaungi transaksi ini.
	 *
	 * @param jadwalPembayaran jadwal pembayaran; boleh {@code null}.
	 */
	public void setJadwalPembayaran(JadwalPembayaran jadwalPembayaran) {
		this.jadwalPembayaran = jadwalPembayaran;
	}

	/**
	 * Mengembalikan semester yang dibayar.
	 * <p>
	 * <b>Berbeda dari paket BNI:</b> tidak ada cabang yang memaksa nilai
	 * menjadi {@code 0} untuk kegiatan pendaftaran calon mahasiswa — nilai
	 * dikembalikan apa adanya, termasuk {@code null}.
	 *
	 * @return nomor semester, atau {@code null}.
	 */
	public Integer getSemester() {
		return semester;
	}

	/**
	 * Menetapkan semester yang dibayar.
	 *
	 * @param semester nomor semester; boleh {@code null}.
	 */
	public void setSemester(Integer semester) {
		this.semester = semester;
	}

	/**
	 * Mengembalikan tahun akademik yang dibayar.
	 *
	 * @return tahun akademik, atau {@code null}.
	 */
	public String getTahunAkademik() {
		return tahunAkademik;
	}

	/**
	 * Menetapkan tahun akademik yang dibayar.
	 *
	 * @param tahunAkademik tahun akademik.
	 */
	public void setTahunAkademik(String tahunAkademik) {
		this.tahunAkademik = tahunAkademik;
	}

	/**
	 * Mengembalikan nilai pengurangan/potongan yang diterapkan pada tagihan.
	 * <p>
	 * <b>Getter destruktif:</b> {@code null} dinormalkan menjadi {@code 0.0}
	 * dan ditulis balik ke field.
	 *
	 * @return nilai pengurangan; tidak pernah {@code null}.
	 */
	public Double getPengurangan() {
		if (pengurangan == null) {
			pengurangan = 0.0;
		}
		return pengurangan;
	}

	/**
	 * Menetapkan nilai pengurangan/potongan tagihan.
	 *
	 * @param pengurangan nilai potongan.
	 */
	public void setPengurangan(Double pengurangan) {
		this.pengurangan = pengurangan;
	}

	/**
	 * Mengembalikan total biaya yang seharusnya dibayar menurut master biaya.
	 * <p>
	 * Pembanding {@link #getAmount()}. <b>Getter destruktif:</b> {@code null}
	 * dinormalkan menjadi {@code 0.0}.
	 *
	 * @return nilai biaya yang harus dibayar; tidak pernah {@code null}.
	 */
	public Double getNilaiBiayaHarusDiBayars() {
		if (nilaiBiayaHarusDiBayars == null) {
			nilaiBiayaHarusDiBayars = 0.0;
		}
		return nilaiBiayaHarusDiBayars;
	}

	/**
	 * Menetapkan total biaya yang seharusnya dibayar menurut master biaya.
	 *
	 * @param nilaiBiayaHarusDiBayars nilai acuan biaya.
	 */
	public void setNilaiBiayaHarusDiBayars(Double nilaiBiayaHarusDiBayars) {
		this.nilaiBiayaHarusDiBayars = nilaiBiayaHarusDiBayars;
	}

	/**
	 * Mengembalikan keterangan bebas transaksi (kolom {@code text}).
	 *
	 * @return keterangan, atau {@code null}.
	 */
	@Column(name = "keterangan", columnDefinition = "text")
	public String getKeterangan() {
		return keterangan;
	}

	/**
	 * Menetapkan keterangan bebas transaksi.
	 *
	 * @param keterangan keterangan transaksi.
	 */
	public void setKeterangan(String keterangan) {
		this.keterangan = keterangan;
	}

	/**
	 * Mengembalikan balasan/notifikasi bank yang tertaut ke transaksi ini.
	 * <p>
	 * Karena BRI tidak memiliki endpoint callback, baris {@link BriResponse}
	 * biasanya dibuat oleh penjadwal
	 * {@code ais.action.master.bri.BriBackandProsess}, bukan oleh panggilan
	 * masuk dari bank.
	 *
	 * @return entitas {@link BriResponse}, atau {@code null}.
	 */
	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE })
	@Fetch(FetchMode.SELECT)
	@JoinColumn(name = "bri_response", nullable = true)
	public BriResponse getBriResponse() {
		return briResponse;
	}

	/**
	 * Menetapkan balasan/notifikasi bank untuk transaksi ini.
	 *
	 * @param briResponse entitas balasan bank.
	 */
	public void setBriResponse(BriResponse briResponse) {
		this.briResponse = briResponse;
	}

	/**
	 * Mengembalikan identitas merchant transaksi ini.
	 * <p>
	 * <b>Getter destruktif:</b> bila {@link #briResponse} sudah terisi, nilai
	 * merchant SELALU ditimpa dengan {@link BriResponse#getMerchant()},
	 * sehingga nilai yang disetel lewat {@link #setMerchant(String)} dapat
	 * hilang setelah balasan bank terekam.
	 *
	 * @return identitas merchant, atau {@code null}.
	 */
	public String getMerchant() {
		if (briResponse != null) {
			merchant = briResponse.getMerchant();
		}
		return merchant;
	}

	/**
	 * Menetapkan identitas merchant transaksi ini.
	 *
	 * @param merchant identitas merchant.
	 */
	public void setMerchant(String merchant) {
		this.merchant = merchant;
	}

	/**
	 * Mengembalikan nominal yang ditagihkan ke gateway BRI.
	 * <p>
	 * <b>Getter destruktif:</b> {@code null} dinormalkan menjadi {@code 0.0}.
	 *
	 * @return nominal tagihan; tidak pernah {@code null}.
	 */
	public Double getAmount() {
		if (amount == null) {
			amount = 0.0;
		}
		return amount;
	}

	/**
	 * Menetapkan nominal yang ditagihkan ke gateway BRI.
	 *
	 * @param amount nominal tagihan.
	 */
	public void setAmount(Double amount) {
		this.amount = amount;
	}

	/**
	 * Mengembalikan payload permintaan MENTAH yang di-POST ke gateway BRI.
	 * <p>
	 * <b>Catatan keamanan (lebih berat daripada BNI):</b> karena BRI
	 * mengandalkan bearer token pada <i>header</i>, badan permintaan tidak
	 * ter-enkripsi. Kolom {@code text} ini karena itu menyimpan JSON POLOS yang
	 * memuat {@code institutionCode}, {@code brivaNo}, {@code custCode} (nomor
	 * BRIVA), nama pembayar, nominal, dan tanggal kedaluwarsa — semuanya
	 * langsung terbaca. Isinya juga ikut digandakan ke tabel revisi Envers
	 * {@code bri_request_AUD}. Jangan tampilkan pada antarmuka
	 * berhak-akses-rendah dan pertimbangkan masking sebelum diekspor.
	 *
	 * @return payload permintaan mentah, atau {@code null}.
	 */
	@Column(columnDefinition = "text")
	public String getRequest() {
		return request;
	}

	/**
	 * Menetapkan payload permintaan mentah yang dikirim ke gateway BRI.
	 *
	 * @param request payload permintaan.
	 */
	public void setRequest(String request) {
		this.request = request;
	}

	/**
	 * Mengembalikan kode institusi BRIVA.
	 * <p>
	 * Diisi dari konfigurasi {@code bri_institution_code}. Ini identitas
	 * institusi, BUKAN kredensial rahasia — client secret
	 * ({@code bri_password}), {@code bri_api_key}, dan {@code access_token}
	 * tidak pernah disimpan pada entitas ini.
	 *
	 * @return kode institusi, atau {@code null}.
	 */
	public String getMerchant_id() {
		return merchant_id;
	}

	/**
	 * Menetapkan kode institusi BRIVA.
	 *
	 * @param merchant_id kode institusi dari konfigurasi.
	 */
	public void setMerchant_id(String merchant_id) {
		this.merchant_id = merchant_id;
	}

	// public String getBill_no() {
	// return bill_no;
	// }
	//
	// public void setBill_no(String bill_no) {
	// this.bill_no = bill_no;
	// }
	//
	// public String getBill_reff() {
	// return bill_reff;
	// }
	//
	// public void setBill_reff(String bill_reff) {
	// this.bill_reff = bill_reff;
	// }
	//
	// public Date getBill_date() {
	// return bill_date;
	// }
	//
	// public void setBill_date(Date bill_date) {
	// this.bill_date = bill_date;
	// }
	//
	/**
	 * Mengembalikan batas waktu berlakunya tagihan BRIVA.
	 * <p>
	 * <b>Getter destruktif:</b> bila belum diisi, nilai dihitung sebagai
	 * <i>satu HARI sejak waktu server saat getter dipanggil</i> lalu ditulis
	 * balik ke field.
	 * <p>
	 * <b>Perbedaan penting terhadap paket BNI:</b> default di sini SATU HARI,
	 * sedangkan {@code BniRequest#getBillExpired()} memberi default satu BULAN.
	 * Selain itu, sama seperti di BNI, kedaluwarsa efektif bergantung pada
	 * KAPAN getter pertama kali dipanggil — bukan pada kapan transaksi dibuat.
	 * Isi field ini secara eksplisit bila kedaluwarsa harus deterministik.
	 *
	 * @return batas waktu tagihan; tidak pernah {@code null}.
	 */
	public Date getBill_expired() {
		if (bill_expired == null) {
			Calendar calendar = ais.ui.util.WaktuUtil.getCalendar();
			calendar.set(Calendar.DATE, calendar.get(Calendar.DATE) + 1);
			bill_expired = calendar.getTime();
		}
		return bill_expired;
	}

	/**
	 * Menetapkan batas waktu berlakunya tagihan BRIVA.
	 *
	 * @param bill_expired batas waktu tagihan.
	 */
	public void setBill_expired(Date bill_expired) {
		this.bill_expired = bill_expired;
	}
	//
	// public String getBill_desc() {
	// return bill_desc;
	// }
	//
	// public void setBill_desc(String bill_desc) {
	// this.bill_desc = bill_desc;
	// }
	//
	// public String getBill_currency() {
	// return bill_currency;
	// }
	//
	// public void setBill_currency(String bill_currency) {
	// this.bill_currency = bill_currency;
	// }
	//
	// public Double getBill_gross() {
	// return bill_gross;
	// }
	//
	// public void setBill_gross(Double bill_gross) {
	// this.bill_gross = bill_gross;
	// }
	//
	// public Double getBill_tax() {
	// return bill_tax;
	// }
	//
	// public void setBill_tax(Double bill_tax) {
	// this.bill_tax = bill_tax;
	// }
	//
	// public Double getBill_miscfee() {
	// return bill_miscfee;
	// }
	//
	// public void setBill_miscfee(Double bill_miscfee) {
	// this.bill_miscfee = bill_miscfee;
	// }
	//
	// public Double getBill_total() {
	// return bill_total;
	// }
	//
	// public void setBill_total(Double bill_total) {
	// this.bill_total = bill_total;
	// }
	//
	// public String getCust_no() {
	// return cust_no;
	// }
	//
	// public void setCust_no(String cust_no) {
	// this.cust_no = cust_no;
	// }
	//
	// public String getCust_name() {
	// return cust_name;
	// }
	//
	// public void setCust_name(String cust_name) {
	// this.cust_name = cust_name;
	// }
	//
	// public String getPayment_channel() {
	// return payment_channel;
	// }
	//
	// public void setPayment_channel(String payment_channel) {
	// this.payment_channel = payment_channel;
	// }
	//
	// public String getPay_type() {
	// return pay_type;
	// }
	//
	// public void setPay_type(String pay_type) {
	// this.pay_type = pay_type;
	// }
	//
	// public String getBank_userid() {
	// return bank_userid;
	// }
	//
	// public void setBank_userid(String bank_userid) {
	// this.bank_userid = bank_userid;
	// }
	//
	// public String getMsisdn() {
	// return msisdn;
	// }
	//
	// public void setMsisdn(String msisdn) {
	// this.msisdn = msisdn;
	// }
	//
	// public String getEmail() {
	// return email;
	// }
	//
	// public void setEmail(String email) {
	// this.email = email;
	// }
	//
	// public String getTerminal() {
	// return terminal;
	// }
	//
	// public void setTerminal(String terminal) {
	// this.terminal = terminal;
	// }
	//
	// public String getBilling_address() {
	// return billing_address;
	// }
	//
	// public void setBilling_address(String billing_address) {
	// this.billing_address = billing_address;
	// }
	//
	// public String getBilling_address_city() {
	// return billing_address_city;
	// }
	//
	// public void setBilling_address_city(String billing_address_city) {
	// this.billing_address_city = billing_address_city;
	// }
	//
	// public String getBilling_address_region() {
	// return billing_address_region;
	// }
	//
	// public void setBilling_address_region(String billing_address_region) {
	// this.billing_address_region = billing_address_region;
	// }
	//
	// public String getBilling_address_state() {
	// return billing_address_state;
	// }
	//
	// public void setBilling_address_state(String billing_address_state) {
	// this.billing_address_state = billing_address_state;
	// }
	//
	// public String getBilling_address_poscode() {
	// return billing_address_poscode;
	// }
	//
	// public void setBilling_address_poscode(String billing_address_poscode) {
	// this.billing_address_poscode = billing_address_poscode;
	// }
	//
	// public String getBilling_address_country_code() {
	// return billing_address_country_code;
	// }
	//
	// public void setBilling_address_country_code(String
	// billing_address_country_code) {
	// this.billing_address_country_code = billing_address_country_code;
	// }
	//
	// public String getReceiver_name_for_shipping() {
	// return receiver_name_for_shipping;
	// }
	//
	// public void setReceiver_name_for_shipping(String
	// receiver_name_for_shipping) {
	// this.receiver_name_for_shipping = receiver_name_for_shipping;
	// }
	//
	// public String getShipping_address() {
	// return shipping_address;
	// }
	//
	// public void setShipping_address(String shipping_address) {
	// this.shipping_address = shipping_address;
	// }
	//
	// public String getShipping_address_city() {
	// return shipping_address_city;
	// }
	//
	// public void setShipping_address_city(String shipping_address_city) {
	// this.shipping_address_city = shipping_address_city;
	// }
	//
	// public String getShipping_address_region() {
	// return shipping_address_region;
	// }
	//
	// public void setShipping_address_region(String shipping_address_region) {
	// this.shipping_address_region = shipping_address_region;
	// }
	//
	// public String getShipping_address_state() {
	// return shipping_address_state;
	// }
	//
	// public void setShipping_address_state(String shipping_address_state) {
	// this.shipping_address_state = shipping_address_state;
	// }
	//
	// public String getShipping_address_poscode() {
	// return shipping_address_poscode;
	// }
	//
	// public void setShipping_address_poscode(String shipping_address_poscode)
	// {
	// this.shipping_address_poscode = shipping_address_poscode;
	// }

	/**
	 * Mengembalikan {@code custCode} BRIVA hasil jawaban bank.
	 * <p>
	 * Kolom pembantu warisan: {@code ais.common.BriCommon} mengisinya dengan
	 * nilai yang SAMA dengan {@link #getVa()}, {@link #getTrxId()}, dan
	 * {@link #getNama()}.
	 *
	 * @return {@code custCode} BRIVA, atau {@code null}.
	 */
	public String getData() {
		return data;
	}

	/**
	 * Menetapkan {@code custCode} BRIVA hasil jawaban bank (kolom pembantu).
	 *
	 * @param data {@code custCode} BRIVA.
	 */
	public void setData(String data) {
		this.data = data;
	}

	/**
	 * Mengembalikan kode respons gateway BRI atas permintaan penerbitan BRIVA.
	 * <p>
	 * Diisi dari medan {@code responseCode} pada jawaban API. Merekam status
	 * PENERBITAN tagihan, bukan status pembayaran — status pembayaran ada pada
	 * {@link BriResponse}.
	 *
	 * @return kode respons gateway, atau {@code null}.
	 */
	public String getResponse_code() {
		return response_code;
	}

	/**
	 * Menetapkan kode respons gateway BRI.
	 *
	 * @param response_code kode respons gateway.
	 */
	public void setResponse_code(String response_code) {
		this.response_code = response_code;
	}

	/**
	 * Mengembalikan keterangan respons gateway BRI atas permintaan penerbitan
	 * BRIVA; diisi dari medan {@code responseDescription} pada jawaban API.
	 *
	 * @return keterangan respons gateway, atau {@code null}.
	 */
	public String getResponse_desc() {
		return response_desc;
	}

	/**
	 * Menetapkan keterangan respons gateway BRI.
	 *
	 * @param response_desc keterangan respons gateway.
	 */
	public void setResponse_desc(String response_desc) {
		this.response_desc = response_desc;
	}

	/**
	 * Mengembalikan payload jawaban MENTAH dari gateway BRI.
	 * <p>
	 * <b>Catatan keamanan:</b> kolom {@code text} ini menyimpan balasan API
	 * bank apa adanya (dapat memuat {@code custCode}/nomor BRIVA dan nominal)
	 * dan ikut digandakan ke tabel revisi Envers {@code bri_request_AUD}.
	 *
	 * @return payload jawaban mentah, atau {@code null}.
	 */
	@Column(columnDefinition = "text")
	public String getResponse() {
		return response;
	}

	/**
	 * Menetapkan payload jawaban mentah dari gateway BRI.
	 *
	 * @param response payload jawaban.
	 */
	public void setResponse(String response) {
		this.response = response;
	}

	/**
	 * Mengembalikan nomor tagihan internal AIS untuk transaksi ini.
	 *
	 * @return nomor tagihan internal, atau {@code null}.
	 */
	public String getBillNo() {
		return billNo;
	}

	/**
	 * Menetapkan nomor tagihan internal AIS.
	 *
	 * @param billNo nomor tagihan internal.
	 */
	public void setBillNo(String billNo) {
		this.billNo = billNo;
	}

	/**
	 * Mengembalikan status pembayaran versi AIS.
	 * <p>
	 * <b>Getter destruktif:</b> bila belum pernah diisi, nilai
	 * {@code "Belum diproses"} ditulis balik ke field.
	 *
	 * @return status pembayaran; tidak pernah {@code null}.
	 */
	public String getStatus() {
		if (status == null) {
			status = "Belum diproses";
		}
		return status;
	}

	/**
	 * Menetapkan status pembayaran versi AIS.
	 *
	 * @param status status pembayaran.
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * Mengembalikan kode status pembayaran versi bank.
	 *
	 * @return kode status, atau {@code null}.
	 */
	public String getKodeStatus() {
		return kodeStatus;
	}

	/**
	 * Menetapkan kode status pembayaran versi bank.
	 *
	 * @param kodeStatus kode status dari bank.
	 */
	public void setKodeStatus(String kodeStatus) {
		this.kodeStatus = kodeStatus;
	}

	/**
	 * Mengembalikan flag "hapus cicilan sebelumnya".
	 * <p>
	 * <b>Getter destruktif dengan default aktif:</b> bila belum pernah diisi,
	 * nilai {@code true} ditulis balik ke field.
	 *
	 * @return {@code true} bila cicilan sebelumnya boleh dihapus; tidak pernah {@code null}.
	 */
	public Boolean getHapusCicilanSebelumnya() {
		if (hapusCicilanSebelumnya == null) {
			hapusCicilanSebelumnya = true;
		}
		return hapusCicilanSebelumnya;
	}

	/**
	 * Menetapkan flag "hapus cicilan sebelumnya".
	 * <p>
	 * <b>Setter dua arah — BERBEDA dari paket BNI:</b> berbeda dari
	 * {@code BniRequest#setHapusCicilanSebelumnya(Boolean)} yang mengabaikan
	 * {@code false}, setter ini menerima nilai apa pun termasuk {@code false}
	 * dan {@code null}. Menyetel {@code null} akan membuat
	 * {@link #getHapusCicilanSebelumnya()} kembali ke default {@code true}.
	 *
	 * @param hapusCicilanSebelumnya flag; nilai apa pun diterima.
	 */
	public void setHapusCicilanSebelumnya(Boolean hapusCicilanSebelumnya) {
		this.hapusCicilanSebelumnya = hapusCicilanSebelumnya;
	}

	/**
	 * Mengembalikan penanda "perlu diperiksa ulang".
	 * <p>
	 * <b>Getter destruktif:</b> {@code null} dinormalkan menjadi {@code false}
	 * dan ditulis balik ke field.
	 * <p>
	 * <b>Field tidur:</b> penelusuran seluruh basis kode menunjukkan properti
	 * ini tidak dibaca maupun ditulis oleh kelas lain mana pun; pemeriksaan
	 * ulang status BRI justru dikendalikan konfigurasi
	 * {@code aktifkan_pembayaran_via_bri} pada
	 * {@code ais.action.master.bri.BriBackandProsess}. Pertahankan kolomnya
	 * demi kompatibilitas skema, tetapi jangan membangun logika baru di atasnya
	 * tanpa lebih dulu menghidupkan kembali pemakaiannya.
	 *
	 * @return {@code false} secara efektif; tidak pernah {@code null}.
	 */
	public Boolean getCheckUlang() {
		if (checkUlang == null) {
			checkUlang = false;
		}
		return checkUlang;
	}

	/**
	 * Menetapkan penanda "perlu diperiksa ulang".
	 * <p>
	 * <b>Setter dua arah — BERBEDA dari paket BNI</b>, yang mengabaikan
	 * {@code false} secara diam-diam.
	 *
	 * @param checkUlang penanda; nilai apa pun diterima.
	 */
	public void setCheckUlang(Boolean checkUlang) {
		this.checkUlang = checkUlang;
	}

	/**
	 * Mengembalikan nomor BRIVA ({@code custCode}) transaksi ini.
	 * <p>
	 * Nomor berada di bawah {@code institutionCode}
	 * ({@code bri_institution_code}) dan {@code brivaNo}
	 * ({@code bri_briva_no}) milik institusi.
	 * <b>Catatan keamanan:</b> disimpan tanpa masking dan dapat ditampilkan
	 * penuh pada dasbor {@code LogHostToHostAction}.
	 *
	 * @return nomor BRIVA, atau {@code null}.
	 */
	public String getVa() {
		return va;
	}

	/**
	 * Menetapkan nomor BRIVA ({@code custCode}) transaksi ini.
	 *
	 * @param va nomor BRIVA.
	 */
	public void setVa(String va) {
		this.va = va;
	}

	/**
	 * Mengembalikan biaya administrasi bank untuk transaksi ini.
	 * <p>
	 * <b>Getter destruktif dengan efek samping konfigurasi:</b> bila nilai
	 * kosong atau lebih kecil dari {@code 0.01}, nilai diambil dari konfigurasi
	 * {@code bri_biaya_administrasi} (default {@code "0.0"}) lalu ditulis balik
	 * ke field. Perhatikan bahwa {@code Common.getKonfigurasi} MENULIS baris
	 * default ke tabel konfigurasi bila kunci belum ada, jadi memanggil getter
	 * ini dapat menciptakan baris konfigurasi baru. Kegagalan penguraian angka
	 * ditangkap dan dicatat lewat {@code ais.common.ErrorAuditUtil}.
	 *
	 * @return biaya administrasi; tidak pernah {@code null}.
	 */
	@Column(name = "biaya_administrasi")
	public Double getBiayaAdministrasi() {
		if (biayaAdministrasi == null || biayaAdministrasi < 0.01) {
			try {
				biayaAdministrasi = Double
						.parseDouble(Common.getKonfigurasi("bri_biaya_administrasi", "0.0").getNilai());
			} catch (Exception e) { ais.common.ErrorAuditUtil.record(e, "auto-audit(empty-catch) src/ais/database/model/bri/BriRequest.java:684");

			}
		}
		return biayaAdministrasi == null ? 0.0 : biayaAdministrasi;
	}

	/**
	 * Menetapkan biaya administrasi bank untuk transaksi ini.
	 *
	 * @param biayaAdministrasi nilai biaya administrasi.
	 */
	public void setBiayaAdministrasi(Double biayaAdministrasi) {
		this.biayaAdministrasi = biayaAdministrasi;
	}

	/**
	 * Mengembalikan biaya payment gateway untuk transaksi ini.
	 * <p>
	 * <b>Getter destruktif dengan efek samping konfigurasi:</b> berperilaku
	 * sama dengan {@link #getBiayaAdministrasi()}, tetapi membaca konfigurasi
	 * {@code bri_biaya_payment_gateway}.
	 *
	 * @return biaya payment gateway; tidak pernah {@code null}.
	 */
	@Column(name = "biaya_payment_gateway")
	public Double getBiayaPaymentGateway() {
		if (biayaPaymentGateway == null || biayaPaymentGateway < 0.01) {
			try {
				biayaPaymentGateway = Double
						.parseDouble(Common.getKonfigurasi("bri_biaya_payment_gateway", "0.0").getNilai());
			} catch (Exception e) { ais.common.ErrorAuditUtil.record(e, "auto-audit(empty-catch) src/ais/database/model/bri/BriRequest.java:701");

			}
		}
		return biayaPaymentGateway == null ? 0.0 : biayaPaymentGateway;
	}

	/**
	 * Menetapkan biaya payment gateway untuk transaksi ini.
	 *
	 * @param biayaPaymentGateway nilai biaya payment gateway.
	 */
	public void setBiayaPaymentGateway(Double biayaPaymentGateway) {
		this.biayaPaymentGateway = biayaPaymentGateway;
	}

	/**
	 * Mengembalikan nominal deposit yang menyertai transaksi ini.
	 * <p>
	 * Normalisasi {@code null} ke {@code 0.0} dilakukan TANPA menulis balik ke
	 * field, jadi getter ini tidak destruktif.
	 *
	 * @return nominal deposit; tidak pernah {@code null}.
	 */
	public Double getDeposit() {
		return deposit == null ? 0.0 : deposit;
	}

	/**
	 * Menetapkan nominal deposit yang menyertai transaksi ini.
	 *
	 * @param deposit nominal deposit.
	 */
	public void setDeposit(Double deposit) {
		this.deposit = deposit;
	}
}
