package ais.database.model.bri;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;




import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;
import org.hibernate.envers.Audited;



import ais.common.Common;
import ais.database.model.DetailBiaya;
import ais.database.model.GeneralValueObject;
import ais.database.model.ItemBiaya;
import ais.database.model.PengaturanPembayaranBulanan;
import ais.database.model.sekolah.Tagihan;

/**
 * Bank generated by hbm2java
 * <p>
 * Entitas <b>rincian baris tagihan</b> integrasi <i>host-to-host</i> BRIVA:
 * satu baris tabel {@code public.bri_request_detail} mewakili SATU item yang
 * dibayar di dalam sebuah {@link BriRequest}.
 *
 * <h3>Pola umum</h3>
 *
 * Kelas ini adalah kaki kedua dari pola empat kelas yang dipakai seluruh paket
 * integrasi bank AIS. <b>Penjelasan lengkap pola tersebut ada pada
 * {@link ais.database.model.bni.BniRequest}</b> dan tidak diulang di sini.
 * Ringkasnya: {@link BriRequest} adalah header (satu BRIVA, satu nominal
 * total), sedangkan kelas ini memecah nominal tersebut menjadi baris-baris
 * yang dapat dipertanggungjawabkan ke tagihan nyata, lewat relasi
 * {@code ManyToOne} pada {@link #getBriRequest()} (kolom {@code bri_request},
 * {@code NOT NULL}).
 *
 * <h3>Perbedaan NYATA terhadap {@code BniRequestDetail}</h3>
 *
 * <ul>
 * <li><b>Hanya TIGA jalur tagihan, bukan empat.</b> Entitas ini tidak memiliki
 * FK {@code pesertaPunyaProdukKursus}; jalur yang tersedia hanya
 * {@link #getItemBiaya()} (item biaya lepas),
 * {@link #getPengaturanPembayaranBulanan()} (SPP bulanan), dan
 * {@link #getTagihan()} (tagihan sekolah). Ini konsisten dengan
 * {@link BriRequest} yang juga tidak mendukung modul kursus.</li>
 *
 * <li><b>{@link #toString()} tidak destruktif.</b> Berbeda dari
 * {@code BniRequestDetail#toString()} yang menulis balik hasil getter ke
 * field, metode di sini membaca field secara langsung tanpa efek samping.</li>
 *
 * <li><b>{@link #getItemBiaya()} tidak destruktif.</b> Nilai dikembalikan apa
 * adanya tanpa dilewatkan {@code check(...)}, dan relasinya memakai
 * {@code FetchMode.SELECT} dengan <i>fetch</i> bawaan (eager) alih-alih
 * {@code FetchType.LAZY}.</li>
 *
 * <li><b>Penanda validator berbeda.</b> Keterangan yang dibangkitkan
 * {@link #getKeterangan()} berakhir dengan {@code ", validator : BRI"},
 * bukan {@code "BNI"} — penanda inilah yang dipakai laporan untuk mengenali
 * sumber pembayaran, jadi jangan disamakan antar-bank.</li>
 * </ul>
 *
 * <h3>Rekonsiliasi</h3>
 *
 * Karena BRI tidak memiliki endpoint callback (lihat {@link BriRequest}),
 * himpunan {@code BriRequestDetail} dibaca saat <i>polling</i>
 * {@code ais.action.master.bri.BriBackandProsess} menemukan pembayaran lunas
 * dan memanggil {@code ais.action.servlet.Briresponse#prosesResponse} untuk
 * menerbitkan {@code CicilanPembayaran}/{@code Kegiatan}.
 * {@link #getIdCicilan()} dan {@link #getCicilanref()} menyimpan kaitan balik
 * ke cicilan yang sudah terbit; {@code idCicilan IS NULL} menandai rincian
 * yang belum terekonsiliasi.
 *
 * <h3>Catatan keamanan</h3>
 *
 * Kolom {@link #getNilai() nilai}, {@link #getNilaiAsli() nilaiAsli}, dan
 * {@link #getDenda() denda} menyimpan nominal keuangan apa adanya tanpa
 * masking, dan kelas beranotasi {@link Audited} sehingga setiap versinya
 * digandakan ke tabel revisi {@code bri_request_detail_AUD}. Tidak ada kolom
 * kepemilikan/tenant — cakupan hanya tersirat lewat {@link BriRequest}
 * induknya.
 *
 * @see ais.database.model.bni.BniRequest
 * @see BriRequest
 * @see BriRequestDetailBiaya
 * @see BriResponse
 * @see ais.action.master.bri.BriBackandProsess
 */
@Entity
@org.hibernate.annotations.Entity(
    dynamicInsert = true,
    dynamicUpdate = true
)
@Audited
@Table(schema = "public", name = "bri_request_detail")



public class BriRequestDetail extends GeneralValueObject {
	/**
	 *
	 * Nomor versi serialisasi entitas; JANGAN diubah agar data lama tetap terbaca.
	 */
	private static final long serialVersionUID = 2463821327548439808L;
	/** Kunci utama (identity, dibangkitkan basis data). */
	private Long id;
	/** Nama pengguna terakhir yang mengubah baris ini (field audit bayangan). */
	private String oleh;
	/** Identitas (id) pengguna terakhir yang mengubah baris ini (field audit bayangan). */
	private String olehId;

	/**
	 * Mengembalikan identitas pengguna terakhir yang menyentuh baris ini.
	 *
	 * @return id pengguna audit, atau {@code null} bila belum pernah diisi.
	 */
	public String getOlehId() {
		return olehId;
	}

	/**
	 * Menetapkan identitas pengguna audit.
	 * <p>
	 * <b>Setter satu arah:</b> nilai {@code null} atau string kosong DIABAIKAN
	 * secara diam-diam.
	 *
	 * @param olehId id pengguna; diabaikan bila kosong.
	 */
	public void setOlehId(String olehId) {if (olehId == null || olehId.trim().isEmpty()) {return;}
		this.olehId = olehId;
	}

	/**
	 * Menetapkan nama pengguna audit.
	 * <p>
	 * <b>Setter satu arah:</b> nilai {@code null} atau string kosong DIABAIKAN
	 * secara diam-diam.
	 *
	 * @param oleh nama pengguna; diabaikan bila kosong.
	 */
	public void setOleh(String oleh) {if (oleh == null || oleh.trim().isEmpty()) {return;}
		this.oleh = oleh;
	}

	/**
	 * Mengembalikan nama pengguna terakhir yang menyentuh baris ini.
	 *
	 * @return nama pengguna audit, atau {@code null} bila belum pernah diisi.
	 */
	public String getOleh() {
		return oleh;
	}

	/**
	 * Kait daur hidup JPA yang dipanggil tepat sebelum {@code UPDATE};
	 * mendelegasikan pengisian jejak audit ke
	 * {@code ais.database.hibernate.AuditTimestampInterceptor#ubah(Object)}.
	 * Keharusan teknis mekanisme audit AIS, bukan logika bisnis.
	 */
	@javax.persistence.PreUpdate protected void onUpdate() { ais.database.hibernate.AuditTimestampInterceptor.ubah(this);}     /** Stempel waktu perubahan terakhir; diinisialisasi ke waktu server saat objek dibuat. */
	private Date tanggal_dirubah = ais.ui.util.WaktuUtil.getDate();

	/**
	 * Menetapkan stempel waktu perubahan terakhir.
	 *
	 * @param tanggal_dirubah waktu perubahan.
	 */
	public void setTanggal_dirubah(Date tanggal_dirubah) {
		this.tanggal_dirubah = tanggal_dirubah;
	}

	/**
	 * Mengembalikan stempel waktu perubahan terakhir apa adanya.
	 *
	 * @return stempel waktu perubahan, atau {@code null}.
	 */
	@Temporal(TemporalType.TIMESTAMP)
	public Date getTanggal_dirubah() {
		return tanggal_dirubah;
	}

	/**
	 * Representasi teks ringkas untuk kombo/daftar ZK dan berkas log.
	 * <p>
	 * <b>Tidak destruktif:</b> berbeda dari
	 * {@code BniRequestDetail#toString()}, metode ini membaca field secara
	 * langsung tanpa memanggil getter dan tanpa menulis balik ke field,
	 * sehingga aman dipanggil pada entitas terkelola.
	 *
	 * @return gabungan id, request induk, item biaya, pengaturan bulanan,
	 *         nilai, tanggal, urutan, dan keterangan dipisah tanda hubung.
	 */
	public String toString() {
		return id + "-" + briRequest + "-" + itemBiaya + "-" + pengaturanPembayaranBulanan + "-" + nilai + "-" + tanggal
				+ "-" + ke + "-" + keterangan;
	}

	/** Header transaksi induk; kolom {@code bri_request}, wajib terisi. */
	private BriRequest briRequest;
	/** Jalur tagihan SPP bulanan yang dibayar baris ini. */
	private PengaturanPembayaranBulanan pengaturanPembayaranBulanan;
	/** Jalur tagihan item biaya lepas yang dibayar baris ini. */
	private ItemBiaya itemBiaya;
	/** Mata biaya master yang menaungi baris ini. */
	private DetailBiaya detailBiaya;
	/** Jalur tagihan modul sekolah yang dibayar baris ini. */
	private Tagihan tagihan;
	/** Nominal yang dibayar untuk baris ini. */
	private Double nilai;
	/** Keterangan baris; dibangkitkan otomatis bila kosong (lihat {@link #getKeterangan()}). */
	private String keterangan;
	/** Tanggal jatuh tempo/pembayaran baris ini. */
	private Date tanggal;
	/** Nomor urut cicilan ke berapa baris ini berada. */
	private Integer ke;
	/** Id {@code CicilanPembayaran} hasil rekonsiliasi; {@code null} berarti belum terekonsiliasi. */
	private Long idCicilan;
	/** Denda keterlambatan yang menyertai baris ini. */
	private Double denda;
	/** Nominal asli sebelum modifikasi/potongan. */
	private Double nilaiAsli;

	/** Referensi cicilan tambahan (kaitan balik sekunder ke cicilan yang terbit). */
	private Long cicilanref;

	/** Konstruktor tanpa argumen yang diwajibkan Hibernate/JPA. */
	public BriRequestDetail() {
	}

	/**
	 * Mengembalikan kunci utama baris ini.
	 *
	 * @return id baris, atau {@code null} bila belum di-persist.
	 */
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", insertable = false, unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	/**
	 * Menetapkan kunci utama baris ini.
	 *
	 * @param id kunci utama.
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * Mengembalikan header transaksi BRI yang menaungi baris rincian ini.
	 * <p>
	 * Kolom {@code bri_request} bersifat {@code NOT NULL}: setiap rincian WAJIB
	 * memiliki induk.
	 *
	 * @return header transaksi induk.
	 */
	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE })
	@Fetch(FetchMode.SELECT)
	@JoinColumn(name = "bri_request", nullable = false)
	public BriRequest getBriRequest() {
		return briRequest;
	}

	/**
	 * Menetapkan header transaksi BRI yang menaungi baris rincian ini.
	 *
	 * @param briRequest header transaksi induk; tidak boleh {@code null} saat di-persist.
	 */
	public void setBriRequest(BriRequest briRequest) {
		this.briRequest = briRequest;
	}

	/**
	 * Mengembalikan pengaturan pembayaran bulanan (satu bulan SPP) yang dibayar
	 * baris ini.
	 *
	 * @return pengaturan pembayaran bulanan, atau {@code null} bila baris ini
	 *         memakai jalur tagihan lain.
	 */
	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE })
	@Fetch(FetchMode.SELECT)
	@JoinColumn(name = "pengaturan_pembayaran_bulanan", nullable = true)
	public PengaturanPembayaranBulanan getPengaturanPembayaranBulanan() {
		return pengaturanPembayaranBulanan;
	}

	/**
	 * Menetapkan pengaturan pembayaran bulanan yang dibayar baris ini.
	 *
	 * @param pengaturanPembayaranBulanan pengaturan bulanan; boleh {@code null}.
	 */
	public void setPengaturanPembayaranBulanan(PengaturanPembayaranBulanan pengaturanPembayaranBulanan) {
		this.pengaturanPembayaranBulanan = pengaturanPembayaranBulanan;
	}

	/**
	 * Mengembalikan item biaya lepas yang dibayar baris ini.
	 * <p>
	 * <b>Bukan getter destruktif:</b> berbeda dari
	 * {@code BniRequestDetail#getItemBiaya()}, nilai dikembalikan apa adanya
	 * tanpa dilewatkan {@code check(...)}, dan relasi memakai
	 * {@code FetchMode.SELECT} dengan <i>fetch</i> bawaan (eager).
	 *
	 * @return item biaya, atau {@code null} bila baris ini memakai jalur
	 *         tagihan lain.
	 */
	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE })
	@Fetch(FetchMode.SELECT)
	@JoinColumn(name = "item_biaya", nullable = true)
	public ItemBiaya getItemBiaya() {
		return itemBiaya;
	}

	/**
	 * Menetapkan item biaya lepas yang dibayar baris ini.
	 *
	 * @param itemBiaya item biaya; boleh {@code null}.
	 */
	public void setItemBiaya(ItemBiaya itemBiaya) {
		this.itemBiaya = itemBiaya;
	}

	/**
	 * Mengembalikan nominal yang dibayar untuk baris rincian ini.
	 * <p>
	 * <b>Getter destruktif:</b> {@code null} dinormalkan menjadi {@code 0.0}
	 * dan ditulis balik ke field.
	 * <p>
	 * <b>Catatan keamanan:</b> nominal disimpan apa adanya tanpa masking dan
	 * ikut digandakan ke tabel revisi {@code bri_request_detail_AUD}.
	 *
	 * @return nominal baris; tidak pernah {@code null}.
	 */
	public Double getNilai() {
		if (nilai == null) {
			nilai = 0.0;
		}
		return nilai;
	}

	/**
	 * Menetapkan nominal yang dibayar untuk baris rincian ini.
	 *
	 * @param nilai nominal baris.
	 */
	public void setNilai(Double nilai) {
		this.nilai = nilai;
	}

	/**
	 * Mengembalikan keterangan baris rincian (kolom {@code text}).
	 * <p>
	 * <b>Getter destruktif dengan pembangkitan otomatis:</b> bila keterangan
	 * masih kosong, teks dibangkitkan lalu DITULIS BALIK ke field, dengan dua
	 * cabang:
	 * <ul>
	 * <li>bila {@link #getPengaturanPembayaranBulanan()} terisi — teks disusun
	 * dari kode dan nama item biaya master, nama bulan, serta nominal
	 * modifikasi yang dihitung
	 * {@code PengaturanPembayaranBulanan#ambilNominalModifikasi(Mahasiswa, Integer)}
	 * berdasarkan mahasiswa dan semester pada {@link BriRequest} induk;</li>
	 * <li>bila hanya {@link #getItemBiaya()} yang terisi — teks disusun dari
	 * kode, nama, dan {@link #getNilai()}.</li>
	 * </ul>
	 * Kedua cabang diakhiri penanda {@code ", validator : BRI"} — <b>berbeda
	 * dari paket BNI yang memakai {@code "BNI"}</b>. Penanda inilah yang
	 * dipakai laporan untuk mengenali sumber pembayaran.
	 * <p>
	 * Blok {@code try} pada cabang pertama sengaja menelan seluruh eksepsi:
	 * {@code pengaturanPembayaranBulanan}/{@code detailBiaya} dapat berupa
	 * instance kanonik bersama milik {@code AuditTimestampInterceptor} yang
	 * proxy-nya terikat ke {@code Session} lain yang sudah tertutup, sehingga
	 * tanpa penjagaan ini getter akan melempar
	 * {@code LazyInitializationException}. Eksepsi tetap dicatat lewat
	 * {@code ais.common.ErrorAuditUtil}; nilai kembalian menjadi {@code null}
	 * sebagai fallback aman.
	 *
	 * @return keterangan baris, atau {@code null} bila tidak dapat dibangkitkan.
	 */
	@Column(columnDefinition = "text")
	public String getKeterangan() {
		if ((keterangan == null || keterangan.trim().isEmpty())) {
			if (pengaturanPembayaranBulanan != null) {
				try {
					// FIX LazyInitializationException: pengaturanPembayaranBulanan/detailBiaya bisa berupa
					// instance canonical/shared (AuditTimestampInterceptor) yang proxy-nya terikat ke Session
					// lain yang sudah closed -> jangan biarkan getter ini crash, kembalikan fallback aman.
					keterangan = pengaturanPembayaranBulanan.getDetailBiaya().getItemBiaya().getKode() + "-"
							+ pengaturanPembayaranBulanan.getDetailBiaya().getItemBiaya().getNama() + ", bulan "
							+ pengaturanPembayaranBulanan.getNamaBulan() + " " + ", nominal Rp. "
							+ Common.numberFormat.get().format(pengaturanPembayaranBulanan.ambilNominalModifikasi(
									briRequest == null || briRequest.getJenisKegiatan() == null ? null
											: briRequest.getMahasiswa(),
									briRequest == null || briRequest.getJenisKegiatan() == null ? null
											: briRequest.getSemester()))
							+ ", validator : BRI";
				} catch (Exception exLazy) { ais.common.ErrorAuditUtil.record(exLazy, "auto-audit(empty-catch) src/ais/database/model/bri/BriRequestDetail.java:getKeterangan-lazy");
				}
			} else if (itemBiaya != null && getNilai() != null) {
				keterangan = itemBiaya.getKode() + "-" + itemBiaya.getNama() + ", nominal Rp. "
						+ Common.numberFormat.get().format(getNilai()) + ", validator : BRI";
			}
		}
		return keterangan;
	}

	/**
	 * Menetapkan keterangan baris rincian.
	 * <p>
	 * Mengisi nilai non-kosong akan MEMATIKAN pembangkitan otomatis pada
	 * {@link #getKeterangan()}.
	 *
	 * @param keterangan keterangan baris.
	 */
	public void setKeterangan(String keterangan) {
		this.keterangan = keterangan;
	}

	/**
	 * Mengembalikan tanggal jatuh tempo/pembayaran baris rincian ini.
	 *
	 * @return tanggal baris, atau {@code null}.
	 */
	@Temporal(TemporalType.TIMESTAMP)
	public Date getTanggal() {
		return tanggal;
	}

	/**
	 * Menetapkan tanggal jatuh tempo/pembayaran baris rincian ini.
	 *
	 * @param tanggal tanggal baris.
	 */
	public void setTanggal(Date tanggal) {
		this.tanggal = tanggal;
	}

	/**
	 * Mengembalikan nomor urut cicilan ke berapa baris ini berada.
	 *
	 * @return nomor urut cicilan, atau {@code null} bila bukan bagian cicilan.
	 */
	public Integer getKe() {
		return ke;
	}

	/**
	 * Menetapkan nomor urut cicilan baris ini.
	 *
	 * @param ke nomor urut cicilan.
	 */
	public void setKe(Integer ke) {
		this.ke = ke;
	}

	/**
	 * Mengembalikan id {@code CicilanPembayaran} hasil rekonsiliasi baris ini.
	 * <p>
	 * Nilai {@code null} berarti baris BELUM terekonsiliasi; kriteria
	 * {@code idCicilan IS NULL} inilah yang dipakai
	 * {@code ais.action.master.bri.BriRequestAction} untuk mencari rincian yang
	 * pembayarannya belum diterbitkan.
	 *
	 * @return id cicilan yang sudah terbit, atau {@code null}.
	 */
	public Long getIdCicilan() {
		return idCicilan;
	}

	/**
	 * Menetapkan id {@code CicilanPembayaran} hasil rekonsiliasi baris ini.
	 *
	 * @param idCicilan id cicilan yang sudah terbit.
	 */
	public void setIdCicilan(Long idCicilan) {
		this.idCicilan = idCicilan;
	}

	/**
	 * Mengembalikan denda keterlambatan yang menyertai baris ini.
	 * <p>
	 * Berbeda dari {@link #getNilai()}, getter ini TIDAK menormalkan
	 * {@code null}.
	 *
	 * @return nilai denda, atau {@code null} bila tidak ada denda.
	 */
	public Double getDenda() {
		return denda;
	}

	/**
	 * Menetapkan denda keterlambatan yang menyertai baris ini.
	 *
	 * @param denda nilai denda.
	 */
	public void setDenda(Double denda) {
		this.denda = denda;
	}

	/**
	 * Mengembalikan nominal asli baris ini sebelum modifikasi/potongan.
	 * <p>
	 * Pembanding {@link #getNilai()} ketika nominal dimodifikasi (beasiswa,
	 * keringanan). Getter ini juga TIDAK menormalkan {@code null}.
	 *
	 * @return nominal asli, atau {@code null}.
	 */
	public Double getNilaiAsli() {
		return nilaiAsli;
	}

	/**
	 * Menetapkan nominal asli baris ini sebelum modifikasi/potongan.
	 *
	 * @param nilaiAsli nominal asli.
	 */
	public void setNilaiAsli(Double nilaiAsli) {
		this.nilaiAsli = nilaiAsli;
	}

	/**
	 * Mengembalikan mata biaya master yang menaungi baris rincian ini.
	 *
	 * @return detail biaya master, atau {@code null}.
	 */
	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE })
	@Fetch(FetchMode.SELECT)
	@JoinColumn(name = "detail_biaya", nullable = true)
	public DetailBiaya getDetailBiaya() {
		return detailBiaya;
	}

	/**
	 * Menetapkan mata biaya master yang menaungi baris rincian ini.
	 *
	 * @param detailBiaya detail biaya master; boleh {@code null}.
	 */
	public void setDetailBiaya(DetailBiaya detailBiaya) {
		this.detailBiaya = detailBiaya;
	}

	/**
	 * Mengembalikan tagihan modul sekolah yang dibayar baris ini.
	 *
	 * @return tagihan sekolah, atau {@code null} bila baris ini memakai jalur
	 *         tagihan lain.
	 */
	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE })
	@Fetch(FetchMode.SELECT)
	@JoinColumn(name = "tagihan", nullable = true)
	public Tagihan getTagihan() {
		return tagihan;
	}

	/**
	 * Menetapkan tagihan modul sekolah yang dibayar baris ini.
	 *
	 * @param tagihan tagihan sekolah; boleh {@code null}.
	 */
	public void setTagihan(Tagihan tagihan) {
		this.tagihan = tagihan;
	}

	/**
	 * Mengembalikan referensi cicilan sekunder baris ini.
	 * <p>
	 * Pendamping {@link #getIdCicilan()} untuk skenario ketika satu rincian
	 * berkaitan dengan lebih dari satu jejak cicilan.
	 *
	 * @return referensi cicilan, atau {@code null}.
	 */
	public Long getCicilanref() {
		return cicilanref;
	}

	/**
	 * Menetapkan referensi cicilan sekunder baris ini.
	 *
	 * @param cicilanref referensi cicilan.
	 */
	public void setCicilanref(Long cicilanref) {
		this.cicilanref = cicilanref;
	}

}
