package ais.database.model.obe;

// Generated Apr 16, 2010 2:27:16 PM by Hibernate Tools 3.2.4.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.envers.Audited;

import ais.database.model.GeneralValueObject;
import ais.database.model.Jurusan;
import ais.database.model.PerguruanTinggi;

/**
 * <h3>ProfesiLulusan — Profesi/Karier Lulusan</h3>
 *
 * <p>Master daftar profesi atau posisi karier yang bisa dituju lulusan sebuah program studi
 * — mis. "Software Engineer", "Data Analyst", "Guru". Kelas ini adalah lookup/master yang
 * relatif independen dari struktur prodi tertentu (field {@link #getJurusan()} bersifat
 * opsional, {@code nullable = true}), dan direlasikan balik dari
 * {@link ProfilLulusan#getProfesiLulusan()} — satu Profil Lulusan (PL) menunjuk paling banyak
 * satu {@code ProfesiLulusan} (relasi many-to-one), menandakan profesi tujuan utama PL
 * tersebut. Dalam rantai OBE modul ini, {@code ProfesiLulusan} berdiri sedikit di luar rantai
 * inti {@link ProfilLulusan}&nbsp;&rarr;&nbsp;{@link CapaianLulusan}&nbsp;&rarr;&nbsp;
 * {@link CapaianPembelajaranLulusan}: perannya adalah metadata deskriptif/pelengkap PL
 * (untuk keperluan pelaporan/akreditasi seperti profil lulusan pada borang ABET-like),
 * bukan bagian dari mekanisme perhitungan capaian atau nilai.</p>
 *
 * <p>Mengikuti pola entitas OBE lain: extends {@link GeneralValueObject}, ber-audit Envers,
 * tabel {@code public.profesilulusan}, dan field audit shadow {@code oleh}/{@code olehId}/
 * {@code tanggal_dirubah} (kebutuhan teknis {@code AuditTimestampInterceptor}, bukan bug).</p>
 *
 * <p><b>Bank generated by hbm2java</b> — komentar asli generator Hibernate Tools.</p>
 */
@Entity
@org.hibernate.annotations.Entity(dynamicInsert = true, dynamicUpdate = true)
@Audited
@Table(schema = "public", name = "profesilulusan")
public class ProfesiLulusan extends GeneralValueObject {

	/** 
	 * 
	 */
	private static final long serialVersionUID = 2463821577548439808L;
	private Long id;
	private String oleh;
	private String olehId;

	/** @return ID pengguna (username) yang terakhir mengubah baris ini. Field audit shadow — lihat {@link #getOleh()}. */
	public String getOlehId() {
		return olehId;
	}

	/**
	 * Setter {@link #getOlehId()}. Nilai kosong/blank diabaikan (no-op) agar jejak audit lama
	 * tidak tertimpa saat proses simpan tidak membawa identitas pengguna — pola baku di semua
	 * entitas modul OBE.
	 */
	public void setOlehId(String olehId) {
		if (olehId == null || olehId.trim().isEmpty()) {
			return;
		}
		this.olehId = olehId;
	}

	/** Setter {@link #getOleh()}. Nilai kosong/blank diabaikan (no-op), sama seperti {@link #setOlehId(String)}. */
	public void setOleh(String oleh) {
		if (oleh == null || oleh.trim().isEmpty()) {
			return;
		}
		this.oleh = oleh;
	}

	/** @return nama pengguna yang terakhir mengubah baris ini (field audit shadow, diisi via {@link #onUpdate()}). */
	public String getOleh() {
		return oleh;
	}

	/**
	 * Callback JPA {@code @PreUpdate}, dipanggil otomatis Hibernate sebelum UPDATE untuk
	 * mengisi {@link #oleh}/{@link #olehId}/{@link #tanggal_dirubah} dari sesi pengguna aktif
	 * via {@link ais.database.hibernate.AuditTimestampInterceptor#ubah(Object)}.
	 */
	@javax.persistence.PreUpdate
	protected void onUpdate() {
		ais.database.hibernate.AuditTimestampInterceptor.ubah(this);
	}

	/** Timestamp terakhir baris ini diubah; default diisi saat objek dibuat, diperbarui via {@link #onUpdate()}. */
	private Date tanggal_dirubah = ais.ui.util.WaktuUtil.getDate();

	/** @param tanggal_dirubah lihat {@link #getTanggal_dirubah()}. */
	public void setTanggal_dirubah(Date tanggal_dirubah) {
		this.tanggal_dirubah = tanggal_dirubah;
	}

	/** @return timestamp terakhir baris ini diubah. */
	@Temporal(TemporalType.TIMESTAMP)
	public Date getTanggal_dirubah() {
		return tanggal_dirubah;
	}

	/** @return representasi ringkas {@code "<id>-<nama>"}, dipakai untuk tampilan log/debug. */
	public String toString() {
		return id + "-" + nama;
	}

	private String kode;
	private String nama;
	private Jurusan jurusan;
	private String keterangan;
	private PerguruanTinggi perguruanTinggi;
	private Boolean aktif;

	/** Konstruktor default (dibutuhkan Hibernate). */
	public ProfesiLulusan() {
	}

	/** @return ID unik baris profesi (primary key, auto-increment via {@code IDENTITY}). */
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", insertable = false, unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	/** @param id lihat {@link #getId()}. Normalnya tidak perlu diisi manual — dihasilkan DB saat insert. */
	public void setId(Long id) {
		this.id = id;
	}

	/** @return kode singkat profesi, di-trim; string kosong bila belum diisi. */
	public String getKode() {
		return kode == null || kode.isEmpty() ? "" : kode.trim();
	}

	/** @param kode lihat {@link #getKode()}. */
	public void setKode(String kode) {
		this.kode = kode;
	}

	/** @return nama profesi/karier (di-trim); {@code null} bila belum diisi. Wajib diisi ({@code nullable = false}). */
	@Column(name = "nama", nullable = false, columnDefinition = "text")
	public String getNama() {
		return this.nama == null ? null : this.nama.trim();
	}

	/** @param nama lihat {@link #getNama()}. */
	public void setNama(String nama) {
		this.nama = nama;
	}

	/** @return keterangan/deskripsi tambahan profesi (opsional); tidak di-trim, boleh {@code null}. */
	@Column(name = "keterangan", nullable = true, columnDefinition = "text")
	public String getKeterangan() {
		return this.keterangan;
	}

	/** @param keterangan lihat {@link #getKeterangan()}. */
	public void setKeterangan(String keterangan) {
		this.keterangan = keterangan;
	}

	/**
	 * @return status aktif profesi. Flag satu-arah: {@code null} (baris lama/belum pernah
	 *         diisi) dianggap aktif secara default agar data lama tidak tiba-tiba hilang dari
	 *         daftar profesi aktif.
	 */
	public Boolean getAktif() {
		return aktif == null ? true : aktif;
	}

	/** @param aktif lihat {@link #getAktif()}. */
	public void setAktif(Boolean aktif) {
		this.aktif = aktif;
	}

	/**
	 * @return perguruan tinggi pemilik daftar profesi ini (opsional, {@code nullable = true} —
	 *         berbeda dari kebanyakan getter perguruan-tinggi lain di paket ini yang
	 *         {@code nullable = false} secara implisit). Lazy-loaded, di-null-safe-kan via
	 *         {@link GeneralValueObject#check(Object)}; bila hasilnya masih {@code null},
	 *         jatuh ke PT milik sesi pengguna saat ini via
	 *         {@link ais.action.master.helper.util.PerguruanTinggiUtil#getPerguruanTinggi()}
	 *         (exception ditangkap diam-diam, direkam ke {@link ais.common.ErrorAuditUtil}).
	 */
	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY)
	@JoinColumn(name = "perguruan_tinggi", nullable = true)
	public PerguruanTinggi getPerguruanTinggi() {
		perguruanTinggi = check(perguruanTinggi);
		try {
			if (perguruanTinggi == null) {
				perguruanTinggi = ais.action.master.helper.util.PerguruanTinggiUtil.getPerguruanTinggi();
			}
		} catch (Exception e) { ais.common.ErrorAuditUtil.record(e, "auto-audit(empty-catch) src/ais/database/model/obe/ProfesiLulusan.java:149");
		}
		return perguruanTinggi;
	}

	/** @param perguruanTinggi lihat {@link #getPerguruanTinggi()}. */
	public void setPerguruanTinggi(PerguruanTinggi perguruanTinggi) {
		this.perguruanTinggi = perguruanTinggi;
	}

	/**
	 * @return program studi terkait profesi ini (opsional, {@code nullable = true}) —
	 *         lazy-loaded, di-null-safe-kan via {@link GeneralValueObject#check(Object)}.
	 *         Boleh {@code null} karena satu profesi bisa relevan untuk lebih dari satu
	 *         program studi (mis. "Data Analyst" relevan untuk prodi Informatika maupun
	 *         Statistika); field ini hanya menandai afiliasi utama/opsional, bukan pembatas.
	 */
	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY)
	@JoinColumn(name = "jurusan", nullable = true)
	public Jurusan getJurusan() {
		jurusan = check(jurusan);
		return jurusan;
	}

	/** @param jurusan lihat {@link #getJurusan()}. */
	public void setJurusan(Jurusan jurusan) {
		this.jurusan = jurusan;
	}

}
