<%-- @generated by generate_new_jsp_scaffold.py
Source: src/ais/action/master/helper/PenjadwalanSkripsiHelper.java
Generated: 2026-08-06T18:20:20Z
Safe service-adapter scaffold. Implement data access in a Java service layer, not directly in this JSP.
--%>
<%@ page language="java" contentType="application/json; charset=UTF-8" pageEncoding="UTF-8" %>
<%
request.setAttribute("nuiServiceModule", "helper");
request.setAttribute("nuiServicePage", "penjadwalan_skripsi_helper");
request.setAttribute("nuiServiceTitle", "Penjadwalan Skripsi Helper");
request.setAttribute("nuiServiceType", "academic");
request.setAttribute("nuiServiceSourceClass", "PenjadwalanSkripsiHelper");
request.setAttribute("nuiServiceSourcePackage", "ais.action.master.helper");
request.setAttribute("nuiServiceSourcePath", "src/ais/action/master/helper/PenjadwalanSkripsiHelper.java");
request.setAttribute("nuiServiceMethods", new String[]{"render", "onEvent", "save", "display", "onSearchDefault"});
request.setAttribute("nuiServiceEntities", new String[]{"StatusPertemuan"});
%>
<jsp:include page="/WEB-INF/new/_shared/services/dispatcher.jsp" />
