<%-- @generated by generate_new_jsp_scaffold.py
Source: src/ais/action/master/helper/PklHelper.java
Generated: 2026-08-06T18:20:20Z
Safe service-adapter scaffold. Implement data access in a Java service layer, not directly in this JSP.
--%>
<%@ page language="java" contentType="application/json; charset=UTF-8" pageEncoding="UTF-8" %>
<%
request.setAttribute("nuiServiceModule", "helper");
request.setAttribute("nuiServicePage", "pkl_helper");
request.setAttribute("nuiServiceTitle", "PKL Helper");
request.setAttribute("nuiServiceType", "list");
request.setAttribute("nuiServiceSourceClass", "PklHelper");
request.setAttribute("nuiServiceSourcePackage", "ais.action.master.helper");
request.setAttribute("nuiServiceSourcePath", "src/ais/action/master/helper/PklHelper.java");
request.setAttribute("nuiServiceMethods", new String[]{"render", "onEvent", "loadData", "display"});
request.setAttribute("nuiServiceEntities", new String[]{"MahasiswaDapatPkl"});
%>
<jsp:include page="/WEB-INF/new/_shared/services/dispatcher.jsp" />
