<%-- @generated by generate_new_jsp_scaffold.py
Source: src/ais/action/master/sekolah/psb/VerifikasiMatapelajaranPSBHelper.java
Generated: 2026-08-06T18:20:20Z
This JSP contains presentation metadata only. Keep business logic in Java services.
--%>
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%
request.setAttribute("nuiModule", "sekolah");
request.setAttribute("nuiModuleLabel", "eSchool");
request.setAttribute("nuiPage", "psb/verifikasi_matapelajaran_psb_helper");
request.setAttribute("nuiPageTitle", "Verifikasi Matapelajaran PSB Helper");
request.setAttribute("nuiPageType", "finance");
request.setAttribute("nuiPageDescription", "Keuangan untuk eSchool. Transaksi, status, rekonsiliasi, detail, dan audit keuangan.");
request.setAttribute("nuiSourceClass", "VerifikasiMatapelajaranPSBHelper");
request.setAttribute("nuiSourcePackage", "ais.action.master.sekolah.psb");
request.setAttribute("nuiSourcePath", "src/ais/action/master/sekolah/psb/VerifikasiMatapelajaranPSBHelper.java");
request.setAttribute("nuiSourceKind", "class");
request.setAttribute("nuiSourceExtends", "");
request.setAttribute("nuiSourceImplements", "");
request.setAttribute("nuiSourceMethods", new String[]{"tampilkanVerifikasi", "onEvent", "simpanVerifikasi"});
request.setAttribute("nuiEntityCandidates", new String[]{"GelombangPendaftaranPsbPunyaMatapelajaran", "MatapelajaranSekolah", "CalonSiswaPunyaVerifikasiMatapelajaran"});
%>
<jsp:include page="/WEB-INF/new/_shared/ui/page.jsp" />
