<%-- @generated by generate_new_jsp_scaffold.py
Source: src/ais/action/master/helper/keuangan/DownloadCicilanCalonMahasiswa.java
Generated: 2026-08-06T18:20:20Z
This JSP contains presentation metadata only. Keep business logic in Java services.
--%>
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%
request.setAttribute("nuiModule", "helper");
request.setAttribute("nuiModuleLabel", "Helper & Komponen Pendukung");
request.setAttribute("nuiPage", "keuangan/download_cicilan_calon_mahasiswa");
request.setAttribute("nuiPageTitle", "Download Cicilan Calon Mahasiswa");
request.setAttribute("nuiPageType", "finance");
request.setAttribute("nuiPageDescription", "Keuangan untuk Helper & Komponen Pendukung. Transaksi, status, rekonsiliasi, detail, dan audit keuangan.");
request.setAttribute("nuiSourceClass", "DownloadCicilanCalonMahasiswa");
request.setAttribute("nuiSourcePackage", "ais.action.master.helper.keuangan");
request.setAttribute("nuiSourcePath", "src/ais/action/master/helper/keuangan/DownloadCicilanCalonMahasiswa.java");
request.setAttribute("nuiSourceKind", "class");
request.setAttribute("nuiSourceExtends", "MyWindow");
request.setAttribute("nuiSourceImplements", "");
request.setAttribute("nuiSourceMethods", new String[]{"onEvent", "run"});
request.setAttribute("nuiEntityCandidates", new String[]{"CicilanPembayaran"});
%>
<jsp:include page="/WEB-INF/new/_shared/ui/page.jsp" />
