<%-- @generated by generate_new_jsp_scaffold.py
Source: src/ais/action/master/employ/util/JabatanFungsionalTreeModel.java
Generated: 2026-08-06T18:20:20Z
This JSP contains presentation metadata only. Keep business logic in Java services.
--%>
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%
request.setAttribute("nuiModule", "employ");
request.setAttribute("nuiModuleLabel", "SDM & Kepegawaian");
request.setAttribute("nuiPage", "util/jabatan_fungsional_tree_model");
request.setAttribute("nuiPageTitle", "Jabatan Fungsional Tree Model");
request.setAttribute("nuiPageType", "list");
request.setAttribute("nuiPageDescription", "Pendataan untuk SDM & Kepegawaian. Daftar data, pencarian, filter, detail, impor, dan ekspor.");
request.setAttribute("nuiSourceClass", "JabatanFungsionalTreeModel");
request.setAttribute("nuiSourcePackage", "ais.action.master.employ.util");
request.setAttribute("nuiSourcePath", "src/ais/action/master/employ/util/JabatanFungsionalTreeModel.java");
request.setAttribute("nuiSourceKind", "class");
request.setAttribute("nuiSourceExtends", "AbstractTreeModel");
request.setAttribute("nuiSourceImplements", "");
request.setAttribute("nuiSourceMethods", new String[]{"getChildren", "generateAllChildren", "getChild", "getChildCount", "deleteChilds", "isLeaf", "getParentCount", "getParentSet", "getChildsSet", "getIndexOfChild"});
request.setAttribute("nuiLegacyRefs", new String[]{});
request.setAttribute("nuiEntityCandidates", new String[]{"JabatanFungsional"});
%>
<jsp:include page="/WEB-INF/new/_shared/ui/page.jsp" />
