package ais.action.master.sosial;

import java.math.BigDecimal; import java.util.Arrays; import java.util.List; import javax.servlet.http.HttpServletRequest;
import org.hibernate.Criteria; import org.hibernate.Session; import org.hibernate.criterion.*; import org.zkoss.zk.ui.Component; import org.zkoss.zk.ui.Executions; import org.zkoss.zk.ui.Page; import org.zkoss.zk.ui.event.Event; import org.zkoss.zk.ui.event.EventListener; import org.zkoss.zk.ui.metainfo.ComponentInfo; import org.zkoss.zk.ui.util.GenericAutowireComposer; import org.zkoss.zul.*;
import ais.action.master.sosial.helper.*; import ais.common.*; import ais.database.hibernate.HibernateUtil; import ais.database.model.GeneralValueObject; import ais.database.model.sosial.*; import ais.ui.util.*;

/** Dashboard + CRUD draft transaksi untuk menu Zakat, Infaq, Shodaqoh, dan Donasi. */
public class SosialTransaksiAction extends GenericAutowireComposer implements DataCriteria,DataSearchDefault,DataInitDefault {
 private static final long serialVersionUID=1L; private MyWindow addWindow; private Paging paging; private MyGrid grid; private Textbox searchnomor,searchdonatur; private Combobox searchstatus; private Label dashboardJudul,totalTransaksi,totalNominal,totalPending,totalPaid; private MyToolbarbuttonConfig add; private String kategori; private SocialRequestContext context; private TransaksiDonasi entity; private Combobox fundType; private Textbox donorName,donorContact,prayer; private Decimalbox amount; private Checkbox anonymous; private boolean edit,delete;
 public ComponentInfo doBeforeCompose(Page p,Component parent,ComponentInfo i){Common.doCheckSecurity();return super.doBeforeCompose(p,parent,i);}
 public void doAfterCompose(Component comp)throws Exception{super.doAfterCompose(comp);Common.initLaguage();kategori=String.valueOf(comp.getAttribute("kategoriSosial"));if(kategori==null||!kategori.matches("ZAKAT|INFAQ|SHODAQOH|DONASI"))throw new IllegalArgumentException("Kategori sosial tidak valid.");context=currentContext();new SocialPrivilegeGuard().require(context,SocialPrivilegeGuard.VIEW);dashboardJudul.setValue("Dashboard "+title());edit=CommonPrivilages.checkPrevilages(CommonPrivilages.UPDATE);delete=CommonPrivilages.checkPrevilages(CommonPrivilages.DELETE);add.setVisible(CommonPrivilages.checkPrevilages(CommonPrivilages.CREATE));searchstatus.appendItem("Semua").setValue("");for(String s:new String[]{"DRAFT","PENDING_PAYMENT","ALLOCATED","CANCELLED"})searchstatus.appendItem(s).setValue(s);searchstatus.setSelectedIndex(0);Common.initPaging(paging,new EventListener(){public void onEvent(Event e)throws Exception{onSearchDefault(null);}});onSearchDefault(null);}
 public void onAdd(Event e)throws Exception{new SocialPrivilegeGuard().require(context,SocialPrivilegeGuard.OPERATE);init(new TransaksiDonasi());}
 public void init(GeneralValueObject value)throws Exception{entity=(TransaksiDonasi)value;if(entity.getId()!=null&&!"DRAFT".equals(entity.getStatus())){MyMessageboxConfig.show("Hanya transaksi DRAFT yang boleh diubah.","Peringatan",MyMessageboxConfig.OK,MyMessageboxConfig.INFORMATION);return;}buildForm();addWindow.setVisible(true);addWindow.onModal();}
 private void buildForm(){addWindow.setTitle(entity.getId()==null?"Tambah "+title():"Ubah "+title());Common.clear(addWindow);Grid form=new MyGrid();form.setWidth("100%");Rows rows=new Rows();rows.setParent(form);row(rows,"Jenis Dana",fundType=new Combobox());fundType.setReadonly(true);loadFunds(fundType,entity.getFundType());row(rows,"Nama Donatur",donorName=new Textbox(entity.getDonorNameSnapshot()));row(rows,"Email/WhatsApp",donorContact=new Textbox(entity.getDonorContactSnapshot()));row(rows,"Nominal",amount=new Decimalbox(entity.getGrossDonationAmount()));row(rows,"Anonim",anonymous=new Checkbox("Tampilkan sebagai Hamba Allah"));anonymous.setChecked(entity.getAnonymous());row(rows,"Doa/Pesan",prayer=new Textbox(entity.getPrayer()));prayer.setRows(3);for(Component c:Arrays.asList(fundType,donorName,donorContact,amount,prayer))((org.zkoss.zk.ui.HtmlBasedComponent)c).setWidth("95%");Toolbar bar=new Toolbar();MyToolbarbuttonConfig cancel=new MyToolbarbuttonConfig("Batal","/img/cancel.gif"),save=new MyToolbarbuttonConfig("Simpan","/img/save.gif");cancel.addEventListener("onClick",new EventListener(){public void onEvent(Event e){addWindow.setVisible(false);}});save.addEventListener("onClick",new EventListener(){public void onEvent(Event e)throws Exception{if(onSave(e)){addWindow.setVisible(false);onSearchDefault(null);}}});cancel.setParent(bar);save.setParent(bar);Vbox box=new Vbox();box.setWidth("100%");form.setParent(box);bar.setParent(box);box.setParent(addWindow);}
 private void row(Rows rows,String label,Component input){Row row=new MyFormRow();row.appendChild(new MyLabelConfig(label+" *"));row.appendChild(input);row.setParent(rows);}
 @SuppressWarnings("unchecked") private void loadFunds(Combobox combo,JenisDanaSosial selected){Session s=HibernateUtil.currentSession();List<JenisDanaSosial> list=addFundFilter(s.createCriteria(JenisDanaSosial.class),"kode").add(Restrictions.eq("publicActive",Boolean.TRUE)).addOrder(Order.asc("nama")).list();for(JenisDanaSosial f:list){Comboitem i=combo.appendItem(f.getNama());i.setValue(f);if(selected!=null&&selected.getId().equals(f.getId()))combo.setSelectedItem(i);}if(combo.getSelectedItem()==null&&combo.getItemCount()>0)combo.setSelectedIndex(0);}
 public boolean onSave(Event e)throws Exception{new SocialPrivilegeGuard().require(context,SocialPrivilegeGuard.OPERATE);if(fundType.getSelectedItem()==null||empty(donorName.getValue())||amount.getValue()==null||amount.getValue().signum()<=0){MyMessageboxConfig.show("Jenis dana, nama donatur, dan nominal wajib diisi.","Peringatan",MyMessageboxConfig.OK,MyMessageboxConfig.INFORMATION);return false;}Session s=HibernateUtil.currentSession();if(entity.getId()!=null){entity=(TransaksiDonasi)s.get(TransaksiDonasi.class,entity.getId());if(entity==null||!context.getTenantKey().equals(entity.getTenantKey()))throw new SecurityException("Transaksi tidak ditemukan pada tenant ini.");if(!"DRAFT".equals(entity.getStatus()))throw new SecurityException("Transaksi bukan DRAFT.");}JenisDanaSosial fund=(JenisDanaSosial)fundType.getSelectedItem().getValue();if(!context.getTenantKey().equals(fund.getTenantKey()))throw new SecurityException("Jenis dana berbeda tenant.");if(fund.getSosialChannel()==null||!context.getTenantKey().equals(fund.getSosialChannel().getTenantKey()))throw new IllegalStateException("Jenis dana belum memiliki SosialChannel yang valid.");if(entity.getId()==null){entity.setTenantKey(context.getTenantKey());entity.setTransactionNumber(SocialSecurity.reference("SOCMAN"));entity.setIdempotencyKey(SocialSecurity.reference("ZKOSS"));entity.setStatus("DRAFT");entity.setSourceChannel("ZKOSS_ADMIN");entity.setCurrency("IDR");entity.setPlatformContribution(BigDecimal.ZERO);entity.setGatewayFee(BigDecimal.ZERO);entity.setReceiptStatus("NOT_AVAILABLE");entity.setAccountingStatus("NOT_POSTED");entity.setCreatedBy(context.getActorId());}entity.setFundType(fund);entity.setSosialChannel(fund.getSosialChannel());entity.setDonorNameSnapshot(donorName.getValue());entity.setDonorContactSnapshot(donorContact.getValue());entity.setAnonymous(Boolean.valueOf(anonymous.isChecked()));entity.setPublicName(anonymous.isChecked()?"Hamba Allah":donorName.getValue());entity.setGrossDonationAmount(amount.getValue().setScale(2,BigDecimal.ROUND_HALF_UP));entity.setTotalPayable(entity.getGrossDonationAmount());entity.setPrayer(prayer.getValue());entity.setPublicPrayer(Boolean.FALSE);entity.setUpdatedBy(context.getActorId());Common.refreshSaveOrUpdate(s,entity);return true;}
 public Criteria initCriteria(boolean order){Session s=HibernateUtil.currentSession();Criteria c=addFundFilter(s.createCriteria(TransaksiDonasi.class).createAlias("fundType","f"),"f.kode").add(Restrictions.eq("tenantKey",context.getTenantKey())).add(empty(searchnomor.getValue())?Restrictions.sqlRestriction("1=1"):Restrictions.ilike("transactionNumber",searchnomor.getValue().trim(),MatchMode.ANYWHERE)).add(empty(searchdonatur.getValue())?Restrictions.sqlRestriction("1=1"):Restrictions.ilike("donorNameSnapshot",searchdonatur.getValue().trim(),MatchMode.ANYWHERE));if(searchstatus.getSelectedItem()!=null&&!empty(String.valueOf(searchstatus.getSelectedItem().getValue())))c.add(Restrictions.eq("status",String.valueOf(searchstatus.getSelectedItem().getValue())));if(order)c.addOrder(Order.desc("createdAt"));return c;}
 private Criteria addFundFilter(Criteria c,String property){if("INFAQ".equals(kategori))return c.add(Restrictions.or(Restrictions.ilike(property,"%INFAQ%"),Restrictions.ilike(property,"%INFAK%")));if("SHODAQOH".equals(kategori))return c.add(Restrictions.or(Restrictions.ilike(property,"%SHODAQ%"),Restrictions.ilike(property,"%SEDEKAH%")));return c.add(Restrictions.ilike(property,"%"+kategori+"%"));}
 @SuppressWarnings("unchecked") public void onSearchDefault(Event e){Common.initPaging(initCriteria(false),paging);List<TransaksiDonasi> rows=initCriteria(true).setMaxResults(Common.ROWS_COUNT_ON_PAGE).setFirstResult(Common.ROWS_COUNT_ON_PAGE*(paging==null?0:paging.getActivePage())).list();grid.setRowRenderer(new MyRowRenderer(){public void render(Row row,Object value)throws Exception{final TransaksiDonasi d=(TransaksiDonasi)value;new Label(d.getTransactionNumber()).setParent(row);new Label(d.getDonorNameSnapshot()).setParent(row);new Label(d.getFundType()==null?"":d.getFundType().getNama()).setParent(row);new Label(money(d.getGrossDonationAmount())).setParent(row);new Label(d.getStatus()).setParent(row);new Label(d.getCreatedAt()==null?"":Common.dateFormat85.get().format(d.getCreatedAt())).setParent(row);if("DRAFT".equals(d.getStatus()))Common.copyEditDeleteButtons(edit,delete,d,SosialTransaksiAction.this).setParent(row);else new Label("Terkunci").setParent(row);}});grid.setModelCheckMobile(new SimpleListModel(rows));refreshDashboard();}
 private void refreshDashboard(){Session s=HibernateUtil.currentSession();Criteria base=addFundFilter(s.createCriteria(TransaksiDonasi.class).createAlias("fundType","f"),"f.kode").add(Restrictions.eq("tenantKey",context.getTenantKey()));Number count=(Number)base.setProjection(Projections.rowCount()).uniqueResult();Criteria sum=addFundFilter(s.createCriteria(TransaksiDonasi.class).createAlias("fundType","f"),"f.kode").add(Restrictions.eq("tenantKey",context.getTenantKey())).add(Restrictions.in("status",new String[]{"ALLOCATED","PAID"})).setProjection(Projections.sum("grossDonationAmount"));BigDecimal nominal=(BigDecimal)sum.uniqueResult();totalTransaksi.setValue(String.valueOf(count==null?0:count.longValue()));totalNominal.setValue(money(nominal));totalPending.setValue(String.valueOf(countStatus(s,"PENDING_PAYMENT")));totalPaid.setValue(String.valueOf(countStatus(s,"ALLOCATED")));}
 private long countStatus(Session s,String status){Number n=(Number)addFundFilter(s.createCriteria(TransaksiDonasi.class).createAlias("fundType","f"),"f.kode").add(Restrictions.eq("tenantKey",context.getTenantKey())).add(Restrictions.eq("status",status)).setProjection(Projections.rowCount()).uniqueResult();return n==null?0:n.longValue();}
 private SocialRequestContext currentContext(){return SocialRequestContext.from((HttpServletRequest)Executions.getCurrent().getNativeRequest());} private String title(){return "SHODAQOH".equals(kategori)?"Shodaqoh":kategori.substring(0,1)+kategori.substring(1).toLowerCase();} private String money(BigDecimal v){return "Rp "+Common.numberFormat2.get().format(v==null?BigDecimal.ZERO:v);} private boolean empty(String v){return v==null||v.trim().isEmpty();}
}
