package ais.database.model.akunting;

// Generated Apr 16, 2010 2:27:16 PM by Hibernate Tools 3.2.4.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.Iterator;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.Session;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;
import org.hibernate.annotations.NotFound;
import org.hibernate.annotations.NotFoundAction;
import org.hibernate.criterion.Restrictions;
import org.hibernate.envers.Audited;
import org.json.JSONObject;

import ais.common.Common;
import ais.database.hibernate.HibernateUtil;
import ais.database.model.Bank;
import ais.database.model.Konfigurasi;
import ais.database.model.payroll.PembayaranGaji;
import ais.database.model.rab.SatuanKerja;
import ais.database.model.sop.DataSop;
import ais.database.model.sop.DisposisiSop;
import ais.ui.util.WaktuUtil;

/**
 * Bank generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Entity(
    dynamicInsert = true,
    dynamicUpdate = true
)
@Audited
@Table(schema = "akunting", name = "standing_instruction")
public class StandingInstruction extends DataSop {

	/** 
	 * 
	 */
	private static final long serialVersionUID = 2463821577548439808L;
	private Long id;
	private String oleh;
	private String olehId;

	public String getOlehId() {
		return olehId;
	}

	public void setOlehId(String olehId) {
		if (olehId == null || olehId.trim().isEmpty()) {
			return;
		}
		this.olehId = olehId;
	}

	public void setOleh(String oleh) {
		if (oleh == null || oleh.trim().isEmpty()) {
			return;
		}
		this.oleh = oleh;
	}

	public String getOleh() {
		return oleh;
	}

	@javax.persistence.PreUpdate protected void onUpdate() { ais.database.hibernate.AuditTimestampInterceptor.ubah(this);}     private Date tanggal_dirubah = ais.ui.util.WaktuUtil.getDate();

	public void setTanggal_dirubah(Date tanggal_dirubah) {
		this.tanggal_dirubah = tanggal_dirubah;
	}

	@Temporal(TemporalType.TIMESTAMP)
	public Date getTanggal_dirubah() {
		return tanggal_dirubah;
	}

	public String toString() {
		return id + "-" + nama;
	}

	private String kode;
	private String nama;
	private String keterangan;
	private Boolean aktif;
	private Double nominal;

	private String transferVia;

	private Bank bankSumber;
	private Akun akun;
	private String atasNamaSumber;
	private String noRekSumber;

	// reference
	private PembayaranGaji pembayaranGaji;
	private Date waktu;
	private SatuanKerja satuanKerja;

	public StandingInstruction() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", insertable = false, unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getKode() {
		try {
			if (getPembayaranGaji() != null) {
				kode = "GAJI-" + getPembayaranGaji().getId();
			}

		} catch (Exception e) { ais.common.ErrorAuditUtil.record(e, "auto-audit(empty-catch) src/ais/database/model/akunting/StandingInstruction.java:136");
			// TODO: handle exception
		}

		return kode;
	}

	public void setKode(String kode) {
		this.kode = kode;
	}

	@Column(name = "nama", nullable = false, columnDefinition = "text")
	public String getNama() {
		return this.nama == null ? null : this.nama.trim();
	}

	public void setNama(String nama) {
		this.nama = nama;
	}

	@Column(name = "keterangan", nullable = true, columnDefinition = "text")
	public String getKeterangan() {
		return this.keterangan;
	}

	public void setKeterangan(String keterangan) {
		this.keterangan = keterangan;
	}

	public Boolean getAktif() {
		return aktif == null ? true : aktif;
	}

	/** Hitung status bisnis secara eksplisit tanpa membuat getter persistence bermutasi. */
	public Boolean hitungAktifDariStatus() {
		DisposisiSop currentDisposisi = getDisposisiSop();
		if (currentDisposisi != null && !currentDisposisi.getAktif()) return false;
		if (currentDisposisi != null && currentDisposisi.getDisposisiEnd() != null
				&& currentDisposisi.getDisposisiEnd().getAlurSop() != null
				&& currentDisposisi.getDisposisiEnd().getAlurSop().getPenolakanAdaDiSini()) return false;
		if (getPembayaranGaji() != null) return pembayaranGaji.getDisetujuiOleh() != null;
		return getAktif();
	}

	public void setAktif(Boolean aktif) {
		this.aktif = aktif;
	}

	public Double getNominal() {

		if (getPembayaranGaji() != null && getPembayaranGaji().getNilai() != null) {
			nominal = getPembayaranGaji().getNilai();
		}

		return nominal == null ? 0.0 : nominal;
	}

	public void setNominal(Double nominal) {
		this.nominal = nominal;
	}

	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY)
	@JoinColumn(name = "bank_sumber_id", nullable = true)
	public Bank getBankSumber() {
		bankSumber = check(bankSumber);

		if (getPembayaranGaji() != null && getPembayaranGaji().getCaraPembayaranGaji() != null
				&& getPembayaranGaji().getCaraPembayaranGaji().getAkun() != null
				&& getPembayaranGaji().getCaraPembayaranGaji().getAkun().getBank() != null) {
			bankSumber = getPembayaranGaji().getCaraPembayaranGaji().getAkun().getBank();
		}

		return bankSumber;
	}

	public void setBankSumber(Bank bankSumber) {
		this.bankSumber = bankSumber;
	}

	public String getAtasNamaSumber() {

		if (getPembayaranGaji() != null && getPembayaranGaji().getCaraPembayaranGaji() != null
				&& getPembayaranGaji().getCaraPembayaranGaji().getAkun() != null) {
			atasNamaSumber = getPembayaranGaji().getCaraPembayaranGaji().getAkun().getAtasNama();
		}

		return atasNamaSumber;
	}

	public void setAtasNamaSumber(String atasNamaSumber) {
		this.atasNamaSumber = atasNamaSumber;
	}

	public String getNoRekSumber() {

		if (getPembayaranGaji() != null && getPembayaranGaji().getCaraPembayaranGaji() != null
				&& getPembayaranGaji().getCaraPembayaranGaji().getAkun() != null) {
			noRekSumber = getPembayaranGaji().getCaraPembayaranGaji().getAkun().getNoRek();
		}

		return noRekSumber == null || noRekSumber.isEmpty() ? null : noRekSumber.trim();
	}

	public void setNoRekSumber(String noRekSumber) {
		this.noRekSumber = noRekSumber;
	}

	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE })
	@NotFound(action = NotFoundAction.IGNORE)
	@Fetch(FetchMode.SELECT)
	@JoinColumn(name = "pembayaran_gaji", nullable = true)
	public PembayaranGaji getPembayaranGaji() {
		return pembayaranGaji;
	}

	public void setPembayaranGaji(PembayaranGaji pembayaranGaji) {
		this.pembayaranGaji = pembayaranGaji;
	}

	private String kodeUnik = null;
	private DisposisiSop disposisiSop;
	private String prosesStanding;

	@Column(unique = true)
	public String getKodeUnik() {
		if (kodeUnik == null && getId() != null) {
			kodeUnik = Common.getGeneratedBarCode() + "_" + getId();
		}
		return kodeUnik;
	}

	public void setKodeUnik(String kodeUnik) {
		this.kodeUnik = kodeUnik;
	}

	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY)
	@JoinColumn(name = "disposisi_sop", nullable = true)
	public DisposisiSop getDisposisiSop() {
		disposisiSop = check(disposisiSop);

		if (getPembayaranGaji() != null && getPembayaranGaji().getDisposisiSop() != null) {
			disposisiSop = getPembayaranGaji().getDisposisiSop();
		}

		return disposisiSop;
	}

	public void setDisposisiSop(DisposisiSop disposisiSop) {
		if (disposisiSop == null || disposisiSop.getId() == null) {
			return;
		}
		this.disposisiSop = (this.disposisiSop != null && (disposisiSop == null || disposisiSop.getId() == null))
				? this.disposisiSop
				: disposisiSop;
	}

	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY)
	@JoinColumn(name = "akun", nullable = true)
	public Akun getAkun() {
		akun = check(akun);

		if (getPembayaranGaji() != null && getPembayaranGaji().getCaraPembayaranGaji() != null
				&& getPembayaranGaji().getCaraPembayaranGaji().getAkun() != null
				&& getPembayaranGaji().getCaraPembayaranGaji().getAkun() != null) {
			akun = getPembayaranGaji().getCaraPembayaranGaji().getAkun();
		}

		return akun;
	}

	public void setAkun(Akun akun) {
		this.akun = akun;
	}

	@Temporal(TemporalType.TIMESTAMP)
	public Date getWaktu() {

		if (getPembayaranGaji() != null) {
			waktu = getPembayaranGaji().getWaktuBayar();
		}

		return waktu == null ? WaktuUtil.getDate() : waktu;
	}

	public void setWaktu(Date waktu) {
		this.waktu = waktu;
	}

	public SatuanKerja ambilSatuanKerja() {
		SatuanKerja satuanKerja = null;

		if (getPembayaranGaji() != null) {
			satuanKerja = getPembayaranGaji().getSatuanKerja();
		}

		return satuanKerja;
	}

	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY)
	@JoinColumn(name = "satuan_kerja", nullable = true)
	public SatuanKerja getSatuanKerja() {
		satuanKerja = ambilSatuanKerja();
		return satuanKerja;
	}

	public void setSatuanKerja(SatuanKerja satuanKerja) {
		this.satuanKerja = satuanKerja;
	}

	public static void simpanPembayaranGajiPunyaPegawai(PembayaranGaji pembayaranGaji) {
		if (Common.bolehKonfigurasi("gaji_masuk_standing_instruction_baru")) {
			if (pembayaranGaji == null || pembayaranGaji.getId() == null) {
				return;
			}
			if (pembayaranGaji != null && pembayaranGaji.getStandingInstruction() != null) {
				return;
			}

			Session session = HibernateUtil.currentNativeSession();
			StandingInstruction standingInstruction = (StandingInstruction) session
					.createCriteria(StandingInstruction.class).add(Restrictions.eq("pembayaranGaji", pembayaranGaji))
					.setMaxResults(1).uniqueResult();
			if (standingInstruction == null) {
				standingInstruction = new StandingInstruction();
				standingInstruction.setPembayaranGaji(pembayaranGaji);
				standingInstruction.setNama("Pembayaran gaji " + pembayaranGaji.getCaraPembayaranGaji().getNama()
						+ " bulan " + pembayaranGaji.getBulan() + " tahun " + pembayaranGaji.getTahun());

				session.getTransaction().begin();
				Common.refreshSaveOrUpdate(session, standingInstruction);
				session.getTransaction().commit();

				pembayaranGaji.setStandingInstruction(standingInstruction);

				session.getTransaction().begin();
				Common.refreshSaveOrUpdate(session, pembayaranGaji);
				session.getTransaction().commit();
			}

			// session.disconnect();
			if (session.isOpen()) {session.disconnect();session.close();}
			HibernateUtil.closeSession();
		}
	}

	@Column(columnDefinition = "text")
	public String getTransferVia() {
		return transferVia == null || transferVia.trim().isEmpty() ? new JSONObject().toString() : transferVia;
	}

	public void setTransferVia(String transferVia) {
		this.transferVia = transferVia;
	}

	@SuppressWarnings("unchecked")
	@Column(columnDefinition = "text")
	public String getProsesStanding() {
		prosesStanding = "";
		try {
			JSONObject jsonObjectTransfer = new JSONObject(getTransferVia());
			Iterator<String> i = jsonObjectTransfer.keys();
			while (i.hasNext()) {
				try {
					String key = i.next();
					JSONObject jsonObject = jsonObjectTransfer.getJSONObject(key);
					if (!jsonObject.isNull("si")) {
						prosesStanding += prosesStanding.isEmpty() ? jsonObject.get("si").toString()
								: "," + jsonObject.get("si");
					}
				} catch (Exception e) { ais.common.ErrorAuditUtil.record(e, "auto-audit(empty-catch) src/ais/database/model/akunting/StandingInstruction.java:411");
					// TODO: handle exception
				}
			}
			jsonObjectTransfer = null;
			i = null;
			prosesStanding = "," + prosesStanding + ",";
		} catch (Exception e) { ais.common.ErrorAuditUtil.record(e, "auto-audit(empty-catch) src/ais/database/model/akunting/StandingInstruction.java:418");
			// TODO: handle exception
		}

//		prosesStanding = (prosesStanding == null || prosesStanding.trim().equalsIgnoreCase(",") ? ""
//				: "," + prosesStanding.trim() + ",").replaceAll(",,", ",").replaceAll(",,", ",").replaceAll(",,", ",");
//
//		if (prosesStanding.equals(",")) {
//			prosesStanding = "";
//		} else if (prosesStanding.equals(",,")) {
//			prosesStanding = "";
//		} else if (prosesStanding.equals(",,,")) {
//			prosesStanding = "";
//		}
		return prosesStanding == null || prosesStanding.trim().equals(",,") ? "" : prosesStanding.trim();
	}

	public void setProsesStanding(String prosesStanding) {
		this.prosesStanding = prosesStanding;
	}
}
