<%-- @generated by generate_new_jsp_scaffold.py
Source: src/ais/action/master/KonfigurasiNewAction.java
Generated: 2026-08-06T18:20:20Z
Safe service-adapter scaffold. Implement data access in a Java service layer, not directly in this JSP.
--%>
<%@ page language="java" contentType="application/json; charset=UTF-8" pageEncoding="UTF-8" %>
<%
request.setAttribute("nuiServiceModule", "root");
request.setAttribute("nuiServicePage", "konfigurasi_new");
request.setAttribute("nuiServiceTitle", "Konfigurasi New");
request.setAttribute("nuiServiceType", "settings");
request.setAttribute("nuiServiceSourceClass", "KonfigurasiNewAction");
request.setAttribute("nuiServiceSourcePackage", "ais.action.master");
request.setAttribute("nuiServiceSourcePath", "src/ais/action/master/KonfigurasiNewAction.java");
request.setAttribute("nuiServiceMethods", new String[]{"onDownloadFileAutoBackup", "onBackupLog", "doBeforeCompose", "doAfterCompose", "onEvent", "doAfterComposeOri", "onSearchDefault", "accept", "run", "createRowNilaiProgramDanJurusan", "createButtonLihat", "createButtonLihatProgramJurusan", "createRowNilai", "displayBackup"});
request.setAttribute("nuiServiceLegacyRefs", new String[]{"/pages/master/download_auto_backup_action.zul", "/pages/master/backup_log.zul", "Tampilkan tombol menuju tampilan full HTML/JSP pada index2.zul", "Tampilkan tombol kembali ke tampilan lama pada index2.zul", "Label tombol tampilan full HTML/JSP di index2.zul", "Label tombol tampilan lama di index2.zul", "Label judul menu samping di index2.zul", "Label tab utama/home di index2.zul", "Tampilkan shortcut modul utama pada header index2.zul", "/WEB-INF/baru/modul/vendor/panduan_pendaftaran.jsp", "/WEB-INF/baru/modul/vendor/syarat_ketentuan.jsp", "/WEB-INF/baru/modul/vendor/kebijakan_privasi.jsp", "/WEB-INF/baru/modul/vendor/bantuan.jsp", "/WEB-INF/baru/modul/karir/panduan_pendaftaran.jsp", "/WEB-INF/baru/modul/karir/syarat_ketentuan.jsp", "/WEB-INF/baru/modul/karir/kebijakan_privasi.jsp", "/WEB-INF/baru/modul/karir/bantuan.jsp"});
request.setAttribute("nuiServiceEntities", new String[]{"Jurusan", "ParameterTambahan", "DefaultJenisParsingReconsile", "LampiranLain", "PertemuanFileContent", "TugasFileContent", "FotoBiodataCalonMahasiswa", "FotoMahasiswa", "FotoDosen", "FotoPegawai", "StraightLineNoiseProducer", "CurvedLineNoiseProducer", "FishEyeGimpyRenderer", "BlockGimpyRenderer", "DropShadowGimpyRenderer", "RippleGimpyRenderer", "ShearGimpyRenderer", "FlatColorBackgroundProducer", "GradiatedBackgroundProducer", "SquigglesBackgroundProducer", "TransparentBackgroundProducer", "DefaultTextProducer", "FiveLetterFirstNameTextProducer", "ChineseTextProducer", "DefaultWordRenderer", "ColoredEdgesWordRenderer", "Tbmrole", "Konfigurasi", "PeminjamanPengadaanItemDetail", "KembaliPengadaanItemDetail"});
%>
<jsp:include page="/WEB-INF/new/_shared/services/dispatcher.jsp" />
