<%-- @generated by generate_new_jsp_scaffold.py
Source: src/ais/action/master/MenuAction.java
Generated: 2026-08-06T18:20:20Z
Safe service-adapter scaffold. Implement data access in a Java service layer, not directly in this JSP.
--%>
<%@ page language="java" contentType="application/json; charset=UTF-8" pageEncoding="UTF-8" %>
<%
request.setAttribute("nuiServiceModule", "root");
request.setAttribute("nuiServicePage", "menu");
request.setAttribute("nuiServiceTitle", "Menu");
request.setAttribute("nuiServiceType", "list");
request.setAttribute("nuiServiceSourceClass", "MenuAction");
request.setAttribute("nuiServiceSourcePackage", "ais.action.master");
request.setAttribute("nuiServiceSourcePath", "src/ais/action/master/MenuAction.java");
request.setAttribute("nuiServiceMethods", new String[]{"doBeforeCompose", "doAfterCompose", "onEvent", "render", "onAdd", "init", "onSave", "initCriteria", "onSearchDefault", "checkId"});
request.setAttribute("nuiServiceEntities", new String[]{"Menu"});
%>
<jsp:include page="/WEB-INF/new/_shared/services/dispatcher.jsp" />
