<%-- @generated by generate_new_jsp_scaffold.py
Source: src/ais/action/master/TampilanPengumumanAkademisAction.java
Generated: 2026-08-06T18:20:20Z
Safe service-adapter scaffold. Implement data access in a Java service layer, not directly in this JSP.
--%>
<%@ page language="java" contentType="application/json; charset=UTF-8" pageEncoding="UTF-8" %>
<%
request.setAttribute("nuiServiceModule", "root");
request.setAttribute("nuiServicePage", "tampilan_pengumuman_akademis");
request.setAttribute("nuiServiceTitle", "Tampilan Pengumuman Akademis");
request.setAttribute("nuiServiceType", "list");
request.setAttribute("nuiServiceSourceClass", "TampilanPengumumanAkademisAction");
request.setAttribute("nuiServiceSourcePackage", "ais.action.master");
request.setAttribute("nuiServiceSourcePath", "src/ais/action/master/TampilanPengumumanAkademisAction.java");
request.setAttribute("nuiServiceMethods", new String[]{"doBeforeCompose", "doAfterCompose", "onEvent", "createMenu", "loadData", "prosess", "sebagaiKelompok", "sebagaiKelompokPmb", "sebagaiALumni", "tampilGelombang", "tampil", "initCriteriaStatic", "onSearchDefault", "setReadonly", "getReadonly"});
request.setAttribute("nuiServiceEntities", new String[]{"PengumumanAkademis", "CalonSiswa", "BiodataCalonMahasiswa", "ParameterTambahanPaket", "ParameterTambahan", "RuangPaketPMB", "GelombangPendaftaran", "JenisSeleksi", "LampiranLain", "GelombangPendaftaranPegawai", "ParameterTambahanGelombangPendaftaranPsb", "PembayaranSiswaDetail", "PengaturanBiaya", "GelombangPendaftaranPsb"});
%>
<jsp:include page="/WEB-INF/new/_shared/services/dispatcher.jsp" />
