<%-- @generated by generate_new_jsp_scaffold.py
Source: src/ais/action/master/surat/helper/AmbilDataNomorSuratBanbox.java
Generated: 2026-08-06T18:20:20Z
This JSP contains presentation metadata only. Keep business logic in Java services.
--%>
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%
request.setAttribute("nuiModule", "surat");
request.setAttribute("nuiModuleLabel", "Surat Menyurat");
request.setAttribute("nuiPage", "helper/ambil_data_nomor_surat_banbox");
request.setAttribute("nuiPageTitle", "Ambil Data Nomor Surat Banbox");
request.setAttribute("nuiPageType", "workflow");
request.setAttribute("nuiPageDescription", "Workflow untuk Surat Menyurat. Antrian kerja, persetujuan, timeline, SLA, dan tindak lanjut.");
request.setAttribute("nuiSourceClass", "AmbilDataNomorSuratBanbox");
request.setAttribute("nuiSourcePackage", "ais.action.master.surat.helper");
request.setAttribute("nuiSourcePath", "src/ais/action/master/surat/helper/AmbilDataNomorSuratBanbox.java");
request.setAttribute("nuiSourceKind", "class");
request.setAttribute("nuiSourceExtends", "Bandbox");
request.setAttribute("nuiSourceImplements", "");
request.setAttribute("nuiSourceMethods", new String[]{"onEvent", "render", "display", "onSearchDefault", "setEventListener", "getEventListener"});
request.setAttribute("nuiEntityCandidates", new String[]{"NomorSurat", "KelompokNomorSurat", "Jurusan", "Yayasan"});
%>
<jsp:include page="/WEB-INF/new/_shared/ui/page.jsp" />
