<%-- @generated by generate_new_jsp_scaffold.py
Source: src/ais/action/master/surat/helper/FotoGambarTandaTanganPejabatHelper.java
Generated: 2026-08-06T18:20:20Z
This JSP contains presentation metadata only. Keep business logic in Java services.
--%>
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%
request.setAttribute("nuiModule", "surat");
request.setAttribute("nuiModuleLabel", "Surat Menyurat");
request.setAttribute("nuiPage", "helper/foto_gambar_tanda_tangan_pejabat_helper");
request.setAttribute("nuiPageTitle", "Foto Gambar Tanda Tangan Pejabat Helper");
request.setAttribute("nuiPageType", "workflow");
request.setAttribute("nuiPageDescription", "Workflow untuk Surat Menyurat. Antrian kerja, persetujuan, timeline, SLA, dan tindak lanjut.");
request.setAttribute("nuiSourceClass", "FotoGambarTandaTanganPejabatHelper");
request.setAttribute("nuiSourcePackage", "ais.action.master.surat.helper");
request.setAttribute("nuiSourcePath", "src/ais/action/master/surat/helper/FotoGambarTandaTanganPejabatHelper.java");
request.setAttribute("nuiSourceKind", "class");
request.setAttribute("nuiSourceExtends", "");
request.setAttribute("nuiSourceImplements", "");
request.setAttribute("nuiSourceMethods", new String[]{"initDetail", "onEvent", "initRow"});
request.setAttribute("nuiEntityCandidates", new String[]{"FotoGambarTandaTanganPejabat"});
%>
<jsp:include page="/WEB-INF/new/_shared/ui/page.jsp" />
