package ais.action.servlet;
import java.text.SimpleDateFormat;import java.util.Date;import javax.servlet.http.*;import org.json.*;
import ais.action.master.jurnal.*;import ais.common.*;import ais.common.newui.NewUiCsrfUtil;import ais.database.hibernate.HibernateUtil;import ais.database.model.Tbmuser;import ais.database.model.jurnal.PenugasanReviewerJurnal;import ais.database.model.penelitiandanpengabdian.JurnalPenelitian;import ais.database.model.repository.*;
/** Thin JSON command API; business authorization remains inside journal services. */
public final class JurnalAdminApi extends HttpServlet{
 private static final long serialVersionUID=1L;private final JurnalAuthorizationService auth=new JurnalAuthorizationService();
 protected void doGet(HttpServletRequest q,HttpServletResponse r)throws java.io.IOException{handle(q,r);}protected void doPost(HttpServletRequest q,HttpServletResponse r)throws java.io.IOException{handle(q,r);}
 private void handle(HttpServletRequest q,HttpServletResponse r)throws java.io.IOException{String trace=Long.toHexString(System.currentTimeMillis())+Integer.toHexString(System.identityHashCode(q));r.setContentType("application/json; charset=UTF-8");r.setHeader("Cache-Control","no-store");r.setHeader("X-Content-Type-Options","nosniff");r.setHeader("X-Request-Id",trace);JSONObject out=new JSONObject();try{Tbmuser user=Common.getCurrentUser(q);if(user==null)throw new SecurityException("Login diperlukan.");String action=text(q.getParameter("action"),"capabilities");if("capabilities".equals(action))capabilities(out,user,q);else{if(!"POST".equalsIgnoreCase(q.getMethod())||!NewUiCsrfUtil.isValid(q))throw new SecurityException("Token CSRF tidak valid.");command(action,q,out,user,trace);}out.put("ok",true);}catch(SecurityException e){r.setStatus(403);fail(out,"FORBIDDEN",e.getMessage());}catch(IllegalArgumentException e){r.setStatus(422);fail(out,"VALIDATION_FAILED",e.getMessage());}catch(Exception e){r.setStatus(500);fail(out,"INTERNAL_ERROR","Perintah jurnal gagal. ID: "+trace);ais.common.ErrorAuditUtil.record(e,"JurnalAdminApi:"+trace);}finally{try{r.getWriter().write(out.toString());}catch(Exception ignored){}HibernateUtil.closeSession();}}
 private void command(String a,HttpServletRequest q,JSONObject o,Tbmuser u,String trace)throws Exception{
  if("createJournal".equals(a)){JurnalPenelitian x=new JurnalAdministrationService().create(q.getParameter("tenant"),req(q,"title"),req(q,"slug"),q.getParameter("locale"),u);o.put("id",x.getId()).put("collectionId",x.getRepoCollectionId());}
  else if("updateProfiles".equals(a)){RepoCollection x=new JurnalAdministrationService().updateProfiles(id(q,"collectionId"),req(q,"metadataProfile"),req(q,"workflowProfile"),req(q,"accessPolicy"),u);o.put("id",x.getId());}
  else if("createDraft".equals(a))item(o,new JurnalWorkflowService().createDraft(id(q,"collectionId"),req(q,"title"),q.getParameter("abstract"),q.getParameter("language"),u,trace));
  else if("transition".equals(a))item(o,new JurnalWorkflowService().transition(id(q,"itemId"),optionalId(q,"version"),req(q,"target"),q.getParameter("workflowAction"),q.getParameter("comment"),u,trace));
  else if("inviteReviewer".equals(a)){PenugasanReviewerJurnal x=new JurnalWorkflowService().inviteReviewer(id(q,"itemId"),req(q,"reviewerId"),integer(q,"round",1),req(q,"anonymity"),date(q.getParameter("responseDue")),date(q.getParameter("reviewDue")),q.getParameter("formVersion"),u,trace);o.put("id",x.getId()).put("status",x.getStatus());}
  else if("respondReview".equals(a)){PenugasanReviewerJurnal x=new JurnalWorkflowService().respondInvitation(id(q,"assignmentId"),bool(q,"accept"),q.getParameter("reason"),u,trace);o.put("id",x.getId()).put("status",x.getStatus());}
  else if("submitReview".equals(a)){PenugasanReviewerJurnal x=new JurnalWorkflowService().submitReview(id(q,"assignmentId"),req(q,"responseJson"),req(q,"recommendation"),u,trace);o.put("id",x.getId()).put("status",x.getStatus());}
  else if("createIssue".equals(a))item(o,new JurnalPublicationService().createIssue(id(q,"collectionId"),req(q,"title"),optionalInt(q,"volume"),q.getParameter("number"),optionalInt(q,"year"),date(q.getParameter("scheduledAt")),u));
  else if("placeArticle".equals(a)){RepoItemRelation x=new JurnalPublicationService().placeArticle(id(q,"issueId"),id(q,"articleId"),integer(q,"sortOrder",0),u);o.put("id",x.getId());}
  else if("publishIssue".equals(a))item(o,new JurnalPublicationService().publishIssue(id(q,"issueId"),date(q.getParameter("publishAt")),u));
  else if("assignDoi".equals(a))item(o,new JurnalIdentifierService().assignDoi(id(q,"itemId"),req(q,"doi"),u));
  else if("assignUrn".equals(a))o.put("urn",new JurnalIdentifierService().assignUrn(id(q,"itemId"),req(q,"urn"),u));
  else if("preparePayment".equals(a)){ais.database.model.jurnal.LanggananJurnal x=new JurnalPaymentService().prepare(id(q,"subscriptionId"),q.getParameter("externalReference"),u);o.put("subscriptionId",x.getId()).put("externalReference",x.getExternalReference()).put("status",x.getStatus());}
  else if("settlePayment".equals(a)){ais.database.model.LogPembayaran x=new JurnalPaymentService().settle(id(q,"subscriptionId"),req(q,"externalReference"),decimal(q,"amount"),req(q,"currency"),req(q,"provider"),req(q,"providerReference"),u);o.put("paymentId",x.getId());}
  else if("failPayment".equals(a)){ais.database.model.jurnal.LanggananJurnal x=new JurnalPaymentService().markFailed(id(q,"subscriptionId"),req(q,"reason"),u);o.put("subscriptionId",x.getId()).put("status",x.getStatus());}
  else if("cancelImport".equals(a))new ais.action.master.jurnal.importer.OjsImportExecutionService().cancel(id(q,"jobId"),u);
  else throw new IllegalArgumentException("Aksi jurnal tidak dikenal.");
 }
 private void capabilities(JSONObject o,Tbmuser u,HttpServletRequest q)throws Exception{JSONArray rows=new JSONArray();for(JurnalAksesKatalog.Entri e:JurnalAksesKatalog.DAFTAR)rows.put(new JSONObject().put("key",e.kunci).put("child",e.child).put("label",e.label).put("open",auth.canMenu(u,e.kunci)).put("read",auth.canRead(u,e.kunci)));o.put("entries",rows).put("csrf",NewUiCsrfUtil.getToken(q.getSession(true)));}
 private static void item(JSONObject o,RepoItem x)throws Exception{o.put("id",x.getId()).put("status",x.getWorkflowStatus()).put("version",x.getLockVersion());}private static void fail(JSONObject o,String c,String m){try{o.put("ok",false).put("code",c).put("message",m==null?c:m);}catch(Exception ignored){}}private static String req(HttpServletRequest q,String n){String v=q.getParameter(n);if(v==null||v.trim().length()==0)throw new IllegalArgumentException(n+" wajib diisi.");return v.trim();}private static Long id(HttpServletRequest q,String n){Long v=optionalId(q,n);if(v==null)throw new IllegalArgumentException(n+" wajib diisi.");return v;}private static Long optionalId(HttpServletRequest q,String n){String v=q.getParameter(n);if(v==null||v.trim().length()==0)return null;try{return Long.valueOf(v);}catch(Exception e){throw new IllegalArgumentException(n+" tidak valid.");}}private static Integer optionalInt(HttpServletRequest q,String n){String v=q.getParameter(n);return v==null||v.trim().length()==0?null:Integer.valueOf(integer(q,n,0));}private static int integer(HttpServletRequest q,String n,int d){String v=q.getParameter(n);if(v==null||v.length()==0)return d;try{return Integer.parseInt(v);}catch(Exception e){throw new IllegalArgumentException(n+" tidak valid.");}}private static java.math.BigDecimal decimal(HttpServletRequest q,String n){try{return new java.math.BigDecimal(req(q,n));}catch(Exception e){throw new IllegalArgumentException(n+" tidak valid.");}}private static boolean bool(HttpServletRequest q,String n){return"true".equalsIgnoreCase(q.getParameter(n));}private static Date date(String v){if(v==null||v.trim().length()==0)return null;try{SimpleDateFormat f=new SimpleDateFormat("yyyy-MM-dd");f.setLenient(false);return f.parse(v);}catch(Exception e){throw new IllegalArgumentException("Tanggal tidak valid.");}}private static String text(String v,String d){return v==null||v.trim().length()==0?d:v.trim();}
}
