package ais.action.servlet;

import java.io.IOException; import javax.servlet.http.*; import org.hibernate.Session; import org.hibernate.criterion.Restrictions;
 import com.itextpdf.text.*; import com.itextpdf.text.pdf.PdfWriter;
 import ais.action.master.sosial.helper.SocialHtml; import ais.common.Common; import ais.database.hibernate.HibernateUtil; import ais.database.model.sosial.*;

/** On-demand verifiable receipt PDF; no donor contact is exposed. */
public final class SosialReceiptPdf extends HttpServlet {
 private static final long serialVersionUID=1L;
 protected void doPost(HttpServletRequest q,HttpServletResponse r)throws IOException{r.sendError(405);} protected void doGet(HttpServletRequest q,HttpServletResponse r)throws IOException{String token=q.getParameter("token");if(token==null||!token.matches("[a-f0-9]{64}")){r.sendError(400);return;}Session s=null;try{s=HibernateUtil.openSession();BuktiSetorSosial receipt=(BuktiSetorSosial)s.createCriteria(BuktiSetorSosial.class).add(Restrictions.eq("verificationToken",token)).setMaxResults(1).uniqueResult();if(receipt==null){r.sendError(404);return;}TransaksiDonasi d=receipt.getTransaction();String fund=d.getFundType().getNama();r.setContentType("application/pdf");r.setHeader("Cache-Control","private, no-store");r.setHeader("Content-Disposition","attachment; filename=\"bukti-setor-"+receipt.getReceiptNumber().replaceAll("[^A-Za-z0-9._-]","_")+".pdf\"");com.itextpdf.text.Document doc=new com.itextpdf.text.Document(PageSize.A4,48,48,52,52);PdfWriter.getInstance(doc,r.getOutputStream());doc.open();Font title=FontFactory.getFont(FontFactory.HELVETICA_BOLD,20);Font strong=FontFactory.getFont(FontFactory.HELVETICA_BOLD,12);doc.add(new Paragraph("BUKTI SETOR SOSIAL AIS",title));doc.add(new Paragraph(" "));doc.add(new Paragraph("Nomor bukti: "+receipt.getReceiptNumber(),strong));doc.add(new Paragraph("Tanggal transaksi: "+String.valueOf(d.getPaidAt()==null?d.getCreatedAt():d.getPaidAt())));doc.add(new Paragraph("Jenis dana: "+fund));doc.add(new Paragraph("Nominal dana: "+SocialHtml.money(d.getGrossDonationAmount())));doc.add(new Paragraph("Institusi: "+receipt.getTenantKey()));doc.add(new Paragraph("Status: "+(receipt.getVoided()?"VOID":"VALID")));doc.add(new Paragraph(" "));doc.add(new Paragraph("Verifikasi: "+Common.getRequestHostWithProtocol(q)+"/sosial/verifikasi-bukti/"+token));doc.add(new Paragraph("Bukti ini diterbitkan setelah pembayaran terverifikasi oleh server."));doc.close();}catch(Exception e){ais.common.ErrorAuditUtil.record(e,"SosialReceiptPdf");if(!r.isCommitted())r.sendError(500);}finally{if(s!=null)try{s.close();}catch(Exception ignored){}}}
}
