package ais.action.servlet;

import java.io.IOException; import java.math.BigDecimal; import javax.servlet.http.*; import org.hibernate.Session; import org.hibernate.Transaction; import org.json.JSONObject;
import ais.action.master.jurnal.JurnalRateLimiter; import ais.action.master.sosial.helper.*; import ais.database.hibernate.HibernateUtil; import ais.database.model.sosial.*;

public final class SosialApi extends HttpServlet {
 private static final long serialVersionUID=1L;
 protected void doGet(HttpServletRequest q,HttpServletResponse r)throws IOException{respond(q,r,false);} protected void doPost(HttpServletRequest q,HttpServletResponse r)throws IOException{respond(q,r,true);}
 private void respond(HttpServletRequest q,HttpServletResponse r,boolean mutation)throws IOException{JSONObject out=new JSONObject();String trace=SocialSecurity.reference("REQ");r.setContentType("application/json; charset=UTF-8");r.setHeader("Cache-Control","no-store");r.setHeader("X-Content-Type-Options","nosniff");r.setHeader("X-Request-Id",trace);try{if(!JurnalRateLimiter.allow("social-api",q.getRemoteAddr(),60,60000L)){r.setStatus(429);fail(out,"RATE_LIMITED","Terlalu banyak permintaan.");return;}if(mutation)SocialSecurity.requireCsrf(q);SocialRequestContext c=SocialRequestContext.from(q);String action=value(q,"action");
   if("calculate".equals(action)){requirePost(mutation);out=calculate(q,c);}else if("donation".equals(action)){requirePost(mutation);out=donation(q,c);}else if("payment".equals(action)){requirePost(mutation);out=payment(q,c);}else if("payment-status".equals(action)){out=paymentStatus(q,c);}else throw new IllegalArgumentException("Action tidak dikenal.");
  }catch(SecurityException e){r.setStatus(403);fail(out,"FORBIDDEN",e.getMessage());}catch(IllegalArgumentException e){r.setStatus(422);fail(out,"VALIDATION_FAILED",e.getMessage());}catch(IllegalStateException e){r.setStatus(409);fail(out,"NOT_READY",e.getMessage());}catch(Exception e){r.setStatus(500);fail(out,"INTERNAL_ERROR","Permintaan gagal. ID: "+trace);ais.common.ErrorAuditUtil.record(e,"SosialApi:"+trace);}finally{try{r.getWriter().write(out.toString());}catch(Exception ignored){}}
 }
 private JSONObject calculate(HttpServletRequest q,SocialRequestContext c)throws Exception{Session s=null;Transaction tx=null;try{s=HibernateUtil.openSession();tx=s.beginTransaction();JSONObject input=new JSONObject();copyNumber(q,input,"amount");copyNumber(q,input,"grossIncome");copyNumber(q,input,"deductions");copyNumber(q,input,"grams");copyNumber(q,input,"people");PerhitunganZakat x=new ZakatCalculatorService().calculateAndStore(s,c,longValue(q,"jenisZakatId"),input);tx.commit();JSONObject o=xResult(x);o.put("ok",true).put("calculationId",x.getId());return o;}catch(Exception e){if(tx!=null)try{tx.rollback();}catch(Exception ignored){}throw e;}finally{if(s!=null)try{s.close();}catch(Exception ignored){}}}
 private JSONObject donation(HttpServletRequest q,SocialRequestContext c)throws Exception{TransaksiDonasi d=new SocialDonationService().create(c,longValue(q,"fundTypeId"),optionalLong(q,"programId"),optionalLong(q,"calculationId"),decimal(q,"amount",false),decimal(q,"contribution",true),bool(q,"anonymous"),q.getParameter("name"),q.getParameter("contact"),q.getParameter("prayer"),bool(q,"publicPrayer"),value(q,"idempotencyKey"));return new JSONObject().put("ok",true).put("transactionNumber",d.getTransactionNumber()).put("status",d.getStatus()).put("nextUrl",q.getContextPath()+"/sosial/pembayaran/"+d.getTransactionNumber());}
 private JSONObject payment(HttpServletRequest q,SocialRequestContext c)throws Exception{PembayaranDonasi p=new SocialPaymentService().initiate(c,value(q,"transactionNumber"),value(q,"gatewayId"));return new JSONObject().put("ok",true).put("orderId",p.getGatewayOrderId()).put("status",p.getPaymentStatus()).put("paymentUrl",p.getPaymentUrl()).put("expiry",p.getExpiryAt()==null?JSONObject.NULL:p.getExpiryAt().getTime());}
 private JSONObject paymentStatus(HttpServletRequest q,SocialRequestContext c)throws Exception{PembayaranDonasi p=new SocialPortalService().payment(c,value(q,"transactionNumber"));if(p==null)throw new IllegalArgumentException("Pembayaran tidak ditemukan.");return new JSONObject().put("ok",true).put("status",p.getPaymentStatus()).put("paymentUrl",p.getPaymentUrl()).put("paidAt",p.getPaidAt()==null?JSONObject.NULL:p.getPaidAt().getTime()).put("expiry",p.getExpiryAt()==null?JSONObject.NULL:p.getExpiryAt().getTime());}
 private JSONObject xResult(PerhitunganZakat x)throws Exception{return new JSONObject(x.getResultJson()).put("policyVersion",x.getPolicyVersion()).put("currency",x.getCurrency());}
 private void copyNumber(HttpServletRequest q,JSONObject o,String k)throws Exception{String v=q.getParameter(k);if(v!=null&&!v.trim().isEmpty())o.put(k,new BigDecimal(v.replace(",","")));}
 private String value(HttpServletRequest q,String k){String v=q.getParameter(k);if(v==null||v.trim().isEmpty())throw new IllegalArgumentException(k+" wajib diisi.");return v.trim();}
 private Long longValue(HttpServletRequest q,String k){try{return Long.valueOf(value(q,k));}catch(Exception e){throw new IllegalArgumentException(k+" tidak valid.");}} private Long optionalLong(HttpServletRequest q,String k){String v=q.getParameter(k);if(v==null||v.trim().isEmpty())return null;try{return Long.valueOf(v);}catch(Exception e){throw new IllegalArgumentException(k+" tidak valid.");}}
 private BigDecimal decimal(HttpServletRequest q,String k,boolean optional){String v=q.getParameter(k);if((v==null||v.trim().isEmpty())&&optional)return BigDecimal.ZERO;try{return new BigDecimal(value(q,k).replace(",",""));}catch(Exception e){throw new IllegalArgumentException(k+" tidak valid.");}}
 private boolean bool(HttpServletRequest q,String k){String v=q.getParameter(k);return "true".equalsIgnoreCase(v)||"1".equals(v)||"on".equalsIgnoreCase(v);}
 private void requirePost(boolean m){if(!m)throw new IllegalArgumentException("POST diperlukan.");} private void fail(JSONObject o,String c,String m){try{o.put("ok",false).put("code",c).put("message",m==null?c:m);}catch(Exception ignored){}}
}
