<%-- @generated by generate_new_jsp_scaffold.py
Source: src/ais/action/report/kpi/LaporanItemKpi.java
Generated: 2026-08-06T18:20:20Z
Safe service-adapter scaffold. Implement data access in a Java service layer, not directly in this JSP.
--%>
<%@ page language="java" contentType="application/json; charset=UTF-8" pageEncoding="UTF-8" %>
<%
request.setAttribute("nuiServiceModule", "root/report");
request.setAttribute("nuiServicePage", "kpi/laporan_item_kpi");
request.setAttribute("nuiServiceTitle", "Laporan Item KPI");
request.setAttribute("nuiServiceType", "report");
request.setAttribute("nuiServiceSourceClass", "LaporanItemKpi");
request.setAttribute("nuiServiceSourcePackage", "ais.action.report.kpi");
request.setAttribute("nuiServiceSourcePath", "src/ais/action/report/kpi/LaporanItemKpi.java");
request.setAttribute("nuiServiceMethods", new String[]{"generateParameters", "onEvent", "onReport"});
request.setAttribute("nuiServiceLegacyRefs", new String[]{});
request.setAttribute("nuiServiceEntities", new String[]{});
%>
<jsp:include page="/WEB-INF/new/_shared/services/dispatcher.jsp" />
