<%-- @generated by generate_new_jsp_scaffold.py
Source: src/ais/action/master/payroll/LiburRutinAction.java
Generated: 2026-08-06T18:20:20Z
This JSP contains presentation metadata only. Keep business logic in Java services.
--%>
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%
request.setAttribute("nuiModule", "payroll");
request.setAttribute("nuiModuleLabel", "Penggajian");
request.setAttribute("nuiPage", "libur_rutin");
request.setAttribute("nuiPageTitle", "Libur Rutin");
request.setAttribute("nuiPageType", "finance");
request.setAttribute("nuiPageDescription", "Keuangan untuk Penggajian. Transaksi, status, rekonsiliasi, detail, dan audit keuangan.");
request.setAttribute("nuiSourceClass", "LiburRutinAction");
request.setAttribute("nuiSourcePackage", "ais.action.master.payroll");
request.setAttribute("nuiSourcePath", "src/ais/action/master/payroll/LiburRutinAction.java");
request.setAttribute("nuiSourceKind", "class");
request.setAttribute("nuiSourceExtends", "GenericAutowireComposer");
request.setAttribute("nuiSourceImplements", "");
request.setAttribute("nuiSourceMethods", new String[]{"doAfterCompose", "onEvent", "render", "onSearchDefault"});
request.setAttribute("nuiEntityCandidates", new String[]{"LiburRutin"});
%>
<jsp:include page="/WEB-INF/new/_shared/ui/page.jsp" />
