package ais.database.model.koperasi;

// Generated Apr 16, 2010 2:27:16 PM by Hibernate Tools 3.2.4.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.Session;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;
import org.hibernate.criterion.MatchMode;
import org.hibernate.criterion.Restrictions;
import org.hibernate.envers.Audited;
import org.json.JSONArray;
import org.json.JSONObject;

import ais.common.Common;
import ais.common.ConstantValues;
import ais.database.model.GeneralValueObject;
import ais.database.model.Tbmuser;
import ais.database.model.akunting.PostingHistory;
import ais.database.model.asset.Lokasi;
import ais.database.model.inventory.DraftPembelian;
import ais.database.model.inventory.Produk;
import ais.database.model.inventory.Toko;

/**
 * Bank generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Entity(dynamicInsert = true, dynamicUpdate = true)
@Audited
@Table(schema = "koperasi", name = "draft_pembelian_anggota_koperasi")
public class DraftPembelianAnggotaKoperasi extends GeneralValueObject {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2463821577548439808L;
	private Long id;
	private Long index;
	private String olehId;

	public String getOlehId() {
		return olehId;
	}

	public void setOlehId(String olehId) {
		if (olehId == null || olehId.trim().isEmpty()) {
			return;
		}
		this.olehId = olehId;
	}

	private String oleh;

	public String toString() {
		return kode;
	}

	public void setOleh(String oleh) {
		if (oleh == null || oleh.trim().isEmpty()) {
			return;
		}
		this.oleh = oleh;
	}

	public String getOleh() {
		return oleh;
	}

	@javax.persistence.PreUpdate
	protected void onUpdate() {
		ais.database.hibernate.AuditTimestampInterceptor.ubah(this);
	}

	private Date tanggal_dirubah = new Date();

	public void setTanggal_dirubah(Date tanggal_dirubah) {
		this.tanggal_dirubah = tanggal_dirubah;
	}

	@Temporal(TemporalType.TIMESTAMP)
	public Date getTanggal_dirubah() {
		return tanggal_dirubah;
	}

	private String kode;
	private String keterangan;
	private AnggotaKoperasi anggotaKoperasi;
	private MejaKantin mejaKantin;
	private Lokasi lokasi;
	private Date tanggalPembayaran = new Date();
	private CaraPembayaranKoperasi caraPembayaranKoperasi;
	private KodePembayaranOnline kodePembayaranOnline;
	private Double biaya = 0.0;
	private Double retur = 0.0;
	private Double diskon = 0.0;
	private Boolean diskonDalamPersen = false;
	private Double totalDiskon = 0.0;
	private Double totalCashback = 0.0;
	private Double ppn = 0.0;
	private Double hargaPpn = 0.0;
	private Toko toko;
	private Double totalBiaya = 0.0;

	private Double bayarTunai = 0.0;
	private Double bayarNonTunai = 0.0;
	private Double kembalian = 0.0;

	private Double bayar = 0.0;

	private Tbmuser tbmuser;

	private String kasirLoginNama;

	private String namaMesin;

	private PembelianAnggotaKoperasi lunas;
	
	private PostingHistory postingHistory;

	public JSONArray simpanRinci(Session session, JSONArray transaksi, String kodeUnik, Date currentWaktu, Toko toko,
			KodePembayaranOnline kodePembayaranOnline) {
		JSONArray arrayTransaksi = new JSONArray();
		for (int i = 0; i < transaksi.length(); i++) {
			try {
				JSONObject objectTransaksi = transaksi.getJSONObject(i);
				String idBarang = objectTransaksi.isNull("id") ? null : objectTransaksi.get("id") + "";
				String kodeBarang = objectTransaksi.isNull("kode") ? "_" : objectTransaksi.get("kode") + "";
				String namaBarang = objectTransaksi.isNull("nama") ? "_" : objectTransaksi.get("nama") + "";
				Double hargaBarang = objectTransaksi.isNull("harga") ? 0.0
						: Double.parseDouble((objectTransaksi.get("harga") + "").trim());
				Double jumlahBarang = objectTransaksi.isNull("jumlah") ? 1.0
						: Double.parseDouble((objectTransaksi.get("jumlah") + "").trim());
				Double diskonBarang = objectTransaksi.isNull("diskon") ? 0.0
						: Double.parseDouble((objectTransaksi.get("diskon") + "").trim());
				Double cashbackBarang = objectTransaksi.isNull("cashback") ? 0.0
						: Double.parseDouble((objectTransaksi.get("cashback") + "").trim());
				Produk produk = PembelianAnggotaKoperasi.resolveOrCreateProduk(session, idBarang, kodeBarang,
						namaBarang, hargaBarang, toko);

				AturanDiskon aturanDiskon = (objectTransaksi.isNull("aturanDiskon") ? null
						: (AturanDiskon) GeneralValueObject.ambilData(AturanDiskon.class,
								(objectTransaksi.get("aturanDiskon") + "").trim()));

				DraftPembelian pembelian = new DraftPembelian();
				pembelian.setDraftPembelianAnggotaKoperasi(this);
				pembelian.setAnggotaKoperasi(this.getAnggotaKoperasi());
				pembelian.setKode(kodeUnik + "-" + kodeBarang);
				pembelian.setNama(namaBarang);
				pembelian.setKodePembayaranOnline(kodePembayaranOnline);
				pembelian.setQty(jumlahBarang);
				pembelian.setDiskon(diskonBarang);
				pembelian.setAturanDiskon(aturanDiskon);
				pembelian.setCashback(cashbackBarang);
				pembelian.setHargaSatuan(hargaBarang);
				pembelian.setProduk(produk);
				pembelian.setToko(toko);
				pembelian.setWaktu(currentWaktu);
				session.getTransaction().begin();
				session.save(pembelian);
				session.getTransaction().commit();

				JSONObject data = new JSONObject();
				Common.insertProperty(DraftPembelian.class, pembelian, data, "", 1, "siswa", "calonSiswa", "mahasiswa",
						"biodataCalonMahasiswa", "pembelianAnggotaKoperasi", "tbmuser", "kodePembayaranOnline", "toko");
				arrayTransaksi.put(data);

				// Gap-closure "Produk Ekstra" -- sama pola persis dgn PembelianAnggotaKoperasi.simpanRinci
				// (lihat JavaDoc di sana), TAPI indukId di sini menunjuk ke id DraftPembelian INDUK ini
				// (bukan Pembelian) -- di-remap 2-pass jadi id Pembelian yg benar saat draft difinalisasi
				// (lihat PembelianAnggotaKoperasi.simpanRinci cabang draft-finalization).
				if (!objectTransaksi.isNull("ekstra")) {
					JSONArray ekstraArr = objectTransaksi.optJSONArray("ekstra");
					for (int k = 0; ekstraArr != null && k < ekstraArr.length(); k++) {
						try {
							JSONObject e = ekstraArr.getJSONObject(k);
							String idEkstra = e.isNull("id") ? null : e.get("id") + "";
							String kodeEkstra = e.isNull("kode") ? "_" : e.get("kode") + "";
							String namaEkstra = e.isNull("nama") ? "_" : e.get("nama") + "";
							Double hargaEkstra = e.isNull("harga") ? 0.0
									: Double.parseDouble((e.get("harga") + "").trim());
							Double jumlahEkstra = e.isNull("jumlah") ? 1.0
									: Double.parseDouble((e.get("jumlah") + "").trim());

							Produk produkEkstra = PembelianAnggotaKoperasi.resolveOrCreateProduk(session, idEkstra,
									kodeEkstra, namaEkstra, hargaEkstra, toko);

							DraftPembelian pembelianEkstra = new DraftPembelian();
							pembelianEkstra.setDraftPembelianAnggotaKoperasi(this);
							pembelianEkstra.setAnggotaKoperasi(this.getAnggotaKoperasi());
							pembelianEkstra.setKode(kodeUnik + "-" + kodeBarang + "-" + kodeEkstra);
							pembelianEkstra.setNama(namaEkstra);
							pembelianEkstra.setKodePembayaranOnline(kodePembayaranOnline);
							pembelianEkstra.setQty(jumlahBarang * jumlahEkstra);
							pembelianEkstra.setDiskon(0.0);
							pembelianEkstra.setCashback(0.0);
							pembelianEkstra.setHargaSatuan(hargaEkstra);
							pembelianEkstra.setProduk(produkEkstra);
							pembelianEkstra.setToko(toko);
							pembelianEkstra.setWaktu(currentWaktu);
							pembelianEkstra.setIndukId(pembelian.getId());
							session.getTransaction().begin();
							session.save(pembelianEkstra);
							session.getTransaction().commit();

							JSONObject dataEkstra = new JSONObject();
							Common.insertProperty(DraftPembelian.class, pembelianEkstra, dataEkstra, "", 1, "siswa",
									"calonSiswa", "mahasiswa", "biodataCalonMahasiswa", "pembelianAnggotaKoperasi",
									"tbmuser", "kodePembayaranOnline", "toko");
							arrayTransaksi.put(dataEkstra);
						} catch (Exception eEkstra) {
							ais.common.ErrorAuditUtil.record(eEkstra,
									"auto-audit src/ais/database/model/koperasi/DraftPembelianAnggotaKoperasi.java:simpanRinci:ekstra");
							try {
								if (session.getTransaction() != null && session.getTransaction().isActive()) {
									session.getTransaction().rollback();
								}
							} catch (Exception eRollback) {
								ais.common.ErrorAuditUtil.record(eRollback,
										"auto-audit(rollback) src/ais/database/model/koperasi/DraftPembelianAnggotaKoperasi.java:simpanRinci:ekstra");
							}
						}
					}
				}

			} catch (Exception e) {
				e.printStackTrace(); ais.common.ErrorAuditUtil.record(e, "auto-audit src/ais/database/model/koperasi/DraftPembelianAnggotaKoperasi.java:200");
				// Gap-closure "Muat ke Keranjang kosong walau toast sukses": tanpa rollback di sini,
				// transaction Hibernate yg SUDAH di-begin() di atas (session.save(produk)/session.save
				// (pembelian)) tertinggal aktif-tapi-gagal begitu item ini gagal -- begin() berikutnya di
				// iterasi SELANJUTNYA jadi no-op (transaction dianggap sudah aktif), sehingga SEMUA item
				// sesudahnya ikut gagal tersimpan diam-diam juga (satu item bermasalah meracuni seluruh
				// keranjang). Rollback eksplisit memastikan tiap item benar-benar terisolasi.
				try {
					if (session.getTransaction() != null && session.getTransaction().isActive()) {
						session.getTransaction().rollback();
					}
				} catch (Exception eRollback) {
					ais.common.ErrorAuditUtil.record(eRollback, "auto-audit(rollback) src/ais/database/model/koperasi/DraftPembelianAnggotaKoperasi.java:simpanRinci");
				}
			}
		}

		return arrayTransaksi;
	}

	public DraftPembelianAnggotaKoperasi() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", insertable = false, unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "kode", nullable = false, length = 255)
	public String getKode() {
		return this.kode;
	}

	public void setKode(String kode) {
		this.kode = kode;
	}

	@Column(name = "keterangan", nullable = true)
	public String getKeterangan() {
		return this.keterangan;
	}

	public void setKeterangan(String keterangan) {
		this.keterangan = keterangan;
	}

	public void setAnggotaKoperasi(AnggotaKoperasi anggotaKoperasi) {
		this.anggotaKoperasi = anggotaKoperasi;
	}

	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY)
	@JoinColumn(name = "anggota_koperasi", nullable = true)
	public AnggotaKoperasi getAnggotaKoperasi() {
		anggotaKoperasi = check(anggotaKoperasi);
		return anggotaKoperasi;
	}

	public void setIndex(Long index) {
		this.index = index;
	}

	public Long getIndex() {
		return index;
	}

	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY)
	@JoinColumn(name = "lokasi", nullable = true)
	public Lokasi getLokasi() {
		lokasi = check(lokasi);
		return lokasi;
	}

	public void setLokasi(Lokasi lokasi) {
		this.lokasi = lokasi;
	}

	public Double getBiaya() {
		return biaya;
	}

	public void setBiaya(Double biaya) {
		this.biaya = biaya;
	}

	public Double getDiskon() {
		return diskon;
	}

	public void setDiskon(Double diskon) {
		this.diskon = diskon;
	}

	@Column(name = "diskon_dalam_persen")
	public Boolean getDiskonDalamPersen() {
		return diskonDalamPersen;
	}

	public void setDiskonDalamPersen(Boolean diskonDalamPersen) {
		this.diskonDalamPersen = diskonDalamPersen;
	}

	@Column(name = "total_diskon")
	public Double getTotalDiskon() {
		return totalDiskon;
	}

	public void setTotalDiskon(Double totalDiskon) {
		this.totalDiskon = totalDiskon;
	}

	public Double getPpn() {
		return ppn;
	}

	public void setPpn(Double ppn) {
		this.ppn = ppn;
	}

	@Column(name = "bayar_tunai")
	public Double getBayarTunai() {
		if (bayarTunai == null) {
			bayarTunai = 0.0;
		}
		return bayarTunai;
	}

	public void setBayarTunai(Double bayarTunai) {
		this.bayarTunai = bayarTunai;
	}

	@Column(name = "bayar_non_tunai")
	public Double getBayarNonTunai() {
		if (bayarNonTunai == null) {
			bayarNonTunai = 0.0;
		}
		return bayarNonTunai;
	}

	public void setBayarNonTunai(Double bayarNonTunai) {
		this.bayarNonTunai = bayarNonTunai;
	}

	public void setTanggalPembayaran(Date tanggalPembayaran) {
		this.tanggalPembayaran = tanggalPembayaran;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "tanggal_pembayaran")
	public Date getTanggalPembayaran() {
		return tanggalPembayaran;
	}

	public void setTbmuser(Tbmuser tbmuser) {
		this.tbmuser = tbmuser;
	}

	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY)
	@JoinColumn(name = "tbmuser", nullable = true)
	public Tbmuser getTbmuser() {
		tbmuser = check(tbmuser);
		return tbmuser;
	}

	/**
	 * Nama kasir yang BENAR-BENAR login di mesin POS saat pesanan/keranjang ditahan -- field baru
	 * terpisah dari {@link #getOleh()}/{@link #getOlehId()} (audit generik, selalu jatuh ke
	 * {@code "external_update"} utk permintaan lewat PosApi). Pola IDENTIK dgn
	 * {@link PembelianAnggotaKoperasi#getKasirLoginNama()} -- lihat JavaDoc di sana utk alasan
	 * lengkap. {@code null} utk pesanan online (lihat {@code PosApi.dariPembeliOnline} -- member yg
	 * checkout sendiri, bukan kasir).
	 */
	@Column(name = "kasir_login_nama", nullable = true)
	public String getKasirLoginNama() {
		return kasirLoginNama;
	}

	public void setKasirLoginNama(String kasirLoginNama) {
		this.kasirLoginNama = kasirLoginNama;
	}

	/**
	 * Nama mesin POS fisik asal pesanan ini -- pola IDENTIK dgn
	 * {@link PembelianAnggotaKoperasi#getNamaMesin()}. {@code null} utk pesanan online (tak ada
	 * "mesin POS" -- pembeli checkout sendiri lewat kanal lain).
	 */
	@Column(name = "nama_mesin", nullable = true, length = 100)
	public String getNamaMesin() {
		return namaMesin;
	}

	public void setNamaMesin(String namaMesin) {
		this.namaMesin = namaMesin;
	}

	public void setRetur(Double retur) {
		this.retur = retur;
	}

	public Double getRetur() {
		return retur;
	}

	public void setTotalBiaya(Double totalBiaya) {
		this.totalBiaya = totalBiaya;
	}

	@Column(name = "total_biaya")
	public Double getTotalBiaya() {
		if (totalBiaya == null) {
			totalBiaya = 0.0;
		}
		return totalBiaya;
	}

	public void setKembalian(Double kembalian) {
		this.kembalian = kembalian;
	}

	public Double getKembalian() {
		return kembalian;
	}

	public void setHargaPpn(Double hargaPpn) {
		this.hargaPpn = hargaPpn;
	}

	@Column(name = "harga_ppn")
	public Double getHargaPpn() {
		return hargaPpn;
	}

	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE })
	@Fetch(FetchMode.SELECT)
	@JoinColumn(name = "posting_history", nullable = true)
	public PostingHistory getPostingHistory() {
		return postingHistory;
	}

	public void setPostingHistory(PostingHistory postingHistory) {
		this.postingHistory = postingHistory;
	}

	

	public Double getBayar() {
		bayar = getBayarNonTunai() + getBayarTunai();
		return bayar;
	}

	public void setBayar(Double bayar) {
		this.bayar = bayar;
	}

	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY)
	@JoinColumn(name = "cara_pembayaran_koperasi", nullable = true)
	public CaraPembayaranKoperasi getCaraPembayaranKoperasi() {
		caraPembayaranKoperasi = check(caraPembayaranKoperasi);
		return caraPembayaranKoperasi;
	}

	public void setCaraPembayaranKoperasi(CaraPembayaranKoperasi caraPembayaranKoperasi) {
		this.caraPembayaranKoperasi = caraPembayaranKoperasi;
	}

	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE })
	@Fetch(FetchMode.SELECT)
	@JoinColumn(name = "kode_pembayaran_online", nullable = true)
	public KodePembayaranOnline getKodePembayaranOnline() {
		return kodePembayaranOnline;
	}

	public void setKodePembayaranOnline(KodePembayaranOnline kodePembayaranOnline) {
		this.kodePembayaranOnline = kodePembayaranOnline;
	}

	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY)
	@JoinColumn(name = "toko", nullable = true)
	public Toko getToko() {
		if (getLokasi() != null && getLokasi().getToko() != null) {
			toko = getLokasi().getToko();
		} else {
			toko = check(toko);
		}
		return toko;
	}

	public void setToko(Toko toko) {
		this.toko = toko;
	}

	public Double getTotalCashback() {
		return totalCashback == null ? 0.0 : totalCashback;
	}

	public void setTotalCashback(Double totalCashback) {
		this.totalCashback = totalCashback;
	}

	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY)
	@JoinColumn(name = "meja_kantin", nullable = true)
	public MejaKantin getMejaKantin() {
		mejaKantin = check(mejaKantin);
		return mejaKantin;
	}

	public void setMejaKantin(MejaKantin mejaKantin) {
		this.mejaKantin = mejaKantin;
	}

	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE })
	@Fetch(FetchMode.SELECT)
	@JoinColumn(name = "lunas", nullable = true)
	public PembelianAnggotaKoperasi getLunas() {
		return lunas;
	}

	public void setLunas(PembelianAnggotaKoperasi lunas) {
		this.lunas = lunas;
	}
}
