<%-- @generated by generate_new_jsp_scaffold.py
Source: src/ais/action/servlet/DataMahasiswa.java
Generated: 2026-08-06T18:20:20Z
This JSP contains presentation metadata only. Keep business logic in Java services.
--%>
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%
request.setAttribute("nuiModule", "root/servlet");
request.setAttribute("nuiModuleLabel", "Servlet & Endpoint");
request.setAttribute("nuiPage", "data_mahasiswa");
request.setAttribute("nuiPageTitle", "Data Mahasiswa");
request.setAttribute("nuiPageType", "integration");
request.setAttribute("nuiPageDescription", "Integrasi untuk Servlet & Endpoint. Status koneksi, sinkronisasi, log, retry, dan pemetaan data.");
request.setAttribute("nuiSourceClass", "DataMahasiswa");
request.setAttribute("nuiSourcePackage", "ais.action.servlet");
request.setAttribute("nuiSourcePath", "src/ais/action/servlet/DataMahasiswa.java");
request.setAttribute("nuiSourceKind", "class");
request.setAttribute("nuiSourceExtends", "HttpServlet");
request.setAttribute("nuiSourceImplements", "");
request.setAttribute("nuiSourceMethods", new String[]{});
request.setAttribute("nuiEntityCandidates", new String[]{"Mahasiswa"});
%>
<jsp:include page="/WEB-INF/new/_shared/ui/page.jsp" />
