<%-- @generated by generate_new_jsp_scaffold.py
Source: src/ais/action/master/sirs/CetakKartuPasienAction.java
Generated: 2026-08-06T18:20:20Z
This JSP contains presentation metadata only. Keep business logic in Java services.
--%>
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%
request.setAttribute("nuiModule", "sirs");
request.setAttribute("nuiModuleLabel", "SIRS / Klinik / Rumah Sakit");
request.setAttribute("nuiPage", "cetak_kartu_pasien");
request.setAttribute("nuiPageTitle", "Cetak Kartu Pasien");
request.setAttribute("nuiPageType", "report");
request.setAttribute("nuiPageDescription", "Laporan untuk SIRS / Klinik / Rumah Sakit. Filter, pratinjau, ekspor, dan histori pembuatan laporan.");
request.setAttribute("nuiSourceClass", "CetakKartuPasienAction");
request.setAttribute("nuiSourcePackage", "ais.action.master.sirs");
request.setAttribute("nuiSourcePath", "src/ais/action/master/sirs/CetakKartuPasienAction.java");
request.setAttribute("nuiSourceKind", "class");
request.setAttribute("nuiSourceExtends", "GenericAutowireComposer");
request.setAttribute("nuiSourceImplements", "");
request.setAttribute("nuiSourceMethods", new String[]{"doAfterCompose", "onEvent", "render", "onAdd", "onSave", "onSearchDefault", "onCetakKartu"});
request.setAttribute("nuiEntityCandidates", new String[]{"JenisPasien", "CetakKartuPasien", "Pendaftaran", "Pasien"});
%>
<jsp:include page="/WEB-INF/new/_shared/ui/page.jsp" />
