<style>
.pos-help-modal .modal-dialog{max-width:1120px}.pos-help-modal .modal-content{background:#f6f8fc}.pos-help-hero{background:linear-gradient(135deg,#143b70,#1677df);color:#fff;border-radius:18px;padding:24px}.pos-help-search{max-width:480px}.pos-help-flow{display:flex;align-items:stretch;gap:8px;overflow-x:auto;padding:8px 0 14px}.pos-help-step{background:#fff;border:1px solid #dce5f1;border-radius:14px;padding:14px;min-width:140px;text-align:center;box-shadow:0 4px 16px rgba(20,59,112,.06)}.pos-help-step i{display:block;color:#1677df;font-size:24px;margin-bottom:8px}.pos-help-arrow{display:flex;align-items:center;color:#7791ae}.pos-help-screen{background:#102a4c;border-radius:16px;padding:10px}.pos-help-screen-head,.pos-help-screen-box{border-radius:9px;margin:5px;padding:12px;text-align:center;font-weight:700;color:#17355b}.pos-help-screen-head{background:#e8f2ff}.pos-help-screen-box{background:#fff}.pos-help-screen-cart{background:#fff1df}.pos-help-topic{background:#fff;border:1px solid #e1e8f2;border-radius:14px;margin-bottom:10px;overflow:hidden}.pos-help-topic summary{cursor:pointer;padding:16px 18px;font-weight:800;color:#183b65}.pos-help-topic p{padding:0 18px 18px;margin:0;line-height:1.8;text-align:justify;color:#425466}.pos-help-check{background:#e9fff4;border:1px solid #b9ead1;border-radius:14px;padding:18px}.pos-help-check li{margin:7px 0}.pos-help-hidden{display:none!important}@media(max-width:767px){.pos-help-modal .modal-body{padding:12px}.pos-help-hero{padding:18px}.pos-help-screen .row>*{width:100%}.pos-help-flow{scroll-snap-type:x mandatory}.pos-help-step{scroll-snap-align:start}}
</style>
<div class="modal fade pos-help-modal" id="modalBantuanPOS<%=rnd%>" tabindex="-1" aria-labelledby="judulBantuanPOS<%=rnd%>" aria-hidden="true">
  <div class="modal-dialog modal-xl modal-dialog-scrollable">
    <div class="modal-content border-0 rounded-4 shadow">
      <div class="modal-header border-0 pb-0">
        <h5 class="modal-title fw-bold" id="judulBantuanPOS<%=rnd%>"><i class="fas fa-question-circle text-primary me-2"></i><%=Common.getBahasaConfig("Panduan Lengkap POS JSP / Browser")%></h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <section class="pos-help-hero mb-3">
          <div class="small fw-bold text-uppercase opacity-75 mb-1"><%=Common.getBahasaConfig("Bantuan operasional terstruktur · lebih dari 1.000 kata")%></div>
          <h3 class="fw-bold mb-2"><%=Common.getBahasaConfig("Dari buka sesi sampai rekonsiliasi akhir shift")%></h3>
          <p class="mb-3"><%=Common.getBahasaConfig("Gunakan panduan ini ketika belajar, mendampingi kasir baru, atau mendiagnosis masalah tanpa menghapus data transaksi.")%></p>
          <div class="input-group pos-help-search">
            <span class="input-group-text border-0 bg-white"><i class="fas fa-search"></i></span>
            <input class="form-control border-0" id="cariBantuanPOS<%=rnd%>" placeholder="<%=Common.getBahasaConfig("Cari: offline, retur, printer, pembayaran...")%>" oninput="filterBantuanPOS<%=rnd%>(this.value)">
          </div>
        </section>

        <section class="card border-0 rounded-4 shadow-sm mb-3"><div class="card-body p-4">
          <h5 class="fw-bold"><%=Common.getBahasaConfig("Diagram workflow transaksi")%></h5>
          <p class="text-muted small"><%=Common.getBahasaConfig("Ikuti alur dari kiri ke kanan. Jika satu tahap gagal, periksa riwayat sebelum mencoba kembali.")%></p>
          <div class="pos-help-flow">
            <div class="pos-help-step"><i class="fas fa-lock-open"></i><b>1. Buka sesi</b><small class="d-block text-muted">Modal awal nyata</small></div><div class="pos-help-arrow"><i class="fas fa-arrow-right"></i></div>
            <div class="pos-help-step"><i class="fas fa-barcode"></i><b>2. Scan</b><small class="d-block text-muted">Produk dan jumlah</small></div><div class="pos-help-arrow"><i class="fas fa-arrow-right"></i></div>
            <div class="pos-help-step"><i class="fas fa-shopping-cart"></i><b>3. Verifikasi</b><small class="d-block text-muted">Member, promo, total</small></div><div class="pos-help-arrow"><i class="fas fa-arrow-right"></i></div>
            <div class="pos-help-step"><i class="fas fa-money-check-alt"></i><b>4. Bayar</b><small class="d-block text-muted">Tunai/non-tunai/split</small></div><div class="pos-help-arrow"><i class="fas fa-arrow-right"></i></div>
            <div class="pos-help-step"><i class="fas fa-user-shield"></i><b>5. Validasi</b><small class="d-block text-muted">Server dan RBAC</small></div><div class="pos-help-arrow"><i class="fas fa-arrow-right"></i></div>
            <div class="pos-help-step"><i class="fas fa-receipt"></i><b>6. Selesai</b><small class="d-block text-muted">Struk dan sinkron</small></div>
          </div>
        </div></section>

        <section class="card border-0 rounded-4 shadow-sm mb-3"><div class="card-body p-4">
          <h5 class="fw-bold"><%=Common.getBahasaConfig("Ilustrasi cara membaca halaman POS JSP")%></h5>
          <p class="text-muted"><%=Common.getBahasaConfig("Pada layar desktop, katalog berada di kiri dan keranjang di kanan. Pada layar sempit keduanya bertumpuk dan dibaca dari atas ke bawah.")%></p>
          <div class="pos-help-screen">
            <div class="pos-help-screen-head">① Status sesi kas · pengguna · outlet · koneksi</div>
            <div class="row g-0"><div class="col-md-7"><div class="pos-help-screen-box">② F2 / scan barcode / cari nama<br><br>③ Kategori dan kartu produk</div></div><div class="col-md-5"><div class="pos-help-screen-box pos-help-screen-cart">④ Keranjang · member · promo<br><br>⑤ Total · metode bayar · F12</div></div></div>
          </div>
        </div></section>

        <div id="topikBantuanPOS<%=rnd%>">
          <details class="pos-help-topic" open data-help="tujuan peran rbac akun audit aman">
            <summary>1. Tujuan halaman, pembagian peran, dan prinsip kerja aman</summary>
            <p>Halaman POS mengubah pilihan barang menjadi transaksi penjualan yang tercatat, dibayar, dicetak, dan dapat ditelusuri kembali. Kasir memastikan barang, jumlah, pelanggan, harga, promo, metode pembayaran, dan uang diterima benar sebelum menekan Bayar. Supervisor menangani tindakan yang memerlukan otorisasi, seperti pembatalan, pembukaan laci manual, koreksi tertentu, atau penyelesaian selisih. Admin menyiapkan produk, harga, perangkat, toko, cara bayar, dan hak akses. Tombol yang tidak terlihat atau tindakan yang ditolak tidak selalu berarti aplikasi rusak; akun mungkin memang tidak memiliki izin. Jangan meminjam akun pengguna lain karena seluruh aktivitas dicatat atas identitas yang sedang login. Dokumen yang sudah berhasil atau posted tidak dihapus. Kesalahan diselesaikan melalui retur, pembatalan, atau dokumen pembalik sehingga stok, kas, pajak, dan audit tetap dapat dijelaskan. Sebelum mulai, periksa nama pengguna, outlet, waktu perangkat, status koneksi, printer, dan sesi kas. Jika toko mewajibkan sesi, modal awal harus sama dengan uang fisik. Prinsip utama operasi adalah satu kejadian penjualan menghasilkan satu dokumen dan satu rangkaian pembayaran yang dapat direkonsiliasi. Jangan menekan tombol berulang ketika proses berjalan, jangan membuat ulang transaksi hanya karena struk gagal, dan jangan menghapus penyimpanan browser untuk menyelesaikan antrean sinkronisasi.</p>
          </details>
          <details class="pos-help-topic" open data-help="browser tab refresh f1 f2 f12 popup zoom sesi">
            <summary>2. Orientasi browser, pintasan, dan batas aman navigasi</summary>
            <p>POS JSP berjalan di AIS melalui browser. Pastikan alamat server dan lingkungan login benar. Gunakan satu tab POS aktif untuk satu kasir; dua tab dapat membuat dua keranjang atau dua permintaan pembayaran bersaing. Hindari Back, Forward, Refresh, dan menutup tab saat pembayaran berlangsung. F1 membuka panduan ini, F2 memusatkan kolom pencarian, dan F12 memulai pembayaran. Label tombol adalah rujukan bila konfigurasi pintasan berubah. Browser harus mengizinkan popup untuk layar pelanggan serta dialog cetak. Gunakan zoom seratus persen agar tombol tidak terpotong. Area atas menunjukkan status sesi kas. Area kiri memuat pencarian, kategori, dan katalog. Area kanan memuat keranjang, promo, total, uang tunai, serta tombol Bayar. Di bawahnya terdapat ringkasan inventori dan transaksi terbaru. Pada ponsel, panel bertumpuk; gulir dengan tenang dan jangan mengetuk dua kali. Jika login berakhir, masuk kembali lalu periksa riwayat sebelum mengisi ulang transaksi. Muat ulang halaman hanya setelah memastikan tidak ada permintaan aktif dan keranjang penting sudah disimpan sebagai tertahan. Scanner barcode bekerja seperti keyboard, sehingga fokus harus berada pada pencarian. Bila hasil scan masuk ke kolom uang, tutup dialog dan kembalikan fokus sebelum memindai lagi.</p>
          </details>
          <details class="pos-help-topic" data-help="shift persiapan modal printer scanner outlet sinkron">
            <summary>3. Persiapan awal shift</summary>
            <p>Mulailah dengan memilih outlet yang sama dengan lokasi fisik. Kesalahan outlet menyebabkan stok, nomor struk, kas, dan laporan tercatat di tempat lain. Pastikan tanggal serta jam perangkat benar. Buka sesi kas menggunakan jumlah uang yang benar-benar tersedia di laci, bukan saldo perkiraan. Lakukan uji printer bila perangkat baru dinyalakan atau kertas diganti. Periksa laci dan layar pelanggan. Pastikan katalog menampilkan produk serta harga terbaru; lakukan sinkronisasi apabila kantor baru mengubah master. Lihat riwayat sinkronisasi untuk mengetahui transaksi tertunda. Pisahkan masalah perangkat dari masalah transaksi: printer gagal tidak berarti penjualan gagal, tetapi penolakan server berarti pembayaran belum selesai. Periksa koneksi scanner, printer, popup, dan jaringan sebelum antrean ramai. Pastikan metode pembayaran yang aktif sesuai perangkat EDC atau QR yang tersedia. Siapkan pecahan uang kembalian dan hitung modal awal bersama petugas yang berwenang bila kebijakan mengharuskan. Catat kondisi tidak normal kepada supervisor. Jangan memulai shift menggunakan sesi milik kasir sebelumnya. Jika tombol Buka Sesi tidak tersedia, baca pesan hak akses atau konfigurasi, lalu minta admin memperbaiki role. Pemeriksaan awal yang singkat mencegah koreksi panjang ketika penutupan kas dilakukan.</p>
          </details>
          <details class="pos-help-topic" data-help="produk barcode scan katalog keranjang qty topping stok">
            <summary>4. Mencari produk dan menyusun keranjang</summary>
            <p>Tekan F2 atau klik pencarian, pindai barcode, lalu tunggu produk masuk. Jika tidak ditemukan, cari sebagian nama atau kode dan pilih kategori. Setiap klik kartu menambah produk. Periksa nama, varian, satuan, jumlah, harga satuan, topping, diskon, dan subtotal baris. Produk yang mirip dapat memiliki satuan berbeda. Gunakan tambah atau kurang untuk kuantitas dan hapus hanya baris yang benar-benar batal. Bila dialog ekstra muncul, pilih tambahan sesuai pesanan karena pilihan memengaruhi harga dan uraian struk. Untuk barcode timbangan, periksa berat yang diterjemahkan. Jangan memakai produk lain sebagai pengganti hanya karena stok sistem kosong. Hubungi petugas stok bila barang fisik dan sistem berbeda. Setelah semua barang masuk, bandingkan isi keranjang dengan barang di meja secara berurutan. Jika pelanggan berhenti sementara, gunakan Keranjang Tertahan, beri catatan yang mudah dikenali, lalu pastikan keranjang aktif kosong sebelum pelanggan berikutnya. Ketika memuat keranjang tertahan, periksa ulang harga, promo, pelanggan, stok, dan metode pembayaran karena keadaan dapat berubah. Data tertahan belum menjadi penjualan dan belum boleh dihitung sebagai penerimaan kas. Jangan gunakan fitur tahan sebagai pengganti transaksi kredit.</p>
          </details>
          <details class="pos-help-topic" data-help="member pelanggan promo diskon pajak cashback harga">
            <summary>5. Pelanggan, promo, diskon, pajak, dan harga akhir</summary>
            <p>Pilih pelanggan sebelum pembayaran bila transaksi menggunakan harga anggota, saldo, limit hutang, poin, atau cashback. Cari melalui kode, nama, telepon, kartu, atau QR sesuai fasilitas. Konfirmasi identitas tanpa membacakan data pribadi berlebihan. Setelah pelanggan dipilih, sistem dapat menghitung ulang harga dan promo. Amati subtotal, diskon, cashback, pajak, pembulatan, serta total. Promo otomatis berlaku saat syarat terpenuhi; promo manual perlu dipilih melalui ikon tag. Baca minimal belanja, produk sasaran, masa berlaku, kuota, metode bayar, dan aturan penggabungan. Jangan menjanjikan diskon sebelum angka keranjang berubah. Bila label rak berbeda, verifikasi produk dan periode harga sesuai kebijakan; jangan mengubah harga tanpa izin. Untuk pelanggan umum, bersihkan identitas transaksi sebelumnya agar poin atau hutang tidak masuk ke orang yang salah. Konfirmasikan total akhir setelah pelanggan, promo, dan metode selesai dipilih. Perubahan salah satu unsur dapat memicu perhitungan ulang. Jika promo menghilang, periksa kuantitas, produk, periode, pelanggan, dan cara bayar, bukan menambahkan potongan manual. Cashback bukan selalu pengurang tagihan saat ini; baca cara pencatatannya. Semua angka sebelum Bayar harus dapat dijelaskan kepada pelanggan dengan bahasa sederhana.</p>
          </details>
          <details class="pos-help-topic" data-help="pembayaran tunai transfer qr split kembalian bayar duplikat">
            <summary>6. Pembayaran tunai, non-tunai, dan split</summary>
            <p>Tekan F12 atau Bayar setelah keranjang benar. Pilih tunai, kartu, transfer, QR, saldo, hutang, atau metode lain yang aktif. Pada tunai, masukkan uang yang benar-benar diberikan pelanggan. Hitung uang di hadapan pelanggan, sebutkan nilai diterima dan kembalian, kemudian simpan uang setelah transaksi disetujui. Pada pembayaran non-tunai, jangan menerima tangkapan layar sebagai bukti final; tunggu status berhasil pada alat atau penyedia. Untuk split payment, pilih hingga batas metode yang diizinkan dan alokasikan nominal sampai sisa tepat nol. Pastikan bagian tunai dan non-tunai tidak tertukar. Jangan menekan Bayar berulang ketika tombol sedang memproses. Bila respons lambat, lihat indikator dan riwayat dahulu. Kode unik membantu mencegah duplikasi, tetapi operator tetap wajib memeriksa. Jika berhasil, catat nomor transaksi dan cetak struk. Jika ditolak, baca pesan lengkap, perbaiki penyebab, lalu ulangi hanya tindakan yang gagal. Jangan membuat keranjang baru sebelum yakin transaksi pertama tidak tercatat. Untuk hutang atau saldo, pastikan pelanggan, limit, PIN, dan otorisasi benar. Bila QR kedaluwarsa atau dibatalkan, tutup dialog secara resmi agar polling berhenti sebelum memilih metode lain.</p>
          </details>
          <details class="pos-help-topic" data-help="struk printer cetak ulang laci layar pelanggan tertahan">
            <summary>7. Struk, printer, laci, layar pelanggan, dan keranjang tertahan</summary>
            <p>Struk dicetak setelah pembayaran berhasil. Kegagalan printer tidak membatalkan penjualan. Periksa daya, kertas, tutup, kabel, antrean cetak, pilihan printer, dan ukuran, kemudian cetak ulang transaksi yang sama. Jangan membayar ulang hanya untuk mendapatkan struk. Laci biasanya terbuka ketika pembayaran tunai; pembukaan manual dapat membutuhkan PIN dan alasan audit. Layar pelanggan menampilkan barang, promo, total, dan status. Gunakan sebagai konfirmasi, tetapi keranjang kasir tetap sumber pengendalian. Tombol layar pelanggan dapat membuka atau menutup popup atau monitor kedua. Bila popup tidak muncul, periksa pemblokir popup dan posisi jendela pada monitor lain. Keranjang Tertahan digunakan ketika pelayanan dijeda, bukan untuk mencatat hutang. Beri identitas singkat tanpa data sensitif. Saat melanjutkan, cocokkan pemilik keranjang dan isi barang. Hapus keranjang yang batal hanya menurut kewenangan. Untuk cetak ulang, cari transaksi dari riwayat berdasarkan nomor, waktu, kasir, atau pelanggan. Pastikan yang dicetak adalah dokumen yang benar. Jika printer mencetak karakter aneh, periksa driver, mode ESC/POS, encoding, dan lebar kertas. Jangan mengubah konfigurasi perangkat ketika antrean ramai tanpa uji hasil.</p>
          </details>
          <details class="pos-help-topic" data-help="offline koneksi sinkron antrean gagal server internet">
            <summary>8. Koneksi terputus dan sinkronisasi</summary>
            <p>Perhatikan indikator online, jumlah antrean, waktu percobaan terakhir, dan pesan kegagalan. Transaksi offline disimpan dengan identitas unik sampai server mengakui. Jangan menghapus cache, database browser, profil, atau instalasi selama antrean masih ada. Jalankan sinkronisasi sekali dan tunggu hasil tiap item. Status terkirim berarti server menerima data; status gagal harus dibaca penyebabnya, misalnya sesi berakhir, izin berubah, referensi tidak ditemukan, atau payload tidak valid. Jangan membuat salinan transaksi untuk mengatasi kegagalan. Ketika jaringan kembali, sinkronkan sebelum menutup shift. Cocokkan transaksi lokal, transaksi server, uang tunai, serta metode non-tunai. Jika ada konflik, catat nomor lokal, waktu, nilai, pengguna, outlet, dan pesan. Mode offline tidak menghapus aturan stok, limit, atau otorisasi. Metode tertentu memang harus online; tawarkan alternatif yang sah. Jika browser menampilkan halaman jaringan sementara pembayaran sedang berjalan, tunggu dan buka riwayat setelah koneksi kembali. Jangan menekan Refresh berkali-kali. Keutuhan data lebih penting daripada membuat layar terlihat cepat selesai. Admin dapat memakai riwayat sinkronisasi dan log error untuk menentukan apakah data perlu dikirim ulang atau hanya perlu dimuat ulang.</p>
          </details>
          <details class="pos-help-topic" data-help="retur batal koreksi reversal audit posted">
            <summary>9. Retur, pembatalan, koreksi, dan audit</summary>
            <p>Kesalahan sesudah transaksi berhasil ditangani dengan retur atau pembatalan resmi, bukan menghapus dokumen atau membuat penjualan negatif. Cari transaksi asli dan cocokkan nomor struk, tanggal, kasir, pelanggan, produk, jumlah, serta metode bayar. Retur mengembalikan barang ke stok bila kondisi sesuai; barang rusak atau kedaluwarsa dapat menggunakan jalur stok lain. Pengembalian uang mengikuti metode dan persetujuan toko. Pembatalan penuh memerlukan kewenangan serta alasan. Dokumen posted dipertahankan dan dibuatkan pembalik agar laporan dapat ditelusuri. Jangan memakai akun atau PIN supervisor tanpa kehadirannya. Baca dampak sebelum menyimpan: nilai, stok, kas, poin, hutang, pajak, dan referensi. Cetak bukti koreksi. Salah cetak cukup diselesaikan melalui cetak ulang, bukan retur. Harga salah sebelum bayar diperbaiki di keranjang; harga salah setelah bayar mengikuti prosedur koreksi. Audit melindungi kasir dan toko karena menunjukkan pelaku, waktu, alasan, dan dokumen terkait. Jika server menolak reversal, baca status dokumen, sesi, hak akses, dan alasan minimal. Jangan mencoba mengubah database secara manual. Eskalasi dengan nomor transaksi dan pesan lengkap.</p>
          </details>
          <details class="pos-help-topic" data-help="tutup shift rekonsiliasi selisih kas laporan logout">
            <summary>10. Menutup shift dan rekonsiliasi</summary>
            <p>Sebelum menutup sesi, hentikan transaksi baru dan selesaikan keranjang aktif atau tertahan. Sinkronkan sampai tidak ada antrean. Buka ringkasan: saldo awal, penjualan tunai, penerimaan non-tunai, pengeluaran atau pembukaan laci, retur, pembatalan, setoran, dan kas seharusnya. Hitung uang fisik menurut pecahan di tempat aman. Masukkan kas aktual apa adanya, jangan menyesuaikan agar terlihat sama. Jika ada selisih, hitung ulang dan periksa transaksi terakhir, split payment, retur, kembalian, keranjang tertahan, serta transaksi belum tersinkron. Tulis alasan faktual. Cocokkan kartu, QR, transfer, saldo, dan hutang dengan sumbernya. Supervisor memeriksa sesuai kebijakan. Tutup sesi hanya setelah bukti lengkap, kemudian logout supaya shift berikutnya tidak memakai akun lama. Bila tombol Tutup ditolak, periksa antrean, status sesi, role, dan kolom wajib. Jangan meninggalkan tab terbuka setelah kas diserahkan. Rekonsiliasi rutin membuat laporan harian dapat dipercaya. Untuk bantuan teknis, catat siapa, perangkat, browser, outlet, waktu, langkah, hasil yang diharapkan, hasil aktual, nomor transaksi, dan tangkapan layar tanpa sandi atau data kartu lengkap.</p>
          </details>
        </div>

        <div class="pos-help-check mt-3">
          <h5 class="fw-bold text-success"><i class="fas fa-tasks me-2"></i>Checklist cepat sebelum transaksi selesai</h5>
          <ul class="mb-0"><li>Outlet, akun, sesi kas, tanggal, dan koneksi benar.</li><li>Produk, jumlah, pelanggan, promo, pajak, dan total dibaca ulang.</li><li>Metode bayar dan nominal diterima dikonfirmasi.</li><li>Status transaksi diperiksa sebelum cetak ulang atau mencoba kembali.</li><li>Antrean sinkronisasi kosong sebelum sesi ditutup.</li></ul>
        </div>
      </div>
      <div class="modal-footer border-0"><button type="button" class="btn btn-primary rounded-pill px-4" data-bs-dismiss="modal"><%=Common.getBahasaConfig("Tutup Panduan")%></button></div>
    </div>
  </div>
</div>
<script>
window.filterBantuanPOS<%=rnd%> = function(q){
  q=(q||'').toLowerCase().trim();
  document.querySelectorAll('#topikBantuanPOS<%=rnd%> .pos-help-topic').forEach(function(el){
    var cocok=!q||(el.textContent+' '+(el.dataset.help||'')).toLowerCase().indexOf(q)>=0;
    el.classList.toggle('pos-help-hidden',!cocok);
    if(q&&cocok)el.open=true;
  });
};
</script>
