<style>
.pos-help-modal .modal-dialog{max-width:1120px}.pos-help-modal .modal-content{background:#f6f8fc}.pos-help-hero{background:linear-gradient(135deg,#143b70,#1677df);color:#fff;border-radius:18px;padding:24px}.pos-help-search{max-width:480px}.pos-help-flow{display:flex;align-items:stretch;gap:8px;overflow-x:auto;padding:8px 0 14px}.pos-help-step{background:#fff;border:1px solid #dce5f1;border-radius:14px;padding:14px;min-width:140px;text-align:center;box-shadow:0 4px 16px rgba(20,59,112,.06)}.pos-help-step i{display:block;color:#1677df;font-size:24px;margin-bottom:8px}.pos-help-arrow{display:flex;align-items:center;color:#7791ae}.pos-help-screen{background:#102a4c;border-radius:16px;padding:10px}.pos-help-screen-head,.pos-help-screen-box{border-radius:9px;margin:5px;padding:12px;text-align:center;font-weight:700;color:#17355b}.pos-help-screen-head{background:#e8f2ff}.pos-help-screen-box{background:#fff}.pos-help-screen-cart{background:#fff1df}.pos-help-topic{background:#fff;border:1px solid #e1e8f2;border-radius:14px;margin-bottom:10px;overflow:hidden}.pos-help-topic summary{cursor:pointer;padding:16px 18px;font-weight:800;color:#183b65}.pos-help-topic p{padding:0 18px 18px;margin:0;line-height:1.8;text-align:justify;color:#425466}.pos-help-check{background:#e9fff4;border:1px solid #b9ead1;border-radius:14px;padding:18px}.pos-help-check li{margin:7px 0}.pos-help-hidden{display:none!important}.pos-help-decision{display:grid;grid-template-columns:1fr auto 1fr;gap:12px;align-items:center}.pos-help-decision>div{padding:14px;border-radius:12px;text-align:center;font-weight:700}.pos-help-yes{background:#e9fff4}.pos-help-no{background:#ffeded}@media(max-width:767px){.pos-help-modal .modal-body{padding:12px}.pos-help-hero{padding:18px}.pos-help-screen .row>*{width:100%}.pos-help-flow{scroll-snap-type:x mandatory}.pos-help-step{scroll-snap-align:start}.pos-help-decision{grid-template-columns:1fr}.pos-help-decision .fas{transform:rotate(90deg)}}
</style>
<div class="modal fade pos-help-modal" id="modalBantuanPOS<%=rnd%>" tabindex="-1" aria-labelledby="judulBantuanPOS<%=rnd%>" aria-hidden="true">
  <div class="modal-dialog modal-xl modal-dialog-scrollable">
    <div class="modal-content border-0 rounded-4 shadow">
      <div class="modal-header border-0 pb-0">
        <h5 class="modal-title fw-bold" id="judulBantuanPOS<%=rnd%>"><i class="fas fa-question-circle text-primary me-2"></i><%=Common.getBahasaConfig("Panduan Lengkap POS JSP / Browser")%></h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <section class="pos-help-hero mb-3">
          <div class="small fw-bold text-uppercase opacity-75 mb-1"><%=Common.getBahasaConfig("Bantuan formal dan mudah dipahami · minimal 3.500 kata")%></div>
          <h3 class="fw-bold mb-2"><%=Common.getBahasaConfig("Dari buka sesi sampai rekonsiliasi akhir shift")%></h3>
          <p class="mb-3"><%=Common.getBahasaConfig("Gunakan panduan ini ketika belajar, mendampingi kasir baru, atau mendiagnosis masalah tanpa menghapus data transaksi.")%></p>
          <div class="input-group pos-help-search">
            <span class="input-group-text border-0 bg-white"><i class="fas fa-search"></i></span>
            <input class="form-control border-0" id="cariBantuanPOS<%=rnd%>" placeholder="<%=Common.getBahasaConfig("Cari: offline, retur, printer, pembayaran...")%>" oninput="filterBantuanPOS<%=rnd%>(this.value)">
          </div>
        </section>

        <section class="card border-0 rounded-4 shadow-sm mb-3"><div class="card-body p-4">
          <h5 class="fw-bold"><%=Common.getBahasaConfig("Diagram workflow transaksi")%></h5>
          <p class="text-muted small"><%=Common.getBahasaConfig("Ikuti alur dari kiri ke kanan. Jika satu tahap gagal, periksa riwayat sebelum mencoba kembali.")%></p>
          <div class="pos-help-flow">
            <div class="pos-help-step"><i class="fas fa-lock-open"></i><b>1. Buka sesi</b><small class="d-block text-muted">Modal awal nyata</small></div><div class="pos-help-arrow"><i class="fas fa-arrow-right"></i></div>
            <div class="pos-help-step"><i class="fas fa-barcode"></i><b>2. Scan</b><small class="d-block text-muted">Produk dan jumlah</small></div><div class="pos-help-arrow"><i class="fas fa-arrow-right"></i></div>
            <div class="pos-help-step"><i class="fas fa-shopping-cart"></i><b>3. Verifikasi</b><small class="d-block text-muted">Member, promo, total</small></div><div class="pos-help-arrow"><i class="fas fa-arrow-right"></i></div>
            <div class="pos-help-step"><i class="fas fa-money-check-alt"></i><b>4. Bayar</b><small class="d-block text-muted">Tunai/non-tunai/split</small></div><div class="pos-help-arrow"><i class="fas fa-arrow-right"></i></div>
            <div class="pos-help-step"><i class="fas fa-user-shield"></i><b>5. Validasi</b><small class="d-block text-muted">Server dan RBAC</small></div><div class="pos-help-arrow"><i class="fas fa-arrow-right"></i></div>
            <div class="pos-help-step"><i class="fas fa-receipt"></i><b>6. Selesai</b><small class="d-block text-muted">Struk dan sinkron</small></div>
          </div>
        </div></section>

        <section class="card border-0 rounded-4 shadow-sm mb-3"><div class="card-body p-4">
          <h5 class="fw-bold"><%=Common.getBahasaConfig("Flowchart saat terjadi kendala")%></h5>
          <p class="text-muted small"><%=Common.getBahasaConfig("Jangan membuat transaksi kedua sebelum status transaksi pertama dipastikan.")%></p>
          <div class="pos-help-decision"><div class="pos-help-yes"><i class="fas fa-check-circle me-2"></i>Server menyatakan berhasil<br><small>Buka riwayat dan gunakan transaksi yang sama</small></div><i class="fas fa-arrows-alt-h text-primary"></i><div class="pos-help-no"><i class="fas fa-pause-circle me-2"></i>Belum pasti atau gagal<br><small>Periksa antrean, koneksi, dan Informasi Teknis</small></div></div>
        </div></section>

        <section class="card border-0 rounded-4 shadow-sm mb-3"><div class="card-body p-4">
          <h5 class="fw-bold"><%=Common.getBahasaConfig("Ilustrasi cara membaca halaman POS JSP")%></h5>
          <p class="text-muted"><%=Common.getBahasaConfig("Pada layar desktop, katalog berada di kiri dan keranjang di kanan. Pada layar sempit keduanya bertumpuk dan dibaca dari atas ke bawah.")%></p>
          <div class="pos-help-screen">
            <div class="pos-help-screen-head">① Status sesi kas · pengguna · outlet · koneksi</div>
            <div class="row g-0"><div class="col-md-7"><div class="pos-help-screen-box">② F2 / scan barcode / cari nama<br><br>③ Kategori dan kartu produk</div></div><div class="col-md-5"><div class="pos-help-screen-box pos-help-screen-cart">④ Keranjang · member · promo<br><br>⑤ Total · metode bayar · F12</div></div></div>
          </div>
        </div></section>

        <div id="topikBantuanPOS<%=rnd%>">
          <details class="pos-help-topic" open data-help="tujuan peran rbac akun audit aman">
            <summary>1. Tujuan halaman, pembagian peran, dan prinsip kerja aman</summary>
            <p>Halaman POS mengubah pilihan barang menjadi transaksi penjualan yang tercatat, dibayar, dicetak, dan dapat ditelusuri kembali. Kasir memastikan barang, jumlah, pelanggan, harga, promo, metode pembayaran, dan uang diterima benar sebelum menekan Bayar. Supervisor menangani tindakan yang memerlukan otorisasi, seperti pembatalan, pembukaan laci manual, koreksi tertentu, atau penyelesaian selisih. Admin menyiapkan produk, harga, perangkat, toko, cara bayar, dan hak akses. Tombol yang tidak terlihat atau tindakan yang ditolak tidak selalu berarti aplikasi rusak; akun mungkin memang tidak memiliki izin. Jangan meminjam akun pengguna lain karena seluruh aktivitas dicatat atas identitas yang sedang login. Dokumen yang sudah berhasil atau posted tidak dihapus. Kesalahan diselesaikan melalui retur, pembatalan, atau dokumen pembalik sehingga stok, kas, pajak, dan audit tetap dapat dijelaskan. Sebelum mulai, periksa nama pengguna, outlet, waktu perangkat, status koneksi, printer, dan sesi kas. Jika toko mewajibkan sesi, modal awal harus sama dengan uang fisik. Prinsip utama operasi adalah satu kejadian penjualan menghasilkan satu dokumen dan satu rangkaian pembayaran yang dapat direkonsiliasi. Jangan menekan tombol berulang ketika proses berjalan, jangan membuat ulang transaksi hanya karena struk gagal, dan jangan menghapus penyimpanan browser untuk menyelesaikan antrean sinkronisasi.</p>
          </details>
          <details class="pos-help-topic" open data-help="browser tab refresh f1 f2 f12 popup zoom sesi">
            <summary>2. Orientasi browser, pintasan, dan batas aman navigasi</summary>
            <p>POS JSP berjalan di AIS melalui browser. Pastikan alamat server dan lingkungan login benar. Gunakan satu tab POS aktif untuk satu kasir; dua tab dapat membuat dua keranjang atau dua permintaan pembayaran bersaing. Hindari Back, Forward, Refresh, dan menutup tab saat pembayaran berlangsung. F1 membuka panduan ini, F2 memusatkan kolom pencarian, dan F12 memulai pembayaran. Label tombol adalah rujukan bila konfigurasi pintasan berubah. Browser harus mengizinkan popup untuk layar pelanggan serta dialog cetak. Gunakan zoom seratus persen agar tombol tidak terpotong. Area atas menunjukkan status sesi kas. Area kiri memuat pencarian, kategori, dan katalog. Area kanan memuat keranjang, promo, total, uang tunai, serta tombol Bayar. Di bawahnya terdapat ringkasan inventori dan transaksi terbaru. Pada ponsel, panel bertumpuk; gulir dengan tenang dan jangan mengetuk dua kali. Jika login berakhir, masuk kembali lalu periksa riwayat sebelum mengisi ulang transaksi. Muat ulang halaman hanya setelah memastikan tidak ada permintaan aktif dan keranjang penting sudah disimpan sebagai tertahan. Scanner barcode bekerja seperti keyboard, sehingga fokus harus berada pada pencarian. Bila hasil scan masuk ke kolom uang, tutup dialog dan kembalikan fokus sebelum memindai lagi.</p>
          </details>
          <details class="pos-help-topic" data-help="shift persiapan modal printer scanner outlet sinkron">
            <summary>3. Persiapan awal shift</summary>
            <p>Mulailah dengan memilih outlet yang sama dengan lokasi fisik. Kesalahan outlet menyebabkan stok, nomor struk, kas, dan laporan tercatat di tempat lain. Pastikan tanggal serta jam perangkat benar. Buka sesi kas menggunakan jumlah uang yang benar-benar tersedia di laci, bukan saldo perkiraan. Lakukan uji printer bila perangkat baru dinyalakan atau kertas diganti. Periksa laci dan layar pelanggan. Pastikan katalog menampilkan produk serta harga terbaru; lakukan sinkronisasi apabila kantor baru mengubah master. Lihat riwayat sinkronisasi untuk mengetahui transaksi tertunda. Pisahkan masalah perangkat dari masalah transaksi: printer gagal tidak berarti penjualan gagal, tetapi penolakan server berarti pembayaran belum selesai. Periksa koneksi scanner, printer, popup, dan jaringan sebelum antrean ramai. Pastikan metode pembayaran yang aktif sesuai perangkat EDC atau QR yang tersedia. Siapkan pecahan uang kembalian dan hitung modal awal bersama petugas yang berwenang bila kebijakan mengharuskan. Catat kondisi tidak normal kepada supervisor. Jangan memulai shift menggunakan sesi milik kasir sebelumnya. Jika tombol Buka Sesi tidak tersedia, baca pesan hak akses atau konfigurasi, lalu minta admin memperbaiki role. Pemeriksaan awal yang singkat mencegah koreksi panjang ketika penutupan kas dilakukan.</p>
          </details>
          <details class="pos-help-topic" data-help="produk barcode scan katalog keranjang qty topping stok">
            <summary>4. Mencari produk dan menyusun keranjang</summary>
            <p>Tekan F2 atau klik pencarian, pindai barcode, lalu tunggu produk masuk. Jika tidak ditemukan, cari sebagian nama atau kode dan pilih kategori. Setiap klik kartu menambah produk. Periksa nama, varian, satuan, jumlah, harga satuan, topping, diskon, dan subtotal baris. Produk yang mirip dapat memiliki satuan berbeda. Gunakan tambah atau kurang untuk kuantitas dan hapus hanya baris yang benar-benar batal. Bila dialog ekstra muncul, pilih tambahan sesuai pesanan karena pilihan memengaruhi harga dan uraian struk. Untuk barcode timbangan, periksa berat yang diterjemahkan. Jangan memakai produk lain sebagai pengganti hanya karena stok sistem kosong. Hubungi petugas stok bila barang fisik dan sistem berbeda. Setelah semua barang masuk, bandingkan isi keranjang dengan barang di meja secara berurutan. Jika pelanggan berhenti sementara, gunakan Keranjang Tertahan, beri catatan yang mudah dikenali, lalu pastikan keranjang aktif kosong sebelum pelanggan berikutnya. Ketika memuat keranjang tertahan, periksa ulang harga, promo, pelanggan, stok, dan metode pembayaran karena keadaan dapat berubah. Data tertahan belum menjadi penjualan dan belum boleh dihitung sebagai penerimaan kas. Jangan gunakan fitur tahan sebagai pengganti transaksi kredit.</p>
          </details>
          <details class="pos-help-topic" data-help="member pelanggan promo diskon pajak cashback harga">
            <summary>5. Pelanggan, promo, diskon, pajak, dan harga akhir</summary>
            <p>Pilih pelanggan sebelum pembayaran bila transaksi menggunakan harga anggota, saldo, limit hutang, poin, atau cashback. Cari melalui kode, nama, telepon, kartu, atau QR sesuai fasilitas. Konfirmasi identitas tanpa membacakan data pribadi berlebihan. Setelah pelanggan dipilih, sistem dapat menghitung ulang harga dan promo. Amati subtotal, diskon, cashback, pajak, pembulatan, serta total. Promo otomatis berlaku saat syarat terpenuhi; promo manual perlu dipilih melalui ikon tag. Baca minimal belanja, produk sasaran, masa berlaku, kuota, metode bayar, dan aturan penggabungan. Jangan menjanjikan diskon sebelum angka keranjang berubah. Bila label rak berbeda, verifikasi produk dan periode harga sesuai kebijakan; jangan mengubah harga tanpa izin. Untuk pelanggan umum, bersihkan identitas transaksi sebelumnya agar poin atau hutang tidak masuk ke orang yang salah. Konfirmasikan total akhir setelah pelanggan, promo, dan metode selesai dipilih. Perubahan salah satu unsur dapat memicu perhitungan ulang. Jika promo menghilang, periksa kuantitas, produk, periode, pelanggan, dan cara bayar, bukan menambahkan potongan manual. Cashback bukan selalu pengurang tagihan saat ini; baca cara pencatatannya. Semua angka sebelum Bayar harus dapat dijelaskan kepada pelanggan dengan bahasa sederhana.</p>
          </details>
          <details class="pos-help-topic" data-help="pembayaran tunai transfer qr split kembalian bayar duplikat">
            <summary>6. Pembayaran tunai, non-tunai, dan split</summary>
            <p>Tekan F12 atau Bayar setelah keranjang benar. Pilih tunai, kartu, transfer, QR, saldo, hutang, atau metode lain yang aktif. Pada tunai, masukkan uang yang benar-benar diberikan pelanggan. Hitung uang di hadapan pelanggan, sebutkan nilai diterima dan kembalian, kemudian simpan uang setelah transaksi disetujui. Pada pembayaran non-tunai, jangan menerima tangkapan layar sebagai bukti final; tunggu status berhasil pada alat atau penyedia. Untuk split payment, pilih hingga batas metode yang diizinkan dan alokasikan nominal sampai sisa tepat nol. Pastikan bagian tunai dan non-tunai tidak tertukar. Jangan menekan Bayar berulang ketika tombol sedang memproses. Bila respons lambat, lihat indikator dan riwayat dahulu. Kode unik membantu mencegah duplikasi, tetapi operator tetap wajib memeriksa. Jika berhasil, catat nomor transaksi dan cetak struk. Jika ditolak, baca pesan lengkap, perbaiki penyebab, lalu ulangi hanya tindakan yang gagal. Jangan membuat keranjang baru sebelum yakin transaksi pertama tidak tercatat. Untuk hutang atau saldo, pastikan pelanggan, limit, PIN, dan otorisasi benar. Bila QR kedaluwarsa atau dibatalkan, tutup dialog secara resmi agar polling berhenti sebelum memilih metode lain.</p>
          </details>
          <details class="pos-help-topic" data-help="struk printer cetak ulang laci layar pelanggan tertahan">
            <summary>7. Struk, printer, laci, layar pelanggan, dan keranjang tertahan</summary>
            <p>Struk dicetak setelah pembayaran berhasil. Kegagalan printer tidak membatalkan penjualan. Periksa daya, kertas, tutup, kabel, antrean cetak, pilihan printer, dan ukuran, kemudian cetak ulang transaksi yang sama. Jangan membayar ulang hanya untuk mendapatkan struk. Laci biasanya terbuka ketika pembayaran tunai; pembukaan manual dapat membutuhkan PIN dan alasan audit. Layar pelanggan menampilkan barang, promo, total, dan status. Gunakan sebagai konfirmasi, tetapi keranjang kasir tetap sumber pengendalian. Tombol layar pelanggan dapat membuka atau menutup popup atau monitor kedua. Bila popup tidak muncul, periksa pemblokir popup dan posisi jendela pada monitor lain. Keranjang Tertahan digunakan ketika pelayanan dijeda, bukan untuk mencatat hutang. Beri identitas singkat tanpa data sensitif. Saat melanjutkan, cocokkan pemilik keranjang dan isi barang. Hapus keranjang yang batal hanya menurut kewenangan. Untuk cetak ulang, cari transaksi dari riwayat berdasarkan nomor, waktu, kasir, atau pelanggan. Pastikan yang dicetak adalah dokumen yang benar. Jika printer mencetak karakter aneh, periksa driver, mode ESC/POS, encoding, dan lebar kertas. Jangan mengubah konfigurasi perangkat ketika antrean ramai tanpa uji hasil.</p>
          </details>
          <details class="pos-help-topic" data-help="offline koneksi sinkron antrean gagal server internet">
            <summary>8. Koneksi terputus dan sinkronisasi</summary>
            <p>Perhatikan indikator online, jumlah antrean, waktu percobaan terakhir, dan pesan kegagalan. Transaksi offline disimpan dengan identitas unik sampai server mengakui. Jangan menghapus cache, database browser, profil, atau instalasi selama antrean masih ada. Jalankan sinkronisasi sekali dan tunggu hasil tiap item. Status terkirim berarti server menerima data; status gagal harus dibaca penyebabnya, misalnya sesi berakhir, izin berubah, referensi tidak ditemukan, atau payload tidak valid. Jangan membuat salinan transaksi untuk mengatasi kegagalan. Ketika jaringan kembali, sinkronkan sebelum menutup shift. Cocokkan transaksi lokal, transaksi server, uang tunai, serta metode non-tunai. Jika ada konflik, catat nomor lokal, waktu, nilai, pengguna, outlet, dan pesan. Mode offline tidak menghapus aturan stok, limit, atau otorisasi. Metode tertentu memang harus online; tawarkan alternatif yang sah. Jika browser menampilkan halaman jaringan sementara pembayaran sedang berjalan, tunggu dan buka riwayat setelah koneksi kembali. Jangan menekan Refresh berkali-kali. Keutuhan data lebih penting daripada membuat layar terlihat cepat selesai. Admin dapat memakai riwayat sinkronisasi dan log error untuk menentukan apakah data perlu dikirim ulang atau hanya perlu dimuat ulang.</p>
          </details>
          <details class="pos-help-topic" data-help="retur batal koreksi reversal audit posted">
            <summary>9. Retur, pembatalan, koreksi, dan audit</summary>
            <p>Kesalahan sesudah transaksi berhasil ditangani dengan retur atau pembatalan resmi, bukan menghapus dokumen atau membuat penjualan negatif. Cari transaksi asli dan cocokkan nomor struk, tanggal, kasir, pelanggan, produk, jumlah, serta metode bayar. Retur mengembalikan barang ke stok bila kondisi sesuai; barang rusak atau kedaluwarsa dapat menggunakan jalur stok lain. Pengembalian uang mengikuti metode dan persetujuan toko. Pembatalan penuh memerlukan kewenangan serta alasan. Dokumen posted dipertahankan dan dibuatkan pembalik agar laporan dapat ditelusuri. Jangan memakai akun atau PIN supervisor tanpa kehadirannya. Baca dampak sebelum menyimpan: nilai, stok, kas, poin, hutang, pajak, dan referensi. Cetak bukti koreksi. Salah cetak cukup diselesaikan melalui cetak ulang, bukan retur. Harga salah sebelum bayar diperbaiki di keranjang; harga salah setelah bayar mengikuti prosedur koreksi. Audit melindungi kasir dan toko karena menunjukkan pelaku, waktu, alasan, dan dokumen terkait. Jika server menolak reversal, baca status dokumen, sesi, hak akses, dan alasan minimal. Jangan mencoba mengubah database secara manual. Eskalasi dengan nomor transaksi dan pesan lengkap.</p>
          </details>
          <details class="pos-help-topic" data-help="tutup shift rekonsiliasi selisih kas laporan logout">
            <summary>10. Menutup shift dan rekonsiliasi</summary>
            <p>Sebelum menutup sesi, hentikan transaksi baru dan selesaikan keranjang aktif atau tertahan. Sinkronkan sampai tidak ada antrean. Buka ringkasan: saldo awal, penjualan tunai, penerimaan non-tunai, pengeluaran atau pembukaan laci, retur, pembatalan, setoran, dan kas seharusnya. Hitung uang fisik menurut pecahan di tempat aman. Masukkan kas aktual apa adanya, jangan menyesuaikan agar terlihat sama. Jika ada selisih, hitung ulang dan periksa transaksi terakhir, split payment, retur, kembalian, keranjang tertahan, serta transaksi belum tersinkron. Tulis alasan faktual. Cocokkan kartu, QR, transfer, saldo, dan hutang dengan sumbernya. Supervisor memeriksa sesuai kebijakan. Tutup sesi hanya setelah bukti lengkap, kemudian logout supaya shift berikutnya tidak memakai akun lama. Bila tombol Tutup ditolak, periksa antrean, status sesi, role, dan kolom wajib. Jangan meninggalkan tab terbuka setelah kas diserahkan. Rekonsiliasi rutin membuat laporan harian dapat dipercaya. Untuk bantuan teknis, catat siapa, perangkat, browser, outlet, waktu, langkah, hasil yang diharapkan, hasil aktual, nomor transaksi, dan tangkapan layar tanpa sandi atau data kartu lengkap.</p>
          </details>
          <details class="pos-help-topic" data-help="sesi kas akun perangkat mesin user udin susi">
            <summary>11. Hubungan sesi kas dengan akun, toko, dan perangkat</summary>
            <p>Sesi kas bukan sekadar penanda bahwa tombol Bayar boleh digunakan. Sesi kas merupakan hubungan resmi antara satu akun pengguna, satu perangkat, satu toko, dan satu rentang waktu kerja. Apabila Udin membuka kas pada mesin kasir pertama, hanya pembayaran Udin dari mesin tersebut yang boleh masuk ke ringkasan sesi Udin. Susi yang bekerja pada mesin kedua mempunyai sesi sendiri. Sistem menyimpan identitas pengguna, identitas instalasi browser, nama perangkat, toko, nomor sesi, waktu buka, serta waktu tutup. Akun yang masih mempunyai sesi terbuka tidak boleh membuka sesi kedua pada perangkat atau toko lain. Perangkat yang masih dipakai satu sesi juga tidak boleh dibuka oleh akun lain. Aturan ini mencegah transaksi bercampur ketika dua kasir bekerja bersamaan. Setiap transaksi final menyimpan hubungan langsung ke nomor sesi, bukan hanya mencocokkan nama kasir dan waktu. Transaksi yang sempat disimpan lokal karena jaringan terputus tetap membawa akun, toko, perangkat, dan kode sesi asal. Karena itu kas tidak boleh ditutup selama antrean lokal belum kosong. Pada layar Tutup Kas, periksa chip nama kasir dan nama perangkat sebelum menghitung uang. Penjualan tunai menambah kas fisik, sedangkan pembayaran kartu, QR, transfer, dan saldo masuk ke kelompok non-tunai. Kas seharusnya bukan total seluruh penjualan; kas seharusnya terutama berasal dari modal awal ditambah penerimaan tunai dan penyesuaian kas resmi. Jika perangkat asal rusak, jangan membuka sesi pengganti secara diam-diam. Supervisor perlu memeriksa riwayat, antrean, bukti pembayaran, dan uang fisik, lalu melakukan penutupan resmi dengan alasan yang dapat diaudit. Sesi lama dari versi aplikasi sebelumnya dapat diikat satu kali oleh akun pemilik pada perangkat yang pertama kali dipakai setelah pembaruan. Setelah terikat, sesi tidak dapat berpindah tanpa prosedur supervisor.</p>
          </details>
          <details class="pos-help-topic" data-help="tabel kartu paging filter ekspor xlsx pdf grafik">
            <summary>12. Membaca kartu, tabel, paging, filter, grafik, dan ekspor</summary>
            <p>Kartu ringkasan pada bagian atas halaman menunjukkan keadaan umum, misalnya jumlah transaksi hari ini, omzet, stok menipis, atau nilai berdasarkan jenis pembayaran. Kartu yang dapat diklik membuka atau menyaring data pembentuk angka tersebut. Selalu baca judul, periode, toko, status, dan satuan sebelum menyimpulkan. Grafik membantu melihat kecenderungan, tetapi tinggi batang atau garis tidak selalu berarti keuntungan. Bandingkan jumlah transaksi, penjualan, diskon, retur, biaya, dan metode pembayaran. Tabel menampilkan rincian dalam paging agar browser tidak memuat semua data sekaligus. Tulisan “1–15 dari 240” berarti hanya lima belas baris pertama yang terlihat. Gunakan tombol halaman berikutnya atau nomor halaman; jangan menganggap baris yang tampak sebagai seluruh hasil. Pencarian dapat menerima nama, kode, barcode, nomor dokumen, telepon, atau surel sesuai halaman. Gunakan kata khusus dan cocokkan beberapa identitas sebelum memilih. Filter tanggal mempunyai awal dan akhir; pastikan status dan toko sama dengan laporan yang ingin dibandingkan. Tombol Muat Ulang meminta data terbaru dari server. Ekspor XLSX mengambil hasil sesuai filter, bukan hanya halaman yang tampak. Setelah mengunduh, pastikan judul, periode, jumlah baris, format tanggal, angka, dan ringkasan benar. Barcode panjang perlu diperlakukan sebagai teks agar tidak berubah menjadi notasi ilmiah. PDF digunakan untuk hasil siap baca dan cetak; periksa ukuran kertas, orientasi, nomor halaman, kolom yang terpotong, identitas toko, serta waktu pembuatan. Jangan memakai tangkapan layar sebagai pengganti laporan resmi jika tombol ekspor tersedia. Saat angka berbeda, samakan periode, toko, status posted, zona waktu, pembatalan, retur, dan transaksi tertunda sebelum menyatakan sistem salah.</p>
          </details>
          <details class="pos-help-topic" data-help="produk member telepon unik import excel stok mutasi kedaluwarsa">
            <summary>13. Data induk, impor XLSX, stok, dan pengendalian perubahan</summary>
            <p>Produk, anggota, pemasok, cara bayar, toko, serta aturan diskon adalah data induk yang dipakai banyak transaksi. Kesalahan kecil dapat menyebar ke seluruh laporan. Untuk produk, periksa kode, barcode, nama, kategori, satuan, harga beli, harga jual, pajak, batas stok, status, dan kebijakan retur. Produk baru hanya dibuat setelah pencarian gabungan kode, barcode, dan nama tidak menemukan pasangan yang benar. Jangan membuat produk kedua untuk memperbaiki stok atau harga. Untuk anggota, nomor telepon wajib dan tidak boleh ganda. Cari dengan nama, kode, telepon, dan surel; bila nomor sudah ada, gunakan anggota tersebut atau minta admin memperbaiki datanya. File impor harus XLSX dan mengikuti format unduhan aplikasi. Jangan mengubah nama kolom. Pratinjau perlu menunjukkan nilai lama, nilai baru, serta selisih stok, harga beli, dan harga jual. Baris tanpa perubahan dilewati, sedangkan produk baru tetap ditampilkan walau stok nol. Uji beberapa baris sebelum memproses ribuan data. Stok berubah melalui dokumen penerimaan, penjualan, retur, mutasi, opname, atau penyesuaian resmi. Jangan mengedit angka stok secara langsung agar transaksi dapat dilanjutkan. Untuk mutasi antaroutlet, toko asal dan tujuan harus terhubung pada dokumen yang sama. Untuk kedaluwarsa, prioritaskan barang yang lebih dahulu berakhir, periksa kondisi fisik, karantina barang tidak layak, dan dokumentasikan retur pemasok atau pemusnahan. Retur penjualan harus mengambil item dari transaksi asli dan jumlahnya tidak boleh melebihi jumlah dibeli dikurangi retur sebelumnya. Setiap perubahan besar sebaiknya dilakukan di luar jam ramai, diawasi supervisor, serta diperiksa melalui sampel produk dan laporan sesudah proses selesai.</p>
          </details>
          <details class="pos-help-topic" data-help="error informasi teknis salin log admin solusi timeout database">
            <summary>14. Pesan kesalahan, Informasi Teknis, ErrorLog, dan eskalasi</summary>
            <p>Pesan untuk pengguna harus menjelaskan apa yang terjadi, dampaknya, dan langkah aman yang dapat dicoba. Pesan stok kosong berbeda dari jaringan terputus, hak akses ditolak, sesi kas berada di perangkat lain, data tidak valid, atau printer gagal. Jangan menyebut semua masalah sebagai server tidak dapat dihubungi. Jika stok kosong, periksa toko aktif, barang fisik, transaksi tertunda, penerimaan, dan opname; jangan memaksa angka. Jika jaringan terputus, pertahankan antrean lokal dan biarkan pengiriman ulang memakai kode transaksi yang sama. Jika akses ditolak, admin meninjau grup pengguna dan izin tindakan, bukan memberikan akun orang lain. Jika printer gagal setelah pembayaran berhasil, cetak ulang transaksi yang sama. Bagian Informasi Teknis dapat dibuka ketika bantuan mandiri belum menyelesaikan kendala. Bagian ini memuat kode referensi, request ID, endpoint, tindakan, waktu, jenis exception, dan jejak proses yang diperlukan pengembang. Gunakan tombol Salin Informasi Teknis agar tidak salah ketik. Jangan mengirim sandi, token, PIN, nomor kartu lengkap, atau data pribadi yang tidak perlu. Server wajib menyimpan exception lengkap ke ErrorLog bersama pengguna, toko, perangkat, halaman, dan waktu. Pengguna mengirim kode referensi, langkah sebelum kejadian, hasil yang diharapkan, hasil yang muncul, serta tangkapan layar aman melalui kanal resmi. Sebelum mencoba kembali, periksa riwayat dan antrean untuk memastikan permintaan pertama belum berhasil. Percobaan berulang dapat membuat kebingungan walaupun server mempunyai perlindungan duplikasi. Admin mengelompokkan kejadian serupa, memeriksa pola waktu dan perangkat, lalu menyampaikan status penyelesaian dengan bahasa operasional. Pendekatan ini membuat pengguna dapat mencoba solusi dasar secara mandiri tanpa kehilangan rincian yang dibutuhkan tim teknis.</p>
          </details>
          <details class="pos-help-topic" data-help="contoh skenario alur harian workflow pengguna pemula">
            <summary>15. Contoh alur kerja harian untuk pengguna baru</summary>
            <p>Seorang kasir baru memulai hari dengan login menggunakan akunnya sendiri, memilih toko fisik tempat ia bekerja, memeriksa nama perangkat, koneksi, printer, scanner, serta antrean sinkronisasi. Ia membuka kas dengan modal awal yang dihitung bersama petugas serah terima. Pelanggan pertama membawa beberapa barang. Kasir memindai satu per satu, melihat jumlah pada keranjang, memilih anggota berdasarkan telepon yang sudah terdaftar, lalu mengonfirmasi promo dan total. Pelanggan membayar tunai. Kasir memasukkan nominal yang benar-benar diterima, menekan Bayar satu kali, menunggu server menyatakan berhasil, menyerahkan kembalian, dan mencetak struk. Pelanggan berikutnya membayar QR. Kasir menunggu perangkat pembayaran menyatakan berhasil dan memastikan transaksi masuk kelompok non-tunai. Ketika koneksi terputus pada transaksi berikutnya, aplikasi menyimpan antrean lokal. Kasir tidak menghapus aplikasi dan tidak membuka sesi baru. Setelah jaringan kembali, ia menjalankan sinkronisasi dengan kode transaksi yang sama, memeriksa riwayat, lalu memastikan antrean kosong. Ada pelanggan yang mengembalikan dua dari lima barang. Kasir mencari transaksi asli, memilih dua unit, mengisi kondisi serta alasan, dan meminta supervisor bila kewenangan dibutuhkan. Pada akhir shift, kasir menyelesaikan keranjang tertahan, memastikan tidak ada antrean, membuka ringkasan sesi, membandingkan tunai dan non-tunai, menghitung uang fisik, mencatat selisih apa adanya, kemudian menutup kas dan logout. Contoh ini menunjukkan bahwa setiap tahap mempunyai bukti: produk di keranjang, respons pembayaran, nomor transaksi, dokumen retur, riwayat sinkronisasi, dan ringkasan sesi. Jika satu bukti belum tersedia, kasir berhenti pada titik aman dan tidak mengarang transaksi pengganti.</p>
          </details>
          <details class="pos-help-topic" data-help="kelangsungan usaha mati listrik perangkat rusak internet putus backup">
            <summary>16. Kelangsungan pelayanan saat internet, listrik, atau perangkat bermasalah</summary>
            <p>Gangguan operasional harus ditangani menurut jenisnya. Jika internet tidak stabil tetapi perangkat dan aplikasi masih hidup, jangan melakukan login berulang. Periksa indikator, pertahankan transaksi lokal, gunakan metode pembayaran yang diizinkan saat offline, dan informasikan keadaan kepada pelanggan. Jika listrik padam, amankan uang, dokumen, serta perangkat pembayaran. Setelah listrik kembali, buka aplikasi, login dengan akun yang sama, pilih toko yang benar, lalu periksa sesi, riwayat, dan antrean sebelum membuat transaksi baru. Jika komputer rusak sedangkan sesi masih terbuka, jangan langsung memakai akun yang sama pada mesin lain. Supervisor perlu mengecek apakah ada transaksi lokal yang belum terkirim pada perangkat rusak. Bila antrean masih dapat dipulihkan, selesaikan sinkronisasi dari perangkat asal. Jika tidak, lakukan prosedur penutupan dan rekonstruksi resmi berdasarkan struk, alat pembayaran, stok, serta uang fisik. Jika printer rusak, pembayaran yang sudah berhasil tetap sah; simpan nomor transaksi dan cetak ulang dari perangkat yang diizinkan setelah printer siap. Jika scanner rusak, pencarian manual dapat digunakan dengan verifikasi kode dan nama yang lebih teliti. Jika layar pelanggan gagal, kasir membacakan ringkasan tanpa menyebut data pribadi berlebihan. Jangan menyalin database lokal secara sembarang, menginstal ulang, membersihkan cache, atau mengubah jam perangkat tanpa arahan admin. Setiap kejadian dicatat dengan waktu mulai, waktu pulih, pengguna, toko, perangkat, transaksi terdampak, tindakan yang dilakukan, dan siapa yang menyetujui. Setelah pelayanan pulih, supervisor melakukan rekonsiliasi tambahan agar transaksi, stok, kas, dan non-tunai tetap lengkap. Tujuan prosedur ini bukan sekadar membuat aplikasi kembali terbuka, tetapi memastikan tidak ada transaksi hilang, ganda, atau masuk ke sesi yang salah.</p>
          </details>
          <details class="pos-help-topic" data-help="istilah sederhana transaksi dokumen posted pending sinkron audit">
            <summary>17. Arti istilah penting dalam bahasa sederhana</summary>
            <p>Transaksi adalah kejadian penjualan yang mempunyai nomor dan nilai. Keranjang adalah daftar sementara sebelum pembayaran. Tertahan berarti keranjang disimpan untuk dilanjutkan dan belum menjadi penerimaan. Pending atau menunggu sinkron berarti data sudah disimpan di perangkat tetapi belum diakui server. Berhasil atau synced berarti server sudah menerima. Posted berarti dokumen sudah masuk proses resmi dan koreksinya harus melalui retur, pembatalan, atau pembalik. Idempotensi berarti percobaan mengirim ulang dengan kode yang sama tidak membuat transaksi kedua. Sesi kas adalah rentang kerja satu akun pada satu perangkat dan bukan sekadar tombol buka. Modal awal adalah uang tunai fisik sebelum penjualan. Penjualan tunai adalah pembayaran yang menambah uang laci. Non-tunai adalah kartu, QR, transfer, saldo, atau metode lain yang tidak menambah uang fisik secara langsung. Kas seharusnya adalah nilai yang menurut dokumen semestinya tersedia, sedangkan uang fisik adalah hasil hitungan nyata. Selisih adalah perbedaan keduanya dan harus dicatat apa adanya. Rekonsiliasi adalah kegiatan mencocokkan sistem dengan uang, alat pembayaran, stok, dan dokumen. Audit trail atau jejak audit adalah catatan siapa melakukan apa, kapan, dari toko serta perangkat mana. Role adalah kelompok hak akses. Supervisor adalah petugas yang diberi kewenangan pengawasan, bukan kata sandi yang boleh dipakai bersama. ErrorLog adalah daftar kejadian teknis yang disimpan server. Kode referensi adalah tanda untuk mencari satu kejadian. Informasi Teknis adalah rincian yang dapat dibuka dan disalin untuk admin. XLSX adalah format Excel yang digunakan aplikasi, sedangkan PDF adalah dokumen siap baca atau cetak. Paging berarti data dibagi menjadi halaman kecil. Filter berarti pembatas hasil menurut tanggal, toko, status, atau kata kunci. Memahami istilah ini membantu pengguna mengikuti pesan aplikasi tanpa perlu memahami pemrograman atau database.</p>
          </details>
        </div>

        <div class="pos-help-check mt-3">
          <h5 class="fw-bold text-success"><i class="fas fa-tasks me-2"></i>Checklist cepat sebelum transaksi selesai</h5>
          <ul class="mb-0"><li>Outlet, akun, sesi kas, tanggal, dan koneksi benar.</li><li>Produk, jumlah, pelanggan, promo, pajak, dan total dibaca ulang.</li><li>Metode bayar dan nominal diterima dikonfirmasi.</li><li>Status transaksi diperiksa sebelum cetak ulang atau mencoba kembali.</li><li>Antrean sinkronisasi kosong sebelum sesi ditutup.</li></ul>
        </div>
      </div>
      <div class="modal-footer border-0"><button type="button" class="btn btn-primary rounded-pill px-4" data-bs-dismiss="modal"><%=Common.getBahasaConfig("Tutup Panduan")%></button></div>
    </div>
  </div>
</div>

<div class="modal fade pos-help-modal" id="modalQAPOS<%=rnd%>" tabindex="-1" aria-labelledby="judulQAPOS<%=rnd%>" aria-hidden="true">
  <div class="modal-dialog modal-xl modal-dialog-scrollable"><div class="modal-content border-0 rounded-4">
    <div class="modal-header border-0"><h5 class="modal-title fw-bold" id="judulQAPOS<%=rnd%>"><i class="fas fa-comments text-success me-2"></i><%=Common.getBahasaConfig("Tanya Jawab — Kasir/POS")%></h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div>
    <div class="modal-body p-4">
      <div class="alert alert-success"><strong><%=Common.getBahasaConfig("Pertanyaan yang sering diajukan")%></strong><br><span id="jumlahKataQAPOS<%=rnd%>"><%=Common.getBahasaConfig("Materi minimal 2.000 kata dan dapat dibaca tanpa pengetahuan teknis.")%></span></div>
      <div class="input-group mb-3"><span class="input-group-text bg-white"><i class="fas fa-search"></i></span><input class="form-control" placeholder="<%=Common.getBahasaConfig("Cari pertanyaan: stok, pembayaran, sesi, offline...")%>" oninput="filterQAPOS<%=rnd%>(this.value)"></div>
      <div id="daftarQAPOS<%=rnd%>"></div>
    </div>
    <div class="modal-footer border-0"><button type="button" class="btn btn-success rounded-pill px-4" data-bs-dismiss="modal"><%=Common.getBahasaConfig("Tutup Tanya Jawab")%></button></div>
  </div></div>
</div>
<script>
window.filterBantuanPOS<%=rnd%> = function(q){
  q=(q||'').toLowerCase().trim();
  document.querySelectorAll('#topikBantuanPOS<%=rnd%> .pos-help-topic').forEach(function(el){
    var cocok=!q||(el.textContent+' '+(el.dataset.help||'')).toLowerCase().indexOf(q)>=0;
    el.classList.toggle('pos-help-hidden',!cocok);
    if(q&&cocok)el.open=true;
  });
};
window.siapkanQAPOS<%=rnd%> = function(){
  var target=document.getElementById('daftarQAPOS<%=rnd%>');
  if(!target||target.dataset.siap==='1')return;
  var semua='',kata=0;
  document.querySelectorAll('#topikBantuanPOS<%=rnd%> .pos-help-topic').forEach(function(src,i){
    var judul=(src.querySelector('summary')||{}).textContent||('Topik '+(i+1));
    var isi=(src.querySelector('p')||{}).textContent||'';
    var item=document.createElement('details'); item.className='pos-help-topic qa-pos-item border rounded-3 p-3 mb-2';
    var q=document.createElement('summary'); q.className='fw-bold text-success'; q.textContent='Bagaimana ketentuan '+judul.replace(/^\d+\.\s*/, '').toLowerCase()+'?';
    var a=document.createElement('p'); a.className='mt-3 mb-0'; a.textContent=isi;
    item.appendChild(q); item.appendChild(a); target.appendChild(item); semua+=' '+q.textContent+' '+isi;
  });
  kata=semua.trim().split(/\s+/).filter(Boolean).length;
  document.getElementById('jumlahKataQAPOS<%=rnd%>').textContent=target.children.length+' pertanyaan · '+kata.toLocaleString('id-ID')+' kata · jawaban mengikuti halaman POS ini.';
  target.dataset.siap='1';
};
window.filterQAPOS<%=rnd%> = function(q){
  q=(q||'').toLowerCase().trim();
  document.querySelectorAll('#daftarQAPOS<%=rnd%> .qa-pos-item').forEach(function(el){var cocok=!q||el.textContent.toLowerCase().indexOf(q)>=0;el.classList.toggle('pos-help-hidden',!cocok);if(q&&cocok)el.open=true;});
};
</script>
