package ais.database.model;

// Generated Apr 16, 2010 2:27:16 PM by Hibernate Tools 3.2.4.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;
import org.hibernate.envers.Audited;
import org.hibernate.envers.RelationTargetAuditMode;

import ais.database.model.penelitiandanpengabdian.Artikel;
import ais.database.model.penelitiandanpengabdian.PengajuanPenelitianDanPengabdian;

/**
 * Satu baris asesmen/penilaian atas SATU bentuk kegiatan kinerja dosen
 * (beban kinerja dosen/BKD) untuk seorang {@link Pegawai}. Kegiatan yang
 * dinilai bisa berasal dari salah satu dari beberapa sumber yang saling
 * eksklusif secara konvensi (bergantung {@link #getSpesifikasi()}, nilai
 * konstanta di {@code PenilaianAsesor}): perkuliahan/{@link Matakuliah}
 * (pengajaran), {@link PenunjangKinerjaDosen}, {@link Artikel},
 * {@link BukuBahanAjar}, {@link PengajuanPenelitianDanPengabdian}, atau
 * {@link KegiatanKedosenanPunyaDosen}. Hasil asesmen dirangkum di
 * {@link #getOutput()} (salah satu konstanta {@code OUTPUT_*}, default
 * {@link #OUTPUT_SELESAI}). {@link #getMatakuliah()}/{@link #getJenjang()}
 * DIDERIVASI otomatis dari {@link #perkuliahan} bila terisi, dan
 * {@link #getMasaTugas()} DIDERIVASI otomatis dari salah satu sumber
 * kegiatan di atas atau dari aturan tetap per {@code spesifikasi} bila
 * belum diisi manual.
 *
 * Bank generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Entity(
    dynamicInsert = true,
    dynamicUpdate = true
)
@Audited
@Table(schema = "public", name = "asesemen_penilaian")

public class AsesemenPenilaian extends GeneralValueObject {

	/** Nilai {@link #output}: asesmen selesai (default bila belum diset). */
	public static final String OUTPUT_SELESAI = "Selesai";
	/** Nilai {@link #output}: kegiatan dilanjutkan/masih berjalan. */
	public static final String OUTPUT_LANJUTKAN = "Lanjutkan";
	/** Nilai {@link #output}: kegiatan/asesmen perlu diperbaiki. */
	public static final String OUTPUT_DIPERBAIKI = "Diperbaiki";
	/** Nilai {@link #output}: kegiatan/asesmen ditolak. */
	public static final String OUTPUT_DITOLAK = "Ditolak";
	/** Nilai {@link #output}: kegiatan gagal dilaksanakan. */
	public static final String OUTPUT_GAGAL = "Gagal";
	/** Nilai {@link #output}: hasil lainnya di luar kategori baku. */
	public static final String OUTPUT_LAINNYA = "Lainnya";
	/** Nilai {@link #output}: kegiatan melebihi beban yang ditetapkan. */
	public static final String OUTPUT_BEBAN_LEBIH = "Beban Lebih";

	/**
	 *
	 */
	private static final long serialVersionUID = 2463821577548439808L;
	/** Primary key (identity, auto-generated oleh database). */
	private Long id;
	/** Nama/label pihak yang menyusun atau terakhir mengubah baris asesmen ini (bebas teks, informasional). */
	private String oleh;
	/** Identifier (mis. username/ID pengguna) dari pihak pada {@link #oleh}, dipakai untuk penelusuran audit. */
	private String olehId;

	/**
	 * @return identifier pihak penyusun/pengubah ({@link #olehId}), atau {@code null} bila belum diisi.
	 */
	public String getOlehId() {
		return olehId;
	}

	/**
	 * Menyimpan identifier pihak penyusun/pengubah. Nilai kosong atau
	 * hanya-spasi diabaikan (field lama dipertahankan).
	 *
	 * @param olehId identifier pihak penyusun/pengubah
	 */
	public void setOlehId(String olehId) {if (olehId == null || olehId.trim().isEmpty()) {return;}
		this.olehId = olehId;
	}

	/**
	 * Menyimpan nama pihak penyusun/pengubah. Nilai kosong atau hanya-spasi
	 * diabaikan (field lama dipertahankan), sama seperti {@link #setOlehId(String)}.
	 *
	 * @param oleh nama pihak penyusun/pengubah
	 */
	public void setOleh(String oleh) {if (oleh == null || oleh.trim().isEmpty()) {return;}
		this.oleh = oleh;
	}

	/**
	 * @return nama pihak penyusun/pengubah ({@link #oleh}), atau {@code null} bila belum diisi.
	 */
	public String getOleh() {
		return oleh;
	}

	/**
	 * Callback JPA sebelum UPDATE: memperbarui stempel waktu audit
	 * {@link #tanggal_dirubah} melalui {@link ais.database.hibernate.AuditTimestampInterceptor#ubah(Object)}.
	 */
	@javax.persistence.PreUpdate protected void onUpdate() { ais.database.hibernate.AuditTimestampInterceptor.ubah(this);}
	/** Stempel waktu terakhir diubah; diinisialisasi ke waktu saat objek dibuat dan diperbarui otomatis oleh {@link #onUpdate()}. */
	private Date tanggal_dirubah = ais.ui.util.WaktuUtil.getDate();

	/**
	 * @param tanggal_dirubah stempel waktu perubahan terakhir
	 */
	public void setTanggal_dirubah(Date tanggal_dirubah) {
		this.tanggal_dirubah = tanggal_dirubah;
	}

	/**
	 * @return stempel waktu terakhir diubah ({@link #tanggal_dirubah}).
	 */
	@Temporal(TemporalType.TIMESTAMP)
	public Date getTanggal_dirubah() {
		return tanggal_dirubah;
	}

	/**
	 * @return keterangan asesmen ({@link #keterangan}) apa adanya (TIDAK melalui {@link #getKeterangan()}/trim; bisa {@code null}).
	 */
	public String toString() {
		return keterangan;
	}

	/** Pegawai (dosen) yang dinilai kinerjanya. */
	private Pegawai pegawai;

	/** Beban SKS kegiatan yang dinilai; default 0.0 bila belum diisi (lihat {@link #getSks()}). */
	private Double sks;
	/** Bidang/kategori kegiatan yang dinilai, opsional. */
	private String bidang;
	/** Keterangan/catatan hasil asesmen. */
	private String keterangan;
	/** Tahun akademik berlakunya asesmen. */
	private String tahunAkademik;
	/** Semester berlakunya asesmen. */
	private String semester;
	/** Jenjang terkait; TIDAK dipakai langsung sebagai nilai tersimpan karena {@link #getJenjang()} menimpanya dari jurusan {@link #perkuliahan} bila tersedia. */
	private Jenjang jenjang;
	/** Masa tugas/penugasan kegiatan (mis. "1 semester", "1 hari"); DIDERIVASI otomatis bila kosong (lihat {@link #getMasaTugas()}). */
	private String masaTugas;
	/** Jenis/spesifikasi kegiatan yang dinilai, nilai konstanta {@code PenilaianAsesor.*} (mis. pengajaran, pembimbing TA, penguji proposal). */
	private String spesifikasi;
	/** Bukti pendukung asesmen (mis. path/uraian dokumen bukti); default string kosong bila belum diisi (lihat {@link #getBukti()}). */
	private String bukti;

	/** Mata kuliah yang dinilai; TIDAK dipakai langsung sebagai nilai tersimpan karena {@link #getMatakuliah()} menimpanya dari {@link #perkuliahan} bila tersedia. */
	private Matakuliah matakuliah;
	/** Perkuliahan (kelas mata kuliah) yang dinilai, opsional (konteks pengajaran). */
	private Perkuliahan perkuliahan;
	/** Kegiatan penunjang kinerja dosen yang dinilai, opsional. */
	private PenunjangKinerjaDosen penunjangKinerjaDosen;
	/** Pengajuan penelitian dan pengabdian yang dinilai, opsional; relasi ini TIDAK ikut diaudit Envers ({@link RelationTargetAuditMode#NOT_AUDITED}). */
	private PengajuanPenelitianDanPengabdian pengajuanPenelitianDanPengabdian;
	/** Kegiatan kedosenan (milik dosen) yang dinilai, opsional. */
	private KegiatanKedosenanPunyaDosen kegiatanKedosenanPunyaDosen;
	/** Artikel yang dinilai, opsional. */
	private Artikel artikel;
	/** Buku bahan ajar yang dinilai, opsional. */
	private BukuBahanAjar bukuBahanAjar;

	/** Menandai apakah baris asesmen ini aktif; default aktif ({@code true}) bila belum diset. */
	private Boolean aktif;
	/** Hasil/status asesmen, salah satu konstanta {@code OUTPUT_*}; default {@link #OUTPUT_SELESAI} bila belum diisi (lihat {@link #getOutput()}). */
	private String output;

	/** Konstruktor default (dibutuhkan Hibernate). */
	public AsesemenPenilaian() {
	}

	/**
	 * @return primary key baris ini.
	 */
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", insertable = false, unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	/**
	 * @param id primary key
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * @return keterangan/catatan hasil asesmen, di-trim; string kosong bila {@link #keterangan} {@code null}.
	 */
	@Column(name = "keterangan", nullable = true, columnDefinition = "text")
	public String getKeterangan() {
		return this.keterangan == null ? "" : keterangan.trim();
	}

	/**
	 * @param keterangan keterangan/catatan hasil asesmen
	 */
	public void setKeterangan(String keterangan) {
		this.keterangan = keterangan;
	}

	/**
	 * @return beban SKS kegiatan yang dinilai; default {@code 0.0} bila {@link #sks} belum diisi (nilai default DI-CACHE ke field sebagai efek samping pemanggilan getter ini).
	 */
	@Column(name = "sks_beban", nullable = true)
	public Double getSks() {
		if (sks == null) {
			sks = 0.0;
		}
		return sks;
	}

	/**
	 * @param sks beban SKS kegiatan yang dinilai
	 */
	public void setSks(Double sks) {
		this.sks = sks;
	}

	/**
	 * @return bidang/kategori kegiatan, bisa {@code null}.
	 */
	public String getBidang() {
		return bidang;
	}

	/**
	 * @param bidang bidang/kategori kegiatan yang dinilai
	 */
	public void setBidang(String bidang) {
		this.bidang = bidang;
	}

	/**
	 * @return tahun akademik berlakunya asesmen, bisa {@code null}.
	 */
	public String getTahunAkademik() {
		return tahunAkademik;
	}

	/**
	 * @param tahunAkademik tahun akademik berlakunya asesmen
	 */
	public void setTahunAkademik(String tahunAkademik) {
		this.tahunAkademik = tahunAkademik;
	}

	/**
	 * @return semester berlakunya asesmen, bisa {@code null}.
	 */
	public String getSemester() {
		return semester;
	}

	/**
	 * @param semester semester berlakunya asesmen
	 */
	public void setSemester(String semester) {
		this.semester = semester;
	}

	/**
	 * @return pegawai (dosen) yang dinilai; TIDAK divalidasi ulang via {@code check(...)}, berbeda dari beberapa relasi lain di kelas ini.
	 */
	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE })
	@Fetch(FetchMode.SELECT)
	@JoinColumn(name = "pegawai", nullable = true)
	public Pegawai getPegawai() {
		return pegawai;
	}

	/**
	 * @param pegawai pegawai (dosen) yang dinilai
	 */
	public void setPegawai(Pegawai pegawai) {
		this.pegawai = pegawai;
	}

	/**
	 * Mata kuliah yang dinilai. Bila {@link #perkuliahan} terisi, field
	 * {@link #matakuliah} DITIMPA (efek samping getter, mutatif) oleh
	 * {@link Perkuliahan#getMatakuliah()} milik perkuliahan tersebut —
	 * artinya {@link #matakuliah} yang di-set eksplisit lewat
	 * {@link #setMatakuliah(Matakuliah)} hanya efektif dipakai selama
	 * {@link #perkuliahan} kosong.
	 *
	 * @return mata kuliah yang berlaku (dari perkuliahan bila ada, jika tidak dari field {@link #matakuliah}).
	 */
	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE })
	@Fetch(FetchMode.SELECT)
	@JoinColumn(name = "matakuliah", nullable = true)
	public Matakuliah getMatakuliah() {
		if (perkuliahan != null) {
			matakuliah = perkuliahan.getMatakuliah();
		}
		return matakuliah;
	}

	/**
	 * @param matakuliah mata kuliah yang dinilai (akan DITIMPA oleh {@link #getMatakuliah()} setiap kali dibaca bila {@link #perkuliahan} terisi)
	 */
	public void setMatakuliah(Matakuliah matakuliah) {
		this.matakuliah = matakuliah;
	}

	/**
	 * Jenjang terkait. Selalu divalidasi via {@link #check(Object)},
	 * KEMUDIAN ditimpa (efek samping getter, mutatif) oleh jenjang milik
	 * jurusan {@link #perkuliahan} bila perkuliahan dan jurusannya tersedia
	 * — artinya field {@link #jenjang} yang di-set eksplisit lewat
	 * {@link #setJenjang(Jenjang)} hanya efektif dipakai selama
	 * {@link #perkuliahan} (atau jurusannya) kosong.
	 *
	 * @return jenjang yang berlaku (dari jurusan perkuliahan bila ada, jika tidak dari field {@link #jenjang}).
	 */
	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY)
	@JoinColumn(name = "jenjang")
	public Jenjang getJenjang() {
		jenjang = check(jenjang);
		if (perkuliahan != null && perkuliahan.getJurusan() != null) {
			jenjang = perkuliahan.getJurusan().getJenjang();
		}
		return jenjang;
	}

	/**
	 * @param jenjang jenjang terkait (akan DITIMPA oleh {@link #getJenjang()} setiap kali dibaca bila {@link #perkuliahan} dan jurusannya terisi)
	 */
	public void setJenjang(Jenjang jenjang) {
		this.jenjang = jenjang;
	}

	/**
	 * @return kegiatan penunjang kinerja dosen yang dinilai, bisa {@code null}.
	 */
	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE })
	@Fetch(FetchMode.SELECT)
	@JoinColumn(name = "penunjang_kinerja_dosen", nullable = true)
	public PenunjangKinerjaDosen getPenunjangKinerjaDosen() {
		return penunjangKinerjaDosen;
	}

	/**
	 * @param penunjangKinerjaDosen kegiatan penunjang kinerja dosen yang dinilai
	 */
	public void setPenunjangKinerjaDosen(PenunjangKinerjaDosen penunjangKinerjaDosen) {
		this.penunjangKinerjaDosen = penunjangKinerjaDosen;
	}

	/**
	 * @return pengajuan penelitian dan pengabdian yang dinilai, bisa {@code null}. Relasi ini tidak ikut diaudit Envers.
	 */
	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE })
	@Fetch(FetchMode.SELECT)
	@JoinColumn(name = "pengajuan_penelitian_dan_pengabdian", nullable = true)
	@Audited(targetAuditMode = RelationTargetAuditMode.NOT_AUDITED)
	public PengajuanPenelitianDanPengabdian getPengajuanPenelitianDanPengabdian() {
		return pengajuanPenelitianDanPengabdian;
	}

	/**
	 * @param pengajuanPenelitianDanPengabdian pengajuan penelitian dan pengabdian yang dinilai
	 */
	public void setPengajuanPenelitianDanPengabdian(PengajuanPenelitianDanPengabdian pengajuanPenelitianDanPengabdian) {
		this.pengajuanPenelitianDanPengabdian = pengajuanPenelitianDanPengabdian;
	}

	/**
	 * @return artikel yang dinilai, bisa {@code null}.
	 */
	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE })
	@Fetch(FetchMode.SELECT)
	@JoinColumn(name = "artikel", nullable = true)
	public Artikel getArtikel() {
		return artikel;
	}

	/**
	 * @param artikel artikel yang dinilai
	 */
	public void setArtikel(Artikel artikel) {
		this.artikel = artikel;
	}

	/**
	 * @return jenis/spesifikasi kegiatan yang dinilai (nilai konstanta {@code PenilaianAsesor.*}), bisa {@code null}.
	 */
	public String getSpesifikasi() {
		return spesifikasi;
	}

	/**
	 * @param spesifikasi jenis/spesifikasi kegiatan yang dinilai
	 */
	public void setSpesifikasi(String spesifikasi) {
		this.spesifikasi = spesifikasi;
	}

	/**
	 * @return buku bahan ajar yang dinilai, bisa {@code null}.
	 */
	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE })
	@Fetch(FetchMode.SELECT)
	@JoinColumn(name = "buku_bahan_ajar", nullable = true)
	public BukuBahanAjar getBukuBahanAjar() {
		return bukuBahanAjar;
	}

	/**
	 * @param bukuBahanAjar buku bahan ajar yang dinilai
	 */
	public void setBukuBahanAjar(BukuBahanAjar bukuBahanAjar) {
		this.bukuBahanAjar = bukuBahanAjar;
	}

	/**
	 * Masa tugas/penugasan kegiatan yang dinilai. Bila {@link #masaTugas}
	 * kosong/belum diisi, DIDERIVASI (dan DI-CACHE ke field, efek samping
	 * getter) secara berjenjang: dari masa penugasan salah satu sumber
	 * kegiatan yang terisi ({@link #getPenunjangKinerjaDosen()},
	 * {@link #getArtikel()}, {@link #getBukuBahanAjar()},
	 * {@link #getPengajuanPenelitianDanPengabdian()}, dicek dalam urutan
	 * itu), atau — bila tidak satupun terisi — dari aturan tetap
	 * berdasarkan {@link #getSpesifikasi()} (mis. {@code PENGAJARAN}/
	 * {@code PEMBIMBING_TA}/{@code PEMBIMBING_KKN}/{@code PEMBIMBING_PKL}/
	 * {@code PEMBIMBING_AKADEMIK} bernilai "1 semester";
	 * {@code PENGUJI_PROPOSAL_TA}/{@code PENGUJI_TA} bernilai "1 hari").
	 *
	 * @return masa tugas/penugasan kegiatan, bisa {@code null} bila tidak ada satupun aturan yang cocok.
	 */
	public String getMasaTugas() {
		if (masaTugas == null || masaTugas.trim().isEmpty()) {
			if (getPenunjangKinerjaDosen() != null) {
				masaTugas = getPenunjangKinerjaDosen().getMasaPenugasan();
			} else if (getArtikel() != null) {
				masaTugas = getArtikel().getMasaPenugasan();
			} else if (getBukuBahanAjar() != null) {
				masaTugas = getBukuBahanAjar().getMasaPenugasan();
			} else if (getPengajuanPenelitianDanPengabdian() != null) {
				masaTugas = getPengajuanPenelitianDanPengabdian().getMasaPenugasan();
			} else if (PenilaianAsesor.PENGAJARAN.equals(getSpesifikasi())) {
				masaTugas = "1 semester";
			} else if (PenilaianAsesor.PEMBIMBING_TA.equals(getSpesifikasi())) {
				masaTugas = "1 semester";
			} else if (PenilaianAsesor.PENGUJI_PROPOSAL_TA.equals(getSpesifikasi())) {
				masaTugas = "1 hari";
			} else if (PenilaianAsesor.PENGUJI_TA.equals(getSpesifikasi())) {
				masaTugas = "1 hari";
			} else if (PenilaianAsesor.PEMBIMBING_KKN.equals(getSpesifikasi())) {
				masaTugas = "1 semester";
			} else if (PenilaianAsesor.PEMBIMBING_PKL.equals(getSpesifikasi())) {
				masaTugas = "1 semester";
			} else if (PenilaianAsesor.PEMBIMBING_AKADEMIK.equals(getSpesifikasi())) {
				masaTugas = "1 semester";
			}
		}
		return masaTugas;
	}

	/**
	 * @param masaTugas masa tugas/penugasan kegiatan yang dinilai
	 */
	public void setMasaTugas(String masaTugas) {
		this.masaTugas = masaTugas;
	}

	/**
	 * @return {@code true} bila baris asesmen ini aktif; default {@code true} bila belum diset.
	 */
	public Boolean getAktif() {
		return aktif == null ? true : aktif;
	}

	/**
	 * @param aktif menandai apakah baris asesmen ini aktif
	 */
	public void setAktif(Boolean aktif) {
		this.aktif = aktif;
	}

	/**
	 * @return kegiatan kedosenan (milik dosen) yang dinilai, bisa {@code null}.
	 */
	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE })
	@Fetch(FetchMode.SELECT)
	@JoinColumn(name = "kegiatan_kedosenan_punya_dosen", nullable = true)
	public KegiatanKedosenanPunyaDosen getKegiatanKedosenanPunyaDosen() {
		return kegiatanKedosenanPunyaDosen;
	}

	/**
	 * @param kegiatanKedosenanPunyaDosen kegiatan kedosenan (milik dosen) yang dinilai
	 */
	public void setKegiatanKedosenanPunyaDosen(KegiatanKedosenanPunyaDosen kegiatanKedosenanPunyaDosen) {
		this.kegiatanKedosenanPunyaDosen = kegiatanKedosenanPunyaDosen;
	}

	/**
	 * @return perkuliahan (kelas mata kuliah) yang dinilai, bisa {@code null}.
	 */
	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE })
	@Fetch(FetchMode.SELECT)
	@JoinColumn(name = "perkuliahan", nullable = true)
	public Perkuliahan getPerkuliahan() {
		return perkuliahan;
	}

	/**
	 * @param perkuliahan perkuliahan (kelas mata kuliah) yang dinilai
	 */
	public void setPerkuliahan(Perkuliahan perkuliahan) {
		this.perkuliahan = perkuliahan;
	}

	/**
	 * @return hasil/status asesmen, salah satu konstanta {@code OUTPUT_*}; default {@link #OUTPUT_SELESAI} bila {@link #output} kosong/belum diisi.
	 */
	public String getOutput() {
		return output == null || output.isEmpty() ? AsesemenPenilaian.OUTPUT_SELESAI : output;
	}

	/**
	 * @param output hasil/status asesmen, salah satu konstanta {@code OUTPUT_*}
	 */
	public void setOutput(String output) {
		this.output = output;
	}

	/**
	 * @return bukti pendukung asesmen, di-trim; string kosong bila {@link #bukti} {@code null}.
	 */
	@Column(columnDefinition = "text")
	public String getBukti() {
		return bukti == null ? "" : bukti.trim();
	}

	/**
	 * @param bukti bukti pendukung asesmen
	 */
	public void setBukti(String bukti) {
		this.bukti = bukti;
	}
}
