package ais.database.model;

// Generated Apr 16, 2010 2:27:16 PM by Hibernate Tools 3.2.4.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;
import org.hibernate.envers.Audited;

import ais.database.model.akunting.PostingHistory;
import ais.database.model.koperasi.AnggotaKoperasi;
import ais.database.model.sekolah.CalonSiswa;
import ais.database.model.sekolah.Siswa;

/**
 * Bank generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Entity(dynamicInsert = true, dynamicUpdate = true)
@Audited
@Table(schema = "public", name = "deposit")
public class Deposit extends GeneralValueObject {

	/** 
	 * 
	 */
	private static final long serialVersionUID = 2463821577548439808L;
	private Long id;
	private String oleh;
	private String olehId;

	public String getOlehId() {
		return olehId;
	}

	public void setOlehId(String olehId) {
		if (olehId == null || olehId.trim().isEmpty()) {
			return;
		}
		this.olehId = olehId;
	}

	public void setOleh(String oleh) {
		if (oleh == null || oleh.trim().isEmpty()) {
			return;
		}
		this.oleh = oleh;
	}

	public String getOleh() {
		return oleh;
	}

	@javax.persistence.PreUpdate
	protected void onUpdate() {
		ais.database.hibernate.AuditTimestampInterceptor.ubah(this);
	}

	private Date tanggal_dirubah = ais.ui.util.WaktuUtil.getDate();

	public void setTanggal_dirubah(Date tanggal_dirubah) {
		this.tanggal_dirubah = tanggal_dirubah;
	}

	@Temporal(TemporalType.TIMESTAMP)
	public Date getTanggal_dirubah() {
		return tanggal_dirubah;
	}

	public String toString() {
		return id + "-" + nama;
	}

	private Mahasiswa mahasiswa;
	private BiodataCalonMahasiswa biodataCalonMahasiswa;
	private AnggotaKoperasi anggotaKoperasi;
	private CalonSiswa calonSiswa;
	private Siswa siswa;

	private JenisPembayaran jenisPembayaran;
	private JenisTabungan jenisTabungan;
	private Double nominal;
	private Date waktu;
	private String nama;
	private String keterangan;
	private PostingHistory postingHistory;
	private Date tanggalExpired;
	private KonfigurasiPoinKegiatan konfigurasiPoinKegiatan;

	public Deposit() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", insertable = false, unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "nama", nullable = false, length = 255)
	public String getNama() {
		mahasiswa = getMahasiswa();
		siswa = getSiswa();
		anggotaKoperasi = getAnggotaKoperasi();
		return this.nama == null
				? (mahasiswa == null
						? (siswa == null
								? (anggotaKoperasi == null ? ""
										: anggotaKoperasi.getKode() + " " + anggotaKoperasi.getNama())
								: siswa.getNama())
						: mahasiswa.getNim() + " " + mahasiswa.getNama())
				: this.nama.trim();
	}

	public void setNama(String nama) {
		this.nama = nama;
	}

	@Column(name = "keterangan", nullable = true)
	public String getKeterangan() {
		return this.keterangan;
	}

	public void setKeterangan(String keterangan) {
		this.keterangan = keterangan;
	}

	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY)
	@JoinColumn(name = "mahasiswa", nullable = true)
	public Mahasiswa getMahasiswa() {

		if (getAnggotaKoperasi() != null && getAnggotaKoperasi().getMahasiswa() != null) {
			mahasiswa = getAnggotaKoperasi().getMahasiswa();
		} else {
			biodataCalonMahasiswa = getBiodataCalonMahasiswa();
			if (biodataCalonMahasiswa != null && biodataCalonMahasiswa.getMahasiswa() != null) {
				mahasiswa = biodataCalonMahasiswa.getMahasiswa();
			} else {
				mahasiswa = check(mahasiswa);
			}
		}
		return mahasiswa;
	}

	public void setMahasiswa(Mahasiswa mahasiswa) {
		this.mahasiswa = mahasiswa;
	}

	public Double getNominal() {
		return nominal == null ? 0.0 : nominal;
	}

	public void setNominal(Double nominal) {
		this.nominal = nominal;
	}

	@Temporal(TemporalType.TIMESTAMP)
	public Date getWaktu() {
		return waktu == null ? ais.ui.util.WaktuUtil.getDate() : waktu;
	}

	public void setWaktu(Date waktu) {
		this.waktu = waktu;
	}

	


	

	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY)
	@JoinColumn(name = "jenis_pembayaran", nullable = true)
	public JenisPembayaran getJenisPembayaran() {
		if (jenisPembayaran == null) {
			jenisPembayaran = JenisPembayaran.DEFAULT_JENIS_PEMBAYARAN;
		} else {
			jenisPembayaran = check(jenisPembayaran);
		}

		return jenisPembayaran;
	}

	public void setJenisPembayaran(JenisPembayaran jenisPembayaran) {
		this.jenisPembayaran = jenisPembayaran;
	}

	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY)
	@JoinColumn(name = "jenis_tabungan", nullable = true)
	public JenisTabungan getJenisTabungan() {
		if (jenisTabungan == null) {
			jenisTabungan = JenisTabungan.DEFAULT_JENIS_TABUNGAN;
		} else {
			jenisTabungan = check(jenisTabungan);
		}
		return jenisTabungan;
	}

	public void setJenisTabungan(JenisTabungan jenisTabungan) {
		this.jenisTabungan = jenisTabungan;
	}

	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE })
	@Fetch(FetchMode.SELECT)
	@JoinColumn(name = "posting_history", nullable = true)
	public PostingHistory getPostingHistory() {
		return postingHistory;
	}

	public void setPostingHistory(PostingHistory postingHistory) {
		this.postingHistory = postingHistory;
	}

	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY)
	@JoinColumn(name = "biodata_calon_mahasiswa", nullable = true)
	public BiodataCalonMahasiswa getBiodataCalonMahasiswa() {
		biodataCalonMahasiswa = check(biodataCalonMahasiswa);
		return biodataCalonMahasiswa;
	}

	public void setBiodataCalonMahasiswa(BiodataCalonMahasiswa biodataCalonMahasiswa) {
		this.biodataCalonMahasiswa = biodataCalonMahasiswa;
	}

	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY)
	@JoinColumn(name = "siswa", nullable = true)
	public Siswa getSiswa() {

		if (getAnggotaKoperasi() != null && getAnggotaKoperasi().getSiswa() != null) {
			siswa = getAnggotaKoperasi().getSiswa();
		} else {
			calonSiswa = getCalonSiswa();
			if (calonSiswa != null && calonSiswa.getSiswa() != null) {
				siswa = calonSiswa.getSiswa();
			} else {
				siswa = check(siswa);
			}
		}
		return siswa;
	}

	public void setSiswa(Siswa siswa) {
		this.siswa = siswa;
	}

	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY)
	@JoinColumn(name = "calon_siswa", nullable = true)
	public CalonSiswa getCalonSiswa() {
		calonSiswa = check(calonSiswa);
		return calonSiswa;
	}

	public void setCalonSiswa(CalonSiswa calonSiswa) {
		this.calonSiswa = calonSiswa;
	}

	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY)
	@JoinColumn(name = "anggota_koperasi", nullable = true)
	public AnggotaKoperasi getAnggotaKoperasi() {
		anggotaKoperasi = check(anggotaKoperasi);
		return anggotaKoperasi;
	}

	public void setAnggotaKoperasi(AnggotaKoperasi anggotaKoperasi) {
		this.anggotaKoperasi = anggotaKoperasi;
	}

	/**
	 * Tanggal kedaluwarsa -- HANYA diisi utk deposit berupa voucher (bonus poin Kajian/Disiplin
	 * Kehadiran Pegawai, lihat {@link #konfigurasiPoinKegiatan}); kosong (null) utk top-up tunai biasa
	 * yang tidak pernah kedaluwarsa. Mengikuti persis pola {@code
	 * PencairanDiskon.tanggalExpiredJikaBerupaTopup} yang sudah dipakai
	 * {@code DepositHelper.hitungDeposit()} utk menghitung "cashback hangus" -- field ini dipakai
	 * dengan cara yang SAMA (deposit yg lewat tanggal & belum sempat dibelanjakan dihanguskan dari
	 * saldo berjalan, dihitung ulang tiap query, BUKAN lewat job pembersih terpisah).
	 */
	@Temporal(TemporalType.DATE)
	@Column(name = "tanggal_expired", nullable = true)
	public Date getTanggalExpired() {
		return tanggalExpired;
	}

	public void setTanggalExpired(Date tanggalExpired) {
		this.tanggalExpired = tanggalExpired;
	}

	/**
	 * Penanda sumber voucher (Fitur Voucher Pegawai) -- non-null berarti baris {@link Deposit} ini
	 * ADALAH voucher poin dari kehadiran Kajian/Disiplin Kehadiran (bukan top-up tunai biasa oleh
	 * pegawai/anggota sendiri), dan menunjuk PERSIS jenis kegiatan/aturan poin mana yang
	 * menerbitkannya -- dipakai laporan utk memisahkan "top-up sendiri" vs "bonus voucher perusahaan".
	 */
	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY)
	@JoinColumn(name = "konfigurasi_poin_kegiatan", nullable = true)
	public KonfigurasiPoinKegiatan getKonfigurasiPoinKegiatan() {
		konfigurasiPoinKegiatan = check(konfigurasiPoinKegiatan);
		return konfigurasiPoinKegiatan;
	}

	public void setKonfigurasiPoinKegiatan(KonfigurasiPoinKegiatan konfigurasiPoinKegiatan) {
		this.konfigurasiPoinKegiatan = konfigurasiPoinKegiatan;
	}
}
