package ais.database.model;

// Generated Apr 18, 2010 11:30:58 PM by Hibernate Tools 3.2.4.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.apache.commons.lang.StringUtils;
import org.hibernate.Session;
import org.hibernate.criterion.Restrictions;
import org.hibernate.envers.Audited;
import org.json.JSONObject;

import ais.common.Common;
import ais.common.ConstantValues;
import ais.database.hibernate.HibernateUtil;

/**
 * DetailBiaya generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Entity(dynamicInsert = true, dynamicUpdate = true)
@Audited
@Table(schema = "public", name = "detail_biaya")
public class DetailBiaya extends GeneralValueObject {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1930910520143688237L;
	private Long id;
	private String oleh;
	private String olehId;

	public String getOlehId() {
		return olehId;
	}

	public void setOlehId(String olehId) {
		if (olehId == null || olehId.trim().isEmpty()) {
			return;
		}
		this.olehId = olehId;
	}

	public void setOleh(String oleh) {
		if (oleh == null || oleh.trim().isEmpty()) {
			return;
		}
		this.oleh = oleh;
	}

	public String getOleh() {
		return oleh;
	}

	@javax.persistence.PreUpdate
	protected void onUpdate() {
		ais.database.hibernate.AuditTimestampInterceptor.ubah(this);
	}

	private Date tanggal_dirubah = ais.ui.util.WaktuUtil.getDate();

	public void setTanggal_dirubah(Date tanggal_dirubah) {
		this.tanggal_dirubah = tanggal_dirubah;
	}

	@Temporal(TemporalType.TIMESTAMP)
	public Date getTanggal_dirubah() {
		return tanggal_dirubah;
	}

	public String toString() {
		itemBiaya = getItemBiaya();
		detailSettingBiaya = getDetailSettingBiaya();
		return id + " - " + itemBiaya + "-" + nilaiBiaya
				+ (detailSettingBiaya == null ? "" : "-" + detailSettingBiaya.toString());
	}

	private String tahunAkademik;
	private JenisKegiatan jenisKegiatan;
	private ItemBiaya itemBiaya;
	private String wnaAtauWni;
	private JenisSeleksi jenisSeleksi;
	private Paket paket;
	private GelombangPendaftaran gelombangPendaftaran;
	private String program;
	private Fakultas fakultas;
	private Jurusan jurusan;
	private Jenjang jenjang;
	private Integer semester;
	private Integer angkatan;
	private Double nilaiBiaya;
	private Double nilaiBiayaBaru;
	private Double tunggakanLalu;
	private String nama;
	private StatusMahasiswa statusMahasiswa;
	private Boolean merupakanPembayaran = false;
	private String bahasa;
	private String mulaiBelajarDiSemester = Perkuliahan.GANJIL;
	private StatusAwalMahasiswa statusAwalMahasiswa;
	private Integer bayarKe;
	private JenisTinggalMahasiswa jenisTinggalMahasiswa;
	private Kelas kelas;
	private DetailSettingBiaya detailSettingBiaya;
	private SettingBiayaDetail settingBiayaDetail;

	private String nilaiTambahan1;
	private String nilaiTambahan2;
	private String nilaiTambahan3;
	private SettingBiaya settingBiaya;
	private String keterangan;
	private Date defaultTanggalTagihan;
	private Date defaultTanggalDeadline;
	private Boolean aktif;

	public DetailBiaya() {
	}

	public DetailBiaya(Long id) {
		this.id = id;
	}

	/**
	 * Muat referensi DetailBiaya berdasarkan id secara NULL-SAFE untuk dipakai sebagai
	 * relasi FK pada entity yang akan disimpan (mis. CicilanPembayaran.detailBiaya).
	 *
	 * Mengganti pola lama "new DetailBiaya(id)" (instance TRANSIENT yang hanya berisi id):
	 * id hasil parse (mis. dari idPemBul / data gateway pembayaran) bisa TIDAK ADA di tabel
	 * detail_biaya sehingga INSERT melanggar foreign key constraint. Di sini di-load dari DB
	 * (lookup primary key murah, bisa kena 2nd-level cache &amp; cache session level-1 saat
	 * dipanggil berulang). Bila id null / session tidak ada / data tidak ditemukan -&gt; null
	 * (kolom detail_biaya nullable). Entity yang dikembalikan ter-asosiasi dengan session yang
	 * sama dengan yang akan menyimpan, sehingga aman dari "object referenced by another session".
	 */
	public static DetailBiaya muatRefAman(Session session, Long id) {
		if (id == null || session == null) {
			return null;
		}
		try {
			return (DetailBiaya) session.get(DetailBiaya.class, id);
		} catch (Exception e) {
			return null;
		}
	}

	public String key() {

		jurusan = getJurusan();
		itemBiaya = getItemBiaya();
		statusMahasiswa = getStatusMahasiswa();
		statusAwalMahasiswa = getStatusAwalMahasiswa();
		paket = getPaket();
		gelombangPendaftaran = getGelombangPendaftaran();
		jenisKegiatan = getJenisKegiatan();
		jenisSeleksi = getJenisSeleksi();
		kelas = getKelas();
		jenisTinggalMahasiswa = getJenisTinggalMahasiswa();

		return DetailBiaya.genKey(jurusan, itemBiaya, program, semester, tahunAkademik, angkatan,
				mulaiBelajarDiSemester, statusMahasiswa, statusAwalMahasiswa, paket, gelombangPendaftaran,
				jenisKegiatan, jenisSeleksi, kelas, jenisTinggalMahasiswa, nilaiTambahan1, nilaiTambahan2,
				nilaiTambahan3);
	}

	public static String genKey(Jurusan jurusan, ItemBiaya itemBiaya, String program, Integer semester,
			String tahunAjaran, Integer angkatan, String mulaiBelajar, StatusMahasiswa statusMahasiswa,
			StatusAwalMahasiswa statusAwalMahasiswa, Paket paket, GelombangPendaftaran gelombangPendaftaran,
			JenisKegiatan jenisKegiatan, JenisSeleksi jenisSeleksi, Kelas kelas,
			JenisTinggalMahasiswa jenisTinggalMahasiswa, String nilaiTambahan1, String nilaiTambahan2,
			String nilaiTambahan3) {
		String key = (jurusan == null || jurusan.getId() == null ? 0L : jurusan.getId()) + "-" + (itemBiaya == null || itemBiaya.getId() == null ? 0L : itemBiaya.getId()) + "-"
				+ program + "-" + semester + "-" + tahunAjaran + "-" + angkatan + "-" + mulaiBelajar + "-"
				+ (statusMahasiswa == null || statusMahasiswa.getId() == null ? 0L : statusMahasiswa.getId()) + "-"
				+ (statusAwalMahasiswa == null || statusAwalMahasiswa.getId() == null ? 0L : statusAwalMahasiswa.getId()) + "-"
				+ (paket == null || paket.getId() == null ? 0L : paket.getId()) + "-"
				+ (gelombangPendaftaran == null || gelombangPendaftaran.getId() == null ? 0L : gelombangPendaftaran.getId()) + "-"
				+ (jenisKegiatan == null || jenisKegiatan.getId() == null ? 0L : jenisKegiatan.getId()) + "-" + (kelas == null || kelas.getId() == null ? 0L : kelas.getId())
				+ "-" + (jenisTinggalMahasiswa == null || jenisTinggalMahasiswa.getId() == null ? 0L : jenisTinggalMahasiswa.getId()) + "-"
				+ (nilaiTambahan1 == null ? "" : nilaiTambahan1) + "-" + (nilaiTambahan2 == null ? "" : nilaiTambahan2)
				+ "-" + (nilaiTambahan3 == null ? "" : nilaiTambahan3);
		return key;
	}

	public DetailBiaya(String tahunAkademik) {
		this.tahunAkademik = tahunAkademik;
	}

	public Double hitungTotal(DetailKegiatan detailKegiatan) {
		Double total = getTunggakanLalu() > 0.01 ? getTunggakanLalu()
				: (detailKegiatan == null ? (getNilaiBiayaBaru() == null ? getNilaiBiaya() : getNilaiBiayaBaru())
						: detailKegiatan.getBiaya());
		return total;
	}

	public Double hitungTotal() {
		return hitungTotal(null);
	}

	public Double hitungTotalKegiatan(Kegiatan kegiatan) {
		if (kegiatan == null || kegiatan.getId() == null) {
			return hitungTotal();
		}

		Session session = null;
		try {
			session = HibernateUtil.currentNativeSession();
			return hitungTotalKegiatan(kegiatan, session);
		} catch (Exception e) {
			Common.tampilErrorJikaAdmin(e);
			return hitungTotal();
		} finally {
			ais.action.master.helper.KegiatanPersistenceHelper.closeOpenedSession(session);
		}
	}

	public Double hitungTotalKegiatan(Kegiatan kegiatan, Session session) {
		if (kegiatan == null || kegiatan.getId() == null) {
			return hitungTotal();
		}

		if (!isSessionSiapDipakai(session)) {
			return hitungTotalKegiatan(kegiatan);
		}

		DetailKegiatan detailKegiatan = null;
		try {
			org.hibernate.Criteria criteria = session.createCriteria(DetailKegiatan.class);
			if (getId() != null) {
				criteria.add(Restrictions.eq("detailBiaya.id", getId()));
			} else {
				criteria.add(Restrictions.eq("detailBiaya", this));
			}
			criteria.add(Restrictions.eq("kegiatan.id", kegiatan.getId()));
			detailKegiatan = (DetailKegiatan) criteria.setMaxResults(1).uniqueResult();
		} catch (Exception e) {
			Common.tampilErrorJikaAdmin(e);
			return hitungTotal();
		}

		return hitungTotal(detailKegiatan);
	}

	private boolean isSessionSiapDipakai(Session session) {
		try {
			return session != null && session.isOpen();
		} catch (Exception e) {
			return false;
		}
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", insertable = false, unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "tahun_akademik", nullable = true, length = 20)
	public String getTahunAkademik() {
		return this.tahunAkademik;
	}

	public void setTahunAkademik(String tahunAkademik) {
		this.tahunAkademik = tahunAkademik;
	}

	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY)
	@JoinColumn(name = "item_biaya", nullable = true)
	public ItemBiaya getItemBiaya() {
		itemBiaya = check(itemBiaya);
		return this.itemBiaya;
	}

	public void setItemBiaya(ItemBiaya itemBiaya) {
		this.itemBiaya = itemBiaya;
	}

	@Column(name = "wna_atau_wni", length = 20)
	public String getWnaAtauWni() {
		return this.wnaAtauWni;
	}

	public void setWnaAtauWni(String wnaAtauWni) {
		this.wnaAtauWni = wnaAtauWni;
	}

	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY)
	@JoinColumn(name = "jenis_seleksi", nullable = true)
	public JenisSeleksi getJenisSeleksi() {
		jenisSeleksi = check(jenisSeleksi);
		return this.jenisSeleksi;
	}

	public void setJenisSeleksi(JenisSeleksi jenisSeleksi) {
		this.jenisSeleksi = jenisSeleksi;
	}

	@Column(name = "program")
	public String getProgram() {
		return this.program;
	}

	public void setProgram(String program) {
		this.program = program;
	}

	public void setJurusan(Jurusan jurusan) {
		this.jurusan = jurusan;
	}

	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY)
	@JoinColumn(name = "jurusan", nullable = true)
	public Jurusan getJurusan() {
		jurusan = check(jurusan);
		return jurusan;
	}

	public void setFakultas(Fakultas fakultas) {
		this.fakultas = fakultas;
	}

	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY)
	@JoinColumn(name = "fakultas", nullable = true)
	public Fakultas getFakultas() {
		fakultas = check(fakultas);
		return fakultas;
	}

	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY)
	@JoinColumn(name = "jenjang", nullable = true)
	public Jenjang getJenjang() {
		jurusan = getJurusan();
		if (jurusan != null) {
			jenjang = jurusan.getJenjang();
		}
		jenjang = check(jenjang);
		return this.jenjang;
	}

	public void setJenjang(Jenjang jenjang) {
		this.jenjang = jenjang;
	}

	@Column(name = "semester")
	public Integer getSemester() {

		return this.semester;
	}

	public void setSemester(Integer semester) {
		this.semester = semester;
	}

	@Column(name = "angkatan")
	public Integer getAngkatan() {
		return this.angkatan;
	}

	public void setAngkatan(Integer angkatan) {
		this.angkatan = angkatan;
	}

	@Column(name = "nilai_biaya", precision = 15)
	public Double getNilaiBiaya() {
		itemBiaya = getItemBiaya();
		settingBiayaDetail = getSettingBiayaDetail();
		settingBiaya = getSettingBiaya();
		detailSettingBiaya = getDetailSettingBiaya();
		jurusan = getJurusan();
		if (jurusan != null && jurusan.getId() != null && settingBiaya != null && settingBiaya.getTampilkanPerProdi()
				&& detailSettingBiaya != null) {
			nilaiBiaya = detailSettingBiaya.ambilDefaultBiaya(jurusan);
		} else if (settingBiayaDetail != null && settingBiayaDetail.getId() != null) {
			try {
				JSONObject jsonObject = new JSONObject(settingBiayaDetail.getBiayas());
				nilaiBiaya = jsonObject.isNull(itemBiaya.getId().toString()) ? detailSettingBiaya.getDefaultBiaya()
						: jsonObject.getDouble(itemBiaya.getId().toString());
			} catch (Exception e) {
				e.printStackTrace(); ais.common.ErrorAuditUtil.record(e, "auto-audit src/ais/database/model/DetailBiaya.java:398");
			}
		} else {
			if (detailSettingBiaya != null && settingBiaya != null && settingBiaya.getGunakanBiayaDefault()) {
				nilaiBiaya = detailSettingBiaya.getDefaultBiaya();
			}
		}
		if (nilaiBiaya == null) {
			nilaiBiaya = 0.0;
		}
		return this.nilaiBiaya;
	}

	public void setNilaiBiaya(Double nilaiBiaya) {
		this.nilaiBiaya = nilaiBiaya;
	}

	public void setNama(String nama) {
		this.nama = nama;
	}

	@Column(name = "nama", length = 255, nullable = false)
	public String getNama() {
		if (getItemBiaya() != null && getSettingBiayaDetail() != null
				&& getSettingBiayaDetail().getSettingBiaya() != null
				&& getSettingBiayaDetail().getSettingBiaya().getJumlahPembayaran() > 1) {
			nama = getItemBiaya().getNama() + " ke-" + getBayarKe();
		} else if (getItemBiaya() != null) {
			nama = getItemBiaya().getNama();
		}
		return nama;
	}

	public void setJenisKegiatan(JenisKegiatan jenisKegiatan) {
		this.jenisKegiatan = jenisKegiatan;
	}

	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY)
	@JoinColumn(name = "jenis_kegiatan", nullable = true)
	public JenisKegiatan getJenisKegiatan() {
		jenisKegiatan = check(jenisKegiatan);
		return jenisKegiatan;
	}

	@Override
	public int compareTo(GeneralValueObject arg0) {
		itemBiaya = getItemBiaya();
		if (arg0 instanceof DetailBiaya) {
			try {
				DetailBiaya o = (DetailBiaya) arg0;
				o.itemBiaya = o.getItemBiaya();
				if (o.itemBiaya != null && itemBiaya != null && o.itemBiaya.getKode().trim() != null
						&& itemBiaya.getKode().trim() != null) {
					return o.itemBiaya.getKode().trim().compareTo(itemBiaya.getKode().trim());
				}
			} catch (Exception e) {
				e.printStackTrace(); ais.common.ErrorAuditUtil.record(e, "auto-audit src/ais/database/model/DetailBiaya.java:454");
			}
		}
		return 0;
	}

	public void setStatusMahasiswa(StatusMahasiswa statusMahasiswa) {
		this.statusMahasiswa = statusMahasiswa;
	}

	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY)
	@JoinColumn(name = "status_mahasiswa", nullable = true)
	public StatusMahasiswa getStatusMahasiswa() {
		statusMahasiswa = check(statusMahasiswa);

		if (getSettingBiaya() != null && getSettingBiaya().getStatusMahasiswa() != null) {
			statusMahasiswa = getSettingBiaya().getStatusMahasiswa();
		}

		return statusMahasiswa;
	}

	@Column(name = "merupakan_pembayaran")
	public Boolean getMerupakanPembayaran() {
		return merupakanPembayaran;
	}

	public void setMerupakanPembayaran(Boolean merupakanPembayaran) {
		this.merupakanPembayaran = merupakanPembayaran;
	}

	public String getBahasa() {
		return bahasa;
	}

	public void setBahasa(String bahasa) {
		this.bahasa = bahasa;
	}

	@Column(name = "mulai_belajar_di_semester")
	public String getMulaiBelajarDiSemester() {
		if (mulaiBelajarDiSemester == null) {
			mulaiBelajarDiSemester = Perkuliahan.GANJIL;
		}
		return mulaiBelajarDiSemester;
	}

	public void setMulaiBelajarDiSemester(String mulaiBelajarDiSemester) {
		this.mulaiBelajarDiSemester = mulaiBelajarDiSemester;
	}

	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY)
	@JoinColumn(name = "status_awal_mahasiswa", nullable = true)
	public StatusAwalMahasiswa getStatusAwalMahasiswa() {
		statusAwalMahasiswa = check(statusAwalMahasiswa);
		if (statusAwalMahasiswa == null) {
			statusAwalMahasiswa = ConstantValues.BARU;
		}
		return statusAwalMahasiswa;
	}

	public void setStatusAwalMahasiswa(StatusAwalMahasiswa statusAwalMahasiswa) {
		this.statusAwalMahasiswa = statusAwalMahasiswa;
	}

	@Transient
	public String getKeterangan() {
		if (keterangan == null || keterangan.trim().isEmpty()) {
			itemBiaya = getItemBiaya();
			if (itemBiaya != null) {
				keterangan = itemBiaya.getNama();
			}

			detailSettingBiaya = getDetailSettingBiaya();
			jurusan = getJurusan();

			if (jurusan != null && jurusan.getId() != null && detailSettingBiaya != null
					&& detailSettingBiaya.getSettingBiaya() != null
					&& detailSettingBiaya.getSettingBiaya().getTampilkanPerProdi()) {

				String s = detailSettingBiaya.ambilDefaultKeteranganTagihan(jurusan);
				if (s != null && !s.trim().isEmpty()) {
					keterangan += ", " + s;
				}
			} else if (detailSettingBiaya != null && detailSettingBiaya.getSettingBiaya() != null
					&& detailSettingBiaya.getSettingBiaya().getGunakanBiayaDefault()
					&& !detailSettingBiaya.getDefaultKeterangan().trim().isEmpty()) {
				keterangan += ", " + detailSettingBiaya.getDefaultKeterangan();
			}
		}

		return keterangan;
	}

	public void setKeterangan(String keterangan) {

		if (keterangan == null) {
			return;
		}

//		if (this.keterangan != null && keterangan != null
//				&& !keterangan.trim().equalsIgnoreCase(this.keterangan.trim())) {
//			try {
//				throw new Exception("Who called me?");
//			} catch (Exception e) { ais.common.ErrorAuditUtil.record(e, "auto-audit(empty-catch) src/ais/database/model/DetailBiaya.java:558");
//				e.printStackTrace();
//			}
//		}

		this.keterangan = keterangan;
	}

	public void updateKeterangan(Mahasiswa mahasiswa, Integer semester) {
		ais.action.master.helper.PembayaranNominalModifikasiHelper.updateKeterangan(this, mahasiswa, semester);
	}

	@Column(name = "aktif")
	public Boolean getAktif() {
		return aktif == null ? true : aktif;
	}

	public void setAktif(Boolean aktif) {
		this.aktif = aktif;
	}

//	@Column(name = "nilai_biaya_baru", precision = 15, insertable = false, updatable = false)
	@Transient
	public Double getNilaiBiayaBaru() {
		return nilaiBiayaBaru;
	}

	public void setNilaiBiayaBaru(Double nilaiBiayaBaru) {
		this.nilaiBiayaBaru = nilaiBiayaBaru;
	}

	public Double getTunggakanLalu() {
		if (tunggakanLalu == null) {
			tunggakanLalu = 0.0;
		}
		return tunggakanLalu;
	}

	public void setTunggakanLalu(Double tunggakanLalu) {
		this.tunggakanLalu = tunggakanLalu;
	}

	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY)
	@JoinColumn(name = "paket", nullable = true)
	public Paket getPaket() {
		paket = check(paket);
		return paket;
	}

	public void setPaket(Paket paket) {
		this.paket = paket;
	}

	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY)
	@JoinColumn(name = "jenis_tinggal_mahasiswa", nullable = true)
	public JenisTinggalMahasiswa getJenisTinggalMahasiswa() {
		jenisTinggalMahasiswa = check(jenisTinggalMahasiswa);
		return jenisTinggalMahasiswa;
	}

	public void setJenisTinggalMahasiswa(JenisTinggalMahasiswa jenisTinggalMahasiswa) {
		this.jenisTinggalMahasiswa = jenisTinggalMahasiswa;
	}

	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY)
	@JoinColumn(name = "kelas", nullable = true)
	public Kelas getKelas() {
		kelas = check(kelas);
		return kelas;
	}

	public void setKelas(Kelas kelas) {
		this.kelas = kelas;
	}

	public String getNilaiTambahan1() {
		return nilaiTambahan1;
	}

	public void setNilaiTambahan1(String nilaiTambahan1) {
		this.nilaiTambahan1 = nilaiTambahan1;
	}

	public String getNilaiTambahan2() {
		return nilaiTambahan2;
	}

	public void setNilaiTambahan2(String nilaiTambahan2) {
		this.nilaiTambahan2 = nilaiTambahan2;
	}

	public String getNilaiTambahan3() {
		return nilaiTambahan3;
	}

	public void setNilaiTambahan3(String nilaiTambahan3) {
		this.nilaiTambahan3 = nilaiTambahan3;
	}

	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY)
	@JoinColumn(name = "gelombang_pendaftaran", nullable = true)
	public GelombangPendaftaran getGelombangPendaftaran() {
		gelombangPendaftaran = check(gelombangPendaftaran);
		return gelombangPendaftaran;
	}

	public void setGelombangPendaftaran(GelombangPendaftaran gelombangPendaftaran) {
		this.gelombangPendaftaran = gelombangPendaftaran;
	}

	@Transient
	public Date getDefaultTanggalTagihan() {
		detailSettingBiaya = getDetailSettingBiaya();
		jurusan = getJurusan();

		if (jurusan != null && jurusan.getId() != null && detailSettingBiaya != null
				&& detailSettingBiaya.getSettingBiaya() != null
				&& detailSettingBiaya.getSettingBiaya().getTampilkanPerProdi()) {
			defaultTanggalTagihan = detailSettingBiaya.ambilDefaultTanggalTagihan(jurusan);
		} else if (detailSettingBiaya != null && detailSettingBiaya.getSettingBiaya() != null
				&& detailSettingBiaya.getSettingBiaya().getGunakanBiayaDefault()) {
			defaultTanggalTagihan = detailSettingBiaya.getDefaultTanggalTagihan();
		}

		return defaultTanggalTagihan;
	}

	public void setDefaultTanggalTagihan(Date defaultTanggalTagihan) {
		this.defaultTanggalTagihan = defaultTanggalTagihan;
	}

	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY)
	@JoinColumn(name = "detail_setting_biaya", nullable = true)
	public DetailSettingBiaya getDetailSettingBiaya() {
		detailSettingBiaya = check(detailSettingBiaya);
		return detailSettingBiaya;
	}

	public void setDetailSettingBiaya(DetailSettingBiaya detailSettingBiaya) {
		this.detailSettingBiaya = detailSettingBiaya;
	}

	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY)
	@JoinColumn(name = "setting_biaya_detail", nullable = true)
	public SettingBiayaDetail getSettingBiayaDetail() {
		settingBiayaDetail = check(settingBiayaDetail);
		return settingBiayaDetail;
	}

	public void setSettingBiayaDetail(SettingBiayaDetail settingBiayaDetail) {
		this.settingBiayaDetail = settingBiayaDetail;
	}

	public Integer getBayarKe() {
		return bayarKe == null ? 1 : bayarKe;
	}

	public void setBayarKe(Integer bayarKe) {
		this.bayarKe = bayarKe;
	}

	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY)
	@JoinColumn(name = "setting_biaya", nullable = true)
	public SettingBiaya getSettingBiaya() {
		settingBiaya = check(settingBiaya);
		return settingBiaya;
	}

	public void setSettingBiaya(SettingBiaya settingBiaya) {
		this.settingBiaya = settingBiaya;
	}

	public Double checkDenda(Double nominalModifikasi, Date tanggalBayar, JadwalPembayaran jadwalPembayaran,
			JenisKegiatan old, PengaturanPembayaranBulanan pengaturanPembayaranBulanan) {

		JenisKegiatan jenisKegiatan = this.getJenisKegiatan();

		infoDenda = "";
		Date deadline = pengaturanPembayaranBulanan == null ? null : pengaturanPembayaranBulanan.getDeadline();
		if (jadwalPembayaran != null && jadwalPembayaran.getJenisKegiatan().getDendaJikaTerlambat()) {
			deadline = jadwalPembayaran.getEndDate();
		} else if (jadwalPembayaran != null && jadwalPembayaran.getKhususUntukNim() != null) {
			deadline = jadwalPembayaran.getEndDate();
		}
		// Gunakan deadline dari SettingBiaya sebagai fallback jika belum diisi dari JadwalPembayaran
		if (deadline == null && this.getDefaultTanggalDeadline() != null) {
			deadline = this.getDefaultTanggalDeadline();
		}

		Double nilaiDenda = this.getItemBiaya() != null ? this.getItemBiaya().getDefaultProsentaseDenda() : 0.0;

		if (jenisKegiatan != null && jenisKegiatan.getDendaDibuatPerProdi()) {
			try {
				JSONObject dendaPerProdi = new JSONObject(jenisKegiatan.getDendaPerProdi());
				nilaiDenda = dendaPerProdi.isNull(jurusan.getId().toString()) ? 0.0
						: dendaPerProdi.getDouble(jurusan.getId().toString());

			} catch (Exception e) {
				e.printStackTrace(); ais.common.ErrorAuditUtil.record(e, "auto-audit src/ais/database/model/DetailBiaya.java:756");
			}
		}

		else if (jenisKegiatan != null && jenisKegiatan.getDendaJikaTerlambat()) {
			nilaiDenda = jenisKegiatan.getDefaultProsentaseDenda();
		}

		boolean before = deadline != null && tanggalBayar != null
				? (deadline.before(tanggalBayar)
						&& !Common.dateFormat83.get().format(deadline).equals(Common.dateFormat83.get().format(tanggalBayar)))
				: false;

//		System.out.println("checkDenda -> deadline " + (deadline == null ? "" : Common.dateFormat1.get().format(deadline))
//				+ ", tanggalBayar " + (tanggalBayar == null ? "" : Common.dateFormat1.get().format(tanggalBayar))
//				+ ", before " + before + " nilaiDenda " + nilaiDenda + " nominalModifikasi " + nominalModifikasi);

		if (

		(

		(this.getItemBiaya() != null && this.getItemBiaya().getDendaJikaTerlambat())

				||

				(jenisKegiatan != null && jenisKegiatan.getDendaJikaTerlambat())

		)

				&& nilaiDenda > 0.0 && deadline != null) {

			if (before) {

				Double d = 0.0;

				Integer kelipatan = this.getItemBiaya().getDendaAkanBerlipatTerlambaHari();
				Integer maksimal = this.getItemBiaya().getMaksimalBerlipatTerlambaHari();
				Boolean dalamPersen = this.getItemBiaya().getNilaiDendaDalamPersen();

				if (jenisKegiatan != null && jenisKegiatan.getDendaJikaTerlambat()) {
					kelipatan = jenisKegiatan.getDendaAkanBerlipatTerlambaHari();
					maksimal = jenisKegiatan.getMaksimalBerlipatTerlambaHari();
					dalamPersen = jenisKegiatan.getNilaiDendaDalamPersen();
				}

				if (dalamPersen) {
					d = (nilaiDenda * nominalModifikasi) / 100.0;
				} else {
					d = nilaiDenda;
				}

				int terlambathari = Common.getBetweenTwoDates(deadline, tanggalBayar) - 1;

				if (kelipatan > 0) {
					int jumlahKali = terlambathari / kelipatan;

					if (maksimal > 0 && jumlahKali > maksimal) {
						jumlahKali = maksimal;
					}

					d = d * jumlahKali;
				}

				infoDenda = " Penambahan denda senilai " + Common.numberFormat.get().format(nilaiDenda) + " "
						+ (dalamPersen ? "%" : "") + " karena terlambat " + terlambathari + " hari ("
						+ Common.dateFormat1.get().format(tanggalBayar) + ") senilai " + Common.numberFormat.get().format(d) + ".";

				System.out.println(infoDenda);

				nominalModifikasi += d;
			}
		}
		return nominalModifikasi;
	}

	public Double checkDendaCicilan(CicilanPembayaran cicilanPembayaran, JadwalPembayaran jadwalPembayaran,
			PengaturanPembayaranBulanan pengaturanPembayaranBulanan) {

		infoDenda = "";
		try {
			boolean batal = cicilanPembayaran != null && cicilanPembayaran.getKegiatan() != null
					&& cicilanPembayaran.getPengaturanPembayaranBulanan() != null
					&& StringUtils.contains(cicilanPembayaran.getKegiatan().getPembatalanDenda(),
							"," + cicilanPembayaran.getPengaturanPembayaranBulanan().getId() + ",");
			if (batal) {
				return 0.0;
			}
		} catch (Exception e) {
			// Data cicilan belum lengkap saat listener audit berjalan; lanjut hitung normal.
		}
		// Dipanggil dari PengaturanPembayaranBulanan.checkDendaCicilan <- AuditListener.onPostInsert
		// (setiap insert entity terkait). NPE tak tertangkap di sini akan mengganggu proses
		// simpanKeranjang (WizardPembayaranMhsHelper). Bungkus sisa perhitungan denda dengan
		// try-catch defensif: kegagalan hitung denda berarti "tidak ada denda tambahan" (d=0.0),
		// bukan membatalkan insert.
		Double d = 0.0;
		try {
		Date deadline = pengaturanPembayaranBulanan == null ? getDefaultTanggalDeadline()
				: pengaturanPembayaranBulanan.getDeadline();
		// jadwalPembayaran.getJenisKegiatan() bisa null (tak selalu diisi) — guard sebelum
		// dereference agar tidak NPE di jalur listener AuditListener.onPostInsert.
		if (jadwalPembayaran != null && jadwalPembayaran.getJenisKegiatan() != null
				&& jadwalPembayaran.getJenisKegiatan().getDendaJikaTerlambat()) {
			deadline = jadwalPembayaran.getEndDate();
		} else if (jadwalPembayaran != null && jadwalPembayaran.getKhususUntukNim() != null) {
			deadline = jadwalPembayaran.getEndDate();
		}

		Double nilaiDenda = this.getItemBiaya() != null ? this.getItemBiaya().getDefaultProsentaseDenda() : 0.0;

		if (jadwalPembayaran != null && jadwalPembayaran.getJenisKegiatan() != null
				&& jadwalPembayaran.getJenisKegiatan().getDendaDibuatPerProdi()) {
			try {
				JSONObject dendaPerProdi = new JSONObject(jadwalPembayaran.getJenisKegiatan().getDendaPerProdi());
				nilaiDenda = dendaPerProdi.isNull(jurusan.getId().toString()) ? 0.0
						: dendaPerProdi.getDouble(jurusan.getId().toString());

			} catch (Exception e) {
				e.printStackTrace(); ais.common.ErrorAuditUtil.record(e, "auto-audit src/ais/database/model/DetailBiaya.java:862");
			}
		}

		else if ((jadwalPembayaran != null && jadwalPembayaran.getJenisKegiatan() != null
				&& jadwalPembayaran.getJenisKegiatan().getNilaiDendaDalamPersen())) {
			nilaiDenda = jadwalPembayaran.getJenisKegiatan().getDefaultProsentaseDenda();
		}

		if (this.getItemBiaya() != null
				&& (this.getItemBiaya().getDendaJikaTerlambat()
						|| (jadwalPembayaran != null && jadwalPembayaran.getJenisKegiatan() != null
								&& jadwalPembayaran.getJenisKegiatan().getNilaiDendaDalamPersen()))
				&& nilaiDenda > 0.0 && deadline != null && cicilanPembayaran.getKegiatan() != null
				&& cicilanPembayaran.getTanggal() != null) {
			Date tanggalBayar = cicilanPembayaran.getTanggal();

			boolean before = deadline != null && tanggalBayar != null
					? (deadline.before(tanggalBayar)
							&& !Common.dateFormat83.get().format(deadline).equals(Common.dateFormat83.get().format(tanggalBayar)))
					: false;

			if (before) {

				Integer kelipatan = this.getItemBiaya().getDendaAkanBerlipatTerlambaHari();
				Integer maksimal = this.getItemBiaya().getMaksimalBerlipatTerlambaHari();

				Boolean dalamPersen = this.getItemBiaya().getNilaiDendaDalamPersen();

				if ((jadwalPembayaran != null && jadwalPembayaran.getJenisKegiatan() != null
						&& jadwalPembayaran.getJenisKegiatan().getNilaiDendaDalamPersen())) {
					kelipatan = jadwalPembayaran.getJenisKegiatan().getDendaAkanBerlipatTerlambaHari();
					maksimal = jadwalPembayaran.getJenisKegiatan().getMaksimalBerlipatTerlambaHari();
					dalamPersen = jadwalPembayaran.getJenisKegiatan().getNilaiDendaDalamPersen();
				}

				Double nominalModifikasi = 0.0;

				if (pengaturanPembayaranBulanan != null) {
					nominalModifikasi = cicilanPembayaran.getKegiatan().getMahasiswa() == null
							? pengaturanPembayaranBulanan.getNominal()
							: pengaturanPembayaranBulanan.ambilNominalModifikasi(
									cicilanPembayaran.getKegiatan().getMahasiswa(),
									cicilanPembayaran.getKegiatan().getSemster());
				} else {

					updateKeterangan(cicilanPembayaran.getKegiatan().getMahasiswa(),
							cicilanPembayaran.getKegiatan().getSemster());

					nominalModifikasi = getNilaiBiayaBaru() == null ? getNilaiBiaya() : getNilaiBiayaBaru();
				}

				if (dalamPersen) {
					d = (nilaiDenda * nominalModifikasi) / 100.0;
				} else {
					d = nilaiDenda;
				}

				int terlambathari = Common.getBetweenTwoDates(deadline, tanggalBayar) - 1;

				if (kelipatan > 0) {
					int jumlahKali = terlambathari / kelipatan;

					if (maksimal > 0 && jumlahKali > maksimal) {
						jumlahKali = maksimal;
					}

					d = d * jumlahKali;
				}

				if (d > 0.01) {

					infoDenda = " Penambahan denda senilai " + Common.numberFormat.get().format(nilaiDenda) + " "
							+ (dalamPersen ? "%" : "") + " karena terlambat " + terlambathari + " hari senilai "
							+ Common.numberFormat.get().format(d) + ".";

					cicilanPembayaran.setDenda(d);
					cicilanPembayaran.setNilaiAsli(nominalModifikasi);
					cicilanPembayaran.setNilai(nominalModifikasi + d);
					String keterangan = cicilanPembayaran.getKeterangan();
					keterangan = org.apache.commons.lang3.StringUtils.replace(keterangan, infoDenda, "") + infoDenda;
					cicilanPembayaran.setKeterangan(keterangan.trim());

					System.out.println("cicilan " + cicilanPembayaran + ". " + infoDenda);
				}
			}

		}
		} catch (Exception e) { ais.common.ErrorAuditUtil.record(e, "auto-audit(empty-catch) src/ais/database/model/DetailBiaya.java:checkDendaCicilan-lazy");
			// kegagalan hitung denda dianggap "tidak ada denda tambahan"; d tetap 0.0
		}
		return d;
	}

	private String infoDenda;
	private String kelamin;
	private AfiliasiCalonMahasiswa afiliasiCalonMahasiswa;

	@Transient
	public String getInfoDenda() {
		return infoDenda == null ? "" : infoDenda;
	}

	public void setInfoDenda(String infoDenda) {
		this.infoDenda = infoDenda;
	}

	public String getKelamin() {
		if (kelamin != null && !(kelamin.equals("Laki-laki") || kelamin.equals("Perempuan"))) {
			kelamin = null;
		}

		settingBiaya = getSettingBiaya();
		if (settingBiaya != null) {
			kelamin = settingBiaya.getKelamin();
		}
		return kelamin;
	}

	public void setKelamin(String kelamin) {
		this.kelamin = kelamin;
	}

	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY)
	@JoinColumn(name = "afiliasi_calon_mahasiswa", nullable = true)
	public AfiliasiCalonMahasiswa getAfiliasiCalonMahasiswa() {
		afiliasiCalonMahasiswa = check(afiliasiCalonMahasiswa);
		return afiliasiCalonMahasiswa;
	}

	public void setAfiliasiCalonMahasiswa(AfiliasiCalonMahasiswa afiliasiCalonMahasiswa) {
		this.afiliasiCalonMahasiswa = afiliasiCalonMahasiswa;
	}

	@Transient
	public Date getDefaultTanggalDeadline() {
		detailSettingBiaya = getDetailSettingBiaya();
		jurusan = getJurusan();

		if (jurusan != null && jurusan.getId() != null && detailSettingBiaya != null
				&& detailSettingBiaya.getSettingBiaya() != null
				&& detailSettingBiaya.getSettingBiaya().getTampilkanPerProdi()) {
			defaultTanggalDeadline = detailSettingBiaya.ambilDefaultTanggalDeadline(jurusan);
		} else if (detailSettingBiaya != null && detailSettingBiaya.getSettingBiaya() != null
				&& detailSettingBiaya.getSettingBiaya().getGunakanBiayaDefault()) {
			defaultTanggalDeadline = detailSettingBiaya.getDefaultTanggalDeadline();
		}

		return defaultTanggalDeadline;
	}

	public void setDefaultTanggalDeadline(Date defaultTanggalDeadline) {
		this.defaultTanggalDeadline = defaultTanggalDeadline;
	}
}
