package ais.database.model;

// Generated Apr 16, 2010 2:27:16 PM by Hibernate Tools 3.2.4.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.envers.Audited;

import ais.database.model.sekolah.Guru;
import ais.database.model.sekolah.Siswa;

/**
 * Bank generated by hbm2java
 *
 * <p><b>Keanggotaan/kepesertaan seseorang dalam sebuah {@link FormulirKegiatan}.</b> Satu baris
 * berarti "satu orang mendaftar/mengikuti kegiatan tersebut", dengan pesertanya diidentifikasi
 * lewat SALAH SATU dari lima FK nullable terpisah per jenis akun -- {@link #getMahasiswa()},
 * {@link #getDosen()}, {@link #getSiswa()}, {@link #getGuru()}, {@link #getPegawai()} -- pola yang
 * sama dipakai {@link KunjunganTamu}. Dukungan {@link #getPegawai()} ditambahkan belakangan khusus
 * untuk fitur Voucher Pegawai (kehadiran Kajian), mengikuti persis pola kolom
 * guru/dosen/siswa yang sudah ada agar konsisten, bukan referensi generik/polimorfik.</p>
 *
 * <p>{@link #getNim()} dan {@link #getNama()} adalah getter turunan: bila {@link #mahasiswa}
 * terisi, keduanya diisi ulang dari data mahasiswa tersebut setiap kali dipanggil (lihat javadoc
 * masing-masing untuk konsekuensi mutasinya). {@link #getAcc()} menandai apakah kepesertaan sudah
 * disetujui/diverifikasi (mis. oleh panitia kegiatan).</p>
 */
@Entity
@org.hibernate.annotations.Entity(dynamicInsert = true, dynamicUpdate = true)
@Audited
@Table(schema = "public", name = "formulir_kegiatan_peserta")
public class FormulirKegiatanPeserta extends GeneralValueObject {

	/**
	 *
	 */
	private static final long serialVersionUID = 2463821577548439808L;

	/** Primary key baris kepesertaan, dihasilkan basis data (strategi {@code IDENTITY}). */
	private Long id;
	/** Jejak "siapa yang menulis baris ini", diisi otomatis lewat {@link #setOleh(String)}. */
	private String oleh;
	/** Pendamping {@link #oleh}. Lihat {@link #getOlehId()}. */
	private String olehId;

	/**
	 * Mengembalikan rantai jejak pemanggil yang tersimpan bersama {@link #oleh}, diisi otomatis
	 * oleh {@code AuditTimestampInterceptor}.
	 *
	 * @return jejak pemanggil; boleh {@code null} bila belum pernah diisi
	 */
	public String getOlehId() {
		return olehId;
	}

	/**
	 * Menyetel jejak pemanggil {@link #getOlehId()}. Setter ini <b>mengabaikan diam-diam</b>
	 * nilai {@code null}/kosong sehingga jejak lama tidak dapat ditimpa nilai hampa.
	 *
	 * @param olehId jejak pemanggil baru; {@code null}/kosong diabaikan tanpa peringatan
	 */
	public void setOlehId(String olehId) {
		if (olehId == null || olehId.trim().isEmpty()) {
			return;
		}
		this.olehId = olehId;
	}

	/**
	 * Menyetel identitas pelaku penyimpanan baris ini. Nilai {@code null}/kosong diabaikan
	 * diam-diam agar jejak lama tidak tertimpa nilai hampa.
	 *
	 * @param oleh nama/identitas pelaku; {@code null}/kosong diabaikan tanpa peringatan
	 */
	public void setOleh(String oleh) {
		if (oleh == null || oleh.trim().isEmpty()) {
			return;
		}
		this.oleh = oleh;
	}

	/**
	 * Mengembalikan identitas pelaku yang terakhir menyimpan baris ini.
	 *
	 * @return nama/identitas pelaku; boleh {@code null} bila belum pernah diisi
	 */
	public String getOleh() {
		return oleh;
	}

	/**
	 * <i>Callback</i> JPA {@link javax.persistence.PreUpdate} yang memperbarui
	 * {@link #getTanggal_dirubah()}/{@link #getOleh()}/{@link #getOlehId()} lewat
	 * {@code AuditTimestampInterceptor} pada setiap UPDATE baris.
	 */
	@javax.persistence.PreUpdate
	protected void onUpdate() {
		ais.database.hibernate.AuditTimestampInterceptor.ubah(this);
	}

	/** Stempel waktu terakhir baris diubah, diinisialisasi ke waktu server saat objek dibuat. */
	private Date tanggal_dirubah = ais.ui.util.WaktuUtil.getDate();

	/**
	 * Menyetel stempel waktu perubahan terakhir. Umumnya diurus otomatis oleh {@link #onUpdate()}.
	 *
	 * @param tanggal_dirubah stempel waktu baru
	 */
	public void setTanggal_dirubah(Date tanggal_dirubah) {
		this.tanggal_dirubah = tanggal_dirubah;
	}

	/**
	 * Mengembalikan stempel waktu perubahan terakhir (presisi TIMESTAMP).
	 *
	 * @return waktu terakhir baris disimpan/diubah
	 */
	@Temporal(TemporalType.TIMESTAMP)
	public Date getTanggal_dirubah() {
		return tanggal_dirubah;
	}

	/**
	 * Representasi teks baris, berupa id digabung {@link #getFormulirKegiatan()} dan
	 * {@link #getMahasiswa()}. <b>Method ini bermutasi</b> field {@link #formulirKegiatan} dan
	 * {@link #mahasiswa} (memanggil ulang getter masing-masing yang menormalkan proxy Hibernate).
	 */
	public String toString() {
		formulirKegiatan = getFormulirKegiatan();
		mahasiswa = getMahasiswa();
		return id + "-" + formulirKegiatan + "-" + mahasiswa;
	}

	/** Kegiatan yang diikuti. Kolom FK wajib {@code formulir_kegiatan}. */
	private FormulirKegiatan formulirKegiatan;
	/** Akun mahasiswa peserta, bila peserta adalah mahasiswa. Lihat {@link #getMahasiswa()}. */
	private Mahasiswa mahasiswa;
	/** Akun dosen peserta, bila peserta adalah dosen. Lihat {@link #getDosen()}. */
	private Dosen dosen;
	/** Akun siswa peserta, bila peserta adalah siswa. Lihat {@link #getSiswa()}. */
	private Siswa siswa;
	/** Akun guru peserta, bila peserta adalah guru. Lihat {@link #getGuru()}. */
	private Guru guru;
	/** Akun pegawai peserta (fitur Voucher Pegawai). Lihat {@link #getPegawai()}. */
	private Pegawai pegawai;
	/** Keterangan bebas kepesertaan. */
	private String keterangan;

	/** Jurusan peserta, diturunkan dari {@link #mahasiswa} bila terisi. Lihat {@link #getJurusan()}. */
	private Jurusan jurusan;
	/** NIM peserta, diturunkan dari {@link #mahasiswa} bila terisi. Lihat {@link #getNim()}. */
	private String nim;

	/** Nilai akhir kepesertaan (teks bebas, mis. angka atau huruf mutu). */
	private String nilai;

	/**
	 * Mengembalikan NIM peserta.
	 *
	 * <p><b>Getter ini bermutasi</b> field {@link #nim}: bila {@link #mahasiswa} terisi, nilainya
	 * SELALU ditimpa dari {@code mahasiswa.getNim()} setiap kali getter ini dipanggil, mengalahkan
	 * nilai apa pun yang sebelumnya disetel manual lewat {@link #setNim(String)}. Nilai manual
	 * hanya bertahan bila {@link #mahasiswa} kosong (mis. peserta bukan mahasiswa).</p>
	 *
	 * @return NIM peserta; nilai manual bila {@link #mahasiswa} kosong, atau NIM mahasiswa terkait
	 */
	public String getNim() {
		if (mahasiswa != null) {
			nim = mahasiswa.getNim();
		}
		return nim;
	}

	/**
	 * Menyetel NIM peserta secara manual. Hanya bertahan bila {@link #mahasiswa} kosong; bila
	 * relasi mahasiswa terisi, {@link #getNim()} akan menimpanya lagi pada pemanggilan berikutnya.
	 *
	 * @param nim NIM baru
	 */
	public void setNim(String nim) {
		this.nim = nim;
	}

	/** Nama peserta, diturunkan dari {@link #mahasiswa} bila terisi. Lihat {@link #getNama()}. */
	private String nama;

	/**
	 * Mengembalikan nama peserta.
	 *
	 * <p><b>Getter ini bermutasi</b> field {@link #nama}: sama seperti {@link #getNim()}, bila
	 * {@link #mahasiswa} terisi nilainya SELALU ditimpa dari {@code mahasiswa.getNama()} setiap
	 * kali getter ini dipanggil, mengalahkan nilai manual yang sebelumnya disetel.</p>
	 *
	 * @return nama peserta; nilai manual bila {@link #mahasiswa} kosong, atau nama mahasiswa terkait
	 */
	public String getNama() {
		if (mahasiswa != null) {
			nama = mahasiswa.getNama();
		}
		return nama;
	}

	/**
	 * Menyetel nama peserta secara manual. Hanya bertahan bila {@link #mahasiswa} kosong.
	 *
	 * @param nama nama baru
	 */
	public void setNama(String nama) {
		this.nama = nama;
	}

	/** Kode bebas kepesertaan (mis. kode registrasi internal). */
	private String kode;

	/** Penanda kepesertaan sudah disetujui/diverifikasi. Lihat {@link #getAcc()}. */
	private Boolean acc;

	/** Konstruktor tanpa argumen yang diwajibkan JPA/Hibernate. */
	public FormulirKegiatanPeserta() {
	}

	/**
	 * Mengembalikan primary key baris kepesertaan.
	 *
	 * <p>Perhatikan {@code insertable = false}: nilai id sepenuhnya dihasilkan basis data
	 * (strategi {@code IDENTITY}), sehingga memanggil {@link #setId(Long)} sebelum menyimpan
	 * tidak memaksakan id tertentu.</p>
	 *
	 * @return id baris; {@code null} selama objek belum pernah disimpan
	 */
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", insertable = false, unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	/**
	 * Menyetel primary key baris kepesertaan. Hanya relevan bagi Hibernate saat mengisi objek
	 * dari hasil query, karena kolom dipetakan {@code insertable = false} (lihat {@link #getId()}).
	 *
	 * @param id nilai primary key
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * Mengembalikan kegiatan yang diikuti. Relasi wajib ({@code nullable = false}), diambil
	 * malas ({@code FetchType.LAZY}) dan dinormalkan lewat {@code check(...)} dari
	 * {@link GeneralValueObject} agar aman terhadap proxy Hibernate yang belum terinisialisasi.
	 *
	 * @return kegiatan terkait; tidak seharusnya {@code null} pada baris yang valid
	 */
	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY)
	@JoinColumn(name = "formulir_kegiatan", nullable = false)
	public FormulirKegiatan getFormulirKegiatan() {
		formulirKegiatan = check(formulirKegiatan);
		return formulirKegiatan;
	}

	/**
	 * Menyetel kegiatan yang diikuti.
	 *
	 * @param formulirKegiatan kegiatan baru
	 */
	public void setFormulirKegiatan(FormulirKegiatan formulirKegiatan) {
		this.formulirKegiatan = formulirKegiatan;
	}

	/**
	 * Mengembalikan akun mahasiswa peserta, bila peserta ini adalah mahasiswa.
	 *
	 * @return akun mahasiswa terkait; {@code null} bila peserta bukan mahasiswa
	 */
	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY)
	@JoinColumn(name = "mahasiswa", nullable = true)
	public Mahasiswa getMahasiswa() {
		mahasiswa = check(mahasiswa);
		return mahasiswa;
	}

	/**
	 * Menyetel akun mahasiswa peserta.
	 *
	 * @param mahasiswa akun mahasiswa; boleh {@code null}
	 */
	public void setMahasiswa(Mahasiswa mahasiswa) {
		this.mahasiswa = mahasiswa;
	}

	/**
	 * Mengembalikan kode bebas kepesertaan.
	 *
	 * @return kode; boleh {@code null}
	 */
	public String getKode() {
		return kode;
	}

	/**
	 * Menyetel kode bebas kepesertaan.
	 *
	 * @param kode kode baru; boleh {@code null}
	 */
	public void setKode(String kode) {
		this.kode = kode;
	}

	/**
	 * Mengembalikan jurusan peserta.
	 *
	 * <p><b>Getter ini bermutasi</b> field {@link #jurusan}: bila {@link #mahasiswa} terisi,
	 * nilainya ditimpa dari {@code mahasiswa.getJurusan()} sebelum dinormalkan lewat
	 * {@code check(...)}.</p>
	 *
	 * @return jurusan peserta; diturunkan dari mahasiswa terkait bila ada
	 */
	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY)
	@JoinColumn(name = "jurusan", nullable = true)
	public Jurusan getJurusan() {
		if (mahasiswa != null) {
			jurusan = mahasiswa.getJurusan();
		}
		jurusan = check(jurusan);
		return jurusan;
	}

	/**
	 * Menyetel jurusan peserta secara manual. Hanya bertahan bila {@link #mahasiswa} kosong.
	 *
	 * @param jurusan jurusan baru
	 */
	public void setJurusan(Jurusan jurusan) {
		this.jurusan = jurusan;
	}

	/**
	 * Mengembalikan keterangan bebas kepesertaan.
	 *
	 * @return keterangan; boleh {@code null}
	 */
	public String getKeterangan() {
		return keterangan;
	}

	/**
	 * Menyetel keterangan bebas kepesertaan.
	 *
	 * @param keterangan keterangan baru; boleh {@code null}
	 */
	public void setKeterangan(String keterangan) {
		this.keterangan = keterangan;
	}

	/**
	 * Mengembalikan penanda apakah kepesertaan sudah disetujui/diverifikasi. Default
	 * {@code false} bila belum disetel eksplisit.
	 *
	 * @return {@code true} bila sudah disetujui
	 */
	public Boolean getAcc() {
		return acc == null ? false : acc;
	}

	/**
	 * Menyetel penanda persetujuan kepesertaan.
	 *
	 * @param acc nilai baru; {@code null} berarti kembali ke bawaan ({@code false})
	 */
	public void setAcc(Boolean acc) {
		this.acc = acc;
	}

	/**
	 * Mengembalikan akun dosen peserta, bila peserta ini adalah dosen.
	 *
	 * @return akun dosen terkait; {@code null} bila peserta bukan dosen
	 */
	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY)
	@JoinColumn(name = "dosen", nullable = true)
	public Dosen getDosen() {
		dosen = check(dosen);
		return dosen;
	}

	/**
	 * Menyetel akun dosen peserta.
	 *
	 * @param dosen akun dosen; boleh {@code null}
	 */
	public void setDosen(Dosen dosen) {
		this.dosen = dosen;
	}

	/**
	 * Mengembalikan nilai akhir kepesertaan (teks bebas).
	 *
	 * @return nilai; boleh {@code null}
	 */
	public String getNilai() {
		return nilai;
	}

	/**
	 * Menyetel nilai akhir kepesertaan.
	 *
	 * @param nilai nilai baru; boleh {@code null}
	 */
	public void setNilai(String nilai) {
		this.nilai = nilai;
	}

	/**
	 * Mengembalikan akun siswa peserta, bila peserta ini adalah siswa.
	 *
	 * @return akun siswa terkait; {@code null} bila peserta bukan siswa
	 */
	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY)
	@JoinColumn(name = "siswa", nullable = true)
	public Siswa getSiswa() {
		siswa = check(siswa);
		return siswa;
	}

	/**
	 * Menyetel akun siswa peserta.
	 *
	 * @param siswa akun siswa; boleh {@code null}
	 */
	public void setSiswa(Siswa siswa) {
		this.siswa = siswa;
	}

	/**
	 * Mengembalikan akun guru peserta, bila peserta ini adalah guru.
	 *
	 * @return akun guru terkait; {@code null} bila peserta bukan guru
	 */
	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY)
	@JoinColumn(name = "guru", nullable = true)
	public Guru getGuru() {
		guru = check(guru);
		return guru;
	}

	/**
	 * Menyetel akun guru peserta.
	 *
	 * @param guru akun guru; boleh {@code null}
	 */
	public void setGuru(Guru guru) {
		this.guru = guru;
	}

	/**
	 * Peserta Pegawai -- ditambahkan untuk fitur Voucher Pegawai (kehadiran Kajian), mengikuti persis
	 * pola kolom {@code guru}/{@code dosen}/{@code siswa} di atas: FK nullable terpisah per jenis
	 * peserta (bukan referensi generik/polimorfik), supaya konsisten dengan kolom yang sudah ada.
	 */
	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY)
	@JoinColumn(name = "pegawai", nullable = true)
	public Pegawai getPegawai() {
		pegawai = check(pegawai);
		return pegawai;
	}

	/**
	 * Menyetel akun pegawai peserta.
	 *
	 * @param pegawai akun pegawai; boleh {@code null}
	 */
	public void setPegawai(Pegawai pegawai) {
		this.pegawai = pegawai;
	}
}
