package ais.database.model;

// Generated Apr 16, 2010 2:27:16 PM by Hibernate Tools 3.2.4.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.Set;
import java.util.TreeSet;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OrderBy;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.envers.Audited;

import ais.database.model.surat.NomorSurat;

/**
 * Entity <b>master jenis pengaduan</b> — daftar kategori aduan yang boleh dipilih saat seseorang
 * mengajukan {@link Pengaduan} (misalnya "Keluhan Layanan Akademik", "Kerusakan Sarana",
 * "Pelaporan Pelanggaran"). Dipetakan ke tabel {@code public.jenis_pengaduan} lewat anotasi
 * (tidak ada berkas {@code .hbm.xml}; pendaftarannya ada di {@code hibernate.cfg.xml} baris 437,
 * {@code <mapping class="ais.database.model.JenisPengaduan" />}), dengan {@code dynamicInsert} +
 * {@code dynamicUpdate} dan {@link org.hibernate.envers.Audited @Audited} sehingga Envers merekam
 * setiap versi baris ke tabel revisi.
 *
 * <p>Komentar {@code "Bank generated by hbm2java"} di atas deklarasi aslinya adalah sisa
 * salin-tempel dari entity {@code Bank} — tidak ada hubungannya dengan jenis pengaduan. Hal yang
 * sama berlaku untuk nilai {@link #serialVersionUID} yang identik di puluhan entity hasil
 * generator yang sama.</p>
 *
 * <h2>Apa yang sebenarnya ditentukan oleh satu baris di sini</h2>
 *
 * <p>Baris jenis pengaduan mengendalikan <b>empat</b> hal, tidak lebih:</p>
 *
 * <ol>
 *   <li><b>Label kategori</b> yang muncul di combo pemilihan jenis pada layar/API pengaduan
 *       ({@link #getNama()} dan {@link #getKode()}).</li>
 *   <li><b>Format nomor agenda</b> lewat {@link #getNomorSurat()}. {@code
 *       PengaduanAction#generateCode(JenisPengaduan, boolean)} memanggil {@link
 *       NomorSurat#format(Long, java.util.Date)} milik baris ini untuk merakit {@code
 *       Pengaduan.kode}, dan menaikkan indeks urut nomor surat setiap kali aduan baru benar-benar
 *       disimpan.</li>
 *   <li><b>Bentuk formulir dinamis</b> lewat {@link #getKelompokParameterTambahanPengaduans()}.
 *       Setiap kelompok parameter yang dicentang di layar master akan diterjemahkan
 *       {@code PengaduanAction} menjadi sekumpulan baris isian tambahan (teks, pilihan, sampai
 *       unggahan berkas) pada formulir pengaduan.</li>
 *   <li><b>Tata letak cetak</b>: berkas {@code .jrxml}/{@code .jasper} yang diunggah pada dialog
 *       jenis pengaduan disimpan sebagai {@code ais.database.model.file.LampiranLain} dengan
 *       {@code ref = }{@link #getId()} dan jenis {@code LampiranLain.FILE_JRXML_LAYOUT_JENIS_
 *       PENGADUAN}. Berkas inilah yang dikompilasi dan dijalankan saat pengguna menekan
 *       Cetak/Laporan pada modul pengaduan.</li>
 * </ol>
 *
 * <p><b>Yang TIDAK ditentukan di sini — penting:</b> entity ini <b>tidak punya satu pun field
 * penerima, tujuan, unit, pejabat, peran, maupun SOP</b>. Lihat bagian "Catatan rute &amp;
 * privasi" di bawah; ini relevan langsung untuk siapa pun yang mengira jenis pengaduan bisa
 * dipakai untuk mengatur ke mana sebuah aduan dialirkan.</p>
 *
 * <h2>Siapa yang memakai entity ini</h2>
 *
 * <ul>
 *   <li>{@code ais.action.master.JenisPengaduanAction} ({@code /pages/master/jenis_pengaduan.zul})
 *       — layar master CRUD-nya. Layar ini <b>tidak punya menu sendiri</b>: ia dimuat sebagai tab
 *       "Jenis Pengaduan" di dalam {@code /pages/master/pengaduan.zul} lewat {@code MyInclude},
 *       dan tabnya disembunyikan untuk pengguna non-admin ({@code Common.getApakahAdmin()}).</li>
 *   <li>{@code ais.action.master.PengaduanAction} — mengisi combo jenis (hanya baris {@code aktif
 *       = true}), merakit nomor agenda, membangun formulir parameter tambahan, dan mencetak
 *       dokumen aduan.</li>
 *   <li>{@code ais.action.report.format1.akademik.LaporanPengaduan} — laporan rekap per jenis.</li>
 *   <li>{@code ais.action.servlet.api.PengaduanMahasiswaApi} — mengirim daftar jenis aktif sebagai
 *       pilihan {@code jenis} pada respons API mobile mahasiswa.</li>
 *   <li>{@code ais.action.servlet.Wa} — webhook WhatsApp; setiap pesan masuk otomatis diberi
 *       <b>jenis aktif ber-id terkecil</b> ({@code setMaxResults(1)} + {@code order by id asc}),
 *       tanpa melihat isi pesan sama sekali.</li>
 *   <li>{@code ais.common.InitData#initClasses(...)} — mendaftarkan class ini pada rutinitas
 *       inisialisasi/penyemaian data awal.</li>
 * </ul>
 *
 * <h2>Pengelompokan anggota</h2>
 *
 * <ul>
 *   <li><b>Audit/identitas warisan</b> — {@link #getId()}, {@link #getOleh()}, {@link
 *       #getOlehId()}, {@link #getTanggal_dirubah()}, {@code onUpdate()}. Lihat catatan
 *       "deklarasi ulang" di bawah.</li>
 *   <li><b>Identitas kategori</b> — {@link #getKode()}, {@link #getNama()}, {@link
 *       #getKeterangan()}, {@link #getAktif()}, {@link #toString()}.</li>
 *   <li><b>Penomoran agenda</b> — {@link #getNomorSurat()}.</li>
 *   <li><b>Formulir dinamis</b> — {@link #getKelompokParameterTambahanPengaduans()}, {@link
 *       #setKelompokParameterTambahanPengaduans(Set)}, dan cache statis {@link #mapParameters}.</li>
 * </ul>
 *
 * <p>Class ini <b>tidak punya method utilitas/query statis</b> dan <b>tidak punya method bisnis
 * ber-logika nyata</b> selain pasangan getter/setter koleksi parameter tambahan yang menyimpan
 * hasilnya di cache statis. Seluruh pencarian, validasi, penomoran, dan penyaringan hak akses
 * berada di {@code JenisPengaduanAction} dan {@code PengaduanAction}. Satu-satunya anggota
 * {@code static} adalah {@link #mapParameters}.</p>
 *
 * <h2>Kenapa {@code id}/{@code oleh}/{@code olehId}/{@code tanggal_dirubah} dideklarasikan ulang</h2>
 *
 * <p>{@link GeneralValueObject} — lewat {@code ais.database.model.sop.DataSop} — <b>bukan</b>
 * {@code @Entity} maupun {@code @MappedSuperclass}, melainkan POJO abstrak biasa. Hibernate karena
 * itu <b>tidak</b> memetakan properti apa pun milik induk. Deklarasi ulang field {@code id},
 * {@code oleh}, {@code olehId}, {@code tanggal_dirubah} beserta getter/setter-nya di sini
 * <b>bukan duplikasi yang keliru</b>, melainkan keharusan teknis supaya kolom-kolom itu benar-benar
 * ada di tabel. Pola yang sama muncul di hampir seluruh entity turunan {@link
 * GeneralValueObject}.</p>
 *
 * <p>Konsekuensi lain dari status "bukan {@code @MappedSuperclass}" itu: properti bawaan induk
 * seperti {@code nim} dan {@code nomorUrut} <b>tidak</b> punya kolom di tabel ini, walaupun
 * {@link GeneralValueObject#compareTo(GeneralValueObject)} memakainya sebagai kunci urut. Untuk
 * baris jenis pengaduan, {@code nomorUrut} dan {@code nim} selalu {@code null} sehingga
 * pengurutan {@code TreeSet} praktis jatuh ke {@code nama}.</p>
 *
 * <h2>Verifikasi pola berulang (diperiksa langsung pada kode file ini)</h2>
 *
 * <ul>
 *   <li><b>Getter yang menulis balik ke field: ADA, dua buah.</b>
 *       <ul>
 *         <li>{@link #getNomorSurat()} — menugaskan ulang {@code nomorSurat = check(nomorSurat)}
 *             (resolusi proxy lazy lewat {@link GeneralValueObject#check(Object)}), pola standar
 *             repo ini.</li>
 *         <li>{@link #getKelompokParameterTambahanPengaduans()} — menimpa field koleksi dengan isi
 *             cache statis {@link #mapParameters} bila ada. Ini yang paling perlu diwaspadai;
 *             uraiannya ada di bagian berikutnya.</li>
 *       </ul>
 *   </li>
 *   <li><b>Getter yang menulis balik ke basis data: TIDAK ADA secara langsung</b>, tetapi karena
 *       tidak ada satu pun properti bertanda {@code @Transient}, nilai yang ditulis balik oleh dua
 *       getter di atas <b>ikut ter-{@code UPDATE} permanen</b> begitu entity di-flush pada session
 *       yang mengelolanya. Perhatikan bahwa {@link #getAktif()}, {@link #getKode()}, dan {@link
 *       #getNama()} sengaja <i>tidak</i> menulis balik: nilai default/rapi yang dikembalikannya
 *       hanya hidup di memori pemanggil, kolom di basis data tetap apa adanya.</li>
 *   <li><b>Getter yang menutup session Hibernate: TIDAK ADA di file ini.</b> Seluruh pengelolaan
 *       session ada di dalam {@link GeneralValueObject#check(Object)}, yang membuka dan menutup
 *       session penyelamatnya sendiri; file ini tidak pernah memanggil {@code
 *       HibernateUtil.openSession()} maupun {@code closeSession()}.</li>
 *   <li><b>Getter destruktif (menghapus/mengosongkan data): TIDAK ADA.</b> Tidak ada satu pun
 *       method di file ini yang menghapus baris, mengosongkan relasi, atau menyetel field ke
 *       {@code null}. (Bandingkan dengan {@code Komentar#getTbmuser()} yang destruktif.)</li>
 * </ul>
 *
 * <h2>Kuirk terbesar: cache statis {@link #mapParameters} berumur JVM</h2>
 *
 * <p>Pasangan {@link #getKelompokParameterTambahanPengaduans()}/{@link
 * #setKelompokParameterTambahanPengaduans(Set)} tidak sekadar membaca dan menulis field: keduanya
 * dijembatani {@code public static} {@link HashMap} {@link #mapParameters} yang di-<i>key</i>
 * dengan {@link #getId()} dan hidup selama JVM berjalan. Karena anotasi pemetaan dipasang pada
 * <i>getter</i> (Hibernate memakai akses properti), pasangan ini juga dipanggil oleh Hibernate
 * sendiri saat memuat dan saat mem-flush entity. Akibat yang perlu diketahui:</p>
 *
 * <ul>
 *   <li>Objek yang tersimpan di map adalah koleksi persisten milik <b>session yang mungkin sudah
 *       ditutup</b>. Pemanggil berikutnya — pengguna lain, thread lain, request lain — menerima
 *       koleksi yang sama. Ini sumber klasik {@code LazyInitializationException} sekaligus
 *       pembocor state antar-sesi.</li>
 *   <li>{@link HashMap} biasa, <b>tanpa sinkronisasi apa pun</b>, ditulis dan dibaca dari thread
 *       request yang berbeda-beda.</li>
 *   <li>Cache <b>tidak pernah dibersihkan</b>: tidak ada pembatasan ukuran, tidak ada kedaluwarsa,
 *       dan tidak ada satu pun pemanggil {@code mapParameters.remove(...)}/{@code clear()} di
 *       seluruh codebase. Menghapus baris jenis pengaduan pun tidak mengeluarkan entri-nya.</li>
 *   <li>{@code JenisPengaduanAction#initKelompokParameterTambahanPengaduan(Rows)} mengambil
 *       koleksi ini <b>secara referensi</b> lalu men-{@code add}/{@code remove} isinya langsung
 *       dari event listener checkbox. Karena referensi itu sama dengan yang tersimpan di
 *       {@link #mapParameters}, mencentang lalu menekan <b>Batal</b> tetap meninggalkan perubahan
 *       pada cache global — formulir pengaduan yang dilihat pengguna lain ikut berubah sampai
 *       aplikasi di-restart, walaupun basis data tidak tersentuh sama sekali.</li>
 * </ul>
 *
 * <p>Pola cache statis yang sama disalin ke belasan entity "Jenis*" lain ({@code JenisPengajuan},
 * {@code JenisCatatanMahasiswa}, {@code JenisCatatanSiswa}, {@code JenisCutiDanIzin},
 * {@code JenisPerbaikanAsset}, {@code JenisGajiPegawai}, dan seterusnya) — jadi ini template
 * arsitektural, bukan kekhasan file ini.</p>
 *
 * <h2>Kuirk penamaan kolom tabel penghubung</h2>
 *
 * <p>Pada {@link #getKelompokParameterTambahanPengaduans()}, {@code @JoinTable} menamai
 * <i>join column</i> sisi pemilik (yang berisi id {@code jenis_pengaduan}) dengan
 * {@code "kelompok_parameter_tambahan_pengaduan"}, dan sisi lawan (yang berisi id
 * {@code kelompok_parameter_tambahan_pengaduan}) dengan {@code "parameter"}. Kedua nama itu
 * <b>tertukar/menyesatkan</b> dibanding entity sejenis yang benar ({@code JenisCatatanMahasiswa}
 * memakai {@code joinColumns = "jenis_catatan_mahasiswa"}, {@code JenisCatatanSiswa} memakai
 * {@code "jenis_catatan_siswa"}). Ini murni soal nama kolom fisik — pemetaannya tetap berfungsi —
 * tetapi siapa pun yang membaca tabel {@code jenis_pengaduan_has_parameter} langsung dari SQL
 * akan salah menafsirkan kolomnya. Kembarannya ada di {@code JenisPengajuan} (nama sama persis)
 * dan {@code JenisCutiDanIzin} (memakai {@code "jenis_catatan_administrasi"}).</p>
 *
 * <h2>Catatan rute &amp; privasi (hasil pemeriksaan khusus)</h2>
 *
 * <p>Karena modul pengaduan dipakai juga sebagai kanal pelaporan pelanggaran, entity ini diperiksa
 * khusus terhadap dua pertanyaan: apakah ia menentukan tujuan penyaluran aduan, dan apakah ia bisa
 * membocorkan identitas pelapor.</p>
 *
 * <ul>
 *   <li><b>Jenis pengaduan sama sekali tidak ikut menentukan rute.</b> Tidak ada field penerima,
 *       unit tujuan, jabatan penanggung jawab, peran, maupun relasi ke {@code
 *       ais.database.model.sop.DataSop}/{@code AlurSop}. Penelusuran seluruh codebase memastikan
 *       hanya tujuh berkas yang menyebut class ini, dan <b>tidak satu pun</b> berada di paket
 *       {@code ais.action.master.sop} atau menyentuh logika penentuan penerima. Siapa yang boleh
 *       melihat dan menyetujui sebuah aduan ditentukan sepenuhnya di {@code PengaduanAction} dari
 *       rantai {@code atasanlangsung}/{@code atasanlangsung2}/{@code atasanlangsung3} milik
 *       pegawai <i>pelapor</i>. Konsekuensi praktisnya: <b>membuat jenis pengaduan khusus
 *       (misalnya "Pelaporan Pelanggaran") tidak mengubah rute apa pun</b> — aduan tetap mengalir
 *       ke atasan langsung pelapor, termasuk ketika atasan itulah yang diadukan.</li>
 *   <li><b>Combo jenis pengaduan adalah kunci enumerasi pada jalur laporan.</b>
 *       {@code PengaduanAction#onLaporan(Event)} membuka {@code LaporanPengaduan} <b>tanpa
 *       pemeriksaan hak akses apa pun</b>, dan {@code LaporanPengaduan#generateParameter(
 *       JenisPengaduan, Date, Date, Pegawai, Mahasiswa, Siswa, Pengaduan)} menyaring
 *       {@code Pengaduan} hanya dengan {@code jenisPengaduan = <pilihan combo>} + rentang tanggal
 *       (filter pegawai/mahasiswa/siswa opsional dan menjadi {@code true} bila dikosongkan).
 *       Penyaringan berbasis "punya bawahan" yang dipasang hati-hati pada daftar utama
 *       {@code PengaduanAction} <b>tidak diterapkan sama sekali</b> di jalur ini, sedangkan isi
 *       laporan menyertakan seluruh properti pelapor lewat {@code Common.insertProperty(
 *       Pegawai.class, ...)} dan seluruh uraian aduan. Efeknya: memilih satu jenis di combo cukup
 *       untuk menarik keluar aduan siapa pun beserta identitasnya.</li>
 *   <li><b>Berkas {@code .jrxml} yang diunggah di layar ini dieksekusi di server.</b> Berkas
 *       layout per jenis dikompilasi runtime oleh {@code Report.generateCompileFileReport(...)};
 *       ekspresi di dalam {@code .jrxml} adalah kode Java. Dialog unggahnya berada di
 *       {@code JenisPengaduanAction#init(JenisPengaduan)}.</li>
 *   <li><b>Tabrakan kunci lampiran antar-modul.</b> Konstanta {@code LampiranLain.FILE_JRXML_
 *       LAYOUT_JENIS_PENGADUAN} (nilainya string {@code "File jrxml jenis pengaduan"}) dipakai
 *       ulang apa adanya oleh {@code PengajuanMahasiswaAction} dan {@code PengajuanSiswaAction}
 *       untuk layout {@code JenisPengajuan} mereka, sementara {@code LampiranLain.ambil(ref,
 *       jenis)} hanya berkunci pada pasangan (id, string jenis) tanpa pembeda class. Artinya
 *       {@code JenisPengaduan} ber-id 5 dan {@code JenisPengajuan} ber-id 5 <b>berbagi satu baris
 *       lampiran yang sama</b>; mengunggah layout di salah satu modul menimpa layout modul
 *       lainnya.</li>
 *   <li><b>Layar master ini tidak benar-benar dijaga oleh {@code doCheckSecurity()}.</b>
 *       {@code JenisPengaduanAction#doBeforeCompose(...)} memanggil {@code Common.doCheckSecurity()},
 *       tetapi rantai panggilannya berujung pada {@code CommonPrivilages#doCheckPrevilagesRead()}
 *       yang hanya menegakkan pemeriksaan untuk 12 halaman di whitelist {@code MUST_CHECKED};
 *       {@code /pages/master/jenis_pengaduan.zul} tidak termasuk. Yang benar-benar menjaga layar
 *       ini hanyalah (a) penyembunyian tab untuk non-admin di {@code PengaduanAction} — sifatnya
 *       visibilitas, bukan otorisasi, dan (b) {@code checkPrevilages} untuk tombol
 *       Tambah/Ubah/Hapus, yang di-resolve terhadap menu <i>Pengaduan</i> induknya karena layar
 *       ini tak punya menu sendiri.</li>
 *   <li><b>Sisi baik:</b> checkbox "Aktif" pada grid daftar sudah dijaga
 *       ({@code checkbox.setDisabled(!edit)}), berbeda dengan beberapa layar master lain yang
 *       membiarkan checkbox grid menulis ke basis data tanpa gerbang {@code UPDATE}.</li>
 * </ul>
 *
 * @see GeneralValueObject
 * @see Pengaduan
 * @see KelompokParameterTambahanPengaduan
 * @see NomorSurat
 */
@Entity
@org.hibernate.annotations.Entity(
    dynamicInsert = true,
    dynamicUpdate = true
)
@Audited
@Table(schema = "public", name = "jenis_pengaduan")
public class JenisPengaduan extends GeneralValueObject {

	/**
	 * Versi serialisasi Java. Nilainya identik dengan puluhan entity lain hasil generator
	 * {@code hbm2java} yang sama (antara lain {@link Pengaduan}, {@link
	 * KelompokParameterTambahanPengaduan}, dan {@link NomorSurat}) — kesamaan itu artefak
	 * salin-tempel, bukan penanda kompatibilitas antar-class.
	 */
	private static final long serialVersionUID = 2463821577548439808L;

	/** Kunci utama tabel; dideklarasikan ulang karena induk tidak dipetakan. Lihat {@link #getId()}. */
	private Long id;

	/** Nama pengguna pembuat/pengubah baris (kolom audit warisan). Lihat {@link #getOleh()}. */
	private String oleh;

	/** Id pengguna pembuat/pengubah baris (kolom audit warisan). Lihat {@link #getOlehId()}. */
	private String olehId;

	/**
	 * Mengembalikan id pengguna yang tercatat sebagai pembuat/pengubah baris ini (kolom audit
	 * warisan pola {@link GeneralValueObject}).
	 *
	 * @return id pengguna, atau {@code null} bila belum pernah diisi
	 */
	public String getOlehId() {
		return olehId;
	}

	/**
	 * Menyetel id pengguna pembuat/pengubah baris. Nilai {@code null}, kosong, atau hanya spasi
	 * <b>diabaikan diam-diam</b> (method langsung {@code return}) sehingga nilai lama bertahan —
	 * kolom audit sengaja dibuat tidak bisa dikosongkan lewat setter.
	 *
	 * @param olehId id pengguna; diabaikan bila {@code null}/kosong/hanya spasi
	 */
	public void setOlehId(String olehId) {if (olehId == null || olehId.trim().isEmpty()) {return;}
		this.olehId = olehId;
	}

	/**
	 * Menyetel nama pengguna pembuat/pengubah baris. Sama seperti {@link #setOlehId(String)},
	 * nilai {@code null}/kosong/hanya spasi <b>diabaikan diam-diam</b>.
	 *
	 * @param oleh nama pengguna; diabaikan bila {@code null}/kosong/hanya spasi
	 */
	public void setOleh(String oleh) {if (oleh == null || oleh.trim().isEmpty()) {return;}
		this.oleh = oleh;
	}

	/**
	 * Mengembalikan nama pengguna yang tercatat sebagai pembuat/pengubah baris ini (kolom audit
	 * warisan pola {@link GeneralValueObject}).
	 *
	 * @return nama pengguna, atau {@code null} bila belum pernah diisi
	 */
	public String getOleh() {
		return oleh;
	}

	/**
	 * Dua deklarasi yang sengaja dibiarkan menyatu pada satu baris (bentuk aslinya hasil
	 * penyisipan otomatis; <b>jangan dipecah</b> supaya diff terhadap entity lain tetap seragam):
	 *
	 * <ol>
	 *   <li>{@code onUpdate()} — kait JPA {@link javax.persistence.PreUpdate @PreUpdate} yang
	 *       dijalankan Hibernate tepat sebelum setiap {@code UPDATE}. Isinya melimpahkan pekerjaan
	 *       ke {@code ais.database.hibernate.AuditTimestampInterceptor.ubah(this)}, yang
	 *       memperbarui stempel waktu perubahan. Tidak untuk dipanggil manual.</li>
	 *   <li>field {@code tanggal_dirubah} — diinisialisasi ke waktu sekarang lewat {@code
	 *       ais.ui.util.WaktuUtil#getDate()} supaya baris baru sudah punya stempel walau belum
	 *       pernah di-{@code UPDATE}. Lihat {@link #getTanggal_dirubah()}.</li>
	 * </ol>
	 */
	@javax.persistence.PreUpdate protected void onUpdate() { ais.database.hibernate.AuditTimestampInterceptor.ubah(this);}     private Date tanggal_dirubah = ais.ui.util.WaktuUtil.getDate();

	/**
	 * Menyetel stempel waktu perubahan terakhir. Biasanya tidak dipanggil dari kode aplikasi —
	 * pengisiannya diserahkan ke kait {@code onUpdate()}.
	 *
	 * @param tanggal_dirubah stempel waktu baru; boleh {@code null}
	 */
	public void setTanggal_dirubah(Date tanggal_dirubah) {
		this.tanggal_dirubah = tanggal_dirubah;
	}

	/**
	 * Mengembalikan stempel waktu perubahan terakhir baris ini, dipetakan sebagai
	 * {@code TIMESTAMP}. Nilai awalnya adalah waktu pembuatan objek Java (lihat catatan pada
	 * {@code onUpdate()}), bukan waktu {@code INSERT} di basis data.
	 *
	 * @return waktu perubahan terakhir; tidak pernah {@code null} untuk objek yang baru dibuat
	 */
	@Temporal(TemporalType.TIMESTAMP)
	public Date getTanggal_dirubah() {
		return tanggal_dirubah;
	}

	/**
	 * Representasi teks singkat berbentuk {@code "<id>-<nama>"}.
	 *
	 * <p>Perhatikan: method ini membaca <b>field</b> {@code nama} secara langsung, bukan {@link
	 * #getNama()}, sehingga nilainya tidak di-{@code trim} dan bisa menghasilkan teks seperti
	 * {@code "null-null"} untuk objek baru yang belum diisi. Ini menimpa {@link
	 * GeneralValueObject#toString()}.</p>
	 *
	 * @return gabungan id dan nama dipisah tanda hubung
	 */
	public String toString() {
		return id + "-" + nama;
	}

	/** Kode singkat kategori; opsional. Lihat {@link #getKode()}. */
	private String kode;

	/** Nama kategori yang tampil di combo dan laporan; wajib. Lihat {@link #getNama()}. */
	private String nama;

	/** Penjelasan bebas kategori; opsional. Lihat {@link #getKeterangan()}. */
	private String keterangan;

	/** Penanda kategori masih boleh dipilih; lihat {@link #getAktif()} soal default {@code null}. */
	private Boolean aktif;

	/** Format nomor agenda milik kategori ini; wajib diisi lewat layar. Lihat {@link #getNomorSurat()}. */
	private NomorSurat nomorSurat;

	/**
	 * Cache statis kelompok parameter tambahan, di-<i>key</i> dengan {@link #getId()}, berumur
	 * selama JVM hidup.
	 *
	 * <p><b>Bukan penyimpanan biasa.</b> Map ini diisi oleh {@link
	 * #setKelompokParameterTambahanPengaduans(Set)} dan dibaca oleh {@link
	 * #getKelompokParameterTambahanPengaduans()}, sehingga koleksi parameter satu baris jenis
	 * pengaduan dibagikan ke <b>seluruh session, thread, dan pengguna</b> aplikasi. Karena
	 * Hibernate memakai akses properti (anotasi dipasang pada getter), Hibernate sendiri juga ikut
	 * mengisi dan membaca map ini saat memuat/mem-flush entity — nilai yang tersimpan bisa berupa
	 * koleksi persisten milik session yang sudah ditutup.</p>
	 *
	 * <p>Map bertipe {@link HashMap} biasa <b>tanpa sinkronisasi</b>, tidak pernah dibersihkan,
	 * dan tidak punya batas ukuran maupun kedaluwarsa (tidak ada satu pun pemanggil {@code
	 * remove}/{@code clear} di seluruh codebase, termasuk saat baris jenis pengaduan dihapus).
	 * Bidangnya {@code public} sehingga kode mana pun bisa memodifikasinya langsung; berbeda dari
	 * kembarannya di {@code JenisCatatanSiswa} dan {@code AlurSop}, map milik entity ini tidak
	 * pernah disemai dari luar. Uraian dampak lengkapnya ada pada Javadoc class.</p>
	 */
	public static Map<Long, Set<KelompokParameterTambahanPengaduan>> mapParameters = new HashMap<Long, Set<KelompokParameterTambahanPengaduan>>();

	/**
	 * Kelompok parameter tambahan yang membentuk formulir dinamis untuk kategori ini.
	 *
	 * <p>Diinisialisasi sebagai {@link TreeSet} agar objek baru (belum tersimpan) sudah terurut
	 * memakai {@link GeneralValueObject#compareTo(GeneralValueObject)}. Untuk objek yang dimuat
	 * dari basis data, Hibernate mengganti isinya dengan koleksi persisten miliknya sendiri dan
	 * urutan ditentukan {@code @OrderBy} pada {@link
	 * #getKelompokParameterTambahanPengaduans()}.</p>
	 */
	private Set<KelompokParameterTambahanPengaduan> kelompokParameterTambahanPengaduans = new TreeSet<KelompokParameterTambahanPengaduan>();

	/**
	 * Mengembalikan kelompok parameter tambahan milik kategori ini — daftar inilah yang
	 * diterjemahkan {@code PengaduanAction} menjadi baris-baris isian tambahan pada formulir
	 * pengaduan.
	 *
	 * <p><b>Getter ini tidak murni membaca.</b> Bila {@link #getId()} sudah terisi dan {@link
	 * #mapParameters} memuat entri untuk id tersebut, isi cache statis itu <b>menimpa</b> field
	 * {@code kelompokParameterTambahanPengaduans} sebelum dikembalikan. Karena tidak ada properti
	 * {@code @Transient} di entity ini, koleksi hasil timpaan itulah yang dilihat Hibernate saat
	 * flush — jadi state yang bocor dari session/pengguna lain bisa ikut tertulis ke tabel
	 * penghubung. Untuk baris yang belum punya id, cache dilewati dan field dikembalikan apa
	 * adanya.</p>
	 *
	 * <p><b>Objek yang dikembalikan adalah referensi hidup, bukan salinan.</b>
	 * {@code JenisPengaduanAction#initKelompokParameterTambahanPengaduan(Rows)} menyimpan
	 * referensi ini lalu men-{@code add}/{@code remove} isinya dari event listener checkbox;
	 * karena referensinya sama dengan yang ada di {@link #mapParameters}, perubahan tetap melekat
	 * di cache global meskipun pengguna akhirnya menekan Batal.</p>
	 *
	 * <p><b>Catatan pemetaan.</b> Relasi {@code @ManyToMany} lewat tabel penghubung
	 * {@code public.jenis_pengaduan_has_parameter}. Nama kolomnya menyesatkan: {@code joinColumns}
	 * (sisi entity ini) dinamai {@code "kelompok_parameter_tambahan_pengaduan"} dan
	 * {@code inverseJoinColumns} (sisi lawan) dinamai {@code "parameter"} — kebalikan dari yang
	 * diduga pembaca SQL, lihat Javadoc class. Cascade hanya {@code MERGE}, jadi menyimpan jenis
	 * pengaduan tidak pernah membuat atau menghapus baris master kelompok parameter.</p>
	 *
	 * @return koleksi kelompok parameter (referensi hidup, tidak pernah {@code null}); terurut
	 *         menurut {@code nomorUrut} lalu {@code nama}
	 */
	@ManyToMany(targetEntity = KelompokParameterTambahanPengaduan.class, cascade = { CascadeType.MERGE })
	@OrderBy(value = "nomorUrut asc, nama asc")
	@JoinTable(name = "jenis_pengaduan_has_parameter", schema = "public", joinColumns = @JoinColumn(name = "kelompok_parameter_tambahan_pengaduan"), inverseJoinColumns = @JoinColumn(name = "parameter"))
	public Set<KelompokParameterTambahanPengaduan> getKelompokParameterTambahanPengaduans() {
		if (id != null) {
			Set<KelompokParameterTambahanPengaduan> temp = mapParameters.get(id);
			if (temp != null) {
				kelompokParameterTambahanPengaduans = temp;
			}
		}
		return kelompokParameterTambahanPengaduans;
	}

	/**
	 * Menyetel kelompok parameter tambahan kategori ini <b>sekaligus menyimpannya ke cache statis
	 * {@link #mapParameters}</b> bila {@link #getId()} sudah terisi.
	 *
	 * <p>Efek samping ke cache global itulah yang membuat setter ini bukan setter biasa: sekali
	 * dipanggil, koleksi yang diberikan menjadi jawaban {@link
	 * #getKelompokParameterTambahanPengaduans()} untuk <b>semua</b> instance {@code
	 * JenisPengaduan} ber-id sama di seluruh aplikasi, sampai JVM dimatikan. Untuk baris baru
	 * ({@code id == null}) cache tidak disentuh; entri baru akan terbentuk pada pemanggilan
	 * berikutnya setelah id terisi.</p>
	 *
	 * <p>Pemanggilnya ada dua jenis: (a) Hibernate, saat memuat entity dari basis data — sehingga
	 * koleksi persisten milik session tersebut ikut masuk cache; dan (b)
	 * {@code JenisPengaduanAction#onSave(Event)}, yang menyetel hasil centang checkbox sebelum
	 * {@code Common.refreshSaveOrUpdate(...)}.</p>
	 *
	 * @param kelompokParameterTambahanPengaduans koleksi kelompok parameter yang dipilih;
	 *        disimpan apa adanya sebagai referensi (tidak disalin), sehingga perubahan pada
	 *        koleksi milik pemanggil ikut terlihat lewat getter dan lewat cache statis
	 */
	public void setKelompokParameterTambahanPengaduans(
			Set<KelompokParameterTambahanPengaduan> kelompokParameterTambahanPengaduans) {
		this.kelompokParameterTambahanPengaduans = kelompokParameterTambahanPengaduans;
		if (id != null) {
			mapParameters.put(id, kelompokParameterTambahanPengaduans);
		}
	}

	/**
	 * Konstruktor tanpa argumen yang dibutuhkan Hibernate. Dipakai juga oleh
	 * {@code JenisPengaduanAction#onAdd(Event)} untuk membuka dialog "Tambah Jenis Pengaduan"
	 * dengan baris kosong.
	 */
	public JenisPengaduan() {
	}

	/**
	 * Mengembalikan kunci utama baris ini. Kolom {@code id} bertipe identity
	 * ({@code insertable = false}) sehingga nilainya dibangkitkan basis data dan baru terisi
	 * setelah {@code INSERT}.
	 *
	 * <p>Selain sebagai kunci utama, id ini dipakai sebagai {@code ref} lampiran layout cetak
	 * ({@code LampiranLain.ambil(getId(), FILE_JRXML_LAYOUT_JENIS_PENGADUAN)}) dan sebagai kunci
	 * {@link #mapParameters} — lihat catatan tabrakan kunci lampiran pada Javadoc class.</p>
	 *
	 * @return id baris, atau {@code null} bila objek belum pernah disimpan
	 */
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", insertable = false, unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	/**
	 * Menyetel kunci utama. Normalnya hanya dipanggil Hibernate; menyetelnya manual pada objek
	 * yang sudah dikelola session akan mengacaukan identitas entity <b>dan</b> memindahkan entri
	 * {@link #mapParameters} yang dipakai baris ini.
	 *
	 * @param id kunci utama baru
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * Mengembalikan kode singkat kategori, sudah di-{@code trim}, dengan {@code null}
	 * dinormalkan menjadi string kosong.
	 *
	 * <p>Normalisasi ini <b>tidak</b> ditulis balik ke field, jadi kolom di basis data tetap
	 * {@code NULL} bila memang belum diisi. Tidak ada {@code @Column} eksplisit sehingga kolomnya
	 * bernama {@code kode} dan {@code nullable}. Kode dipakai sebagai kolom deskripsi kedua pada
	 * combo pemilihan jenis ({@code Common.insertCombo(..., new String[] { "nama", "kode" }, ...)})
	 * dan diekspos sebagai field {@code kode} pada respons {@code PengaduanMahasiswaApi}; layar
	 * master sendiri <b>tidak menyediakan isian untuk kolom ini</b>, jadi pada praktiknya ia
	 * hampir selalu kosong.</p>
	 *
	 * @return kode kategori yang sudah dirapikan; {@code ""} bila belum diisi, tidak pernah
	 *         {@code null}
	 */
	public String getKode() {
		return kode == null ? "" : kode.trim();
	}

	/**
	 * Menyetel kode singkat kategori. Nilai disimpan apa adanya tanpa {@code trim} maupun
	 * validasi keunikan.
	 *
	 * @param kode kode kategori; boleh {@code null}
	 */
	public void setKode(String kode) {
		this.kode = kode;
	}

	/**
	 * Mengembalikan nama kategori (label yang dilihat pengguna), sudah di-{@code trim}.
	 *
	 * <p>Berbeda dari {@link #getKode()}, {@code null} <b>tidak</b> dinormalkan menjadi string
	 * kosong — pemanggil harus siap menerima {@code null}. Hasil {@code trim} tidak ditulis balik
	 * ke field. Kolomnya {@code text} dan {@code nullable = false} di tingkat basis data,
	 * sedangkan validasi "wajib diisi" dilakukan di {@code JenisPengaduanAction#onSave(Event)};
	 * jalur non-UI (impor Excel, endpoint reflektif) tidak melewati validasi itu dan hanya akan
	 * ditolak oleh basis data.</p>
	 *
	 * <p>Nilai ini juga menjadi judul aduan ketika pengguna tidak mengisi judul sendiri — lihat
	 * {@link Pengaduan#getNama()}.</p>
	 *
	 * @return nama kategori yang sudah dirapikan, atau {@code null} bila field belum diisi
	 */
	@Column(name = "nama", nullable = false, columnDefinition = "text")
	public String getNama() {
		return this.nama == null ? null : this.nama.trim();
	}

	/**
	 * Menyetel nama kategori. Nilai disimpan apa adanya tanpa {@code trim}; perapian baru terjadi
	 * saat dibaca lewat {@link #getNama()}. Menimpa {@link
	 * GeneralValueObject#setNama(String)} yang hanya mengisi field bantu induk (tidak dipetakan).
	 *
	 * @param nama nama kategori
	 */
	public void setNama(String nama) {
		this.nama = nama;
	}

	/**
	 * Mengembalikan penjelasan bebas kategori apa adanya — tanpa {@code trim} dan tanpa
	 * normalisasi {@code null}. Kolomnya bertipe {@code text} dan boleh kosong.
	 *
	 * <p>Isian ini muncul sebagai kolom "Keterangan" pada grid daftar, sebagai deskripsi item
	 * combo pemilihan jenis, dan diekspos pada respons {@code PengaduanMahasiswaApi} — jadi teks
	 * yang ditulis di sini terbaca oleh mahasiswa lewat aplikasi mobile, bukan hanya oleh
	 * operator.</p>
	 *
	 * @return keterangan kategori, atau {@code null} bila belum diisi
	 */
	@Column(name = "keterangan", nullable = true, columnDefinition = "text")
	public String getKeterangan() {
		return this.keterangan;
	}

	/**
	 * Menyetel penjelasan bebas kategori. Menimpa {@link
	 * GeneralValueObject#setKeterangan(String)}; berbeda dari induknya, nilai di sini benar-benar
	 * dipetakan ke kolom {@code keterangan}.
	 *
	 * @param keterangan penjelasan kategori; boleh {@code null}
	 */
	public void setKeterangan(String keterangan) {
		this.keterangan = keterangan;
	}

	/**
	 * Mengembalikan penanda apakah kategori masih boleh dipilih, dengan <b>{@code null}
	 * diperlakukan sebagai {@code true}</b> (default berpihak "aktif").
	 *
	 * <p>Nilai default itu <b>tidak</b> ditulis balik ke field, jadi kolomnya tetap {@code NULL}
	 * di basis data. Konsekuensinya perlu diperhatikan oleh penulis query: penyaring yang ditulis
	 * sebagai {@code Restrictions.eq("aktif", true)} — dipakai oleh combo jenis di
	 * {@code PengaduanAction}, {@code LaporanPengaduan}, dan daftar pilihan
	 * {@code PengaduanMahasiswaApi} — akan <b>melewatkan</b> baris yang kolom {@code aktif}-nya
	 * masih {@code NULL}, padahal getter ini menyatakan baris tersebut aktif. Hanya
	 * {@code ais.action.servlet.Wa} yang menulis penyaringnya secara lengkap sebagai
	 * {@code isNull("aktif") OR eq("aktif", true)}. Baris yang dibuat lewat layar master selalu
	 * mendapat nilai eksplisit karena checkbox grid menuliskannya, tetapi baris hasil impor
	 * Excel/penyemaian awal bisa saja tertinggal {@code NULL} dan menjadi "aktif tapi tak pernah
	 * muncul di combo".</p>
	 *
	 * <p>Tidak ada {@code @Column} eksplisit, sehingga kolomnya bernama {@code aktif}.</p>
	 *
	 * @return {@code true} bila kategori boleh dipilih; {@code true} juga ketika field masih
	 *         {@code null}
	 */
	public Boolean getAktif() {
		return aktif == null ? true : aktif;
	}

	/**
	 * Menyetel penanda aktif. Dipanggil dari event {@code onCheck} checkbox "Aktif" pada grid
	 * daftar {@code JenisPengaduanAction}, yang langsung disusul {@code
	 * Common.refreshSaveOrUpdate(...)} sehingga perubahannya <b>tersimpan permanen seketika</b>
	 * tanpa dialog konfirmasi. Checkbox tersebut dinonaktifkan bila pengguna tidak punya hak
	 * {@code UPDATE}.
	 *
	 * @param aktif {@code true}/{@code false}; {@code null} akan dibaca sebagai {@code true} oleh
	 *        {@link #getAktif()} tetapi tetap tersimpan sebagai {@code NULL}
	 */
	public void setAktif(Boolean aktif) {
		this.aktif = aktif;
	}

	/**
	 * Mengembalikan format nomor agenda milik kategori ini, setelah proxy lazy-nya dipaksa
	 * teratasi.
	 *
	 * <p><b>Getter ini menulis balik ke field</b>: hasil {@link
	 * GeneralValueObject#check(Object)} ditugaskan ulang ke {@code nomorSurat} sebelum
	 * dikembalikan — pola standar resolusi proxy di repo ini. {@code check(...)} sendiri yang
	 * membuka dan menutup session penyelamatnya bila session asal sudah tertutup; file ini tidak
	 * pernah mengelola session sendiri.</p>
	 *
	 * <p>Nilai ini menggerakkan seluruh penomoran agenda pengaduan:
	 * {@code PengaduanAction#generateCode(JenisPengaduan, boolean)} membaca
	 * {@code getGunakanIndexUrut()}/{@code getNomorIndex()} lalu memanggil {@code
	 * NomorSurat#format(...)}, dan {@code PengaduanAction#getindex(JenisPengaduan)} memakai
	 * flag {@code urutBerdasarkanNomor}/{@code urutBerdasarkanKelompok}/{@code
	 * resetUrutanTiapTahun}/{@code resetUrutanTiapBulan}/{@code resetTiap} untuk menghitung nomor
	 * urut berikutnya. Bila {@code null}, {@code generateCode} mengembalikan string kosong dan
	 * {@code getindex} mengembalikan {@code 0} — aduan tetap bisa disimpan, hanya tanpa nomor
	 * agenda. Layar master mewajibkan pengisiannya, jalur non-UI tidak.</p>
	 *
	 * <p>Relasi {@code @ManyToOne} lazy dengan cascade {@code PERSIST} + {@code MERGE} ke kolom
	 * {@code nomor_surat} yang {@code nullable}.</p>
	 *
	 * @return format nomor agenda kategori ini, atau {@code null} bila belum ditetapkan
	 */
	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY)
	@JoinColumn(name = "nomor_surat", nullable = true)
	public NomorSurat getNomorSurat() {
		nomorSurat = check(nomorSurat);
		return nomorSurat;
	}

	/**
	 * Menyetel format nomor agenda kategori ini. Dipanggil dari
	 * {@code JenisPengaduanAction#onSave(Event)} dengan nilai yang dipilih lewat komponen
	 * {@code AmbilDataNomorSuratBanbox}; penyimpanan akan ditolak lebih dulu oleh validasi UI bila
	 * belum ada pilihan.
	 *
	 * @param nomorSurat format nomor agenda; boleh {@code null} pada jalur non-UI
	 */
	public void setNomorSurat(NomorSurat nomorSurat) {
		this.nomorSurat = nomorSurat;
	}

}
