package ais.database.model;

// Generated Apr 12, 2010 1:48:52 AM by Hibernate Tools 3.2.4.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.envers.Audited;
import org.json.JSONArray;
import org.json.JSONObject;
import org.zkoss.zk.ui.sys.ExecutionCtrl;
import org.zkoss.zk.ui.sys.ExecutionsCtrl;

import ais.action.ws.util.ConstantUtil;
import ais.common.Common;
import ais.common.ConstantValues;
import ais.database.model.sekolah.KanalPembayaran;
import ais.ui.util.MyToolbarbuttonConfig;
import ais.ui.util.MyWindow;

/**
 * JenisKegiatan generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Entity(dynamicInsert = true, dynamicUpdate = true)
@Audited
@Table(schema = "public", name = "jenis_kegiatan")
public class JenisKegiatan extends GeneralValueObject {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3088613612931036389L;
	private Long id;
	private String oleh;
	private String olehId;

	public String getOlehId() {
		return olehId;
	}

	public void setOlehId(String olehId) {
		if (olehId == null || olehId.trim().isEmpty()) {
			return;
		}
		this.olehId = olehId;
	}

	public void setOleh(String oleh) {
		if (oleh == null || oleh.trim().isEmpty()) {
			return;
		}
		this.oleh = oleh;
	}

	public String getOleh() {
		return oleh;
	}

	@Override
	public int compareTo(GeneralValueObject arg0) {
		try {
			if (getNama() != null && arg0.getNama() != null) {
				return getNama().compareTo(arg0.getNama());
			}
		} catch (Exception e) { ais.common.ErrorAuditUtil.record(e, "auto-audit(empty-catch) src/ais/database/model/JenisKegiatan.java:80");

		}

		return 0;
	}

	@javax.persistence.PreUpdate
	protected void onUpdate() {
		ais.database.hibernate.AuditTimestampInterceptor.ubah(this);
	}

	private Date tanggal_dirubah = ais.ui.util.WaktuUtil.getDate();

	public void setTanggal_dirubah(Date tanggal_dirubah) {
		this.tanggal_dirubah = tanggal_dirubah;
	}

	@Temporal(TemporalType.TIMESTAMP)
	public Date getTanggal_dirubah() {
		return tanggal_dirubah;
	}

	private String namaKegiatan;
	private String prefixKodePembayaran;
	private String namaBankPembayaran;
	private String keterangan;
	private String penjelasanPembayaran;

	public String getKeterangan() {
		return keterangan == null ? "" : keterangan;
	}

	public void setKeterangan(String keterangan) {
		this.keterangan = keterangan;
	}

	private String kode;
	private Boolean defaultKegiatan = false;
	private Boolean aktif;
	private Boolean defaultPembayaran = false;
	private Boolean digunakanUntukPengecekanKrs;
	private Boolean digunakanUntukPengecekanNilai;
	private Boolean digunakanUntukPengecekanUjian;
	private Boolean digunakanSyaratKeaktifan;
	private Boolean digunakanSyaratLogin;
	private Boolean digunakanSyaratCetakSuratBebasAktif;

	private Integer minSmt = 0;
	private Integer maxSmt = 30;

	private Double persenSyaratLogin;
	private KanalPembayaran kanalPembayaran;
	private Boolean bayarHanyaSmtSaatIni;
	private Boolean bayarHanyaSmtSaatIniDanSebelumnya;
	private Boolean bayarHanyaSmtSaatIniDanSebelumnyalagi;
	private Boolean bayarHanyaSmtSaatIniDanSebelumnyalagi3;
	private Boolean bayarHanyaSmtSaatIniDanSebelumnyalagi4;
	private Boolean hanyaBerupaAngsuran;
	private Boolean hanyaBerupaBukanAngsuran;
	private String jenjangAngsuranJson;
	private Boolean tagihanJugaUntukAlumni;

	private Boolean tidakBolehMengangsur;
	private Double persenSyaratLogin1;
	private Double persenSyaratLogin2;
	private Double persenSyaratLogin3;
	private Double persenSyaratLogin4;
	private Double persenSyaratLogin5;
	private Double persenSyaratLogin6;
	private Double persenSyaratLogin7;
	private Double persenSyaratLogin8;
	private Double persenSyaratLogin9;
	private Double persenSyaratLogin10;
	private Double persenSyaratLogin11;
	private Double persenSyaratLogin12;
	private Double persenSyaratLogin13;
	private Double persenSyaratLogin14;
	private Boolean bayarHanyaSmtSaatIniDanSebelumnyalagi5;
	// private Set<DetailBiaya> detailBiayas = new HashSet<DetailBiaya>();
	private Boolean bayarHanyaSmtSaatIniDanSebelumnyalagi6;
	private Boolean bayarHanyaSmtSaatIniDanSebelumnyalagi7;
	private Boolean bayarHanyaSmtSaatIniDanSebelumnyalagi8;

	private Boolean bayarHanyaSmtSaatIniDanSebelumnyalagi9;
	private Boolean bayarHanyaSmtSaatIniDanSebelumnyalagi10;
	private Boolean bayarHanyaSmtSaatIniDanSebelumnyalagi11;
	private Boolean bayarHanyaSmtSaatIniDanSebelumnyalagi12;
	private Boolean bayarHanyaSmtSaatIniDanSebelumnyalagi13;
	private Boolean bayarHanyaSmtSaatIniDanSebelumnyalagi14;

	private Boolean dendaJikaTerlambat;
	private Boolean dendaDibuatPerProdi;
	private Boolean nilaiDendaDalamPersen;
	private Integer dendaAkanBerlipatTerlambaHari;
	private Integer maksimalBerlipatTerlambaHari;
	private Double defaultProsentaseDenda;
	private String dendaPerProdi;
	private Boolean untukBayarSP;

	private Boolean abaikanNilaiMinus;

	public String toString() {
		return id + "-" + kode + "-" + namaKegiatan;
	}

	public JenisKegiatan() {
	}

	public JenisKegiatan(Long id) {
		this.id = id;
	}

	public JenisKegiatan(String namaKegiatan) {
		this.namaKegiatan = namaKegiatan;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", insertable = false, unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "nama_kegiatan", nullable = false, insertable = false, updatable = false, length = 100)
	public String getNama() {
		return this.namaKegiatan;
	}

	public void setNama(String namaKegiatan) {
		this.namaKegiatan = namaKegiatan;
	}

	@Column(name = "nama_kegiatan", nullable = false, length = 100)
	public String getNamaKegiatan() {
		return this.namaKegiatan;
	}

	public void setNamaKegiatan(String namaKegiatan) {
		this.namaKegiatan = namaKegiatan;
	}

	public void setKode(String kode) {
		this.kode = kode;
	}

	public String getKode() {
		if (kode == null || kode.trim().isEmpty()) {
			if (getNamaKegiatan() != null && getNamaKegiatan().equals(ConstantUtil.PENDAFTARAN_MAHASISWA_LAMA)) {
				kode = ConstantUtil.PEMBAYARAN_PENDAFTARAN_ULANG;
			} else if (getNamaKegiatan() != null
					&& getNamaKegiatan().equals(ConstantUtil.PENDAFTARAN_CALON_MAHASISWA)) {
				kode = ConstantUtil.PEMBAYARAN_PENDAFTARAN_CALON_MAHASISWA;
			} else if (getNamaKegiatan() != null
					&& getNamaKegiatan().equals(ConstantUtil.PENDAFTARAN_ULANG_MAHASISWA_BARU)) {
				kode = ConstantUtil.PEMBAYARAN_PENDAFTARAN_ULANG_MAHASISWA_BARU;
			} else if (getNamaKegiatan() != null && getNamaKegiatan().equals(ConstantUtil.PENDAFTARAN_WISUDA)) {
				kode = ConstantUtil.PEMBAYARAN_PENDAFTARAN_WISUDA;
			}
		}
		return kode;
	}

	public void setDefaultKegiatan(Boolean defaultKegiatan) {
		this.defaultKegiatan = defaultKegiatan;
	}

	@Column(name = "default_kegiatan")
	public Boolean getDefaultKegiatan() {
		return defaultKegiatan;
	}

	public Boolean getAktif() {
		if (aktif == null) {
			aktif = true;
		}
		JenisKegiatan jenisKegiatan = this;
		if (jenisKegiatan.getId() != null) {
			if ((ConstantValues.PENDAFTARAN_CALON_MAHASISWA != null
					&& jenisKegiatan.getId().equals(ConstantValues.PENDAFTARAN_CALON_MAHASISWA.getId()))
					|| (ConstantValues.PENDAFTARAN_MAHASISWA_LAMA != null
							&& jenisKegiatan.getId().equals(ConstantValues.PENDAFTARAN_MAHASISWA_LAMA.getId()))
					|| (ConstantValues.PENDAFTARAN_ULANG_MAHASISWA_BARU != null
							&& jenisKegiatan.getId().equals(ConstantValues.PENDAFTARAN_ULANG_MAHASISWA_BARU.getId()))) {
				aktif = true;
			}
		}

		return aktif;
	}

	public void setAktif(Boolean aktif) {
		this.aktif = aktif;
	}

	@Column(name = "digunakan_untuk_pengecekan_krs")
	public Boolean getDigunakanUntukPengecekanKrs() {
		if (namaKegiatan != null && namaKegiatan.equalsIgnoreCase(ConstantUtil.PENDAFTARAN_MAHASISWA_LAMA)) {
			digunakanUntukPengecekanKrs = true;
		}
		return digunakanUntukPengecekanKrs == null ? false : digunakanUntukPengecekanKrs;
	}

	public void setDigunakanUntukPengecekanKrs(Boolean digunakanUntukPengecekanKrs) {
		this.digunakanUntukPengecekanKrs = digunakanUntukPengecekanKrs;
	}

	@Column(name = "default_pembayaran")
	public Boolean getDefaultPembayaran() {
		return defaultPembayaran == null ? false : defaultPembayaran;
	}

	public void setDefaultPembayaran(Boolean defaultPembayaran) {
		this.defaultPembayaran = defaultPembayaran;
	}

	public Integer getMinSmt() {
		return minSmt == null ? 0 : minSmt;
	}

	public void setMinSmt(Integer minSmt) {
		this.minSmt = minSmt;
	}

	public Integer getMaxSmt() {
		if (getNamaKegiatan() != null && getNamaKegiatan().equals(ConstantUtil.PENDAFTARAN_MAHASISWA_LAMA)) {
			if (maxSmt == null)
				maxSmt = 14;
		} else if (getNamaKegiatan() != null && getNamaKegiatan().equals(ConstantUtil.PENDAFTARAN_CALON_MAHASISWA)) {
			if (maxSmt == null)
				maxSmt = 1;
		} else if (getNamaKegiatan() != null
				&& getNamaKegiatan().equals(ConstantUtil.PENDAFTARAN_ULANG_MAHASISWA_BARU)) {
			if (maxSmt == null)
				maxSmt = 1;
		} else if (getNamaKegiatan() != null && getNamaKegiatan().equals(ConstantUtil.PENDAFTARAN_WISUDA)) {
			if (maxSmt == null)
				maxSmt = 20;
		}
		if (maxSmt == null) {
			maxSmt = 30;
		}
		return maxSmt;
	}

	public void setMaxSmt(Integer maxSmt) {
		this.maxSmt = maxSmt;
	}

	public Boolean getDigunakanUntukPengecekanUjian() {
		if (digunakanUntukPengecekanUjian == null) {
			digunakanUntukPengecekanUjian = getDigunakanUntukPengecekanKrs();
		}
		return digunakanUntukPengecekanUjian;
	}

	public void setDigunakanUntukPengecekanUjian(Boolean digunakanUntukPengecekanUjian) {
		this.digunakanUntukPengecekanUjian = digunakanUntukPengecekanUjian;
	}

	public Boolean getDigunakanSyaratKeaktifan() {
		if (getNamaKegiatan() != null && getNamaKegiatan().equals(ConstantUtil.PENDAFTARAN_MAHASISWA_LAMA)) {
			digunakanSyaratKeaktifan = true;
		} else if (getNamaKegiatan() != null
				&& getNamaKegiatan().equals(ConstantUtil.PENDAFTARAN_ULANG_MAHASISWA_BARU)) {
			if (digunakanSyaratKeaktifan == null)
				digunakanSyaratKeaktifan = true;
		}
		return digunakanSyaratKeaktifan == null ? false : digunakanSyaratKeaktifan;
	}

	public void setDigunakanSyaratKeaktifan(Boolean digunakanSyaratKeaktifan) {
		this.digunakanSyaratKeaktifan = digunakanSyaratKeaktifan;
	}

	public Boolean getDigunakanSyaratLogin() {
		return digunakanSyaratLogin == null ? false : digunakanSyaratLogin;
	}

	public void setDigunakanSyaratLogin(Boolean digunakanSyaratLogin) {
		this.digunakanSyaratLogin = digunakanSyaratLogin;
	}

	public Double getPersenSyaratLogin() {
		return persenSyaratLogin == null ? 0.0 : persenSyaratLogin;
	}

	public void setPersenSyaratLogin(Double persenSyaratLogin) {
		this.persenSyaratLogin = persenSyaratLogin;
	}

	public Double getPersenSyaratLogin1() {
		return persenSyaratLogin1 == null ? getPersenSyaratLogin() : persenSyaratLogin1;
	}

	public void setPersenSyaratLogin1(Double persenSyaratLogin1) {
		this.persenSyaratLogin1 = persenSyaratLogin1;
	}

	public Double getPersenSyaratLogin2() {
		return persenSyaratLogin2 == null ? getPersenSyaratLogin() : persenSyaratLogin2;
	}

	public void setPersenSyaratLogin2(Double persenSyaratLogin2) {
		this.persenSyaratLogin2 = persenSyaratLogin2;
	}

	public Boolean getBayarHanyaSmtSaatIni() {
		return bayarHanyaSmtSaatIni == null ? false : bayarHanyaSmtSaatIni;
	}

	public void setBayarHanyaSmtSaatIni(Boolean bayarHanyaSmtSaatIni) {
		this.bayarHanyaSmtSaatIni = bayarHanyaSmtSaatIni;
	}

	public Boolean getBayarHanyaSmtSaatIniDanSebelumnya() {
		return bayarHanyaSmtSaatIniDanSebelumnya == null ? false : bayarHanyaSmtSaatIniDanSebelumnya;
	}

	public void setBayarHanyaSmtSaatIniDanSebelumnya(Boolean bayarHanyaSmtSaatIniDanSebelumnya) {
		this.bayarHanyaSmtSaatIniDanSebelumnya = bayarHanyaSmtSaatIniDanSebelumnya;
	}

	public static void apakahBoleh(Mahasiswa mahasiswa, int currentSmt, List<String> warning) throws Exception {
		// 1. Reload data jika null
		if (ais.common.CommonHelperClass.jenisKegiatansAktif == null) {
			Common.reloadJenisKegiatans();
		}

		if (ais.common.CommonHelperClass.jenisKegiatansAktif == null) {
			return; // Cegah NullPointerException jika reload tetap gagal
		}

		// 2. Iterasi langsung tanpa membuat ArrayList sementara (Hemat Memory)
		for (JenisKegiatan syarat : ais.common.CommonHelperClass.jenisKegiatansAktif) {
			if (!syarat.getDigunakanSyaratLogin()) {
				continue; // Skip jika tidak digunakan sebagai syarat login
			}

			// 3. Masukkan aturan boolean ke dalam Array agar bisa di-loop secara dinamis
			boolean[] aturanSmtMundur = { syarat.getBayarHanyaSmtSaatIni(),
					syarat.getBayarHanyaSmtSaatIniDanSebelumnya(), syarat.getBayarHanyaSmtSaatIniDanSebelumnyalagi(),
					syarat.getBayarHanyaSmtSaatIniDanSebelumnyalagi3(),
					syarat.getBayarHanyaSmtSaatIniDanSebelumnyalagi4(),
					syarat.getBayarHanyaSmtSaatIniDanSebelumnyalagi5(),
					syarat.getBayarHanyaSmtSaatIniDanSebelumnyalagi6(),
					syarat.getBayarHanyaSmtSaatIniDanSebelumnyalagi7(),
					syarat.getBayarHanyaSmtSaatIniDanSebelumnyalagi8() };

			// Cek apakah ada spesifik semester mundur yang diaktifkan
			boolean adaAturanSpesifik = false;
			for (boolean aturanAktif : aturanSmtMundur) {
				if (aturanAktif) {
					adaAturanSpesifik = true;
					break;
				}
			}

			if (adaAturanSpesifik) {
				// Loop 0 s.d 8 sesuai dengan index boolean array di atas
				for (int i = 0; i < aturanSmtMundur.length; i++) {
					if (aturanSmtMundur[i] && currentSmt > i) {
						int targetSmt = currentSmt - i;
						PendaftaranCutiMahasiswa cuti = mahasiswa.ambilCuti(targetSmt, null, false);

						// Jika tidak cuti atau cuti tidak disetujui, maka cek syarat masuk
						if (cuti == null || !cuti.getPersetujuan()) {
							syarat.bolehMasuk(mahasiswa, targetSmt, i, warning);
						}
					}
				}
			} else {
				// Jika tidak ada aturan spesifik mundur, cek dari minimal semester sampai saat
				// ini
				for (int smtMulai = syarat.getMinSmt(); smtMulai <= currentSmt; smtMulai++) {
					PendaftaranCutiMahasiswa cuti = mahasiswa.ambilCuti(smtMulai, null, false);
					if (cuti == null || !cuti.getPersetujuan()) {
						syarat.bolehMasuk(mahasiswa, smtMulai, 0, warning);
					}
				}
			}
		}
	}

	public boolean bolehMasuk(Mahasiswa mahasiswa, int smtMulai, int smtMundur, List<String> warning) throws Exception {
		// Validasi batas rentang semester
		if (smtMulai == 0 || getMinSmt() > smtMulai || getMaxSmt() < smtMulai) {
			return true;
		}

		// Pengecualian khusus untuk Genap smt 1
		if (Perkuliahan.GENAP.equalsIgnoreCase(mahasiswa.getSemesterMulai()) && smtMulai == 1) {
			return true;
		}

		// Gunakan Switch-Case untuk menentukan persen syarat agar lebih cepat (O(1))
		// dan rapi
		double persenSyarat = 0.0;
		switch (smtMundur) {
		case 1:
			persenSyarat = this.getPersenSyaratLogin1();
			break;
		case 2:
			persenSyarat = this.getPersenSyaratLogin2();
			break;
		case 3:
			persenSyarat = this.getPersenSyaratLogin3();
			break;
		case 4:
			persenSyarat = this.getPersenSyaratLogin4();
			break;
		case 5:
			persenSyarat = this.getPersenSyaratLogin5();
			break;
		case 6:
			persenSyarat = this.getPersenSyaratLogin6();
			break;
		case 7:
			persenSyarat = this.getPersenSyaratLogin7();
			break;
		case 8:
			persenSyarat = this.getPersenSyaratLogin8();
			break;
		case 9:
			persenSyarat = this.getPersenSyaratLogin9();
			break;
		case 10:
			persenSyarat = this.getPersenSyaratLogin10();
			break;
		case 11:
			persenSyarat = this.getPersenSyaratLogin11();
			break;
		case 12:
			persenSyarat = this.getPersenSyaratLogin12();
			break;
		case 13:
			persenSyarat = this.getPersenSyaratLogin13();
			break;
		case 14:
			persenSyarat = this.getPersenSyaratLogin14();
			break;
		default:
			persenSyarat = this.getPersenSyaratLogin();
			break; // Berlaku untuk index 0 atau tidak terdaftar
		}

		// Jika lolos bypass status, tidak perlu cek tagihan
		if (Common.checkBaypassStatusPembayaranMahasiswa(smtMulai, null, mahasiswa, this)) {
			return true;
		}

		if (persenSyarat > 0.1) {
			Kegiatan kegiatan = null;

			// Deteksi apakah ini Kegiatan Calon Mahasiswa atau Mahasiswa Baru
			boolean isPendaftaranUlangBaru = ConstantValues.PENDAFTARAN_ULANG_MAHASISWA_BARU != null
					&& this.getId() != null
					&& this.getId().equals(ConstantValues.PENDAFTARAN_ULANG_MAHASISWA_BARU.getId());

			boolean isPendaftaranCalonMhs = ConstantValues.PENDAFTARAN_CALON_MAHASISWA != null && this.getId() != null
					&& this.getId().equals(ConstantValues.PENDAFTARAN_CALON_MAHASISWA.getId());

			// Penentuan Data Kegiatan
			if (mahasiswa.getBiodataCalonMahasiswa() != null && mahasiswa.getBiodataCalonMahasiswaData() != null) {
				if (isPendaftaranUlangBaru || isPendaftaranCalonMhs) {
					kegiatan = mahasiswa.getBiodataCalonMahasiswaData().ambilKegiatans(smtMulai, this);
				}
			}

			// Jika bukan dari pendaftaran calon mhs, ambil dari data mahasiswa aktif
			if (kegiatan == null) {
				kegiatan = mahasiswa.ambilKegiatans(smtMulai, this);
			}

			// Validasi Jika Punya Tunggakan dan Persentase Bayar di Bawah Syarat
			if (kegiatan != null && kegiatan.getPersentase() < persenSyarat) {

				// Blok Pemanggilan UI Modal
				try {
					ExecutionCtrl ctrl = ExecutionsCtrl.getCurrentCtrl();
					if (ctrl != null && ctrl.getCurrentPage() != null) {

						final MyWindow window = new MyWindow("", "none", false);
						ctrl.getCurrentPage().getFirstRoot().appendChild(window);

						org.zkoss.zul.Borderlayout borderlayout = new org.zkoss.zul.Borderlayout();
						borderlayout.setParent(window);

						org.zkoss.zul.Center center = new org.zkoss.zul.Center();
						center.setBorder("none");
						center.setParent(borderlayout);
						ais.ui.util.ZkCompat.setFlex(center, true);
						center.appendChild(
								new ais.ui.util.MyInclude("/pages/master/informasi_pembayaran_mahasiswa.zul"));

						org.zkoss.zul.South south = new org.zkoss.zul.South();
						ais.ui.util.ZkCompat.setFlex(south, true);
						south.setParent(borderlayout);

						org.zkoss.zul.Toolbar toolbar = new org.zkoss.zul.Toolbar();
						toolbar.setParent(south);

						MyToolbarbuttonConfig cancel = new MyToolbarbuttonConfig("Selesai", "/img/cancel.gif");
						cancel.setTooltiptext("Tutup");
						cancel.addEventListener("onClick", new org.zkoss.zk.ui.event.EventListener() {
							@Override
							public void onEvent(org.zkoss.zk.ui.event.Event event) throws Exception {
								Common.goLogoff();
							}
						});
						cancel.setParent(toolbar);

						window.setVisible(true);
						window.setHeight("99%");
						window.setWidth("99%");
						window.onModal();
					}
				} catch (Exception e) {
					e.printStackTrace(); ais.common.ErrorAuditUtil.record(e, "auto-audit src/ais/database/model/JenisKegiatan.java:602"); // Tampilkan error ke server log, bukan ditelan diam-diam
				}

				String textPeringatan = "Mohon maaf, Anda belum dapat mengakses sistem. "
				        + "Syarat minimum pembayaran untuk tagihan \"" + this.getNamaKegiatan() + "\" "
				        + "di Semester " + smtMulai + " adalah " + Common.numberFormat.get().format(persenSyarat) + "%, "
				        + "sedangkan total pembayaran Anda saat ini tercatat sebesar " 
				        + Common.numberFormat.get().format(kegiatan.getPersentase()) + "%.\n\n"
				        + "Untuk informasi dan bantuan lebih lanjut, silakan menghubungi Bagian Keuangan.";

				warning.add(textPeringatan);

				return false;
			}
		}

		return true;
	}

	public Boolean getBayarHanyaSmtSaatIniDanSebelumnyalagi() {
		return bayarHanyaSmtSaatIniDanSebelumnyalagi == null ? false : bayarHanyaSmtSaatIniDanSebelumnyalagi;
	}

	public void setBayarHanyaSmtSaatIniDanSebelumnyalagi(Boolean bayarHanyaSmtSaatIniDanSebelumnyalagi) {
		this.bayarHanyaSmtSaatIniDanSebelumnyalagi = bayarHanyaSmtSaatIniDanSebelumnyalagi;
	}

	public Boolean getDigunakanUntukPengecekanNilai() {
		return digunakanUntukPengecekanNilai == null ? false : digunakanUntukPengecekanNilai;
	}

	public void setDigunakanUntukPengecekanNilai(Boolean digunakanUntukPengecekanNilai) {
		this.digunakanUntukPengecekanNilai = digunakanUntukPengecekanNilai;
	}

	public Boolean getTidakBolehMengangsur() {
		return tidakBolehMengangsur == null ? false : tidakBolehMengangsur;
	}

	public void setTidakBolehMengangsur(Boolean tidakBolehMengangsur) {
		this.tidakBolehMengangsur = tidakBolehMengangsur;
	}

	public Boolean getTagihanJugaUntukAlumni() {
		if (tagihanJugaUntukAlumni == null) {
			if (getNamaKegiatan() != null && getNamaKegiatan().toLowerCase().contains("wisuda")) {
				tagihanJugaUntukAlumni = true;
			} else {
				String alumni = retreive("tagihan_juga_untuk_alumni");
				if (alumni == null) {
					alumni = "";
				}
				tagihanJugaUntukAlumni = alumni.equalsIgnoreCase("true");
			}

		}
		return tagihanJugaUntukAlumni;
	}

	public void setTagihanJugaUntukAlumni(Boolean tagihanJugaUntukAlumni) {
		this.tagihanJugaUntukAlumni = tagihanJugaUntukAlumni;
	}

	public Boolean getDigunakanSyaratCetakSuratBebasAktif() {
		return digunakanSyaratCetakSuratBebasAktif == null ? true : digunakanSyaratCetakSuratBebasAktif;
	}

	public void setDigunakanSyaratCetakSuratBebasAktif(Boolean digunakanSyaratCetakSuratBebasAktif) {
		this.digunakanSyaratCetakSuratBebasAktif = digunakanSyaratCetakSuratBebasAktif;
	}

	@Column(columnDefinition = "text")
	public String getPenjelasanPembayaran() {
		return penjelasanPembayaran == null ? "" : penjelasanPembayaran;
	}

	public void setPenjelasanPembayaran(String penjelasanPembayaran) {
		this.penjelasanPembayaran = penjelasanPembayaran;
	}

	public Boolean getBayarHanyaSmtSaatIniDanSebelumnyalagi3() {
		return bayarHanyaSmtSaatIniDanSebelumnyalagi3 == null ? false : bayarHanyaSmtSaatIniDanSebelumnyalagi3;
	}

	public void setBayarHanyaSmtSaatIniDanSebelumnyalagi3(Boolean bayarHanyaSmtSaatIniDanSebelumnyalagi3) {
		this.bayarHanyaSmtSaatIniDanSebelumnyalagi3 = bayarHanyaSmtSaatIniDanSebelumnyalagi3;
	}

	public Boolean getBayarHanyaSmtSaatIniDanSebelumnyalagi4() {
		return bayarHanyaSmtSaatIniDanSebelumnyalagi4 == null ? false : bayarHanyaSmtSaatIniDanSebelumnyalagi4;
	}

	public void setBayarHanyaSmtSaatIniDanSebelumnyalagi4(Boolean bayarHanyaSmtSaatIniDanSebelumnyalagi4) {
		this.bayarHanyaSmtSaatIniDanSebelumnyalagi4 = bayarHanyaSmtSaatIniDanSebelumnyalagi4;
	}

	public Boolean getBayarHanyaSmtSaatIniDanSebelumnyalagi5() {
		return bayarHanyaSmtSaatIniDanSebelumnyalagi5 == null ? false : bayarHanyaSmtSaatIniDanSebelumnyalagi5;
	}

	public void setBayarHanyaSmtSaatIniDanSebelumnyalagi5(Boolean bayarHanyaSmtSaatIniDanSebelumnyalagi5) {
		this.bayarHanyaSmtSaatIniDanSebelumnyalagi5 = bayarHanyaSmtSaatIniDanSebelumnyalagi5;
	}

	public Boolean getBayarHanyaSmtSaatIniDanSebelumnyalagi6() {
		return bayarHanyaSmtSaatIniDanSebelumnyalagi6 == null ? false : bayarHanyaSmtSaatIniDanSebelumnyalagi6;
	}

	public void setBayarHanyaSmtSaatIniDanSebelumnyalagi6(Boolean bayarHanyaSmtSaatIniDanSebelumnyalagi6) {
		this.bayarHanyaSmtSaatIniDanSebelumnyalagi6 = bayarHanyaSmtSaatIniDanSebelumnyalagi6;
	}

	public Boolean getBayarHanyaSmtSaatIniDanSebelumnyalagi7() {
		return bayarHanyaSmtSaatIniDanSebelumnyalagi7 == null ? false : bayarHanyaSmtSaatIniDanSebelumnyalagi7;
	}

	public void setBayarHanyaSmtSaatIniDanSebelumnyalagi7(Boolean bayarHanyaSmtSaatIniDanSebelumnyalagi7) {
		this.bayarHanyaSmtSaatIniDanSebelumnyalagi7 = bayarHanyaSmtSaatIniDanSebelumnyalagi7;
	}

	public Boolean getBayarHanyaSmtSaatIniDanSebelumnyalagi8() {
		return bayarHanyaSmtSaatIniDanSebelumnyalagi8 == null ? false : bayarHanyaSmtSaatIniDanSebelumnyalagi8;
	}

	public void setBayarHanyaSmtSaatIniDanSebelumnyalagi8(Boolean bayarHanyaSmtSaatIniDanSebelumnyalagi8) {
		this.bayarHanyaSmtSaatIniDanSebelumnyalagi8 = bayarHanyaSmtSaatIniDanSebelumnyalagi8;
	}

	public Double getPersenSyaratLogin3() {
		return persenSyaratLogin3 == null ? getPersenSyaratLogin() : persenSyaratLogin3;
	}

	public void setPersenSyaratLogin3(Double persenSyaratLogin3) {
		this.persenSyaratLogin3 = persenSyaratLogin3;
	}

	public Double getPersenSyaratLogin4() {
		return persenSyaratLogin4 == null ? getPersenSyaratLogin() : persenSyaratLogin4;
	}

	public void setPersenSyaratLogin4(Double persenSyaratLogin4) {
		this.persenSyaratLogin4 = persenSyaratLogin4;
	}

	public Double getPersenSyaratLogin5() {
		return persenSyaratLogin5 == null ? getPersenSyaratLogin() : persenSyaratLogin5;
	}

	public void setPersenSyaratLogin5(Double persenSyaratLogin5) {
		this.persenSyaratLogin5 = persenSyaratLogin5;
	}

	public Double getPersenSyaratLogin6() {
		return persenSyaratLogin6 == null ? getPersenSyaratLogin() : persenSyaratLogin6;
	}

	public void setPersenSyaratLogin6(Double persenSyaratLogin6) {
		this.persenSyaratLogin6 = persenSyaratLogin6;
	}

	public Double getPersenSyaratLogin7() {
		return persenSyaratLogin7 == null ? getPersenSyaratLogin() : persenSyaratLogin7;
	}

	public void setPersenSyaratLogin7(Double persenSyaratLogin7) {
		this.persenSyaratLogin7 = persenSyaratLogin7;
	}

	public Double getPersenSyaratLogin8() {
		return persenSyaratLogin8 == null ? getPersenSyaratLogin() : persenSyaratLogin8;
	}

	public void setPersenSyaratLogin8(Double persenSyaratLogin8) {
		this.persenSyaratLogin8 = persenSyaratLogin8;
	}

	public Boolean getDendaJikaTerlambat() {
		return dendaJikaTerlambat == null ? false : dendaJikaTerlambat;
	}

	public void setDendaJikaTerlambat(Boolean dendaJikaTerlambat) {
		this.dendaJikaTerlambat = dendaJikaTerlambat;
	}

	public Double getDefaultProsentaseDenda() {
		return defaultProsentaseDenda == null ? 0.0 : defaultProsentaseDenda;
	}

	public void setDefaultProsentaseDenda(Double defaultProsentaseDenda) {
		this.defaultProsentaseDenda = defaultProsentaseDenda;
	}

	public Boolean getNilaiDendaDalamPersen() {
		return nilaiDendaDalamPersen == null ? true : nilaiDendaDalamPersen;
	}

	public void setNilaiDendaDalamPersen(Boolean nilaiDendaDalamPersen) {
		this.nilaiDendaDalamPersen = nilaiDendaDalamPersen;
	}

	public Integer getDendaAkanBerlipatTerlambaHari() {
		return dendaAkanBerlipatTerlambaHari == null ? 0 : dendaAkanBerlipatTerlambaHari;
	}

	public void setDendaAkanBerlipatTerlambaHari(Integer dendaAkanBerlipatTerlambaHari) {
		this.dendaAkanBerlipatTerlambaHari = dendaAkanBerlipatTerlambaHari;
	}

	public Integer getMaksimalBerlipatTerlambaHari() {
		return maksimalBerlipatTerlambaHari == null ? 0 : maksimalBerlipatTerlambaHari;
	}

	public void setMaksimalBerlipatTerlambaHari(Integer maksimalBerlipatTerlambaHari) {
		this.maksimalBerlipatTerlambaHari = maksimalBerlipatTerlambaHari;
	}

	public Boolean getHanyaBerupaAngsuran() {
		return hanyaBerupaAngsuran == null ? false : hanyaBerupaAngsuran;
	}

	public void setHanyaBerupaAngsuran(Boolean hanyaBerupaAngsuran) {
		this.hanyaBerupaAngsuran = hanyaBerupaAngsuran;
	}

	public Double getPersenSyaratLogin9() {
		return persenSyaratLogin9 == null ? getPersenSyaratLogin() : persenSyaratLogin9;
	}

	public void setPersenSyaratLogin9(Double persenSyaratLogin9) {
		this.persenSyaratLogin9 = persenSyaratLogin9;
	}

	public Double getPersenSyaratLogin10() {
		return persenSyaratLogin10 == null ? getPersenSyaratLogin() : persenSyaratLogin10;
	}

	public void setPersenSyaratLogin10(Double persenSyaratLogin10) {
		this.persenSyaratLogin10 = persenSyaratLogin10;
	}

	public Double getPersenSyaratLogin11() {
		return persenSyaratLogin11 == null ? getPersenSyaratLogin() : persenSyaratLogin11;
	}

	public void setPersenSyaratLogin11(Double persenSyaratLogin11) {
		this.persenSyaratLogin11 = persenSyaratLogin11;
	}

	public Double getPersenSyaratLogin12() {
		return persenSyaratLogin12 == null ? getPersenSyaratLogin() : persenSyaratLogin12;
	}

	public void setPersenSyaratLogin12(Double persenSyaratLogin12) {
		this.persenSyaratLogin12 = persenSyaratLogin12;
	}

	public Double getPersenSyaratLogin13() {
		return persenSyaratLogin13 == null ? getPersenSyaratLogin() : persenSyaratLogin13;
	}

	public void setPersenSyaratLogin13(Double persenSyaratLogin13) {
		this.persenSyaratLogin13 = persenSyaratLogin13;
	}

	public Double getPersenSyaratLogin14() {
		return persenSyaratLogin14 == null ? getPersenSyaratLogin() : persenSyaratLogin14;
	}

	public void setPersenSyaratLogin14(Double persenSyaratLogin14) {
		this.persenSyaratLogin14 = persenSyaratLogin14;
	}

	public Boolean getBayarHanyaSmtSaatIniDanSebelumnyalagi9() {
		return bayarHanyaSmtSaatIniDanSebelumnyalagi9 == null ? false : bayarHanyaSmtSaatIniDanSebelumnyalagi9;
	}

	public void setBayarHanyaSmtSaatIniDanSebelumnyalagi9(Boolean bayarHanyaSmtSaatIniDanSebelumnyalagi9) {
		this.bayarHanyaSmtSaatIniDanSebelumnyalagi9 = bayarHanyaSmtSaatIniDanSebelumnyalagi9;
	}

	public Boolean getBayarHanyaSmtSaatIniDanSebelumnyalagi10() {
		return bayarHanyaSmtSaatIniDanSebelumnyalagi10 == null ? false : bayarHanyaSmtSaatIniDanSebelumnyalagi10;
	}

	public void setBayarHanyaSmtSaatIniDanSebelumnyalagi10(Boolean bayarHanyaSmtSaatIniDanSebelumnyalagi10) {
		this.bayarHanyaSmtSaatIniDanSebelumnyalagi10 = bayarHanyaSmtSaatIniDanSebelumnyalagi10;
	}

	public Boolean getBayarHanyaSmtSaatIniDanSebelumnyalagi11() {
		return bayarHanyaSmtSaatIniDanSebelumnyalagi11 == null ? false : bayarHanyaSmtSaatIniDanSebelumnyalagi11;
	}

	public void setBayarHanyaSmtSaatIniDanSebelumnyalagi11(Boolean bayarHanyaSmtSaatIniDanSebelumnyalagi11) {
		this.bayarHanyaSmtSaatIniDanSebelumnyalagi11 = bayarHanyaSmtSaatIniDanSebelumnyalagi11;
	}

	public Boolean getBayarHanyaSmtSaatIniDanSebelumnyalagi12() {
		return bayarHanyaSmtSaatIniDanSebelumnyalagi12 == null ? false : bayarHanyaSmtSaatIniDanSebelumnyalagi12;
	}

	public void setBayarHanyaSmtSaatIniDanSebelumnyalagi12(Boolean bayarHanyaSmtSaatIniDanSebelumnyalagi12) {
		this.bayarHanyaSmtSaatIniDanSebelumnyalagi12 = bayarHanyaSmtSaatIniDanSebelumnyalagi12;
	}

	public Boolean getBayarHanyaSmtSaatIniDanSebelumnyalagi13() {
		return bayarHanyaSmtSaatIniDanSebelumnyalagi13 == null ? false : bayarHanyaSmtSaatIniDanSebelumnyalagi13;
	}

	public void setBayarHanyaSmtSaatIniDanSebelumnyalagi13(Boolean bayarHanyaSmtSaatIniDanSebelumnyalagi13) {
		this.bayarHanyaSmtSaatIniDanSebelumnyalagi13 = bayarHanyaSmtSaatIniDanSebelumnyalagi13;
	}

	public Boolean getBayarHanyaSmtSaatIniDanSebelumnyalagi14() {
		return bayarHanyaSmtSaatIniDanSebelumnyalagi14 == null ? false : bayarHanyaSmtSaatIniDanSebelumnyalagi14;
	}

	public void setBayarHanyaSmtSaatIniDanSebelumnyalagi14(Boolean bayarHanyaSmtSaatIniDanSebelumnyalagi14) {
		this.bayarHanyaSmtSaatIniDanSebelumnyalagi14 = bayarHanyaSmtSaatIniDanSebelumnyalagi14;
	}

	public Boolean getUntukBayarSP() {
		return untukBayarSP == null ? false : untukBayarSP;
	}

	public void setUntukBayarSP(Boolean untukBayarSP) {
		this.untukBayarSP = untukBayarSP;
	}

	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY)
	@JoinColumn(name = "kanal_pembayaran", nullable = true)
	public KanalPembayaran getKanalPembayaran() {
		kanalPembayaran = check(kanalPembayaran);
		return kanalPembayaran;
	}

	public void setKanalPembayaran(KanalPembayaran kanalPembayaran) {
		this.kanalPembayaran = kanalPembayaran;
	}

	public Boolean getHanyaBerupaBukanAngsuran() {
		return hanyaBerupaBukanAngsuran == null ? false : hanyaBerupaBukanAngsuran;
	}

	public void setHanyaBerupaBukanAngsuran(Boolean hanyaBerupaBukanAngsuran) {
		this.hanyaBerupaBukanAngsuran = hanyaBerupaBukanAngsuran;
	}

	@javax.persistence.Column(name = "jenjang_angsuran_json")
	public String getJenjangAngsuranJson() {
		return jenjangAngsuranJson;
	}

	public void setJenjangAngsuranJson(String jenjangAngsuranJson) {
		this.jenjangAngsuranJson = jenjangAngsuranJson;
	}

	/**
	 * Periksa apakah jenjang tertentu masuk dalam array bertanda key ("harus" atau "bukan")
	 * di dalam jenjangAngsuranJson. Array kosong/null berarti berlaku untuk semua jenjang.
	 */
	private boolean jenjangDalamArray(String key, Jenjang jenjang) {
		if (jenjangAngsuranJson == null || jenjangAngsuranJson.trim().isEmpty()) return true;
		try {
			JSONArray arr = new JSONObject(jenjangAngsuranJson).optJSONArray(key);
			if (arr == null || arr.length() == 0) return true;
			if (jenjang == null || jenjang.getId() == null) return false;
			String jid = String.valueOf(jenjang.getId());
			for (int i = 0; i < arr.length(); i++) {
				try { if (jid.equals(arr.getString(i))) return true; } catch (Exception ignored) { ais.common.ErrorAuditUtil.record(ignored, "auto-audit(empty-catch) src/ais/database/model/JenisKegiatan.java:970");}
			}
		} catch (Exception ignored) { ais.common.ErrorAuditUtil.record(ignored, "auto-audit(empty-catch) src/ais/database/model/JenisKegiatan.java:972");}
		return false;
	}

	/** Set true untuk mencetak log tiap panggilan modeAngsuranUntukJenjang. */
	public static boolean DEBUG_MODE_ANGSURAN = false;

	/**
	 * Tentukan mode angsuran untuk jenjang tertentu berdasarkan kombinasi flag:
	 * <ul>
	 *   <li>{@link Boolean#TRUE}  → jenjang ini HARUS pakai angsuran (cicilan)</li>
	 *   <li>{@link Boolean#FALSE} → jenjang ini BUKAN angsuran (reguler/sekaligus)</li>
	 *   <li>{@code null}          → tidak ada aturan khusus; ikuti logika default</li>
	 * </ul>
	 * Logika:
	 * <ol>
	 *   <li>Kedua flag aktif (harus &amp;&amp; bukan) → per-jenjang; "bukan" override "harus"</li>
	 *   <li>Hanya harus aktif → jenjang di array "harus" ⇒ TRUE, else null</li>
	 *   <li>Hanya bukan aktif → jenjang di array "bukan" ⇒ FALSE, else null</li>
	 * </ol>
	 */
	public Boolean modeAngsuranUntukJenjang(Jenjang jenjang) {
		return modeAngsuranUntukJenjang(jenjang, null);
	}

	/**
	 * Periksa apakah aturan angsuran kunci tertentu ("harus"/"bukan") berlaku pada
	 * SEMESTER (dan opsional TAHUN ANGKATAN) yang diminta, berdasarkan peta
	 * {@code <key>_smt} di jenjangAngsuranJson — isian field "Berlaku di smt" pada form
	 * Jenis Kegiatan. Format isian (dipisah koma, boleh dicampur):
	 * <ul>
	 *   <li>{@code 1,2,3,5,6} — daftar semester GLOBAL: berlaku di smt tersebut untuk
	 *       semua angkatan (contoh ini: TIDAK berlaku di smt 4).</li>
	 *   <li>{@code 2023:1} — khusus angkatan 2023 semester 1.</li>
	 *   <li>{@code 2023:1,2,3,4,5,8} — angka setelah token {@code TAHUN:SMT} tetap milik
	 *       angkatan tersebut sampai bertemu token ber-titik-dua berikutnya; contoh:
	 *       {@code 2023:1,2,8,2024:1} = angkatan 2023 smt 1,2,8 dan angkatan 2024 smt 1.</li>
	 *   <li>{@code 2023:} (tanpa smt) — angkatan 2023 di SEMUA semester.</li>
	 * </ul>
	 * Prioritas pencocokan: (1) bila tahun angkatan mahasiswa punya entri sendiri, pakai
	 * daftar smt angkatan itu (kosong = semua smt); (2) bila tidak, pakai daftar global;
	 * (3) bila hanya ada entri ber-angkatan dan angkatan mahasiswa tidak terdaftar,
	 * aturan dianggap TIDAK berlaku untuk mahasiswa itu. Kosong/tidak ada isian = berlaku
	 * di semua semester &amp; angkatan (kompatibel data lama). {@code semester == null} =
	 * tanpa konteks semester → cocok; {@code angkatan == null} = tanpa konteks angkatan →
	 * entri ber-angkatan diabaikan (jatuh ke daftar global / toleran).
	 */
	private boolean semesterCocokUntukJenjang(String key, Jenjang jenjang, Integer semester, Integer angkatan) {
		if (semester == null)
			return true;
		if (jenjangAngsuranJson == null || jenjangAngsuranJson.trim().isEmpty())
			return true;
		try {
			org.json.JSONObject peta = new org.json.JSONObject(jenjangAngsuranJson).optJSONObject(key + "_smt");
			if (peta == null)
				return true;
			String daftar = jenjang == null || jenjang.getId() == null ? null
					: peta.optString(String.valueOf(jenjang.getId()), null);
			if (daftar == null || daftar.trim().isEmpty())
				return true;

			java.util.List<Integer> smtGlobal = new java.util.ArrayList<Integer>();
			java.util.Map<Integer, java.util.List<Integer>> smtPerAngkatan =
					new java.util.HashMap<Integer, java.util.List<Integer>>();
			Integer cakupan = null; // null = global; selain itu = tahun angkatan aktif
			for (String token : daftar.split(",")) {
				String t = token.trim();
				if (t.isEmpty())
					continue;
				int posTitikDua = t.indexOf(':');
				if (posTitikDua >= 0) {
					String tahunStr = t.substring(0, posTitikDua).trim();
					String smtStr = t.substring(posTitikDua + 1).trim();
					try {
						cakupan = Integer.valueOf(tahunStr);
					} catch (Exception exTahun) {
						ais.common.ErrorAuditUtil.record(exTahun,
								"semesterCocokUntukJenjang: tahun angkatan tidak valid '" + tahunStr
										+ "' pada jenis kegiatan id=" + getId());
						cakupan = null;
						continue;
					}
					if (!smtPerAngkatan.containsKey(cakupan))
						smtPerAngkatan.put(cakupan, new java.util.ArrayList<Integer>());
					if (!smtStr.isEmpty()) {
						try {
							smtPerAngkatan.get(cakupan).add(Integer.valueOf(smtStr));
						} catch (Exception exSmt) {
							ais.common.ErrorAuditUtil.record(exSmt,
									"semesterCocokUntukJenjang: isian smt tidak valid '" + smtStr
											+ "' pada jenis kegiatan id=" + getId());
						}
					}
				} else {
					Integer nilai;
					try {
						nilai = Integer.valueOf(t);
					} catch (Exception exNum) {
						ais.common.ErrorAuditUtil.record(exNum, "semesterCocokUntukJenjang: isian smt tidak valid '"
								+ t + "' pada jenis kegiatan id=" + getId());
						continue;
					}
					if (cakupan == null)
						smtGlobal.add(nilai);
					else
						smtPerAngkatan.get(cakupan).add(nilai);
				}
			}

			if (angkatan != null && smtPerAngkatan.containsKey(angkatan)) {
				java.util.List<Integer> daftarSmt = smtPerAngkatan.get(angkatan);
				return daftarSmt.isEmpty() || daftarSmt.contains(semester);
			}
			if (!smtGlobal.isEmpty())
				return smtGlobal.contains(semester);
			if (!smtPerAngkatan.isEmpty())
				return angkatan == null; // tanpa konteks angkatan → toleran (perilaku lama)
			return false; // isian ada namun tak satu pun token valid
		} catch (Exception e) {
			ais.common.ErrorAuditUtil.record(e, "semesterCocokUntukJenjang gagal; jk id=" + getId());
			return true; // toleran: gagal parse → jangan mengubah perilaku lama
		}
	}

	/**
	 * Varian ber-SEMESTER dari {@link #modeAngsuranUntukJenjang(Jenjang)} — jawaban atas
	 * kenyataan bahwa konfigurasi billing dibuat per semester (contoh: S2 smt 1-3 ditagih
	 * bulanan, smt 4 sekali tagih). Aturan per-jenjang hanya dianggap MENGENAI mahasiswa
	 * bila jenjangnya masuk array kunci DAN semester berjalan masuk daftar "Berlaku di
	 * smt" kunci tersebut (kosong = semua semester). Semester di luar daftar menghasilkan
	 * {@code null} (tidak ada aturan) sehingga logika hilir jatuh ke penghitungan nyata
	 * dari database — bukan dipaksa angsuran atau dipaksa reguler.
	 *
	 * @param jenjang  jenjang mahasiswa/calon; {@code null} diperlakukan seperti versi lama
	 * @param semester semester berjalan; {@code null} = tanpa konteks semester (perilaku
	 *                 identik versi satu-argumen)
	 * @return {@link Boolean#TRUE} harus angsuran, {@link Boolean#FALSE} bukan angsuran,
	 *         {@code null} tidak ada aturan untuk kombinasi jenjang+semester ini
	 */
	public Boolean modeAngsuranUntukJenjang(Jenjang jenjang, Integer semester) {
		return modeAngsuranUntukJenjang(jenjang, semester, null);
	}

	/**
	 * Varian ber-SEMESTER dan ber-TAHUN-ANGKATAN — mendukung isian "Berlaku di smt"
	 * berformat campuran {@code 1,2,3} (global) dan {@code 2023:1,2,8,2024:1} (khusus
	 * angkatan; lihat {@link #semesterCocokUntukJenjang}). Aturan per-jenjang hanya
	 * dianggap mengenai mahasiswa bila jenjangnya masuk array kunci DAN kombinasi
	 * semester+angkatan-nya lolos daftar "Berlaku di smt". Kombinasi di luar daftar
	 * menghasilkan {@code null} (tidak ada aturan) sehingga logika hilir jatuh ke
	 * penghitungan nyata dari database.
	 *
	 * @param jenjang  jenjang mahasiswa/calon
	 * @param semester semester berjalan; {@code null} = tanpa konteks semester
	 * @param angkatan tahun angkatan mahasiswa/calon; {@code null} = tanpa konteks
	 *                 angkatan (entri ber-angkatan diabaikan)
	 * @return TRUE harus angsuran, FALSE bukan angsuran, {@code null} tidak ada aturan
	 */
	public Boolean modeAngsuranUntukJenjang(Jenjang jenjang, Integer semester, Integer angkatan) {
		boolean harus = getHanyaBerupaAngsuran();
		boolean bukan = getHanyaBerupaBukanAngsuran();

		String jkLabel = "[JK id=" + getId() + " nama=" + getNama() + "]";
		String jjLabel = "[Jenjang id=" + (jenjang != null ? jenjang.getId() : "null")
				+ " nama=" + (jenjang != null ? jenjang.getNama() : "null") + "]";
		String jsonLabel = "[json=" + getJenjangAngsuranJson() + "]";

		if (!harus && !bukan) {
			if (DEBUG_MODE_ANGSURAN) System.out.println("[DEBUG-ANGSURAN] " + jkLabel + " " + jjLabel
					+ " harus=false bukan=false → null (tidak ada aturan angsuran)");
			return null;
		}

		Boolean hasil;
		String branch;

		boolean kenaBukan = jenjangDalamArray("bukan", jenjang)
				&& semesterCocokUntukJenjang("bukan", jenjang, semester, angkatan);
		boolean kenaHarus = jenjangDalamArray("harus", jenjang)
				&& semesterCocokUntukJenjang("harus", jenjang, semester, angkatan);

		if (harus && bukan) {
			// BRANCH 1: kedua flag aktif → "bukan" override "harus"
			branch = "BRANCH-1(harus&&bukan)";
			if (bukan && kenaBukan) {
				hasil = Boolean.FALSE;
			} else if (kenaHarus) {
				hasil = Boolean.TRUE;
			} else {
				hasil = null;
			}
		} else if (harus) {
			// BRANCH 2: hanya harus aktif
			branch = "BRANCH-2(hanyaHarus)";
			hasil = kenaHarus ? Boolean.TRUE : null;
		} else {
			// BRANCH 3: hanya bukan aktif
			branch = "BRANCH-3(hanyaBukan)";
			hasil = kenaBukan ? Boolean.FALSE : null;
		}

		if (DEBUG_MODE_ANGSURAN) System.out.println("[DEBUG-ANGSURAN] " + jkLabel + " " + jjLabel
				+ " harus=" + harus + " bukan=" + bukan + " " + jsonLabel
				+ " → " + branch + " → hasil=" + hasil);
		return hasil;
	}

	public Boolean getAbaikanNilaiMinus() {
		return abaikanNilaiMinus == null ? false : abaikanNilaiMinus;
	}

	public void setAbaikanNilaiMinus(Boolean abaikanNilaiMinus) {
		this.abaikanNilaiMinus = abaikanNilaiMinus;
	}

	public Boolean getDendaDibuatPerProdi() {
		if (!getDendaJikaTerlambat()) {
			dendaDibuatPerProdi = false;
		}
		return dendaDibuatPerProdi == null ? false : dendaDibuatPerProdi;
	}

	public void setDendaDibuatPerProdi(Boolean dendaDibuatPerProdi) {
		this.dendaDibuatPerProdi = dendaDibuatPerProdi;
	}

	@Column(columnDefinition = "text")
	public String getDendaPerProdi() {
		return dendaPerProdi == null || dendaPerProdi.trim().isEmpty() ? new JSONObject().toString() : dendaPerProdi;
	}

	public void setDendaPerProdi(String dendaPerProdi) {
		this.dendaPerProdi = dendaPerProdi;
	}

	public String getPrefixKodePembayaran() {
		return prefixKodePembayaran == null || prefixKodePembayaran.trim().isEmpty() ? null
				: prefixKodePembayaran.trim();
	}

	public void setPrefixKodePembayaran(String prefixKodePembayaran) {
		this.prefixKodePembayaran = prefixKodePembayaran;
	}

	@Column(columnDefinition = "text")
	public String getNamaBankPembayaran() {
		if (namaBankPembayaran == null) {
			namaBankPembayaran = "";
		}

		namaBankPembayaran = (namaBankPembayaran == null || namaBankPembayaran.trim().equalsIgnoreCase(";") ? ""
				: ";" + namaBankPembayaran.trim() + ";").replaceAll(";;", ";").replaceAll(";;", ";")
				.replaceAll(";;", ";");

		if (namaBankPembayaran.equals(";")) {
			namaBankPembayaran = "";
		} else if (namaBankPembayaran.equals(";;")) {
			namaBankPembayaran = "";
		} else if (namaBankPembayaran.equals(";;;")) {
			namaBankPembayaran = "";
		} else if (namaBankPembayaran.equals(";;;;")) {
			namaBankPembayaran = "";
		}

		return namaBankPembayaran == null ? "" : namaBankPembayaran.trim();
	}

	public void setNamaBankPembayaran(String namaBankPembayaran) {
		this.namaBankPembayaran = namaBankPembayaran;
	}

}