package ais.database.model;

// Generated Apr 16, 2010 2:27:16 PM by Hibernate Tools 3.2.4.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;
import org.hibernate.envers.Audited;

/**
 * Bank generated by hbm2java
 *
 * <p><b>Master aturan ambang beban kerja dosen (BKD)</b> &mdash; satu baris tabel
 * {@code public.kewajiban_beban_dosen} mewakili satu paket aturan ambang SKS minimal/maksimal
 * yang harus dipenuhi seorang dosen pada empat unsur Tridarma (pendidikan, penelitian,
 * pengabdian, penunjang), dilekatkan pada satu {@link #getStatusKewajibanBebanDosen() status
 * pemenuhan} tertentu (mis. "Memenuhi"/"Tidak Memenuhi").</p>
 *
 * <h2>Empat unsur beban &amp; ambang SKS per unsur (diverifikasi dari kode)</h2>
 * <p>Kelas ini menyimpan dua lapis informasi terkait empat unsur Tridarma:</p>
 * <ul>
 *   <li><b>Penanda unsur mana yang berlaku</b>: {@link #getPendidikan()},
 *       {@link #getPenelitian()}, {@link #getPengabdian()}, {@link #getPenunjang()} &mdash;
 *       masing-masing {@link Boolean}, default {@code false} bila belum diisi.</li>
 *   <li><b>Ambang SKS minimal per unsur</b>: {@link #getMinimalSksPendidikan()},
 *       {@link #getMinimalSksPenelitian()}, {@link #getMinimalSksPengabdian()},
 *       {@link #getMinimalSksPenunjang()} &mdash; masing-masing {@link Double}, default
 *       {@code 0.0} bila belum diisi.</li>
 * </ul>
 * <p>{@link #getMinimalSks()} <b>dan</b> {@link #getMaksimalSks()} adalah ambang total
 * keseluruhan (SKS minimal/maksimal gabungan seluruh unsur), <b>bukan</b> hasil penjumlahan
 * otomatis dari keempat {@code minimalSksXxx} di atas: baris perhitungan penjumlahan pada
 * {@link #getMinimalSks()} sudah dikomentari ({@code //}) di kode sumber, sehingga
 * {@code minimalSks} hanya mengembalikan nilai yang tersimpan langsung (atau {@code 0.0}) tanpa
 * pernah menjumlahkan ulang keempat komponen unsur secara otomatis &mdash; keduanya harus diisi
 * manual secara terpisah oleh pemakai/pengelola data.</p>
 *
 * <h2>Peta anggota</h2>
 * <ul>
 *   <li><b>Identitas &amp; audit</b>: {@link #getId()}/{@link #setId(Long)},
 *       {@link #getOleh()}/{@link #setOleh(String)}, {@link #getOlehId()}/{@link #setOlehId(String)},
 *       {@link #getTanggal_dirubah()}/{@link #setTanggal_dirubah(Date)}, {@link #onUpdate()}.</li>
 *   <li><b>Deskriptif</b>: {@link #getKeterangan()}/{@link #setKeterangan(String)} (dipakai
 *       {@link #toString()} bersama {@link #getStatusKewajibanBebanDosen()}).</li>
 *   <li><b>Status &amp; relasi</b>: {@link #getAktif()}/{@link #setAktif(Boolean)} (default
 *       {@code true} bila belum pernah diisi, sekaligus disimpan ke field pada pemanggilan
 *       pertama), {@link #getStatusKewajibanBebanDosen()}/
 *       {@link #setStatusKewajibanBebanDosen(StatusKewajibanBebanDosen)}.</li>
 *   <li><b>Ambang total</b>: {@link #getMinimalSks()}/{@link #setMinimalSks(Double)} (lihat
 *       catatan penjumlahan yang dinonaktifkan di atas), {@link #getMaksimalSks()}/
 *       {@link #setMaksimalSks(Double)}.</li>
 *   <li><b>Penanda &amp; ambang per unsur Tridarma</b>: {@link #getPendidikan()}/
 *       {@link #setPendidikan(Boolean)}, {@link #getPenelitian()}/{@link #setPenelitian(Boolean)},
 *       {@link #getPengabdian()}/{@link #setPengabdian(Boolean)}, {@link #getPenunjang()}/
 *       {@link #setPenunjang(Boolean)}, {@link #getMinimalSksPendidikan()}/
 *       {@link #setMinimalSksPendidikan(Double)}, {@link #getMinimalSksPenelitian()}/
 *       {@link #setMinimalSksPenelitian(Double)}, {@link #getMinimalSksPengabdian()}/
 *       {@link #setMinimalSksPengabdian(Double)}, {@link #getMinimalSksPenunjang()}/
 *       {@link #setMinimalSksPenunjang(Double)}.</li>
 * </ul>
 *
 * @see StatusKewajibanBebanDosen
 * @see GeneralValueObject
 */
@Entity
@org.hibernate.annotations.Entity(
    dynamicInsert = true,
    dynamicUpdate = true
)
@Audited
@Table(schema = "public", name = "kewajiban_beban_dosen")

public class KewajibanBebanDosen extends GeneralValueObject {

	/**
	 * Penanda versi serialisasi Java. Tidak berdampak fungsional.
	 */
	private static final long serialVersionUID = 2463821577548439808L;

	/** Kunci utama, lihat {@link #getId()}. */
	private Long id;

	/** Nama pengguna pengubah terakhir, lihat {@link #getOleh()}. */
	private String oleh;

	/** Id pengguna pengubah terakhir, lihat {@link #getOlehId()}. */
	private String olehId;

	/**
	 * Id pengguna pengubah terakhir.
	 *
	 * @return id pengguna pengubah terakhir; {@code null} bila belum pernah tercatat.
	 */
	public String getOlehId() {
		return olehId;
	}

	/**
	 * Menetapkan id pengguna pengubah terakhir. Setter penjaga: nilai {@code null}/kosong diabaikan
	 * diam-diam sehingga jejak audit yang sudah terisi tidak dapat dihapus lewat setter ini.
	 *
	 * @param olehId id pengguna; diabaikan bila {@code null} atau kosong.
	 */
	public void setOlehId(String olehId) {if (olehId == null || olehId.trim().isEmpty()) {return;}
		this.olehId = olehId;
	}

	/**
	 * Menetapkan nama pengguna pengubah terakhir. Berperilaku sama dengan
	 * {@link #setOlehId(String)}: nilai {@code null}/kosong diabaikan diam-diam.
	 *
	 * @param oleh nama pengguna; diabaikan bila {@code null} atau kosong.
	 */
	public void setOleh(String oleh) {if (oleh == null || oleh.trim().isEmpty()) {return;}
		this.oleh = oleh;
	}

	/**
	 * Nama pengguna yang terakhir mengubah baris ini.
	 *
	 * @return nama pengguna pengubah terakhir; {@code null} bila belum pernah tercatat.
	 */
	public String getOleh() {
		return oleh;
	}

	/**
	 * Hook JPA {@code @PreUpdate} yang menyegarkan metadata audit sebelum baris ini di-{@code UPDATE},
	 * plus deklarasi field {@code tanggal_dirubah} yang menempel pada baris kode yang sama. Mendelegasikan
	 * ke {@code ais.database.hibernate.AuditTimestampInterceptor.ubah(this)}; dipanggil Hibernate saja.
	 */
	@javax.persistence.PreUpdate protected void onUpdate() { ais.database.hibernate.AuditTimestampInterceptor.ubah(this);}     private Date tanggal_dirubah = ais.ui.util.WaktuUtil.getDate();

	/**
	 * Menetapkan stempel waktu perubahan terakhir. Tidak menjaga terhadap {@code null}.
	 *
	 * @param tanggal_dirubah waktu perubahan terakhir; boleh {@code null}.
	 */
	public void setTanggal_dirubah(Date tanggal_dirubah) {
		this.tanggal_dirubah = tanggal_dirubah;
	}

	/**
	 * Waktu terakhir baris ini diubah.
	 *
	 * @return waktu perubahan terakhir, dipetakan sebagai {@code TIMESTAMP}.
	 */
	@Temporal(TemporalType.TIMESTAMP)
	public Date getTanggal_dirubah() {
		return tanggal_dirubah;
	}

	/**
	 * Representasi teks baris ini: id, status pemenuhan, dan keterangan digabung.
	 *
	 * @return string {@code "<id>-<statusKewajibanBebanDosen>-<keterangan>"}.
	 */
	public String toString() {
		return id + "-" + statusKewajibanBebanDosen + "-" + keterangan;
	}

	/** Keterangan bebas, lihat {@link #getKeterangan()}. */
	private String keterangan;

	/** Status aktif/nonaktif baris, lihat {@link #getAktif()}. */
	private Boolean aktif;

	/** Status pemenuhan kewajiban beban dosen yang dilekatkan pada aturan ini, lihat {@link #getStatusKewajibanBebanDosen()}. */
	private StatusKewajibanBebanDosen statusKewajibanBebanDosen;

	/** Ambang SKS minimal total (bukan penjumlahan otomatis unsur), lihat {@link #getMinimalSks()}. */
	private Double minimalSks = 0.0;

	/** Ambang SKS maksimal total, lihat {@link #getMaksimalSks()}. */
	private Double maksimalSks = 0.0;

	/** Penanda unsur pendidikan berlaku, lihat {@link #getPendidikan()}. */
	private Boolean pendidikan;

	/** Penanda unsur penelitian berlaku, lihat {@link #getPenelitian()}. */
	private Boolean penelitian;

	/** Penanda unsur pengabdian berlaku, lihat {@link #getPengabdian()}. */
	private Boolean pengabdian;

	/** Penanda unsur penunjang berlaku, lihat {@link #getPenunjang()}. */
	private Boolean penunjang;

	/** Ambang SKS minimal unsur pendidikan, lihat {@link #getMinimalSksPendidikan()}. */
	private Double minimalSksPendidikan = 0.0;

	/** Ambang SKS minimal unsur penelitian, lihat {@link #getMinimalSksPenelitian()}. */
	private Double minimalSksPenelitian = 0.0;

	/** Ambang SKS minimal unsur pengabdian, lihat {@link #getMinimalSksPengabdian()}. */
	private Double minimalSksPengabdian = 0.0;

	/** Ambang SKS minimal unsur penunjang, lihat {@link #getMinimalSksPenunjang()}. */
	private Double minimalSksPenunjang = 0.0;

	/** Konstruktor tanpa argumen yang dibutuhkan Hibernate/JPA. */
	public KewajibanBebanDosen() {
	}

	/**
	 * Konstruktor kenyamanan untuk merujuk baris berdasarkan id yang sudah diketahui.
	 *
	 * @param id id baris yang dirujuk.
	 */
	public KewajibanBebanDosen(Long id) {
		this.id = id;
	}

	/**
	 * Kunci utama baris (kolom {@code id}, {@code IDENTITY} &mdash; dibangkitkan database).
	 *
	 * @return id baris; {@code null} selama object belum pernah disimpan.
	 */
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", insertable = false, unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	/**
	 * Menetapkan kunci utama. Praktis hanya dipanggil Hibernate.
	 *
	 * @param id kunci utama baris.
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * Keterangan bebas (kolom {@code keterangan}, {@code nullable}).
	 *
	 * @return keterangan; {@code null} bila belum diisi.
	 */
	@Column(name = "keterangan", nullable = true)
	public String getKeterangan() {
		return this.keterangan;
	}

	/**
	 * Menetapkan keterangan bebas.
	 *
	 * @param keterangan teks keterangan; boleh {@code null}.
	 */
	public void setKeterangan(String keterangan) {
		this.keterangan = keterangan;
	}

	/**
	 * Status aktif/nonaktif baris ini pada layar pemilihan.
	 *
	 * @return {@code true} bila aktif atau belum pernah diisi; berbeda dari kebanyakan master
	 *         lain di paket ini, nilai default {@code true} di sini juga <b>ditugaskan kembali
	 *         ke field {@code aktif}</b> pada pemanggilan pertama, bukan hanya dikembalikan.
	 */
	public Boolean getAktif() {
		if (aktif == null) {
			aktif = true;
		}
		return aktif;
	}

	/**
	 * Menetapkan status aktif/nonaktif.
	 *
	 * @param aktif status aktif baru; boleh {@code null} (akan dinormalisasi menjadi {@code true}
	 *              oleh pemanggilan {@link #getAktif()} berikutnya).
	 */
	public void setAktif(Boolean aktif) {
		this.aktif = aktif;
	}

	/**
	 * Status pemenuhan kewajiban beban dosen (kolom {@code status_kewajiban_beban_dosen},
	 * {@code ManyToOne}, {@code FetchMode.SELECT}). Getter murni tanpa efek samping (berbeda
	 * dari beberapa relasi lazy lain di paket ini yang memakai {@code check(...)}).
	 *
	 * @return status pemenuhan; {@code null} bila belum diisi.
	 */
	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE })
	@Fetch(FetchMode.SELECT)
	@JoinColumn(name = "status_kewajiban_beban_dosen", nullable = true)
	public StatusKewajibanBebanDosen getStatusKewajibanBebanDosen() {
		return statusKewajibanBebanDosen;
	}

	/**
	 * Menetapkan status pemenuhan kewajiban beban dosen.
	 *
	 * @param statusKewajibanBebanDosen status pemenuhan; boleh {@code null}.
	 */
	public void setStatusKewajibanBebanDosen(StatusKewajibanBebanDosen statusKewajibanBebanDosen) {
		this.statusKewajibanBebanDosen = statusKewajibanBebanDosen;
	}

	/**
	 * Ambang SKS minimal total (gabungan seluruh unsur Tridarma). <b>Bukan</b> hasil penjumlahan
	 * otomatis dari {@link #getMinimalSksPendidikan()}/{@link #getMinimalSksPenelitian()}/
	 * {@link #getMinimalSksPengabdian()}/{@link #getMinimalSksPenunjang()}: baris perhitungan
	 * penjumlahan tersebut sudah dikomentari di kode sumber, sehingga nilai ini harus diisi
	 * manual secara terpisah dan dapat tidak sinkron dengan jumlah ambang per unsur.
	 *
	 * @return ambang SKS minimal total; {@code 0.0} bila belum pernah diisi.
	 */
	public Double getMinimalSks() {
//		minimalSks = getMinimalSksPendidikan() + getMinimalSksPenelitian() + getMinimalSksPengabdian()
//				+ getMinimalSksPenunjang();
		return minimalSks == null ? 0.0 : minimalSks;
	}

	/**
	 * Menetapkan ambang SKS minimal total.
	 *
	 * @param minimalSks ambang SKS minimal; boleh {@code null} (dinormalisasi menjadi 0.0 oleh
	 *                   {@link #getMinimalSks()}).
	 */
	public void setMinimalSks(Double minimalSks) {
		this.minimalSks = minimalSks;
	}

	/**
	 * Ambang SKS maksimal total (gabungan seluruh unsur Tridarma).
	 *
	 * @return ambang SKS maksimal total; {@code 0.0} bila belum pernah diisi.
	 */
	public Double getMaksimalSks() {
		return maksimalSks == null ? 0.0 : maksimalSks;
	}

	/**
	 * Menetapkan ambang SKS maksimal total.
	 *
	 * @param maksimalSks ambang SKS maksimal; boleh {@code null} (dinormalisasi menjadi 0.0 oleh
	 *                    {@link #getMaksimalSks()}).
	 */
	public void setMaksimalSks(Double maksimalSks) {
		this.maksimalSks = maksimalSks;
	}

	/**
	 * Penanda apakah unsur pendidikan termasuk dalam aturan ambang beban ini.
	 *
	 * @return {@code true} bila berlaku; {@code false} bila belum pernah diisi.
	 */
	public Boolean getPendidikan() {
		return pendidikan == null ? false : pendidikan;
	}

	/**
	 * Menetapkan penanda unsur pendidikan.
	 *
	 * @param pendidikan penanda unsur pendidikan; boleh {@code null}.
	 */
	public void setPendidikan(Boolean pendidikan) {
		this.pendidikan = pendidikan;
	}

	/**
	 * Penanda apakah unsur penelitian termasuk dalam aturan ambang beban ini.
	 *
	 * @return {@code true} bila berlaku; {@code false} bila belum pernah diisi.
	 */
	public Boolean getPenelitian() {
		return penelitian == null ? false : penelitian;
	}

	/**
	 * Menetapkan penanda unsur penelitian.
	 *
	 * @param penelitian penanda unsur penelitian; boleh {@code null}.
	 */
	public void setPenelitian(Boolean penelitian) {
		this.penelitian = penelitian;
	}

	/**
	 * Penanda apakah unsur pengabdian termasuk dalam aturan ambang beban ini.
	 *
	 * @return {@code true} bila berlaku; {@code false} bila belum pernah diisi.
	 */
	public Boolean getPengabdian() {
		return pengabdian == null ? false : pengabdian;
	}

	/**
	 * Menetapkan penanda unsur pengabdian.
	 *
	 * @param pengabdian penanda unsur pengabdian; boleh {@code null}.
	 */
	public void setPengabdian(Boolean pengabdian) {
		this.pengabdian = pengabdian;
	}

	/**
	 * Penanda apakah unsur penunjang termasuk dalam aturan ambang beban ini.
	 *
	 * @return {@code true} bila berlaku; {@code false} bila belum pernah diisi.
	 */
	public Boolean getPenunjang() {
		return penunjang == null ? false : penunjang;
	}

	/**
	 * Menetapkan penanda unsur penunjang.
	 *
	 * @param penunjang penanda unsur penunjang; boleh {@code null}.
	 */
	public void setPenunjang(Boolean penunjang) {
		this.penunjang = penunjang;
	}

	/**
	 * Ambang SKS minimal khusus unsur pendidikan.
	 *
	 * @return ambang SKS minimal pendidikan; {@code 0.0} bila belum pernah diisi.
	 */
	public Double getMinimalSksPendidikan() {
		return minimalSksPendidikan == null ? 0.0 : minimalSksPendidikan;
	}

	/**
	 * Menetapkan ambang SKS minimal unsur pendidikan.
	 *
	 * @param minimalSksPendidikan ambang SKS minimal pendidikan; boleh {@code null}.
	 */
	public void setMinimalSksPendidikan(Double minimalSksPendidikan) {
		this.minimalSksPendidikan = minimalSksPendidikan;
	}

	/**
	 * Ambang SKS minimal khusus unsur penelitian.
	 *
	 * @return ambang SKS minimal penelitian; {@code 0.0} bila belum pernah diisi.
	 */
	public Double getMinimalSksPenelitian() {
		return minimalSksPenelitian == null ? 0.0 : minimalSksPenelitian;
	}

	/**
	 * Menetapkan ambang SKS minimal unsur penelitian.
	 *
	 * @param minimalSksPenelitian ambang SKS minimal penelitian; boleh {@code null}.
	 */
	public void setMinimalSksPenelitian(Double minimalSksPenelitian) {
		this.minimalSksPenelitian = minimalSksPenelitian;
	}

	/**
	 * Ambang SKS minimal khusus unsur penunjang.
	 *
	 * @return ambang SKS minimal penunjang; {@code 0.0} bila belum pernah diisi.
	 */
	public Double getMinimalSksPenunjang() {
		return minimalSksPenunjang == null ? 0.0 : minimalSksPenunjang;
	}

	/**
	 * Menetapkan ambang SKS minimal unsur penunjang.
	 *
	 * @param minimalSksPenunjang ambang SKS minimal penunjang; boleh {@code null}.
	 */
	public void setMinimalSksPenunjang(Double minimalSksPenunjang) {
		this.minimalSksPenunjang = minimalSksPenunjang;
	}

	/**
	 * Ambang SKS minimal khusus unsur pengabdian.
	 *
	 * @return ambang SKS minimal pengabdian; {@code 0.0} bila belum pernah diisi.
	 */
	public Double getMinimalSksPengabdian() {
		return minimalSksPengabdian == null ? 0.0 : minimalSksPengabdian;
	}

	/**
	 * Menetapkan ambang SKS minimal unsur pengabdian.
	 *
	 * @param minimalSksPengabdian ambang SKS minimal pengabdian; boleh {@code null}.
	 */
	public void setMinimalSksPengabdian(Double minimalSksPengabdian) {
		this.minimalSksPengabdian = minimalSksPengabdian;
	}

}
