package ais.database.model;

// Generated Apr 16, 2010 2:27:16 PM by Hibernate Tools 3.2.4.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;
import org.hibernate.envers.Audited;

/**
 * Bank generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Entity(
    dynamicInsert = true,
    dynamicUpdate = true
)
@Audited
@Table(schema = "public", name = "kewajiban_beban_dosen")

public class KewajibanBebanDosen extends GeneralValueObject {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2463821577548439808L;
	private Long id;
	private String oleh;
	private String olehId;

	public String getOlehId() {
		return olehId;
	}

	public void setOlehId(String olehId) {if (olehId == null || olehId.trim().isEmpty()) {return;}
		this.olehId = olehId;
	}

	public void setOleh(String oleh) {if (oleh == null || oleh.trim().isEmpty()) {return;}
		this.oleh = oleh;
	}

	public String getOleh() {
		return oleh;
	}

	@javax.persistence.PreUpdate protected void onUpdate() { ais.database.hibernate.AuditTimestampInterceptor.ubah(this);}     private Date tanggal_dirubah = ais.ui.util.WaktuUtil.getDate();

	public void setTanggal_dirubah(Date tanggal_dirubah) {
		this.tanggal_dirubah = tanggal_dirubah;
	}

	@Temporal(TemporalType.TIMESTAMP)
	public Date getTanggal_dirubah() {
		return tanggal_dirubah;
	}

	public String toString() {
		return id + "-" + statusKewajibanBebanDosen + "-" + keterangan;
	}

	private String keterangan;
	private Boolean aktif;
	private StatusKewajibanBebanDosen statusKewajibanBebanDosen;
	private Double minimalSks = 0.0;
	private Double maksimalSks = 0.0;
	private Boolean pendidikan;
	private Boolean penelitian;
	private Boolean pengabdian;
	private Boolean penunjang;

	private Double minimalSksPendidikan = 0.0;
	private Double minimalSksPenelitian = 0.0;
	private Double minimalSksPengabdian = 0.0;
	private Double minimalSksPenunjang = 0.0;

	public KewajibanBebanDosen() {
	}

	public KewajibanBebanDosen(Long id) {
		this.id = id;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", insertable = false, unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "keterangan", nullable = true)
	public String getKeterangan() {
		return this.keterangan;
	}

	public void setKeterangan(String keterangan) {
		this.keterangan = keterangan;
	}

	public Boolean getAktif() {
		if (aktif == null) {
			aktif = true;
		}
		return aktif;
	}

	public void setAktif(Boolean aktif) {
		this.aktif = aktif;
	}

	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE })
	@Fetch(FetchMode.SELECT)
	@JoinColumn(name = "status_kewajiban_beban_dosen", nullable = true)
	public StatusKewajibanBebanDosen getStatusKewajibanBebanDosen() {
		return statusKewajibanBebanDosen;
	}

	public void setStatusKewajibanBebanDosen(StatusKewajibanBebanDosen statusKewajibanBebanDosen) {
		this.statusKewajibanBebanDosen = statusKewajibanBebanDosen;
	}

	public Double getMinimalSks() {
//		minimalSks = getMinimalSksPendidikan() + getMinimalSksPenelitian() + getMinimalSksPengabdian()
//				+ getMinimalSksPenunjang();
		return minimalSks == null ? 0.0 : minimalSks;
	}

	public void setMinimalSks(Double minimalSks) {
		this.minimalSks = minimalSks;
	}

	public Double getMaksimalSks() {
		return maksimalSks == null ? 0.0 : maksimalSks;
	}

	public void setMaksimalSks(Double maksimalSks) {
		this.maksimalSks = maksimalSks;
	}

	public Boolean getPendidikan() {
		return pendidikan == null ? false : pendidikan;
	}

	public void setPendidikan(Boolean pendidikan) {
		this.pendidikan = pendidikan;
	}

	public Boolean getPenelitian() {
		return penelitian == null ? false : penelitian;
	}

	public void setPenelitian(Boolean penelitian) {
		this.penelitian = penelitian;
	}

	public Boolean getPengabdian() {
		return pengabdian == null ? false : pengabdian;
	}

	public void setPengabdian(Boolean pengabdian) {
		this.pengabdian = pengabdian;
	}

	public Boolean getPenunjang() {
		return penunjang == null ? false : penunjang;
	}

	public void setPenunjang(Boolean penunjang) {
		this.penunjang = penunjang;
	}

	public Double getMinimalSksPendidikan() {
		return minimalSksPendidikan == null ? 0.0 : minimalSksPendidikan;
	}

	public void setMinimalSksPendidikan(Double minimalSksPendidikan) {
		this.minimalSksPendidikan = minimalSksPendidikan;
	}

	public Double getMinimalSksPenelitian() {
		return minimalSksPenelitian == null ? 0.0 : minimalSksPenelitian;
	}

	public void setMinimalSksPenelitian(Double minimalSksPenelitian) {
		this.minimalSksPenelitian = minimalSksPenelitian;
	}

	public Double getMinimalSksPenunjang() {
		return minimalSksPenunjang == null ? 0.0 : minimalSksPenunjang;
	}

	public void setMinimalSksPenunjang(Double minimalSksPenunjang) {
		this.minimalSksPenunjang = minimalSksPenunjang;
	}

	public Double getMinimalSksPengabdian() {
		return minimalSksPengabdian == null ? 0.0 : minimalSksPengabdian;
	}

	public void setMinimalSksPengabdian(Double minimalSksPengabdian) {
		this.minimalSksPengabdian = minimalSksPengabdian;
	}

}
