package ais.database.model;

// Generated Apr 16, 2010 2:27:16 PM by Hibernate Tools 3.2.4.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.envers.Audited;

import ais.common.Common;
import ais.ui.util.WaktuUtil;

/**
 * Entity Hibernate untuk tabel {@code public.konfigurasi_kalender_akademik} &mdash; baris yang
 * mengaitkan satu {@link KalenderAkademik} (sesi/rentang tanggal kalender akademik) dengan satu
 * {@link Konfigurasi} (flag/nilai konfigurasi global) agar nilai {@link Konfigurasi} tersebut
 * OTOMATIS berubah tergantung apakah tanggal sekarang berada di dalam atau di luar rentang
 * {@link KalenderAkademik#getTanggalMulai()}..{@link KalenderAkademik#getTanggalSelesai()}. Lihat
 * {@link #getKonfigurasi()} untuk mekanisme lengkapnya.
 *
 * <p><b>Relasi dengan {@link KalenderAkademik}:</b> hanya membaca
 * {@link KalenderAkademik#getTanggalMulai()}, {@link KalenderAkademik#getTanggalSelesai()},
 * {@link KalenderAkademik#getTahunAjaran()}, dan {@link KalenderAkademik#getGanjilGenap()}; TIDAK
 * pernah memanggil {@link KalenderAkademik#getHari()} sehingga TIDAK terpapar bug
 * {@code ArrayIndexOutOfBoundsException} yang terdokumentasi pada method tersebut (indeks
 * {@code Calendar.WEEK_OF_MONTH} yang keliru, lihat Javadoc {@link KalenderAkademik#getHari()}).
 *
 * <p>Javadoc class ini sebelumnya adalah stub salah-tempel ("Bank generated by hbm2java")
 * peninggalan generator hbm2java untuk entity lain; sudah dikoreksi di sini tanpa mengubah
 * perilaku.
 *
 * @see KalenderAkademik
 * @see Konfigurasi
 */
@Entity
@org.hibernate.annotations.Entity(dynamicInsert = true, dynamicUpdate = true)
@Audited
@Table(schema = "public", name = "konfigurasi_kalender_akademik")
public class KonfigurasiKalenderAkademik extends GeneralValueObject {

	/**
	 *
	 */
	private static final long serialVersionUID = 2463821577548439808L;
	private Long id;
	/** Nama pelaku (audit shadow, lihat {@link GeneralValueObject}) yang membuat/mengubah baris ini. */
	private String oleh;
	/** Id pelaku (audit shadow) yang membuat/mengubah baris ini. */
	private String olehId;

	/** @return id pelaku terakhir yang mengubah baris ini, atau {@code null} bila belum pernah diisi. */
	public String getOlehId() {
		return olehId;
	}

	/**
	 * Mengisi id pelaku. Nilai kosong/blank diabaikan (fail-safe agar audit shadow tidak
	 * tertimpa string kosong secara tidak sengaja) &mdash; bukan validasi keamanan.
	 *
	 * @param olehId id pelaku; diabaikan jika {@code null} atau hanya berisi spasi
	 */
	public void setOlehId(String olehId) {
		if (olehId == null || olehId.trim().isEmpty()) {
			return;
		}
		this.olehId = olehId;
	}

	/**
	 * Mengisi nama pelaku. Nilai kosong/blank diabaikan, sama seperti {@link #setOlehId(String)}.
	 *
	 * @param oleh nama pelaku; diabaikan jika {@code null} atau hanya berisi spasi
	 */
	public void setOleh(String oleh) {
		if (oleh == null || oleh.trim().isEmpty()) {
			return;
		}
		this.oleh = oleh;
	}

	/** @return nama pelaku terakhir yang mengubah baris ini, atau {@code null} bila belum pernah diisi. */
	public String getOleh() {
		return oleh;
	}

	/** Menandai baris berubah; dipanggil otomatis oleh Hibernate sebelum setiap update. */
	@javax.persistence.PreUpdate
	protected void onUpdate() {
		ais.database.hibernate.AuditTimestampInterceptor.ubah(this);
	}

	private Date tanggal_dirubah = ais.ui.util.WaktuUtil.getDate();

	/**
	 * Mengubah stempel waktu perubahan terakhir secara manual. Nilai default sudah di-set ke
	 * waktu saat ini pada deklarasi field dan di-refresh otomatis oleh {@link #onUpdate()} pada
	 * setiap update; setter ini jarang perlu dipanggil langsung.
	 *
	 * @param tanggal_dirubah stempel waktu perubahan baru
	 */
	public void setTanggal_dirubah(Date tanggal_dirubah) {
		this.tanggal_dirubah = tanggal_dirubah;
	}

	/** @return stempel waktu perubahan terakhir baris ini. */
	@Temporal(TemporalType.TIMESTAMP)
	public Date getTanggal_dirubah() {
		return tanggal_dirubah;
	}

	/** @return representasi ringkas berisi nilai konfigurasi dan kedua ambang perubahannya, dipakai untuk debugging/log. */
	public String toString() {
		return "konfigurasi = " + konfigurasi + ", padaSaatMulaiBerubahMenjadi = " + padaSaatMulaiBerubahMenjadi + ", "
				+ padaSaatSelesaiBerubahMenjadi;
	}

	private String keterangan;
	private String padaSaatMulaiBerubahMenjadi = Konfigurasi.AKTIF;
	private String padaSaatSelesaiBerubahMenjadi = Konfigurasi.TIDAK_AKTIF;
	private KalenderAkademik kalenderAkademik;
	private Konfigurasi konfigurasi;

	/** Konstruktor kosong yang diperlukan Hibernate. */
	public KonfigurasiKalenderAkademik() {
	}

	/** @return id baris (primary key, auto-generated identity di database). */
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", insertable = false, unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	/** @param id id baris; kolom tidak insertable sehingga nilai ini diabaikan saat insert. */
	public void setId(Long id) {
		this.id = id;
	}

	/** @return keterangan tambahan untuk baris konfigurasi ini, boleh {@code null}. */
	@Column(name = "keterangan", nullable = true)
	public String getKeterangan() {
		return this.keterangan;
	}

	/** @param keterangan keterangan tambahan untuk baris konfigurasi ini. */
	public void setKeterangan(String keterangan) {
		this.keterangan = keterangan;
	}

	/**
	 * @return nilai yang akan diset ke {@link Konfigurasi#setNilai(String)} ketika tanggal
	 * sekarang berada DI DALAM rentang {@link KalenderAkademik#getTanggalMulai()}..
	 * {@link KalenderAkademik#getTanggalSelesai()}; default {@link Konfigurasi#AKTIF}.
	 */
	public String getPadaSaatMulaiBerubahMenjadi() {
		return padaSaatMulaiBerubahMenjadi;
	}

	/** @param padaSaatMulaiBerubahMenjadi nilai konfigurasi saat tanggal sekarang berada di dalam rentang kalender akademik. */
	public void setPadaSaatMulaiBerubahMenjadi(String padaSaatMulaiBerubahMenjadi) {
		this.padaSaatMulaiBerubahMenjadi = padaSaatMulaiBerubahMenjadi;
	}

	/**
	 * @return nilai yang akan diset ke {@link Konfigurasi#setNilai(String)} ketika tanggal
	 * sekarang berada DI LUAR rentang {@link KalenderAkademik#getTanggalMulai()}..
	 * {@link KalenderAkademik#getTanggalSelesai()}; default {@link Konfigurasi#TIDAK_AKTIF}.
	 */
	public String getPadaSaatSelesaiBerubahMenjadi() {
		return padaSaatSelesaiBerubahMenjadi;
	}

	/** @param padaSaatSelesaiBerubahMenjadi nilai konfigurasi saat tanggal sekarang berada di luar rentang kalender akademik. */
	public void setPadaSaatSelesaiBerubahMenjadi(String padaSaatSelesaiBerubahMenjadi) {
		this.padaSaatSelesaiBerubahMenjadi = padaSaatSelesaiBerubahMenjadi;
	}

	/**
	 * @return {@link KalenderAkademik} yang rentang tanggalnya dipakai sebagai penentu nilai
	 * {@link #getKonfigurasi()}, boleh {@code null}; relasi lazy, dimuat via
	 * {@link GeneralValueObject#check(Object)} saat pertama diakses.
	 */
	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY)
	@JoinColumn(name = "kalender_akademik", nullable = true)
	public KalenderAkademik getKalenderAkademik() {
		kalenderAkademik = check(kalenderAkademik);
		return kalenderAkademik;
	}

	/** @param kalenderAkademik kalender akademik yang rentang tanggalnya dipakai sebagai penentu nilai {@link #getKonfigurasi()}. */
	public void setKalenderAkademik(KalenderAkademik kalenderAkademik) {
		this.kalenderAkademik = kalenderAkademik;
	}

	/**
	 * @return {@link Konfigurasi} yang diatur otomatis oleh baris ini. <b>Getter dengan efek
	 * samping besar (getter destruktif):</b> setiap pemanggilan, bila {@link #getKalenderAkademik()}
	 * dan {@link #getTanggalMulai()}/{@link #getTanggalSelesai()}-nya tersedia, membandingkan
	 * tanggal sekarang terhadap rentang kalender akademik itu dan MENULIS LANGSUNG ke objek
	 * {@link Konfigurasi} yang direlasikan: {@link Konfigurasi#setNilai(String)} diisi
	 * {@link #getPadaSaatMulaiBerubahMenjadi()} bila tanggal sekarang di dalam rentang (inklusif,
	 * dibandingkan per-hari), atau {@link #getPadaSaatSelesaiBerubahMenjadi()} bila di luar;
	 * {@link Konfigurasi#setTahunAkademik(String)} dan (bila terisi)
	 * {@link Konfigurasi#setInfo1(String)} disalin dari {@link KalenderAkademik#getTahunAjaran()}
	 * dan {@link KalenderAkademik#getGanjilGenap()}. Perubahan ini terjadi in-memory pada objek
	 * yang dibaca; pemanggil yang lalu menyimpan/mem-flush session akan membuatnya persisten.
	 * Seluruh badan method dibungkus {@code try/catch(Exception)} dengan audit otomatis
	 * ({@code ErrorAuditUtil.record}) &mdash; kegagalan di sini fail-silent, mengembalikan
	 * {@link Konfigurasi} dengan nilai yang mungkin belum sempat diperbarui.
	 *
	 * @return objek konfigurasi yang nilainya sudah/sedang disinkronkan dari rentang kalender
	 * akademik terkait, boleh {@code null} bila belum diisi
	 */
	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY)
	@JoinColumn(name = "konfigurasi", nullable = true)
	public Konfigurasi getKonfigurasi() {
		try {
			konfigurasi = check(konfigurasi);
			kalenderAkademik = getKalenderAkademik();
			if (konfigurasi != null && kalenderAkademik != null && kalenderAkademik.getTanggalMulai() != null
					&& kalenderAkademik.getTanggalSelesai() != null) {
				Date date = WaktuUtil.getDate();
				if ((Common.dateFormat1.get().format(kalenderAkademik.getTanggalMulai())
						.equals(Common.dateFormat1.get().format(date)) || kalenderAkademik.getTanggalMulai().before(date))
						&& (Common.dateFormat1.get().format(kalenderAkademik.getTanggalSelesai()).equals(
								Common.dateFormat1.get().format(date)) || kalenderAkademik.getTanggalSelesai().after(date))) {
					konfigurasi.setNilai(getPadaSaatMulaiBerubahMenjadi());
				} else {
					konfigurasi.setNilai(getPadaSaatSelesaiBerubahMenjadi());
				}
			}

			if (kalenderAkademik != null) {
				konfigurasi.setTahunAkademik(kalenderAkademik.getTahunAjaran());
				if (kalenderAkademik.getGanjilGenap() != null && !kalenderAkademik.getGanjilGenap().isEmpty()) {
					konfigurasi.setInfo1(kalenderAkademik.getGanjilGenap());
				}
			}
		} catch (Exception e) { ais.common.ErrorAuditUtil.record(e, "auto-audit(empty-catch) src/ais/database/model/KonfigurasiKalenderAkademik.java:167");
			// TODO: handle exception
		}

		return konfigurasi;
	}

	/** @param konfigurasi konfigurasi yang akan diatur otomatis oleh baris ini. */
	public void setKonfigurasi(Konfigurasi konfigurasi) {
		this.konfigurasi = konfigurasi;
	}

}
