package ais.database.model;

// Generated Apr 16, 2010 2:27:16 PM by Hibernate Tools 3.2.4.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.io.File;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.apache.commons.lang.StringUtils;
import org.hibernate.Session;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;
import org.hibernate.criterion.Order;
import org.hibernate.criterion.Restrictions;
import org.hibernate.envers.Audited;

import ais.common.Common;
import ais.database.hibernate.HibernateUtil;
import ais.database.model.pkl.KelompokPkl;
import ais.database.model.pkl.KomponenPenilaianPkl;
import ais.database.model.pkl.PklPunyaKomponenPenilaianPkl;

/**
 * Bank generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Entity(
    dynamicInsert = true,
    dynamicUpdate = true
)
@Audited
@Table(schema = "public", name = "mahasiswa_dapat_kelompok_kelompok_pkl")

public class MahasiswaDapatKelompokPkl extends GeneralValueObject implements VOPesertaPembelajaran {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2463821577548439808L;
	private Long id;
	private String oleh;
	private String olehId;

	public String getOlehId() {
		return olehId;
	}

	public void setOlehId(String olehId) {if (olehId == null || olehId.trim().isEmpty()) {return;}
		this.olehId = olehId;
	}

	public void setOleh(String oleh) {if (oleh == null || oleh.trim().isEmpty()) {return;}
		this.oleh = oleh;
	}

	public String getOleh() {
		return oleh;
	}

	@javax.persistence.PreUpdate protected void onUpdate() { ais.database.hibernate.AuditTimestampInterceptor.ubah(this);}     private Date tanggal_dirubah = ais.ui.util.WaktuUtil.getDate();

	public void setTanggal_dirubah(Date tanggal_dirubah) {
		this.tanggal_dirubah = tanggal_dirubah;
	}

	@Temporal(TemporalType.TIMESTAMP)
	public Date getTanggal_dirubah() {
		return tanggal_dirubah;
	}

	public String toString() {
		kelompokPkl = getKelompokPkl();
		mahasiswa = getMahasiswa();
		return kelompokPkl + "-" + mahasiswa;
	}

	private String namaDosen;
	private KelompokPkl kelompokPkl;
	private Mahasiswa mahasiswa;
	private Detailperkuliahan detailperkuliahan;
	private String keterangan;
	private String hasil;

	private Double totalNilai;
	private String nilaiHuruf;
	private Double totalIP = 0.0;
	private Boolean lulus;

	private String detailNilai = "";
	private Boolean diterima;

	public File write() {
		File f = write(Jurusan.class.getName(), Dosen.class.getName(), MahasiswaDapatKelompokPkl.class.getName(),
				Pegawai.class.getName(), Fakultas.class.getName(), PerguruanTinggi.class.getName(),
				LembagaPengangkat.class.getName(), TingkatKesulitanMatakuliah.class.getName(),
				Kurikulum.class.getName(), MasaPerkuliahan.class.getName(), JamPerkuliahan.class.getName(),
				JenisEvaluasi.class.getName(), Ruang.class.getName());
		return f;
	}

	public MahasiswaDapatKelompokPkl() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", insertable = false, unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "keterangan")
	public String getKeterangan() {
		return this.keterangan;
	}

	public void setKeterangan(String keterangan) {
		this.keterangan = keterangan;
	}

	public void setKelompokPkl(KelompokPkl kelompokPkl) {
		this.kelompokPkl = kelompokPkl;
	}

	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY)
	@JoinColumn(name = "kelompok_pkl", nullable = false)
	public KelompokPkl getKelompokPkl() {
		kelompokPkl = check(kelompokPkl);
		return kelompokPkl;
	}

	public void setMahasiswa(Mahasiswa mahasiswa) {
		this.mahasiswa = mahasiswa;
	}

	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY)
	@JoinColumn(name = "mahasiswa", nullable = false)
	public Mahasiswa getMahasiswa() {
		mahasiswa = check(mahasiswa);
		return mahasiswa;
	}

	public Double getTotalNilai() {
		return totalNilai == null ? 0.0 : totalNilai;
	}

	public void setTotalNilai(Double totalNilai) {
		this.totalNilai = totalNilai;
	}

	public String getNilaiHuruf() {
		return this.nilaiHuruf == null ? null : this.nilaiHuruf.trim();
	}

	public void setNilaiHuruf(String nilaiHuruf) {
		this.nilaiHuruf = nilaiHuruf;
	}

	@SuppressWarnings("unchecked")
	public void reloadPklPunyaKomponenPenilaianPkl(Session session) {

		refreshNilaiKeDefault();

		String formatbaru = "";
		List<PklPunyaKomponenPenilaianPkl> pklPunyaKomponenPenilaianPkls = session
				.createCriteria(PklPunyaKomponenPenilaianPkl.class).add(Restrictions.eq("pkl", kelompokPkl.getPkl()))
				.add(Restrictions.isNull("parent")).add(Restrictions.gt("persen", 0.01))
				.createCriteria("statusPertemuan").add(Restrictions.or(Restrictions.isNull("aktif"), Restrictions.eq("aktif", true))).addOrder(Order.asc("id")).list();
		for (PklPunyaKomponenPenilaianPkl pklPunyaKomponenPenilaianPkl : pklPunyaKomponenPenilaianPkls) {
			try {
				Double jumlah = retreiveDetailNilai(pklPunyaKomponenPenilaianPkl.getKomponenPenilaianPkl());
				Boolean verivy = retreiveDetailVerifikasiNilai(pklPunyaKomponenPenilaianPkl);
				String aformatBaru = pklPunyaKomponenPenilaianPkl.getKomponenPenilaianPkl().getId() + "," + jumlah
						+ ",0," + pklPunyaKomponenPenilaianPkl.getKomponenPenilaianPkl().getBobot() + "," + verivy;
				formatbaru += formatbaru.isEmpty() ? aformatBaru : ";" + aformatBaru;
			} catch (Exception e) {
				Common.tampilErrorJikaAdmin(e);
			}
		}

		detailNilai = formatbaru;
		// System.out.println("detailNilai baru => " + detailNilai);
	}

	public Double hitungTotalNilai(Boolean gunakanPklPunyaKomponenPenilaianPklDariDatabase) {
		return hitungTotalNilai(gunakanPklPunyaKomponenPenilaianPklDariDatabase, null);
	}

	public Double hitungTotalNilai(Boolean gunakanPklPunyaKomponenPenilaianPklDariDatabase,
			List<PklPunyaKomponenPenilaianPkl> pklPunyaKomponenPenilaianPkls) {

		refreshNilaiKeDefault();
		if (gunakanPklPunyaKomponenPenilaianPklDariDatabase) {
			if (pklPunyaKomponenPenilaianPkls == null) {
				bersihkanNilaiKeDefault();
			} else {
				bersihkanNilaiKeDefault(pklPunyaKomponenPenilaianPkls);
			}
		}

		Double total = 0.0;
		String str = getDetailNilai();
		Double totalPersen = 0.0;

		if (str != null && !str.trim().isEmpty()) {
			String[] s = StringUtils.split(str, ";");
			Map<Long, Object[]> nilais = new HashMap<Long, Object[]>();
			for (String ss : s) {
				try {
					String[] sss = StringUtils.split(ss, ",");
					Long idPklPunyaKomponenPenilaianPkl = Long.parseLong(sss[0].trim());
					// Parse aman: nilai/persen bisa berisi teks "null" atau kosong (komponen belum
					// diisi) yang membuat Double.parseDouble melempar NumberFormatException.
					Double persen = null;
					if (sss.length > 3) {
						try {
							persen = Double.parseDouble(sss[3].trim());
						} catch (Exception ig) {
							persen = null;
						}
					}
					if (persen != null) {
						double n = 0.0;
						try {
							if (sss.length > 1 && sss[1] != null) {
								n = Double.parseDouble(sss[1].trim());
							}
						} catch (Exception ig) {
							n = 0.0;
						}
						nilais.put(idPklPunyaKomponenPenilaianPkl, new Object[] { n, persen });

						totalPersen += persen;

					}
				} catch (Exception e) {
					Common.tampilErrorJikaAdmin(e);
				}
			}

			if (totalPersen > 0.001) {
				for (Long pklPunyaKomponenPenilaianPkl : nilais.keySet()) {
					try {
						Double n = (Double) nilais.get(pklPunyaKomponenPenilaianPkl)[0];
						Double persen = (Double) nilais.get(pklPunyaKomponenPenilaianPkl)[1];
						total += (n * (persen / totalPersen));
					} catch (Exception e) {
						Common.tampilErrorJikaAdmin(e);
					}
				}
			}
		}

		return total;
	}

	public void populateDetailNilai(KomponenPenilaianPkl komponenPenilaianPkl, Double jumlah, Boolean verify) {
		if (jumlah != null && jumlah < 0.01) {
			verify = false;
		}
		if (komponenPenilaianPkl != null) {
			String formatBaru = "";
			String[] nilais = detailNilai == null ? new String[] {} : detailNilai.split(";");
			Boolean ada = false;
			for (String nn : nilais) {
				try {
					String aformatBaru = "";
					String[] s = nn.split(",");
					if (!s[0].trim().isEmpty()) {
						Long formatId = Long.parseLong(s[0]);
						if (komponenPenilaianPkl.getId().equals(formatId)) {
							aformatBaru = komponenPenilaianPkl.getId() + "," + jumlah + ",0,"
									+ komponenPenilaianPkl.getBobot() + "," + verify;
							ada = true;
						} else {
							aformatBaru = nn;
						}
						if (!aformatBaru.trim().isEmpty()) {
							formatBaru += formatBaru.isEmpty() ? aformatBaru : ";" + aformatBaru;
						}
					}
				} catch (Exception e) {
					Common.tampilErrorJikaAdmin(e);
				}
			}

			if (!ada) {
				String aformatBaru = komponenPenilaianPkl.getId() + "," + jumlah + ",0,"
						+ komponenPenilaianPkl.getBobot() + "," + verify;
				formatBaru += formatBaru.isEmpty() ? aformatBaru : ";" + aformatBaru;
			}

			detailNilai = formatBaru;
		}

	}

	@SuppressWarnings("unchecked")
	public void bersihkanNilaiKeDefault() {
		Session session = HibernateUtil.currentSession();
		List<PklPunyaKomponenPenilaianPkl> pklPunyaKomponenPenilaianPkls = session
				.createCriteria(PklPunyaKomponenPenilaianPkl.class)
				.createAlias("komponenPenilaianPkl", "komponenPenilaianPkl")
				.add(Restrictions.or(Restrictions.isNull("komponenPenilaianPkl.aktif"),
						Restrictions.eq("komponenPenilaianPkl.aktif", true)))
				.add(Restrictions.eq("pkl", kelompokPkl.getPkl())).list();
		bersihkanNilaiKeDefault(pklPunyaKomponenPenilaianPkls);
	}

	public void bersihkanNilaiKeDefault(List<PklPunyaKomponenPenilaianPkl> pklPunyaKomponenPenilaianPkls) {
		String formatbaru = "";

		if (detailNilai != null && !detailNilai.trim().isEmpty()) {
			String[] s = StringUtils.split(detailNilai, ";");

			List<Long> ids = new ArrayList<Long>();
			for (PklPunyaKomponenPenilaianPkl pklPunyaKomponenPenilaianPkl : pklPunyaKomponenPenilaianPkls) {
				ids.add(pklPunyaKomponenPenilaianPkl.getKomponenPenilaianPkl().getId());
			}

			List<Long> idPklPunyaKomponenPenilaianPkls = new ArrayList<Long>();
			for (String ss : s) {
				String[] sss = StringUtils.split(ss, ",");
				Long idPklPunyaKomponenPenilaianPkl = Long.parseLong(sss[0].trim());
				if (!idPklPunyaKomponenPenilaianPkls.contains(idPklPunyaKomponenPenilaianPkl)) {
					idPklPunyaKomponenPenilaianPkls.add(idPklPunyaKomponenPenilaianPkl);
					if (ids.contains(idPklPunyaKomponenPenilaianPkl)) {
						formatbaru += formatbaru.isEmpty() ? ss : ";" + ss;
					}
				}
			}

			detailNilai = formatbaru;
		}
	}

	@SuppressWarnings("unchecked")
	public void refreshNilaiKeDefault() {
		if ((detailNilai == null || detailNilai.trim().isEmpty()) && totalNilai != null && totalNilai > 1.0) {
			String formatbaru = "";
			Session session = HibernateUtil.currentSession();
			List<PklPunyaKomponenPenilaianPkl> pklPunyaKomponenPenilaianPkls = session
					.createCriteria(PklPunyaKomponenPenilaianPkl.class)
					.createAlias("komponenPenilaianPkl", "komponenPenilaianPkl")
					.add(Restrictions.or(Restrictions.isNull("komponenPenilaianPkl.aktif"),
							Restrictions.eq("komponenPenilaianPkl.aktif", true)))
					.add(Restrictions.eq("pkl", kelompokPkl.getPkl())).list();

			for (PklPunyaKomponenPenilaianPkl pklPunyaKomponenPenilaianPkl : pklPunyaKomponenPenilaianPkls) {

				String aformatBaru = pklPunyaKomponenPenilaianPkl.getKomponenPenilaianPkl().getId() + "," + totalNilai
						+ ",0," + pklPunyaKomponenPenilaianPkl.getKomponenPenilaianPkl().getBobot() + ",false";
				formatbaru += formatbaru.isEmpty() ? aformatBaru : ";" + aformatBaru;
			}

			detailNilai = formatbaru;
		}
	}

	public Double retreiveDetailNilai(KomponenPenilaianPkl formatIdSource) {

		refreshNilaiKeDefault();

		if (formatIdSource != null && formatIdSource.getId() != null) {
			String[] nilais = detailNilai == null ? new String[] {} : detailNilai.split(";");
			for (String nn : nilais) {
				try {
					String[] s = nn.split(",");
					if (s.length < 2 || s[0] == null || s[0].trim().isEmpty()) {
						continue;
					}
					Long formatId = Long.parseLong(s[0]);
					if (formatIdSource.getId().equals(formatId)) {
						return s[1] == null || s[1].trim().isEmpty() ? 0.0 : Double.parseDouble(s[1]);
					}
				} catch (Exception e) { ais.common.ErrorAuditUtil.record(e, "auto-audit(empty-catch) src/ais/database/model/MahasiswaDapatKelompokPkl.java:393");

				}
			}
		}

		return 0.0;
	}

	public Boolean retreiveDetailVerifikasiNilai(PklPunyaKomponenPenilaianPkl formatIdSource) {

		refreshNilaiKeDefault();

		if (formatIdSource != null && formatIdSource.getId() != null) {
			String[] nilais = detailNilai == null ? new String[] {} : detailNilai.split(";");
			for (String nn : nilais) {
				try {
					String[] s = nn.split(",");
					Long formatId = Long.parseLong(s[0]);
					if (formatIdSource.getKomponenPenilaianPkl().getId().equals(formatId)) {
						if (Double.parseDouble(s[1]) < 0.01) {
							return false;
						}
						return Boolean.parseBoolean(s[4]);
					}
				} catch (Exception e) { ais.common.ErrorAuditUtil.record(e, "auto-audit(empty-catch) src/ais/database/model/MahasiswaDapatKelompokPkl.java:418");

				}
			}
		}

		return false;
	}

	public Double getTotalIP() {
		return totalIP == null ? 0.0 : totalIP;
	}

	public void setTotalIP(Double totalIP) {
		this.totalIP = totalIP;
	}

	public Boolean getLulus() {
		nilaiHuruf = getNilaiHuruf();
		// Utamakan KONFIGURASI Nilai Huruf yang DIPEROLEH (permintaan): status lulus mengikuti master
		// Nilai Huruf (ConstantValues.lulusDariNilaiHuruf) & mengoreksi nilai tersimpan yang basi.
		try {
			if (nilaiHuruf != null && !nilaiHuruf.trim().isEmpty()) {
				Boolean cfgLulus = ais.common.ConstantValues.lulusDariNilaiHuruf(nilaiHuruf, getMahasiswa());
				if (cfgLulus != null) {
					if (lulus == null || !lulus.equals(cfgLulus)) {
						lulus = cfgLulus;
					}
					return lulus;
				}
			}
		} catch (Exception e) { ais.common.ErrorAuditUtil.record(e, "auto-audit(empty-catch) src/ais/database/model/MahasiswaDapatKelompokPkl.java:449");
		}
		if (lulus == null && nilaiHuruf != null) {
			if (nilaiHuruf.isEmpty() || nilaiHuruf.toUpperCase().contains("D") || nilaiHuruf.toUpperCase().contains("E")
					|| nilaiHuruf.toUpperCase().contains("T")) {
				lulus = false;
			} else {
				lulus = true;
			}
		} else if (lulus == null) {
			lulus = true;
		}

		if (nilaiHuruf == null) {
			lulus = false;
		}

		return lulus;
	}

	public void setLulus(Boolean lulus) {
		this.lulus = lulus;
	}

	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE })
	@Fetch(FetchMode.SELECT)
	@JoinColumn(name = "detailperkuliahan_id", nullable = true)
	public Detailperkuliahan getDetailperkuliahan() {
		return detailperkuliahan;
	}

	public void setDetailperkuliahan(Detailperkuliahan detailperkuliahan) {
		this.detailperkuliahan = detailperkuliahan;
	}

	@Column(columnDefinition = "text")
	public String getDetailNilai() {
		return detailNilai == null ? "" : detailNilai.trim();
	}

	public void setDetailNilai(String detailNilai) {
		this.detailNilai = detailNilai;
	}

	public Boolean getDiterima() {
		// if (kelompokPkl != null && !kelompokPkl.getMahasiswaBisaMemilih()) {
		// diterima = true;
		// }
		return diterima == null ? false : diterima;
	}

	public void setDiterima(Boolean diterima) {
		this.diterima = diterima;
	}

	public String getNamaDosen() {
		if (kelompokPkl != null) {
			namaDosen = org.apache.commons.lang3.StringUtils.replace(
					org.apache.commons.lang3.StringUtils.replace(kelompokPkl.populateDosenBuNama().toString(), "]", ""),
					"[", "");
		}
		return namaDosen;
	}

	public void setNamaDosen(String namaDosen) {
		this.namaDosen = namaDosen;
	}

	@Override
	public VOPembelajaran ambilVOPembelajaran() {
		// TODO Auto-generated method stub
		return kelompokPkl;
	}

	@Column(columnDefinition = "text")
	public String getHasil() {
		return hasil == null ? "" : hasil.trim();
	}

	public void setHasil(String hasil) {
		this.hasil = hasil;
	}
}
