package ais.database.model;

// Generated Dec 22, 2009 12:14:16 PM by Hibernate Tools 3.2.4.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.io.File;
import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.envers.Audited;

/**
 * MatakuliahEkivalen generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Entity(
    dynamicInsert = true,
    dynamicUpdate = true
)
@Audited
@Table(schema = "public", name = "matakuliah_ekivalen")
public class MatakuliahEkivalen extends GeneralValueObject {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1950126270979098967L;
	private Long id;
	private String oleh;
	private String olehId;

	public String getOlehId() {
		return olehId;
	}

	public void setOlehId(String olehId) {if (olehId == null || olehId.trim().isEmpty()) {return;}
		this.olehId = olehId;
	}

	public void setOleh(String oleh) {if (oleh == null || oleh.trim().isEmpty()) {return;}
		this.oleh = oleh;
	}

	public String getOleh() {
		return oleh;
	}

	@javax.persistence.PreUpdate protected void onUpdate() { ais.database.hibernate.AuditTimestampInterceptor.ubah(this);}     private Date tanggal_dirubah = ais.ui.util.WaktuUtil.getDate();

	public void setTanggal_dirubah(Date tanggal_dirubah) {
		this.tanggal_dirubah = tanggal_dirubah;
	}

	@Temporal(TemporalType.TIMESTAMP)
	public Date getTanggal_dirubah() {
		return tanggal_dirubah;
	}

	public String toString() {
		return matakuliah + "_" + matakuliahEkivalen;
	}

	private Matakuliah matakuliah;
	private Matakuliah matakuliahEkivalen;
	private Matakuliah matakuliahEkivalen2;
	private Matakuliah matakuliahEkivalen3;
	private Matakuliah matakuliahEkivalen4;
	private Matakuliah matakuliahEkivalen5;
	private String keterangan;
	private String khususUntukNim;
	private Boolean udah;

	private String fileLocation;
	private Boolean aktif;

	public File write() {
		File f = write(Jurusan.class.getName(), Dosen.class.getName(), TingkatKesulitanMatakuliah.class.getName(),
				Kurikulum.class.getName(), MasaPerkuliahan.class.getName(), JamPerkuliahan.class.getName(),
				JenisEvaluasi.class.getName(), Ruang.class.getName());
		setFileLocation(f.getAbsolutePath());
		return f;
	}

	public MatakuliahEkivalen() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", insertable = false, unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY)
	@JoinColumn(name = "matakuliah", nullable = false)
	public Matakuliah getMatakuliah() {
		matakuliah = check(matakuliah);
		return this.matakuliah;
	}

	public void setMatakuliah(Matakuliah matakuliah) {
		this.matakuliah = matakuliah;
	}

	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY)
	@JoinColumn(name = "matakuliah_ekivalen", nullable = false)
	public Matakuliah getMatakuliahEkivalen() {
		matakuliahEkivalen = check(matakuliahEkivalen);
		return this.matakuliahEkivalen;
	}

	public void setMatakuliahEkivalen(Matakuliah matakuliahEkivalen) {
		this.matakuliahEkivalen = matakuliahEkivalen;
	}

	public String getKeterangan() {
		return keterangan;
	}

	public void setKeterangan(String keterangan) {
		this.keterangan = keterangan;
	}

	@Column(columnDefinition = "text", name = "khusus_untuk_nim")
	public String getKhususUntukNim() {
		khususUntukNim = (khususUntukNim == null || khususUntukNim.trim().equalsIgnoreCase(",") ? ""
				: "," + khususUntukNim.trim() + ",").replaceAll(",,", ",").replaceAll(",,", ",").replaceAll(",,", ",");

		if (khususUntukNim.equals(",")) {
			khususUntukNim = "";
		} else if (khususUntukNim.equals(",,")) {
			khususUntukNim = "";
		} else if (khususUntukNim.equals(",,,")) {
			khususUntukNim = "";
		} else if (khususUntukNim.equals(",,,,")) {
			khususUntukNim = "";
		} else if (khususUntukNim.equals(",,,,,")) {
			khususUntukNim = "";
		}

		if (khususUntukNim == null) {
			khususUntukNim = "";
		}

		return khususUntukNim.trim();
	}

	public void setKhususUntukNim(String khususUntukNim) {
		this.khususUntukNim = khususUntukNim;
	}

	public Boolean getUdah() {
		return udah == null ? true : udah;
	}

	public void setUdah(Boolean udah) {
		this.udah = udah;
	}

	public String getFileLocation() {
		if (fileLocation == null || !fileLocation.endsWith(getId() + ".json")
				|| java.nio.file.Files.notExists(java.nio.file.Paths.get(fileLocation))) {
			write();
		}
		return fileLocation;
	}

	public void setFileLocation(String fileLocation) {
		this.fileLocation = fileLocation;
	}

	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY)
	@JoinColumn(name = "matakuliah_ekivalen2", nullable = true)
	public Matakuliah getMatakuliahEkivalen2() {
		matakuliahEkivalen2 = check(matakuliahEkivalen2);
		return matakuliahEkivalen2;
	}

	public void setMatakuliahEkivalen2(Matakuliah matakuliahEkivalen2) {
		this.matakuliahEkivalen2 = matakuliahEkivalen2;
	}

	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY)
	@JoinColumn(name = "matakuliah_ekivalen3", nullable = true)
	public Matakuliah getMatakuliahEkivalen3() {
		matakuliahEkivalen3 = check(matakuliahEkivalen3);
		return matakuliahEkivalen3;
	}

	public void setMatakuliahEkivalen3(Matakuliah matakuliahEkivalen3) {
		this.matakuliahEkivalen3 = matakuliahEkivalen3;
	}

	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY)
	@JoinColumn(name = "matakuliah_ekivalen4", nullable = true)
	public Matakuliah getMatakuliahEkivalen4() {
		matakuliahEkivalen4 = check(matakuliahEkivalen4);
		return matakuliahEkivalen4;
	}

	public void setMatakuliahEkivalen4(Matakuliah matakuliahEkivalen4) {
		this.matakuliahEkivalen4 = matakuliahEkivalen4;
	}

	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY)
	@JoinColumn(name = "matakuliah_ekivalen5", nullable = true)
	public Matakuliah getMatakuliahEkivalen5() {
		matakuliahEkivalen5 = check(matakuliahEkivalen5);
		return matakuliahEkivalen5;
	}

	public void setMatakuliahEkivalen5(Matakuliah matakuliahEkivalen5) {
		this.matakuliahEkivalen5 = matakuliahEkivalen5;
	}

	public Boolean getAktif() {
		return aktif == null ? true : aktif;
	}

	public void setAktif(Boolean aktif) {
		this.aktif = aktif;
	}

}
