package ais.database.model;

// Generated 06 Jan 09 21:45:56 by Hibernate Tools 3.2.4.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.apache.commons.lang.RandomStringUtils;
import org.hibernate.envers.Audited;

/**
 * Menu generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Entity(
    dynamicInsert = true,
    dynamicUpdate = true
)
@Audited
@Table(schema = "public", name = "menu_mobile")
public class MenuMobile extends GeneralValueObject {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7836173482067483952L;
	private Long id;
	private String oleh;
	private String olehId;

	public String getOlehId() {
		return olehId;
	}

	public void setOlehId(String olehId) {if (olehId == null || olehId.trim().isEmpty()) {return;}
		this.olehId = olehId;
	}

	public void setOleh(String oleh) {if (oleh == null || oleh.trim().isEmpty()) {return;}
		this.oleh = oleh;
	}

	public String getOleh() {
		return oleh;
	}

	@javax.persistence.PreUpdate protected void onUpdate() { ais.database.hibernate.AuditTimestampInterceptor.ubah(this);}     private Date tanggal_dirubah = ais.ui.util.WaktuUtil.getDate();

	public void setTanggal_dirubah(Date tanggal_dirubah) {
		this.tanggal_dirubah = tanggal_dirubah;
	}

	@Temporal(TemporalType.TIMESTAMP)
	public Date getTanggal_dirubah() {
		return tanggal_dirubah;
	}

	private Long root;
	private Long child;
	private String label;
	private String url;
	private String icon;
	private String bigIcon;
	private Boolean aktif;
	private Integer nomorUrut;

	public String toString() {
		return label;
	}

	@Column(name = "icon")
	public String getIcon() {
		return icon;
	}

	public void setIcon(String icon) {
		this.icon = icon;
	}

	public MenuMobile() {
	}

	public MenuMobile(Long root, Long child) {
		this.root = root;
		this.child = child;
	}

	public MenuMobile(Long root, Long child, String label) {
		this.root = root;
		this.child = child;
		this.label = label;
	}

	public MenuMobile(Long root, Long child, String label, String url) {
		this.root = root;
		this.child = child;
		this.label = label;
		this.url = url;
	}

	@Id
	@Column(name = "id", insertable = true, unique = true, nullable = false)
	public Long getId() {
		if (id == null) {
			id = Long.parseLong(RandomStringUtils.randomNumeric(6));
		}
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "root", nullable = true)
	public Long getRoot() {
		return this.root;
	}

	public void setRoot(Long root) {
		this.root = root;
	}

	@Column(name = "child", nullable = true)
	public Long getChild() {
		return this.child;
	}

	public void setChild(Long child) {
		this.child = child;
	}

	@Column(name = "label", nullable = true, length = 100)
	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	@Column(name = "url", length = 100)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public void setBigIcon(String bigIcon) {
		this.bigIcon = bigIcon;
	}

	@Column(name = "big_icon", length = 255)
	public String getBigIcon() {
		return bigIcon;
	}

	@Override
	public int compareTo(GeneralValueObject object) {
		MenuMobile arg0 = (MenuMobile) object;
		if (arg0 == null || arg0.getLabel() == null || this.label == null) {
			return 0;
		} else {
			return this.label.compareTo(arg0.getLabel());
		}
	}

	public void setAktif(Boolean aktif) {
		this.aktif = aktif;
	}

	public Boolean getAktif() {
		if (aktif == null) {
			aktif = true;
		}
		return aktif;
	}

	public Integer getNomorUrut() {
		return nomorUrut == null ? 1 : nomorUrut;
	}

	public void setNomorUrut(Integer nomorUrut) {
		this.nomorUrut = nomorUrut;
	}
}
