package ais.database.model;

// Generated Apr 16, 2010 2:27:16 PM by Hibernate Tools 3.2.4.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.envers.Audited;

/**
 * Bank generated by hbm2java
 *
 * <p><b>Jurnal peristiwa restart/siklus-hidup aplikasi.</b> Satu baris = satu catatan bebas-teks
 * tentang kapan dan mengapa aplikasi (server/aplikasi web AIS) dihentikan/dinyalakan ulang, atau
 * peristiwa siklus-hidup serupa yang ingin dicatat operator/administrator. Tidak ada relasi ke
 * entity lain dan tidak ada field terstruktur selain {@link #getKeterangan()} -- seluruh makna
 * baris ada di dalam teks bebas tersebut, ditulis oleh pemanggil.</p>
 */
@Entity
@org.hibernate.annotations.Entity(
    dynamicInsert = true,
    dynamicUpdate = true
)
@Audited
@Table(schema = "public", name = "restart_log")

public class RestartLog extends GeneralValueObject {

	/**
	 *
	 */
	private static final long serialVersionUID = 2463821577548439808L;

	/** Primary key baris log, dihasilkan basis data (strategi {@code IDENTITY}). */
	private Long id;
	/** Jejak "siapa yang menulis baris ini", diisi otomatis lewat {@link #setOleh(String)}. */
	private String oleh;
	/** Pendamping {@link #oleh}. Lihat {@link #getOlehId()}. */
	private String olehId;

	/**
	 * Mengembalikan rantai jejak pemanggil yang tersimpan bersama {@link #oleh}, diisi otomatis
	 * oleh {@code AuditTimestampInterceptor}.
	 *
	 * @return jejak pemanggil; boleh {@code null} bila belum pernah diisi
	 */
	public String getOlehId() {
		return olehId;
	}

	/**
	 * Menyetel jejak pemanggil {@link #getOlehId()}. Setter ini <b>mengabaikan diam-diam</b>
	 * nilai {@code null}/kosong sehingga jejak lama tidak dapat ditimpa nilai hampa.
	 *
	 * @param olehId jejak pemanggil baru; {@code null}/kosong diabaikan tanpa peringatan
	 */
	public void setOlehId(String olehId) {if (olehId == null || olehId.trim().isEmpty()) {return;}
		this.olehId = olehId;
	}

	/**
	 * Menyetel identitas pelaku penyimpanan baris ini. Nilai {@code null}/kosong diabaikan
	 * diam-diam agar jejak lama tidak tertimpa nilai hampa.
	 *
	 * @param oleh nama/identitas pelaku; {@code null}/kosong diabaikan tanpa peringatan
	 */
	public void setOleh(String oleh) {if (oleh == null || oleh.trim().isEmpty()) {return;}
		this.oleh = oleh;
	}

	/**
	 * Mengembalikan identitas pelaku yang terakhir menyimpan baris ini.
	 *
	 * @return nama/identitas pelaku; boleh {@code null} bila belum pernah diisi
	 */
	public String getOleh() {
		return oleh;
	}

	/**
	 * <i>Callback</i> JPA {@link javax.persistence.PreUpdate} yang memperbarui
	 * {@link #getTanggal_dirubah()}/{@link #getOleh()}/{@link #getOlehId()} lewat
	 * {@code AuditTimestampInterceptor} pada setiap UPDATE baris.
	 */
	@javax.persistence.PreUpdate protected void onUpdate() { ais.database.hibernate.AuditTimestampInterceptor.ubah(this);}     /** Stempel waktu terakhir baris diubah, diinisialisasi ke waktu server saat objek dibuat. */
	private Date tanggal_dirubah = ais.ui.util.WaktuUtil.getDate();

	/**
	 * Menyetel stempel waktu perubahan terakhir. Umumnya diurus otomatis oleh {@link #onUpdate()}.
	 *
	 * @param tanggal_dirubah stempel waktu baru
	 */
	public void setTanggal_dirubah(Date tanggal_dirubah) {
		this.tanggal_dirubah = tanggal_dirubah;
	}

	/**
	 * Mengembalikan stempel waktu perubahan terakhir (presisi TIMESTAMP).
	 *
	 * @return waktu terakhir baris disimpan/diubah
	 */
	@Temporal(TemporalType.TIMESTAMP)
	public Date getTanggal_dirubah() {
		return tanggal_dirubah;
	}

	/** Representasi teks baris, berupa id digabung keterangan apa adanya (tanpa <i>trim</i>). */
	public String toString() {
		return id + "-" + keterangan;
	}

	/** Keterangan bebas peristiwa restart/siklus-hidup. Satu-satunya field bisnis kelas ini. */
	private String keterangan;

	/** Konstruktor tanpa argumen yang diwajibkan JPA/Hibernate. */
	public RestartLog() {
	}

	/**
	 * Mengembalikan primary key baris log.
	 *
	 * <p>Perhatikan {@code insertable = false}: nilai id sepenuhnya dihasilkan basis data
	 * (strategi {@code IDENTITY}), sehingga memanggil {@link #setId(Long)} sebelum menyimpan
	 * tidak memaksakan id tertentu.</p>
	 *
	 * @return id baris; {@code null} selama objek belum pernah disimpan
	 */
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", insertable = false, unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	/**
	 * Menyetel primary key baris log. Hanya relevan bagi Hibernate saat mengisi objek dari hasil
	 * query, karena kolom dipetakan {@code insertable = false} (lihat {@link #getId()}).
	 *
	 * @param id nilai primary key
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * Mengembalikan keterangan bebas peristiwa, dengan spasi tepi dipangkas dan dinormalisasi ke
	 * string kosong (bukan {@code null}) bila belum diisi.
	 *
	 * @return keterangan yang sudah di-<i>trim</i>; tidak pernah {@code null}
	 */
	@Column(name = "keterangan", columnDefinition = "text", nullable = true)
	public String getKeterangan() {
		return this.keterangan == null ? "" : keterangan.trim();
	}

	/**
	 * Menyetel keterangan bebas peristiwa restart/siklus-hidup. Kolom {@code text} sehingga tidak
	 * dibatasi panjang.
	 *
	 * @param keterangan keterangan baru; boleh {@code null}
	 */
	public void setKeterangan(String keterangan) {
		this.keterangan = keterangan;
	}

}
