package ais.database.model.penelitiandanpengabdian;

/**
 * Catatan (diverifikasi ulang, lihat riwayat javadoc r78724): kelas ini BUKAN
 * entitas Hibernate (tidak ada anotasi {@code @Entity}/{@code @Table}, tidak
 * ada field persisten sama sekali) — berbeda dari kebanyakan kelas lain di
 * paket {@code ais.database.model}, dan BUKAN pula wrapper/pemegang relasi
 * seperti {@code LampiranLainMahasiswa} di paket {@code ais.database.model.file}
 * (entitas mandiri dengan FK ke pemiliknya). Kelas ini murni penyedia templat
 * HTML statis (constant HTML factory) untuk modul penelitian &amp; pengabdian
 * kepada masyarakat dosen: {@link #init()} mengembalikan satu string HTML
 * raksasa (gabungan literal-literal Java, tanpa I/O, tanpa akses DB) berisi
 * SEMBILAN blok lampiran baku proposal/laporan hibah penelitian-pengabdian
 * ala pedoman DIKTI, dalam urutan kemunculan:
 * <ol>
 * <li>Format Justifikasi Anggaran (rincian honor, peralatan penunjang, bahan
 * habis pakai, perjalanan, lain-lain, total anggaran per tahun);</li>
 * <li>Format Jadwal Kegiatan (tabel bulan x tahun per jenis kegiatan);</li>
 * <li>Format Susunan Organisasi Tim Peneliti/Pelaksana dan pembagian
 * tugas;</li>
 * <li>Format Biodata Ketua/Anggota Tim Peneliti/Pelaksana (identitas diri,
 * riwayat pendidikan, pengalaman penelitian/pengabdian, publikasi, HKI, dll,
 * ditutup pernyataan tanggung jawab &amp; tanda tangan);</li>
 * <li>Format Surat Pernyataan Ketua Peneliti/Pelaksana (kop perguruan tinggi,
 * pernyataan orisinalitas proposal, meterai &amp; tanda tangan);</li>
 * <li>Format Catatan Harian (Logbook) — tabel tanggal/kegiatan/dokumen
 * pendukung;</li>
 * <li>Format Laporan Kemajuan — sampul muka, halaman pengesahan, dan
 * sistematika laporan (kolom Penelitian vs Pengabdian berdampingan);</li>
 * <li>Format Laporan Tahunan/Akhir — struktur sampul &amp; halaman pengesahan
 * yang sama persis dengan Laporan Kemajuan (poin 7), hanya judul &amp;
 * beberapa catatan kaki yang berbeda; dan</li>
 * <li>Formulir Evaluasi Atas Capaian Luaran Kegiatan — identitas
 * ketua/kegiatan, tabel luaran direncanakan vs capaian, lalu rincian bukti
 * capaian per kategori luaran (publikasi ilmiah, buku ajar, pembicara
 * seminar, keynote speaker, undangan visiting scientist, capaian luaran
 * lainnya seperti HKI/TTG/rekayasa sosial/jejaring/penghargaan).</li>
 * </ol>
 * Setiap bagian dibungkus {@code <div class="content-frame">} berisi tabel
 * kosong siap-isi (placeholder {@code &nbsp;}/titik-titik), memakai kelas CSS
 * {@code font-TitleContent}/{@code font-IsiBab} yang didefinisikan oleh
 * stylesheet halaman JSP/ZK pemanggil (bukan oleh kelas ini). Konten HANYA
 * lampiran umum/contoh format kosong untuk ditampilkan sebagai panduan pada
 * layar pengajuan penelitian &amp; pengabdian masyarakat — bukan diisi dari
 * data entitas tersimpan, dan tidak mengandung data spesifik dosen/pengguna
 * mana pun. Pemakai satu-satunya yang ditemukan di kode: field
 * {@code lampiranUmum} pada
 * {@link ais.database.model.penelitiandanpengabdian.PenelitianDanPengabdian}
 * diinisialisasi langsung dari {@link #init()} sebagai NILAI AWAL (default)
 * saat objek dibuat — bukan dipanggil ulang setiap kali ditampilkan — sehingga
 * setelah baris itu dieksekusi, isi lampiran umum pada tiap record
 * {@code PenelitianDanPengabdian} sudah lepas dari kelas ini dan bisa diedit
 * independen (mis. lewat editor HTML di UI) tanpa memengaruhi record lain.
 */
public class LampiranUmumPenelitian {

	/**
	 * Menghasilkan satu blok HTML statis berisi seluruh templat lampiran umum
	 * penelitian &amp; pengabdian masyarakat — sembilan bagian yang didaftar
	 * lengkap pada javadoc kelas ({@link LampiranUmumPenelitian}), dari Format
	 * Justifikasi Anggaran sampai Formulir Evaluasi Atas Capaian Luaran.
	 * Implementasi membangun string {@code s} lewat rangkaian penambahan
	 * ({@code s += "..."}) blok demi blok, murni literal HTML tanpa logika
	 * kondisional, perulangan, maupun substitusi parameter — setiap pemanggilan
	 * method ini dengan input apa pun (tidak ada parameter) selalu menghasilkan
	 * string yang identik byte-demi-byte. Karena tanda tangannya {@code static}
	 * dan tidak mengubah/membaca state instance atau statis lain, method ini
	 * murni (pure) dan aman dipanggil dari thread mana pun tanpa sinkronisasi.
	 * Biaya pemanggilannya didominasi alokasi/penggabungan string yang cukup
	 * besar (ratusan baris literal); pemanggil yang butuh nilai ini berkali-kali
	 * dalam permintaan yang sama sebaiknya menyimpan hasilnya sendiri alih-alih
	 * memanggil ulang {@link #init()}, meskipun untuk pemakaian sebagai nilai
	 * awal field (satu kali per objek baru, lihat javadoc kelas) biaya ini tidak
	 * signifikan.
	 *
	 * @return string HTML gabungan seluruh templat lampiran, siap ditampilkan
	 *         apa adanya (tanpa proses lebih lanjut) oleh komponen UI pemanggil
	 */
	public static String init() {

		String s = "<div class=\"content-frame\" style=\"width:625px;\">\n"
				+ "        <p class=\"font-TitleContent\">Format Justifikasi Anggaran</p>\n" + "        \n"
				+ "        <table width=\"620\" border=\"1\" cellpadding=\"1\" class=\"font-IsiBab\">\n"
				+ "          \n"
				+ "            <tbody><tr><td colspan=\"7\" height=\"25\" align=\"left\"><b>1. Honor</b></td></tr>\n"
				+ "          \n"
				+ "            <tr><td rowspan=\"2\" align=\"center\" width=\"160\">Pelaksana</td><td align=\"center\" rowspan=\"2\" width=\"100\">Honor/jam (Rp)</td>\n"
				+ "                <td align=\"center\" rowspan=\"2\" width=\"90\">Waktu (jam/minggu)</td><td align=\"center\" rowspan=\"2\" width=\"90\">Minggu</td>\n"
				+ "                <td align=\"center\" colspan=\"3\" width=\"180\">Honor per tahun (Rp)</td></tr>\n"
				+ "                <tr><td align=\"center\" width=\"60\">Thn I</td><td align=\"center\" width=\"60\">Thn ...</td><td align=\"center\" width=\"60\">Thn n</td></tr>\n"
				+ "            <tr><td>&nbsp;Ketua</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>\n"
				+ "            <tr><td>&nbsp;Anggota 1</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>\n"
				+ "            <tr><td>&nbsp;Anggota 2</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>\n"
				+ "            <tr><td>&nbsp;Anggota n</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>\n"
				+ "            <tr><td colspan=\"4\" align=\"right\">Sub total (Rp)</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>\n"
				+ "        \n"
				+ "            <tr><td colspan=\"7\" height=\"25\" align=\"left\"><b>2. Peralatan penunjang</b></td></tr>\n"
				+ "        \n"
				+ "            <tr><td rowspan=\"2\" align=\"center\" width=\"160\">Material</td><td align=\"center\" rowspan=\"2\" width=\"100\">Justifikasi Pemakaian</td>\n"
				+ "                <td align=\"center\" rowspan=\"2\" width=\"90\">Kuantitas</td><td align=\"center\" rowspan=\"2\" width=\"90\">Harga Satuan (Rp)</td>\n"
				+ "                <td align=\"center\" colspan=\"3\" width=\"180\">Harga Peralatan Penunjang  (Rp)</td></tr>\n"
				+ "                <tr><td align=\"center\" width=\"60\">Thn I</td><td align=\"center\" width=\"60\">Thn ...</td><td align=\"center\" width=\"60\">Thn n</td></tr>\n"
				+ "            <tr><td>&nbsp;Peralatan penunjang 1</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>\n"
				+ "            <tr><td>&nbsp;Peralatan penunjang 2</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>\n"
				+ "            <tr><td>&nbsp;..... </td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>\n"
				+ "            <tr><td>&nbsp;Peralatan penunjang n</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>\n"
				+ "            <tr><td colspan=\"4\" align=\"right\">Sub total (Rp)</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>\n"
				+ "        \n"
				+ "            <tr><td colspan=\"7\" height=\"25\" align=\"left\"><b>3. Bahan Habis Pakai </b></td></tr>\n"
				+ "\n"
				+ "            <tr><td rowspan=\"2\" align=\"center\" width=\"160\">Material</td><td align=\"center\" rowspan=\"2\" width=\"100\">Justifikasi Pemakaian</td>\n"
				+ "                <td align=\"center\" rowspan=\"2\" width=\"90\">Kuantitas</td><td align=\"center\" rowspan=\"2\" width=\"90\">Harga Satuan (Rp)</td>\n"
				+ "                <td align=\"center\" colspan=\"3\" width=\"180\">Biaya per Tahun (Rp)</td></tr>\n"
				+ "                <tr><td align=\"center\" width=\"60\">Thn I</td><td align=\"center\" width=\"60\">Thn ...</td><td align=\"center\" width=\"60\">Thn n</td></tr>\n"
				+ "            <tr><td>&nbsp;Material 1</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>\n"
				+ "            <tr><td>&nbsp;Material 2</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>\n"
				+ "            <tr><td>&nbsp;..... </td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>\n"
				+ "            <tr><td>&nbsp;Material n</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>\n"
				+ "            <tr><td colspan=\"4\" align=\"right\">Sub total (Rp)</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>\n"
				+ "\n"
				+ "            <tr><td colspan=\"7\" height=\"25\" align=\"left\"><b>4. Perjalanan </b></td></tr>\n"
				+ "      \n"
				+ "            <tr><td rowspan=\"2\" align=\"center\" width=\"160\">Perjalanan</td><td align=\"center\" rowspan=\"2\" width=\"100\">Justifikasi Perjalanan</td>\n"
				+ "                <td align=\"center\" rowspan=\"2\" width=\"90\">Kuantitas</td><td align=\"center\" rowspan=\"2\" width=\"90\">Harga Satuan (Rp)</td>\n"
				+ "                <td align=\"center\" colspan=\"3\" width=\"180\">Biaya per Tahun (Rp)</td></tr>\n"
				+ "                <tr><td align=\"center\" width=\"60\">Thn I</td><td align=\"center\" width=\"60\">Thn ...</td><td align=\"center\" width=\"60\">Thn n</td></tr>\n"
				+ "            <tr><td>&nbsp;Perjalanan ke kota A</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>\n"
				+ "            <tr><td>&nbsp;Perjalanan ke kota B</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>\n"
				+ "            <tr><td>&nbsp;..... </td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>\n"
				+ "            <tr><td>&nbsp;Perjalanan ke kota ke-n</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>\n"
				+ "            <tr><td colspan=\"4\" align=\"right\">Sub total (Rp)</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>\n"
				+ "      \n"
				+ "            <tr><td colspan=\"7\" height=\"25\" align=\"left\"><b>5. Lain-lain  </b></td></tr>\n"
				+ "        \n"
				+ "            <tr><td rowspan=\"2\" align=\"center\" width=\"160\">Kegiatan</td><td align=\"center\" rowspan=\"2\" width=\"100\">Justifikasi</td>\n"
				+ "                <td align=\"center\" rowspan=\"2\" width=\"90\">Kuantitas</td><td align=\"center\" rowspan=\"2\" width=\"90\">Harga Satuan (Rp)</td>\n"
				+ "                <td align=\"center\" colspan=\"3\" width=\"180\">Biaya per Tahun (Rp)</td></tr>\n"
				+ "                <tr><td align=\"center\" width=\"60\">Thn I</td><td align=\"center\" width=\"60\">Thn ...</td><td align=\"center\" width=\"60\">Thn n</td></tr>\n"
				+ "            <tr><td>&nbsp;Lain-lain (administrasi, publikasi, seminar, laporan, lainnya sebutkan)</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>\n"
				+ "            <tr><td>&nbsp;Perjalanan ke kota B</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>\n"
				+ "            <tr><td>&nbsp;..... </td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>\n"
				+ "            <tr><td>&nbsp;Perjalanan ke kota ke-n</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>\n"
				+ "            <tr><td colspan=\"4\" align=\"right\">Sub total (Rp)</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>\n"
				+ "\n"
				+ "            <tr><td colspan=\"4\" rowspan=\"2\" align=\"right\">TOTAL ANGGARAN YANG DIPERLUKAN SETIAP TAHUN (Rp)</td>\n"
				+ "                <td align=\"center\" width=\"60\">Thn I</td><td align=\"center\" width=\"60\">Thn ...</td><td align=\"center\" width=\"60\">Thn n</td></tr>\n"
				+ "            <tr><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>\n" + "\n"
				+ "            <tr><td colspan=\"4\" height=\"30\" align=\"right\">TOTAL ANGGARAN YANG DIPERLUKAN SELURUH TAHUN (Rp)</td>\n"
				+ "                <td colspan=\"3\">&nbsp;</td></tr>\n" + "      \n" + "        </tbody></table>\n"
				+ "         &nbsp;<br>\n" + "\n" + "    </div>";

		s += "<div class=\"content-frame\" style=\"width:625px;\">\n"
				+ "        <p class=\"font-TitleContent\">Format Jadwal Kegiatan</p>\n" + "        \n"
				+ "        <table width=\"620\" border=\"1\" cellpadding=\"1\" class=\"font-IsiBab\">\n"
				+ "          \n" + "                   \n"
				+ "            <tbody><tr><td rowspan=\"2\" align=\"center\"><b>No</b></td><td align=\"center\" rowspan=\"2\"><b>Jenis Kegiatan</b></td>\n"
				+ "                <td align=\"center\" colspan=\"6\"><b>Tahun I</b></td><td align=\"center\" colspan=\"6\"><b>Tahun ...</b> </td><td align=\"center\" colspan=\"6\"><b>Tahun n</b></td></tr>\n"
				+ "            <tr><td align=\"center\">1</td><td align=\"center\">2</td><td align=\"center\">3</td><td align=\"center\">...</td><td align=\"center\">...</td><td align=\"center\">12</td>\n"
				+ "                <td align=\"center\">1</td><td align=\"center\">2</td><td align=\"center\">3</td><td align=\"center\">...</td><td align=\"center\">...</td><td align=\"center\">12</td>\n"
				+ "                <td align=\"center\">1</td><td align=\"center\">2</td><td align=\"center\">3</td><td align=\"center\">...</td><td align=\"center\">...</td><td align=\"center\">12</td></tr>\n"
				+ "            <tr><td align=\"center\">1</td><td align=\"left\">&nbsp;Kegiatan 1</td>\n"
				+ "                <td align=\"center\">&nbsp;</td><td align=\"center\">&nbsp;</td><td align=\"center\">&nbsp;</td><td align=\"center\">&nbsp;</td><td align=\"center\">&nbsp;</td><td align=\"center\">&nbsp;</td>\n"
				+ "                <td align=\"center\">&nbsp;</td><td align=\"center\">&nbsp;</td><td align=\"center\">&nbsp;</td><td align=\"center\">&nbsp;</td><td align=\"center\">&nbsp;</td><td align=\"center\">&nbsp;</td>\n"
				+ "                <td align=\"center\">&nbsp;</td><td align=\"center\">&nbsp;</td><td align=\"center\">&nbsp;</td><td align=\"center\">&nbsp;</td><td align=\"center\">&nbsp;</td><td align=\"center\">&nbsp;</td></tr>\n"
				+ "            <tr><td align=\"center\">2</td><td align=\"left\">&nbsp;Kegiatan 2</td>\n"
				+ "                <td align=\"center\">&nbsp;</td><td align=\"center\">&nbsp;</td><td align=\"center\">&nbsp;</td><td align=\"center\">&nbsp;</td><td align=\"center\">&nbsp;</td><td align=\"center\">&nbsp;</td>\n"
				+ "                <td align=\"center\">&nbsp;</td><td align=\"center\">&nbsp;</td><td align=\"center\">&nbsp;</td><td align=\"center\">&nbsp;</td><td align=\"center\">&nbsp;</td><td align=\"center\">&nbsp;</td>\n"
				+ "                <td align=\"center\">&nbsp;</td><td align=\"center\">&nbsp;</td><td align=\"center\">&nbsp;</td><td align=\"center\">&nbsp;</td><td align=\"center\">&nbsp;</td><td align=\"center\">&nbsp;</td></tr>\n"
				+ "            <tr><td align=\"center\">3</td><td align=\"left\">&nbsp;Kegiatan 3</td>\n"
				+ "                <td align=\"center\">&nbsp;</td><td align=\"center\">&nbsp;</td><td align=\"center\">&nbsp;</td><td align=\"center\">&nbsp;</td><td align=\"center\">&nbsp;</td><td align=\"center\">&nbsp;</td>\n"
				+ "                <td align=\"center\">&nbsp;</td><td align=\"center\">&nbsp;</td><td align=\"center\">&nbsp;</td><td align=\"center\">&nbsp;</td><td align=\"center\">&nbsp;</td><td align=\"center\">&nbsp;</td>\n"
				+ "                <td align=\"center\">&nbsp;</td><td align=\"center\">&nbsp;</td><td align=\"center\">&nbsp;</td><td align=\"center\">&nbsp;</td><td align=\"center\">&nbsp;</td><td align=\"center\">&nbsp;</td></tr>\n"
				+ "            <tr><td align=\"center\">...</td><td align=\"left\">&nbsp;..........</td>\n"
				+ "                <td align=\"center\">&nbsp;</td><td align=\"center\">&nbsp;</td><td align=\"center\">&nbsp;</td><td align=\"center\">&nbsp;</td><td align=\"center\">&nbsp;</td><td align=\"center\">&nbsp;</td>\n"
				+ "                <td align=\"center\">&nbsp;</td><td align=\"center\">&nbsp;</td><td align=\"center\">&nbsp;</td><td align=\"center\">&nbsp;</td><td align=\"center\">&nbsp;</td><td align=\"center\">&nbsp;</td>\n"
				+ "                <td align=\"center\">&nbsp;</td><td align=\"center\">&nbsp;</td><td align=\"center\">&nbsp;</td><td align=\"center\">&nbsp;</td><td align=\"center\">&nbsp;</td><td align=\"center\">&nbsp;</td></tr>\n"
				+ "            <tr><td align=\"center\">...</td><td align=\"left\">&nbsp;..........</td>\n"
				+ "                <td align=\"center\">&nbsp;</td><td align=\"center\">&nbsp;</td><td align=\"center\">&nbsp;</td><td align=\"center\">&nbsp;</td><td align=\"center\">&nbsp;</td><td align=\"center\">&nbsp;</td>\n"
				+ "                <td align=\"center\">&nbsp;</td><td align=\"center\">&nbsp;</td><td align=\"center\">&nbsp;</td><td align=\"center\">&nbsp;</td><td align=\"center\">&nbsp;</td><td align=\"center\">&nbsp;</td>\n"
				+ "                <td align=\"center\">&nbsp;</td><td align=\"center\">&nbsp;</td><td align=\"center\">&nbsp;</td><td align=\"center\">&nbsp;</td><td align=\"center\">&nbsp;</td><td align=\"center\">&nbsp;</td></tr>\n"
				+ "            <tr><td align=\"center\">n</td><td align=\"left\">&nbsp;Kegiatan n</td>\n"
				+ "                <td align=\"center\">&nbsp;</td><td align=\"center\">&nbsp;</td><td align=\"center\">&nbsp;</td><td align=\"center\">&nbsp;</td><td align=\"center\">&nbsp;</td><td align=\"center\">&nbsp;</td>\n"
				+ "                <td align=\"center\">&nbsp;</td><td align=\"center\">&nbsp;</td><td align=\"center\">&nbsp;</td><td align=\"center\">&nbsp;</td><td align=\"center\">&nbsp;</td><td align=\"center\">&nbsp;</td>\n"
				+ "                <td align=\"center\">&nbsp;</td><td align=\"center\">&nbsp;</td><td align=\"center\">&nbsp;</td><td align=\"center\">&nbsp;</td><td align=\"center\">&nbsp;</td><td align=\"center\">&nbsp;</td></tr>\n"
				+ "        </tbody></table>\n" + "         &nbsp;<br>\n" + "\n" + "    </div>";

		s += "<div class=\"content-frame\" style=\"width:625px;\">\n"
				+ "        <p class=\"font-TitleContent\">Format Susunan Organisasi Tim</p>\n"
				+ "        <p class=\"font-IsiBab\">Format Susunan Organisasi Tim Peneliti/Pelaksana dan Pembagian Tugas</p>\n"
				+ "        \n" + "        <table width=\"620\" border=\"1\" cellpadding=\"3\" class=\"font-IsiBab\">\n"
				+ "                   \n"
				+ "            <tbody><tr><td align=\"center\"><b>No</b></td><td align=\"center\"><b>Nama / NIDN</b></td><td align=\"center\"><b>Instansi Asal</b></td>\n"
				+ "                <td align=\"center\"><b>Bidang Ilmu</b> </td><td align=\"center\" width=\"120\"><b>Alokasi Waktu (jam/minggu)</b></td>\n"
				+ "                <td align=\"center\" width=\"120\"><b>Uraian Tugas</b></td></tr>\n"
				+ "            <tr><td align=\"center\"><b>1.</b></td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>\n"
				+ "            <tr><td align=\"center\"><b>2.</b></td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>\n"
				+ "            <tr><td align=\"center\"><b>...</b></td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>\n"
				+ "            <tr><td align=\"center\"><b>...</b></td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>\n"
				+ "            <tr><td align=\"center\"><b>n</b></td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>\n"
				+ "\n" + "        </tbody></table>\n" + "       \n" + "\n" + "    </div>";

		s += "<div class=\"content-frame\" style=\"width:625px;\">\n"
				+ "        <p class=\"font-TitleContent\">Format Biodata</p>\n"
				+ "        <p class=\"font-IsiBab\">Format Biodata Ketua/Anggota Tim Peneliti/Pelaksana</p>\n"
				+ "        \n" + "        <p class=\"font-IsiBab\"><b>A.  Identitas Diri</b></p>\n"
				+ "        <table width=\"620\" border=\"1\" cellpadding=\"2\" class=\"font-IsiBab\">              \n"
				+ "            <tbody><tr><td align=\"center\" width=\"20\">1</td><td width=\"250\">&nbsp;Nama Lengkap (dengan gelar)</td><td width=\"350\">&nbsp;</td></tr>\n"
				+ "            <tr><td align=\"center\">2</td><td>&nbsp;Jenis Kelamin</td><td>&nbsp;L/P</td></tr>\n"
				+ "            <tr><td align=\"center\">3</td><td>&nbsp;Jabatan Fungsional</td><td>&nbsp;</td></tr>\n"
				+ "            <tr><td align=\"center\">4</td><td>&nbsp;NIP/NIK/Identitas lainnya</td><td>&nbsp;</td></tr>\n"
				+ "            <tr><td align=\"center\">5</td><td>&nbsp;NIDN</td><td>&nbsp;</td></tr>\n"
				+ "            <tr><td align=\"center\">6</td><td>&nbsp;Tempat, Tanggal Lahir</td><td>&nbsp;</td></tr>\n"
				+ "            <tr><td align=\"center\">7</td><td>&nbsp;E-mail</td><td>&nbsp;</td></tr>\n"
				+ "            <tr><td align=\"center\">8</td><td>&nbsp;Nomor Telepon/HP</td><td>&nbsp;</td></tr>\n"
				+ "            <tr><td align=\"center\">9</td><td>&nbsp;Alamat Kantor</td><td>&nbsp;</td></tr>\n"
				+ "            <tr><td align=\"center\">10</td><td>&nbsp;Nomor Telepon/Faks</td><td>&nbsp;</td></tr>\n"
				+ "            <tr><td align=\"center\">11</td><td>&nbsp;Lulusan yang Telah Dihasilkan</td><td>&nbsp;S-1 = ... orang; S-2 = ... orang;  S-3 = ... orang </td></tr>\n"
				+ "            <tr><td align=\"center\">12</td><td>&nbsp;Nomor Telepon/Faks</td><td>&nbsp;</td></tr>\n"
				+ "            <tr><td align=\"center\" rowspan=\"4\">13</td><td rowspan=\"4\">&nbsp;Mata Kuliah yang Diampu</td><td>&nbsp;1</td></tr>\n"
				+ "            <tr><td>&nbsp;2</td></tr>\n" + "            <tr><td>&nbsp;3</td></tr>\n"
				+ "            <tr><td>&nbsp;dst</td></tr>\n" + "        </tbody></table>\n"
				+ "        <p class=\"font-IsiBab\"><b>B.  Riwayat Pendidikan</b></p>\n"
				+ "        <table width=\"620\" border=\"1\" cellpadding=\"2\" class=\"font-IsiBab\"><tbody><tr><td align=\"center\" width=\"230\">&nbsp;</td>\n"
				+ "            <td align=\"center\" width=\"120\">S-1</td><td align=\"center\" width=\"120\">S-2</td><td align=\"center\" width=\"120\">S-3</td></tr>\n"
				+ "            <tr><td>&nbsp;Nama Perguruan Tinggi</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>\n"
				+ "            <tr><td>&nbsp;Bidang Ilmu</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>\n"
				+ "            <tr><td>&nbsp;Tahun Masuk-Lulus</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>\n"
				+ "            <tr><td>&nbsp;Judul Skripsi/Tesis/Disertasi</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>\n"
				+ "            <tr><td>&nbsp;Nama Pembimbing/Promotor</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>\n"
				+ "        </tbody></table>\n"
				+ "        <p class=\"font-IsiBab\"><b>C. Pengalaman Penelitian Dalam 5 Tahun Terakhir</b> <br>\n"
				+ "            &nbsp;&nbsp;&nbsp;&nbsp;(Bukan Skripsi, Tesis, maupun Disertasi)</p>\n"
				+ "        <table width=\"620\" border=\"1\" cellpadding=\"2\" class=\"font-IsiBab\">              \n"
				+ "            <tbody><tr><td align=\"center\" width=\"20\" rowspan=\"2\">No.</td><td align=\"center\" width=\"50\" rowspan=\"2\">Tahun</td>\n"
				+ "                <td align=\"center\" width=\"350\" rowspan=\"2\">Judul Penelitian</td><td align=\"center\" width=\"200\" colspan=\"2\">Pendanaan</td></tr>\n"
				+ "            <tr><td align=\"center\" width=\"100\">Sumber*</td><td align=\"center\" width=\"100\">Jml (Juta Rp)</td></tr>\n"
				+ "            <tr><td align=\"center\">1</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>\n"
				+ "            <tr><td align=\"center\">2</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>\n"
				+ "            <tr><td align=\"center\">3</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>\n"
				+ "            <tr><td align=\"center\">dst</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>\n"
				+ "        </tbody></table>\n"
				+ "        <p class=\"font-IsiBab\">* Tuliskan sumber pendanaan baik dari skema penelitian DIKTI maupun dari sumber lainnya.</p>\n"
				+ "        <p class=\"font-IsiBab\"><b>D. Pengalaman Pengabdian Kepada Masyarakat dalam 5 Tahun Terakhir</b></p>\n"
				+ "        <table width=\"620\" border=\"1\" cellpadding=\"2\" class=\"font-IsiBab\">              \n"
				+ "            <tbody><tr><td align=\"center\" width=\"20\" rowspan=\"2\">No.</td><td align=\"center\" width=\"50\" rowspan=\"2\">Tahun</td>\n"
				+ "                <td align=\"center\" width=\"350\" rowspan=\"2\">Judul Pengabdian Kepada Masyarakat</td><td align=\"center\" width=\"200\" colspan=\"2\">Pendanaan</td></tr>\n"
				+ "            <tr><td align=\"center\" width=\"100\">Sumber*</td><td align=\"center\" width=\"100\">Jml (Juta Rp)</td></tr>\n"
				+ "            <tr><td align=\"center\">1</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>\n"
				+ "            <tr><td align=\"center\">2</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>\n"
				+ "            <tr><td align=\"center\">3</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>\n"
				+ "            <tr><td align=\"center\">dst</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>\n"
				+ "        </tbody></table>\n"
				+ "        <p class=\"font-IsiBab\">* Tuliskan sumber pendanaan baik dari skema pengabdian kepada masyarakat DIKTI maupun dari sumber lainnya.</p>\n"
				+ "        <p class=\"font-IsiBab\"><b>E. Publikasi Artikel Ilmiah Dalam Jurnal dalam 5 Tahun Terakhir</b></p>\n"
				+ "        <table width=\"620\" border=\"1\" cellpadding=\"2\" class=\"font-IsiBab\">              \n"
				+ "            <tbody><tr><td align=\"center\" width=\"20\">No.</td><td align=\"center\" width=\"300\">Judul Artikel Ilmiah</td>\n"
				+ "                <td align=\"center\" width=\"150\">Nama Jurnal</td><td align=\"center\" width=\"150\">Volume/Nomor/Tahun</td></tr>\n"
				+ "            <tr><td align=\"center\">1</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>\n"
				+ "            <tr><td align=\"center\">2</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>\n"
				+ "            <tr><td align=\"center\">3</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>\n"
				+ "            <tr><td align=\"center\">dst</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>\n"
				+ "        </tbody></table>\n"
				+ "        <p class=\"font-IsiBab\"><b>F. Pemakalah Seminar Ilmiah (<i>Oral Presentation</i>) dalam 5 Tahun Terakhir</b></p>\n"
				+ "        <table width=\"620\" border=\"1\" cellpadding=\"2\" class=\"font-IsiBab\">              \n"
				+ "            <tbody><tr><td align=\"center\" width=\"20\">No.</td><td align=\"center\" width=\"200\">Nama Pertemuan Ilmiah / Seminar</td>\n"
				+ "                <td align=\"center\" width=\"250\">Judul Artikel Ilmiah</td><td align=\"center\" width=\"150\">Waktu dan Tempat</td></tr>\n"
				+ "            <tr><td align=\"center\">1</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>\n"
				+ "            <tr><td align=\"center\">2</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>\n"
				+ "            <tr><td align=\"center\">3</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>\n"
				+ "            <tr><td align=\"center\">dst</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>\n"
				+ "        </tbody></table>\n"
				+ "        <p class=\"font-IsiBab\"><b>G. Karya Buku dalam 5 Tahun Terakhir</b></p>\n"
				+ "        <table width=\"620\" border=\"1\" cellpadding=\"2\" class=\"font-IsiBab\">              \n"
				+ "            <tbody><tr><td align=\"center\" width=\"20\">No.</td><td align=\"center\" width=\"300\">Judul Buku</td>\n"
				+ "                <td align=\"center\" width=\"70\">Tahun</td><td align=\"center\" width=\"80\">Jumlah Halaman</td>\n"
				+ "                <td align=\"center\" width=\"150\">Penerbit</td></tr>\n"
				+ "            <tr><td align=\"center\">1</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>\n"
				+ "            <tr><td align=\"center\">2</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>\n"
				+ "            <tr><td align=\"center\">3</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>\n"
				+ "            <tr><td align=\"center\">dst</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>\n"
				+ "        </tbody></table>\n"
				+ "        <p class=\"font-IsiBab\"><b> H.  Perolehan HKI dalam 5-10 Tahun Terakhir</b></p>\n"
				+ "        <table width=\"620\" border=\"1\" cellpadding=\"2\" class=\"font-IsiBab\">              \n"
				+ "            <tbody><tr><td align=\"center\" width=\"20\">No.</td><td align=\"center\" width=\"300\">Judul/Tema  HKI</td>\n"
				+ "                <td align=\"center\" width=\"70\">Tahun</td><td align=\"center\" width=\"80\">Jenis</td>\n"
				+ "                <td align=\"center\" width=\"150\">Nomor P/ID</td></tr>\n"
				+ "            <tr><td align=\"center\">1</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>\n"
				+ "            <tr><td align=\"center\">2</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>\n"
				+ "            <tr><td align=\"center\">3</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>\n"
				+ "            <tr><td align=\"center\">dst</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>\n"
				+ "        </tbody></table>\n"
				+ "        <p class=\"font-IsiBab\"><b> I. 	Pengalaman Merumuskan Kebijakan Publik/Rekayasa Sosial Lainnya dalam 5 Tahun Terakhir</b></p>\n"
				+ "        <table width=\"620\" border=\"1\" cellpadding=\"2\" class=\"font-IsiBab\">              \n"
				+ "            <tbody><tr><td align=\"center\" width=\"20\">No.</td><td align=\"center\" width=\"300\">Judul/Tema/Jenis Rekayasa Sosial Lainnya yang Telah Diterapkan</td>\n"
				+ "                <td align=\"center\" width=\"70\">Tahun</td><td align=\"center\" width=\"80\">Tempat Penerapan</td>\n"
				+ "                <td align=\"center\" width=\"150\">Respon Masyarakat</td></tr>\n"
				+ "            <tr><td align=\"center\">1</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>\n"
				+ "            <tr><td align=\"center\">2</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>\n"
				+ "            <tr><td align=\"center\">3</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>\n"
				+ "            <tr><td align=\"center\">dst</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>\n"
				+ "        </tbody></table>\n"
				+ "        <p class=\"font-IsiBab\"><b>J.  Penghargaan dalam 10 tahun Terakhir (dari pemerintah, asosiasi atau institusi lainnya)</b></p>\n"
				+ "        <table width=\"620\" border=\"1\" cellpadding=\"2\" class=\"font-IsiBab\">              \n"
				+ "            <tbody><tr><td align=\"center\" width=\"20\">No.</td><td align=\"center\" width=\"300\">Jenis Penghargaan</td>\n"
				+ "                <td align=\"center\" width=\"200\">Institusi Pemberi Penghargaan</td><td align=\"center\" width=\"100\">Tahun </td></tr>\n"
				+ "            <tr><td align=\"center\">1</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>\n"
				+ "            <tr><td align=\"center\">2</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>\n"
				+ "            <tr><td align=\"center\">3</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>\n"
				+ "            <tr><td align=\"center\">dst</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>\n"
				+ "        </tbody></table>\n" + "        \n"
				+ "        <p class=\"font-IsiBab\">Semua data yang saya isikan dan tercantum dalam biodata ini adalah benar dan dapat \n"
				+ "            dipertanggungjawabkan secara hukum. Apabila di kemudian hari ternyata dijumpai ketidak-sesuaian dengan kenyataan, \n"
				+ "            saya sanggup menerima sanksi.  </p>\n"
				+ "        <p class=\"font-IsiBab\">Demikian biodata ini saya buat dengan sebenarnya untuk memenuhi salah satu persyaratan \n"
				+ "            dalam pengajuan Hibah ..................................................... </p>\n"
				+ "\n" + "        <table width=\"620\" border=\"0\" cellpadding=\"1\">\n"
				+ "            <tbody><tr><td width=\"400\" class=\"font-IsiBab\">&nbsp;</td>\n"
				+ "                <td class=\"font-IsiBab\">Kota, tanggal-bulan-tahun</td></tr>\n"
				+ "            <tr><td width=\"400\" class=\"font-IsiBab\">&nbsp;</td>\n"
				+ "                <td class=\"font-IsiBab\">Pengusul,</td></tr>\n"
				+ "            <tr><td width=\"400\" class=\"font-IsiBab\">&nbsp;</td>\n"
				+ "                <td class=\"font-IsiBab\">&nbsp;</td></tr>\n"
				+ "            <tr><td width=\"400\" class=\"font-IsiBab\">&nbsp;</td>\n"
				+ "                <td class=\"font-IsiBab\">tanda tangan</td></tr>\n"
				+ "            <tr><td width=\"400\" class=\"font-IsiBab\">&nbsp;</td>\n"
				+ "                <td class=\"font-IsiBab\">&nbsp;</td></tr>\n"
				+ "            <tr><td width=\"400\" class=\"font-IsiBab\">&nbsp;</td>\n"
				+ "                <td class=\"font-IsiBab\">( Nama Lengkap )</td></tr>\n" + "       </tbody></table>\n"
				+ "\n" + "    </div>";

		s += "<div class=\"content-frame\" style=\"width:625px;\">\n"
				+ "        <p class=\"font-TitleContent\">Format Surat Pernyataan Ketua Peneliti/Pelaksana</p>\n"
				+ "         &nbsp; <br>\n"
				+ "        <p class=\"font_Judul1\" align=\"center\"><b>KOP PERGURUAN TINGGI</b></p>\n"
				+ "        <hr>\n" + "        &nbsp; <br>\n"
				+ "        <p class=\"font-IsiBab\" align=\"center\"><b>SURAT PERNYATAAN KETUA PELITI/PELAKSANA</b></p>\n"
				+ "\n" + "        <table width=\"620\" border=\"0\" cellpadding=\"1\">\n"
				+ "            <tbody><tr><td class=\"font-IsiBab\" colspan=\"3\">Yang bertanda tangan di bawah ini: </td>\n"
				+ "            </tr><tr><td class=\"font-IsiBab\">Nama</td><td class=\"font-IsiBab\"> : </td>\n"
				+ "                <td class=\"font-IsiBab\"> .................................................................. </td></tr>\n"
				+ "            <tr><td class=\"font-IsiBab\">NIDN</td><td class=\"font-IsiBab\"> : </td>\n"
				+ "                <td class=\"font-IsiBab\"> .................................................................. </td></tr>\n"
				+ "            <tr><td class=\"font-IsiBab\">Pangkat / Golongan</td><td class=\"font-IsiBab\"> : </td>\n"
				+ "                <td class=\"font-IsiBab\"> .................................................................. </td></tr>\n"
				+ "            <tr><td class=\"font-IsiBab\">Jabatan Fungsional</td><td class=\"font-IsiBab\"> : </td>\n"
				+ "                <td class=\"font-IsiBab\"> .................................................................. </td></tr>\n"
				+ "        </tbody></table>\n" + "\n"
				+ "        <p class=\"font-IsiBab\">Dengan ini menyatakan bahwa proposal penelitian saya dengan judul:</p>\n"
				+ "        <p class=\"font-IsiBab\">........................................................................................................\n"
				+ "            ..........................................</p>\n"
				+ "        <p class=\"font-IsiBab\">........................................................................................................\n"
				+ "            ..........................................</p>\n"
				+ "        <p class=\"font-IsiBab\">yang diusulkan dalam skema .....(tulis skema) ...... untuk tahun anggaran ................ \n"
				+ "            <b>bersifat original dan belum pernah dibiayai oleh lembaga/sumber dana lain.</b> </p>\n"
				+ "        <p class=\"font-IsiBab\">Bilamana di kemudian hari ditemukan ketidaksesuaian dengan pernyataan ini, maka saya bersedia \n"
				+ "            dituntut dan diproses sesuai dengan ketentuan yang berlaku dan mengembalikan seluruh biaya penelitian yang sudah \n"
				+ "            diterima ke kas negara. </p>\n"
				+ "        <p class=\"font-IsiBab\">Demikian pernyataan ini dibuat dengan sesungguhnya dan dengan sebenar-benarnya.</p>\n"
				+ "\n" + "    \n" + "        <table width=\"620\" border=\"0\" cellpadding=\"1\">\n"
				+ "            <tbody><tr><td width=\"400\" class=\"font-IsiBab\">&nbsp;</td>\n"
				+ "                <td class=\"font-IsiBab\">Kota, tanggal-bulan-tahun</td></tr>\n"
				+ "            <tr><td width=\"400\" class=\"font-IsiBab\">Mengetahui</td>\n"
				+ "                <td class=\"font-IsiBab\">Yang menyatakan,</td></tr>\n"
				+ "            <tr><td width=\"400\" class=\"font-IsiBab\">Ketua Lembaga,</td>\n"
				+ "                <td class=\"font-IsiBab\">&nbsp;</td></tr>\n"
				+ "            <tr><td width=\"400\" class=\"font-IsiBab\">&nbsp;</td>\n"
				+ "                <td class=\"font-IsiBab\">meterai Rp6000</td></tr>\n"
				+ "            <tr><td width=\"400\" class=\"font-IsiBab\">Cap dan tanda tangan</td>\n"
				+ "                <td class=\"font-IsiBab\">tanda tangan</td></tr>\n"
				+ "            <tr><td width=\"400\" class=\"font-IsiBab\">&nbsp;</td>\n"
				+ "                <td class=\"font-IsiBab\">&nbsp;</td></tr>\n"
				+ "            <tr><td width=\"400\" class=\"font-IsiBab\">( Nama Lengkap )</td>\n"
				+ "                <td class=\"font-IsiBab\">( Nama Lengkap )</td></tr>\n"
				+ "            <tr><td width=\"400\" class=\"font-IsiBab\">NIP/NIK</td>\n"
				+ "                <td class=\"font-IsiBab\">NIP/NIK</td></tr>\n" + "       </tbody></table>\n" + "\n"
				+ "    </div>";

		s += "<div class=\"content-frame\" style=\"width:625px;\">\n"
				+ "        <p class=\"font-TitleContent\">Format Catatan Harian (<i>Logbook</i>)</p>\n"
				+ "        <table width=\"620\" border=\"1\" cellpadding=\"3\" class=\"font-IsiBab\">\n"
				+ "                   \n"
				+ "            <tbody><tr><td align=\"center\" width=\"30\" height=\"30\"><b>No</b></td><td align=\"center\" width=\"70\"><b>Tanggal</b></td><td align=\"center\"><b>Kegiatan</b></td></tr>\n"
				+ "            <tr><td align=\"center\" height=\"80\">1.</td><td align=\"center\">&nbsp;.../.../...</td>\n"
				+ "                <td>&nbsp;Catatan: ......................................................................................................<br>\n"
				+ "                 &nbsp; <br>\n"
				+ "                 &nbsp;Dokumen Pendukung: [...] [...] [...] [...] [...] [...]</td></tr>\n"
				+ "            <tr><td align=\"center\" height=\"80\">2.</td><td align=\"center\">&nbsp;.../.../...</td>\n"
				+ "                <td>&nbsp;Catatan: ......................................................................................................<br>\n"
				+ "                 &nbsp; <br>\n"
				+ "                 &nbsp;Dokumen Pendukung: [...] [...] [...] [...] [...] [...]</td></tr>\n"
				+ "            <tr><td align=\"center\" height=\"80\">3.</td><td align=\"center\">&nbsp;.../.../...</td>\n"
				+ "                <td>&nbsp;Catatan: ......................................................................................................<br>\n"
				+ "                 &nbsp; <br>\n"
				+ "                 &nbsp;Dokumen Pendukung: [...] [...] [...] [...] [...] [...]</td></tr>\n"
				+ "            <tr><td align=\"center\" height=\"80\">dst.</td><td align=\"center\">dst.</td><td>dan seterusnya...</td></tr>\n"
				+ "            <tr><td align=\"center\" height=\"80\">&nbsp;</td><td align=\"center\">&nbsp;</td><td>&nbsp;</td></tr>\n"
				+ "            <tr><td align=\"center\" height=\"80\">&nbsp;</td><td align=\"center\">&nbsp;</td><td>&nbsp;</td></tr>\n"
				+ "            <tr><td align=\"center\" height=\"80\">&nbsp;</td><td align=\"center\">&nbsp;</td><td>&nbsp;</td></tr>\n"
				+ "        </tbody></table>\n"
				+ "		<p class=\"font-IsiBab\"><b>Keterangan:</b> hasil yang dicapai pada setiap kegiatan (foto, grafik, tabel, catatan, dokumen, \n"
				+ "            data dan sebagainya) dilampirkan (diunggah).</p>\n" + "    </div>";

		s += "<div class=\"content-frame\" style=\"width:625px;\">\n"
				+ "        <p class=\"font-TitleContent\">Format Laporan Kemajuan</p>\n"
				+ "	<p class=\"font-IsiBab\"><b>a. Sampul Muka Laporan Kemajuan Hibah Penelitian/Pengabdian </b></p>\n"
				+ "	   \n" + "            <table width=\"620\" border=\"1\" cellpadding=\"10\" height=\"700\">\n"
				+ "                <tbody><tr><td>\n"
				+ "                <table width=\"320\" border=\"1\" cellpadding=\"3\" height=\"30\" align=\"right\">\n"
				+ "    \n" + "                </table>\n" + "               \n"
				+ "                <p class=\"font-IsiBab\" align=\"center\">&nbsp;</p>\n"
				+ "                <p class=\"font-IsiBab\" align=\"center\">&nbsp;</p>\n"
				+ "                <p class=\"font-IsiBab\" align=\"center\">&nbsp;</p>\n"
				+ "                <p class=\"font-IsiBab\" align=\"center\"><b>LAPORAN KEMAJUAN</b></p>\n"
				+ "                <p class=\"font-IsiBab\" align=\"center\"><b>.......................................................*</b></p>\n"
				+ "                <p class=\"font-IsiBab\" align=\"center\">&nbsp;</p>\n"
				+ "                <p class=\"font-IsiBab\" align=\"center\">&nbsp;</p>\n"
				+ "                <p class=\"font-IsiBab\" align=\"center\">&nbsp;</p>\n"
				+ "                <p class=\"font-IsiBab\" align=\"center\">&nbsp;</p>\n"
				+ "                <p class=\"font-IsiBab\" align=\"center\"><b>Logo Perguruan Tinggi</b></p>\n"
				+ "                <p class=\"font-IsiBab\" align=\"center\">&nbsp;</p>\n"
				+ "                <p class=\"font-IsiBab\" align=\"center\">&nbsp;</p>\n"
				+ "                <p class=\"font-IsiBab\" align=\"center\">&nbsp;</p>\n"
				+ "                <p class=\"font-IsiBab\" align=\"center\">&nbsp;</p>\n"
				+ "                <p class=\"font-IsiBab\" align=\"center\"><b>JUDUL</b></p>\n"
				+ "                <p class=\"font-IsiBab\" align=\"center\">&nbsp;</p>\n"
				+ "                <p class=\"font-IsiBab\" align=\"center\"><b>Tahun ke ........ dari rencana ....... tahun </b></p>\n"
				+ "                <p class=\"font-IsiBab\" align=\"center\">&nbsp;</p>\n"
				+ "                <p class=\"font-IsiBab\" align=\"center\">&nbsp;</p>\n"
				+ "                <p class=\"font-IsiBab\" align=\"center\"><b>Ketua Tim Peneliti</b></p>\n"
				+ "                <p class=\"font-IsiBab\" align=\"center\"><b>(Nama lengkap dan NIDN)</b></p>\n"
				+ "                <p class=\"font-IsiBab\" align=\"center\">&nbsp;</p>\n"
				+ "                <p class=\"font-IsiBab\" align=\"center\">&nbsp;</p>\n"
				+ "                <p class=\"font-IsiBab\" align=\"center\">&nbsp;</p>\n"
				+ "                <p class=\"font-IsiBab\" align=\"center\"><b>PERGURUAN TINGGI PENGUSUL</b></p>\n"
				+ "                <p class=\"font-IsiBab\" align=\"center\"><b> Bulan dan Tahun</b></p>\n"
				+ "            \n" + "                </td></tr>\n" + "            </tbody></table>\n"
				+ "            <p class=\"font-IsiBab\">* Tulis skema penelitian/pengabdian. <br>\n"
				+ "			Warna sampul sama dengan warna sampul proposal masing-masing skema. </p>\n"
				+ "            <p class=\"font-IsiBab\" align=\"center\">&nbsp;</p>\n" + "\n"
				+ "    <p class=\"font-IsiBab\"><b>b.  Format Halaman Pengesahan Laporan Kemajuan</b></p>\n" + "\n"
				+ "            <table width=\"620\" border=\"1\" cellpadding=\"10\" height=\"700\">\n"
				+ "                <tbody><tr><td>\n"
				+ "                <p class=\"font-IsiBab\" align=\"center\"><b>HALAMAN PENGESAHAN</b></p>\n"
				+ "                <table width=\"570\" border=\"0\" cellpadding=\"1\">\n"
				+ "                    <tbody><tr><td class=\"font-IsiBab\">Judul Penelitian</td><td class=\"font-IsiBab\"> : </td>\n"
				+ "                        <td class=\"font-IsiBab\"> ................................................................................................... </td></tr>\n"
				+ " 						<tr><td class=\"font-IsiBab\">Peneliti / Pelaksana</td><td class=\"font-IsiBab\"> : </td>\n"
				+ "                        <td class=\"font-IsiBab\"> &nbsp; </td></tr>\n"
				+ "                    <tr><td class=\"font-IsiBab\">&nbsp;&nbsp;Nama Lengkap</td><td class=\"font-IsiBab\"> : </td>\n"
				+ "                        <td class=\"font-IsiBab\"> .................................................................................................... </td></tr>\n"
				+ "                    <tr><td class=\"font-IsiBab\">&nbsp;&nbsp;NIDN</td><td class=\"font-IsiBab\"> : </td>\n"
				+ "                        <td class=\"font-IsiBab\"> .................................................................................................... </td></tr>\n"
				+ "                    <tr><td class=\"font-IsiBab\">&nbsp;&nbsp;Jabatan Fungsional</td><td class=\"font-IsiBab\"> : </td>\n"
				+ "                        <td class=\"font-IsiBab\"> .................................................................................................... </td></tr>\n"
				+ "                    <tr><td class=\"font-IsiBab\">&nbsp;&nbsp;Program Studi</td><td class=\"font-IsiBab\"> : </td>\n"
				+ "                        <td class=\"font-IsiBab\"> .................................................................................................... </td></tr>\n"
				+ "                    <tr><td class=\"font-IsiBab\">&nbsp;&nbsp;Nomor HP</td><td class=\"font-IsiBab\"> : </td>\n"
				+ "                        <td class=\"font-IsiBab\"> .................................................................................................... </td></tr>\n"
				+ "                    <tr><td class=\"font-IsiBab\">&nbsp;&nbsp;Alamat surel (e-mail)</td><td class=\"font-IsiBab\"> : </td>\n"
				+ "                        <td class=\"font-IsiBab\"> .................................................................................................... </td></tr>\n"
				+ "                    <tr><td class=\"font-IsiBab\">Anggota (1)</td><td class=\"font-IsiBab\"> : </td>\n"
				+ "                        <td class=\"font-IsiBab\"> &nbsp; </td></tr>\n"
				+ "                    <tr><td class=\"font-IsiBab\">&nbsp;&nbsp;Nama Lengkap</td><td class=\"font-IsiBab\"> : </td>\n"
				+ "                        <td class=\"font-IsiBab\"> .................................................................................................... </td></tr>\n"
				+ "                    <tr><td class=\"font-IsiBab\">&nbsp;&nbsp;NIDN</td><td class=\"font-IsiBab\"> : </td>\n"
				+ "                        <td class=\"font-IsiBab\"> .................................................................................................... </td></tr>\n"
				+ "                    <tr><td class=\"font-IsiBab\">&nbsp;&nbsp;Perguruan Tinggi</td><td class=\"font-IsiBab\"> : </td>\n"
				+ "                        <td class=\"font-IsiBab\"> .................................................................................................... </td></tr>\n"
				+ "                    <tr><td class=\"font-IsiBab\">Anggota(2)</td><td class=\"font-IsiBab\"> : </td>\n"
				+ "                        <td class=\"font-IsiBab\"> &nbsp; </td></tr>\n"
				+ "                    <tr><td class=\"font-IsiBab\">&nbsp;&nbsp;Nama Lengkap</td><td class=\"font-IsiBab\"> : </td>\n"
				+ "                        <td class=\"font-IsiBab\"> .................................................................................................... </td></tr>\n"
				+ "                    <tr><td class=\"font-IsiBab\">&nbsp;&nbsp;NIDN</td><td class=\"font-IsiBab\"> : </td>\n"
				+ "                        <td class=\"font-IsiBab\"> .................................................................................................... </td></tr>\n"
				+ "                    <tr><td class=\"font-IsiBab\">&nbsp;&nbsp;Perguruan Tinggi</td><td class=\"font-IsiBab\"> : </td>\n"
				+ "                        <td class=\"font-IsiBab\"> .................................................................................................... </td></tr>\n"
				+ "					<tr><td class=\"font-IsiBab\">Anggota (ke-n)</td><td class=\"font-IsiBab\"> : </td>\n"
				+ "                        <td class=\"font-IsiBab\"> &nbsp; </td></tr>\n"
				+ "                    <tr><td class=\"font-IsiBab\">&nbsp;&nbsp;Nama Lengkap</td><td class=\"font-IsiBab\"> : </td>\n"
				+ "                        <td class=\"font-IsiBab\"> .................................................................................................... </td></tr>\n"
				+ "                    <tr><td class=\"font-IsiBab\">&nbsp;&nbsp;NIDN</td><td class=\"font-IsiBab\"> : </td>\n"
				+ "                        <td class=\"font-IsiBab\"> .................................................................................................... </td></tr>\n"
				+ "                    <tr><td class=\"font-IsiBab\">&nbsp;&nbsp;Perguruan Tinggi</td><td class=\"font-IsiBab\"> : </td>\n"
				+ "                        <td class=\"font-IsiBab\"> .................................................................................................... </td></tr>\n"
				+ "					<tr><td class=\"font-IsiBab\">Institusi Mitra (jika ada)</td><td class=\"font-IsiBab\"> : </td>\n"
				+ "                        <td class=\"font-IsiBab\"> &nbsp; </td></tr>\n"
				+ "                    <tr><td class=\"font-IsiBab\">&nbsp;&nbsp;Nama Institusi Mitra</td><td class=\"font-IsiBab\"> : </td>\n"
				+ "                        <td class=\"font-IsiBab\"> .................................................................................................... </td></tr>\n"
				+ "                    <tr><td class=\"font-IsiBab\">&nbsp;&nbsp;Alamat</td><td class=\"font-IsiBab\"> : </td>\n"
				+ "                        <td class=\"font-IsiBab\"> .................................................................................................... </td></tr>\n"
				+ "                    <tr><td class=\"font-IsiBab\">&nbsp;&nbsp;Penanggung Jawab</td><td class=\"font-IsiBab\"> : </td>\n"
				+ "                        <td class=\"font-IsiBab\"> .................................................................................................... </td></tr>                          \n"
				+ "					<tr><td class=\"font-IsiBab\">Tahun Pelaksanaan</td><td class=\"font-IsiBab\"> : </td>\n"
				+ "                        <td class=\"font-IsiBab\"> Tahun ke ........ dari rencana ....... tahun </td></tr>\n"
				+ "                    <tr><td class=\"font-IsiBab\">Biaya Tahun Berjalan</td><td class=\"font-IsiBab\"> : </td>\n"
				+ "                        <td class=\"font-IsiBab\"> Rp ................... </td></tr>\n"
				+ "                    <tr><td class=\"font-IsiBab\">Biaya Keseluruhan</td><td class=\"font-IsiBab\"> : </td>\n"
				+ "                        <td class=\"font-IsiBab\"> Rp ................... </td></tr>\n"
				+ "                </tbody></table>\n" + "                &nbsp; <br>\n"
				+ "                <table width=\"570\" border=\"0\" cellpadding=\"1\">\n"
				+ "                    <tbody><tr><td width=\"380\" class=\"font-IsiBab\">Mengetahui</td>\n"
				+ "                        <td class=\"font-IsiBab\">Kota, tanggal-bulan-tahun</td></tr>\n"
				+ "                    <tr><td width=\"380\" class=\"font-IsiBab\">Ketua Lembaga penelitian/pengabdian*</td>\n"
				+ "                        <td class=\"font-IsiBab\">Ketua Peneliti,</td></tr>\n"
				+ "                    <tr><td width=\"380\" class=\"font-IsiBab\">&nbsp;</td>\n"
				+ "                        <td class=\"font-IsiBab\">&nbsp;</td></tr>\n"
				+ "                    <tr><td width=\"380\" class=\"font-IsiBab\">tanda tangan</td>\n"
				+ "                        <td class=\"font-IsiBab\">tanda tangan</td></tr>\n"
				+ "                    <tr><td width=\"380\" class=\"font-IsiBab\">&nbsp;</td>\n"
				+ "                        <td class=\"font-IsiBab\">&nbsp;</td></tr>\n"
				+ "                    <tr><td width=\"380\" class=\"font-IsiBab\">( Nama Lengkap )</td>\n"
				+ "                        <td class=\"font-IsiBab\">( Nama Lengkap )</td></tr>\n"
				+ "                    <tr><td width=\"380\" class=\"font-IsiBab\">NIP/NIK</td>\n"
				+ "                        <td class=\"font-IsiBab\">NIP/NIK</td></tr>\n"
				+ "                </tbody></table>\n" + "                \n" + "             \n"
				+ "                </td></tr>\n" + "            </tbody></table>   	\n"
				+ "      <p class=\"font-IsiBab\">* Disesuaikan dengan nama lembaga penelitian dan atau pengabdian kepada masyarakat di PT</p>\n"
				+ "       <p class=\"font-IsiBab\">&nbsp;</p>\n"
				+ "      <p class=\"font-IsiBab\"><b>c.  Sistematika Laporan Kemajuan</b></p>\n" + "\n"
				+ "      <table width=\"620\" border=\"1\" cellpadding=\"3\">\n"
				+ "                    <tbody><tr height=\"30\"><td width=\"310\" class=\"font-IsiBab\"><b>Laporan Kemajuan Penelitian</b></td>\n"
				+ "                        <td class=\"font-IsiBab\"><b>Laporan Kemajuan Pengabdian</b></td></tr>\n"
				+ "                    <tr><td width=\"310\" class=\"font-IsiBab\">HALAMAN SAMPUL</td>\n"
				+ "                        <td class=\"font-IsiBab\">HALAMAN SAMPUL</td></tr>\n"
				+ "                    <tr><td width=\"310\" class=\"font-IsiBab\">HALAMAN PENGESAHAN</td>\n"
				+ "                        <td class=\"font-IsiBab\">HALAMAN PENGESAHAN</td></tr>\n"
				+ "                    <tr><td width=\"310\" class=\"font-IsiBab\">RINGKASAN </td>\n"
				+ "                        <td class=\"font-IsiBab\">RINGKASAN </td></tr>\n"
				+ "                    <tr><td width=\"310\" class=\"font-IsiBab\">PRAKATA </td>\n"
				+ "                        <td class=\"font-IsiBab\">PRAKATA </td></tr>\n"
				+ "                    <tr><td width=\"310\" class=\"font-IsiBab\">DAFTAR ISI </td>\n"
				+ "                        <td class=\"font-IsiBab\">DAFTAR ISI </td></tr>\n"
				+ "                    <tr><td width=\"310\" class=\"font-IsiBab\">DAFTAR TABEL</td>\n"
				+ "                        <td class=\"font-IsiBab\">DAFTAR TABEL</td></tr>\n"
				+ "                    <tr><td width=\"310\" class=\"font-IsiBab\">DAFTAR GAMBAR</td>\n"
				+ "                        <td class=\"font-IsiBab\">DAFTAR GAMBAR</td></tr>\n"
				+ "                    <tr><td width=\"310\" class=\"font-IsiBab\">DAFTAR LAMPIRAN</td>\n"
				+ "                        <td class=\"font-IsiBab\">DAFTAR LAMPIRAN</td></tr>\n"
				+ "                    <tr><td width=\"310\" class=\"font-IsiBab\">BAB 1. PENDAHULUAN </td>\n"
				+ "                        <td class=\"font-IsiBab\">BAB 1. PENDAHULUAN </td></tr>\n"
				+ "                    <tr><td width=\"310\" class=\"font-IsiBab\">BAB 2. TINJAUAN PUSTAKA </td>\n"
				+ "                        <td class=\"font-IsiBab\">BAB 2. TARGET DAN LUARAN </td></tr>\n"
				+ "                    <tr><td width=\"310\" class=\"font-IsiBab\">BAB 3. TUJUAN DAN MANFAAT PENELITIAN</td>\n"
				+ "                        <td class=\"font-IsiBab\">BAB 3. METODE PELAKSANAAN</td></tr>\n"
				+ "                    <tr><td width=\"310\" class=\"font-IsiBab\">BAB 4. METODE PENELITIAN </td>\n"
				+ "                        <td class=\"font-IsiBab\">BAB 4. KELAYAKAN PERGURUAN TINGGI</td></tr>\n"
				+ "                    <tr><td width=\"310\" class=\"font-IsiBab\">BAB 5. HASIL YANG DICAPAI</td>\n"
				+ "                        <td class=\"font-IsiBab\">BAB 5. HASIL YANG DICAPAI </td></tr>\n"
				+ "                    <tr><td width=\"310\" class=\"font-IsiBab\">BAB 6. RENCANA TAHAPAN BERIKUTNYA</td>\n"
				+ "                        <td class=\"font-IsiBab\">BAB 6. RENCANA TAHAPAN BERIKUTNYA</td></tr>\n"
				+ "                    <tr><td width=\"310\" class=\"font-IsiBab\">BAB 7. KESIMPULAN DAN SARAN </td>\n"
				+ "                        <td class=\"font-IsiBab\">BAB 7. KESIMPULAN DAN SARAN </td></tr>\n"
				+ "                    <tr><td width=\"310\" class=\"font-IsiBab\">DAFTAR PUSTAKA</td>\n"
				+ "                        <td class=\"font-IsiBab\">DAFTAR PUSTAKA</td></tr>\n"
				+ "                    <tr><td width=\"310\" class=\"font-IsiBab\">LAMPIRAN <br>\n"
				+ "                        <ul>\n"
				+ "                        <li>Artikel ilmiah (draft, bukti status submission atau reprint), jika ada.</li>\n"
				+ "                        <li>Produk penelitian </li>\n" + "                        </ul></td>\n"
				+ "                        <td class=\"font-IsiBab\">LAMPIRAN <br>\n" + "                        <ul>\n"
				+ "                        <li>Artikel ilmiah (draft, bukti status submission atau reprint), jika ada.</li>\n"
				+ "                        <li>Produk pengabdian </li>\n" + "                        </ul>	\n"
				+ "                        </td></tr>\n" + "                </tbody></table>\n" + "    </div>";

		s += "<div class=\"content-frame\" style=\"width:625px;\">\n"
				+ "        <p class=\"font-TitleContent\">Format Laporan Tahunan/Akhir</p>\n"
				+ "	<p class=\"font-IsiBab\"><b>a. Sampul Muka Laporan Tahunan/Akhir Hibah Penelitian/Pengabdian </b></p>\n"
				+ "	   \n" + "            <table width=\"620\" border=\"1\" cellpadding=\"10\" height=\"600\">\n"
				+ "                <tbody><tr><td>\n" + "                \n" + "               \n"
				+ "                \n" + "                <p class=\"font-IsiBab\" align=\"center\">&nbsp;</p>\n"
				+ "                <p class=\"font-IsiBab\" align=\"center\">&nbsp;</p>\n"
				+ "                <p class=\"font-IsiBab\" align=\"center\"><b>LAPORAN TAHUNAN/AKHIR*</b></p>\n"
				+ "                <p class=\"font-IsiBab\" align=\"center\"><b>.......................................................**</b></p>\n"
				+ "               \n" + "                <p class=\"font-IsiBab\" align=\"center\">&nbsp;</p>\n"
				+ "                <p class=\"font-IsiBab\" align=\"center\">&nbsp;</p>\n"
				+ "                <p class=\"font-IsiBab\" align=\"center\">&nbsp;</p>\n"
				+ "                <p class=\"font-IsiBab\" align=\"center\"><b>Logo Perguruan Tinggi</b></p>\n"
				+ "                \n" + "                <p class=\"font-IsiBab\" align=\"center\">&nbsp;</p>\n"
				+ "                <p class=\"font-IsiBab\" align=\"center\">&nbsp;</p>\n"
				+ "                <p class=\"font-IsiBab\" align=\"center\">&nbsp;</p>\n"
				+ "                <p class=\"font-IsiBab\" align=\"center\"><b>JUDUL</b></p>\n"
				+ "                <p class=\"font-IsiBab\" align=\"center\">&nbsp;</p>\n"
				+ "                <p class=\"font-IsiBab\" align=\"center\"><b>Tahun ke ........ dari rencana ....... tahun </b></p>\n"
				+ "                <p class=\"font-IsiBab\" align=\"center\">&nbsp;</p>\n"
				+ "                <p class=\"font-IsiBab\" align=\"center\">&nbsp;</p>\n"
				+ "                <p class=\"font-IsiBab\" align=\"center\"><b>Ketua Tim Peneliti</b></p>\n"
				+ "                <p class=\"font-IsiBab\" align=\"center\"><b>(Nama lengkap dan NIDN)</b></p>\n"
				+ "                <p class=\"font-IsiBab\" align=\"center\">&nbsp;</p>\n"
				+ "                <p class=\"font-IsiBab\" align=\"center\">&nbsp;</p>\n"
				+ "                <p class=\"font-IsiBab\" align=\"center\">&nbsp;</p>\n"
				+ "                <p class=\"font-IsiBab\" align=\"center\"><b>PERGURUAN TINGGI PENGUSUL</b></p>\n"
				+ "                <p class=\"font-IsiBab\" align=\"center\"><b> Bulan dan Tahun</b></p>\n"
				+ "            \n" + "                </td></tr>\n" + "            </tbody></table>\n"
				+ "            <p class=\"font-IsiBab\">* Pilih salah satu yang sesuai. <br>\n"
				+ "            </p><p class=\"font-IsiBab\">** Tulis skema penelitian/pengabdian. <br>\n"
				+ "			Warna sampul sama dengan warna sampul proposal masing-masing skema. </p>\n"
				+ "            <p class=\"font-IsiBab\" align=\"center\">&nbsp;</p>\n" + "\n"
				+ "    <p class=\"font-IsiBab\"><b>b.  Format Halaman Pengesahan Laporan Tahunan/Akhir</b></p>\n" + "\n"
				+ "            <table width=\"620\" border=\"1\" cellpadding=\"10\" height=\"700\">\n"
				+ "                <tbody><tr><td>\n"
				+ "                <p class=\"font-IsiBab\" align=\"center\"><b>HALAMAN PENGESAHAN</b></p>\n"
				+ "                <table width=\"570\" border=\"0\" cellpadding=\"1\">\n"
				+ "                    <tbody><tr><td class=\"font-IsiBab\">Judul Penelitian</td><td class=\"font-IsiBab\"> : </td>\n"
				+ "                        <td class=\"font-IsiBab\"> ................................................................................................... </td></tr>\n"
				+ " 						<tr><td class=\"font-IsiBab\">Peneliti / Pelaksana</td><td class=\"font-IsiBab\"> : </td>\n"
				+ "                        <td class=\"font-IsiBab\"> &nbsp; </td></tr>\n"
				+ "                    <tr><td class=\"font-IsiBab\">&nbsp;&nbsp;Nama Lengkap</td><td class=\"font-IsiBab\"> : </td>\n"
				+ "                        <td class=\"font-IsiBab\"> .................................................................................................... </td></tr>\n"
				+ "                    <tr><td class=\"font-IsiBab\">&nbsp;&nbsp;NIDN</td><td class=\"font-IsiBab\"> : </td>\n"
				+ "                        <td class=\"font-IsiBab\"> .................................................................................................... </td></tr>\n"
				+ "                    <tr><td class=\"font-IsiBab\">&nbsp;&nbsp;Jabatan Fungsional</td><td class=\"font-IsiBab\"> : </td>\n"
				+ "                        <td class=\"font-IsiBab\"> .................................................................................................... </td></tr>\n"
				+ "                    <tr><td class=\"font-IsiBab\">&nbsp;&nbsp;Program Studi</td><td class=\"font-IsiBab\"> : </td>\n"
				+ "                        <td class=\"font-IsiBab\"> .................................................................................................... </td></tr>\n"
				+ "                    <tr><td class=\"font-IsiBab\">&nbsp;&nbsp;Nomor HP</td><td class=\"font-IsiBab\"> : </td>\n"
				+ "                        <td class=\"font-IsiBab\"> .................................................................................................... </td></tr>\n"
				+ "                    <tr><td class=\"font-IsiBab\">&nbsp;&nbsp;Alamat surel (e-mail)</td><td class=\"font-IsiBab\"> : </td>\n"
				+ "                        <td class=\"font-IsiBab\"> .................................................................................................... </td></tr>\n"
				+ "                    <tr><td class=\"font-IsiBab\">Anggota (1)</td><td class=\"font-IsiBab\"> : </td>\n"
				+ "                        <td class=\"font-IsiBab\"> &nbsp; </td></tr>\n"
				+ "                    <tr><td class=\"font-IsiBab\">&nbsp;&nbsp;Nama Lengkap</td><td class=\"font-IsiBab\"> : </td>\n"
				+ "                        <td class=\"font-IsiBab\"> .................................................................................................... </td></tr>\n"
				+ "                    <tr><td class=\"font-IsiBab\">&nbsp;&nbsp;NIDN</td><td class=\"font-IsiBab\"> : </td>\n"
				+ "                        <td class=\"font-IsiBab\"> .................................................................................................... </td></tr>\n"
				+ "                    <tr><td class=\"font-IsiBab\">&nbsp;&nbsp;Perguruan Tinggi</td><td class=\"font-IsiBab\"> : </td>\n"
				+ "                        <td class=\"font-IsiBab\"> .................................................................................................... </td></tr>\n"
				+ "                    <tr><td class=\"font-IsiBab\">Anggota(2)</td><td class=\"font-IsiBab\"> : </td>\n"
				+ "                        <td class=\"font-IsiBab\"> &nbsp; </td></tr>\n"
				+ "                    <tr><td class=\"font-IsiBab\">&nbsp;&nbsp;Nama Lengkap</td><td class=\"font-IsiBab\"> : </td>\n"
				+ "                        <td class=\"font-IsiBab\"> .................................................................................................... </td></tr>\n"
				+ "                    <tr><td class=\"font-IsiBab\">&nbsp;&nbsp;NIDN</td><td class=\"font-IsiBab\"> : </td>\n"
				+ "                        <td class=\"font-IsiBab\"> .................................................................................................... </td></tr>\n"
				+ "                    <tr><td class=\"font-IsiBab\">&nbsp;&nbsp;Perguruan Tinggi</td><td class=\"font-IsiBab\"> : </td>\n"
				+ "                        <td class=\"font-IsiBab\"> .................................................................................................... </td></tr>\n"
				+ "					<tr><td class=\"font-IsiBab\">Anggota (ke-n)</td><td class=\"font-IsiBab\"> : </td>\n"
				+ "                        <td class=\"font-IsiBab\"> &nbsp; </td></tr>\n"
				+ "                    <tr><td class=\"font-IsiBab\">&nbsp;&nbsp;Nama Lengkap</td><td class=\"font-IsiBab\"> : </td>\n"
				+ "                        <td class=\"font-IsiBab\"> .................................................................................................... </td></tr>\n"
				+ "                    <tr><td class=\"font-IsiBab\">&nbsp;&nbsp;NIDN</td><td class=\"font-IsiBab\"> : </td>\n"
				+ "                        <td class=\"font-IsiBab\"> .................................................................................................... </td></tr>\n"
				+ "                    <tr><td class=\"font-IsiBab\">&nbsp;&nbsp;Perguruan Tinggi</td><td class=\"font-IsiBab\"> : </td>\n"
				+ "                        <td class=\"font-IsiBab\"> .................................................................................................... </td></tr>\n"
				+ "					<tr><td class=\"font-IsiBab\">Institusi Mitra (jika ada)</td><td class=\"font-IsiBab\"> : </td>\n"
				+ "                        <td class=\"font-IsiBab\"> &nbsp; </td></tr>\n"
				+ "                    <tr><td class=\"font-IsiBab\">&nbsp;&nbsp;Nama Institusi Mitra</td><td class=\"font-IsiBab\"> : </td>\n"
				+ "                        <td class=\"font-IsiBab\"> .................................................................................................... </td></tr>\n"
				+ "                    <tr><td class=\"font-IsiBab\">&nbsp;&nbsp;Alamat</td><td class=\"font-IsiBab\"> : </td>\n"
				+ "                        <td class=\"font-IsiBab\"> .................................................................................................... </td></tr>\n"
				+ "                    <tr><td class=\"font-IsiBab\">&nbsp;&nbsp;Penanggung Jawab</td><td class=\"font-IsiBab\"> : </td>\n"
				+ "                        <td class=\"font-IsiBab\"> .................................................................................................... </td></tr>                          \n"
				+ "					<tr><td class=\"font-IsiBab\">Tahun Pelaksanaan</td><td class=\"font-IsiBab\"> : </td>\n"
				+ "                        <td class=\"font-IsiBab\"> Tahun ke ........ dari rencana ....... tahun </td></tr>\n"
				+ "                    <tr><td class=\"font-IsiBab\">Biaya Tahun Berjalan</td><td class=\"font-IsiBab\"> : </td>\n"
				+ "                        <td class=\"font-IsiBab\"> Rp ................... </td></tr>\n"
				+ "                    <tr><td class=\"font-IsiBab\">Biaya Keseluruhan</td><td class=\"font-IsiBab\"> : </td>\n"
				+ "                        <td class=\"font-IsiBab\"> Rp ................... </td></tr>\n"
				+ "                </tbody></table>\n" + "                &nbsp; <br>\n"
				+ "                <table width=\"570\" border=\"0\" cellpadding=\"1\">\n"
				+ "                    <tbody><tr><td width=\"380\" class=\"font-IsiBab\">Mengetahui</td>\n"
				+ "                        <td class=\"font-IsiBab\">Kota, tanggal-bulan-tahun</td></tr>\n"
				+ "                    <tr><td width=\"380\" class=\"font-IsiBab\">Dekan/Ketua</td>\n"
				+ "                        <td class=\"font-IsiBab\">Ketua Peneliti/Pelaksana,</td></tr>\n"
				+ "                    <tr><td width=\"380\" class=\"font-IsiBab\">&nbsp;</td>\n"
				+ "                        <td class=\"font-IsiBab\">&nbsp;</td></tr>\n"
				+ "                    <tr><td width=\"380\" class=\"font-IsiBab\">tanda tangan</td>\n"
				+ "                        <td class=\"font-IsiBab\">tanda tangan</td></tr>\n"
				+ "                    <tr><td width=\"380\" class=\"font-IsiBab\">&nbsp;</td>\n"
				+ "                        <td class=\"font-IsiBab\">&nbsp;</td></tr>\n"
				+ "                    <tr><td width=\"380\" class=\"font-IsiBab\">( Nama Lengkap )</td>\n"
				+ "                        <td class=\"font-IsiBab\">( Nama Lengkap )</td></tr>\n"
				+ "                    <tr><td width=\"380\" class=\"font-IsiBab\">NIP/NIK</td>\n"
				+ "                        <td class=\"font-IsiBab\">NIP/NIK</td></tr>\n"
				+ "                </tbody></table>\n" + "                \n"
				+ "                <p class=\"font-IsiBab\" align=\"center\">Menyetujui,<br>\n"
				+ "                                                      Ketua lembaga penelitian/pengabdian*</p>\n"
				+ "                <p class=\"font-IsiBab\" align=\"center\">&nbsp;</p>                      \n"
				+ "                <p class=\"font-IsiBab\" align=\"center\">tanda tangan</p>\n"
				+ "                <p class=\"font-IsiBab\" align=\"center\">&nbsp;<br>\n"
				+ "                                                      ( Nama Lengkap )<br>\n"
				+ "                                                      NIP/NIK</p>\n" + "                </td></tr>\n"
				+ "            </tbody></table>   	\n" + "\n" + "               \n" + "                \n"
				+ "             \n" + "                	\n"
				+ "      <p class=\"font-IsiBab\">* Disesuaikan dengan nama lembaga penelitian dan atau pengabdian kepada masyarakat di PT</p>\n"
				+ "       <p class=\"font-IsiBab\">&nbsp;</p>\n"
				+ "      <p class=\"font-IsiBab\"><b>c.  Sistematika Laporan Tahunan/Akhir</b></p>\n" + "\n"
				+ "      <table width=\"620\" border=\"1\" cellpadding=\"3\">\n"
				+ "                    <tbody><tr height=\"30\"><td width=\"310\" class=\"font-IsiBab\"><b>Laporan Tahunan/Akhir Penelitian</b></td>\n"
				+ "                        <td class=\"font-IsiBab\"><b>Laporan Tahunan/Akhir Pengabdian</b></td></tr>\n"
				+ "                    <tr><td width=\"310\" class=\"font-IsiBab\">HALAMAN SAMPUL</td>\n"
				+ "                        <td class=\"font-IsiBab\">HALAMAN SAMPUL</td></tr>\n"
				+ "                    <tr><td width=\"310\" class=\"font-IsiBab\">HALAMAN PENGESAHAN</td>\n"
				+ "                        <td class=\"font-IsiBab\">HALAMAN PENGESAHAN</td></tr>\n"
				+ "                    <tr><td width=\"310\" class=\"font-IsiBab\">RINGKASAN </td>\n"
				+ "                        <td class=\"font-IsiBab\">RINGKASAN </td></tr>\n"
				+ "                    <tr><td width=\"310\" class=\"font-IsiBab\">PRAKATA </td>\n"
				+ "                        <td class=\"font-IsiBab\">PRAKATA </td></tr>\n"
				+ "                    <tr><td width=\"310\" class=\"font-IsiBab\">DAFTAR ISI </td>\n"
				+ "                        <td class=\"font-IsiBab\">DAFTAR ISI </td></tr>\n"
				+ "                    <tr><td width=\"310\" class=\"font-IsiBab\">DAFTAR TABEL</td>\n"
				+ "                        <td class=\"font-IsiBab\">DAFTAR TABEL</td></tr>\n"
				+ "                    <tr><td width=\"310\" class=\"font-IsiBab\">DAFTAR GAMBAR</td>\n"
				+ "                        <td class=\"font-IsiBab\">DAFTAR GAMBAR</td></tr>\n"
				+ "                    <tr><td width=\"310\" class=\"font-IsiBab\">DAFTAR LAMPIRAN</td>\n"
				+ "                        <td class=\"font-IsiBab\">DAFTAR LAMPIRAN</td></tr>\n"
				+ "                    <tr><td width=\"310\" class=\"font-IsiBab\">BAB 1. PENDAHULUAN </td>\n"
				+ "                        <td class=\"font-IsiBab\">BAB 1. PENDAHULUAN </td></tr>\n"
				+ "                    <tr><td width=\"310\" class=\"font-IsiBab\">BAB 2. TINJAUAN PUSTAKA </td>\n"
				+ "                        <td class=\"font-IsiBab\">BAB 2. TARGET DAN LUARAN </td></tr>\n"
				+ "                    <tr><td width=\"310\" class=\"font-IsiBab\">BAB 3. TUJUAN DAN MANFAAT PENELITIAN</td>\n"
				+ "                        <td class=\"font-IsiBab\">BAB 3. METODE PELAKSANAAN</td></tr>\n"
				+ "                    <tr><td width=\"310\" class=\"font-IsiBab\">BAB 4. METODE PENELITIAN </td>\n"
				+ "                        <td class=\"font-IsiBab\">BAB 4. KELAYAKAN PERGURUAN TINGGI</td></tr>\n"
				+ "                    <tr><td width=\"310\" class=\"font-IsiBab\">BAB 5. HASIL DAN PEMBAHASAN</td>\n"
				+ "                        <td class=\"font-IsiBab\">BAB 5. HASIL DAN PEMBAHASAN </td></tr>\n"
				+ "                    <tr><td width=\"310\" class=\"font-IsiBab\">BAB 6. RENCANA TAHAPAN BERIKUTNYA (untuk laporan tahunan)</td>\n"
				+ "                        <td class=\"font-IsiBab\">BAB 6. RENCANA TAHAPAN BERIKUTNYA (untuk laporan tahunan)</td></tr>\n"
				+ "                    <tr><td width=\"310\" class=\"font-IsiBab\">BAB 7. KESIMPULAN DAN SARAN </td>\n"
				+ "                        <td class=\"font-IsiBab\">BAB 7. KESIMPULAN DAN SARAN </td></tr>\n"
				+ "                    <tr><td width=\"310\" class=\"font-IsiBab\">DAFTAR PUSTAKA</td>\n"
				+ "                        <td class=\"font-IsiBab\">DAFTAR PUSTAKA</td></tr>\n"
				+ "                    <tr><td width=\"310\" class=\"font-IsiBab\">LAMPIRAN <br>\n"
				+ "                        <ul>\n" + "                        <li>instrumen </li>\n"
				+ "                        <li>personalia tenaga peneliti beserta kualifikasinya</li>\n"
				+ "                        <li>HKI dan  publikasi</li>\n" + "                        </ul></td>\n"
				+ "\n" + "                        <td class=\"font-IsiBab\">LAMPIRAN <br>\n"
				+ "                        <ul>\n" + "                        <li>instrumen </li>\n"
				+ "                        <li>personalia tenaga peneliti beserta kualifikasinya</li>\n"
				+ "                        <li>HKI dan  publikasi (jika disyaratkan)</li>\n"
				+ "                        </ul>	\n" + "                        </td></tr>\n"
				+ "                </tbody></table>\n" + "    </div>";

		s += "<div class=\"content-frame\" style=\"width:625px;\">\n"
				+ "        <p class=\"font-TitleContent\">Formulir Evaluasi Atas Capaian Luaran </p>\n"
				+ "        <p class=\"font-IsiBab\">FORMULIR EVALUASI ATAS CAPAIAN LUARAN KEGIATAN</p>\n" + "   \n"
				+ "        <table width=\"620\" border=\"0\" cellpadding=\"2\" class=\"font-IsiBab\">              \n"
				+ "            <tbody><tr><td>&nbsp;Ketua</td><td align=\"center\">:</td><td>................................................................</td></tr>\n"
				+ "            <tr><td>&nbsp;Perguruan Tinggi</td><td align=\"center\">:</td><td>................................................................</td></tr>\n"
				+ "            <tr><td>&nbsp;Judul</td><td align=\"center\">:</td><td>................................................................</td></tr>\n"
				+ "            <tr><td>&nbsp;Waktu Kegiatan</td><td align=\"center\">:</td><td>tahun ke ......... dari rencana ......... tahun</td></tr>\n"
				+ "        </tbody></table>\n"
				+ "        <p class=\"font-IsiBab\"><b>Luaran yang direncanakan dan capaian tertulis dalam proposal awal:</b></p>\n"
				+ "        <table width=\"620\" border=\"1\" cellpadding=\"2\" class=\"font-IsiBab\">\n"
				+ "            <tbody><tr><td align=\"center\" width=\"40\"><b>No</b></td><td width=\"300\">&nbsp;<b>Luaran yang Direncanakan</b></td><td width=\"280\">&nbsp;<b>Capaian</b></td></tr>\n"
				+ "            <tr><td align=\"center\">1.</td><td>&nbsp;........................</td><td>&nbsp;........................</td></tr>\n"
				+ "            <tr><td align=\"center\">2.</td><td>&nbsp;........................</td><td>&nbsp;........................</td></tr>\n"
				+ "            <tr><td align=\"center\">3.</td><td>&nbsp;........................</td><td>&nbsp;........................</td></tr>\n"
				+ "            <tr><td align=\"center\">dst.</td><td>&nbsp;........................</td><td>&nbsp;........................</td></tr>\n"
				+ "        </tbody></table>\n" + "        <p class=\"font-IsiBab\">\n"
				+ "        CAPAIAN (Lampirkan bukti-bukti luaran dari kegiatan dengan judul yang tertulis di atas, bukan dari kegiatan penelitian/pengabdian dengan judul lain sebelumnya) \n"
				+ "        </p>\n" + "        <p class=\"font-IsiBab\"><b>1. PUBLIKASI ILMIAH</b> </p>\n"
				+ "        <table width=\"620\" border=\"1\" cellpadding=\"2\" class=\"font-IsiBab\">              \n"
				+ "            <tbody><tr><td colspan=\"2\" width=\"250\">&nbsp;</td><td align=\"center\" width=\"370\">&nbsp;<b>Keterangan</b></td></tr>\n"
				+ "            <tr><td colspan=\"2\"><b>&nbsp;Artikel Jurnal Ke-1*</b></td><td>&nbsp;</td></tr>\n"
				+ "            <tr><td>&nbsp;Nama jurnal yang dituju </td><td align=\"center\">:</td><td>&nbsp;</td></tr>\n"
				+ "            <tr><td>&nbsp;Klasifikasi jurnal</td><td align=\"center\">:</td><td>&nbsp;Jurnal Nasional Terkareditasi/Jurnal Internasional</td></tr>\n"
				+ "            <tr><td>&nbsp;Impact factor jurnal </td><td align=\"center\">:</td><td>&nbsp;</td></tr>\n"
				+ "            <tr><td>&nbsp;Judul artikel </td><td align=\"center\">:</td><td>&nbsp;</td></tr>\n"
				+ "            <tr><td>&nbsp;Status naskah (beri tanda v) </td><td align=\"center\">:</td><td>&nbsp;</td></tr>\n"
				+ "            <tr><td>&nbsp;-	Draf artikel </td><td align=\"center\">:</td><td>&nbsp;</td></tr>\n"
				+ "            <tr><td>&nbsp;-	Sudah dikirim ke jurnal </td><td align=\"center\">:</td><td>&nbsp;</td></tr>\n"
				+ "            <tr><td>&nbsp;-	Sedang ditelaah </td><td align=\"center\">:</td><td>&nbsp;</td></tr>\n"
				+ "            <tr><td>&nbsp;-	Sedang direvisi </td><td align=\"center\">:</td><td>&nbsp;</td></tr>\n"
				+ "            <tr><td>&nbsp;-	Sudah diterima </td><td align=\"center\">:</td><td>&nbsp;</td></tr>\n"
				+ "            <tr><td>&nbsp;-	Sudah terbit </td><td align=\"center\">:</td><td>&nbsp;</td></tr>\n"
				+ "        </tbody></table>\n"
				+ "        <p class=\"font-IsiBab\"> * Jika masih ada artikel ke-2 dan seterusnya, uraikan pada lembar tambahan.</p>\n"
				+ "\n" + "        <p class=\"font-IsiBab\"><b>2. BUKU AJAR</b></p>\n"
				+ "        <table width=\"620\" border=\"1\" cellpadding=\"2\" class=\"font-IsiBab\">             \n"
				+ "            <tbody><tr><td colspan=\"3\"><b>Buku ke-1</b></td></tr>\n"
				+ "            <tr><td width=\"150\">Judul</td><td width=\"10\" align=\"center\">:</td><td>&nbsp;</td></tr>\n"
				+ "            <tr><td>Penulis</td><td align=\"center\">:</td><td>&nbsp;</td></tr>\n"
				+ "            <tr><td>Penerbit</td><td align=\"center\">:</td><td>&nbsp;</td></tr>\n"
				+ "        </tbody></table>\n"
				+ "        <p class=\"font-IsiBab\">Jika masih ada buku ke-2 dan seterusnya, uraikan pada lembar tambahan.</p>\n"
				+ "        <p class=\"font-IsiBab\"><b>3. PEMBICARA PADA PERTEMUAN ILMIAH (SEMINAR/SIMPOSIUM) </b></p>\n"
				+ "        <table width=\"620\" border=\"1\" cellpadding=\"2\" class=\"font-IsiBab\">             \n"
				+ "            <tbody><tr><td width=\"220\">&nbsp;</td><td width=\"200\"><b>&nbsp;Nasional</b></td><td width=\"200\"><b>&nbsp;Internasional</b></td></tr>\n"
				+ "            <tr><td>&nbsp;Judul Makalah</td><td>&nbsp;</td><td>&nbsp;</td></tr>\n"
				+ "            <tr><td>&nbsp;Nama Pertemuan Ilmiah</td><td>&nbsp;</td><td>&nbsp;</td></tr>\n"
				+ "            <tr><td>&nbsp;Tempat Pelaksanaan</td><td>&nbsp;</td><td>&nbsp;</td></tr>\n"
				+ "            <tr><td>&nbsp;Waktu Pelaksanaan</td><td>&nbsp;</td><td>&nbsp;</td></tr>\n"
				+ "            <tr><td>&nbsp;-	Draf makalah</td><td>&nbsp;</td><td>&nbsp;</td></tr>\n"
				+ "            <tr><td>&nbsp;-	Sudah dikirim</td><td>&nbsp;</td><td>&nbsp;</td></tr>\n"
				+ "            <tr><td>&nbsp;-	Sedang direview</td><td>&nbsp;</td><td>&nbsp;</td></tr>\n"
				+ "            <tr><td>&nbsp;-	Sudah dilaksanakan</td><td>&nbsp;</td><td>&nbsp;</td></tr>\n"
				+ "        </tbody></table>\n"
				+ "        <p class=\"font-IsiBab\">Jika masih ada pertemuan ilmiah ke 2 dan seterusnya uraikan pada lembar tambahan.</p>\n"
				+ "  \n"
				+ "         <p class=\"font-IsiBab\"><b>4. SEBAGAI PEMBICARA KUNCI (KEYNOTE SPEAKER) </b></p>\n"
				+ "        <table width=\"620\" border=\"1\" cellpadding=\"2\" class=\"font-IsiBab\">             \n"
				+ "            <tbody><tr><td width=\"220\">&nbsp;</td><td width=\"200\"><b>&nbsp;Nasional</b></td><td width=\"200\"><b>&nbsp;Internasional</b></td></tr>\n"
				+ "            <tr><td>&nbsp;Bukti Undangan dari Panitia</td><td>&nbsp;</td><td>&nbsp;</td></tr>\n"
				+ "            <tr><td>&nbsp;Judul Makalah</td><td>&nbsp;</td><td>&nbsp;</td></tr>\n"
				+ "            <tr><td>&nbsp;Penulis</td><td>&nbsp;</td><td>&nbsp;</td></tr>\n"
				+ "            <tr><td>&nbsp;Penyelenggara</td><td>&nbsp;</td><td>&nbsp;</td></tr>\n"
				+ "            <tr><td>&nbsp;Tempat Pelaksanaan</td><td>&nbsp;</td><td>&nbsp;</td></tr>\n"
				+ "            <tr><td>&nbsp;Waktu Pelaksanaan</td><td>&nbsp;</td><td>&nbsp;</td></tr>\n"
				+ "            <tr><td>&nbsp;-	Draf makalah</td><td>&nbsp;</td><td>&nbsp;</td></tr>\n"
				+ "            <tr><td>&nbsp;-	Sudah dikirim</td><td>&nbsp;</td><td>&nbsp;</td></tr>\n"
				+ "            <tr><td>&nbsp;-	Sedang direview</td><td>&nbsp;</td><td>&nbsp;</td></tr>\n"
				+ "            <tr><td>&nbsp;-	Sudah dilaksanakan</td><td>&nbsp;</td><td>&nbsp;</td></tr>\n"
				+ "        </tbody></table>\n"
				+ "        <p class=\"font-IsiBab\">Jika masih ada undangan ke 2 dan seterusnya uraikan pada lembar tambahan.</p>\n"
				+ "  \n"
				+ "        <p class=\"font-IsiBab\"><b>5. UNDANGAN SEBAGAI VISITING SCIENTIST PADA PERGURUAN TINGGI LAIN</b></p>\n"
				+ "        <table width=\"620\" border=\"1\" cellpadding=\"2\" class=\"font-IsiBab\">             \n"
				+ "            <tbody><tr><td width=\"220\">&nbsp;</td><td width=\"200\"><b>&nbsp;Nasional</b></td><td width=\"200\"><b>&nbsp;Internasional</b></td></tr>\n"
				+ "            <tr><td>&nbsp;Bukti undangan</td><td>&nbsp;</td><td>&nbsp;</td></tr>\n"
				+ "            <tr><td>&nbsp;Perguruan tinggi pengundang</td><td>&nbsp;</td><td>&nbsp;</td></tr>\n"
				+ "            <tr><td>&nbsp;Lama kegiatan</td><td>&nbsp;</td><td>&nbsp;</td></tr>\n"
				+ "            <tr><td>&nbsp;Kegiatan penting yang dilakukan</td><td>&nbsp;</td><td>&nbsp;</td></tr>\n"
				+ "        </tbody></table>\n"
				+ "        <p class=\"font-IsiBab\">Jika masih ada undangan ke 2 dan seterusnya uraikan pada lembar tambahan.</p>\n"
				+ " \n" + "        <p class=\"font-IsiBab\"><b>6. CAPAIAN LUARAN LAINNYA</b></p>\n"
				+ "        <table width=\"620\" border=\"1\" cellpadding=\"3\" class=\"font-IsiBab\">             \n"
				+ "            <tbody><tr><td width=\"220\">&nbsp;HKI</td><td width=\"400\">&nbsp;(Uraikan status kemajuan mulai dari pengajuan sampai \"granted\")</td></tr>\n"
				+ "            <tr><td>&nbsp;TEKNOLOGI TEPAT GUNA</td><td>&nbsp;(Uraikan siapa masyarakat pengguna teknologi yang dimaksud) </td></tr>\n"
				+ "            <tr><td>&nbsp;REKAYASA SOSIAL</td><td>&nbsp;(Uraikan kebijakan publik yang sedang atau sudah dapat diubah)</td></tr>\n"
				+ "            <tr><td>&nbsp;JEJARING KERJA SAMA</td><td>&nbsp;(Uraikan kapan jejaring dibentuk dan kegiatannya sampai saat ini, baik antar peneliti maupun antar lembaga)</td></tr>\n"
				+ "            <tr><td>&nbsp;PENGHARGAAN</td><td>&nbsp;(Uraikan penghargaan yang diterima sebagai peneliti, baik dari pemerintah atau asosiasi profesi)</td></tr>\n"
				+ "            <tr><td>&nbsp;LAINNYA </td><td>&nbsp;(Tuliskan)</td></tr>\n"
				+ "        </tbody></table>\n" + "        \n"
				+ "        <p class=\"font-IsiBab\">Jika luaran yang direncanakan tidak tercapai, uraikan alasannya: </p>\n"
				+ "        <p class=\"font-IsiBab\">..........................................................................................................\n"
				+ "            ............................................... </p>\n"
				+ "        <p class=\"font-IsiBab\">..........................................................................................................\n"
				+ "            ............................................... </p>\n"
				+ "        <p class=\"font-IsiBab\">..........................................................................................................\n"
				+ "            ............................................... </p>\n" + "\n"
				+ "        <table width=\"620\" border=\"0\" cellpadding=\"1\">\n"
				+ "            <tbody><tr><td width=\"400\" class=\"font-IsiBab\">&nbsp;</td>\n"
				+ "                <td class=\"font-IsiBab\">Kota, tanggal-bulan-tahun</td></tr>\n"
				+ "            <tr><td width=\"400\" class=\"font-IsiBab\">&nbsp;</td>\n"
				+ "                <td class=\"font-IsiBab\">Ketua,</td></tr>\n"
				+ "            <tr><td width=\"400\" class=\"font-IsiBab\">&nbsp;</td>\n"
				+ "                <td class=\"font-IsiBab\">&nbsp;</td></tr>\n"
				+ "            <tr><td width=\"400\" class=\"font-IsiBab\">&nbsp;</td>\n"
				+ "                <td class=\"font-IsiBab\">tanda tangan</td></tr>\n"
				+ "            <tr><td width=\"400\" class=\"font-IsiBab\">&nbsp;</td>\n"
				+ "                <td class=\"font-IsiBab\">&nbsp;</td></tr>\n"
				+ "            <tr><td width=\"400\" class=\"font-IsiBab\">&nbsp;</td>\n"
				+ "                <td class=\"font-IsiBab\">( Nama Lengkap )</td></tr>\n" + "       </tbody></table>\n"
				+ "\n" + "    </div>";

		return s;
	}

}
