package ais.database.model.lkp;

// Generated Apr 16, 2010 2:27:16 PM by Hibernate Tools 3.2.4.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.Set;
import java.util.TreeSet;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OrderBy;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.envers.Audited;
import org.hibernate.envers.NotAudited;

import ais.database.model.GeneralValueObject;
import ais.database.model.Tbmrole;
import ais.database.model.rab.SatuanKerja;

/**
 * Bank generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Entity(
    dynamicInsert = true,
    dynamicUpdate = true
)
@Audited
@Table(schema = "public", name = "kegiatan_tugas_jabatan")
public class KegiatanTugasJabatan extends GeneralValueObject {

	public static final String BULANAN = "Bulanan";
	public static final String TAHUNAN = "Tahunan";

	/** 
	 * 
	 */
	private static final long serialVersionUID = 2463821577548439808L;
	private Long id;
	private String oleh;
	private String olehId;

	public String getOlehId() {
		return olehId;
	}

	public void setOlehId(String olehId) {if (olehId == null || olehId.trim().isEmpty()) {return;}
		this.olehId = olehId;
	}

	public void setOleh(String oleh) {if (oleh == null || oleh.trim().isEmpty()) {return;}
		this.oleh = oleh;
	}

	public String getOleh() {
		return oleh;
	}

	@javax.persistence.PreUpdate protected void onUpdate() { ais.database.hibernate.AuditTimestampInterceptor.ubah(this);}     private Date tanggal_dirubah = ais.ui.util.WaktuUtil.getDate();

	public void setTanggal_dirubah(Date tanggal_dirubah) {
		this.tanggal_dirubah = tanggal_dirubah;
	}

	@Temporal(TemporalType.TIMESTAMP)
	public Date getTanggal_dirubah() {
		return tanggal_dirubah;
	}

	public String toString() {
		return id + "-" + nama;
	}

	private SatuanKerja satuanKerja;
	private Tbmrole userRole;
	private String nama;
	private Double angkaKredit;
	private SatuanKegiatanTugasJabatan satuanKuantitas;
	private Double kuantitasDefault;
	private Double kuantitasRealisasiDefault;
	private Double kualitasDefault;
	private Double waktuDefault;
	private Double biayaDefault;
	private String satuanWaktu;
	private String keterangan;
	private Boolean aktif;
	private Boolean wajib;
	private Double noUrut;

	private KegiatanTugasJabatan induk;
	private Integer deep;
	private Long jmlDipakai;
	private String periode;

	private Set<KelompokParameterTambahanKegiatan> kelompokParameterTambahanKegiatans = new TreeSet<KelompokParameterTambahanKegiatan>();

	@ManyToMany(targetEntity = KelompokParameterTambahanKegiatan.class, cascade = { CascadeType.MERGE,
			CascadeType.PERSIST })
	@OrderBy(value = "nomorUrut asc")
	@JoinTable(name = "kegiatan_has_parameter", joinColumns = @JoinColumn(name = "kegiatan_tugas_jabatan"), inverseJoinColumns = @JoinColumn(name = "kelompok_parameter_tambahan_kegiatan"))
	@NotAudited
	public Set<KelompokParameterTambahanKegiatan> getKelompokParameterTambahanKegiatans() {
		return kelompokParameterTambahanKegiatans;
	}

	public void setKelompokParameterTambahanKegiatans(
			Set<KelompokParameterTambahanKegiatan> kelompokParameterTambahanKegiatans) {
		this.kelompokParameterTambahanKegiatans = kelompokParameterTambahanKegiatans;
	}

	public KegiatanTugasJabatan() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", insertable = false, unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "nama", nullable = false, length = 255)
	public String getNama() {
		return this.nama == null ? null : this.nama.trim();
	}

	public void setNama(String nama) {
		this.nama = nama;
	}

	@Column(name = "keterangan", nullable = true)
	public String getKeterangan() {
		return this.keterangan;
	}

	public void setKeterangan(String keterangan) {
		this.keterangan = keterangan;
	}

	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY)
	@JoinColumn(name = "satuan_kerja", nullable = false)
	public SatuanKerja getSatuanKerja() {
		satuanKerja = check(satuanKerja);
		return satuanKerja;
	}

	public void setSatuanKerja(SatuanKerja satuanKerja) {
		this.satuanKerja = satuanKerja;
	}

	public Double getAngkaKredit() {
		return angkaKredit == null ? 0.0 : angkaKredit;
	}

	public void setAngkaKredit(Double angkaKredit) {
		this.angkaKredit = angkaKredit;
	}

	public Double getKuantitasDefault() {
		return kuantitasDefault == null ? 0.0 : kuantitasDefault;
	}

	public void setKuantitasDefault(Double kuantitasDefault) {
		this.kuantitasDefault = kuantitasDefault;
	}

	public Double getKualitasDefault() {
		return kualitasDefault == null ? 100.0 : kualitasDefault;
	}

	public void setKualitasDefault(Double kualitasDefault) {
		this.kualitasDefault = kualitasDefault;
	}

	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY)
	@JoinColumn(name = "satuan_kuantitas", nullable = true)
	public SatuanKegiatanTugasJabatan getSatuanKuantitas() {
		satuanKuantitas = check(satuanKuantitas);
		return satuanKuantitas;
	}

	public void setSatuanKuantitas(SatuanKegiatanTugasJabatan satuanKuantitas) {
		this.satuanKuantitas = satuanKuantitas;
	}

	public Double getWaktuDefault() {
		return waktuDefault == null ? 0.0 : waktuDefault;
	}

	public void setWaktuDefault(Double waktuDefault) {
		this.waktuDefault = waktuDefault;
	}

	public String getSatuanWaktu() {
		return satuanWaktu == null || satuanWaktu.isEmpty() ? "Jam" : satuanWaktu.trim();
	}

	public void setSatuanWaktu(String satuanWaktu) {
		this.satuanWaktu = satuanWaktu;
	}

	public Double getBiayaDefault() {
		return biayaDefault == null ? 0.0 : biayaDefault;
	}

	public void setBiayaDefault(Double biayaDefault) {
		this.biayaDefault = biayaDefault;
	}

	public Boolean getAktif() {
		return aktif == null ? true : aktif;
	}

	public void setAktif(Boolean aktif) {
		this.aktif = aktif;
	}

	public Double getKuantitasRealisasiDefault() {
		return kuantitasRealisasiDefault == null ? 90.0 : kuantitasRealisasiDefault;
	}

	public void setKuantitasRealisasiDefault(Double kuantitasRealisasiDefault) {
		this.kuantitasRealisasiDefault = kuantitasRealisasiDefault;
	}

	public Boolean getWajib() {
		return wajib == null ? true : wajib;
	}

	public void setWajib(Boolean wajib) {
		this.wajib = wajib;
	}

	public Double getNoUrut() {
		return noUrut == null ? 0.0 : noUrut;
	}

	public void setNoUrut(Double noUrut) {
		this.noUrut = noUrut;
	}

	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY)
	@JoinColumn(name = "induk", nullable = true)
	public KegiatanTugasJabatan getInduk() {
		induk = check(induk);
		return induk;
	}

	public void setInduk(KegiatanTugasJabatan induk) {
		this.induk = induk;
	}

	public Integer getDeep() {
		return deep;
	}

	public void setDeep(Integer deep) {
		this.deep = deep;
	}

	public Long getJmlDipakai() {
		return jmlDipakai;
	}

	public void setJmlDipakai(Long jmlDipakai) {
		this.jmlDipakai = jmlDipakai;
	}

	public String getPeriode() {
		return periode == null || periode.trim().isEmpty() ? BULANAN : periode;
	}

	public void setPeriode(String periode) {
		this.periode = periode;
	}

	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY)
	@JoinColumn(name = "userrole", nullable = true)
	public Tbmrole getUserRole() {
		userRole = check(userRole);
		return this.userRole;
	}

	public void setUserRole(Tbmrole userRole) {
		if (userRole == null) {
			return;
		}
		this.userRole = userRole;
	}

}
