package ais.database.model.lkp;

// Generated Dec 19, 2009 10:58:09 PM by Hibernate Tools 3.2.4.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.envers.Audited;

import ais.database.model.GeneralValueObject;
import ais.database.model.rab.Indikator;

///**
// * Satuan generated by hbm2java
// */
@Entity
@org.hibernate.annotations.Entity(
    dynamicInsert = true,
    dynamicUpdate = true
)
@Audited
@Table(schema = "public", name = "kegiatan_tugas_jabatan_punya_indikator")
public class KegiatanTugasJabatanPunyaIndikator extends GeneralValueObject {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8738027816264807168L;
	private String oleh;
	private String olehId;

	public String getOlehId() {
		return olehId;
	}

	public void setOlehId(String olehId) {if (olehId == null || olehId.trim().isEmpty()) {return;}
		this.olehId = olehId;
	}

	private Long id;

	public void setOleh(String oleh) {if (oleh == null || oleh.trim().isEmpty()) {return;}
		this.oleh = oleh;
	}

	public String getOleh() {
		return oleh;
	}

	@javax.persistence.PreUpdate protected void onUpdate() { ais.database.hibernate.AuditTimestampInterceptor.ubah(this);}     private Date tanggal_dirubah = ais.ui.util.WaktuUtil.getDate();

	public void setTanggal_dirubah(Date tanggal_dirubah) {
		this.tanggal_dirubah = tanggal_dirubah;
	}

	@Temporal(TemporalType.TIMESTAMP)
	public Date getTanggal_dirubah() {
		return tanggal_dirubah;
	}

	private Indikator indikator;
	private KegiatanTugasJabatan kegiatanTugasJabatan;
	private Double nilaiTarget;
	private SatuanKegiatanTugasJabatan satuan;
	private String target;
	private String output;

	public KegiatanTugasJabatanPunyaIndikator() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY)
	@JoinColumn(name = "indikator", nullable = true)
	public Indikator getIndikator() {
		indikator = check(indikator);
		return indikator;
	}

	public void setIndikator(Indikator indikator) {
		this.indikator = indikator;
	}

	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY)
	@JoinColumn(name = "kegiatan_tugas_jabatan", nullable = false)
	public KegiatanTugasJabatan getKegiatanTugasJabatan() {
		kegiatanTugasJabatan = check(kegiatanTugasJabatan);
		return kegiatanTugasJabatan;
	}

	public void setKegiatanTugasJabatan(KegiatanTugasJabatan kegiatanTugasJabatan) {
		this.kegiatanTugasJabatan = kegiatanTugasJabatan;
	}

	@Column(name = "output", columnDefinition = "text")
	public String getOutput() {
		return output;
	}

	public void setOutput(String output) {
		this.output = output;
	}

	@Column(name = "nilai_target")
	public Double getNilaiTarget() {
		return nilaiTarget;
	}

	public void setNilaiTarget(Double nilaiTarget) {
		this.nilaiTarget = nilaiTarget;
	}

	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY)
	@JoinColumn(name = "satuan", nullable = true)
	public SatuanKegiatanTugasJabatan getSatuan() {
		satuan = check(satuan);
		return satuan;
	}

	public void setSatuan(SatuanKegiatanTugasJabatan satuan) {
		this.satuan = satuan;
	}

	public String getTarget() {
		return target;
	}

	public void setTarget(String target) {
		this.target = target;
	}

}
