<%-- @generated by generate_new_jsp_scaffold.py
Source: src/ais/action/master/surat/ArsipMasukAction.java
Generated: 2026-08-06T18:20:20Z
Safe service-adapter scaffold. Implement data access in a Java service layer, not directly in this JSP.
--%>
<%@ page language="java" contentType="application/json; charset=UTF-8" pageEncoding="UTF-8" %>
<%
request.setAttribute("nuiServiceModule", "surat");
request.setAttribute("nuiServicePage", "arsip_masuk");
request.setAttribute("nuiServiceTitle", "Arsip Masuk");
request.setAttribute("nuiServiceType", "workflow");
request.setAttribute("nuiServiceSourceClass", "ArsipMasukAction");
request.setAttribute("nuiServiceSourcePackage", "ais.action.master.surat");
request.setAttribute("nuiServiceSourcePath", "src/ais/action/master/surat/ArsipMasukAction.java");
request.setAttribute("nuiServiceMethods", new String[]{"istilah"});
request.setAttribute("nuiServiceLegacyRefs", new String[]{});
request.setAttribute("nuiServiceEntities", new String[]{});
%>
<jsp:include page="/WEB-INF/new/_shared/services/dispatcher.jsp" />
