<%-- @generated by generate_new_jsp_scaffold.py
Source: src/ais/action/master/surat/OpsiSuratMasukAction.java
Generated: 2026-08-06T18:20:20Z
Safe service-adapter scaffold. Implement data access in a Java service layer, not directly in this JSP.
--%>
<%@ page language="java" contentType="application/json; charset=UTF-8" pageEncoding="UTF-8" %>
<%
request.setAttribute("nuiServiceModule", "surat");
request.setAttribute("nuiServicePage", "opsi_surat_masuk");
request.setAttribute("nuiServiceTitle", "Opsi Surat Masuk");
request.setAttribute("nuiServiceType", "workflow");
request.setAttribute("nuiServiceSourceClass", "OpsiSuratMasukAction");
request.setAttribute("nuiServiceSourcePackage", "ais.action.master.surat");
request.setAttribute("nuiServiceSourcePath", "src/ais/action/master/surat/OpsiSuratMasukAction.java");
request.setAttribute("nuiServiceMethods", new String[]{"initCriteria", "onEvent", "onSave", "checkNamaOpsiSuratMasuk", "render"});
request.setAttribute("nuiServiceEntities", new String[]{"OpsiSuratMasuk"});
%>
<jsp:include page="/WEB-INF/new/_shared/services/dispatcher.jsp" />
