<%-- @generated by generate_new_jsp_scaffold.py
Source: src/ais/action/master/sirs/StatusPembayaranAction.java
Generated: 2026-08-06T18:20:20Z
Safe service-adapter scaffold. Implement data access in a Java service layer, not directly in this JSP.
--%>
<%@ page language="java" contentType="application/json; charset=UTF-8" pageEncoding="UTF-8" %>
<%
request.setAttribute("nuiServiceModule", "sirs");
request.setAttribute("nuiServicePage", "status_pembayaran");
request.setAttribute("nuiServiceTitle", "Status Pembayaran");
request.setAttribute("nuiServiceType", "finance");
request.setAttribute("nuiServiceSourceClass", "StatusPembayaranAction");
request.setAttribute("nuiServiceSourcePackage", "ais.action.master.sirs");
request.setAttribute("nuiServiceSourcePath", "src/ais/action/master/sirs/StatusPembayaranAction.java");
request.setAttribute("nuiServiceMethods", new String[]{"initCriteria", "onEvent", "onSave", "checkNamaStatusPembayaran", "render"});
request.setAttribute("nuiServiceLegacyRefs", new String[]{});
request.setAttribute("nuiServiceEntities", new String[]{"StatusPembayaran"});
%>
<jsp:include page="/WEB-INF/new/_shared/services/dispatcher.jsp" />
