<%-- @generated by generate_new_jsp_scaffold.py
Source: src/ais/action/master/employ/PeraturanAction.java
Generated: 2026-08-06T18:20:20Z
Safe service-adapter scaffold. Implement data access in a Java service layer, not directly in this JSP.
--%>
<%@ page language="java" contentType="application/json; charset=UTF-8" pageEncoding="UTF-8" %>
<%
request.setAttribute("nuiServiceModule", "employ");
request.setAttribute("nuiServicePage", "peraturan");
request.setAttribute("nuiServiceTitle", "Peraturan");
request.setAttribute("nuiServiceType", "list");
request.setAttribute("nuiServiceSourceClass", "PeraturanAction");
request.setAttribute("nuiServiceSourcePackage", "ais.action.master.employ");
request.setAttribute("nuiServiceSourcePath", "src/ais/action/master/employ/PeraturanAction.java");
request.setAttribute("nuiServiceMethods", new String[]{"doBeforeCompose", "doAfterCompose", "onEvent", "render", "init", "onAdd", "onSave", "initCriteria", "onSearchDefault", "checkNamaPeraturan"});
request.setAttribute("nuiServiceEntities", new String[]{"JenisKegiatanEmploy", "JenisPeraturan", "Peraturan"});
%>
<jsp:include page="/WEB-INF/new/_shared/services/dispatcher.jsp" />
