<%-- @generated by generate_new_jsp_scaffold.py
Source: src/ais/action/report/format1/koperasi/LaporanTransaksiKoperasi.java
Generated: 2026-08-06T18:20:20Z
Safe service-adapter scaffold. Implement data access in a Java service layer, not directly in this JSP.
--%>
<%@ page language="java" contentType="application/json; charset=UTF-8" pageEncoding="UTF-8" %>
<%
request.setAttribute("nuiServiceModule", "root/report");
request.setAttribute("nuiServicePage", "format1/koperasi/laporan_transaksi_koperasi");
request.setAttribute("nuiServiceTitle", "Laporan Transaksi Koperasi");
request.setAttribute("nuiServiceType", "report");
request.setAttribute("nuiServiceSourceClass", "LaporanTransaksiKoperasi");
request.setAttribute("nuiServiceSourcePackage", "ais.action.report.format1.koperasi");
request.setAttribute("nuiServiceSourcePath", "src/ais/action/report/format1/koperasi/LaporanTransaksiKoperasi.java");
request.setAttribute("nuiServiceMethods", new String[]{"generateParameters", "onEvent", "generateParameter", "onReport"});
request.setAttribute("nuiServiceEntities", new String[]{"TransaksiKoperasi", "JenisTransaksiKoperasi"});
%>
<jsp:include page="/WEB-INF/new/_shared/services/dispatcher.jsp" />
