<%-- @generated by generate_new_jsp_scaffold.py
Source: src/ais/action/master/kpi/PengajuanKpiAction.java
Generated: 2026-08-06T18:20:20Z
Safe service-adapter scaffold. Implement data access in a Java service layer, not directly in this JSP.
--%>
<%@ page language="java" contentType="application/json; charset=UTF-8" pageEncoding="UTF-8" %>
<%
request.setAttribute("nuiServiceModule", "kpi");
request.setAttribute("nuiServicePage", "pengajuan_kpi");
request.setAttribute("nuiServiceTitle", "Pengajuan KPI");
request.setAttribute("nuiServiceType", "workflow");
request.setAttribute("nuiServiceSourceClass", "PengajuanKpiAction");
request.setAttribute("nuiServiceSourcePackage", "ais.action.master.kpi");
request.setAttribute("nuiServiceSourcePath", "src/ais/action/master/kpi/PengajuanKpiAction.java");
request.setAttribute("nuiServiceMethods", new String[]{"doAfterCompose", "onEvent", "render", "onSearchDefault", "onAdd", "init", "onSave", "form", "istilah", "ambil", "ambilClass", "setPersetujuan", "cetakData"});
request.setAttribute("nuiServiceLegacyRefs", new String[]{});
request.setAttribute("nuiServiceEntities", new String[]{"PengajuanKpi", "PenilaianKpi"});
%>
<jsp:include page="/WEB-INF/new/_shared/services/dispatcher.jsp" />
