<%-- @generated by generate_new_jsp_scaffold.py
Source: src/ais/action/iso8583/ConstansValueIso8583.java
Generated: 2026-08-06T18:20:20Z
This JSP contains presentation metadata only. Keep business logic in Java services.
--%>
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%
request.setAttribute("nuiModule", "root/iso8583");
request.setAttribute("nuiModuleLabel", "ISO 8583 & Switching Pembayaran");
request.setAttribute("nuiPage", "constans_value_iso8583");
request.setAttribute("nuiPageTitle", "Constans Value Iso 8583");
request.setAttribute("nuiPageType", "finance");
request.setAttribute("nuiPageDescription", "Keuangan untuk ISO 8583 & Switching Pembayaran. Transaksi, status, rekonsiliasi, detail, dan audit keuangan.");
request.setAttribute("nuiSourceClass", "ConstansValueIso8583");
request.setAttribute("nuiSourcePackage", "ais.action.iso8583");
request.setAttribute("nuiSourcePath", "src/ais/action/iso8583/ConstansValueIso8583.java");
request.setAttribute("nuiSourceKind", "class");
request.setAttribute("nuiSourceExtends", "");
request.setAttribute("nuiSourceImplements", "");
request.setAttribute("nuiSourceMethods", new String[]{"main"});
request.setAttribute("nuiLegacyRefs", new String[]{});
request.setAttribute("nuiEntityCandidates", new String[]{});
%>
<jsp:include page="/WEB-INF/new/_shared/ui/page.jsp" />
