<%-- @generated by generate_new_jsp_scaffold.py
Source: src/ais/action/master/rab/MetodePengadaanAction.java
Generated: 2026-08-06T18:20:20Z
This JSP contains presentation metadata only. Keep business logic in Java services.
--%>
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%
request.setAttribute("nuiModule", "rab");
request.setAttribute("nuiModuleLabel", "RAB & Anggaran");
request.setAttribute("nuiPage", "metode_pengadaan");
request.setAttribute("nuiPageTitle", "Metode Pengadaan");
request.setAttribute("nuiPageType", "finance");
request.setAttribute("nuiPageDescription", "Keuangan untuk RAB & Anggaran. Transaksi, status, rekonsiliasi, detail, dan audit keuangan.");
request.setAttribute("nuiSourceClass", "MetodePengadaanAction");
request.setAttribute("nuiSourcePackage", "ais.action.master.rab");
request.setAttribute("nuiSourcePath", "src/ais/action/master/rab/MetodePengadaanAction.java");
request.setAttribute("nuiSourceKind", "class");
request.setAttribute("nuiSourceExtends", "GenericAutowireComposer");
request.setAttribute("nuiSourceImplements", "");
request.setAttribute("nuiSourceMethods", new String[]{"doBeforeCompose", "doAfterCompose", "onEvent", "render", "onAdd", "onSave", "initCriteria", "onSearchDefault", "checkNamaMetodePengadaan"});
request.setAttribute("nuiEntityCandidates", new String[]{"MetodePengadaan"});
%>
<jsp:include page="/WEB-INF/new/_shared/ui/page.jsp" />
