<%-- @generated by generate_new_jsp_scaffold.py
Source: src/ais/action/master/bsi/BsiRequestAction.java
Generated: 2026-08-06T18:20:20Z
This JSP contains presentation metadata only. Keep business logic in Java services.
--%>
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%
request.setAttribute("nuiModule", "bsi");
request.setAttribute("nuiModuleLabel", "Integrasi BSI");
request.setAttribute("nuiPage", "bsi_request");
request.setAttribute("nuiPageTitle", "BSI Request");
request.setAttribute("nuiPageType", "finance");
request.setAttribute("nuiPageDescription", "Keuangan untuk Integrasi BSI. Transaksi, status, rekonsiliasi, detail, dan audit keuangan.");
request.setAttribute("nuiSourceClass", "BsiRequestAction");
request.setAttribute("nuiSourcePackage", "ais.action.master.bsi");
request.setAttribute("nuiSourcePath", "src/ais/action/master/bsi/BsiRequestAction.java");
request.setAttribute("nuiSourceKind", "class");
request.setAttribute("nuiSourceExtends", "GenericAutowireComposer");
request.setAttribute("nuiSourceImplements", "DataCriteria");
request.setAttribute("nuiSourceMethods", new String[]{"doBeforeCompose", "doAfterCompose", "onEvent", "run", "render", "initCriteria", "onSearchDefault"});
request.setAttribute("nuiEntityCandidates", new String[]{"Siswa", "CalonSiswa", "CicilanPembayaran", "BsiRequestDetail", "BsiRequest"});
%>
<jsp:include page="/WEB-INF/new/_shared/ui/page.jsp" />
