<%-- @generated by generate_new_jsp_scaffold.py
Source: src/ais/action/master/dashboard/keuangan/DashboardPerbandinganSudahMembayarDanBelum.java
Generated: 2026-08-06T18:20:20Z
This JSP contains presentation metadata only. Keep business logic in Java services.
--%>
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%
request.setAttribute("nuiModule", "dashboard");
request.setAttribute("nuiModuleLabel", "Dashboard & Analitik");
request.setAttribute("nuiPage", "keuangan/dashboard_perbandingan_sudah_membayar_dan_belum");
request.setAttribute("nuiPageTitle", "Dashboard Perbandingan Sudah Membayar Dan Belum");
request.setAttribute("nuiPageType", "dashboard");
request.setAttribute("nuiPageDescription", "Dashboard untuk Dashboard & Analitik. Ringkasan KPI, tren, aktivitas, dan tindakan prioritas.");
request.setAttribute("nuiSourceClass", "DashboardPerbandinganSudahMembayarDanBelum");
request.setAttribute("nuiSourcePackage", "ais.action.master.dashboard.keuangan");
request.setAttribute("nuiSourcePath", "src/ais/action/master/dashboard/keuangan/DashboardPerbandinganSudahMembayarDanBelum.java");
request.setAttribute("nuiSourceKind", "class");
request.setAttribute("nuiSourceExtends", "MyWindow");
request.setAttribute("nuiSourceImplements", "");
request.setAttribute("nuiSourceMethods", new String[]{"onEvent"});
request.setAttribute("nuiLegacyRefs", new String[]{});
request.setAttribute("nuiEntityCandidates", new String[]{"Fakultas", "StatusMahasiswa"});
%>
<jsp:include page="/WEB-INF/new/_shared/ui/page.jsp" />
