<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%
String posHelpKey = request.getParameter("menu");
if (posHelpKey == null) posHelpKey = "";
%>
<style>
.ph-wrap{max-width:1180px;margin:auto}.ph-hero{width:100%;aspect-ratio:16/9;object-fit:cover;border-radius:18px;max-height:520px}.ph-flow{display:flex;align-items:stretch;gap:8px;overflow:auto;padding:8px 0 18px}.ph-step{min-width:145px;flex:1;padding:14px;border:1px solid #93c5fd;background:#eff6ff;border-radius:12px;text-align:center;font-weight:700;color:#1e3a8a}.ph-num{display:block;width:28px;height:28px;line-height:28px;border-radius:50%;margin:0 auto 8px;background:#2563eb;color:white}.ph-arrow{display:flex;align-items:center;color:#2563eb;font-size:24px}.ph-section{background:white;border:1px solid #e5e7eb;border-radius:14px;padding:18px;margin-bottom:14px;box-shadow:0 3px 12px rgba(15,23,42,.05)}.ph-section h3{font-size:1.02rem;color:#1d4ed8;margin:0 0 10px}.ph-section p{line-height:1.75;margin:0;color:#334155;text-align:justify}.ph-count{font-size:.82rem;background:#dcfce7;color:#166534;border-radius:999px;padding:5px 10px}@media(max-width:700px){.ph-flow{flex-direction:column}.ph-arrow{justify-content:center;transform:rotate(90deg)}.ph-section{padding:14px}}
</style>
<div class="ph-wrap pb-4">
  <div class="d-flex flex-wrap justify-content-between align-items-center gap-2 mb-3">
    <div><h3 class="mb-1" id="ph-title">Bantuan POS</h3><div class="text-muted">Panduan operasional rinci, kontrol, contoh, dan workflow</div></div>
    <span class="ph-count" id="ph-count"></span>
  </div>
  <img id="ph-hero" class="ph-hero mb-4" alt="Ilustrasi penggunaan menu POS">
  <h4>Diagram workflow</h4><div id="ph-flow" class="ph-flow"></div>
  <div id="ph-content"></div>
</div>
<script>
(function(){
var key=<%=org.json.JSONObject.quote(posHelpKey)%>, ctx='<%=request.getContextPath()%>';
var S={
'apotik_kasir':['Kasir Apotik','melayani penjualan obat nonresep dan menyelesaikan pembayaran secara aman','Identifikasi pembeli|Cari obat|Validasi batch FEFO|Tinjau keranjang|Bayar|Verifikasi bukti','permintaan pelanggan, identitas bila dibutuhkan, obat yang dipilih, dan metode pembayaran','Sistem memilih batch layak dengan prinsip FEFO, menolak batch kedaluwarsa, menghitung nilai, dan mencatat transaksi','nomor transaksi, rincian obat, total pembayaran, pengurangan stok, dan jejak operator','verifikasi obat benar, pasien benar, jumlah wajar, batch valid, serta total pembayaran sesuai','Seorang pelanggan membeli dua obat bebas; petugas mencari kode, membandingkan nama dan satuan, memeriksa batch, mengonfirmasi jumlah, menerima pembayaran, lalu mengecek nomor transaksi'],
'apotik_resep':['Tebus Resep Dokter','mengambil resep menunggu dan menyerahkan obat sesuai instruksi dokter','Cari resep|Cocokkan pasien|Telaah item|Siapkan obat|Validasi farmasis|Bayar dan serahkan','resep sah, identitas pasien, informasi dokter, alergi atau catatan klinis yang tersedia','Sistem memuat rincian resep, menghubungkan item, memeriksa batch, dan menandai status penebusan','transaksi penebusan, status resep, bukti pembayaran, dan jejak penyerahan obat','kecocokan resep-pasien-dokter, potensi duplikasi, obat terkendali, racikan, LASA, dan batch FEFO','Pasien membawa resep terdaftar; petugas mencari kode, meminta pasien menyebutkan identitas, mencocokkan seluruh baris, meminta validasi farmasis, lalu memproses pembayaran'],
'apotik_racikan':['Racikan','mencatat formula serta penyiapan obat racikan secara dapat ditelusuri','Pilih resep|Telaah formula|Hitung kebutuhan|Siapkan bahan|Racik dan periksa|Serahkan','resep racikan, formula, kekuatan, jumlah, aturan pakai, bahan, dan identitas peracik','Petugas menyalin formula, menghitung kebutuhan, mendokumentasikan bahan, dan melakukan pemeriksaan akhir','catatan racikan, rincian bahan, jumlah hasil, etiket, dan identitas pemeriksa','pemeriksaan ganda formula, perhitungan, kompatibilitas, kebersihan, label, dan kewenangan farmasis','Farmasis menerima resep puyer; formula diverifikasi, kebutuhan dihitung ulang, bahan ditimbang, hasil diperiksa petugas kedua, kemudian etiket dikonfirmasi'],
'apotik_formularium':['Formularium & Obat','memelihara profil obat, golongan, penanda LASA, harga, dan informasi operasional','Cari item|Verifikasi master|Ubah profil|Tinjau dampak|Simpan|Audit perubahan','kode dan nama obat, satuan, golongan, harga, serta kebijakan formularium yang disahkan','Sistem memperbarui profil apotik yang dipakai pencarian, kasir, validasi, dan laporan','master obat yang konsisten dan riwayat perubahan profil','otorisasi perubahan master, validasi golongan, penanda LASA, satuan, harga, dan larangan duplikasi','Supervisor menerima keputusan formularium, mencari item dengan kode, memastikan bukan item serupa, memperbarui golongan dan LASA, lalu menguji pada kasir'],
'apotik_batch':['Batch & Kedaluwarsa','memantau sisa batch dan memprioritaskan obat yang mendekati kedaluwarsa','Tentukan horizon|Muat batch|Urutkan risiko|Verifikasi fisik|Tindak lanjuti|Dokumentasikan','periode hari ke depan, lokasi, data penerimaan, dan hasil pemeriksaan fisik','Sistem menghitung sisa batch sesudah konsumsi dan mengurutkan tanggal terdekat','daftar batch aktif, segera kedaluwarsa, kedaluwarsa, sisa, dan nilai risiko','pencocokan fisik, karantina produk kedaluwarsa, FEFO, dan larangan penjualan batch tidak layak','Petugas memilih horizon sembilan puluh hari, mencetak daftar, memeriksa rak, memisahkan produk kedaluwarsa, dan melaporkan selisih'],
'apotik_pengadaan':['Pengadaan / PBF','mencatat penerimaan obat dari pemasok resmi lengkap dengan jumlah, harga, dan kedaluwarsa','Terima dokumen|Pilih item|Periksa fisik|Isi jumlah dan ED|Simpan penerimaan|Rekonsiliasi stok','faktur PBF, obat fisik, nomor referensi, harga, jumlah, lokasi, batch, dan tanggal kedaluwarsa','Sistem mencatat stok masuk dan membentuk data batch yang akan dipakai kasir','dokumen penerimaan, kenaikan stok, batch baru, nilai pembelian, dan jejak pemasok','pemasok sah, kesesuaian pesanan-faktur-fisik, kondisi kemasan, suhu, batch, ED, harga, dan duplikasi faktur','Barang datang dari PBF; petugas mencocokkan surat jalan, menghitung kemasan, menolak kemasan rusak, memasukkan ED, menyimpan sekali, lalu memeriksa stok'],
'apotik_stok_opname':['Stok Opname Apotik','menyesuaikan stok sistem berdasarkan penghitungan fisik yang sah dan terdokumentasi','Bekukan pergerakan|Hitung fisik|Bandingkan sistem|Teliti selisih|Simpan penyesuaian|Setujui laporan','lembar hitung fisik, lokasi, item, jumlah sistem, jumlah fisik, alasan selisih, dan persetujuan','Sistem menghitung perbedaan lalu menulis penyesuaian stok dengan jejak operator','saldo stok terkoreksi, daftar selisih, alasan, waktu, dan referensi opname','pemisahan penghitung dan penyetuju, hitung ulang selisih besar, dan larangan menutup kehilangan tanpa investigasi','Tim menghentikan pergerakan rak, dua petugas menghitung, supervisor membandingkan angka, selisih dihitung ulang, alasan dicatat, lalu disimpan'],
'apotik_retur':['Retur Obat','mencatat pengembalian dari pembeli atau ke PBF dengan arah stok yang tepat','Identifikasi transaksi|Pilih jenis retur|Periksa kelayakan|Isi item dan alasan|Otorisasi|Simpan dan verifikasi','referensi transaksi atau faktur, item, jumlah, kondisi barang, pihak asal atau tujuan, dan alasan retur','Sistem menambah stok untuk retur penjualan yang layak atau mengurangi stok untuk retur ke PBF','dokumen retur, mutasi stok, nilai koreksi, alasan, dan jejak persetujuan','arah retur benar, kelayakan barang, jumlah tidak melebihi sumber, dan obat tertentu tidak kembali ke stok jual','Pelanggan mengembalikan obat sesuai kebijakan; petugas mencari transaksi, memeriksa segel, meminta persetujuan, memilih retur masuk, lalu memastikan mutasi'],
'apotik_narkotika':['Obat Terkendali','meninjau register narkotika dan psikotropika beserta pihak, dokter, jumlah, dan waktu','Pilih periode|Muat register|Periksa kelengkapan|Cocokkan dokumen|Investigasi selisih|Arsipkan laporan','periode, golongan obat, resep, identitas pembeli, alamat, dokter, jumlah, dan dokumen wajib','Sistem membaca jejak penyerahan obat terkendali yang dibuat saat transaksi','register kronologis dengan obat, golongan, jumlah, pihak, dokter, operator, dan keterangan','akses terbatas, kelengkapan identitas, resep sah, rekonsiliasi stok, dan pelaporan menurut regulasi','Apoteker memilih periode bulanan, mencocokkan setiap baris dengan resep fisik dan kartu stok, meneliti selisih, lalu mengarsipkan hasil'],
'apotik_laporan':['Laporan Apotik','menganalisis penjualan, pergerakan obat, dan risiko kedaluwarsa untuk pengawasan','Tentukan tujuan|Pilih periode|Muat data|Validasi filter|Analisis|Tindak lanjut','periode, lokasi, jenis laporan, horizon kedaluwarsa, dan kebutuhan analisis','Sistem mengagregasi transaksi yang sudah diposting dan menampilkan kuantitas, nilai, golongan, atau batch','indikator penjualan, rincian per obat, register, kedaluwarsa, dan dasar tindak lanjut','periode konsisten, status transaksi, lokasi, cutoff, rekonsiliasi kas dan stok, serta pemisahan laporan dari data mentah','Supervisor memilih periode shift, membandingkan total dengan penerimaan kas, meninjau obat terlaris dan batch berisiko, lalu mencatat tindak lanjut'],
'emedik_kasir':['Kasir Layanan Medis','menyelesaikan pembayaran tagihan layanan dan tindakan pasien','Cari kunjungan|Verifikasi pasien|Telaah tagihan|Terapkan penjamin|Terima pembayaran|Terbitkan bukti','nomor kunjungan, identitas pasien, rincian layanan, penjamin, deposit, dan metode pembayaran','Sistem menghitung kewajiban pasien sesudah penjamin atau deposit dan mencatat pembayaran','status tagihan, bukti pembayaran, saldo tersisa, pemakaian deposit, dan jejak kasir','pasien dan kunjungan benar, layanan disahkan, penjamin aktif, alokasi pembayaran, dan larangan pembayaran ganda','Pasien selesai berobat; kasir mencari kunjungan, mencocokkan identitas, menjelaskan rincian, menerapkan penjamin, menerima pembayaran, dan memastikan status lunas'],
'emedik_pendaftaran':['Pendaftaran Pasien','membuat booking atau kunjungan rawat jalan, rawat inap, maupun UGD secara tepat','Identifikasi pasien|Pilih jenis layanan|Lengkapi data|Pilih unit dan jadwal|Validasi|Daftarkan','identitas pasien, rekam medis bila ada, kontak, penjamin, rujukan, unit tujuan, dokter, dan jadwal','Sistem mencari pasien lama atau membuat hubungan pendaftaran lalu menghasilkan kunjungan','nomor booking atau kunjungan, unit tujuan, jadwal, penjamin, dan status antrean','pencegahan pasien ganda, verifikasi dua identitas, kegawatan UGD, rujukan, hak penjamin, dan persetujuan privasi','Pasien rawat jalan membawa identitas; petugas mencari rekam medis, mengonfirmasi tanggal lahir, memilih poli dan dokter, memeriksa penjamin, lalu mencetak nomor'],
'emedik_tagihan':['Tagihan Kunjungan','meninjau status seluruh komponen biaya pada satu kunjungan pasien','Cari kunjungan|Verifikasi pasien|Telaah komponen|Periksa status|Koreksi melalui sumber|Konfirmasi tagihan','nomor kunjungan, identitas pasien, layanan, tindakan, obat, kamar, diskon, penjamin, dan pembayaran','Sistem menggabungkan komponen biaya yang sudah diposting dari unit pelayanan','rincian tagihan, nilai bruto, penjamin, pembayaran, saldo, dan status','larangan mengubah layanan tanpa sumber klinis, pencegahan duplikasi, cutoff, otorisasi diskon, dan rekonsiliasi','Kasir menerima pertanyaan pasien; kunjungan dicari, setiap tindakan dijelaskan, komponen ganda ditelusuri ke unit sumber, kemudian tagihan dikonfirmasi'],
'emedik_deposit':['Deposit Pasien','menerima, menggunakan, dan memantau uang muka pasien secara dapat ditelusuri','Cari pasien|Periksa saldo|Pilih jenis mutasi|Isi nilai|Otorisasi|Simpan dan cetak','identitas pasien, nomor kunjungan, nilai deposit, metode pembayaran, referensi, tujuan penggunaan, dan bukti','Sistem menambah atau mengalokasikan saldo deposit serta mencatat mutasi','saldo deposit, riwayat mutasi, bukti penerimaan atau penggunaan, dan operator','identitas pasien, pemisahan uang antar pasien, larangan saldo negatif, otorisasi pengembalian, dan rekonsiliasi kas','Keluarga pasien rawat inap menyerahkan uang muka; kasir mencari pasien dengan dua identitas, menerima dana, mencetak bukti, lalu memeriksa saldo'],
'emedik_penjamin':['Penjamin & Asuransi','memelihara dan menggunakan informasi penjamin untuk menentukan tanggungan layanan','Pilih penjamin|Verifikasi kepesertaan|Periksa manfaat|Hubungkan kunjungan|Catat otorisasi|Pantau klaim','identitas peserta, penjamin, nomor polis, masa aktif, kelas, manfaat, rujukan, dan nomor otorisasi','Sistem menghubungkan penjamin dengan pasien atau kunjungan dan membantu perhitungan tanggungan','status penjamin, porsi tanggungan, kewajiban pasien, referensi otorisasi, dan dasar klaim','validitas kepesertaan, manfaat, pengecualian, kelas, rujukan, plafon, otorisasi, dan perlindungan data','Petugas memverifikasi kartu asuransi melalui kanal resmi, mencocokkan identitas dan masa aktif, merekam nomor otorisasi, lalu menghubungkannya ke kunjungan'],
'emedik_laporan':['Laporan Kasir Medis','memantau kunjungan, status pembayaran, penerimaan, dan saldo tagihan layanan medis','Tentukan periode|Pilih jenis laporan|Terapkan filter|Muat hasil|Rekonsiliasi|Tindak lanjuti','periode, unit, kasir, penjamin, status kunjungan, status pembayaran, dan kebutuhan rekonsiliasi','Sistem mengagregasi pendaftaran dan transaksi medis yang sudah tercatat','jumlah kunjungan, tagihan, pembayaran, piutang, rincian sesuai kewenangan, dan pengecualian','cutoff shift, pembatalan, refund, deposit, penjamin, transaksi tertunda, dan pembatasan ekspor data pasien','Supervisor menutup shift dengan memilih periode dan kasir, membandingkan penerimaan dengan kas, meneliti tagihan belum lunas, lalu mendokumentasikan selisih']};
var s=S[key]; if(!s){document.getElementById('ph-content').innerHTML='<div class="alert alert-warning">Artikel bantuan tidak ditemukan.</div>';return}
var emedik=key.indexOf('emedik_')===0;
document.getElementById('ph-title').textContent='Bantuan — '+s[0];
document.getElementById('ph-hero').src=ctx+'/assets/images/help/'+(emedik?'emedik':'apotik')+'-workflow.png';
var steps=s[2].split('|'),flow=document.getElementById('ph-flow');steps.forEach(function(x,i){var d=document.createElement('div');d.className='ph-step';d.innerHTML='<span class="ph-num">'+(i+1)+'</span>';d.appendChild(document.createTextNode(x));flow.appendChild(d);if(i<steps.length-1){var a=document.createElement('div');a.className='ph-arrow';a.textContent='→';flow.appendChild(a)}});
var sections=[
['Pengantar dan tujuan',s[0]+' merupakan bagian dari '+(emedik?'POS eMedik':'POS Apotik')+' yang dipakai untuk '+s[1]+'. Bantuan ini ditujukan kepada petugas operasional, supervisor, administrator, dan pemeriksa internal. Bacalah seluruh bagian sebelum menggunakan menu untuk pertama kali. Sistem membantu pencatatan, tetapi keputusan pelayanan tetap harus mengikuti kewenangan petugas, standar operasional fasilitas, peraturan kesehatan, dan hasil pemeriksaan dokumen sumber. Jangan memasukkan data contoh pada lingkungan produksi. Gunakan akun sendiri, jangan berbagi kata sandi, dan pastikan identitas pengguna yang tampil memang benar sebelum memproses data pasien, resep, obat, pembayaran, atau persediaan.'],
['Hasil yang diharapkan','Ketika pekerjaan selesai, sistem menghasilkan '+s[5]+'. Hasil dianggap benar apabila data sumber terbaca, identitas dan tanggal sesuai, angka diperiksa, tidak ada peringatan yang diabaikan, dan server menyatakan berhasil. Tombol simpan atau bayar tidak boleh ditekan berulang ketika jaringan lambat. Tunggu indikator proses dan baca pesan yang muncul. Jika hasil meragukan, jangan membuat transaksi pengganti sebelum memastikan transaksi pertama benar-benar gagal. Pemeriksaan dapat dilakukan melalui laporan, status tagihan, riwayat transaksi, kartu stok, atau konfirmasi supervisor sesuai menu.'],
['Persiapan sebelum mulai','Pastikan tanggal dan waktu perangkat benar, koneksi server stabil, aplikasi memakai versi yang disetujui, printer dan pemindai bila diperlukan siap, serta sesi login belum kedaluwarsa. Siapkan '+s[3]+'. Periksa kelengkapan, keterbacaan, nomor referensi, tanggal, pihak terkait, dan otorisasi. Untuk data klinis dan farmasi, hindari menyebut informasi pasien dengan suara keras atau memperlihatkan layar kepada pihak yang tidak berkepentingan. Pada perangkat bergerak jaga baterai dan jangan berpindah aplikasi ketika penyimpanan berjalan. Pada desktop manfaatkan layar lebar untuk membandingkan dokumen dengan data sistem.'],
['Memahami tampilan','Bagian judul menunjukkan menu aktif. Tombol Bantuan membuka panduan ini tanpa mengubah transaksi. Area filter atau pencarian menemukan data yang sudah ada; gunakan kata kunci cukup spesifik lalu cocokkan lebih dari satu identitas. Formulir memasukkan data baru atau koreksi yang diizinkan. Tabel menunjukkan hasil server dan dapat berubah setelah penyegaran. Hijau umumnya berhasil atau aman, kuning meminta perhatian, dan merah berarti kondisi harus dihentikan atau dikoreksi. Ikon tidak menggantikan teks; baca tooltip, label, serta pesan validasi sampai selesai.'],
['Alur kerja rinci','Alur utama menu ini adalah '+steps.join(' → ')+'. Mulailah dari tahap pertama dan jangan melompati pemeriksaan. '+s[4]+'. Pada setiap perpindahan tahap, bandingkan layar dengan dokumen sumber. Jika ada pilihan mirip, periksa kode, nama, tanggal lahir, satuan, lokasi, nomor kunjungan, nomor resep, nomor faktur, atau pembeda lain. Setelah mengisi form, baca kembali dari atas ke bawah. Koreksi sebelum menyimpan karena pembatalan setelah posting dapat memerlukan supervisor dan meninggalkan jejak audit.'],
['Cara pakai langkah demi langkah','Pertama, buka menu dan pastikan judulnya '+s[0]+'. Kedua, tentukan konteks seperti pasien, resep, lokasi, periode, pemasok, atau transaksi. Ketiga, cari dan pilih hanya hasil yang identitasnya telah diverifikasi. Keempat, lengkapi kolom wajib tanpa tanda sembarang. Kelima, periksa kuantitas, satuan, harga, diskon, penjamin, pembayaran, tanggal, dan catatan. Keenam, baca peringatan. Ketujuh, minta pemeriksaan kedua jika diwajibkan. Kedelapan, tekan aksi utama satu kali dan tunggu. Kesembilan, catat nomor hasil atau cetak bukti. Kesepuluh, buka laporan atau riwayat untuk memastikan hasil tercatat.'],
['Contoh penggunaan',s[7]+'. Petugas tidak langsung menekan Simpan. Petugas mencocokkan sumber data, mengecek hak akses, meninjau rincian, lalu menunggu respons berhasil. Bila pasien meminta perubahan setelah selesai, petugas tidak mengubah diam-diam. Gunakan koreksi, retur, pembatalan, atau penyesuaian resmi agar jejak awal dan alasan perubahan tetap dapat ditelusuri. Pendekatan ini melindungi pasien, petugas, persediaan, kas, dan laporan organisasi.'],
['Validasi dan kontrol keamanan','Kontrol terpenting adalah '+s[6]+'. Sistem juga menerapkan hak akses berbasis role. Ketiadaan tombol biasanya berarti role belum diizinkan, bukan kerusakan. Jangan memakai akun orang lain. Data sensitif hanya dibuka untuk pekerjaan. Sebelum meninggalkan meja, selesaikan proses dan kunci perangkat. Hindari tangkapan layar berisi identitas pasien. Jika bukti dikirim ke dukungan, samarkan nama, nomor identitas, alamat, telepon, dan informasi medis kecuali kanal serta kewenangannya telah ditetapkan.'],
['Penanganan peringatan dan kesalahan','Jika data tidak ditemukan, periksa ejaan, periode, lokasi, dan apakah sumber sudah dibuat. Jika akses ditolak, catat menu dan minta administrator meninjau role; jangan memanipulasi alamat. Jika stok atau batch tidak cukup, hentikan pelayanan item dan ikuti substitusi atau pengadaan. Jika jaringan terputus setelah simpan, jangan ulang sebelum memeriksa riwayat. Jika laporan berbeda, samakan periode, zona waktu, status, lokasi, dan filter. Simpan pesan kesalahan lengkap beserta waktu tanpa rahasia akun.'],
['Pemeriksaan setelah proses','Sesudah berhasil, cocokkan nomor referensi, waktu, operator, nilai, status, dan item. Untuk persediaan, bandingkan dengan kartu stok dan fisik. Untuk pembayaran, cocokkan dengan kas, mesin pembayaran, atau transfer. Untuk pendaftaran, pastikan kunjungan masuk ke unit benar. Untuk laporan, pastikan filter tercantum dan pahami bahwa hasil mencerminkan data yang diposting. Laporkan selisih pada hari yang sama. Jangan menghapus dokumen sumber sebelum masa retensi organisasi berakhir.'],
['Pengawasan harian dan serah terima','Pada awal shift periksa koneksi, lokasi, perangkat, status awal, dan transaksi tertunda. Selama shift jaga urutan nomor, periksa peringatan, dan pisahkan pekerjaan belum lengkap. Pada akhir shift tinjau transaksi berhasil, gagal, batal, retur, atau koreksi; bandingkan bukti fisik; lalu serahkan masalah terbuka secara tertulis. Supervisor meninjau pengecualian, nilai besar, perubahan master, dan kewenangan khusus. Jejak audit tidak boleh dibersihkan untuk membuat laporan tampak cocok.'],
['Praktik yang harus dihindari','Jangan memilih pasien atau item hanya karena urutan pertama. Jangan mengubah tanggal agar masuk periode tertentu. Jangan memecah transaksi untuk menghindari otorisasi. Jangan menyimpan kata sandi atau data kartu pada catatan. Jangan menutup aplikasi saat proses aktif. Jangan menganggap warna hijau cukup tanpa membaca nomor hasil. Jangan abaikan kedaluwarsa, LASA, obat terkendali, duplikasi, penjamin tidak aktif, atau ketidaksesuaian nilai. Jangan koreksi langsung basis data; gunakan fungsi aplikasi yang sah.'],
['Checklist verifikasi identitas','Minta pihak terkait menyebutkan identitas, jangan mengarahkan jawabannya. Cocokkan sedikitnya dua pengenal yang disetujui organisasi. Pastikan dokumen dan layar merujuk orang atau item yang sama. Untuk nama serupa, gunakan nomor unik, tanggal lahir, alamat, satuan, produsen, atau lokasi. Hentikan proses jika identitas tidak konsisten. Catat koreksi melalui prosedur resmi. Pemeriksaan identitas harus diulang setelah jeda panjang, perpindahan layar, pergantian operator, atau ketika dokumen baru ditambahkan.'],
['Checklist angka dan dokumen','Baca angka dari satuan terkecil sampai total. Perhatikan pemisah ribuan, desimal, satuan kemasan, kuantitas, tarif, diskon, pajak, tanggungan, dan saldo. Cocokkan nomor referensi serta tanggal. Pastikan dokumen belum pernah diproses. Untuk koreksi, tautkan referensi asal dan tulis alasan faktual. Bukti yang dicetak harus terbaca. Dokumen fisik dan digital disimpan sesuai kebijakan retensi. Selisih tidak boleh ditutup menggunakan transaksi fiktif atau akun penampung tanpa persetujuan.'],
['Checklist keselamatan dan privasi','Atur posisi layar agar tidak terlihat antrean. Panggil pasien dengan cara yang menjaga kerahasiaan. Jangan mendiskusikan diagnosis atau obat di area terbuka melebihi kebutuhan pelayanan. Periksa kewenangan sebelum membuka laporan rinci. Tutup artikel bantuan ketika kembali bekerja agar layar tidak menutupi peringatan transaksi. Bersihkan dokumen dari meja setelah selesai. Laporkan perangkat hilang, akun mencurigakan, atau akses yang terlalu luas segera kepada administrator dan penanggung jawab privasi.'],
['Ringkasan cepat','Urutan aman selalu sama: siapkan dokumen, pastikan konteks, cari data, verifikasi identitas, isi rincian, tinjau peringatan, simpan satu kali, periksa hasil, dan dokumentasikan pengecualian. Gunakan diagram sebagai pengingat dan narasi sebagai acuan. Bila kondisi nyata tidak tercakup, hentikan proses pada titik aman dan minta keputusan supervisor atau tenaga klinis berwenang. Kecepatan penting, tetapi keselamatan pasien, keutuhan stok, kebenaran kas, perlindungan data, dan jejak audit selalu lebih utama.']];
var content=document.getElementById('ph-content'),all='';sections.forEach(function(sec){var box=document.createElement('section');box.className='ph-section';var h=document.createElement('h3');h.textContent=sec[0];var p=document.createElement('p');p.textContent=sec[1];box.appendChild(h);box.appendChild(p);content.appendChild(box);all+=' '+sec[0]+' '+sec[1]});var wc=all.trim().split(/\s+/).length;document.getElementById('ph-count').textContent=wc.toLocaleString('id-ID')+' kata';
})();
</script>
