<%-- @generated by generate_new_jsp_scaffold.py
Source: src/ais/action/master/helper/generic/AmbilDataSiswaDariSiswaBanyak.java
Generated: 2026-08-06T18:20:20Z
Safe service-adapter scaffold. Implement data access in a Java service layer, not directly in this JSP.
--%>
<%@ page language="java" contentType="application/json; charset=UTF-8" pageEncoding="UTF-8" %>
<%
request.setAttribute("nuiServiceModule", "helper");
request.setAttribute("nuiServicePage", "generic/ambil_data_siswa_dari_siswa_banyak");
request.setAttribute("nuiServiceTitle", "Ambil Data Siswa Dari Siswa Banyak");
request.setAttribute("nuiServiceType", "academic");
request.setAttribute("nuiServiceSourceClass", "AmbilDataSiswaDariSiswaBanyak");
request.setAttribute("nuiServiceSourcePackage", "ais.action.master.helper.generic");
request.setAttribute("nuiServiceSourcePath", "src/ais/action/master/helper/generic/AmbilDataSiswaDariSiswaBanyak.java");
request.setAttribute("nuiServiceMethods", new String[]{"render", "onEvent", "display", "onSearchDefault", "setEventListener", "getEventListener"});
request.setAttribute("nuiServiceEntities", new String[]{"Siswa"});
%>
<jsp:include page="/WEB-INF/new/_shared/services/dispatcher.jsp" />
