<%-- @generated by generate_new_jsp_scaffold.py
Source: src/ais/action/master/helper/generic/LiveStreamingPlayerWindow.java
Generated: 2026-08-06T18:20:20Z
Safe service-adapter scaffold. Implement data access in a Java service layer, not directly in this JSP.
--%>
<%@ page language="java" contentType="application/json; charset=UTF-8" pageEncoding="UTF-8" %>
<%
request.setAttribute("nuiServiceModule", "helper");
request.setAttribute("nuiServicePage", "generic/live_streaming_player");
request.setAttribute("nuiServiceTitle", "Live Streaming Player");
request.setAttribute("nuiServiceType", "list");
request.setAttribute("nuiServiceSourceClass", "LiveStreamingPlayerWindow");
request.setAttribute("nuiServiceSourcePackage", "ais.action.master.helper.generic");
request.setAttribute("nuiServiceSourcePath", "src/ais/action/master/helper/generic/LiveStreamingPlayerWindow.java");
request.setAttribute("nuiServiceMethods", new String[]{"simpanVideo", "onEvent", "run"});
request.setAttribute("nuiServiceEntities", new String[]{"VideoPertemuan"});
%>
<jsp:include page="/WEB-INF/new/_shared/services/dispatcher.jsp" />
