package ais.common.newui.kursus;
import java.io.File;import java.io.FileOutputStream;import java.io.InputStream;import java.util.ArrayList;import java.util.Calendar;import java.util.Date;import java.util.HashSet;import java.util.List;import java.util.Set;import org.apache.commons.io.IOUtils;import org.hibernate.Criteria;import org.hibernate.Session;import org.hibernate.Transaction;import org.hibernate.criterion.MatchMode;import org.hibernate.criterion.Order;import org.hibernate.criterion.Projections;import org.hibernate.criterion.Restrictions;import ais.common.Common;import ais.common.ConstantValues;import ais.database.hibernate.HibernateUtil;import ais.database.hibernate.StreamingHibernateUtil;import ais.database.model.Pegawai;import ais.database.model.Pertemuan;import ais.database.model.Tbmuser;import ais.database.model.Ujian;import ais.database.model.file.FileFotoLain;import ais.database.model.file.LampiranLain;import ais.database.model.kursus.KomponenDataProdukKursus;import ais.database.model.kursus.KomponenProdukKursus;import ais.database.model.library.Item;import ais.database.model.rab.SatuanKerja;
/** Port headless CRUD, lampiran, tutor, unit, serta agenda dari KomponenDataProdukKursusAction/helper. */
@SuppressWarnings({"rawtypes","unchecked"})public final class NewUiCourseComponentService{
 public static String typeForPage(String p){if("komponen_data_video".equals(p))return KomponenProdukKursus.VIDEO;if("komponen_data_buku".equals(p))return KomponenProdukKursus.BUKU;if("komponen_data_ebook".equals(p))return KomponenProdukKursus.EBOOK;if("komponen_data_latihan_soal".equals(p))return KomponenProdukKursus.LATIHAN_SOAL;if("komponen_data_ujian".equals(p))return KomponenProdukKursus.UJIAN;if("komponen_data_tatap_muka".equals(p))return KomponenProdukKursus.PEMBELAJARAN_TATAP_MUKA;if("komponen_data_jarak_jauh".equals(p))return KomponenProdukKursus.PEMBELAJARAN_JARAK_JAUH;if("komponen_data_ekstrakulikuler".equals(p))return KomponenProdukKursus.EKSTRA_KURIKULER;if("komponen_data_produk_kursus".equals(p))return null;throw new IllegalArgumentException("Halaman komponen kursus tidak dikenal.");}
 public Snapshot load(String type,String q,Long unitId,boolean active,int page,int size,Set<SatuanKerja>allowed){Session s=HibernateUtil.openSession();try{Snapshot o=new Snapshot();Criteria count=criteria(s,type,q,unitId,active,allowed,false);Number n=(Number)count.setProjection(Projections.rowCount()).uniqueResult();o.total=n==null?0:n.intValue();for(Object x:criteria(s,type,q,unitId,active,allowed,true).setFirstResult(Math.max(0,page)*size).setMaxResults(size).list())o.rows.add(row((KomponenDataProdukKursus)x));options(s,o,allowed);return o;}finally{s.close();}}
 public Row get(Long id,String type,Set<SatuanKerja>allowed){Session s=HibernateUtil.openSession();try{return row(require(s,id,type,allowed));}finally{s.close();}}
 public Long save(Input v,String type,Set<SatuanKerja>allowed,Tbmuser user){validate(v,type);Session s=HibernateUtil.openSession();Transaction tx=null;try{tx=s.beginTransaction();KomponenDataProdukKursus x=v.id==null?new KomponenDataProdukKursus():require(s,v.id,type,allowed);x.setKomponenProdukKursus(type);x.setKode(clean(v.code));x.setNama(clean(v.name));x.setKeterangan(clean(v.note));x.setHargaIkutDefault(Boolean.valueOf(v.defaultPrice));x.setHarga(Double.valueOf(v.price));x.setJumlahPertemuan(Integer.valueOf(v.meetings));x.setMulai(v.start==null?new Date():v.start);x.setDurasi(v.duration);x.setAktif(Boolean.valueOf(v.active));x.setBuku(v.itemId==null?null:(Item)s.get(Item.class,v.itemId));x.setUjian(v.examId==null?null:(Ujian)s.get(Ujian.class,v.examId));x.setSatuanKerja(unit(s,v.unitId,allowed));x.setTutor1(employee(s,v.tutor1));x.setTutor2(employee(s,v.tutor2));x.setTutor3(employee(s,v.tutor3));x.setTutor4(employee(s,v.tutor4));x.setTutor5(employee(s,v.tutor5));if(schedule(type))x.setStatusPertemuan(KomponenProdukKursus.PEMBELAJARAN_JARAK_JAUH.equals(type)?ConstantValues.DARING:ConstantValues.TATAP_MUKA);else x.setStatusPertemuan(null);stamp(x,user);s.saveOrUpdate(x);s.flush();tx.commit();return x.getId();}catch(RuntimeException e){rollback(tx);throw e;}finally{s.close();}}
 public void setActive(Long id,String type,boolean active,Set<SatuanKerja>allowed,Tbmuser user){Session s=HibernateUtil.openSession();Transaction tx=null;try{tx=s.beginTransaction();KomponenDataProdukKursus x=require(s,id,type,allowed);x.setAktif(Boolean.valueOf(active));stamp(x,user);s.update(x);s.flush();tx.commit();}catch(RuntimeException e){rollback(tx);throw e;}finally{s.close();}}
 public void remove(Long id,String type,Set<SatuanKerja>allowed,Tbmuser user){setActive(id,type,false,allowed,user);}
 public void attach(Long id,String type,String fileName,InputStream in,String link,Tbmuser user)throws Exception{if(!fileType(type))return;if(clean(link)!=null&&!safeLink(link))throw new IllegalArgumentException("Tautan lampiran hanya boleh menggunakan HTTP atau HTTPS.");Session c=HibernateUtil.openSession();try{require(c,id,type,null);}finally{c.close();}if(in!=null){File tmp=File.createTempFile("nui-course-component-",".upload");FileOutputStream out=null;try{out=new FileOutputStream(tmp);IOUtils.copyLarge(in,out);}finally{IOUtils.closeQuietly(out);}Session stream=StreamingHibernateUtil.getInstance().getSessionFactory().openSession();try{FileFotoLain.createFileFotoLain(user,stream,LampiranLain.class,false,id,KomponenDataProdukKursus.class.getName(),null,tmp,fileName);}finally{try{stream.close();}catch(Exception ignored){}tmp.delete();}}else if(clean(link)!=null){Session s=HibernateUtil.openSession();Transaction tx=null;try{tx=s.beginTransaction();LampiranLain l=LampiranLain.ambil(id,KomponenDataProdukKursus.class.getName());if(l==null)l=new LampiranLain();l.setRef(id);l.setJenis(KomponenDataProdukKursus.class.getName());l.setNama("Data / dokumen berupa link");l.setLink(link.trim());if(user!=null){l.setOleh(user.getUserNama());l.setOlehId(user.getUserId());}s.saveOrUpdate(l);s.flush();tx.commit();}catch(RuntimeException e){rollback(tx);throw e;}finally{s.close();}}else if(LampiranLain.ambil(id,KomponenDataProdukKursus.class.getName())==null)throw new IllegalArgumentException("File atau link "+type+" wajib diisi.");}
 public Long copy(Long id,String type,Set<SatuanKerja>allowed,Tbmuser user){Session s=HibernateUtil.openSession();Transaction tx=null;try{tx=s.beginTransaction();KomponenDataProdukKursus a=require(s,id,type,allowed),x=new KomponenDataProdukKursus();x.setKomponenProdukKursus(a.getKomponenProdukKursus());x.setKode(clean(a.getKode())==null?null:a.getKode()+"-COPY");x.setNama((clean(a.getNama())==null?"Komponen":a.getNama())+" (Salinan)");x.setKeterangan(a.getKeterangan());x.setHargaIkutDefault(a.getHargaIkutDefault());x.setHarga(a.getHarga());x.setJumlahPertemuan(a.getJumlahPertemuan());x.setMulai(a.getMulai());x.setDurasi(a.getDurasi());x.setAktif(Boolean.TRUE);x.setBuku(a.getBuku());x.setUjian(a.getUjian());x.setSatuanKerja(a.getSatuanKerja());x.setTutor1(a.getTutor1());x.setTutor2(a.getTutor2());x.setTutor3(a.getTutor3());x.setTutor4(a.getTutor4());x.setTutor5(a.getTutor5());x.setStatusPertemuan(a.getStatusPertemuan());stamp(x,user);s.save(x);s.flush();tx.commit();return x.getId();}catch(RuntimeException e){rollback(tx);throw e;}finally{s.close();}}
 public List<History> history(Long id,String type,Set<SatuanKerja>allowed){Session guard=HibernateUtil.openSession();try{require(guard,id,type,allowed);}finally{guard.close();}Session s=HibernateUtil.openSession();try{List<History>out=new ArrayList<History>();for(Object o:s.createSQLQuery("select a.rev,a.revtype,r.revtstmp,a.oleh,a.kode,a.nama,a.komponen_produk_kursus,a.harga,a.aktif,a.keterangan from new_audit.komponen_data_produk_kursus__audit a left join new_audit.revinfo r on r.rev=a.rev where a.id=:id order by a.rev desc").setLong("id",id.longValue()).list())out.add(new History((Object[])o));return out;}finally{s.close();}}
 public List<Meeting> meetings(Long id,String type,Set<SatuanKerja>allowed,boolean generate){if(!schedule(type))throw new IllegalArgumentException("Jenis komponen ini tidak mempunyai agenda pertemuan.");Session s=HibernateUtil.openSession();Transaction tx=null;try{KomponenDataProdukKursus x=require(s,id,type,allowed);if(generate){tx=s.beginTransaction();Calendar date=Calendar.getInstance();date.setTime(x.getMulai());for(int i=1;i<=x.getJumlahPertemuan();i++){Pertemuan p=(Pertemuan)s.createCriteria(Pertemuan.class).add(Restrictions.eq("komponenDataProdukKursus",x)).add(Restrictions.eq("pertemuanKe",Integer.valueOf(i))).setMaxResults(1).uniqueResult();if(p==null){p=new Pertemuan();p.setKomponenDataProdukKursus(x);p.setPertemuanKe(Integer.valueOf(i));p.setStatusPertemuan(KomponenProdukKursus.PEMBELAJARAN_JARAK_JAUH.equals(type)?ConstantValues.DARING:ConstantValues.TATAP_MUKA);p.setTanggal(date.getTime());p.setTopik("Agenda materi \""+x.getNama()+"\"");p.setWaktuMulai(Common.timeFormat2.get().format(date.getTime()));p.setWaktuSelesai(Common.timeFormat2.get().format(date.getTime()));p.setAktif(Boolean.TRUE);s.save(p);}date.add(Calendar.WEEK_OF_YEAR,1);}s.flush();tx.commit();}List<Meeting>out=new ArrayList<Meeting>();for(Object o:s.createCriteria(Pertemuan.class).add(Restrictions.eq("komponenDataProdukKursus",x)).add(Restrictions.or(Restrictions.isNull("aktif"),Restrictions.eq("aktif",true))).addOrder(Order.asc("pertemuanKe")).list())out.add(new Meeting((Pertemuan)o));return out;}catch(RuntimeException e){rollback(tx);throw e;}finally{s.close();}}
 private Criteria criteria(Session s,String type,String q,Long unitId,boolean active,Set<SatuanKerja>a,boolean order){Criteria c=s.createCriteria(KomponenDataProdukKursus.class);if(type!=null)c.add(Restrictions.eq("komponenProdukKursus",type));if(active)c.add(Restrictions.or(Restrictions.isNull("aktif"),Restrictions.eq("aktif",true)));String z=clean(q);if(z!=null)c.add(Restrictions.or(Restrictions.ilike("nama",z,MatchMode.ANYWHERE),Restrictions.ilike("kode",z,MatchMode.ANYWHERE)));if(unitId!=null)c.add(Restrictions.eq("satuanKerja.id",unitId));else if(a!=null&&!a.isEmpty())c.add(Restrictions.or(Restrictions.isNull("satuanKerja"),Restrictions.in("satuanKerja",a)));else c.add(Restrictions.isNull("satuanKerja"));if(order)c.addOrder(Order.asc("kode")).addOrder(Order.asc("nama"));return c;}
 private void options(Session s,Snapshot o,Set<SatuanKerja>a){if(a!=null)for(SatuanKerja x:a)o.units.add(new Option(x.getId(),x.getNama()));for(Object x:s.createCriteria(Pegawai.class).add(Restrictions.or(Restrictions.isNull("aktif"),Restrictions.eq("aktif",true))).addOrder(Order.asc("nama")).setMaxResults(2000).list()){Pegawai p=(Pegawai)x;o.employees.add(new Option(p.getId(),p.getNama()));}for(Object x:s.createCriteria(Item.class).add(Restrictions.or(Restrictions.isNull("aktif"),Restrictions.eq("aktif",true))).addOrder(Order.asc("nama")).setMaxResults(2000).list()){Item p=(Item)x;o.items.add(new Option(p.getId(),p.getNama()));}for(Object x:s.createCriteria(Ujian.class).add(Restrictions.or(Restrictions.isNull("aktif"),Restrictions.eq("aktif",true))).addOrder(Order.asc("nama")).setMaxResults(2000).list()){Ujian p=(Ujian)x;o.exams.add(new Option(p.getId(),p.getNama()));}}
 private Row row(KomponenDataProdukKursus x){Row r=new Row();r.id=x.getId();r.code=x.getKode();r.name=x.getNama();r.note=x.getKeterangan();r.type=x.getKomponenProdukKursus();r.active=Boolean.TRUE.equals(x.getAktif());r.defaultPrice=Boolean.TRUE.equals(x.getHargaIkutDefault());r.price=x.getHarga();r.meetings=x.getJumlahPertemuan();r.start=x.getMulai();r.duration=x.getDurasi();if(x.getSatuanKerja()!=null){r.unitId=x.getSatuanKerja().getId();r.unit=x.getSatuanKerja().getNama();}if(x.getBuku()!=null){r.itemId=x.getBuku().getId();r.item=x.getBuku().getNama();}if(x.getUjian()!=null){r.examId=x.getUjian().getId();r.exam=x.getUjian().getNama();}Pegawai[]ps={x.getTutor1(),x.getTutor2(),x.getTutor3(),x.getTutor4(),x.getTutor5()};for(Pegawai p:ps)if(p!=null){r.tutorIds.add(p.getId());r.tutors.add(p.getNama());}LampiranLain l=null;try{l=LampiranLain.ambil(x.getId(),KomponenDataProdukKursus.class.getName());}catch(Exception ignored){}if(l!=null){r.attachmentName=l.getNama();String link=clean(l.getLink());r.attachmentUrl=link!=null&&safeLink(link)?link:l.getUrl();r.hasAttachment=clean(r.attachmentUrl)!=null;}return r;}
 private static KomponenDataProdukKursus require(Session s,Long id,String type,Set<SatuanKerja>a){KomponenDataProdukKursus x=id==null?null:(KomponenDataProdukKursus)s.get(KomponenDataProdukKursus.class,id);if(x==null)throw new IllegalArgumentException("Komponen kursus tidak ditemukan.");if(type!=null&&!type.equals(x.getKomponenProdukKursus()))throw new IllegalArgumentException("Jenis komponen tidak sesuai halaman.");if(x.getSatuanKerja()!=null&&a!=null){boolean ok=false;for(SatuanKerja u:a)if(u.getId().equals(x.getSatuanKerja().getId()))ok=true;if(!ok)throw new IllegalArgumentException("Komponen berada di luar akses satuan kerja.");}return x;}
 private static SatuanKerja unit(Session s,Long id,Set<SatuanKerja>a){if(id==null)return null;if(a!=null)for(SatuanKerja x:a)if(id.equals(x.getId()))return(SatuanKerja)s.get(SatuanKerja.class,id);throw new IllegalArgumentException("Satuan kerja berada di luar akses.");}private static Pegawai employee(Session s,Long id){return id==null?null:(Pegawai)s.get(Pegawai.class,id);}private static void validate(Input v,String t){if(t==null)throw new IllegalArgumentException("Jenis komponen wajib dipilih.");if((KomponenProdukKursus.BUKU.equals(t)||KomponenProdukKursus.EBOOK.equals(t))&&v.itemId==null)throw new IllegalArgumentException("Buku wajib dipilih.");if((KomponenProdukKursus.UJIAN.equals(t)||KomponenProdukKursus.LATIHAN_SOAL.equals(t))&&v.examId==null)throw new IllegalArgumentException("Ujian wajib dipilih.");if(!KomponenProdukKursus.BUKU.equals(t)&&!KomponenProdukKursus.EBOOK.equals(t)&&!KomponenProdukKursus.UJIAN.equals(t)&&!KomponenProdukKursus.LATIHAN_SOAL.equals(t)&&clean(v.name)==null)throw new IllegalArgumentException("Nama wajib diisi.");if(schedule(t)&&(v.meetings<1||v.start==null))throw new IllegalArgumentException("Jumlah dan tanggal mulai pertemuan wajib diisi.");}private static boolean schedule(String t){return KomponenProdukKursus.PEMBELAJARAN_TATAP_MUKA.equals(t)||KomponenProdukKursus.PEMBELAJARAN_JARAK_JAUH.equals(t)||KomponenProdukKursus.EKSTRA_KURIKULER.equals(t);}private static boolean fileType(String t){return KomponenProdukKursus.VIDEO.equals(t)||KomponenProdukKursus.EBOOK.equals(t);}private static boolean safeLink(String v){String x=clean(v);return x!=null&&(x.toLowerCase().startsWith("http://")||x.toLowerCase().startsWith("https://"));}private static void stamp(KomponenDataProdukKursus x,Tbmuser u){if(u!=null){x.setOleh(u.getUserNama());x.setOlehId(u.getUserId());}}private static void rollback(Transaction t){if(t!=null)try{t.rollback();}catch(Exception ignored){}}private static String clean(String v){return v==null||v.trim().length()==0?null:v.trim();}
 /**
  * Tipe implementasi bersarang {@link Input} milik {@link NewUiCourseComponentService}. Kelas ini memberi nama
  * pada state atau perilaku lokal agar tanggung jawabnya tidak tersebar sebagai blok anonim.
  *
  * <p><b>Scope:</b> tipe bersifat {@code static}; instance tidak menangkap object {@link
  * NewUiCourseComponentService}. Dependensi yang diperlukan harus diberikan secara eksplisit agar aman
  * digunakan dan diuji.</p>
  * <p>Kontrak yang tampak dari deklarasi ini meliputi state utama: {@code Long id}, {@code Long itemId}, {@code
  * Long examId}, {@code Long unitId}, {@code Long tutor1}, {@code Long tutor2}, {@code Long tutor3}, {@code
  * Long tutor4}. Aturan bisnis bersama tetap berada pada kelas induk atau service yang dipanggilnya.</p>
  *
  * @see NewUiCourseComponentService
  */
 public static final class Input{public Long id,itemId,examId,unitId,tutor1,tutor2,tutor3,tutor4,tutor5;public String code,name,note;public boolean active=true,defaultPrice=true;public double price;public int meetings=10;public Date start,duration;}
 /**
  * Pembawa data/helper lokal milik {@link NewUiCourseComponentService} untuk snapshot. Tipe ini mengelompokkan
  * nilai antara agar perhitungan atau rendering tidak memakai array/map tanpa kontrak yang jelas.
  *
  * <p><b>Scope:</b> tipe bersifat {@code static}; instance tidak menangkap object {@link
  * NewUiCourseComponentService}. Dependensi yang diperlukan harus diberikan secara eksplisit agar aman
  * digunakan dan diuji.</p>
  * <p>Kontrak yang tampak dari deklarasi ini meliputi state utama: {@code int total}, {@code List rows}, {@code
  * List units}, {@code List employees}, {@code List items}, {@code List exams}. Aturan bisnis bersama tetap
  * berada pada kelas induk atau service yang dipanggilnya.</p>
  *
  * @see NewUiCourseComponentService
  */
 public static final class Snapshot{public int total;public final List<Row>rows=new ArrayList<Row>();public final List<Option>units=new ArrayList<Option>(),employees=new ArrayList<Option>(),items=new ArrayList<Option>(),exams=new ArrayList<Option>();}
 /**
  * Pembawa data/helper lokal milik {@link NewUiCourseComponentService} untuk option. Tipe ini mengelompokkan
  * nilai antara agar perhitungan atau rendering tidak memakai array/map tanpa kontrak yang jelas.
  *
  * <p><b>Scope:</b> tipe bersifat {@code static}; instance tidak menangkap object {@link
  * NewUiCourseComponentService}. Dependensi yang diperlukan harus diberikan secara eksplisit agar aman
  * digunakan dan diuji.</p>
  * <p>Kontrak yang tampak dari deklarasi ini meliputi state utama: {@code Long id}, {@code String label}.
  * Aturan bisnis bersama tetap berada pada kelas induk atau service yang dipanggilnya.</p>
  *
  * @see NewUiCourseComponentService
  */
 public static final class Option{public final Long id;public final String label;Option(Long i,String l){id=i;label=l;}}
 /**
  * Pembawa data/helper lokal milik {@link NewUiCourseComponentService} untuk row. Tipe ini mengelompokkan nilai
  * antara agar perhitungan atau rendering tidak memakai array/map tanpa kontrak yang jelas.
  *
  * <p><b>Scope:</b> tipe bersifat {@code static}; instance tidak menangkap object {@link
  * NewUiCourseComponentService}. Dependensi yang diperlukan harus diberikan secara eksplisit agar aman
  * digunakan dan diuji.</p>
  * <p>Kontrak yang tampak dari deklarasi ini meliputi state utama: {@code Long id}, {@code Long unitId}, {@code
  * Long itemId}, {@code Long examId}, {@code String code}, {@code String name}, {@code String note}, {@code
  * String type}. Aturan bisnis bersama tetap berada pada kelas induk atau service yang dipanggilnya.</p>
  *
  * @see NewUiCourseComponentService
  */
 public static final class Row{public Long id,unitId,itemId,examId;public String code,name,note,type,unit,item,exam,attachmentName,attachmentUrl;public boolean active,defaultPrice,hasAttachment;public double price;public int meetings;public Date start,duration;public final List<Long>tutorIds=new ArrayList<Long>();public final List<String>tutors=new ArrayList<String>();}
 /**
  * Tipe implementasi bersarang {@link Meeting} milik {@link NewUiCourseComponentService}. Kelas ini memberi
  * nama pada state atau perilaku lokal agar tanggung jawabnya tidak tersebar sebagai blok anonim.
  *
  * <p><b>Scope:</b> tipe bersifat {@code static}; instance tidak menangkap object {@link
  * NewUiCourseComponentService}. Dependensi yang diperlukan harus diberikan secara eksplisit agar aman
  * digunakan dan diuji.</p>
  * <p>Kontrak yang tampak dari deklarasi ini meliputi state utama: {@code Long id}, {@code int number}, {@code
  * Date date}, {@code String start}, {@code String end}, {@code String topic}, {@code String status}. Aturan
  * bisnis bersama tetap berada pada kelas induk atau service yang dipanggilnya.</p>
  *
  * @see NewUiCourseComponentService
  */
 public static final class Meeting{public final Long id;public final int number;public final Date date;public final String start,end,topic,status;Meeting(Pertemuan p){id=p.getId();number=p.getPertemuanKe();date=p.getTanggal();start=p.getWaktuMulai();end=p.getWaktuSelesai();topic=p.getTopik();status=p.getStatusPertemuan()==null?"":p.getStatusPertemuan().getNama();}}
 /**
  * Tipe implementasi bersarang {@link History} milik {@link NewUiCourseComponentService}. Kelas ini memberi
  * nama pada state atau perilaku lokal agar tanggung jawabnya tidak tersebar sebagai blok anonim.
  *
  * <p><b>Scope:</b> tipe bersifat {@code static}; instance tidak menangkap object {@link
  * NewUiCourseComponentService}. Dependensi yang diperlukan harus diberikan secara eksplisit agar aman
  * digunakan dan diuji.</p>
  * <p>Kontrak yang tampak dari deklarasi ini meliputi state utama: {@code int revision}, {@code int type},
  * {@code long timestamp}, {@code String by}, {@code String code}, {@code String name}, {@code String
  * componentType}, {@code String note}. Aturan bisnis bersama tetap berada pada kelas induk atau service yang
  * dipanggilnya.</p>
  *
  * @see NewUiCourseComponentService
  */
 public static final class History{public final int revision,type;public final long timestamp;public final String by,code,name,componentType,note;public final double price;public final Boolean active;History(Object[]x){revision=((Number)x[0]).intValue();type=x[1]==null?0:((Number)x[1]).intValue();timestamp=x[2]==null?0:((Number)x[2]).longValue();by=x[3]==null?"":String.valueOf(x[3]);code=x[4]==null?"":String.valueOf(x[4]);name=x[5]==null?"":String.valueOf(x[5]);componentType=x[6]==null?"":String.valueOf(x[6]);price=x[7]==null?0:((Number)x[7]).doubleValue();active=x[8]==null?null:(Boolean)x[8];note=x[9]==null?"":String.valueOf(x[9]);}}
}
