<%-- @generated by generate_new_jsp_scaffold.py
Source: src/ais/action/report/format1/payroll/LaporanRekapPembayaranGajiSatuanKerja.java
Generated: 2026-08-06T18:20:20Z
Safe service-adapter scaffold. Implement data access in a Java service layer, not directly in this JSP.
--%>
<%@ page language="java" contentType="application/json; charset=UTF-8" pageEncoding="UTF-8" %>
<%
request.setAttribute("nuiServiceModule", "root/report");
request.setAttribute("nuiServicePage", "format1/payroll/laporan_rekap_pembayaran_gaji_satuan_kerja");
request.setAttribute("nuiServiceTitle", "Laporan Rekap Pembayaran Gaji Satuan Kerja");
request.setAttribute("nuiServiceType", "report");
request.setAttribute("nuiServiceSourceClass", "LaporanRekapPembayaranGajiSatuanKerja");
request.setAttribute("nuiServiceSourcePackage", "ais.action.report.format1.payroll");
request.setAttribute("nuiServiceSourcePath", "src/ais/action/report/format1/payroll/LaporanRekapPembayaranGajiSatuanKerja.java");
request.setAttribute("nuiServiceMethods", new String[]{"onEvent", "onCetak", "run"});
request.setAttribute("nuiServiceEntities", new String[]{"CaraPembayaranGaji", "PembayaranGajiPunyaPegawai", "ItemGaji"});
%>
<jsp:include page="/WEB-INF/new/_shared/services/dispatcher.jsp" />
