<%-- @generated by generate_new_jsp_scaffold.py
Source: src/ais/action/master/rab/PejabatAction.java
Generated: 2026-08-06T18:20:20Z
Safe service-adapter scaffold. Implement data access in a Java service layer, not directly in this JSP.
--%>
<%@ page language="java" contentType="application/json; charset=UTF-8" pageEncoding="UTF-8" %>
<%
request.setAttribute("nuiServiceModule", "rab");
request.setAttribute("nuiServicePage", "pejabat");
request.setAttribute("nuiServiceTitle", "Pejabat");
request.setAttribute("nuiServiceType", "finance");
request.setAttribute("nuiServiceSourceClass", "PejabatAction");
request.setAttribute("nuiServiceSourcePackage", "ais.action.master.rab");
request.setAttribute("nuiServiceSourcePath", "src/ais/action/master/rab/PejabatAction.java");
request.setAttribute("nuiServiceMethods", new String[]{"doBeforeCompose", "doAfterCompose", "onEvent", "render", "onAdd", "onSave", "initCriteria", "onSearchDefault"});
request.setAttribute("nuiServiceEntities", new String[]{"Pejabat", "Dosen", "Guru", "JenisJabatan"});
%>
<jsp:include page="/WEB-INF/new/_shared/services/dispatcher.jsp" />
