<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ page import="java.text.SimpleDateFormat" %><%@ page import="java.util.List" %>
<%@ page import="ais.common.newui.menu.NewUiDashboardUtilityService" %><%@ page import="ais.common.newui.menu.NewUiDashboardUtilityService.OnlineUserInfo" %><%@ page import="ais.common.newui.menu.NewUiDashboardUtilityService.CustomerContact" %>
<%!
private String nuiToolbarH(Object value){if(value==null)return "";return String.valueOf(value).replace("&","&amp;").replace("<","&lt;").replace(">","&gt;").replace("\"","&quot;").replace("'","&#39;");}
%>
<%
List<OnlineUserInfo> nuiToolbarOnline=NewUiDashboardUtilityService.onlineUsers();
List<CustomerContact> nuiToolbarContacts=NewUiDashboardUtilityService.customerServices();
Number nuiToolbarAccess=NewUiDashboardUtilityService.accessCount();Number nuiToolbarOnlineCount=NewUiDashboardUtilityService.onlineCount();
SimpleDateFormat nuiToolbarLoginFormat=new SimpleDateFormat("dd-MM-yyyy HH:mm:ss");
%>
<button type="button" class="nui-icon-btn" data-nui-dialog-open="nuiShellOnlineDialog" aria-label="Pengguna online" title="Pengguna online"><i class="fa-solid fa-users nui-fa-icon" aria-hidden="true"></i><span class="nui-badge"><%=nuiToolbarH(nuiToolbarOnlineCount)%></span></button>
<%if(!nuiToolbarContacts.isEmpty()){%><button type="button" class="nui-icon-btn" data-nui-dialog-open="nuiShellCustomerDialog" aria-label="Layanan pengguna" title="Layanan pengguna"><i class="fa-solid fa-headset nui-fa-icon" aria-hidden="true"></i></button><%}%>
<dialog id="nuiShellOnlineDialog" class="nui-dashboard-dialog"><header><div><small>Sumber existing: UserOnlineCounter dan SecurityFilter.dataOnline</small><h2>Daftar Pengguna Online</h2></div><button type="button" class="nui-icon-btn" data-nui-dialog-close aria-label="Tutup">×</button></header><div class="nui-dashboard-summary"><span>Akses 23 jam: <strong><%=nuiToolbarH(nuiToolbarAccess)%></strong></span><span>Login aktif: <strong><%=nuiToolbarH(nuiToolbarOnlineCount)%></strong></span></div><div class="nui-table-wrap"><table class="nui-table"><thead><tr><th>Nama</th><th>Jenis pengguna</th><th>Unit</th><th>Sub Unit</th><th>Waktu Login</th></tr></thead><tbody><%if(nuiToolbarOnline.isEmpty()){%><tr><td colspan="5">Belum ada pengguna online.</td></tr><%}for(int nuiToolbarI=0;nuiToolbarI<nuiToolbarOnline.size();nuiToolbarI++){OnlineUserInfo info=nuiToolbarOnline.get(nuiToolbarI);%><tr><td><%=nuiToolbarH(info.getName())%></td><td><%=nuiToolbarH(info.getRole())%></td><td><%=nuiToolbarH(info.getUnit())%></td><td><%=nuiToolbarH(info.getSubUnit())%></td><td><%=info.getLogin()==null?"":nuiToolbarH(nuiToolbarLoginFormat.format(info.getLogin()))%></td></tr><%}%></tbody></table></div></dialog>
<%if(!nuiToolbarContacts.isEmpty()){%><dialog id="nuiShellCustomerDialog" class="nui-dashboard-dialog nui-customer-dialog"><header><div><small>Sumber existing: tabel CustomerService aktif</small><h2>Layanan Pengguna</h2></div><button type="button" class="nui-icon-btn" data-nui-dialog-close aria-label="Tutup">×</button></header><div class="nui-customer-grid"><%for(int nuiToolbarC=0;nuiToolbarC<nuiToolbarContacts.size();nuiToolbarC++){CustomerContact contact=nuiToolbarContacts.get(nuiToolbarC);String phone=contact.getInternationalPhone();%><article class="nui-card nui-card-pad"><small><%=nuiToolbarH(contact.getGroup())%></small><strong><%=nuiToolbarH(contact.getPerson().length()==0?contact.getPhone():contact.getPerson())%></strong><span><%=nuiToolbarH(contact.getPhone())%></span><div><a class="nui-btn" target="_blank" rel="noopener" href="https://web.whatsapp.com/send?phone=<%=nuiToolbarH(phone)%>&amp;text=Halo.."><i class="fa-brands fa-whatsapp"></i> WhatsApp</a><a class="nui-btn" href="tel:<%=nuiToolbarH(phone)%>"><i class="fa-solid fa-phone"></i> Telepon</a></div></article><%}%></div></dialog><%}%>
