<%-- @generated by generate_new_jsp_scaffold.py
Source: src/ais/action/master/akunting/helper/DpcTransferStatusHelper.java
Generated: 2026-08-06T18:20:20Z
This JSP contains presentation metadata only. Keep business logic in Java services.
--%>
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%
request.setAttribute("nuiModule", "akunting");
request.setAttribute("nuiModuleLabel", "Akuntansi");
request.setAttribute("nuiPage", "helper/dpc_transfer_status_helper");
request.setAttribute("nuiPageTitle", "Dpc Transfer Status Helper");
request.setAttribute("nuiPageType", "finance");
request.setAttribute("nuiPageDescription", "Keuangan untuk Akuntansi. Transaksi, status, rekonsiliasi, detail, dan audit keuangan.");
request.setAttribute("nuiSourceClass", "DpcTransferStatusHelper");
request.setAttribute("nuiSourcePackage", "ais.action.master.akunting.helper");
request.setAttribute("nuiSourcePath", "src/ais/action/master/akunting/helper/DpcTransferStatusHelper.java");
request.setAttribute("nuiSourceKind", "class");
request.setAttribute("nuiSourceExtends", "");
request.setAttribute("nuiSourceImplements", "");
request.setAttribute("nuiSourceMethods", new String[]{"dari"});
request.setAttribute("nuiEntityCandidates", new String[]{});
%>
<jsp:include page="/WEB-INF/new/_shared/ui/page.jsp" />
