package ais.common.newui.akunting;
import java.util.HashMap;import java.util.Map;
import java.util.ArrayList;import java.util.Date;import java.util.List;import org.hibernate.Criteria;import org.hibernate.Session;import org.hibernate.Transaction;import org.hibernate.criterion.MatchMode;import org.hibernate.criterion.Order;import org.hibernate.criterion.Projections;import org.hibernate.criterion.Restrictions;import ais.database.hibernate.HibernateUtil;import ais.database.model.Tbmuser;import ais.database.model.akunting.DaftarPengajuanTransfer;import ais.database.model.akunting.Transitori;
/** Port headless TransitoriAction: monitoring, repair relasi balik, dan catatan inline. */
@SuppressWarnings({"rawtypes","unchecked"})public final class NewUiTransitoriService{
 public Snapshot load(String q,Date start,Date end,boolean activeOnly,boolean waiting,boolean submitted,boolean transferred,int page,int size){Session s=HibernateUtil.openSession();try{Criteria all=criteria(s,q,start,end,activeOnly);List values=all.addOrder(Order.desc("id")).list();Map<Long,Boolean>flags=transferFlags(s);Snapshot out=new Snapshot();List<Row> rows=new ArrayList<Row>();for(Object o:values){Transitori v=(Transitori)o;String status=status(v,flags.get(v.getId()));if(!waiting&&!submitted&&!transferred||waiting&&"WAITING".equals(status)||submitted&&"SUBMITTED".equals(status)||transferred&&"TRANSFERRED".equals(status)){rows.add(new Row(v,status));if("WAITING".equals(status))out.waiting++;else if("SUBMITTED".equals(status))out.submitted++;else out.transferred++;}}out.total=rows.size();int from=Math.min(out.total,Math.max(0,page)*size),to=Math.min(out.total,from+size);out.rows.addAll(rows.subList(from,to));return out;}finally{s.close();}}
 public void updateNote(Long id,String note,Tbmuser user){Session s=HibernateUtil.openSession();Transaction tx=null;try{tx=s.beginTransaction();Transitori v=(Transitori)s.get(Transitori.class,id);if(v==null)throw new IllegalArgumentException("Transitori tidak ditemukan.");v.setKeterangan(clean(note));stamp(v,user);s.update(v);repair(s,v);s.flush();tx.commit();}catch(RuntimeException e){rollback(tx);throw e;}finally{s.close();}}
 public int repairLinks(){Session s=HibernateUtil.openSession();Transaction tx=null;try{tx=s.beginTransaction();List values=s.createCriteria(Transitori.class).list();int n=0;for(Object o:values)if(repair(s,(Transitori)o))n++;s.flush();tx.commit();return n;}catch(RuntimeException e){rollback(tx);throw e;}finally{s.close();}}
 private boolean repair(Session s,Transitori v){DaftarPengajuanTransfer d=v.getDaftarPengajuanTransfer();if(d!=null&&d.getTransitoriData()==null){d.setTransitoriData(v);s.update(d);return true;}return false;}
 private Criteria criteria(Session s,String q,Date start,Date end,boolean active){Criteria c=s.createCriteria(Transitori.class,"t").createAlias("daftarPengajuanTransfer","d",Criteria.LEFT_JOIN);if(start!=null)c.add(Restrictions.ge("d.waktu",start));if(end!=null)c.add(Restrictions.le("d.waktu",new Date(end.getTime()+86399999L)));if(active)c.add(Restrictions.or(Restrictions.isNull("aktif"),Restrictions.eq("aktif",Boolean.TRUE)));String x=clean(q);if(x!=null)c.add(Restrictions.or(Restrictions.ilike("d.kode",x,MatchMode.ANYWHERE),Restrictions.or(Restrictions.ilike("d.nama",x,MatchMode.ANYWHERE),Restrictions.ilike("nama",x,MatchMode.ANYWHERE))));return c;}
 /** Model lama memaksa getter transfer=true; gunakan snapshot kolom melalui property Hibernate bukan getter mutatif. */
 private Map<Long,Boolean>transferFlags(Session s){Map<Long,Boolean>m=new HashMap<Long,Boolean>();List rows=s.createSQLQuery("select id, transfer from akunting.transitori").list();for(Object o:rows){Object[]x=(Object[])o;m.put(Long.valueOf(String.valueOf(x[0])),x[1]==null?Boolean.FALSE:(Boolean)x[1]);}return m;}private String status(Transitori v,Boolean transfer){if(v.getProsesTransitori()==null)return"WAITING";return Boolean.TRUE.equals(transfer)?"TRANSFERRED":"SUBMITTED";}
 private static void stamp(Transitori v,Tbmuser u){if(u!=null){v.setOleh(u.getUserNama());v.setOlehId(u.getUserId());}}private static String clean(String v){return v==null||v.trim().length()==0?null:v.trim();}private static void rollback(Transaction t){if(t!=null)try{t.rollback();}catch(Exception ignored){}}
 public static final class Snapshot{public final List<Row>rows=new ArrayList<Row>();public int total,waiting,submitted,transferred;}
 public static final class Row{public final Long id,processId,transferProcessId,sopId;public final String code,name,note,status,processCode,account,bank,accountName,accountNumber,sop;public final Date time;public final double amount;public final boolean sourceMissing,active;Row(Transitori v,String st){id=v.getId();name=v.getNama();note=v.getKeterangan();status=st;active=v.getAktif();processId=v.getProsesTransitori()==null?null:v.getProsesTransitori().getId();processCode=v.getProsesTransitori()==null?"":v.getProsesTransitori().getNama();DaftarPengajuanTransfer d=v.getDaftarPengajuanTransfer();sourceMissing=d==null;code=d==null?v.getKode():d.getKode();time=d==null?null:d.getWaktu();amount=d==null||d.getNominal()==null?0:d.getNominal();account=d==null||d.getAkun()==null?"":d.getAkun().getKode()+" - "+d.getAkun().getNama();bank=d==null||d.getBankSumber()==null?"":d.getBankSumber().getNama();accountName=d==null?"":d.getAtasNamaSumber();accountNumber=d==null?"":d.getNoRekSumber();transferProcessId=d==null||d.getProsesTransfer()==null?null:d.getProsesTransfer().getId();sopId=d==null||d.getDisposisiSop()==null?null:d.getDisposisiSop().getId();sop=d==null||d.getDisposisiSop()==null?"":d.getDisposisiSop().getKeterangan();}}
}
