package ais.database.model.file;

// Generated Apr 16, 2010 2:27:16 PM by Hibernate Tools 3.2.4.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.sql.Blob;
import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.Session;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;
import org.hibernate.annotations.NotFound;
import org.hibernate.annotations.NotFoundAction;
import org.hibernate.criterion.Projections;
import org.hibernate.criterion.Restrictions;
import org.hibernate.envers.Audited;
import org.hibernate.envers.NotAudited;

import ais.common.Common;
import ais.database.hibernate.StreamingHibernateUtil;
import ais.database.model.BiodataCalonMahasiswa;
import ais.database.model.Konfigurasi;
import ais.ui.util.MyMessageboxConfig;

/**
 * Bank generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Entity(
    dynamicInsert = true,
    dynamicUpdate = true
)
@Audited
@Table(schema = "public", name = "lampiran_lain_biodata_calon_mahasiswa")
public class LampiranLainBiodataCalonMahasiswa extends FileFotoLain {
	private String lokasiSimpan;

	public String getLokasiSimpan() {
		return lokasiSimpan;
	}

	public void setLokasiSimpan(String lokasiSimpan) {
		this.lokasiSimpan = lokasiSimpan;
	}

	public static final String TRANSKRIP_NILAI = "Transkrip Nilai";
	public static final String IJAZAH = "Ijazah";
	public static final String KTP = "Ktp";

	public static final String BUKTI_BAYAR_PENDAFTARAN = "Bukti Bayar Pendaftaran";
	public static final String BUKTI_BAYAR_DAFTAR_ULANG = "Bukti Bayar Daftar Ulang";

	public static final String LAMPIRAN_1 = "Lampiran ke-1";
	public static final String LAMPIRAN_2 = "Lampiran ke-2";
	public static final String LAMPIRAN_3 = "Lampiran ke-3";
	public static final String LAMPIRAN_4 = "Lampiran ke-4";
	public static final String LAMPIRAN_5 = "Lampiran ke-5";
	public static final String LAMPIRAN_6 = "Lampiran ke-6";
	public static final String LAMPIRAN_7 = "Lampiran ke-7";
	public static final String LAMPIRAN_8 = "Lampiran ke-8";
	public static final String LAMPIRAN_9 = "Lampiran ke-9";
	public static final String LAMPIRAN_10 = "Lampiran ke-10";

	@Override
	public String ambilJenis() {
		return jenis;
	}

	public static boolean checkLampiran(BiodataCalonMahasiswa biodataCalonMahasiswa) throws Exception {
		Session streamingSession = StreamingHibernateUtil.getInstance().currentSession();

		int foto = (biodataCalonMahasiswa.getPaket() == null || biodataCalonMahasiswa.getPaket().getWajibUploadFoto())
				? (((Number) streamingSession.createCriteria(FotoBiodataCalonMahasiswa.class)
						.setProjection(Projections.rowCount())
						.add(Restrictions.eq("biodataCalonMahasiswa", biodataCalonMahasiswa.getId())).setMaxResults(1)
						.uniqueResult()).intValue())
				: 1;

		int ijazah = 1;
		int nilai = 1;
		int ktp = 1;
		int lampiran_1 = 1;
		int lampiran_2 = 1;
		int lampiran_3 = 1;
		int lampiran_4 = 1;
		int lampiran_5 = 1;
		int lampiran_6 = 1;
		int lampiran_7 = 1;
		int lampiran_8 = 1;
		int lampiran_9 = 1;
		int lampiran_10 = 1;

		if (Common.getKonfigurasi("calon_mahasiswa_tidak_perlu_upload_ijazah", Konfigurasi.AKTIF).getNilai()
				.equals(Konfigurasi.TIDAK_AKTIF)) {
			ijazah = ((Number) streamingSession.createCriteria(LampiranLainBiodataCalonMahasiswa.class)
					.setProjection(Projections.rowCount())
					.add(Restrictions.eq("jenis", LampiranLainBiodataCalonMahasiswa.IJAZAH))
					.add(Restrictions.eq("biodataCalonMahasiswa", biodataCalonMahasiswa.getId())).setMaxResults(1)
					.uniqueResult()).intValue();
		}

		if (Common.getKonfigurasi("calon_mahasiswa_tidak_perlu_upload_nilai", Konfigurasi.AKTIF).getNilai()
				.equals(Konfigurasi.TIDAK_AKTIF)) {
			nilai = ((Number) streamingSession.createCriteria(LampiranLainBiodataCalonMahasiswa.class)
					.setProjection(Projections.rowCount())
					.add(Restrictions.eq("jenis", LampiranLainBiodataCalonMahasiswa.TRANSKRIP_NILAI))
					.add(Restrictions.eq("biodataCalonMahasiswa", biodataCalonMahasiswa.getId())).setMaxResults(1)
					.uniqueResult()).intValue();
		}

		if (Common.getKonfigurasi("calon_mahasiswa_tidak_perlu_upload_ktp", Konfigurasi.AKTIF).getNilai()
				.equals(Konfigurasi.TIDAK_AKTIF)) {
			ktp = ((Number) streamingSession.createCriteria(LampiranLainBiodataCalonMahasiswa.class)
					.setProjection(Projections.rowCount())
					.add(Restrictions.eq("jenis", LampiranLainBiodataCalonMahasiswa.KTP))
					.add(Restrictions.eq("biodataCalonMahasiswa", biodataCalonMahasiswa.getId())).setMaxResults(1)
					.uniqueResult()).intValue();
		}

		Konfigurasi konfigurasiUpload = Common.getKonfigurasi("calon_mahasiswa_upload_lampiran_1",
				Konfigurasi.TIDAK_AKTIF);
		String keteranganInfo1 = "";
		if (konfigurasiUpload.getNilai().equals(Konfigurasi.AKTIF)) {
			lampiran_1 = ((Number) streamingSession.createCriteria(LampiranLainBiodataCalonMahasiswa.class)
					.setProjection(Projections.rowCount())
					.add(Restrictions.eq("jenis", LampiranLainBiodataCalonMahasiswa.LAMPIRAN_1))
					.add(Restrictions.eq("biodataCalonMahasiswa", biodataCalonMahasiswa.getId())).setMaxResults(1)
					.uniqueResult()).intValue();
			keteranganInfo1 = konfigurasiUpload.getInfo1();
		}

		konfigurasiUpload = Common.getKonfigurasi("calon_mahasiswa_upload_lampiran_2", Konfigurasi.TIDAK_AKTIF);
		String keteranganInfo2 = "";
		if (konfigurasiUpload.getNilai().equals(Konfigurasi.AKTIF)) {
			lampiran_2 = ((Number) streamingSession.createCriteria(LampiranLainBiodataCalonMahasiswa.class)
					.setProjection(Projections.rowCount())
					.add(Restrictions.eq("jenis", LampiranLainBiodataCalonMahasiswa.LAMPIRAN_2))
					.add(Restrictions.eq("biodataCalonMahasiswa", biodataCalonMahasiswa.getId())).setMaxResults(1)
					.uniqueResult()).intValue();
			keteranganInfo2 = konfigurasiUpload.getInfo1();
		}

		konfigurasiUpload = Common.getKonfigurasi("calon_mahasiswa_upload_lampiran_3", Konfigurasi.TIDAK_AKTIF);
		String keteranganInfo3 = "";
		if (konfigurasiUpload.getNilai().equals(Konfigurasi.AKTIF)) {
			lampiran_3 = ((Number) streamingSession.createCriteria(LampiranLainBiodataCalonMahasiswa.class)
					.setProjection(Projections.rowCount())
					.add(Restrictions.eq("jenis", LampiranLainBiodataCalonMahasiswa.LAMPIRAN_3))
					.add(Restrictions.eq("biodataCalonMahasiswa", biodataCalonMahasiswa.getId())).setMaxResults(1)
					.uniqueResult()).intValue();
			keteranganInfo3 = konfigurasiUpload.getInfo1();
		}

		konfigurasiUpload = Common.getKonfigurasi("calon_mahasiswa_upload_lampiran_4", Konfigurasi.TIDAK_AKTIF);
		String keteranganInfo4 = "";
		if (konfigurasiUpload.getNilai().equals(Konfigurasi.AKTIF)) {
			lampiran_4 = ((Number) streamingSession.createCriteria(LampiranLainBiodataCalonMahasiswa.class)
					.setProjection(Projections.rowCount())
					.add(Restrictions.eq("jenis", LampiranLainBiodataCalonMahasiswa.LAMPIRAN_4))
					.add(Restrictions.eq("biodataCalonMahasiswa", biodataCalonMahasiswa.getId())).setMaxResults(1)
					.uniqueResult()).intValue();
			keteranganInfo4 = konfigurasiUpload.getInfo1();
		}

		konfigurasiUpload = Common.getKonfigurasi("calon_mahasiswa_upload_lampiran_5", Konfigurasi.TIDAK_AKTIF);
		String keteranganInfo5 = "";
		if (konfigurasiUpload.getNilai().equals(Konfigurasi.AKTIF)) {
			lampiran_5 = ((Number) streamingSession.createCriteria(LampiranLainBiodataCalonMahasiswa.class)
					.setProjection(Projections.rowCount())
					.add(Restrictions.eq("jenis", LampiranLainBiodataCalonMahasiswa.LAMPIRAN_5))
					.add(Restrictions.eq("biodataCalonMahasiswa", biodataCalonMahasiswa.getId())).setMaxResults(1)
					.uniqueResult()).intValue();
			keteranganInfo5 = konfigurasiUpload.getInfo1();
		}

		konfigurasiUpload = Common.getKonfigurasi("calon_mahasiswa_upload_lampiran_6", Konfigurasi.TIDAK_AKTIF);
		String keteranganInfo6 = "";
		if (konfigurasiUpload.getNilai().equals(Konfigurasi.AKTIF)) {
			lampiran_6 = ((Number) streamingSession.createCriteria(LampiranLainBiodataCalonMahasiswa.class)
					.setProjection(Projections.rowCount())
					.add(Restrictions.eq("jenis", LampiranLainBiodataCalonMahasiswa.LAMPIRAN_6))
					.add(Restrictions.eq("biodataCalonMahasiswa", biodataCalonMahasiswa.getId())).setMaxResults(1)
					.uniqueResult()).intValue();
			keteranganInfo6 = konfigurasiUpload.getInfo1();
		}

		konfigurasiUpload = Common.getKonfigurasi("calon_mahasiswa_upload_lampiran_7", Konfigurasi.TIDAK_AKTIF);
		String keteranganInfo7 = "";
		if (konfigurasiUpload.getNilai().equals(Konfigurasi.AKTIF)) {
			lampiran_7 = ((Number) streamingSession.createCriteria(LampiranLainBiodataCalonMahasiswa.class)
					.setProjection(Projections.rowCount())
					.add(Restrictions.eq("jenis", LampiranLainBiodataCalonMahasiswa.LAMPIRAN_7))
					.add(Restrictions.eq("biodataCalonMahasiswa", biodataCalonMahasiswa.getId())).setMaxResults(1)
					.uniqueResult()).intValue();
			keteranganInfo7 = konfigurasiUpload.getInfo1();
		}

		konfigurasiUpload = Common.getKonfigurasi("calon_mahasiswa_upload_lampiran_8", Konfigurasi.TIDAK_AKTIF);
		String keteranganInfo8 = "";
		if (konfigurasiUpload.getNilai().equals(Konfigurasi.AKTIF)) {
			lampiran_8 = ((Number) streamingSession.createCriteria(LampiranLainBiodataCalonMahasiswa.class)
					.setProjection(Projections.rowCount())
					.add(Restrictions.eq("jenis", LampiranLainBiodataCalonMahasiswa.LAMPIRAN_8))
					.add(Restrictions.eq("biodataCalonMahasiswa", biodataCalonMahasiswa.getId())).setMaxResults(1)
					.uniqueResult()).intValue();
			keteranganInfo8 = konfigurasiUpload.getInfo1();
		}

		konfigurasiUpload = Common.getKonfigurasi("calon_mahasiswa_upload_lampiran_9", Konfigurasi.TIDAK_AKTIF);
		String keteranganInfo9 = "";
		if (konfigurasiUpload.getNilai().equals(Konfigurasi.AKTIF)) {
			lampiran_9 = ((Number) streamingSession.createCriteria(LampiranLainBiodataCalonMahasiswa.class)
					.setProjection(Projections.rowCount())
					.add(Restrictions.eq("jenis", LampiranLainBiodataCalonMahasiswa.LAMPIRAN_9))
					.add(Restrictions.eq("biodataCalonMahasiswa", biodataCalonMahasiswa.getId())).setMaxResults(1)
					.uniqueResult()).intValue();
			keteranganInfo9 = konfigurasiUpload.getInfo1();
		}

		konfigurasiUpload = Common.getKonfigurasi("calon_mahasiswa_upload_lampiran_10", Konfigurasi.TIDAK_AKTIF);
		String keteranganInfo10 = "";
		if (konfigurasiUpload.getNilai().equals(Konfigurasi.AKTIF)) {
			lampiran_10 = ((Number) streamingSession.createCriteria(LampiranLainBiodataCalonMahasiswa.class)
					.setProjection(Projections.rowCount())
					.add(Restrictions.eq("jenis", LampiranLainBiodataCalonMahasiswa.LAMPIRAN_10))
					.add(Restrictions.eq("biodataCalonMahasiswa", biodataCalonMahasiswa.getId())).setMaxResults(1)
					.uniqueResult()).intValue();
			keteranganInfo10 = konfigurasiUpload.getInfo1();
		}

		StreamingHibernateUtil.getInstance().closeSession();

		if (foto == 0) {
			MyMessageboxConfig.show("Foto harus di upload", "Informasi", MyMessageboxConfig.OK,
					MyMessageboxConfig.INFORMATION);
			return false;
		}

		if (ijazah == 0) {
			MyMessageboxConfig.show("Ijazah/surat keterangan lulus harus di upload", "Informasi", MyMessageboxConfig.OK,
					MyMessageboxConfig.INFORMATION);
			return false;
		}

		if (nilai == 0) {
			MyMessageboxConfig.show("Transkrip nilai harus di upload", "Informasi", MyMessageboxConfig.OK,
					MyMessageboxConfig.INFORMATION);
			return false;
		}

		if (ktp == 0) {
			MyMessageboxConfig.show("KTP / Kartu Pelajar harus di upload", "Informasi", MyMessageboxConfig.OK,
					MyMessageboxConfig.INFORMATION);
			return false;
		}

		if (lampiran_1 == 0) {
			MyMessageboxConfig.show(keteranganInfo1 + " harus di upload", "Informasi", MyMessageboxConfig.OK,
					MyMessageboxConfig.INFORMATION);
			return false;
		}

		if (lampiran_2 == 0) {
			MyMessageboxConfig.show(keteranganInfo2 + " harus di upload", "Informasi", MyMessageboxConfig.OK,
					MyMessageboxConfig.INFORMATION);
			return false;
		}

		if (lampiran_3 == 0) {
			MyMessageboxConfig.show(keteranganInfo3 + " harus di upload", "Informasi", MyMessageboxConfig.OK,
					MyMessageboxConfig.INFORMATION);
			return false;
		}

		if (lampiran_4 == 0) {
			MyMessageboxConfig.show(keteranganInfo4 + " harus di upload", "Informasi", MyMessageboxConfig.OK,
					MyMessageboxConfig.INFORMATION);
			return false;
		}

		if (lampiran_5 == 0) {
			MyMessageboxConfig.show(keteranganInfo5 + " harus di upload", "Informasi", MyMessageboxConfig.OK,
					MyMessageboxConfig.INFORMATION);
			return false;
		}

		if (lampiran_6 == 0) {
			MyMessageboxConfig.show(keteranganInfo6 + " harus di upload", "Informasi", MyMessageboxConfig.OK,
					MyMessageboxConfig.INFORMATION);
			return false;
		}

		if (lampiran_7 == 0) {
			MyMessageboxConfig.show(keteranganInfo7 + " harus di upload", "Informasi", MyMessageboxConfig.OK,
					MyMessageboxConfig.INFORMATION);
			return false;
		}

		if (lampiran_8 == 0) {
			MyMessageboxConfig.show(keteranganInfo8 + " harus di upload", "Informasi", MyMessageboxConfig.OK,
					MyMessageboxConfig.INFORMATION);
			return false;
		}

		if (lampiran_9 == 0) {
			MyMessageboxConfig.show(keteranganInfo9 + " harus di upload", "Informasi", MyMessageboxConfig.OK,
					MyMessageboxConfig.INFORMATION);
			return false;
		}

		if (lampiran_10 == 0) {
			MyMessageboxConfig.show(keteranganInfo10 + " harus di upload", "Informasi", MyMessageboxConfig.OK,
					MyMessageboxConfig.INFORMATION);
			return false;
		}

		return true;
	}

	/**
	 * 
	 */
	private static final long serialVersionUID = 2463821577548439808L;
	private Long id;
	private String oleh;
	private String olehId;

	public String getOlehId() {
		return olehId;
	}

	public void setOlehId(String olehId) {if (olehId == null || olehId.trim().isEmpty()) {return;}
		this.olehId = olehId;
	}

	public void setOleh(String oleh) {if (oleh == null || oleh.trim().isEmpty()) {return;}
		this.oleh = oleh;
	}

	public String getOleh() {
		return oleh;
	}

	@javax.persistence.PreUpdate protected void onUpdate() { ais.database.hibernate.AuditTimestampInterceptor.ubah(this);}     private Date tanggal_dirubah = ais.ui.util.WaktuUtil.getDate();

	public void setTanggal_dirubah(Date tanggal_dirubah) {
		this.tanggal_dirubah = tanggal_dirubah;
	}

	@Temporal(TemporalType.TIMESTAMP)
	public Date getTanggal_dirubah() {
		return tanggal_dirubah;
	}

	public String toString() {
		return nama;
	}

	private String nama;
	private String keterangan;
	private Long biodataCalonMahasiswa;
	private Blob foto;
	private String jenis;
	private LampiranLainBiodataCalonMahasiswa copyDari;
	private String link;

	public LampiranLainBiodataCalonMahasiswa() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", insertable = false, unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "nama", nullable = false, length = 255)
	public String getNama() {
		if (copyDari != null) {
			nama = copyDari.nama;
		} else if (!getLink().isEmpty()) {
			nama = "Berupa link file";
		}
		return this.nama == null ? null : this.nama.trim();
	}

	public void setNama(String nama) {
		this.nama = nama;
	}

	@Column(name = "keterangan", nullable = true)
	public String getKeterangan() {
		return this.keterangan;
	}

	public void setKeterangan(String keterangan) {
		this.keterangan = keterangan;
	}

	public void setFoto(Blob foto) {
		this.foto = foto;
	}

	@NotAudited
	public Blob getFoto() {
		return gdrive != null && !gdrive.trim().isEmpty() ? null : (foto != null ? foto : (copyDari == null ? null : copyDari.foto));
	}

	public void setBiodataCalonMahasiswa(Long biodataCalonMahasiswa) {
		this.biodataCalonMahasiswa = biodataCalonMahasiswa;
	}

	@Column(name = "biodata_calon_mahasiswa", nullable = true)
	public Long getBiodataCalonMahasiswa() {
		return biodataCalonMahasiswa;
	}

	public String getJenis() {
		return jenis;
	}

	public void setJenis(String jenis) {
		this.jenis = jenis;
	}

	@ManyToOne(cascade = { CascadeType.PERSIST, CascadeType.MERGE })
	@Fetch(FetchMode.SELECT)
	@NotFound(action = NotFoundAction.IGNORE)
	@JoinColumn(name = "copy_dari", nullable = true)
	public LampiranLainBiodataCalonMahasiswa getCopyDari() {
		return copyDari;
	}

	public void setCopyDari(LampiranLainBiodataCalonMahasiswa copyDari) {
		this.copyDari = copyDari;
	}

	private String gdrive;
	private String gdriveUsername;

	public String getGdrive() {
		if (copyDari != null) {
			gdrive = copyDari.gdrive;
		}
		String s = gdrive == null || gdrive.trim().isEmpty() ? retreive("gdrive") : gdrive;
		return s != null && !s.trim().isEmpty() ? s : gdrive;
	}

	public void setGdrive(String gdrive) {
		if (gdrive != null && !gdrive.trim().isEmpty()) {
			put(gdrive, "gdrive");
		}
		this.gdrive = gdrive;
	}

	public String getGdriveUsername() {
		if (copyDari != null) {
			gdriveUsername = copyDari.gdriveUsername;
		}
		return gdriveUsername;
	}

	public void setGdriveUsername(String gdriveUsername) {
		this.gdriveUsername = gdriveUsername;
	}

	@Override
	public Long ambilRef() {
		// TODO Auto-generated method stub
		return biodataCalonMahasiswa;
	}

	@SuppressWarnings("rawtypes")
	@Override
	public Class ambilClazz() {
		// TODO Auto-generated method stub
		return LampiranLainBiodataCalonMahasiswa.class;
	}

	public String getLink() {
		return link == null ? "" : link.trim();
	}

	public void setLink(String link) {
		this.link = link;
	}

	@Override
	public String ambilLink() {
		return getLink();
	}

	private String url;

	@Transient
	public String getUrl() {
		try {
			if (url == null && getId() != null) {
				url = createLinkUri();
			}
		} catch (Exception e) {
			e.printStackTrace(); ais.common.ErrorAuditUtil.record(e, "auto-audit src/ais/database/model/file/LampiranLainBiodataCalonMahasiswa.java:519");
		}
		return url;
	}

	public void setUrl(String url) {
		this.url = url;
	}
}
