<%-- @generated by generate_new_jsp_scaffold.py
Source: src/ais/action/report/helper/pdf/LaporanTranskipAkademikKonversiWindow.java
Generated: 2026-08-06T18:20:20Z
This JSP contains presentation metadata only. Keep business logic in Java services.
--%>
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%
request.setAttribute("nuiModule", "root/report");
request.setAttribute("nuiModuleLabel", "Pelaporan");
request.setAttribute("nuiPage", "helper/pdf/laporan_transkip_akademik_konversi");
request.setAttribute("nuiPageTitle", "Laporan Transkip Akademik Konversi");
request.setAttribute("nuiPageType", "report");
request.setAttribute("nuiPageDescription", "Laporan untuk Pelaporan. Filter, pratinjau, ekspor, dan histori pembuatan laporan.");
request.setAttribute("nuiSourceClass", "LaporanTranskipAkademikKonversiWindow");
request.setAttribute("nuiSourcePackage", "ais.action.report.helper.pdf");
request.setAttribute("nuiSourcePath", "src/ais/action/report/helper/pdf/LaporanTranskipAkademikKonversiWindow.java");
request.setAttribute("nuiSourceKind", "class");
request.setAttribute("nuiSourceExtends", "MyWindow");
request.setAttribute("nuiSourceImplements", "");
request.setAttribute("nuiSourceMethods", new String[]{"onEvent", "onTranskrip"});
request.setAttribute("nuiEntityCandidates", new String[]{"Staff"});
%>
<jsp:include page="/WEB-INF/new/_shared/ui/page.jsp" />
